### ISSUE TITLE
Add more alternatives to "Contacts & Calendar Synchronization"

### ISSUE THREAD

**Issue by m4rcs** [mail-in-a-box/mailinabox#1002]
I was wondering if it would be in favour if there are more alternatives listed on the "Contacts & Calendar Synchronization" page as [NextCloud](https://nextcloud.com/blog/nextcloud-offers-caldav-synchronizer-for-outlook-users/) has now an official syncing client for Outlook.

If this sounds interesting I will gladly prepare a pull request.

**Comment by jvolkenant** [comment]
have you tried the sync client with owncloud? If it supports caldav spec, it may work with Owncloud as well

**Comment by acs-ferreira** [comment]
See https://github.com/mail-in-a-box/mailinabox/issues/514 also

**Comment by msgerbs** [comment]
Why would you use an Outlook sync client for NextCloud to sync your contacts to Outlook? Outlook natively supports CalDav and will sync directly without need of another client.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
