### ISSUE TITLE
test domain justtesting.email doesn't exist

### ISSUE THREAD

**Issue by wsteitz** [mail-in-a-box/mailinabox#1003]
I tried to get a vagrant box running using the Vagrantfile provided in the repo. It seems to hook up the service on the justtesting.email domain. That domain is currently unowned.. Is this supposed to work or should we remove the justtesting.email domain?

(I think that we don't need to connect the vagrant box to the Internet to run some tests. For example the sovereign guys test email sending / receiving just fine without that.)

**Comment by JoshData** [comment]
I owned the domain but let it lapse. We should remove anything that still references it.
