### ISSUE TITLE
Spam problem

### ISSUE THREAD

**Issue by ponychicken** [mail-in-a-box/mailinabox#1004]
I have a problem of predominantely german language spam getting through the filter. Even though it has quite a lot of patterns and I have manually trained spam assassin (using sa-learn), it still comes through. Maybe someone has some suggestions on how to tackle this?

**Comment by razem-io** [comment]
I had the same problem. 1-4 spam e-mails came through per hour. What fixed it for me was an upgrade to the latest version and a restart. Since then it is nice and quiet again.

**Comment by ponychicken** [comment]
After more investigation it was a culmination of multiple factors:
1. Spam Assassin was setup to not check messages larger than 500kb, yet the spam I received was sometime up to 1MB (!!!)
2. An incorrectly forwarding email group, which forwarded a lot of spam, thereby defeating greylisting and DNS checks
3. A Bayes set which though that all german words are ham.
