### ISSUE TITLE
PHP Fatal Error during Active Sync

### ISSUE THREAD

**Issue by ubahmapk** [mail-in-a-box/mailinabox#1012]
This PHP error during ActiveSync is repeated consistently. Sanitized error message below:

"PHP Fatal error: require_once(): Failed opening required 'backend/combined/config.php' (include_path='.:/usr/share/php:/usr/share/pear:/usr/share/awl/inc') in /usr/local/lib/z-push/backend/combined/combined.php on line 53" while reading response header from upstream, client: 10.20.30.40, server: mail.maildomain.com, request: "POST /Microsoft-Server-ActiveSync?User=email_user%40maildomain.com&DeviceId=DEADBEAFDEADBEAF&DeviceType=Outlook&Cmd=Sync HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:"

This has occurred 114 times in the last 19 hours.

I'm running version 0.20 of mail-in-a-box

Please let me know if you have any other questions or if there is any other data I can provide.

Thank you! :-)

JM

**Comment by ubahmapk** [comment]
Forgot to include my version of Mail-in-a-box: v0.20

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
