### ISSUE TITLE
Merging Two Instances

### ISSUE THREAD

**Issue by martindale** [mail-in-a-box/mailinabox#1013]
If someone has two instances of Mail-in-a-Box running with say, one unique domain per, how might one merge those two instances into a single, managed, multi-domain instance?

**Comment by yodax** [comment]
This is going to be difficult to easily do. If you just have mail you could copy the mail directories over to one machine. Add a domain and the accounts should show up for you to activate. You will need to reset the password. 

You can also copy the owncloud directories of the users, however the calendar/contacts database is stored in the owncloud.db. These can't be migrated easily. This would be a manual action for the user to do I think.

**Comment by dieideeistgut** [comment]
Just out of curiosity & because i'm facing the same issue as @martindale in some weeks: would it make sense to archive the to-be-moved accounts on the outdated system before moving them to the new server instance? thanks!

**Comment by yodax** [comment]
That shouldn't matter, it just removes the user from the the local database. I would of course suggest verified backups when doing something like this.

**Comment by martindale** [comment]
@yodax I'm moving forward with the plan to merge two of my deployments; what directory explicitly contains the mail directories?  I can `rsync` these between boxes easily.  Should I migrate the domain + DNS before or after copying the data?

**Comment by yodax** [comment]
/home/user-data/mail contains the mail. Migrating the DNS/domain will take a while. My steps would be (I haven't tested this, so for important stuff like this do some research and don't trust a random stranger on the internet)

- Rsync all the data (initial copy)
- Shutdown postfix and dovecot on the source server
- Start migrating the domain/dns
- Rsync data again (with --delete to remove deleted items between the last sync, take special care not to remove the existing data on the destination server. So do this per user)
- Activate the domains on the new server
- Wait

I have probably forgotten something, but this should be the gist. Again can't stress this enough; make backups of both servers. Test that they work. Make sure you know what you are doing. Preferably set up two test hosts and try it out.
