### ISSUE TITLE
WebDav not allowed by nginx

### ISSUE THREAD

**Issue by jirislav** [mail-in-a-box/mailinabox#1016]
When I try to connect to WebDav at https://hostname/cloud/remote.pl, nginx returns 405 Not Allowed.

There might be another issues while connecting to ownCloud using WebDav that would be worth investigating.

**Comment by yodax** [comment]
Have you tried this url: https://domain/cloud/remote.php/webdav ?

**Comment by jirislav** [comment]
That works! Thanks for that! I see you've already changed the suggested URL to the correct one, so I'm closing this issue.
