### ISSUE TITLE
IP address selector for outgoing connections

### ISSUE THREAD

**Issue by tkorves** [mail-in-a-box/mailinabox#1018]
As we're using an IPv6 tunnel with a routed /64 network, we'd like to see a selection box within the admin interface to bind at least postfix to use this specific IP address for outgoing connections.

Problem which occurs: Postfix uses the first IP(v6) address attached to the outbound interface - which in our situation is the tunnels interface IP address (which doesn't have the correct reverse DNS mapping) and not one out of our routed network.

**Comment by jabbink** [comment]
Can't you change your used IPv6 in the config? https://github.com/mail-in-a-box/mailinabox/commit/77937df95509488d5a794cbf9d4f703af506ae6e#diff-2c91206d3285034a200b23d8c296b8e5R67

**Comment by msgerbs** [comment]
@jabbink I don't think that would stay between versions since that's set by the MIAB setup.

I'd be in favor of this as it seems like a relatively simple and non-breaking change, but I'm not sure how many people would ever actually use this.

**Comment by JoshData** [comment]
@jabbink is suggesting you change the PRIVATE_IPV6 setting by setting the environment variable prior to setup or changing it in /etc/mailinabox.conf and re-running setup.
