### ISSUE TITLE
Relative paths on rsync backup setup won't work

### ISSUE THREAD

**Issue by semente** [mail-in-a-box/mailinabox#1019]
When I try to setup rsync backup, if I put a relative path I get the not accurate message "need more than 2 values to unpack".

The path also must exist on destination, I think it is worth creating it automatically or put this info in the form, or the user will get the also not accurate message "Connection to rsync host failed".

**Comment by guyzmo** [comment]
cf your comment on [issue #717](https://github.com/mail-in-a-box/mailinabox/issues/717#issuecomment-264183198)

**Comment by guyzmo** [comment]
can you provide proper reproduceable inputs to replicate the issue?

as I'm guilty of the rsync patch, I'm happy to help solve this and come up with a fix 😉

**Comment by dieideeistgut** [comment]
There's a `--relative` parameter in rsync allowing the use of relative paths. Or am i wrong with this? Had serveral rsync-scripts where i had to use this param. There's also a `--no-relative` parameter.

**Comment by guyzmo** [comment]
@dieideeistgut well if that's *that* simple, we could easily detect whether a path is relative or not — with something like: `path.startswith('/')` — and add the option based on that?

Also, improving the error reporting is definitely a good idea.

**Comment by dieideeistgut** [comment]
Should be *that* simple (ツ) From [rsync manpage](https://download.samba.org/pub/rsync/rsync.html):

` -R, --relative              use relative path names`
`--no-implied-dirs       don't send implied dirs with --relative`

**Comment by semente** [comment]
Well, I don't think we need to use the `-R` argument. The following works just fine:

```
rsync /path/to/data/ to/relative/
```

I didn't know about this parameter but I guess it is for another thing or to force the use of relative in some situations. dunno...

In the case of relative paths, the error is in Python code. The inputs I tried are:

1. `./mailinabox`
2. `mailinabox`

And when I use `/path/to/backups/mailinbox`, if this path do not exist on destination I get an "Connection error" instead a more accurate feedback.

**Comment by guyzmo** [comment]
ok, that sounds like fair test samples. I'll try to have a look at it the sooner I can ☺

I'm pretty sure those are simple cases to catch and report properly.

**Comment by guyzmo** [comment]
ok, the issue is [at this line](https://github.com/mail-in-a-box/mailinabox/blob/master/management/backup.py#L396,L396):

```
	_, target_host, target_path = config['target'].split('//')
```

as it expects an URL looking like:

```
rsync://backup_user@domain.tld//path/to/backups
```

basically, I'm using here a trick where I get the parts of the URI using the double slashes as separator. Might be better off using `urlparse()` or something like that?

**Comment by guyzmo** [comment]
I just checked, if a single `/` is given, the path is considered as relative.

We got two choices, either:

1. support both paths (and change the `split('//')` thing into something better), or 
2. support only absolute paths and raise a meaningful error to tell the user to only use absolute paths.

@JoshData what'd be your preference?

**Comment by JoshData** [comment]
I haven't been following this issue closely but definitely replace the split with a proper URL parser.

**Comment by ixof** [comment]
#1035
