### ISSUE TITLE
roundcube.sqlite owned by root

### ISSUE THREAD

**Issue by cromulus** [mail-in-a-box/mailinabox#1023]
Hi!
On a fresh install, roundcube can't open the sqlite database because it is owned by root.

The fix is: `sudo chown www-data:www-data /home/user-data/mail/roundcube/roundcube.sqlite`

However, this should be part of the install script.

Thanks!

**Comment by JoshData** [comment]
Broken by #940 probably. Paging @electrickite .

**Comment by JoshData** [comment]
Thanks for the bug report! This is now released as v0.21b.

**Comment by JoshData** [comment]
(I mean the fix is now released.)
