### ISSUE TITLE
Rsync Backup: error message not helpful

### ISSUE THREAD

**Issue by nodomain** [mail-in-a-box/mailinabox#1033]
I am trying to set up rsync backup. I think all settings are correct, but nevertheless I get 
"Connection to rsync host failed". This does not help me at all.

* where can I find more detailed errors?
* RFE: please provide a more detailed error on the UI

**Comment by guyzmo** [comment]
could you tell what kind of values you're using? (not the exact matches, of course, but the closest lookalike)

**Comment by guyzmo** [comment]
As shown on #1019 there's a limitation on the path: you shall provide an absolute path to the directory target on the destination.

**Comment by nodomain** [comment]
I use
Server data.server.name
Path /home/mailbox-backup/backups/box.server.name
User mailbox-backup

This should be ok, shouldn't it?

**Comment by yodax** [comment]
Could you add a trailing slash ?

**Comment by guyzmo** [comment]
I just tested, it works with a trailing slash. I'm getting that error with an invalid hostname, username or a missing SSH key, though.

**Comment by guyzmo** [comment]
As a hint, you can lookup on the target host's logs: if you see a connection attempt from your mailinabox' server, your user or ssh's authorized_key setting is wrong, if you do not, your host is wrong.

**Comment by guyzmo** [comment]
If you want more information on what's wrong with your settings, you can always run:

```
sudo management/backup.py --verify
```

in your mailinabox application root.

**Comment by guyzmo** [comment]
About returning a more meaningful error message, it should be possible to extract some stuff out of the `listing` variable when [raising this exception](https://github.com/mail-in-a-box/mailinabox/blob/master/management/backup.py#L420,L420).

**Comment by guyzmo** [comment]
another test I just ran, if you launch mailinabox as standalone and not a service you'll get in the standard output:

* when given a wrong username or you forgot to add the ssh-key in your `authorized_keys` (by design you cannot tell those apart):

```
Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.0]
```

* wrong hostname:

```
ssh: connect to host X.Y.Z.T port 22: Network is unreachable
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.0]
```

or 

```
ssh: Could not resolve hostname domain.tld: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.0]
```

**Comment by nodomain** [comment]
It was a missing "s" at the imported ssh-key on the target host.

Now it says: Stop: unknown instance when running backup.py manually. Any ideas?

**Comment by nodomain** [comment]
Works, it was due to hitting Ctrl-C after invoking backup.py. After a reboot everything seems fine.

**Comment by guyzmo** [comment]
happy to have helped. Though I believe improving error reporting wouldn't be a bad thing, because it's clearly not obvious what's going wrong when it fails ☺
