### ISSUE TITLE
"The SSH server on this machine permits password-based login" despite correct SSHD

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#1038]
I have been trying to figure this out, and I did uncomment "PasswordAuthentication no" and all the usual things. I checked and it won't permit a login without my SSH key. So what can I do to get rid of the annoying thing? It doesn't show on my personal email server, but shows on my company's mail-in-a-box. They are both configured similar, so I am at the "hair pulling" stage at this point.

**Comment by yodax** [comment]
Could you check for a duplicate password line in the config? Apparently that is in new Digital Ocean configurations.

**Comment by josephbu** [comment]
Sounds the same as issue #990
