### ISSUE TITLE
E-mail bounced: Set up SPF records for your sending domain if you have not done so already.

### ISSUE THREAD

**Issue by louwers** [mail-in-a-box/mailinabox#1046]
```
Delivery to the following recipient failed permanently:

     robin.klantenservice@brandfield.nl

Technical details of permanent failure: 
Your email to group robin.klantenservice@brandfield.nl was rejected due to spam classification. To address this issue:

* Contact the owner of the group, who can choose to enable message moderation instead of bouncing these emails.
* Set up SPF records for your sending domain if you have not done so already.

Instructions for both steps can be found here: https://support.google.com/a/answer/168383.
```

An e-mail I sent got bouned. What does this mean? Is the e-mail server of the entity I'm trying to contact improperly configured or is there something I can do?

**Comment by biermeester** [comment]
You could start by visiting http://www.mail-tester.com/ and send the same mail that got bounced to the address they provide. They'll give you a nice report afterward, which will indicate if anything's wrong at your end.

**Comment by louwers** [comment]
Everything shows up green. Could it be that they just bounce everything that doesn't come from big email providers?

I'm contacting them, this probably has nothing to do with mail-in-a-box. Thanks @biermeester.
