### ISSUE TITLE
Dislike the "index.php" in the sharing URL of ownCloud

### ISSUE THREAD

**Issue by bogao** [mail-in-a-box/mailinabox#1047]
Can the new version of MIAB deliver a new nginx configuration so that the URL can look better?
![screenshot_20161221_001004](https://cloud.githubusercontent.com/assets/2892458/21357903/f67df070-c711-11e6-9f9c-3c15b733a757.jpg)

**Comment by jvolkenant** [comment]
This may be possible via https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/index_php_less_urls.html#configuration-steps

But if the old URL's stop working that would be a problem and having two urls would only complicate matters.

**Comment by bogao** [comment]
Those instructions are for Apache configuration. As far as I remember MIAB is using nginx, for which it is claimed that no extra configuration steps are required?

**Comment by azzamsa** [comment]
any update on this?

I've installed the latest version of MIAB, but nexcloud sharing URL still contains "index.php"

**Comment by JoshData** [comment]
If someone does the work to make the change and ensure it doesn't break any existing uses and users of Mail-in-a-Box, I would consider it, of course, but it seems unlikely that will happen.

**Comment by azzamsa** [comment]
Thanks for the response. I don't think I've that capability currently.

**Comment by Synchro** [comment]
Looking at [the config recommended in Nextcloud (16) docs](https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-nginx), there are quite a few differences from what's in MIAB (beyond `/cloud` vs `/nextcloud`). At a guess, I'd say the current MIAB config looks like an older config. Is there any particular reason not to copy that config as-is?

**Comment by JoshData** [comment]
> Is there any particular reason not to copy that config as-is?

That's not a question that can be answered without doing some work to compare it and research what each directive is for. If you ask a more specific question about it, I can try to answer.

**Comment by dumblob** [comment]
@Synchro did you find some time for comparison to decide whether the new configuration would solve the issue described in the very first post?
