### ISSUE TITLE
Custom DNS API - POST

### ISSUE THREAD

**Issue by realbuz** [mail-in-a-box/mailinabox#1049]
I'm trying to setup an automatic DNS update script on a Mikrotik router.  However the router does not support curl.  So we can't do POST or PUT commands.

It would be great if the customer dos API would allow this kind of script to update the dns records:

http://wiki.mikrotik.com/wiki/Dynamic_DNS_Update_Script_for_DNSoMatic.com

this example is for dnsomatic, however there are many more dynamic dos services that use the same kind of api.

in parallel I'm also trying to see if dnsomatic would be willing to add mailinabox in their supported list.

Thanks

Simon

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
