### ISSUE TITLE
Fail2Ban recidive jails IPs used by devices connecting via ActiveSync

### ISSUE THREAD

**Issue by nikksno** [mail-in-a-box/mailinabox#1050]
Ever since changing the way my phone connects to my miab server [imap/smtp to activesync], all the IPs it connects from get recidive jailed by Fail2Ban. I always have to `nano /etc/fail2ban/jail.d/mailinabox.conf` and add the IPs to the `ignoreip=` line. I have a lot of emails on my account [about 30k]. For comparison, my phone also connects [now too via activesync] to another account on another miab server with the same version, that only has about 100 mails, and this second server's Fail2Ban never recidive jails any of the IPs. Is there a way to fix this on IPs that successfully authenticate on an account?

Thank you!

**Comment by anoma** [comment]
Can you check the fail2ban log to see what triggers have been activated.

**Comment by nikksno** [comment]
Absolutely, yes, let me remove one of the IPs from the blacklist and as soon as it's jailed again I'll update you. Thank you!

**Comment by nikksno** [comment]
Here it is:

```
Chain fail2ban-dovecot (1 references)
target     prot opt source               destination         
REJECT     all  --  [my ip]          0.0.0.0/0            reject-with icmp-port-unreachable
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

I think I've seen it elsewhere than dovecot in the past, I'll keep an eye on it. I confirm no jails on the other server right now.

**Comment by yodax** [comment]
Could you grep the ip address from /var/log/fail2ban.log?

```
zgrep [ip] /var/log/fail2ban.log*
```

And execute these commands: 

```
fail2ban-client status
fail2ban-client status dovecot
```

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
