### ISSUE TITLE
External DNS issue

### ISSUE THREAD

**Issue by bogao** [mail-in-a-box/mailinabox#1054]
I don't think it reasonable to point the A records of my www.domain.name and domain.name to the box since I am only planning to use the domain name as a mailbox extension so I guess only MX records are required might be more reasonable then the current situation.
![screenshot_20170101_235027](https://cloud.githubusercontent.com/assets/2892458/21581854/2c4c6366-d07d-11e6-97ae-e2d858e969ee.png)

Beside that I notice the system check does not recognize my MX record has already been correctly set to the box's domain name.

![screenshot_20170101_235315](https://cloud.githubusercontent.com/assets/2892458/21581862/7f4c526a-d07d-11e6-9dae-87b26bc90646.png)

![screenshot_20170101_235505](https://cloud.githubusercontent.com/assets/2892458/21581870/c10dd2fa-d07d-11e6-909f-c4cd2a90040d.png)

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
