### ISSUE TITLE
Something unexpected went wrong: Error creating new cert :: Too many certificates already issued for exact set of domains:

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#1059]
I have my SSL/TLS expiring in 11 days but Mailinabox won't provision a new one... 

box.ganon.me, ganon.me, www.ganon.me

Something unexpected went wrong: Error creating new cert :: Too many certificates already issued for exact set of domains: box.ganon.me,ganon.me,www.ganon.me

Log:
Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
Reusing existing challenges for box.ganon.me.
The challenges for box.ganon.me have been accepted.
Reusing existing challenges for ganon.me.
The challenges for ganon.me have been accepted.
Reusing existing challenges for www.ganon.me.
The challenges for www.ganon.me have been accepted.
Generating a new certificate signing request.
Requesting a certificate.

**Comment by ChiefGyk** [comment]
Tried sudo mailinabox which didn't fix anything

**Comment by guyzmo** [comment]
usually that error happens when you've reached the API limit of letsencrypt. I'm not sure what is the cause, but letsencrypt enforces a grace period of a few days when you've reached that limit.

**Comment by ChiefGyk** [comment]
Well I don't know what could be causing it as it was working flawlessly on it's own. But others have mentioned the same as well recently so it seems as if we do in fact have a bug. https://discourse.mailinabox.email/t/lets-encrypt-failure-too-many-certificates-already-issued-for-exact-set-of-domains/1745

https://discourse.mailinabox.email/t/tls-certificate-auto-renewal/1795

https://discourse.mailinabox.email/t/tls-certificate-renewal-failing-with-lets-encrypt/1261

**Comment by ChiefGyk** [comment]
Is there any work around for this as I just created a brand new box just for this

**Comment by stan3** [comment]
You may have same issue as https://github.com/mail-in-a-box/mailinabox/issues/848 with "TypeError: must be X509, not ComparableX509".  I only saw this if running management/ssl_certificates.py on the console.

One workaround for the letsencrypt limit that seemed to work for me is to run management/ssl_certificates.py with a different set of domains to your original set (e.g. just box.domain)

**Comment by ChiefGyk** [comment]
Thanks @stan3 how do I run it with a different set of domains because I am still new SSL/TLS provisioning via Lets Encrypt

**Comment by stan3** [comment]
e.g. `sudo management/ssl_certificates.py ganon.me`

**Comment by ChiefGyk** [comment]
FIXED! Thanks @stan3 

`sudo service php5-fpm stop
sudo service postfix stop
sudo service dovecot stop
sudo management/ssl_certificates.py
 * Stopping Postfix Mail Transport Agent postfix
   ...done.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
stop: Unknown instance: 
dovecot start/running, process 13273
 * Reloading nginx configuration nginx
   ...done.
A TLS certificate was successfully installed for box.ganon.me, ganon.me, www.ganon.me.

sudo service php5-fpm start
sudo service postfix start
sudo service dovecot start
`
