### ISSUE TITLE
DNS CAA (RFC 6844) Support

### ISSUE THREAD

**Issue by TheRyanHowell** [mail-in-a-box/mailinabox#1066]
It would be great if you could add support for DNS CAA (RFC 6844), you just have to generate extra dns records/add support adding them manually.

Lets encrypt supports this standard fully, rejecting requests that don't comply with the CAA records.

NSD >4.0.1
```
example.com.	CAA	0 issue "letsencrypt.org"
example.com.	CAA	0 issuewild ";"
```
NSD <4.0.1
```
example.com.	TYPE257	\# 22 000569737375656C657473656E63727970742E6F7267
example.com.	TYPE257	\# 12 0009697373756577696C643B
```

**Comment by yodax** [comment]
I think this is a good idea in principle. The effect of CAA records now is limited, but it should grow.

When someone creates a PR for this it would need to take into account that not all certificates are issued via lets encrypt.

**Comment by justinmayer** [comment]
Support for custom CAA records was added in [version 0.23](
https://github.com/mail-in-a-box/mailinabox/blob/15583ec10d423e5273897de95924e69227d8046c/CHANGELOG.md#v023-may-30-2017). Consequently, I believe this issue can be closed.
