### ISSUE TITLE
LetsEncrypt renewal bug

### ISSUE THREAD

**Issue by nicholashead** [mail-in-a-box/mailinabox#1067]
Definitely seems like there is some bug regarding extending LE certs: https://discourse.mailinabox.email/t/lets-encrypt-failure-too-many-certificates-already-issued-for-exact-set-of-domains/1745/12?u=backpackhasjetz

I'm having the problem across two totally separate MIAB setups/domains. So it makes me think it must be a bug.

**Comment by cromulus** [comment]
For reference, here are two threads on the support forum:

https://discourse.mailinabox.email/t/tls-certificate-auto-renewal/1795/19

https://discourse.mailinabox.email/t/lets-encrypt-failure-too-many-certificates-already-issued-for-exact-set-of-domains/1745/12

**Comment by stan3** [comment]
This happened to me and I resolved it at the time by tweaking some of the python code and running management/ssl_certificates.py.  Now that I'm not having the problem it's hard to troubleshoot but I think it might be related to having the python3-openssl debian package and the pip3 package installed at the same time (this is mentioned in the link above).

**Comment by nicholashead** [comment]
@stan3 do you know what ssl package should be installed and which should be removed? what ssl package does mailinabox officially use?

**Comment by nicholashead** [comment]
Is there more information/debugging info I can provide to folks here, to help get this solved?

**Comment by nicholashead** [comment]
@stan3 also would be curious if you could remember/find what modifications you made to the code?

**Comment by cromulus** [comment]
@nicholashead What is the output of these two commands:
`dpkg --list` and `pip3 list`

**Comment by stan3** [comment]
@nicholashead seems like free_tls_certificate needs the pip3 installed version of pyOpenSSL and I'm assuming that gets installed as a dependency when the setup script calls pips3 install free_tls_certificate.  Not sure why python3-openssl would get installed

```
$ aptitude why python3-openssl
i   python3-flask    Depends    python3-werkzeug
i A python3-werkzeug Recommends python3-openssl
```

The modification I'd previously made to the code is described in https://github.com/mail-in-a-box/mailinabox/issues/848.

**Comment by jalogisch** [comment]
please check if this issue has the same background: https://github.com/mail-in-a-box/mailinabox/issues/1101#issuecomment-281026627

my problem is solved

**Comment by nicholashead** [comment]
I think what I ended up doing was manually pausing the daily attempts until the time window had passed, then turned it back on. It must have been a combination of wrong package versions and MIAB not handling the throttling requests properly? Anyway everything's dandy now.
