### ISSUE TITLE
DKIM and DMARC is failing for gmail

### ISSUE THREAD

**Issue by Aravin** [mail-in-a-box/mailinabox#1069]
I have DKIM verified domain for sending an email. But still, I am getting this error.

![image](https://cloud.githubusercontent.com/assets/4869265/21993791/ab3e730a-dc42-11e6-9ea1-9e5a4a36be20.png)

I am using a same domain name for more than 5 months.

Also, I am getting this error sometimes

```
host gmail-smtp-in.l.google.com[74.125.130.26] said:
    550-5.7.1 [139.59.13.177      12] Our system has detected that this message
    is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to
    Gmail, 550-5.7.1 this message has been blocked. Please visit 550-5.7.1
    https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1  for
    more information. u21si22238279plj.19 - gsmtp (in reply to end of DATA
    command)
```

Domain is verified on https://postmaster.google.com also.

**Comment by biermeester** [comment]
What does http://www.mail-tester.com/ tell you, when you send an email to the address they provide you?

**Comment by Aravin** [comment]
I am getting

![image](https://cloud.githubusercontent.com/assets/4869265/21995360/7fc48630-dc4a-11e6-9667-1b947486efe1.png)

### One issue:

Matches your server IP address (139.59.13.177) against 21 of the most common ipv4 blacklists.

**Comment by biermeester** [comment]
What blacklist(s) have your IP address in them? You should get it removed from those, even though I doubt that Gmail uses those lists for spam checking.

**Comment by Aravin** [comment]
@biermeester, any udpates?

**Comment by nicholashead** [comment]
@Aravin they already responded. Your IP address is on at least one blacklist. You'll need to remove yourself from the blacklist or change your servers IP.

**Comment by Aravin** [comment]
@nicholashead  and @biermeester See that link now: http://www.mail-tester.com/web-7mvax 10/10

Still I am facing same error.

**Comment by nicholashead** [comment]
@Aravin have you tried diagnosing with https://postmaster.google.com/ ?

**Comment by Aravin** [comment]
@nicholashead How to diagnose. I have already added & verified the domain in Postmaster.

**Comment by Aravin** [comment]
How to solve this issue? 

`DKIM:	NEUTRAL with domain null `

**Comment by Aravin** [comment]
Any updates?

**Comment by yodax** [comment]
I think you need to contact google. If the status checks are all green there isn't anything to be done that I can think of.

**Comment by Aravin** [comment]
oh @yodax It means I have to contact google/hotmail/yahoo to not mark my email as span?

**Comment by nicholashead** [comment]
@Aravin your IP is still listed under SORBS blacklist: 139.59.13.177 - http://www.sorbs.net/lookup.shtml

**Comment by Aravin** [comment]
It is new VPS server from DigitalOcean. I have not yet sent any mail!!!

**Comment by biermeester** [comment]
When you open a new VPS, they assign you one of their IP addresses. That same address might have been used before by some other VPS that sent spam, thus causing the blacklist registration.

**Comment by Aravin** [comment]
@biermeester I got it.

Is it the only reason? for DKIM & DMARC failure?

Created at:	Thu, Jan 19, 2017 at 11:26 PM (Delivered after 11 seconds)
To:	aravin@worldbases.com
Subject:	What is the status update?
SPF:	PASS with IP 74.201.154.111 Learn more
DKIM:	NEUTRAL with domain null Learn more
DMARC:	FAIL Learn more

**Comment by biermeester** [comment]
I'm afraid the blacklist thing is a separate problem. And since mail-tester says everything is okay, I'm somewhat out of ideas. Check your mail server at http://mxtoolbox.com/diagnostic.aspx. Maybe we'll learn something new.

**Comment by nicholashead** [comment]
@aravin - what exact domain/email address are you testing? Worldbases.com? webepix.in? Where are you seeing the DMARC: FAIL language?

**Comment by Aravin** [comment]
webepix.in @nicholas!

**Comment by alexweissman** [comment]
For what it's worth, I'm getting a similar problem with DKIM on my mail server.  When I try to validate against http://dkimvalidator.com, I get this response:

```
Public Key DNS Lookup

Building DNS Query for mail._domainkey.userfrosting.com
Retrieved this publickey from DNS: 
Validating Signature

result = invalid
Details: public key: not available
```

Gmail seems to flag my messages as well, and seems to have some new feature that "warns" people if they click a link in said message:

![screen shot 2017-03-02 at 12 13 19 am](https://cloud.githubusercontent.com/assets/5004534/23495285/ca2ecf7e-fee5-11e6-963d-ba9a3fae0a63.png)


I can see the `TXT` record for DKIM in my MiaB "External DNS" control panel, and it looks fine to me:

```
mail._domainkey.userfrosting.com	TXT	v=DKIM1; k=rsa; s=email; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ltRGcNK7DsjtqQcb7Jt1a1GOsSgOGPiL6bfuxsTwxa7gxMr+a/S1tvK8ss7DlKtDbjhQ/p83/Sonpf6A8imFe8kmN6yriwEDQBWxCK5h5tuZ6jZeh4SfTua1p+wUF1G7H/5Pf1VJCsvK0IeNx1N9UpZ9ztRp4aXJKBIwXtICaK+JKstsUvJTvhYDmTswbtCl9Vuz+nWecdnb1yEIOwN/MEgg3fCte1pjdLZxZej7Pea1b5MQpMxQ5xGcsRKRj0IJZdg8vmNMpdzDetE0BIYVWkjY0RO16tMH47AKs5IGjKnO6GmOxmhk7fICPDiIBxRxgcODMvMHeJ/n5iurdHHoQIDAQAB
```

**Comment by nicholashead** [comment]
@alexweissman I believe it's because your DNS for that domain isn't being handled by mailinabox. So you're missing the TXT DNS entry.

**Comment by haraldkoch** [comment]
It's in the error message, guys. Google does *content filtering* on incoming email. No matter how good your IP address reputation and DKIM/DMARC records are, you'll still get rejections if a message body triggers their content filters...

**Comment by alexweissman** [comment]
@nicholashead you were right.  For some reason I must have added `userfrosting.com` records to my MiaB, but when I sign in to my registrar, I can see that I am in fact using my registrar's DNS, and not MiaB.

I will explain in more detail here: https://discourse.mailinabox.email/t/dkim-signature-header-exists-but-is-not-valid/1968

**Comment by nicholashead** [comment]
@Aravin did you try using http://dkimvalidator.com/ to validate your dkim config?

**Comment by Aravin** [comment]
Issue still exist!

**Comment by remowashere** [comment]
It seemed to be the settings at the DNS registar.

In my case, I changed "mail._domainkey.<domain>.<tld>" to "mail._domainkey" and after that, it's validating. Now dkimvalidator.com works fine.
