### ISSUE TITLE
Setting up Mailgun

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#1070]
How does one go about setting up Mailgun as an SMTP relay. I seem to be stumped on how to go about doing that unless changing them to 
`mxa.mailgun.org`
and
`mxb.mailgun.org`

is not required and I should stick with the box defaults. Also the optional DNS record is not apparently setting up properly, as rather than `mailgun.org` it is setting the CNAME to `mailgun.org.server.tld`

**Comment by cromulus** [comment]
@ChiefGyk It feels to me like this is out of scope for MIAB, which is meant to be a single, standalone email server.
