### ISSUE TITLE
OS version 16.04

### ISSUE THREAD

**Issue by EduardJS** [mail-in-a-box/mailinabox#1073]
Hello!

Would it work with Ubuntu 16.04 LTS ? As I can see there's only support for 14.04 but the Hetzner guys which I'm using apparently renewed their OS images pool.

Regards!

**Comment by ajankuv** [comment]
Do you really want systemd controlling things?

**Comment by EduardJS** [comment]
Hei! I have no idea what Ubuntu implies, I've never used that distro.. just asked if it's possible to get things running in 16.4 rather than 14.4

**Comment by JoshData** [comment]
See #758.
