### ISSUE TITLE
Problem! Only admin can send message?

### ISSUE THREAD

**Issue by uitlaber** [mail-in-a-box/mailinabox#1074]
I have problem. How to fix if only first admin can send message?

**Comment by yodax** [comment]
Are all the status checks green? What error is the user seeing? What is in /var/log/mail.log when the user tries to send a message?

**Comment by uitlaber** [comment]
I think problem in webmail client i using afterlogic lite version.

**Comment by yodax** [comment]
Roundcube is the default install, is that working? 

Changing the box isn't supported.
