### ISSUE TITLE
can't get a certificate from letsencrypt

### ISSUE THREAD

**Issue by jazzl0ver** [mail-in-a-box/mailinabox#1087]
Hello. I've set up Mail-In-A-Box behind NAT. It uses internal DNS servers which resolve itself to an internal IP address, while ssl_certificates.py compares the IP address to the public IP before requesting a certificate:
```
                import dns.resolver
                for rtype, value in [("A", env["PUBLIC_IP"]), ("AAAA", env.get("PUBLIC_IPV6"))]:
                        if not value: continue # IPv6 is not configured
```
Please fix it.

At the meantime I had to replace PUBLIC_IP to PRIVATE_IP to get the certificate.

**Comment by cromulus** [comment]
Pretty sure that running MIAB behind a NAT isn't supported. 

It makes a bunch of assumptions about having a real, internet routable IP address, as well as being the source of truth regarding DNS for it's own domain, unless you explicitly configure an external DNS server correctly.

**Comment by jazzl0ver** [comment]
I believe MIAB behind a NAT might be a pretty common task, since many of cloud providers (AWS, GCE, etc) do not support direct public IP addresses

**Comment by TabTwo** [comment]
All the pain that gets added when NAT is involved :-(
I definitely would't recommend this

**Comment by jazzl0ver** [comment]
@TabTwo , it's the reality. Why to run away of it? At the moment I run MIAB behind NAT w/o any issues. So, it's a working solution. It just needs a little bit of tuning for the installation script.

**Comment by cromulus** [comment]
Aws does support public IP addresses for ec2 instances. I don't have any experience with GCE. 

added complexity ==harder to debug and more support required. 

That said, I feel that the maintainers respond positively to pull requests with new functionality. 

If it is straightforward, make a PR. 


There is a nontrivial chance this message has been to space.

**Comment by jazzl0ver** [comment]
@cromulus , EC2 instances have only private address inside. Same thing with GCE.
If it were easy for me, I'd make a PR.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
