### ISSUE TITLE
no support for multuple certificates

### ISSUE THREAD

**Issue by jazzl0ver** [mail-in-a-box/mailinabox#1088]
After installation MIAB sees three FQDNs:
box.mydomain.com
www.mydomain.com
mydomain.com

Fro some reason a certificate for box.mydomain.com is installed in the system. All others point to the same certificate, which I believe isn't correct.

**Comment by cromulus** [comment]
LetsEncrypt will use the same certificate for up to 100 subdomains.

This is expected behavior. See: https://letsencrypt.org/docs/rate-limits/

**Comment by jazzl0ver** [comment]
Yeah, but how to make MIAB to combine all these domains in the certificate request?

**Comment by haraldkoch** [comment]
@jazzl0ver the secret to how this works is "subjectAltName".

**Comment by jazzl0ver** [comment]
@haraldkoch , I know, thank you. The point is that MIAB does not do that out of the box

**Comment by TabTwo** [comment]
mine does, the biggest one covers 20 domains. out off the box

**Comment by jazzl0ver** [comment]
@TabTwo , this is strange, b/c my MIAB got a certificate from Let's encrypt just for a single domain.
During the installation I specified the domain name (mydomain.com) of the box and it's name (mx.mydomain.com). So, you're telling it had to request 3 certificates in one pem: mydomain.com, www.mydomain.com and mx.mydomain.com. Is that correct?
If yes, could you please provide either troubleshooting steps or steps to debug this issue?

**Comment by cromulus** [comment]
Perhaps if you could explain the use case, that might help. 

Why do you want all subdomains in a single certificate?

For normal MIAB usage, it shouldn't matter. 

There is a nontrivial chance this message has been to space.

**Comment by jazzl0ver** [comment]
@cromulus , the case is simple - I want to be able to open the MIAB by just opening https://mydomain.com, rather than https://mx.mydomain.com.
I don't mind if that would be two certificates. The issue was that MIAB didn't request certificates for all FQDNs.

**Comment by jazzl0ver** [comment]
@JoshData, may I ask you why you closed this issue? Was it resolved or you just think it's not a big one?

**Comment by JoshData** [comment]
I close support tickets that have stalled that don't appear to be bugs. I can re-open it if you want to keep working on it.
