### ISSUE TITLE
Letsencrypt provision error

### ISSUE THREAD

**Issue by Lucif3r** [mail-in-a-box/mailinabox#1089]
Something unexpected went wrong: The HTTP Validation challenge for www.mail.domain.com failed: DNS problem: SERVFAIL looking up A for www.mail.domain.com.

Log:
Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
Requesting new challenges for mail.domain.com.
Validation file is not present --- a file must be installed on the web server.
Reusing existing challenges for www.mail.domain.com.
The HTTP Validation challenge for www.domain.com failed: DNS problem: SERVFAIL looking up A for www.mail.domain.com.

**Comment by anoma** [comment]
Can you confirm you mailinabox version.

0.21c was just released and may be specifically relevant

**Comment by Lucif3r** [comment]
Hi i have reinstalled 3 times already.

Version 0.21c

**Comment by alphazo** [comment]
Same issue here. 
I was running 0.21b until today (feb 02) and eight of my domain's certificates (let's encrypt) should have been automatically renewed 4 days ago.
Now each of them show: 
`Certificate has a problem: The certificate is expiring soon: The certificate expires in 10 days on 02/13/17`
I then upgraded to 0.21c and hit the Provision buttont to force their renewal. Process went pretty smooth with challenge-responses accepted but in the end I received an error message with no special details. I tried to re-use the Provision button a second time and got the same error message. Now I'm stuck and no longer can use the Provision button.

**Comment by cromulus** [comment]
`SERVFAIL looking up A for www.mail.domain.com` means that your DNS isn't functioning the way it should.

Are you using MIAB as your DNS server, or are you using an external DNS provider?

**Comment by cromulus** [comment]
What is the output of this command:
`/root/mailinabox/management/status_checks.py`

**Comment by jalogisch** [comment]
please check if this will solve your issue: https://github.com/mail-in-a-box/mailinabox/issues/1101#issuecomment-281026627

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
