### ISSUE TITLE
Front end for changing passwords

### ISSUE THREAD

**Issue by chris13524** [mail-in-a-box/mailinabox#1090]
I've had several cases where people want to change their passwords, but this forces them to tell _me_ their password so I can enter it. I'd be nice if there was a frontend for this. Enter your username, old password, and new password. Done!

I'd work on it myself, but I am not familiar with the code base :/

**Comment by osiloke** [comment]
There is a rest api and a cli. I also needed some client side admin ui so i created one based off the cli.

**Comment by chris13524** [comment]
@osiloke But doesn't the REST API require the user be an administrator?

**Comment by nstanke** [comment]
Users can change their password within Roundcube (`/mail/?_task=settings&_action=plugin.password`)

-Norman

**Comment by osiloke** [comment]
@chris13524, i created a web app with its own authentication system, i think its better to just do it from roundcube (i actually forgot that) as suggested by @nstanke

**Comment by chris13524** [comment]
@nstanke Ah, that's defiantly a better option. Might be worth putting in the documentation somewhere?
