### ISSUE TITLE
Clean Install of 0.21c Incorrectly Setup BOTO for Python 2.7

### ISSUE THREAD

**Issue by umbertoghio** [mail-in-a-box/mailinabox#1092]
Reproduction steps:
1) Deploy Ubuntu 14.04 from Amazon EC2
2) change hostname / hosts file and perform a apt-get update and apt-get dist-upgrade, then reboot
3)  Clean install of Mailinabox 0.21C 
4) Attempt a restore from a S3 bucket in frankfurt 

The followng error occurs:

`BackendException: Could not initialize backend: No module named boto`

pip freeze and pip3 freeze correctly shows boto package as installed

The workaround to install boto from `apt-get install python-boto` partially resolves the issue but backup and restore won't work on European S3 buckets resulting in the error as the version of boto from Ubuntu repository is too old

`BackendException("No connection to backend")`

I back-tracked the problem in the configuration script of mailinabox: 

[management.sh](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/management.sh)

```
# duplicity uses python 2 so we need to get the python 2 package of boto to have backups to S3.
# boto from the Ubuntu package manager is too out-of-date -- it doesn't support the newer
# S3 api used in some regions, which breaks backups to those regions.  See #627, #653.
hide_output pip install --upgrade boto
```

The problem seems that the pip command is linked to Python 3, not to python 2.7, therefore the upgrade commands tries to upgrade an already up to date package

Workaround:
I resolved the issue by installing boto from git:
```
git clone git://github.com/boto/boto.git
cd boto
python setup.py install
```

Proposed solution: improve management.sh package to correctly handle python 2.7 packages

**Comment by nstanke** [comment]
So would `hide_output pip2 install --upgrade boto` do the job?

**Comment by umbertoghio** [comment]
Hi nstanke, 
I just tested it on a new deployed VM and your solution works just fine!

I was not aware of pip2, only thought that pip was for 2.7 and pip3 for 3.4 

pip2 freeze correctly shows the package installed and restore from Germany S3 works!
