### ISSUE TITLE
Backup/Restore

### ISSUE THREAD

**Issue by mackill** [mail-in-a-box/mailinabox#11]
How do you backup/restore your email server ? 

Do you have an easy script/application to do so ?

**Comment by glennbb** [comment]
I know you've closed this in favor of #262 but I thought I'd add a comment with what I tried to sync the encrypted backups with S3 using the AWS CLI tools (see: http://aws.amazon.com/cli/)

First I installed PIP:

    wget https://bootstrap.pypa.io/get-pip.py
    python get-pip.py

Then install the AWS tools:
    pip install awscli

Now we can test by doing either `aws help` or `aws configure`

When doing aws configure I found it worked better to leave the default region and output format prompts to none.

Now I can just do:

    aws s3 sync /home/user-data/backup/encrypted s3://my-mail-backup-bucket/nightly

Hope that helps someone.
