### ISSUE TITLE
Point domain name to another machine

### ISSUE THREAD

**Issue by haroldus-** [mail-in-a-box/mailinabox#110]
Dear Josh,

How would you point the domain name (example.com) to another machine ? The other machine serves an application while the box.example.com machine continues to act as nameserver and email server. Is it simply/only a matter of amending the the zone files in /etc/nsd/zones?

Harold

**Comment by karlingen** [comment]
@JoshData 
I want `example.se` and `www.example.se` to point to another droplet's IP while box.example.se still act as a name and email server on a separate droplet.
Is this still the way to do it?

**Comment by JoshData** [comment]
There's a shiny control panel and custom DNS API now. It's pretty fantastic. :)

**Comment by karlingen** [comment]
Aw sweet! Will check it out as soon as the public DNS records are updated.

**Comment by karlingen** [comment]
AMAZING! Love the control panel. Such amazing work you have put into it. Wow!
