### ISSUE TITLE
RCMCardDAV require php5.6

### ISSUE THREAD

**Issue by mariusv** [mail-in-a-box/mailinabox#1102]
Heya,

As the title says it RCMCardDAV requires minimum PHP 5.6.18[1] but you install php5.5 so carddav is not working correctly.

[1] https://github.com/blind-coder/rcmcarddav#requirements

**Comment by cromulus** [comment]
I'll take a look.

**Comment by cromulus** [comment]
I'm currently running this version of php:
```
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

and my contacts are working just fine...

It may be that if you are updating you may not get the latest plugins as the webmail install only checks if webmail is installed, not if plugins are up to date.

**Comment by mariusv** [comment]
Closing this as it started working as expected after the update .
