### ISSUE TITLE
 Too many certificates already issued for exact set of domains

### ISSUE THREAD

**Issue by gitcob** [mail-in-a-box/mailinabox#1107]
Like many others here I've had this SSL renewal problem.

Yesterday I followed the advice here: #1101 
...but I couldn't provision a new certificate because of daily limits (I think).

Today I tried again and got this error:

> Something unexpected went wrong: Error creating new cert :: Too many certificates already issued for exact set of domains

My guess is that this comes from the script failing over and over.

What do I do now? My certificates expire in 4 days.

**Comment by stan3** [comment]
Try with a different set of domains, see end of #1059.

**Comment by gitcob** [comment]
Thanks! I followed the advice in that ticket, used the script to provision a certificate for a single domain, then used the web ui to provision the rest.
