### ISSUE TITLE
BuddyNS secondary DNS Server configuration

### ISSUE THREAD

**Issue by cringer** [mail-in-a-box/mailinabox#1110]
Using BuddyNS as a secondary DNS server does not work.  Most users seeking this option has come across the following article which has been re-posted on several mediums.  https://schiller.im/guide/setting-up-a-free-secondary-dns-for-mail-in-a-box/

The problem is that when you choose a zone for BuddyNS and add it to mail-in-a-box it looks like /etc/nsd/zones.conf only gets the resolution of that DNS name.  This is not the correct configuration for BuddyNS.  You can see BuddyNS AXFR Transfer instructions for NSD at https://www.buddyns.com/support/setup/zone-transfer/

For instance, I add i.ns.buddyns.com as my secondary nameserver hostname.  The actual IP of this hostname is 107.181.178.180 and that's what is added to zones.conf.  This value should be added as an NS record under the domain but not for the nsd config.
 
The following should be added to the zones.conf
```
provide-xfr: 173.244.206.26 NOKEY
provide-xfr: 88.198.106.11 NOKEY
provide-xfr: 108.61.224.67 NOKEY
provide-xfr: 103.6.87.125 NOKEY
provide-xfr: 185.136.176.247 NOKEY
```

I manually modify nsd.conf with the following values and everything works properly for a bit.  However, somehow the zones.conf is reset back to its default.

**Comment by jvolkenant** [comment]
have you tried adding it to /etc/nsd/nsd.conf instead?  does it get clobbered there?

**Comment by adamvallee** [comment]
I wonder if this issue has been resolved?

**Comment by yeah** [comment]
In the description below the secondary nameserver hostname field in your MIAB, it says:

> To enable zone transfers to additional servers without listing them as secondary nameservers, add `xfr:IPADDRESS`.

I haven't tried buddyns, but adding all their IP addresses to the hostname line like this should do the trick:

```
i.ns.buddyns.com xfr:173.244.206.26 xfr:88.198.106.11 xfr:...
```

**Comment by josephbu** [comment]
@yeah Can confirm this works just fine, for buddyns (and others) you just have to add the xfr:IPADDRESS as it says in the description.

**Comment by yeah** [comment]
@JoshData feel free to close this one. I would, but I don’t have permissions.
