### ISSUE TITLE
Security Check - https://scan.nextcloud.com

### ISSUE THREAD

**Issue by sudo-gedit** [mail-in-a-box/mailinabox#1111]
Hi Guys,

I am not sure if you have already noticed this.

Nextcloud asks for a security check. Since the "Mail in a Box" does not cut off particularly well.

This is my result:

http://imgur.com/a/rf3TS

You can test yourself at https://scan.nextcloud.com.

Unfortunately, I do not speak the English language very well. Sorry.

Best regards

**Comment by yeah** [comment]
This is interesting. I ran the tool against a stock MIAB v0.21c and I got the same E rating (on a scale from A to F, I suppose) as @sudo-gedit. These are the vulnerabilities the tool finds:

**High**
- SMB User Authentication Bypass

**Medium**
- Stored XSS in CardDAV image export
- Reflected XSS in Gallery application
- Bypass received read-only share permissions using read-write reshare
- User enumeration with error messages
- Information disclosure in email field dialog at sharing
- Flooding logfiles with a 1 Bit BMP File

**Low**
- Content-Spoofing in "files" app
- Content-Spoofing in "dav" app

I think we should definitely do something here.

A manual upgrade to 9.1.4.2 made all errors go away and move the rating to a solid A. I'm preparing a PR now.

**Comment by yodax** [comment]
The smb one doesn't apply to us. 

When preparing a pr please run the test script for repeating login failures.

**Comment by yeah** [comment]
> When preparing a pr please run the test script for repeating login failures.

I'm still new to this project. Is there some documentation on how to run the test suite? 

I've just tested it manually and it works as expected. It's just a patch level update and it's pretty much identical to what you did in 3af5e550350.

**Comment by yodax** [comment]
It's the script under tests/fail2ban.py. That checks that they haven't changed their login messages (again).

**Comment by yeah** [comment]
Thanks! I ran the script against an upgraded server and it passes. I am also seeing

`2017-03-26 10:39:53,678 fail2ban.actions: WARNING [miab-owncloud] Ban <IP_ADDRESS>`

in `/var/log/fail2ban.log` where `<IP_ADDRESS>` is my client's public IP.

**Comment by JoshData** [comment]
Thanks everyone. Fixed by the PR above.
