### ISSUE TITLE
dovecot-lucene in dockerized mailinabox

### ISSUE THREAD

**Issue by gnh1201** [mail-in-a-box/mailinabox#1113]
I want build dockerized mailinabox. but, dovecot-lucene package not found.
Any have no ideas?

related issue: #112

> $ docker build -t mailinabox-docker .
> Sending build context to Docker daemon  3.15 MB
> Sending build context to Docker daemon 
> Step 0 : FROM phusion/baseimage:0.9.16
>  ---> 5a14c1498ff4
> Step 1 : MAINTAINER Joshua Tauberer (http://razor.occams.info)
>  ---> Using cache
>  ---> 17f7fb051e62
> Step 2 : EXPOSE 25 53/udp 53/tcp 80 443 587 993 4190
>  ---> Using cache
>  ---> 16ddd4187025
> Step 3 : VOLUME /home/user-data
>  ---> Using cache
>  ---> 7b81c269598e
> Step 4 : CMD /sbin/my_init
>  ---> Using cache
>  ---> 58805652607f
> Step 5 : RUN useradd -m user-data
>  ---> Using cache
>  ---> 8d65abe64ea0
> Step 6 : RUN apt-get update
>  ---> Using cache
>  ---> d5b301da1e60
> Step 7 : RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
>  ---> Using cache
>  ---> dcebe52a8f6e
> Step 8 : RUN add-apt-repository -y ppa:mail-in-a-box/ppa
>  ---> Using cache
>  ---> 6d7e1a6f5e62
> Step 9 : ADD containers/docker/apt_package_list.txt /tmp/mailinabox_apt_package_list.txt
>  ---> Using cache
>  ---> ce27f7404615
> Step 10 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y $(cat /tmp/mailinabox_apt_package_list.txt)
>  ---> Running in 3a228ba40a3e
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package dovecot-lucene
> INFO[0004] The command [/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y $(cat /tmp/mailinabox_apt_package_list.txt)] returned a non-zero code: 100

**Comment by cromulus** [comment]
You'll need the special PPA that @JoshData publishes here: https://launchpad.net/%7Email-in-a-box/+archive/ubuntu/ppa
