### ISSUE TITLE
Let's Encrypt ssl certificate problem

### ISSUE THREAD

**Issue by zoof** [mail-in-a-box/mailinabox#1118]
As I noted [here](https://discourse.mailinabox.email/t/force-lets-encrypt-to-replace-startcon-certificates/1897/6?u=zoof), `./management/ssl_certificates.py --force` is not working for me and I'm not sure why.  My StartSSL certificates are not expired and will not do so for some time but Chrome is now blocking them so I really need to migrate.

**Comment by cromulus** [comment]
Looks like you are running an older version of MIAB and this may be resolved by upgrading to the latest version.

**Comment by zoof** [comment]
I went ahead and upgraded but I'm getting different errors now.  The first time:

    $ sudo ./management/ssl_certificates.py --force
    
    I'm going to provision a TLS certificate (formerly called a SSL certificate)
    for you from Let's Encrypt (letsencrypt.org).

    TLS certificates are cryptographic keys that ensure communication between
    you and this box are secure when getting and sending mail and visiting
    websites hosted on this box. Let's Encrypt is a free provider of TLS
    certificates.

    Please open this document in your web browser:
    
    https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
    
    It is Let's Encrypt's terms of service agreement. If you agree, I can
    provision that TLS certificate. If you don't agree, you will have an
    opportunity to install your own TLS certificate from the Mail-in-a-Box
    control panel.
    
    Do you agree to the agreement? Type Y or N and press <ENTER>: y
    
    A TLS certificate was requested for: box.rainexpected.com, rainexpected.com, www.rainexpected.com.
    We have to wait 60 seconds for the certificate to be issued...
    We have to wait 50 seconds for the certificate to be issued...
    We have to wait 40 seconds for the certificate to be issued...
    We have to wait 30 seconds for the certificate to be issued...
    We have to wait 20 seconds for the certificate to be issued...
    We have to wait 10 seconds for the certificate to be issued...
    Traceback (most recent call last):
      File "./management/ssl_certificates.py", line 807, in <module>
        provision_certificates_cmdline()
      File "./management/ssl_certificates.py", line 450, in provision_certificates_cmdline
        status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
      File "./management/ssl_certificates.py", line 337, in provision_certificates
        logger=my_logger)
      File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 76, in issue_certificate
        (cert_pem, chain) = request_certificate_issuance(client, challenges, csr, logger)
      File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 210, in request_certificate_issuance
        cert_pem = cert_to_pem(cert_response.body)
      File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 217, in cert_to_pem
        return OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
    TypeError: must be X509, not ComparableX509
    Exception ignored in: <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7fe2426072e8>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/acme/client.py", line 534, in __del__
        self.session.close()
      File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 689, in close
        for v in self.adapters.values():
      File "/usr/lib/python3.4/_collections_abc.py", line 512, in __iter__
        for key in self._mapping:
      File "/usr/lib/python3.4/collections/__init__.py", line 91, in __iter__
        curr = root.next
    ReferenceError: weakly-referenced object no longer exists

and the second time:

    $ sudo ./management/ssl_certificates.py --force
    Traceback (most recent call last):
      File "./management/ssl_certificates.py", line 807, in <module>
        provision_certificates_cmdline()
      File "./management/ssl_certificates.py", line 450, in provision_certificates_cmdline
        status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
      File "./management/ssl_certificates.py", line 337, in provision_certificates
        logger=my_logger)
      File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 76, in issue_certificate
        (cert_pem, chain) = request_certificate_issuance(client, challenges, csr, logger)
      File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 210, in request_certificate_issuance
        cert_pem = cert_to_pem(cert_response.body)
      File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 217, in cert_to_pem
        return OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
    TypeError: must be X509, not ComparableX509

**Comment by zoof** [comment]
So I made some progress following [this](https://discourse.mailinabox.email/t/letsencrypt-issue/1891/10). I now have a cert for the main URL (box.example.com) but not for the other URLs (example.com and www.example.com).  So box.example.com shows on the admin page as having a signed and valid certificate for 89 days but example.com and www.example.com still show the expiry for the old certificate (200+ days).  Any ideas on how to get the remaining 2 certificates migrated to Let's Encrypt?

    $ sudo ./management/ssl_certificates.py --force -v
    
    I'm going to provision a TLS certificate (formerly called a SSL certificate)
    for you from Let's Encrypt (letsencrypt.org).
    
    TLS certificates are cryptographic keys that ensure communication between
    you and this box are secure when getting and sending mail and visiting
    websites hosted on this box. Let's Encrypt is a free provider of TLS
    certificates.
    
    Please open this document in your web browser:
    
    https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
    
    It is Let's Encrypt's terms of service agreement. If you agree, I can
    provision that TLS certificate. If you don't agree, you will have an
    opportunity to install your own TLS certificate from the Mail-in-a-Box
    control panel.
    
    Do you agree to the agreement? Type Y or N and press <ENTER>: y
    
    A TLS certificate was requested for: box.example.com, example.com, www.example.com.
    We have to wait 60 seconds for the certificate to be issued...
    We have to wait 50 seconds for the certificate to be issued...
    We have to wait 40 seconds for the certificate to be issued...
    We have to wait 30 seconds for the certificate to be issued...
    We have to wait 20 seconds for the certificate to be issued...
    We have to wait 10 seconds for the certificate to be issued...
     * Stopping Postfix Mail Transport Agent postfix
       ...done.
     * Starting Postfix Mail Transport Agent postfix
       ...done.
    dovecot stop/waiting
    dovecot start/running, process 21616
     * Reloading nginx configuration nginx
       ...done.
    A TLS certificate was successfully installed for box.example.com, example.com, www.example.com.
    Exception ignored in: <bound method ClientNetwork.__del__ of <acme.client.ClientNetwork object at 0x7fea02d5aa58>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/acme/client.py", line 534, in __del__
        self.session.close()
      File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 689, in close
        for v in self.adapters.values():
      File "/usr/lib/python3.4/_collections_abc.py", line 512, in __iter__
        for key in self._mapping:
      File "/usr/lib/python3.4/collections/__init__.py", line 91, in __iter__
        curr = root.next
    ReferenceError: weakly-referenced object no longer exists

**Comment by yodax** [comment]
I haven't tried this, but looking at the code you should be able to pass in just the domain on the cli for which you want the cert.

See [here](https://github.com/mail-in-a-box/mailinabox/blob/master/management/ssl_certificates.py#L441)

**Comment by zoof** [comment]
Thanks -- I tried this (`sudo management/ssl_certificates.py example.com --force`) and it says 
`A TLS certificate was successfully installed for example.com.` But when I go to the admin interface, it is still only box.example.com that has a Let's Encrypt certificate.

**Comment by zoof** [comment]
So looking in the `/home/user-data/ssl` directory and there are `example.com-20170624-????????.pem` and  `www.example.com-20170624-????????.pem` files.  Is the problem with the `ssl_certificates.py script that it did not delete the old certificates?  If I delete them, will that fix my problem?

**Comment by zoof** [comment]
So moving the old StartSSL certificates to a different location did not fix the problem.  Any ideas how to fix this?

**Comment by elSpike** [comment]
Hey @zoof, I fixed this after seeing the exact issue you were.

SSL into your box and remove the old StartSSL certificates (move them completely out of the `/home/user-data/ssl` directory, simply renaming them to *.old didn't work for me.

Once done, just run `~/mailinabox/tools/web_update`

You can confirm it is working by looking at `/etc/nginx/conf.d/local.conf` and seeing which ssl cert is configured for each domain. `/web_update` edits that file, so don't manually change.

Cheers
Patrick

**Comment by zoof** [comment]
@elSpike Many thanks!  That seems to have done the trick.

**Comment by elSpike** [comment]
@JoshData I think this one can be closed.
