### ISSUE TITLE
master is a v0.22 release candidate

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#1122]
For those that can help kick the tires before a release, the master branch is now a RC for the next release. If all goes well, I'll post it as v0.22 next weekend.

**Comment by just4t** [comment]
Perhaps posting a link to this one at your discourse forum could be of help, too

**Comment by yeah** [comment]
Updated a few boxes, works great! Found a possible issue with `mail_log.py`, see #970.

**Comment by yodax** [comment]
I deployed to a few machines. All is well.

**Comment by xetorixik** [comment]
v0.22 release candidate working fine here, both upgrade and fresh install.
The new CardDAV Roundcube plugin is really really nice. 
Thanks @JoshData and team.

**Comment by JoshData** [comment]
Thanks everyone! It's posted now.
