### ISSUE TITLE
Mail-in-a-box should support Shared Mailboxes

### ISSUE THREAD

**Issue by franklouwers** [mail-in-a-box/mailinabox#1125]
Hi,

Are there any plans to support shared mailboxes? It seems not that hard to do in Dovecot: http://wiki.dovecot.org/SharedMailboxes

**Comment by yeah** [comment]
I'd vote no, because a shared mailbox is almost always just a workaround for a proper help desk or ticketing system – none of which MIAB tries to be afaik.

**Comment by bronson** [comment]
I'm not sure https://wiki.dovecot.org/SharedMailboxes/Shared meets my definition of "not that hard".  :)

You could try it out on your host.  Just save your changes before upgrading mail-in-a-box.  If it works and is useful, submit a PR!

Personally, I've never seen shared mailboxes work for more than a few months in practice... they seem to create more communications issues than they solve.

**Comment by JoshData** [comment]
I'm pushing back on any new feature requests. This project is complicated enough as it is. :)
