### ISSUE TITLE
Quick question about ICMP

### ISSUE THREAD

**Issue by NitescuLucian** [mail-in-a-box/mailinabox#1127]
If I am going to block ICMP broadcast and requests to a MiaB would it have any kind of impact over the functionality?

echo net.ipv4.icmp_echo_ignore_all = 1 >> /etc/sysctl.conf
echo net.ipv4.icmp_echo_ignore_broadcasts = 1 >> /etc/sysctl.conf
sysctl -p

**Comment by yodax** [comment]
Never block icmp.  

http://shouldiblockicmp.com

**Comment by yodax** [comment]
Nothing. You are already advertising via DNS that a smtp server is running on that ip. Smtp will send a header. It makes no sense blocking icmp, it will only prevent people from diagnosing connection issues and it will not stop adversaries. You will also run into issues when people connecting to you server are having connectivity issues. (fragmentation and rate limiting)

**Comment by yeah** [comment]
@NitescuLucian in the future, please use https://discourse.mailinabox.email/ for questions of this kind. GitHub issues are for development of MIAB. Thanks!
