### ISSUE TITLE
question about DNS and using more than 1 domain.

### ISSUE THREAD

**Issue by systemroot** [mail-in-a-box/mailinabox#1128]
hello,

so i have more than 1 domain and domain **example.email** is where i've install `mail in a box`

so simple af just i want to use **example.email** as the email service for all my other domains, 
and i was testing to put nameservers of **example.email** `ns1.example.email, ns2.example.email` at another domain name which i own. **newdomain.com**
first  i didn't find any option to add another domain so anyway i read somewhere when i create a email with the @new domain, `main in a box` will create all other stuff. so i did this and now for that new domain **newdomain.com** at **custom dns** i've create 2 dns records
`@ pointed to 1.1.1.1`
& `www pointed to 1.1.1.1`

but my domain is offline with the output `DNS_PROBE_FINISHED_NXDOMAIN` :confused:  any solution?!

thanks!

all this is about to create hostmaster@newdomain.com to get a SSL from GeoTrust!

another try

i've remove `ns1.example.email, ns2.example.email` from `newdomain.com` and i'm using cloudflare dns and MX records are the same i didn't change them to use my email service

so i tried to create a email 'hostmaster@newdomain.com' and output from mail in a box

> You may not make a user account for that address because it is frequently used for domain control validation. Use an alias instead if necessary.

reading email forwards at 'alias' tab. i can't read anywhere "hostmaster@newdomain.com" and i tried to send a email from my gmail account to hostmaster@newdomain.com and i got autoreply from gmail system

>Address not found
Your message wasn't delivered to hostmaster@newdomain.com because the address couldn't be found. Check for typos or unnecessary spaces and try again.

what's the reason which you've configure mail in a box to auto create domain aliases or to stop me to create hostmaster@newdomain.com ?!

Thanks again!

**Comment by yodax** [comment]
I'm having a hard time understanding what it is you are trying to do. Did you add an alias for hostmaster@newdomain.com? After that what did the status checks say?

**Comment by systemroot** [comment]
@yodax 
![](http://image.prntscr.com/image/3055dbf15654446fa4050f91d7212ea5.png)

but when i tried to put forward to raw@example.email (admin email) this alert doesn't appears :/
