### ISSUE TITLE
Need help with the Custom DNS API 

### ISSUE THREAD

**Issue by lepidas** [mail-in-a-box/mailinabox#1133]
Hi! I need some help here, 
I have a machine IP:xx.xxx.xx.xxx hosting MAIB  box.domain.com (all is ok with glue records etc.)
I have another machine IP:yy.yyy.yy.yyy hosting domain.com and sub.domain.com
I don't understand how and where to set this through the Custom DNS API.

Thanx in advance and please be as specific as possible so to understand.

**Comment by yodax** [comment]
You need to set an A record for that hostname and ip. If it doesn't work immediately you might need to wait for the DNS to propagate.

**Comment by lepidas** [comment]
How? The only available set in Set custom DNS records
is box.domain.com.
I could use sub.box.domain.com but I want sub.domain.com and domain.com

**Comment by yodax** [comment]
The dropdown doesn't show domain.com? Just box.domain.com?

**Comment by lepidas** [comment]
That is the problem, the dropdown shows only box.domain.com.
I read somewhere that if I add catch-all alias @domain.com then I would be able but I'm not sure if that is the correct, safe and risk free way.

**Comment by yodax** [comment]
Should be risk free. You have a backup right?

**Comment by lepidas** [comment]
It is working ok. So has nothing to do with custom dns api
