### ISSUE TITLE
Roundcube shows "DATABASE ERROR: CONNECTION FAILED" after v0.22 upgrade

### ISSUE THREAD

**Issue by sbidin** [mail-in-a-box/mailinabox#1136]
I updated to v0.22 and rebooted the server.

Visiting Roundcube displays the following error:

    DATABASE ERROR: CONNECTION FAILED!

    Unable to connect to the database!
    Please contact your server-administrator.

The server seems to otherwise be working fine (i.e. emails can be sent and received using other clients), I just can't use the web interface.

**Comment by yodax** [comment]
Can you see if the tips here help: https://discourse.mailinabox.email/t/solved-upgrade-from-0-21c-to-0-22-fails-to-upgrade-roundcube-sqlite-database/2055

**Comment by sbidin** [comment]
Deleting the cookies fixes the issue.

Thanks!
