### ISSUE TITLE
python mail_log.py

### ISSUE THREAD

**Issue by NitescuLucian** [mail-in-a-box/mailinabox#1146]
root@box:~/fail/mailinabox/management# python mail_log.py
```
  File "mail_log.py", line 249
    ), end='\n\n')
          ^
SyntaxError: invalid syntax
```

**Comment by yodax** [comment]
You are calling it wrong. The file has a shebang and can be executed directly. Also it's a python3 file.

**Comment by NitescuLucian** [comment]
@yodax Indeed.
Now I have this:
root@box:~/fail/mailinabox/management# ./mail_log.py
```
Scanning from 2017-04-05 16:59:15 back to 2017-04-05 00:00:00
Processing file /var/log/mail.log ...
Traceback (most recent call last):
  File "./mail_log.py", line 881, in <module>
    scan_mail_log(env_vars)
  File "./mail_log.py", line 127, in scan_mail_log
    scan_files(collector)
  File "./mail_log.py", line 83, in scan_files
    if scan_mail_log_line(line.strip(), collector) is False:
  File "./mail_log.py", line 334, in scan_mail_log_line
    date = datetime.datetime.strptime(date, '%b %d %H:%M:%S')
  File "/usr/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'AApr 05 09:10:50' does not match format '%b %d %H:%M:%S'
```

**Comment by yodax** [comment]
CC @biermeester. Looks like a localization issue.

**Comment by biermeester** [comment]
I'm on it!

(And just when I'm almost done re-rewriting this script, so it can be used for monitoring mail activity 😉 )

**Comment by NitescuLucian** [comment]
@yodax @biermeester Lovely support gentlemens. I will test as sonn the new script is out!

**Comment by biermeester** [comment]
@NitescuLucian, do all current dates start with `AApr`? You can run `tail /var/log/mail.log` to find out.

**Comment by NitescuLucian** [comment]
@biermeester No. But not just one.

**Comment by biermeester** [comment]
Can you copy such a line here? I'm curious what service is logging badly.

**Comment by NitescuLucian** [comment]
@biermeester I host my VM at Azure and beetwen  09:10:50 and 09:2X:XX I have dealocated my machine to extend the OS disk. 

All logs for the following types are with an A in front of them:
```
AApr 05 09:10:50 config: Warning: service auth { client_limit=1000 } is lower than required under max. load (1250)
AApr 05 09:10:50 config: Warning: service anvil { client_limit=1000 } is lower than required under max. load (1003)
```

**Comment by NitescuLucian** [comment]
@yodax @biermeester after I have deleted the A in front everything is working.

**Comment by biermeester** [comment]
So, this only happened when the machine was dealocated? Anyway, I've made the new script I'm working on a bit more robust, so it will ignore weird dates.

**Comment by NitescuLucian** [comment]
@biermeester Yes, happened when the machine was dealocated. I just found that in the actual version I don't get all the emails stats.

**Comment by biermeester** [comment]
>I just found that in the actual version I don't get all the emails stats.

What do you mean by that? Not every kind of stat? Or is some data not collected? Or is the wrong time span scanned?

What command are you running exactly? (try `./mail_log.py -h` to see all the options)

**Comment by NitescuLucian** [comment]
@biermeester Some data are not collected when I run ./mail_log.py

**Comment by biermeester** [comment]
By default it only shows sent and received mail for the current day. Run `./mail_log.py **-h**` for more options.

**Comment by NitescuLucian** [comment]
@biermeester I got it but i don't get the real statistics.

**Comment by biermeester** [comment]
If you'd like, you can try the new version of the script. You can find it this pull request: #1165
