### ISSUE TITLE
Route53 DNS and DKIM issues

### ISSUE THREAD

**Issue by a-schaefers** [mail-in-a-box/mailinabox#1152]
Updated the wiki in my repository here, feel free to use what I have written if it helps.
https://github.com/a-schaefers/Mail-In-A-Box-Wiki/blob/master/FAQ.md#aws-route53-related
as per request from JoshData here:
https://github.com/mail-in-a-box/mailinabox/issues/656#issuecomment-177341678

**Comment by Crx4** [comment]
Can't we use CNAME record instead? like: mail._domainkey.example.com which example.com the domain using for my mail box. I'm currently using without issue, am I doing something wrong?
