### ISSUE TITLE
Add CAA DNS record generation

### ISSUE THREAD

**Issue by drmartinsweden** [mail-in-a-box/mailinabox#1154]
CAA record checking is now (or shortly will be) mandatory for certificate providers.

The additional DNS records needed are fairly simple:

Syntax:
**CAA flags tag value**

Example:
**example.com. CAA 0 issue "letsencrypt.org"**

Additionally, to provide an email alert of a non-approved CA requesting certificate:
**example.com.  CAA 0 iodef "mailto:administrator@example.com"**

_Originally posted to Discourse:
https://discourse.mailinabox.email/t/caa-dns-record-checking-now-mandatory/2081_

**Comment by yodax** [comment]
Closed by https://github.com/mail-in-a-box/mailinabox/issues/1155
