### ISSUE TITLE
NextCloud 10 warnings

### ISSUE THREAD

**Issue by bronson** [mail-in-a-box/mailinabox#1156]
NextCloud 10 shows two warnings:

![screen shot 2017-04-12 at 2 33 39 pm](https://cloud.githubusercontent.com/assets/1776/24980755/73e86016-1f8e-11e7-9166-502bb106ba39.png)

* php does not seem to be setup properly to query system environment variables. The test with getenv("PATH") only returns an empty response.  Please check the installation documentation ↗ for php configuration notes and the php configuration of your server, especially when using php-fpm.
* APCu below version 4.0.6 is installed, for stability and performance reasons we recommend updating to a newer APCu version.

Just making sure...  The first one looks intentional, the second presumably will be taken care of by #758?

Ping @yeah since #1121 is locked.

**Comment by yeah** [comment]
Also see #1140

**Comment by bronson** [comment]
#1140 looks awesome.  I'll go for it once I get Nextcloud 10 stable.  (still having contact flakiness but I don't think it's anything to do with mailinabox)

**Comment by yodax** [comment]
The apc issue is there since https://github.com/mail-in-a-box/mailinabox/pull/894 

See the comments there. I can't recal, but I believe the same for the other one. (Which may have been there earlier)

**Comment by bronson** [comment]
Well...  I just haven't had any luck getting contacts to work reliably on NextCloud 10.  They appear fine inside OwnCloud, but I can't get rcmcarddav and Thunderbird's CardBook to work.  Does NextCloud 10's contacts work for anyone else?

I'll be jumping on #1140 soon (and closing this issue), unless anyone suggests a good reason not to.  I'd much rather play with new bugs in NC11 than old bugs in NC10.

**Comment by yeah** [comment]
> Does NC10's contacts work for anyone else?

Like a charm and out of the box using Contacts app on iOS, macOS, and a regular web browser.

**Comment by bronson** [comment]
Ah, that's true,  MacOS contacts is working for me.

regular web browser...  you mean the NC contacts app?

**Comment by yodax** [comment]
Contacts app inside Nextcloud works for me. Also zpush, carddav iOS and macOS work for me.

**Comment by bronson** [comment]
Does Roundcube's rcmcarddav work for either of you?

Agreed, the Mac clients all work for me too.

**Comment by yeah** [comment]
> Does Roundcube's rcmcarddav work for either of you?

Yup. Sorry that it doesn't for you.

**Comment by yodax** [comment]
I just checked and roundcube<=>Nextcloud contacts work.

**Comment by bronson** [comment]
So strange!  Thanks for confirming that it works.  Guess I'll try a backup and restore.

**Comment by yodax** [comment]
The Nextcloud 10 warnings are gone with the Nextcloud 12 move, if it doesn't work for everyone shall we make a specific issue about that? :smile:
