### ISSUE TITLE
Spam Reporting?

### ISSUE THREAD

**Issue by daslicht** [mail-in-a-box/mailinabox#1157]
Hi
, is there a way to report spam to services such as spamcop to prevent future spam please?

**Comment by bronson** [comment]
Right now, no.  All spam handling is internal.

Is this issue asking for integration with spamcop.net?

You could set it up on your mail-in-a-box and see how it works.

**Comment by yeah** [comment]
@daslicht: In the future, please use [the forum](https://discourse.mailinabox.email/) for usage related questions and reserve GitHub to discussing confirmed bugs or issues. This way, it will be easier for the developers of MIAB to push the project forward more efficiently. Thanks!
