### ISSUE TITLE
Domain control validation alias needs administrator address, but check is invalid

### ISSUE THREAD

**Issue by louwers** [mail-in-a-box/mailinabox#1159]
On my box, `administrator@mybox.net` is administrator. When I try to add an alias `abuse@mybox.net` to `administrator@mybox.net`, it works. However, when I try to set as destination `administrator+abuse@mybox.net` (which is essantially the same e-mail address), it refuses to create the alias with the following message:

> This alias can only have administrators of this system as destinations because the address is frequently used for domain control validation.

I believe the check if the provided e-mail is an administrator account should strip the local-part of the email address after and including the `+`.

Edit: please let me know if this needs to be reported upstream instead.

**Comment by bronson** [comment]
`administrator+abuse@mybox.net` gets delivered to `administrator@mybox.net` by default, no configuration needed.

You're saying you want to change this?

**Comment by louwers** [comment]
Yes, that is correct, but the error message is triggered regardless (i.e. the alias can't be created).

Hope that's clear!

**Comment by bronson** [comment]
So MiaB isn't letting you create an alias from abuse@mybox.net to administrator+abuse@mybox.net.

That's strange because this code appears to be taking that situation into account: https://github.com/mail-in-a-box/mailinabox/blob/36bef2ee16362eec1a0051f2b96034b1fbc63963/management/mailconfig.py#L81

And I just tested it by updating my abuse@mydomain.net alias to forward to administrator+abuse@mydomain.net.  Worked just fine.

Is there anything different about your system?

**Comment by louwers** [comment]
Oops, my bad. Yes. I'm not actually trying to make an alias for `administrator'. `administrator+something@mybox.net` actually works, but `sysadmin+something@mybox.net` (an account I created which I am actually using) doesn't.  

[This](https://github.com/mail-in-a-box/mailinabox/blob/36bef2ee16362eec1a0051f2b96034b1fbc63963/management/mailconfig.py#L440) is the relevant check. It's passing the e-mail with `+` part to `get_mail_user_privileges` if it's not a dcv address.

**Comment by bronson** [comment]
Ah sure.  The issue is that get_mail_user_privileges doesn't work with +tag addresses.

Not sure if that's intentional.  Could anything go wrong if the +tag is stripped before checking for privileges?

**Comment by louwers** [comment]
In this case I'm fairly sure it's no problem at all. This is just a mechanism to prevent people from accidentily letting mail to drc addreses bounce anyway.

**Comment by JoshData** [comment]
Yep, let's fix this.

**Comment by macmedia** [comment]
Can we just add this line to the `get_mail_user_privileges()` function?

```
email = re.sub(r"(?=\+)[^@]*(?=@)",'',email)
```

```
def get_mail_user_privileges(email, env, empty_on_error=False):

	# Strip +tags from email
	email = re.sub(r"(?=\+)[^@]*(?=@)",'',email)
	
	# get privs
	c = open_database(env)
	c.execute('SELECT privileges FROM users WHERE email=?', (email,))
	rows = c.fetchall()
	if len(rows) != 1:
		if empty_on_error: return []
		return ("That's not a user (%s)." % email, 400)
	return parse_privs(rows[0][0])
```

**Comment by JoshData** [comment]
Would be better to handle it in the function that calls this function, rather than here.

**Comment by macmedia** [comment]
We could do something like this on line [335](https://github.com/mail-in-a-box/mailinabox/blob/36bef2ee16362eec1a0051f2b96034b1fbc63963/management/mailconfig.py#L435). 

`email = re.sub(r"(?=\+)[^@]*(?=@)",'',email).strip()`

**Comment by JoshData** [comment]
The latter is OK.

**Comment by macmedia** [comment]
Tested by creating an admin user `sysadmin@mybox.net` per @louwers. Then updated the abuse@domainname.local to point to sysadmin+abuse@mybox.net. Sent an email and it was forwarded to this account.

`abuse@mybox.net -> sysadmin+abuse@mybox.net`
