### ISSUE TITLE
Changing hostname does not affect Nextcloud

### ISSUE THREAD

**Issue by yeah** [mail-in-a-box/mailinabox#1161]
I am not sure if changing the hostname of your box is a supported use case, but since the installer asks for the hostname on every run, I thought it was.

After changing the hostname however in a subsequent run, the `config/config.php` in Nextcloud (same applied to ownCloud before the switch) isn't changed and will still contain the old hostname as a value for `mail_domain`.

**Comment by JoshData** [comment]
We should fix this.
