### ISSUE TITLE
Reasons for next/owncloud integration

### ISSUE THREAD

**Issue by kunago** [mail-in-a-box/mailinabox#1175]
As MIAB is a solution focusing maily on emails and all it takes, what are the reasons for integrating any cloud solution? I myself have used owncloud in the past and Nextcloud just recently but would never need to use it in a bundle with any email solution. If one wants to use this cloud for managing emails, there is a nice plugin for it already.

So could someone please clarify the reasons for integrating any such solution?

**Comment by JoshData** [comment]
See #514.

**Comment by kunago** [comment]
Thank you, however running through the discussion what I see is comments about possible replacement. I just wonder why there is a need for any such solution to be integrated in the first place. If it is in the discussion, my apology but did not find the answer.

**Comment by JoshData** [comment]
It's there primarily for storing contacts, which is an important part of sending email.

**Comment by kunago** [comment]
I see. They way many people around me use emails is just for sending and receiving it. Not that many of them actually sync contacts even though I use it and it's a nice feature. In general though, would you consider having owncloud as an opt-in plugin? I did not find any config file to be able to inject a simple boolean to but I could help out with this as I have experience with scripting. Well, if it is desired of course.

**Comment by JoshData** [comment]
> would you consider having owncloud as an opt-in plugin

No.
