### ISSUE TITLE
Add Support to Ubuntu 17.04 and Debian Stretch 

### ISSUE THREAD

**Issue by h3ct0rjs** [mail-in-a-box/mailinabox#1176]
Hi Everybody, 

After testing this awesome work in the past, today I was testing if the version v0.22 was supporting the new LTS version of Ubuntu zesty, and for my surprise it says:

> We can't write scripts that run on every possible setup, sorry.

I think that we can handle this, at least for debian and ubuntu versions, so are you planning to add support to new OS versions ?, the other thing is about the letsencrypt project, will it be supported?, because is pretty hard to combine this version to run with letsencrypt and you need to make a few manual steps.

Best Regards and great job,
Hector F.

**Comment by yodax** [comment]
> I think that we can handle this

Even supporting the different configurations of 14.04 is quite challenging. Not all cloud images are created equally.

See similar discussion [here](https://github.com/mail-in-a-box/mailinabox/issues/758) about 16.04.

**Comment by JoshData** [comment]
Let's keep this discussion on that issue thread.

**Comment by h3ct0rjs** [comment]
Sure, I will add my comment.
