### ISSUE TITLE
dnssec ns record on primary dns server

### ISSUE THREAD

**Issue by grauschnabel** [mail-in-a-box/mailinabox#1178]
Hi there,

mailinabox tells me to set a dnssec on the status page.  my isp (inwx.de) tells me:

> In case you are running DNSSEC on your own primary DNS, you may use DNSSEC with our name servers as secondary DNS.

I'm using mailinabox as primary dns server, so why is this not configured by itself?

**Comment by JoshData** [comment]
Why is what not configured?

If you aren't using secondary DNS, the message from your ISP can be ignored. I'm not sure what they're trying to say.

**Comment by grauschnabel** [comment]
I have in my mail-in-a-box status page for several domains:

> ? This domain's DNSSEC DS record is not set. The DS record is optional. The DS record activates DNSSEC. To set a DS record, you must follow the instructions provided by your domain name registrar and provide to them this information:
> show more

I try to fix that.  It says follow the instructions from my domain name registrar.  And in this issue i tell you what it says.

I use mailinabox as primary name server, and 2 of my isps as secondary name servers.

**Comment by JoshData** [comment]
The DNSSEC DS record is something set at your domain name registrar. It's not something the box configures. You'll have to ask your registrar for help if they aren't clear about what to do.

**Comment by nodomain** [comment]
In the specific example of inwx.de you'll need to send them an email to support@inwx.de with the information provided on the status page together with your support PIN. Been there, done that ;-)

**Comment by grauschnabel** [comment]
Did it and broke my box.  The thing was that the dnssec key tag on the box is set to 63153 where the dns registrat is calculating that key and gets 63152  so this makes the box wrong and all dns settings are refused by other dns servers, as far as I understood.  So now the ndssec is deleted again, and I have no clue how to fix that.

**Comment by JoshData** [comment]
DNSSEC is very weird and different registrars implement it a little differently. I'm going to close this because it's been more than a month. Feel free to re-open if you have more info.

**Comment by bf** [comment]
@grauschnabel how did you resolve this issue? Did you move away from inwx?
