### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Madji** [mail-in-a-box/mailinabox#1180]
Returns this message when checking backups. But in fact backups on the remote server are present, it can be seen from the screenshot
![_2017-05-23_11-14-57](https://cloud.githubusercontent.com/assets/2238714/26347527/8a2bebb0-3fb2-11e7-875a-6b2faa55bb84.png)
![_2017-05-23_11-15-26](https://cloud.githubusercontent.com/assets/2238714/26347532/8d48ceda-3fb2-11e7-96a3-5e0c9b5fe48b.png)

**Comment by yodax** [comment]
This will be fixed in the next release. For now you can try adding a slash to the end of the path.

**Comment by Madji** [comment]
Yes. It helped thanks. I realized that the problem is with the syntax.
