### ISSUE TITLE
Strange issue with virgin install of MIAB

### ISSUE THREAD

**Issue by pohutukawanz** [mail-in-a-box/mailinabox#1183]
![helpful_error](https://cloud.githubusercontent.com/assets/1432159/26569044/3f3b4ea2-455c-11e7-8672-9ef40c1de223.png)
Hi, I have a suitable box at Linode with Ubuntu 14.04 LTS and a clean install of MIAB.

After the install/inital config. script, I head off to the /admin URL, authenticate successfully but get the following error:

> "Error
> Something went wrong, sorry."

I found my way around to running the Python status check and have included the results below ([DOMAIN] is the subdomain and [DOMAIN] is the fqdn).

Reverse DNS at Linode is setup and is looking good.

Any help much appreciated!

Robin

root@ubuntu:~/mailinabox/management# ./status_checks.py

System
======
✓  All system services are running.
✖  The SSH server on this machine permits password-based login. A more secure 
   way to log in is using a public key. Add your SSH public key to 
   $HOME/.ssh/authorized_keys, check that you can log in without a password, 
   set the option 'PasswordAuthentication no' in /etc/ssh/sshd_config, and then
   restart the openssh via 'sudo service ssh restart'.
✓  System software is up to date.
?  Mail-in-a-Box version check disabled by privacy setting.
✓  System administrator address exists as a mail alias. 
   [administrator@[SUBDOMAIN] ↦ admin@[DOMAIN]]
✓  The disk has 16.54 GB space remaining.
✓  System memory is 60% free.

Network
=======
✓  Firewall is active.
✓  Outbound mail (SMTP port 25) is not blocked.
✓  IP address is not blacklisted by zen.spamhaus.org.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "./status_checks.py", line 344, in run_domain_checks_on_domain
    check_primary_hostname_dns(domain, env, output, dns_domains, dns_zonefiles)
  File "./status_checks.py", line 396, in check_primary_hostname_dns
    if ip == env['PUBLIC_IP'] and not (ipv6 and env['PUBLIC_IPV6'] and normalize_ip(ipv6) != normalize_ip(env['PUBLIC_IPV6'])):
  File "./status_checks.py", line 897, in normalize_ip
    return str(ipaddress.ip_address(ip))
  File "/usr/lib/python3.4/ipaddress.py", line 54, in ip_address
    address)
ValueError: '[Not Set]' does not appear to be an IPv4 or IPv6 address
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./status_checks.py", line 980, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "./status_checks.py", line 65, in run_checks
    run_domain_checks(rounded_values, env, output, pool)
  File "./status_checks.py", line 323, in run_domain_checks
    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
ValueError: '[Not Set]' does not appear to be an IPv4 or IPv6 address

Adding output of:

root@boxname:~# tail -f /var/log/syslog

...

(where "boxname" is the name of the box, and 8.8.8.8 appears in place of the actual box's ipv4)

May 30 15:41:00 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:f8:66:f2:00:08:41:08:00 SRC=78.188.102.189 DST=8.8.8.8 LEN=40 TOS=0x00 PREC=0x00 TTL=240 ID=33855 PROTO=TCP SPT=11643 DPT=81 WINDOW=14600 RES=0x00 SYN URGP=0 
May 30 15:43:23 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:f8:66:f2:00:08:41:08:00 SRC=60.215.245.85 DST=8.8.8.8 LEN=40 TOS=0x00 PREC=0x00 TTL=117 ID=63143 PROTO=TCP SPT=14609 DPT=23 WINDOW=2343 RES=0x00 SYN URGP=0 
May 30 15:43:26 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:f8:66:f2:00:08:41:08:00 SRC=184.105.247.246 DST=8.8.8.8 LEN=40 TOS=0x00 PREC=0x00 TTL=248 ID=54321 PROTO=TCP SPT=51757 DPT=3389 WINDOW=65535 RES=0x00 SYN URGP=0 
May 30 15:43:53 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:f8:66:f2:00:08:41:08:00 SRC=189.218.201.100 DST=8.8.8.8 LEN=40 TOS=0x08 PREC=0x00 TTL=238 ID=4238 PROTO=TCP SPT=29966 DPT=81 WINDOW=14600 RES=0x00 SYN URGP=0 
May 30 15:44:10 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:40:55:39:08:e9:c1:08:00 SRC=188.241.35.75 DST=8.8.8.8 LEN=40 TOS=0x00 PREC=0x00 TTL=49 ID=59769 PROTO=TCP SPT=56376 DPT=23 WINDOW=50211 RES=0x00 SYN URGP=0 
May 30 15:45:01 boxname CRON[8488]: (root) CMD (if [ -x /etc/munin/plugins/apt_all ]; then munin-run apt_all update 7200 12 >/dev/null; elif [ -x /etc/munin/plugins/apt ]; then munin-run apt update 7200 12 >/dev/null; fi)
May 30 15:45:01 boxname CRON[8489]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
May 30 15:45:01 boxname CRON[8490]: (munin) CMD (if [ -x /usr/bin/munin-cron ]; then /usr/bin/munin-cron; fi)
May 30 15:46:48 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:f8:66:f2:00:08:41:08:00 SRC=211.117.167.169 DST=8.8.8.8 LEN=40 TOS=0x00 PREC=0x00 TTL=50 ID=27574 PROTO=TCP SPT=25342 DPT=23 WINDOW=2376 RES=0x00 SYN URGP=0 
May 30 15:47:20 boxname kernel: [UFW BLOCK] IN=eth0 OUT= MAC=f2:3c:91:60:eb:83:40:55:39:08:e9:c1:08:00 SRC=94.177.196.205 DST=8.8.8.8 LEN=37 TOS=0x00 PREC=0x00 TTL=45 ID=56371 DF PROTO=UDP SPT=53799 DPT=123 LEN=17 
May 30 15:48:47 boxname named[32364]: received control channel command 'flush'
May 30 15:48:47 boxname named[32364]: flushing caches in all views succeeded
May 30 15:48:47 boxname postfix/submission/smtpd[9118]: connect from unknown[2400:8902::f03c:91ff:fe60:eb83]
May 30 15:48:47 boxname postfix/smtpd[9119]: connect from unknown[2400:8902::f03c:91ff:fe60:eb83]
May 30 15:48:47 boxname postfix/submission/smtpd[9118]: lost connection after CONNECT from unknown[2400:8902::f03c:91ff:fe60:eb83]
May 30 15:48:47 boxname postfix/submission/smtpd[9118]: disconnect from unknown[2400:8902::f03c:91ff:fe60:eb83]
May 30 15:48:47 boxname postfix/smtpd[9119]: lost connection after CONNECT from unknown[2400:8902::f03c:91ff:fe60:eb83]
May 30 15:48:47 boxname postfix/smtpd[9119]: disconnect from unknown[2400:8902::f03c:91ff:fe60:eb83]
May 30 15:48:47 boxname postfix/smtpd[9107]: connect from li1689-116.members.linode.com[8.8.8.8]
May 30 15:48:47 boxname postfix/smtpd[9107]: lost connection after CONNECT from li1689-116.members.linode.com[8.8.8.8]
May 30 15:48:47 boxname postfix/smtpd[9107]: disconnect from li1689-116.members.linode.com[8.8.8.8]
May 30 15:48:48 boxname postfix/submission/smtpd[9108]: connect from li1689-116.members.linode.com[8.8.8.8]
May 30 15:48:48 boxname postfix/submission/smtpd[9108]: lost connection after CONNECT from li1689-116.members.linode.com[8.8.8.8]
May 30 15:48:48 boxname postfix/submission/smtpd[9108]: disconnect from li1689-116.members.linode.com[8.8.8.8]
```

**Comment by yodax** [comment]
This should be fixed in master. Are you running it via the curl setup?

**Comment by just4t** [comment]
Would not be easier to make, from master, a bug fix official new release?

**Comment by pohutukawanz** [comment]
Hi and thank you for replying.

Yes, I deployed the box at Linode → SSH session as root and then

`curl -s https://mailinabox.email/setup.sh | sudo bash`

Hopefully that's what you were asking!

**Comment by just4t** [comment]
If you finally wish to install the currently dev. 'master' you must use the 'git' way as follows:

```
apt-get update && apt-get upgrade -y
apt-get install git
git clone https://github.com/mail-in-a-box/mailinabox
cd mailinabox
setup/start.sh
```

hope this helps.

**Comment by yodax** [comment]
Releasing is up to @joshdata. A release requires extra time from him to support and test. 

@just4t steps should work in the mean time.

**Comment by just4t** [comment]
> Releasing is up to @JoshData. A release requires extra time from him to support and test.

I have no doubt that's the reason but... answering the same question again and again takes time, too. Isn't it?
- A 'new features / improvement(s)' release can be delayed as far as needed but when a release means a bug fix i think NOT (just my opinion, of course!)

**Comment by pohutukawanz** [comment]
Thanks to @yodax and @just4t for the awesome, quick help!

@just4t is that what I would use from scratch (i.e. newly-deployed box) or an upgrade?

Thanks!

**Comment by pohutukawanz** [comment]
@yodax Thanks Michael I redeployed the box and followed your instructions and now I have an install (along with a bunch of issues to resolve!).

Thank you again!

**Comment by just4t** [comment]
@pohutukawanz to update / upgrade 'Master' from 'Master' in the future your could use:

```
apt-get update && apt-get upgrade -y
cd mailinabox
git fetch
git pull
git checkout
setup/start.sh
```
Hope this helps!
