### ISSUE TITLE
0.23: problems in the web ui after update

### ISSUE THREAD

**Issue by hachre** [mail-in-a-box/mailinabox#1184]
Seems the update to 0.23 didn't go through smoothly for me.

I've found no ability to delete aliases in the updated web ui (just to edit them). Upon closer inspection of the problem, I found out that there's several paths the site attempts to load from the server which result in a 404:
- https://example.com/admin/fonts/glyphicons-halflings-regular.woff2
- https://example.com/admin/fonts/glyphicons-halflings-regular.woff
- https://example.com/admin/fonts/glyphicons-halflings-regular.ttf
- https://example.com/admin/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular

The aliases page only seems to have an edit button in front of each alias, but I see no way to delete anything. Is it possible that a potential trash icon isn't loading due to the errors above?

**Comment by yodax** [comment]
@macmedia do you have time to look into to this? I can as well but I won't have time for at least half a day.

**Comment by just4t** [comment]
Confirmed reported here, too right after upgrading to 0.23 ... 'trash' icons missing for custom aliases (perhaps still trying to get them from CDN instead than being served locally, too ...!?)

**Comment by yodax** [comment]
This has to do with that change yes. I'll get to it later today.

**Comment by yodax** [comment]
PR submitted https://github.com/mail-in-a-box/mailinabox/issues/1185

If you are feeling adventurous you could give it a spin.

**Comment by JoshData** [comment]
Fixed/merged, and I've released v0.23a with this change.

**Comment by hachre** [comment]
Thank you @yodax and @JoshData! I've tested this by updating to 0.23a and it's working great now!
