### ISSUE TITLE
0.23 - Installing Z-Push took a long time to complete

### ISSUE THREAD

**Issue by hieuhuynh93** [mail-in-a-box/mailinabox#1186]
I'm running update but go to install z-push step, it take a long time, i'm waiting for it about 30 mins. 

Image: [http://imgur.com/SIvDNaI](http://imgur.com/SIvDNaI)

**Comment by yodax** [comment]
The image doesn't work. If you have a large user base for z-push it might be rebuilding the states. On my box with just one user it took some time. 

What does top and z-push-top say?

**Comment by hieuhuynh93** [comment]
Thanks for reply, it just completed after 40mins installing.

**Comment by hieuhuynh93** [comment]
I have another issue, why did fail2ban need more CPU ? My CPU always 100% if I turn on fail2ban service.

**Comment by yodax** [comment]
There is noting in the current release relating to fail2ban. You could check the log to see what it is doing.
