### ISSUE TITLE
MiaB front page shows 0.22 as active version

### ISSUE THREAD

**Issue by dyve** [mail-in-a-box/mailinabox#1188]
The frontpage of mailinabox.email shows v0.22 as active version, not v0.23 (or now v0.23a).

**Comment by hieuhuynh93** [comment]
I think you can try run command "**sudo mailinabox**" to re-configure your box. Or not you should run upgrade again.

**Comment by yodax** [comment]
@hieuhuynh93 I think @dyve means the public website. :smile: That wasn't updated. It is now. Thanks!

**Comment by dyve** [comment]
That's right @yodax. Thanks for the fix.
