### ISSUE TITLE
Static web hosting for a subdomain?

### ISSUE THREAD

**Issue by gg2001** [mail-in-a-box/mailinabox#1189]
How do I add static site hosting for a subdomain?
Say if I had example.com and I had static site hosting for it. How would I add static hosting for abcd.example.com?

**Comment by hachre** [comment]
You need to add a dummy mail alias for the domain. While creating the alias, the domain will automatically be added for web hosting as well.

**Comment by gg2001** [comment]
Ahh ok, working great.

**Comment by sefeng211** [comment]
I wanted to achieve the same thing, however it didn't work for me. I tried both creating a new user or alias, none of them created a new static web hosting for me.
