### ISSUE TITLE
nextcloud apps and files?

### ISSUE THREAD

**Issue by grauschnabel** [mail-in-a-box/mailinabox#1190]
Hi there,

As I see you use nextcloud 10 now, and the goal is to have calendars and contacts there.  But is it also supposed to use it as a file sharing server and so on?  I would like to do that, because it is there and I don't need any extra server or configuration for that.

But I would not only like to use it for files, but also for tasks, and that I think needs to have an extra app to bee installed.  but there is no 'admin' account for nextcloud, right?
So how to do that?
Thanks,
Martin

**Comment by hieuhuynh93** [comment]
You can run this file to have admin permission: tools/owncloud-unlockadmin.sh
