### ISSUE TITLE
Ability to whitelist domain or email in system UI

### ISSUE THREAD

**Issue by geekafy** [mail-in-a-box/mailinabox#1192]
Hi Guys,

I would be great to have the ability to whitelist a domain or email in the system UI.
Until then, is there another way to do this?

I have a legit email that always go to spam.

Thanks!

(I'm loving mail-in-a-box!) :-)

**Comment by wioxjk** [comment]
There is always a reason that emails is placed in the spamfolder thou :)

**Comment by geekafy** [comment]
Yep, agreed!
But my kid's camp coordinator does not spam me. :-)

**Comment by wioxjk** [comment]
Just curious, why does the message go to spam? What does your logs say?

**Comment by geekafy** [comment]
No clue, will take a look, where is the log situated?

**Comment by wioxjk** [comment]
/var/log/mail.log I think

**Comment by geekafy** [comment]
Just checked, nothing in the logs :-(

**Comment by yodax** [comment]
Check the headers of the email. That should contain more information. Also moving the mail from spam to inbox should train the filter. Setting a rule for the from address in roundcube should work as a whitelist I think.

**Comment by geekafy** [comment]
Here are the headers below.
It's interesting what I found.... the sender has a gmail account but the mail is sending from what looks like a VPS from GoDaddy who's IP was flagged... The camp must be using some sort of hosted management system that sends out mail on the camps behalf....

How... I doubt they will change anything on their end... Will the creations of filters in RoundCube teach the server to not flag as spam even when I'm usually using IMAP to get my email?

------
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on box.xxxxxxxx.com
X-Spam-Flag: YES
X-Spam-Level: *****
X-Spam-Status: Yes, score=5.4 required=5.0 tests=DKIM_ADSP_CUSTOM_MED,
	FREEMAIL_FROM,FROM_LOCAL_NOVOWEL,HK_RANDOM_FROM,HTML_MESSAGE,
	HTML_MIME_NO_HTML_TAG,MIME_HTML_ONLY,NML_ADSP_CUSTOM_MED,RCVD_IN_DNSWL_NONE,
	RCVD_IN_MSPIKE_H3,RCVD_IN_MSPIKE_WL,REPLYTO_WITHOUT_TO_CC autolearn=no
	autolearn_force=no version=3.4.0
X-Spam-Report: 
	* -0.0 RCVD_IN_DNSWL_NONE RBL: Sender listed at http://www.dnswl.org/, no
	*      trust
	*      [208.109.80.74 listed in list.dnswl.org]
	*  0.0 HK_RANDOM_FROM From username looks random
	*  0.5 FROM_LOCAL_NOVOWEL From: localpart has series of non-vowel letters
	*  0.0 DKIM_ADSP_CUSTOM_MED No valid author signature, adsp_override is
	*      CUSTOM_MED
	*  0.0 FREEMAIL_FROM Sender email is commonly abused enduser mail provider
	*      (xxxxxx[at]gmail.com)
	* -0.0 RCVD_IN_MSPIKE_H3 RBL: Good reputation (+3)
	*      [208.109.80.74 listed in wl.mailspike.net]
	*  1.1 MIME_HTML_ONLY BODY: Message only has text/html MIME parts
	*  0.0 HTML_MESSAGE BODY: HTML included in message
	*  1.9 REPLYTO_WITHOUT_TO_CC No description available.
	*  0.6 HTML_MIME_NO_HTML_TAG HTML-only message, but there is no HTML tag
	* -0.0 RCVD_IN_MSPIKE_WL Mailspike good senders
	*  1.2 NML_ADSP_CUSTOM_MED ADSP custom_med hit, and not from a mailing list

**Comment by wioxjk** [comment]
Whoever the genius who did it... 
They are propably sending out BULK emails, and therefore they are getting blacklisted,

**Comment by stan3** [comment]
Might work for you to create extra spamassassin config, e.g.

$ cat /etc/spamassassin/local2.cf
whitelist_from example@example.org

$ /etc/init.d/spampd restart

**Comment by geekafy** [comment]
OK so based on what was mentioned by stan3, I got some documentation from https://wiki.apache.org/spamassassin/ManualWhitelist 

I added the following code to the bottom my global config file `/etc/mail/spamassassin/local.cf`

```
# whitelist:
whitelist_from  name@email.com
```

If you want to add multiple addresses, you just add a space and add the following one right after.

```
# whitelist:
whitelist_from  name@email.com name2@email.com
```

It is important to run `/etc/init.d/spampd restart` after you save the file to enable the changes.

The old "spam" email comes right in the inbox.

This is what is now in the headers:

```
X-Spam-Report: 
	* -100 USER_IN_WHITELIST From: address is in the user's white-list
	*  0.0 SPF_HELO_FAIL SPF: HELO does not match SPF record (fail)
	*      [SPF failed: Please see http://www.openspf.org/Why?
```

Thanks for the help!
