### ISSUE TITLE
checking IPV6 notation

### ISSUE THREAD

**Issue by tynie** [mail-in-a-box/mailinabox#1200]
Hi,

i think this is a bug, isnt it?

> This domain should resolve to your box's IP address (AAAA 2a01:XXXX:0191:64d0:0000:0000:0000:0004) if you would like the box to serve webmail or a website on this domain. The domain currently resolves to 2a01:XXXX:191:64d0::4 in public DNS. It may take several hours for public DNS to update after a change. This problem may result from other issues listed here.

It´s the same IPv6 address but Mail in a box isn´t recognize it.

**Comment by JoshData** [comment]
See #907.
