### ISSUE TITLE
Wrong php7.1-soap version after upgrading to NextCloud12 using PHP7

### ISSUE THREAD

**Issue by xetorixik** [mail-in-a-box/mailinabox#1202]
@yodax Thanks for your NextCloud12 using PHP7 #1140 commit. 
It is working fine.

There is only one problem.  Actually a small problem or a bug.
After upgrading my test machine to the latest Mail in a box master with Nextcloud 12. 

The system wants to upgrade php-soap, and only php-soap to php7.1-soap after dist-upgrading the system. Which is strange because php7.0 is used.

It could be a repo issue?

Test machine is upgraded from v0.23a to the latest master.
No other repo's or packages other than htop are installed, it's all vanilla. 

> The following NEW packages will be installed:
>   php7.1-soap
> The following packages will be upgraded:
>   libbsd0 libedit2 libjbig0 libssl-doc php-soap pkg-php-tools
> 6 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 1,822 kB of archives.
> After this operation, 433 kB of additional disk space will be used.
> Do you want to continue? [Y/n]

**Comment by yodax** [comment]
That's weird. I've got a fresh 14.04 with only ever NextCloud 12 installed which gives this result:

```
$ apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
```
apt list --installed | grep soap

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

php-soap/trusty,now 1:7.1+53~ubuntu14.04.1+deb.sury.org+1 all [installed,automatic]
php7.0-soap/trusty,now 7.0.21-1~ubuntu14.04.1+deb.sury.org+1 amd64 [installed]
php7.1-soap/trusty,now 7.1.7.retag-1+ubuntu14.04.1+deb.sury.org+1 amd64 [installed,automatic]

```

And an older box which gives this result:

```
apt-get dist-upgrade
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libvpx1 php-http-request php-net-dime php-net-url
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  php7.1-soap
The following packages will be upgraded:
  libbsd0 libedit2 libjbig0 libssl-doc php-soap pkg-php-tools
6 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,822 kB of archives.
After this operation, 433 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```
```
apt list --installed | grep soap

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

php-soap/trusty,now 0.13.0-1 all [installed,upgradable to: 1:7.1+53~ubuntu14.04.1+deb.sury.org+1]
php7.0-soap/trusty,now 7.0.21-1~ubuntu14.04.1+deb.sury.org+1 amd64 [installed]
```

So it seems a fresh box gets 7.1-soap and an older one wants it installed only when running dist-upgrade. Seeing that my fresh box has it (and works) there is probably no harm in updating. 

The culprit is php-auth
```
aptitude why php7.1-soap --show-summary
Packages requiring php7.1-soap:
  php-auth
```
It requires a minimum version of soap and goes with the latest it can find on a fresh install unless an older one exists:
```
aptitude why php7.1-soap
i   php-auth Recommends php-soap (>= 0.9.0)
i A php-soap Depends    php7.1-soap
```

**Comment by xetorixik** [comment]
Hmm so it is an repo issue because both php70 and php71 extensions are included in the same repo, 
and the system will pick the latest package. If i'm correct.

I am not a Ubuntu adept but with RHEL you could exclude packages from a repo. 
If that's also possible with Ubuntu it could be a solution to force the system to install the right php70 package.

You should not want to mix php70 and php71 packages. Possibly non-stable, dependency problems  etc.

Anyway php71 isn't an option at all?

**Comment by yodax** [comment]
> Anyway php71 isn't an option at all?

We would also have to install php7. I checked during the creation of the PR, we would need php5 to upgrade from owncloud, php7 to go to nextcloud 11 and then php7.1 to go to nextcloud 12. I don't know if z-push and round cube support it. Ideally we run everything on one version.

Php-auth thinks it can work with any version. Maybe we can tweak it, but I'm not sure it's a problem. (granted it's odd)

**Comment by xetorixik** [comment]
Roundcube 1.3: https://github.com/roundcube/roundcubemail/releases
Support for version PHP 7.1 check.

Nextcloud 11: https://help.nextcloud.com/t/does-nextcloud-11-support-php-7-1/6241/4
Support for version PHP 7.1, seems a bit problematic. As shown in the link above.
One user reports works perfectly, the other reports problems.

Z-push 2.3.7: http://download.z-push.org/final/2.3/z-push-2.3.7.txt
Nothing about PHP 7.1. Z-push is compatible with PHP 7 since version 2.3.4, thats all.
http://download.z-push.org/final/2.3/z-push-2.3.4.txt

Too bad that Nextcloud requires PHP 7, PHP 5.5 works fine.
But no other choice. It seems to me now, that fixing PHP7 soap is the best option.

**Comment by yodax** [comment]
I'm still not convinced there is an issue. PHP-auth has one version, they build it against all php versions, see here: https://github.com/PHPAuth/PHPAuth. It requests the latest version and that is what it gets.

**Comment by xetorixik** [comment]
Its fine to me.
I've reported it and you looked at it. 

It is up to you as creator of this feature to decide.
