### ISSUE TITLE
Provision a certificate: Something unexpected went wrong...

### ISSUE THREAD

**Issue by myfirstnameispaul** [mail-in-a-box/mailinabox#1203]
I have a standalone server on a home ISP that is confirmed to support mail server requirements. (PLEASE note: I have successfully built and maintained my own mail stacks on this ISP connection.)

I choose to call my 'box' mail and my domain is example.net and have DNS configured for example.net and mail.example.net. I have not configured a DNS entry for www.example.net.

I have confirmed that from outside the network, example.net and mail.example.net successfully load in a browser, though the browser is automatically forwarded to the secure session when requesting insecure session.

When I try to provision certificates, I get the following output from the interface:

> Something unexpected went wrong: [NeedToInstallFile('http://example.net/.well-known/acme-challenge/BLtEhniQmmlVCDW5RdOLxt472FMQ_rh1huOthBr0Vf0', 'BLtEhniQmmlVCDW5RdOLxt472FMQ_rh1huOthBr0Vf0.7rlrpUSqgphc7SRmQQiEtqYy2wEQ0woPt-ipyw7F37g', 'BLtEhniQmmlVCDW5RdOLxt472FMQ_rh1huOthBr0Vf0')]
> Log:
> Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
> Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
> Reusing existing challenges for mail.example.net.
> The challenges for mail.example.net have been accepted.
> Reusing existing challenges for example.net.
> Validation file is not present --- a file must be installed on the web server.
> Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
> Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
> Reusing existing challenges for mail.example.net.
> The challenges for mail.example.net have been accepted.
> Reusing existing challenges for example.net.
> Validation file is not present --- a file must be installed on the web server.

I thought this might have something to do with not having a www subdomain, so I added www subdomain and provisioning still fails:

> Something unexpected went wrong: [NeedToInstallFile('http://example.net/.well-known/acme-challenge/BLtEhniQmmlVCDW5RdOLxt472FMQ_rh1huOthBr0Vf0', 'BLtEhniQmmlVCDW5RdOLxt472FMQ_rh1huOthBr0Vf0.7rlrpUSqgphc7SRmQQiEtqYy2wEQ0woPt-ipyw7F37g', 'BLtEhniQmmlVCDW5RdOLxt472FMQ_rh1huOthBr0Vf0'), NeedToInstallFile('http://www.example.net/.well-known/acme-challenge/-BbM1B9Una4yiN9tZCIBwvV62htbqigF6pxDn_nM760', '-BbM1B9Una4yiN9tZCIBwvV62htbqigF6pxDn_nM760.7rlrpUSqgphc7SRmQQiEtqYy2wEQ0woPt-ipyw7F37g', '-BbM1B9Una4yiN9tZCIBwvV62htbqigF6pxDn_nM760')]
> Log:
> Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
> Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
> Reusing existing challenges for mail.example.net.
> The challenges for mail.example.net have been accepted.
> Reusing existing challenges for example.net.
> Validation file is not present --- a file must be installed on the web server.
> Requesting new challenges for www.example.net.
> Validation file is not present --- a file must be installed on the web server.
> Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
> Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
> Reusing existing challenges for mail.example.net.
> The challenges for mail.example.net have been accepted.
> Reusing existing challenges for example.net.
> Validation file is not present --- a file must be installed on the web server.
> Reusing existing challenges for www.example.net.
> Validation file is not present --- a file must be installed on the web server.

**Comment by elderlabs** [comment]
bump.

**Comment by 3rods** [comment]
I also have this same issue. 

`Something unexpected went wrong: [NeedToInstallFile('http://mail.xxxx.life/.well-known/acme-challenge/h9ejZI-c-_ttC-h2_riBW_gZlysLmQZYEOd0JX9Gfgc', 'h9ejZI-c-_ttC-h2_riBW_gZlysLmQZYEOd0JX9Gfgc.jiPgj_8zMLFlXuX858tjQAeD-SrGMMmrRBziTazW6_I', 'h9ejZI-c-_ttC-h2_riBW_gZlysLmQZYEOd0JX9Gfgc'), NeedToInstallFile('http://xxxx.life/.well-known/acme-challenge/vSvDQBA7Z73VCoOnaneH3m-4PJCV2-cC97POJGAKCrM', 'vSvDQBA7Z73VCoOnaneH3m-4PJCV2-cC97POJGAKCrM.jiPgj_8zMLFlXuX858tjQAeD-SrGMMmrRBziTazW6_I', 'vSvDQBA7Z73VCoOnaneH3m-4PJCV2-cC97POJGAKCrM'), NeedToInstallFile('http://www.xxxx.life/.well-known/acme-challenge/Fd4o15fQUQ0D9eZkltJAtEnqUelqA0SwzoBMliZm23g', 'Fd4o15fQUQ0D9eZkltJAtEnqUelqA0SwzoBMliZm23g.jiPgj_8zMLFlXuX858tjQAeD-SrGMMmrRBziTazW6_I', 'Fd4o15fQUQ0D9eZkltJAtEnqUelqA0SwzoBMliZm23g')]`

**Comment by elderlabs** [comment]
An easy fix is to symbolically link the certificate .well-known folder to the web folder with proper permissions. Figured this out after a few hours of debugging.

**Comment by tebs85** [comment]
Hi guys maybe I'm just being dumb. Where is the .well-known folder located?

**Comment by 3rods** [comment]
I had to actually create it in my web root (/var/www/html/.well-known/), but I needed to use the "alternative" method of verification for my deployment.

**Comment by tebs85** [comment]
Finally got it to work thanks.

**Comment by collinjlesko** [comment]
@tebs85 what exactly did you do to correct this? I am getting the exact same error with a cert expiring in 4 days... My root www folder is under /home/user-data/www/default

**Comment by tebs85** [comment]
Have you run recent updates?

**Comment by collinjlesko** [comment]
@tebs85 @elderlabs 

No, I haven't run recent updates because I don't necessarily trust them, and my version is working perfect...

However, I did fix it. I had some old redirects and server_name conflicts in the local.conf that some how made there way in there.. I am not sure how, but whenever I create a new sub-domain, old code is copied into that file (including the re-writes)... Where is mail-in-a-box (or rather nginx?) copying that from??

**Comment by JoshData** [comment]
Fixed by 2a72c800f6b7c4910f5fa294d7a82ec805cdf020.
