### ISSUE TITLE
Cleanup after php7.0 installation

### ISSUE THREAD

**Issue by yodax** [mail-in-a-box/mailinabox#1205]
Now that Nextcloud 12 is in and all php code runs under php7.0 we can do the following tasks:

- [ ] Factor out the upgrades of ownCloud to a separate file
- [ ] Rename all ownCloud paths to Nextcloud.
- [ ] Remove all php5 packages

Any thoughts? I don't mind picking up some work, but thought we should discuss it first.

**Comment by JoshData** [comment]
I think we may want to just keep things as they are for now. We should shift our focus toward what's coming in Ubuntu 18.04 and let the cleanup be a part of that shift.

**Comment by yodax** [comment]
That makes sense. I'll get that effort going again by testing the work on the test set. And looking at the port/branch for 16.04.
