### ISSUE TITLE
Secondary nameserver won't work after commit #1177

### ISSUE THREAD

**Issue by xetorixik** [mail-in-a-box/mailinabox#1208]
Adding a secondary nameserver won't work using GIT with commit #1177 and gives the following error message:

```
Secondary DNS
Invalid name.
```

Trow back to the GIT code before commit 1177, reboot system and it works fine.

```
Secondary DNS
updated DNS .................
```

Verified the raw NSD config. 
With commit 1177 no changes written to the config, without commit 1177 changes written to the config as it should be.

P.s. No secondary nameserver used previously by the test system.
Added for the first time.

**Comment by yodax** [comment]
Thanks for the detailed report! I created a PR for this.

**Comment by yodax** [comment]
Closed by: https://github.com/mail-in-a-box/mailinabox/issues/1209
