### ISSUE TITLE
Feature: Adding a port option for Rsync backup

### ISSUE THREAD

**Issue by slave2anubis** [mail-in-a-box/mailinabox#1210]
Hi. I am using the mailinabox for a few years now, and i can say its very nice!
I have one suggestion: Please add a port field to the rsync backup option since some of us use custom ports for ssh. Currently i hard coded the port in the "Backup.py" file, but it would be nice to have a easy way of setting the port.

Thank you.

**Comment by yodax** [comment]
A quick solution is to edit or add a config file under ~/root/.ssh/config. Add your host with the port in there. That the ssh client will use that port. 

It would be nice if it is in the ui though.

**Comment by yodax** [comment]
Duplicate: https://github.com/mail-in-a-box/mailinabox/issues/1147
