### ISSUE TITLE
Domain alias won't accept puny code

### ISSUE THREAD

**Issue by Zhann** [mail-in-a-box/mailinabox#1214]
I can't add `xn--sw8hj0a.ws` or `🛡🔼.ws` as address. 

For example when trying to set up as domain alias (either of the two above), I get: `Invalid email address (@xn--sw8hj0a.ws)`. Even though this domain is perfectly valid. 

I think the problem resides in [mailconfig.py#validate_email](https://github.com/mail-in-a-box/mailinabox/blob/19a928e4ecb84480e61ed0e8959339eb0682725d/management/mailconfig.py#L8) though I don't see how exactly.

**Comment by JoshData** [comment]
Not all Unicode strings are valid domain names per IDNA 2008. I think that's probably the case here. Under IDNA 2008, roughly only letter/number characters are permitted and not symbols.

If you were able to register that domain, the registry is probably operating under old rules and you'll run the risk that the domain will become invalid and/or inaccessible when browsers fully switch to IDNA 2008 (from IDNA 2003).
