### ISSUE TITLE
Join the Nextcloud Conference and have your say!

### ISSUE THREAD

**Issue by jospoortvliet** [mail-in-a-box/mailinabox#1222]
Hi Mail-in-a-Box team!

In a few weeks at the TU Berlin we kick off the Nextcloud Conference. It'll be a very open event, not just in terms of free entry but we will cover all thinks privacy, self-hosting, security, surveillance and more. Our keynote speaker, former Mozilla president Tristan Nitot, is right now CTO of Cozy Cloud - another private, open source cloud project. Just to give an indication as to how open the event is :smile_cat: 

We expect between 100 and 200 people, maybe more. And I would like to invite you folks as well! Think of it: lots of interesting people, nice hacking rooms, free network :signal_strength: food & drinks :cake: :beers: what could go wrong?

Many of us will just use the week days to work from the event location and you're welcome to do that, too!

Saturday/Sunday we have a program, however, with a opening keynote and then a series of short lighting talks to kick off discussions and collaboration. In the afternoon (after a nice lunch) you can either go back to hacking or join one of the workshops.

And yes, this is ALSO an invitation to give one or multiple talks about Mail in a Box or one of the other projects and subjects you care about!

I hope I've not abused the issue tracker too much - and intrigued some of you. Consider joining! Register & submit talks or just learn more on https://nextcloud.com/conf

**Comment by chriskacerguis** [comment]
This doesn't really seem the best place for this.  Perhaps the forum?

**Comment by jospoortvliet** [comment]
Sorry... You have a forum?

/me goes search for that!
