### ISSUE TITLE
dns update does not work

### ISSUE THREAD

**Issue by grauschnabel** [mail-in-a-box/mailinabox#1227]
I changed an ip of a subdomain, but a few days after I always get the ip which I had before. The zone file of nsd includes the new ip but even `nslookup sub.mydomain.com box.mymailinabox.com` returns the old ip.

Same after running `sudo mailinabox` again.

What can I do?

**Comment by matDOTviguier** [comment]
Have you tried to flush the dns cache from where you typed the `nslookup` command ?

**Comment by grauschnabel** [comment]
I accidentally deleted the xfr frm the settings... At this works again.
