### ISSUE TITLE
Upgrade doesn't work from v0.20 to v0.23a

### ISSUE THREAD

**Issue by matDOTviguier** [mail-in-a-box/mailinabox#1230]
I launched a update pass on all of our productions servers.
Here comes the turn of MiaB ...

On one server, we stucked in v0.20 (don't ask why, i don't know ...).

> admin-mail@mail:~/mailinabox/conf$ curl -s https://mailinabox.email/setup.sh | s                                                                                                     udo bash
[sudo] password for admin-mail: **###**
Updating Mail-in-a-Box to v0.23a . . .
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
error: Your local changes to the following files would be overwritten by checkou                                                                                                                                                             t:
        conf/nginx-alldomains.conf
Please, commit your changes or stash them before you can switch branches.
Aborting
Update failed. Did you modify something in /home/admin-mail/mailinabox?

Of course, it is the second try (delta was not à 0 the first time).
We did a quick and dirty **apt-get update** and **apt-get upgrade** before trying the **git status**. Here is the result.

> HEAD detached at v0.20
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  modified:   nginx-alldomains.conf
  no changes added to commit (use "git add" and/or "git commit -a")

Checked the file present on the server with an sha256sum
 66aae104a585018fd8dedc836c06833e09343ec8071479e537bd79e8d483a8b2  nginx-alldomains.conf 

It is the same as in master.

What the hell it is ?

**Comment by matDOTviguier** [comment]
The file has been stashed with the same result.
Once commited, the upgrade continue ...

**Comment by matDOTviguier** [comment]
Finally, the MiaB on this box crashes ...

Try to v0.20 -> v0.21 -> etc ...

**Comment by hachre** [comment]
Disclaimer: I'm not a dev but have this project running on several servers myself.

I'd try this (as root):
```
cd /
tar cvf /root/mailinabox_backup.tar /root/mailinabox
rm -R /root/mailinabox
curl -s https://mailinabox.email/setup.sh | bash
```

**Comment by matDOTviguier** [comment]
I have datas (and customers) on the server.
I have to fortk the vm. Too late tonight.

**Comment by hachre** [comment]
The important data is stored in `/home/user-data`.

**Comment by matDOTviguier** [comment]
ok, let's try on hot machine ...

**Comment by matDOTviguier** [comment]
This time, a bit more verbose : 

> Your Mail-in-a-Box is running.
> 
> Please log in to the control panel for further instructions at:
> 
> Traceback (most recent call last):
>   File "management/status_checks.py", line 993, in <module>
>     ssl_certificates = get_ssl_certificates(env)
>   File "/home/admin-mail/mailinabox/management/ssl_certificates.py", line 46, in get_ssl_certificates
>     pem = load_pem(load_cert_chain(fn)[0])
>   File "/home/admin-mail/mailinabox/management/ssl_certificates.py", line 761, in load_pem
>     return serialization.load_pem_private_key(pem, password=None, backend=default_backend())
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
>     from cryptography.hazmat.backends.openssl.backend import backend
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
>     from cryptography.hazmat.backends.openssl.backend import backend
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
>     from cryptography.hazmat.bindings.openssl import binding
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
>     Binding.init_static_locks()
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
>     cls._ensure_ffi_initialized()
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
>     cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
>   File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 84, in build_conditional_library
>     if not getattr(lib, condition):
> AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_X509_STORE_CTX_GET_ISSUER'
> https://x.y.z.210/admin
> 
> You will be alerted that the website has an invalid certificate. Check that
> the certificate fingerprint matches:
> 
> 01:1A:17:A7:D7:76:9A:1D:67:30:67:F4:DE:41:21:B8:DD:F4:CB:2A:F2:C2:61:20:23:5B:23:52:7F:FC:B7:24
> 
> Then you can confirm the security exception and continue.
> 
> admin-mail@mail:~$

**Comment by hachre** [comment]
Why is everything in `/home/admin-mail` and not in `/root` ? Did `apt-get update` and `apt-get dist-upgrade` run?

**Comment by yodax** [comment]
Could you try the steps mentioned here: https://discourse.mailinabox.email/t/version-0-21-is-posted/1678

**Comment by matDOTviguier** [comment]
This method lets the update be OK. Issue Closed.
