### ISSUE TITLE
Can't load older emails in Exchange account

### ISSUE THREAD

**Issue by axd** [mail-in-a-box/mailinabox#1245]
Hi,

I've set up an email account for my phone using "Exchange" service (Gmail app, android) for contacts and calendar sync with my account.

The problem is when I reach the last (downloaded) email in any folder it doesn't load the older ones, I don't know if it's a limitation for Exchange accounts or it's SOGo limitation, if so, it is possible to override it? So I can go further loading older emails until the very first one if I want to.

Regards.

**Comment by hachre** [comment]
There's usually a control somewhere in the Exchange-related settings that allows you to define how much you want to sync. It usually defaults to 1 month. On iOS you can set it to unlimited, but I don't know how it works on Android.
