### ISSUE TITLE
master branch is now a release candidate for v0.24

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#1246]
If you can, please test the master branch ahead of the release of v0.24 and let me know here if it works or if you encounter a problem. Thanks!

Changes are listed in [CHNAGELOG.md](https://github.com/mail-in-a-box/mailinabox/blob/master/CHANGELOG.md#in-development).

**Comment by yodax** [comment]
Thanks for the upcoming release :smile:

It's running (well was running mostly already) on my main box now.

**Comment by hachre** [comment]
Going to test this here very soon after finishing backups and report back!

**Comment by hachre** [comment]
The mail-in-a-box in master called itself version v0.23a-18-g35b8a14. I updated from v0.23a.

### During the installation, I noted the following things:
- Everything went through without any apparent errors during the update.
- The Nextcloud updates were pretty exciting and also showed no errors.
- The "Installing Munin" step took surprisingly long, but it went through as well.
- After it was done, I ran `apt-get update && apt-get dist-upgrade` and it wanted to install `php7.1-soap`, so I did that.

### After the installation was done, I did some testing:
#### I tried out sending and receiving mail via
- SMTP / IMAP from Thunderbird on my PC & Spark on my iPhone 
- ActiveSync from Apple's Mail on my iPhone
- Webmail
#### I also tried Contacts via ActiveSync to my iPhone

### Results
When using SMTP for the first time from Thunderbird, I had to re-enter my password once.
Everything seems to work correctly, I noticed nothing that wasn't working!

**Comment by hachre** [comment]
A few days later and I've noticed the following problem: When leaving Roundcube open in a tab it no longer automatically gets mail despite me having it set to "every minute". I always have to press the Refresh button or reload the browser manually. Does anyone else experience this?

**Comment by JoshData** [comment]
I don't use Roundcube much but I just tried it and it picked up a new email OK. (Which isn't to say I don't believe you, just that I can't reproduce it.)

Thanks everyone for the feedback so far. It's all very helpful.

**Comment by JoshData** [comment]
I've posted the release.

**Comment by hachre** [comment]
@JoshData No problem, it might be dependent on my browser, which is a beta and got an update at the same time.

**Comment by JoshData** [comment]
If you can figure it out we can always fix post-release. :)
