### ISSUE TITLE
Hidden Master DNS server

### ISSUE THREAD

**Issue by DenseComet** [mail-in-a-box/mailinabox#1247]
Is there an option for a hidden master so that secondary DNS servers answer all queries, but fetch the zone from mailinabox?

The only necessary change would be to have an option to remove only the 
NS box.example.com
record removed. This would completely hide mailinabox as the master for the domain.

Right now, we can just not put box.example.com as a nameserver in the registrar, but it is still listed as a nameserver by the child nameservers, so some clients still query it.

**Comment by JoshData** [comment]
This seems like an advanced use case that is out of scope for us.
