### ISSUE TITLE
Multiple questions and great job!

### ISSUE THREAD

**Issue by Extarys** [mail-in-a-box/mailinabox#1248]
Hey guys!

GREAT WORK! OMG!

Ok now that is out of the way :P

I run a nextcloud instance with 2-3 users but it would be a little pain to backup, any way I can still install Mail in a box without a fresh instance?

Also, any pans on merging the 16.04 branch soon? I'm on stretch :D

Or is there any advantages generally speaking of using a 16.04 server instead of an "older" 14.04? I always though the latest offer more security, but I also know it offers more incompatibility.

I would've prefer a debian release of this since debian is considered more secure, :( BUUUT I don't mean that the author(s) didn't do a great job please don't read me wrong.

In the same note, ubuntu is owned by a big company, and mail in a box purpose is to get away from that, isn't that controversial? I know it's a big step up from Google Drive, but still. Should I be afraid of canonical making a poisonous update to spy on us? (It is a US company)

**Comment by DenseComet** [comment]
First thing: No, Mailinabox is meant to be used on a brand new server and will wipe out all your existing config. 

Unless you have an alternate suggestion for a OS, Ubuntu seems like the best bet. It is widely supported, Canonical has a very good track record, and if you really wanted to, you could track every packet. You could not use Canonical repos, but build from source yourself. 

There has to be a healthy balance between doing EVERYTHING yourself and nothing yourself, the balance being, do what is not available yourself and make use of preexisting code (same philosophy as using libraries when coding).

Also, as mailinabox is meant to be run on a dedicated server, the os is locked down quite a bit. Security depends on the applications, which are the same on every version of linux. 

All in all, the OS choice doesn't make a difference. 14.04 is perfectly fine, so its unlikely for the authors to change distro anytime soon.
