### ISSUE TITLE
SSL certs generation: HTTP Validation challenge fails.

### ISSUE THREAD

**Issue by SheriefAlaa** [mail-in-a-box/mailinabox#1249]
Hi,

I am facing a problem with Letsencrypt certs generation. This is a *new* installation (I also attempted to rm -rf /etc/mailinabox.conf && rm -rf /home/user-data.

logs:

```
Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
Reusing existing challenges for box.medimail.us.
The HTTP Validation challenge for box.medimail.us failed: DNS problem: SERVFAIL looking up A for box.medimail.us.
```

config:

/etc/hosts
```
127.0.0.1 localhost.localdomain localhost
x.x.x.x box.medimail.us box
```

/etc/resolv.conf
```
nameserver x.x.x.x # MiAB IP here <---
nameserver 127.0.0.1
search us-west-1.compute.internal
```

Any help would be appreciated.

Thanks.

**Comment by hachre** [comment]
Is this a new installation or renewing of certificates after it's been already working for a while?

**Comment by SheriefAlaa** [comment]
@hachre It's a new installation and I originally tried to do external DNS from AWS. However, I changed that later to just give MiAB NS control from GoDaddy by creating two hostnames (ns1.box and ns2.box) then pointing the nameservers to the aws instance that MiAB is on.

```
Does it literally say example.com in those error outputs and config files? Or did you edit that?
```

No I edited that out and have the real domain in my original comment now.

Thanks.

**Comment by hachre** [comment]
Looks to me like everything is working correctly now. Did you change anything? Maybe DNS just needed time to propagate.

**Comment by SheriefAlaa** [comment]
@hachre Nothing! I only added the DNSSEC record and that's it. Anyway, now I do have certificates but there's another problem with reverse DNS.

```
Your box's reverse DNS is currently ec2-13-57-43-106.us-west-1.compute.amazonaws.com, but it should be box.medimail.us. Your ISP or cloud provider will have instructions on setting up reverse DNS for your box.
```

and sometimes I get that port 25 fails but not constantly.

```
Outbound mail (SMTP port 25) seems to be blocked by your network. You will not be able to send any mail. Many residential networks block port 25 to prevent hijacked machines from being able to send spam. A quick connection test to Google's mail server on port 25 failed.
```


Thanks.

**Comment by hachre** [comment]
The reverse DNS is something you have to set up with whomever provides you your IP. I don't know how to do with for AWS specifically and setting it up is also not mandatory, but recommended.

Maybe Google's server blocks AWS occasionally to rate limit or something. I wouldn't worry too much about it.
