### ISSUE TITLE
adding an NS record to a subdomain

### ISSUE THREAD

**Issue by bjesus** [mail-in-a-box/mailinabox#1250]
Hey! Thanks for mailinabox!

I'm trying to add an [NS record](https://support.dnsimple.com/articles/ns-record/) to a subdomain of a domain handled by mailinabox. It seems that this is currently impossible, as there simply isn't an NS record option in the select box.

Is this intentional? Should an NS record be added? I'd be glad to try and submit a pull request if it fits your agenda.

The reason I need this is because I'm trying to [setup Iodine](https://gist.github.com/nukeador/7483958).

**Comment by just4t** [comment]
Looks like custyom NS records will be added in from next 'stable' version. See changelog: https://github.com/mail-in-a-box/mailinabox/blob/master/CHANGELOG.md

**Comment by bjesus** [comment]
Oh, wonderful. sorry I didn't check the changelog. looking forward for it then, and closing this meanwhile. 
Thanks!
