### ISSUE TITLE
Error upgrading from 0.23 to 0.24

### ISSUE THREAD

**Issue by geekafy** [mail-in-a-box/mailinabox#1254]
Howdy! 

I'm trying to upgrade from 0.23 to 0.24 and I am running the install script to upgrade as indicated on the upgrade page (https://mailinabox.email/maintenance.html#upgrade). Once I do, I am getting the following error:

```
root@box:~# curl -s https://mailinabox.email/setup.sh | sudo bash
Updating Mail-in-a-Box to v0.24 . . .
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
error: Your local changes to the following files would be overwritten by checkout:
	management/status_checks.py
Please, commit your changes or stash them before you can switch branches.
Aborting
Update failed. Did you modify something in /root/mailinabox?
```

I have not made nay modifications.

Any clue hot to fix this?

Thanks!

**Comment by yodax** [comment]
If you go into the mailinabox directory under root's account and run ```git diff management/status_checks.py``` you can see what was changed. To get rid of the changes you can run ```git checkout -- management/status_checks.py``` or just trash the entire directory and run ```curl -s https://mailinabox.email/setup.sh | sudo bash``` again.

**Comment by geekafy** [comment]
It worked, thank you!
