### ISSUE TITLE
Admin console running on different port to 80

### ISSUE THREAD

**Issue by SirCameron** [mail-in-a-box/mailinabox#1256]
Hey Guys

Thanks for this project.. 
I'm about to install, but I'd like the admin console running on a separate port to 80... This way, i can still run apache/nginx on port 80.

Is this possible? I'm unable to find a config that specifies the port..

Thanks
C

**Comment by JoshData** [comment]
Running other things on the same server isn't something we support, sorry. Things will break if the web components are not running where they're expected.
