### ISSUE TITLE
Ensure all dependencies are installed when upgrading from 0.23a to 0.24

### ISSUE THREAD

**Issue by zoof** [mail-in-a-box/mailinabox#1259]
When I upgraded to 0.24, php7.0-mbstring was not installed as it should have been.  See https://discourse.mailinabox.email/t/solved-after-upgrading-to-0-24-roundcubemail-appears-to-be-broken/2536/9

**Comment by JoshData** [comment]
That's strange because `php7.0-mbstring` is listed in our list of packages to install.

**Comment by zoof** [comment]
That is weird because I had to run `curl -s https://mailinabox.email/setup.sh | sudo bash` twice. The first time failed because it had not installed `php7.0-curl` which I had to manually install before it would complete. The relevant `history` lines:

>  1936  curl -s https://mailinabox.email/setup.sh | sudo bash
>  1937  aptitude search php|grep curl
>  1938  aptitude search php|grep 7
>  1939  aptitude search php|grep curl
>  1940  sudo apt install php7.0-curl
>  1941  curl -s https://mailinabox.email/setup.sh | sudo bash

And then of course it still needed `php7.0-mbstring`. Does the setup process keeps any logs so that we can see why these dependencies were not installed?

**Comment by JoshData** [comment]
apt might have a log, but tbh I would think apt would fail if it doesn't install all of the requested packages, and if it fails it would all probably break.

**Comment by zoof** [comment]
From the first upgrade attempt:

> Start-Date: 2017-10-07  11:25:01
> Commandline: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install openssl
> Install: libssl1.1:amd64 (1.1.0f-2~ubuntu14.04.1+deb.sury.org+1, automatic)
> Upgrade: openssl:amd64 (1.0.1f-1ubuntu2.22, 1.1.0f-2~ubuntu14.04.1+deb.sury.org+1)
> End-Date: 2017-10-07  11:25:03
> 
> Start-Date: 2017-10-07  11:25:44
> Commandline: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install nginx php7.0-cli php7.0-fpm
> Install: php7.0-json:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1, automatic), php7.0-cli:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-common:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1, automatic), php-common:amd64 (55+ubuntu14.04.1+deb.sury.org+1, automatic), php7.0-fpm:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-opcache:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1, automatic), php7.0-readline:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1, automatic)
> End-Date: 2017-10-07  11:25:54
> 
> Start-Date: 2017-10-07  11:26:00
> Commandline: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install dbconfig-common php7.0-cli php7.0-sqlite php7.0-mcrypt php7.0-intl php7.0-json php7.0-common php-auth php-net-smtp php-net-socket php-net-sieve php-mail-mime php-crypt-gpg php7.0-gd php7.0-pspell tinymce libjs-jquery libjs-jquery-mousewheel libmagic1
> Install: php7.0-sqlite3:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-mcrypt:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-intl:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), libwebp5:amd64 (0.4.4-1+deb.sury.org~trusty+1, automatic), php7.0-gd:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-pspell:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1)
> Upgrade: libgd3:amd64 (2.1.0-3ubuntu0.8, 2.2.5-3+ubuntu14.04.1+deb.sury.org+1)
> End-Date: 2017-10-07  11:26:03
> 
> Start-Date: 2017-10-07  11:26:12
> Commandline: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install php7.0-soap php7.0-imap libawl-php php7.0-xsl
> Install: php7.0-xsl:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-imap:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-soap:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1), php7.0-xml:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1, automatic)
> End-Date: 2017-10-07  11:26:17

After it failed, I installed `php7.0-curl`:

> Start-Date: 2017-10-07  11:32:11
> Commandline: apt install php7.0-curl
> Install: php7.0-curl:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1)
> End-Date: 2017-10-07  11:32:12

The second upgrade attempt shows nothing further in `history/apt.log` and then I installed `php7.0-mbstring` after which everything worked again:

> Start-Date: 2017-10-08  13:57:30
> Commandline: apt install php7.0-mbstring
> Install: php7.0-mbstring:amd64 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1)
> End-Date: 2017-10-08  13:57:32

Could the problem be that these dependencies are installed as a requirement for Nextcloud?  (Which I have commented out because I don't use it and none of the fixes I attempted [roughly 2 years ago when it was still Owncloud] seem to work?)

**Comment by JoshData** [comment]
> Could the problem be that these dependencies are installed as a requirement for Nextcloud? (Which I have commented out

I wish you had mentioned that at the start.

Ok so it looks like we need to copy `php7.0-mbstring` to the apt-install line for roundcube. Easy enough.

**Comment by zoof** [comment]
Sorry, having linked the discourse thread, I didn't think about that detail.

**Comment by JoshData** [comment]
Oh, I missed it there.

**Comment by JoshData** [comment]
Fixed via ^.

**Comment by zoof** [comment]
Should add `php7.0-curl` somewhere as well.  That crashed my initial upgrade attempt crashed and I had to manually install before the upgrade worked (see above).
