### ISSUE TITLE
Cannot Delete Messages on iPhone with Z-Push

### ISSUE THREAD

**Issue by Futurama56** [mail-in-a-box/mailinabox#126]
"Unable to Move Message"
The message could not be moved to the mailbox Trash.

After investigation, it looks like there is a patch for this that should be included from http://sealedabstract.com/code/nsa-proof-your-e-mail-in-2-hours/

A quick note that I needed a patch /usr/share/d-push/backend/imap/imap.php to get my “Deleted Messages” folder working:

	else if($lid == "trash" || $lid == "deleted messages") {
	            $folder->parentid = "0";
	            $folder->displayname = "Trash";
	            $folder->type = SYNC_FOLDER_TYPE_WASTEBASKET;
	            $this->wasteID = $id;
	        }

Obviously our path is /usr/local/lib/z-push/backend/imap/imap.php

I tried the updates - adding the deleted messages, but still get this error on iPhone.  A serious blocker.

**Comment by fmbiete** [comment]
This problem should be fixed in last master of z-push-contrib. There are better options to configure the folders name, also the possibility to use the "archive" folder on iOS.
