### ISSUE TITLE
python-boto still not working

### ISSUE THREAD

**Issue by nordurljosahvida** [mail-in-a-box/mailinabox#1260]
I just set up a brand new box on v0.24 and when running duplicity form s3 I still had to:

`apt -y install python-boto`

like in the old days.

Also, the fact that /home/user-data exists and therefore must be deleted or moved before duplicity will work is confusing for users I think. We could add:

`mv /home/user-data /home/user-data-orig`

to [these instructions](https://mailinabox.email/maintenance.html#moving-boxes) perhaps?

Thanks!

**Comment by JoshData** [comment]
> I just set up a brand new box on v0.24 and when running duplicity form s3 I still had to:
> apt -y install python-boto

We do install boto ([here](https://github.com/mail-in-a-box/mailinabox/blob/e49c99890be4dafcd160e711007257a4729ed2db/setup/management.sh#L51) so I'm not sure why that would happen.

> the fact that /home/user-data exists and therefore must be deleted or moved before duplicity will work is confusing for users I think

Yes. Your suggestion is fine.

**Comment by nordurljosahvida** [comment]
Hi again. I've just found this old issue and it was amazing as your link in the previous comment is completely unrelatedly what I found a few weeks back from a random google search when working on our xmpp-server automation project [aenigma](https://github.com/openspace42/aenigma) and having the same issue with an old version of boto not supporting newer key signature versions on european Amazon S3 endpoints. Very interesting to see that you had actually mentioned here and that's what we were talking about in the first place. In any event, I think we can close this first point as I've never encountered the issue again and the pip install seems to work great.

Do you still agree we should move the original `/home/user-data` before a duplciity restore? If so, where do you think this action should be included in the code?

Thanks again!

**Comment by JoshData** [comment]
> Do you still agree we should move the original /home/user-data before a duplciity restore? If so, where do you think this action should be included in the code?

I'm not sure, actually.

**Comment by nordurljosahvida** [comment]
@JoshData I think that presenting the user with an error during restore [one of the most critical times of managing a server] because there's already a folder in place that cointains potentially empty data is both a problem and easily solvable. I think `/home/user-data` should simply become `/home/user-data-old` just before the duplicity command. Would you review a relevant PR for the restore script?
