### ISSUE TITLE
Upgrade to 0.24 - Nextcloud - Command "upgrade" is not defined.

### ISSUE THREAD

**Issue by patrickscottbest** [mail-in-a-box/mailinabox#1262]
On Ubuntu, upgrading to 0.24

root@mail:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
expired old bayes database entries in 9 seconds
141340 entries kept, 47791 deleted
token frequency: 1-occurrence tokens: 74.80%
token frequency: less than 8 occurrences: 12.38%
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Updating database schema (2016081200)... [OK]
Updating database schema (2016100900)... [OK]
Updating database schema (2016112200)... [OK]
Installing Nextcloud (contacts/calendar)...
upgrading ownCloud/Nextcloud to  12.0.3 (backing up existing installation, configuration and database to directory to /home/user-data/owncloud-backup/2017-10-12-09:08:07...
We are running Nextcloud 10.0.x, upgrading to Nextcloud 11.0.3 first

Upgrading to Nextcloud version 11.0.3

Nextcloud is not installed - only a limited number of commands are available

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "upgrade" is not defined.

Trying ownCloud upgrade again to work around ownCloud upgrade bug...
Nextcloud is not installed - only a limited number of commands are available

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "upgrade" is not defined.

**Comment by yodax** [comment]
Sorry for the late response. Did you manage to fix this? Otherwise running tools/owncloud-restore.sh and retrying might solve it. I had 3 identical boxes, one of them had this issue. Seems to be general flakiness.

**Comment by patrickscottbest** [comment]
sorry for the long delay.  I ended up reverting to a previous snapshot and haven't attempted an upgrade again yet.  A great package overall though.  Keep up the good work guys.
