### ISSUE TITLE
emails take too long to receive

### ISSUE THREAD

**Issue by systemroot** [mail-in-a-box/mailinabox#1267]
Hello,

I'm using mail in a box in one small vps 
2GB RAM
1 Core 2.4 GHz
50GB SSD
100MB/s internet

And so mail in a box takes around 1-2 min to send an email, some times it send em in 10sec sometimes in 5min but avg is 2min. 

is there anything which i can do to speed up this? 
*(i'm using it just for personal emails not for offering mail service or anything else, so if there are security rules or something else which takes some time to check email by slowing them, i'll like to know how to disable it.)*

Thanks for support.

**Comment by yodax** [comment]
Sending and receiving could vary wildly in the causes on why it takes a while for a message to arrive. Mailinabox uses grey listing to filter out spam. (See the [readme](https://github.com/mail-in-a-box/mailinabox/blob/master/README.md))

If you want to get a live view of the messages you can follow along in /var/log/mail.log by running ```tail -f /var/log/mail.log```

**Comment by systemroot** [comment]
Thank you for information!

**Comment by matteofabbri** [comment]
ok, how to add address or domain to the lists ? 
I'not able to activate amazon prime becuase their mail server goes graylisted

**Comment by zatricky** [comment]
Graylisting is temporary; if the mail is still not functional, it is very likely a different issue.

Maybe first check the "Need Help?" section on the main site for other ways to get more specific assistance: https://mailinabox.email/
