### ISSUE TITLE
Your box's reverse DNS is currently [Not Set]

### ISSUE THREAD

**Issue by alexgleason** [mail-in-a-box/mailinabox#1270]
Every so often, like every week or so, Mail in a Box reports that `Your box's reverse DNS is currently [Not Set]`.

Usually the following morning it sends another message saying that it has been resolved.

I have two Mail in a Box servers and this happens to both of them. Both are hosted on Vultr.

**Comment by wioxjk** [comment]
Have you set a reverserecord?

**Comment by alexgleason** [comment]
Yes, here are two notifications for reference. It sends the first one, then the following day it sends the second one. It happens somewhat regularly.

**Subject:** [box.alexgleason.me] Status Checks Change Notice
**Date:** Oct 14, 2017, 03:00
```
box.alexgleason.me -- Previously:
=================================
✓  Reverse DNS is set correctly at ISP. [45.77.144.241 / 2001:19f0:5:39:5400:1ff:fe36:d181 ↦ box.alexgleason.me]

box.alexgleason.me -- Currently:
================================
✖  Your box's reverse DNS is currently [Not Set] (IPv4) and box.alexgleason.me (IPv6), but it should be box.alexgleason.me. Your ISP or cloud provider will have instructions on setting up reverse DNS for your box.
```

**Subject:** [box.alexgleason.me] Status Checks Change Notice
**Date:** Oct 15, 2017, 03:00
```
box.alexgleason.me -- Previously:
=================================
✖  Your box's reverse DNS is currently [Not Set] (IPv4) and box.alexgleason.me (IPv6), but it should be box.alexgleason.me. Your ISP or cloud provider will have instructions on setting up reverse DNS for your box.

box.alexgleason.me -- Currently:
================================
✓  Reverse DNS is set correctly at ISP. [45.77.144.241 / 2001:19f0:5:39:5400:1ff:fe36:d181 ↦ box.alexgleason.me]
```

**Comment by wioxjk** [comment]
I would talk to the hostingprovider and see if there is any issues around that time. Maybee they reboot the DNS server at that time?

**Comment by yodax** [comment]
This is a common problem, see this PR: https://github.com/mail-in-a-box/mailinabox/pull/743

**Comment by alexgleason** [comment]
Thank you! Closing as a dupe of #628.
