### ISSUE TITLE
Why box.mysite.com instead of mysite.com?

### ISSUE THREAD

**Issue by alexgleason** [mail-in-a-box/mailinabox#1272]
Excuse me for asking this totally semantic/pointless question, but I've been getting accustomed to Mail-in-a-Box, falling in love with it, and wanting to install it everywhere. Each time I configure it, I rake my mind about how I want the URLs to be structured. I can make arguments from both sides and I keep going back and forth on it. I wish to know the rationale in favor of using box.mysite.com as the default. That said, here are some arguments against it:

1. It creates two separate static sites by default, which is confusing and probably unnecessary. Of course I want to host something at `mysite.com` but I do not want to host something at `box.mysite.com`. If anything, I'd expect Mail-in-a-Box to be there. I was surprised that I had to type `box.mysite.com/admin` to reach the management page; `box.mysite.com` seems distinct enough. In fact, I think I'd prefer `box.mysite.com`, `mail.mysite.com`, and `cloud.mysite.com` for each separate service.
2. I'm guessing box.mysite.com is the default so you can point the A record of mysite.com to a different server if needed. Also, possibly because /admin, /mail, /cloud may conflict with paths on the actual website. Subdomains as described above could also fix this issue.

So, for starters, I'm considering using `mysite.com` instead of `box.mysite.com` going forward. That'll give me:

* `mysite.com/admin`
* `mysite.com/cloud`
* `mysite.com/mail`
* `mysite.com`

which IMO is a big improvement over:

* `box.mysite.com/admin`
* `box.mysite.com/cloud`
* `box.mysite.com/mail`
* `box.mysite.com`
* `mysite.com`

Although, ideally, I think I'd prefer it like this:

* `box.mysite.com` (management admin)
* `cloud.mysite.com` (nextcloud)
* `mail.mysite.com` (roundcube)
* `mysite.com` (front-facing static site)

**Comment by JoshData** [comment]
> I'm guessing box.mysite.com is the default so you can point the A record of mysite.com to a different server if needed.

That's the reason.

**Comment by alexgleason** [comment]
Are you against using subdomains as a default? If each service existed on a subdomain rather than a path, you could still set the A record of @ to whatever you want and MIAB features would be unaffected.

**Comment by deuceBag33** [comment]
can't you use DNS to change:


   - box.mysite.com/admin => box.mysite.com (management admin)
   - box.mysite.com/cloud => cloud.mysite.com (nextcloud)
   - box.mysite.com/mail => mail.mysite.com (roundcube)

**Comment by JoshData** [comment]
@alexgleason Having everything on the same domain is easier to manage / there's less that can go wrong.

**Comment by alexgleason** [comment]
@JoshData What if the MIAB admin was displayed for box.mysite.com? It seems weird, semantically, to have a static site associated with that subdomain.

Another option could be defaulting to something like this: https://apps.disroot.org/

**Comment by JoshData** [comment]
> What if the MIAB admin was displayed for box.mysite.com?

Anything is possible. There are lots of why nots, which you can imagine:

* Some people might want to put something else there.
* It's a little weird and difficult to configure having the admin at `/` and other unrelated services at `/mail`, `/cloud` etc.

> Another option could be defaulting to something like this: https://apps.disroot.org/

I mean, sure, we could change the recommended hostname. Feel free to open an issue about that. I have a feeling you won't be able to find consensus.

**Comment by alexgleason** [comment]
I wasn't suggesting we change the hostname, rather put some sort of default portal on the box subdomain. This link is not an example, it's meant to be clicked: https://apps.disroot.org/

**Comment by JoshData** [comment]
Ahhha. Sorry I misunderstood. Yeah, there's already an issue to discuss that: #985.

**Comment by alexgleason** [comment]
Cool, thanks! I'll head over there. Thank you for explaining this all; it makes a lot more sense now.
