### ISSUE TITLE
Uninstalling / Reverting Mail in a box

### ISSUE THREAD

**Issue by oreHGA** [mail-in-a-box/mailinabox#1273]
Hi, I recently just installed the mail in the box on an ubuntu VPS i'm working on but i realized that i want to use the docker version instead so that i could still use my server for other stuff... been tryna find a way to uninstall mail in a box but i don't see anything useful anywhere. 
Kindly help, thank you

**Comment by yodax** [comment]
The box can’t be uninstalled. You need to wipe the vm after you’ve backed up all the data on it.

**Comment by oreHGA** [comment]
is there a way for me to just stop it from "listening on port 80 and redirecting me". Cus i just want to get my web server back online

**Comment by yodax** [comment]
You need to change the nginx config.

**Comment by oreHGA** [comment]
i'll try that now.. thank you

**Comment by codeguru1983** [comment]
this is the most stupid thing ever... can't get rid of it :)) such a shit app

**Comment by anoma** [comment]
Second line on homepage

`Technically, Mail-in-a-Box turns a fresh cloud computer into a working mail server.`

It sounds like you ignored the requirement for a ` fresh cloud computer `.

One of only 5 Pre-flight Checklist items which are the very first thing presented in the setup guide

`Can I modify my box after / use my box for something else too? (Advanced.)
    No. Mail-in-a-Box must be installed on a fresh machine that will be dedicated to Mail-in-a-Box, and you cannot modify the box after installation (configuration changes will get overwritten by the box’s self-management). `

I understand your frustration but the error is yours.

Saying that I think we should change these words to be stronger, explicitly state it cannot just be uninstalled and make it clearer MIAB is not an app it is an appliance.

**Comment by codeguru1983** [comment]
mate, nobody on this plannet builds something that can't be removed. if it requires a fresh server then just pop a fucking screen saying: DICKHEAD IF YOU INSTALL THIS SHIT THING I'VE BUILT, you will never be able to remove it and all the work you might have done on your server will be fucking lost... because I'm a dickhead and can't build an unistall... that will sort the problem... stupid indian programmers

**Comment by JoshData** [comment]
@codeguru1983 has been blocked for being racist. Anyone else is free to open a new issue or PR on the same subject.
