### ISSUE TITLE
Add roundcube/customizr for easier customization

### ISSUE THREAD

**Issue by fmp777** [mail-in-a-box/mailinabox#1274]
https://plugins.roundcube.net/packages/roundcube/customizr

Not really sure if mail-in-a-box has a provision for being able to safely add new roundcube plugins, but seems like this would be a good one to have default installed.  I can of course modify the skins but also imagine future updates could wipe out modifications?

**Comment by JoshData** [comment]
Although it makes sense from a feature perspective, each new thing we add creates maintenance headaches down the road, and since this issue has been silent, I'm going to close it.
