### ISSUE TITLE
DNS over TLS?

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#1275]
I haven't looked at how DNS over TLS works yet but it's something to consider implementing.

**Comment by cromulus** [comment]
Seems fairly straightforward: [https://dnsprivacy.org/wiki/display/DP/Using+a+TLS+proxy](nginx config)

I'll take a whack at it.

**Comment by cromulus** [comment]
So, learned a bunch about what DNS over TLS is... AFAIK, it really makes sense if you are using your mailinabox server as your recursive dns server (like opendns or google's 8.8.8.8) which currently it's not setup to do. I haven't read anything about using DNS over TLS for authoritative dns servers, like mailinabox. 

All that said, for DNS over TLS to be proxied via nginx, which IMHO is the simplest, most straightforward approach, we'll have to upgrade our nginx version to 1.9.0+.

My suggestion is to add the official nginx stable ppa.

See this branch for an initial whack at it: [dns-over-tls](https://github.com/cromulus/mailinabox/tree/dns_over_tls)

**Comment by JoshData** [comment]
Thanks for looking into it! That's interesting and easy. Since the box isn't acting as a recursive DNS server now, I guess there's no reason to add it. But it might be a worthwhile feature. We probably just would want to add access controls because we don't want to expose a recursive DNS server to the world.

**Comment by JoshData** [comment]
Decided to close this because it's not really in scope.
