### ISSUE TITLE
Mailinabox not broadcasting CNAME

### ISSUE THREAD

**Issue by alexgleason** [mail-in-a-box/mailinabox#1276]
I've read through the 10+ threads with similar issues, but still not finding the solution.

When I run this command:

```
dig @ns1.box.mysite.com mysite.com
```

it gives me:

```
;; ANSWER SECTION:
mysite.com.	1800	IN	A	123.123.123.123 ; (my box IP)
```

Under Custom DNS I have configured this *and nothing else*:

```
mysite.com	CNAME	na-west1.surge.sh.
www.mysite.com	CNAME	na-west1.surge.sh.
```

**I have included the period at the end.**

This doesn't seem to be an issue of waiting for the DNS to propagate, because even when using dig to request info from the nameserver directly it sends back the wrong info. I've tried restarting NSD and looking at the configuration for it. Am I misunderstanding how this dig command works? Any help would be appreciated.

**Comment by yodax** [comment]
Can you try dig @ns1.box.mysite.com mysite.com CNAME

**Comment by alexgleason** [comment]
@yodax Here's the output of dig, still looks like it's not showing anything.

```
alex@Firestorm:~$ dig @ns1.box.mysite.com mysite.com CNAME

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> @ns1.box.mysite.com mysite.com CNAME
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20414
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mysite.com.		IN	CNAME

;; AUTHORITY SECTION:
mysite.com.	1800	IN	SOA	ns1.box.mysite.com. hostmaster.box.mysite.com. 2017102807 7200 1800 1209600 1800

;; Query time: 19 msec
;; SERVER: 2001:19f0:5:29ba:5400:1ff:fe3d:a701#53(2001:19f0:5:29ba:5400:1ff:fe3d:a701)
;; WHEN: Sat Oct 28 14:24:04 EDT 2017
;; MSG SIZE  rcvd: 100
```

I have confirmed that `/etc/nsd/zones/mysite.com` is correct. Also `/home/user-data/dns/custom.yml` lists my CNAME entries.

I've run `service nsd restart` and even tried restarting the whole server.

Also, the "external DNS" page in MIAB shows the correct DNS config. But using dig directly on the nameserver isn't showing the right values.

**Comment by alexgleason** [comment]
I had previously set an A record alongside the CNAME for the same domain. I didn't know this was wrong, and assumed one would take precedence. After reading that this is an invalid configuration I deleted all custom DNS entries and recreated the CNAME entries.

My syslog shows errors like this from hours ago, prior to making this change:

```
Oct 28 13:16:23 box nsd[1209]: mysite.com.txt.signed:16: CNAME and other data at the same name
```

**Comment by alexgleason** [comment]
Wait a sec... I just did `service nsd restart` again and I am indeed still getting these errors! Sorry for blowing up your inbox.

```
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:6: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:7: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:8: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:9: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:10: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:11: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:12: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:13: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:14: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:15: CNAME and other data at the same name
Oct 28 14:55:56 box nsd[11108]: mysite.com.txt.signed:16: CNAME and other data at the same name
```

I'm not sure how much of the data within that file is safe for me to share here. "Signed" means it's encrypted and I shouldn't share that, right?

**Comment by alexgleason** [comment]
Based on what I'm reading, you can't mix a CNAME and MX record. Since there's an MX record for @.mysite.com I cannot use a CNAME for it at the same time.

https://docs.oracle.com/cd/E19455-01/806-1075/msgs-1694/index.html

Can anyone verify that this is true? I'm going to try using an A record instead of a CNAME. If this is true, MIAB could alert the user about using a CNAME and any other record simultaneously. I've misunderstood how CNAMEs work.

**Comment by alexgleason** [comment]
Switching to an A record worked.
