### ISSUE TITLE
When pointing domain to elsewhere in Custom DNS, the newly added entries won't take effect

### ISSUE THREAD

**Issue by bogao** [mail-in-a-box/mailinabox#1280]
Repro steps:
1. I changed a domain (gaobo.org)'s NS to my MIAB box;
2. I added some new entries (A/CName records) to that domain, working like a charm;
3. I point the gaobo.org and www.gaobo.org to elsewhere (by adding A/CName records to them);
4. I added some more new entries (A/CName records) to that domain.

Step 3 and 4 won't take effect. In other words, gaobo.org and www.gaobo.org still point to MIAB box's IP address, and all the new entries added after Step 3 won't take effect.

And if I undo Step 3 by removing the A/CName records of gaobo.org and www.gaobo.org, the entries in Step 4 will take effect afterward.

I think it makes a lot of sense that I'd specify the MIAB box as my DNS server of some domains but I'd point those domains to elsewhere. Thus, it's an issue to fix.

**Comment by he8us** [comment]
Hello @bogao,

I use my box to manage my dns for my domains, all of them points to 2 other servers and I have no problems. I usually don't use CNAME records, btw

Maybe it's a configuration issue ?

Can you give the detailed DNS entries you're trying to set?
