### ISSUE TITLE
Can no longer add a wildcard DNS record (*)

### ISSUE THREAD

**Issue by israelroldan** [mail-in-a-box/mailinabox#1282]
The changes in #1177 introduced an issue where you can no longer add wildcard records (which is a feature one of my instances rely on).

### Steps to reproduce:
* Add a new CNAME record on any domain: 
    * Name: *
    * Type: CNAME
    * Value: example.com.

### Expected result
It should work fine, just as it did prior to the upgrade

### Actual result
It fails since it does not pass the new [RegEx based validation](https://github.com/ctrlaltdel/mailinabox/blob/4b0198379cd516325b11d7893f873eb5544f4d63/management/dns_update.py#L18)

**Comment by JoshData** [comment]
Already at #1281.

**Comment by israelroldan** [comment]
Cool, I've +1'd it :)
