### ISSUE TITLE
[Request] Replace roundcube with Nextcloud / mail

### ISSUE THREAD

**Issue by pmatos** [mail-in-a-box/mailinabox#1283]
We desperately need something better than roundcube. It's outdated, poorly designed and we need something better.

My suggestion is Nextcloud Mail (https://github.com/nextcloud/mail/). I understand it is probably a lot of work but I leave the suggestion.

**Comment by yodax** [comment]
Can you be more specific? 

Why is it outdated, etc? What's the urgency?

Is there a comparison between the two? Is Nextcloud mail as feature complete as roundcube?

There are some issues/pull requests about Rainloop as well.

**Comment by pmatos** [comment]
OK, I have possibly spoken too soon. I looked at the project to be 'Roundcube Next' and noticed it's dead. Assumed normal Roundcube was as well but as it turns out it's still churning out releases and some nice themes. Apologies for the noise.
