### ISSUE TITLE
External DNS issues preventing SSL certificate renewal

### ISSUE THREAD

**Issue by joejacobs** [mail-in-a-box/mailinabox#1284]
I am using MIAB with an external DNS server. As far as I can tell, the external dns servers are setup correctly. When I use dig to query the A records from my laptop I get the correct responses. However, when I run dig on my MIAB server, instead of checking the records on the external DNS server it checks 127.0.0.1 and fails.

Running `dig A example.com` on MIAB box
```
; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> A example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 26073
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.com.			IN	A

;; Query time: 5 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Nov 09 03:19:18 GMT 2017
;; MSG SIZE  rcvd: 43
```

Running `dig @ns1.example.net A example.com` on MIAB box
```
; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> @ns1.example.net A example.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59282
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 9
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.com.			IN	A

;; ANSWER SECTION:
example.com.		7200	IN	A	zzz.zzz.zzz.zzz

;; AUTHORITY SECTION:
example.com.		7200	IN	NS	ns2.example.net.
example.com.		7200	IN	NS	ns1.example.net.

;; ADDITIONAL SECTION:
ns1.example.net.	7200	IN	A	xxx.xxx.xxx.xxx
ns2.example.net.	7200	IN	A	xxx.xxx.xxx.xxx

;; Query time: 5 msec
;; SERVER: xxx.xxx.xxx.xxx#53(xxx.xxx.xxx.xxx)
;; WHEN: Thu Nov 09 03:20:31 GMT 2017
;; MSG SIZE  rcvd: 317
```

This issue seems to be causing the SSL certification renewal to fail (`dns.resolve.query` fails in `management/ssl_certificates.py`).

```
example.com: DNS isn't configured properly for this domain: DNS resolution failed (A: All nameservers failed to answer the query example.com. IN A: Server 127.0.0.1 UDP port 53 answered SERVFAIL).
```

**Comment by yodax** [comment]
The local dns server use the root servers directly to lookup hostnames. You get servfail back. Can you, from the box via ssh, resolve any other domain names?

**Comment by joejacobs** [comment]
Other domain names resolve. It even resolves for other domain names on the same nameserver that don't have email hosted on the MIAB server. It only fails for domain names that have emails hosted on this particular MIAB server.

**Comment by joejacobs** [comment]
Turns out this was an issue with DNSSEC, not MIAB. Closing the issue.
