### ISSUE TITLE
Exchange mysteriously stopped working on one of my MIAB servers

### ISSUE THREAD

**Issue by alexgleason** [mail-in-a-box/mailinabox#1285]
I'm running 3 MIAB servers. The other two have been doing just fine for quite a while. On the third, my Android device kicked me out of it. Mail is still working, but Exchange functionality is not.

I tried updating MIAB to the latest version, updating the system software, and rebooting the system to no avail. Do you have any ideas about where I can begin to debug this? I don't know much about Exchange nor what logs to look at.

It's worth noting this server has some customizations. The biggest is that I'm running Mailman alongside it on the same server. However, Exchange worked fine in this setup for a long time. I can't remember making any particular changes prior to it not working.

**Comment by hachre** [comment]
Sorry, I somehow didn't see this or I would have responded earlier.

You can try to make sense from the logs in `/var/log/z-push/`.
Generally you should look into `z-push-admin -a clearloop` or `-a fixstates` or if all else fails delete your specific device registration (and set up the account anew on your device) with `-a remove -d deviceid`. You get the deviceid from `-a list`.
