### ISSUE TITLE
Decrypt user password

### ISSUE THREAD

**Issue by petarkozic** [mail-in-a-box/mailinabox#1286]
This is not issue, question only.

Can I on localhost where installed mail-in-a-box to decrypt sha512-crypt from database ?

**Comment by yodax** [comment]
I hope not. We store it via doveadm.

**Comment by petarkozic** [comment]
How can I setup to see password ? If that posible ?
Thank you on answer.

**Comment by yodax** [comment]
That’s not possible. The password is hashed. 

Met vriendelijke groet, 

Michael Kroes 

> Op 11 nov. 2017 om 10:51 heeft petarkozic <notifications@github.com> het volgende geschreven:
> 
> How can I setup to see password ? If that posible ?
> Thank you on answer.
>
