### ISSUE TITLE
Solution for - The query to URIBL was blocked

### ISSUE THREAD

**Issue by xetorixik** [mail-in-a-box/mailinabox#1288]
A general problem for a Mail in a box server is the fact that queries to URIBL are regularly blocked.

> 0.0 URIBL_BLOCKED ADMINISTRATOR NOTICE: The query to URIBL was blocked.

It's referring to the dns server you're using not being allowed to do an RBL request to the the RBL servers.

Most RBL servers use a "free for some" method, where as long as a given DNS server isn't doing too many requests, it's allowed.  But for a dns server that is too busy, (eg: 8.8.8.8 is very busy), it will be blocked from doing RBL queries, since it no longer qualifies as the "Free for some" method.

Because most public Dedi/VPS servers make use of a free Google Public DNS (8.8.8.8 and 8.8.4.4) out of the box.
This is a general problem for all Mail in a box servers as the Mail in a box installation script doesn't change the nameserver and use the default settings.

**Solution**

The solution is simple.
As Mail in a box does run NSD out of the box. 
This problem could be fixed quite easy.
You should simply use its own NSD nameserver 127.0.0.1 as DNS nameserver to send queries to URIBL.

I previously had +50% blocked query's to URIBL with the free Google Public DNS.
After changing to Mail in a box NSD, literally: 0.

Resuming: Please add nameserver 127.0.0.1 to /etc/resolv.conf to the Mail in a box installation script. And remove all public default nameservers to prevent "query to URIBL was blocked" [problems](https://help.directadmin.com/item.php?id=666).

`

**Comment by yodax** [comment]
MIAB overrides the default local dns servers used for lookups. See setup/system.sh. 

We use the root servers directly and not the cloud provided defaults. 

Or am I missing the point of the issue?

**Comment by xetorixik** [comment]
Weird. Could /etc/resolv.conf be managed and overruled by the VPS provider?
It is working fine here as long as I use 127.0.0.1 in /etc/resolv.conf.

Return to the original of resolv.conf and pronto:

`0.0 URIBL_BLOCKED ADMINISTRATOR NOTICE: The query to URIBL was blocked.
`

**Comment by yodax** [comment]
That's probably the case yes. You can have a look in the startup scripts to see if that's the case. (Or reboot and see if it's reverted)

Which cloud provider do you use? Maybe we can add an install not somewhere? Or detect where that happens and disable it in the setup?

**Comment by xetorixik** [comment]
I sent a ticket to the provider a while ago, to see if there is or was an override (DNS).
No response yet. I'll keep you informed.

**Comment by xetorixik** [comment]
After a look in the log files, I found this:
`etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf`
Even after a reinstallation.


It is a strange problem. Fortunately, easy to solve with the addition of the above nameserver to:  /etc/resolv.conf
