### ISSUE TITLE
MiaB default overrides wildcards DNS

### ISSUE THREAD

**Issue by dbogatov** [mail-in-a-box/mailinabox#1289]
If I set wildcard A record (eq. `*.example.com.` to some IP 111.111.111.111), it correctly routes all subdomains to that IP, but routes `www.example.com` and `example.com` to box's IP.

Can be fixed by manually setting those two records.

**Comment by dbogatov** [comment]
Any feedback?

**Comment by hachre** [comment]
this is normal behavior in DNS servers

maybe it's not clear that this will happen from the way the admin interface presents it

**Comment by dbogatov** [comment]
Could elaborate on why it is normal?
Why are root and www are special?

It seems that for some implementations if there exists record of any type for a subdomain, then it won’t be caught by wildcard. If this is the case, then root level may bypass wildcard (due to MX record), but not www.

**Comment by hachre** [comment]
The `*` wildcard in DNS never applies to the root and only applies to "all other hosts, not already mentioned". So when `www` was set up with an A entry, the `*` will not touch it. Mail-in-a-box sets `www` and root A records by default, so `*` would never catch those automatically. By setting your own `www` records, you essentially override what Mail-in-a-box has already set.

**Comment by dbogatov** [comment]
Thanks!
