### ISSUE TITLE
Owncloud 8.2.3 unavailable

### ISSUE THREAD

**Issue by sfPlayer1** [mail-in-a-box/mailinabox#1297]
The release is no longer available from the URL used by the setup script, causing upgrading old installs to fail. On a side note wget_verify aborts the setup without any user notification in such a case, i.e. the last message is "Upgrading to OwnCloud version 8.2.3" before being returned to the command prompt.

A workaround is patching owncloud.sh to use http://ftp.icm.edu.pl/packages/owncloud/ for 8.2.3.

**Comment by JoshData** [comment]
I think we may need to just use a different version. 8.2.11 is listed here:

https://owncloud.org/changelog/

Probably 8.2.3 was removed because it's obsoleted by a later release in the same series.

**Comment by JoshData** [comment]
Here are the official past download links that we probably need to use:

https://download.owncloud.org/community/owncloud-8.1.12.tar.bz2

**Comment by JoshData** [comment]
Ooops, I pasted the wrong link last night. I meant to paste https://owncloud.org/download/older-versions/. Anyway, this should be fixed now thanks to @yeah .
