### ISSUE TITLE
Can't send mail after upgrading from MIAB 0.24 to 0.25

### ISSUE THREAD

**Issue by geekafy** [mail-in-a-box/mailinabox#1299]
Hello,

Since I upgraded, I have been receiving mail without an issue but when I want to send mail, a few hours later I get this response: 

```
This is the mail system at host box.XXXXXX.com.

####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 3 hour(s).
It will be retried until it is 2 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<XXXXXXXX@XXXXXXX.com>: Host or domain name not found. Name service
    error for name=smtp.XXXXXXX.com type=AAAA: Host not found
Reporting-MTA: dns; box.XXXXXXX.com
X-Postfix-Queue-ID: B2D70FFA00
X-Postfix-Sender: rfc822; XXXXXX@XXXXXXX.com
Arrival-Date: Mon,  4 Dec 2017 21:05:25 -0500 (EST)

Final-Recipient: rfc822; XXXXXXX@XXXXXXX.com
Original-Recipient: rfc822;XXXXXX@XXXXX.com
Action: delayed
Status: 4.3.5
Diagnostic-Code: X-Postfix; Host or domain name not found. Name service error
    for name=smtp.XXXXXX.com type=AAAA: Host not found
Will-Retry-Until: Wed,  6 Dec 2017 21:05:25 -0500 (EST)

```

Seeing that it might be a IPv6 DNS issue, I tried changing the following config to try to prioritize IPv4 in `/etc/postfix/main.cf`

Change 

`inet_protocols = all` to `inet_protocols = ipv4, ipv6`

Unfortunately it has not worked. Any other ideas?

**Comment by yodax** [comment]
Does this happen with all recipients? If so this might be a local dns resolver issue.

**Comment by geekafy** [comment]
I tried with 4 domains and all the same, so I am assuming that it all domains at this point. Delivery to accounts where the mail is hosted on the same box works, so no issue with local delivery.

Ho would I fix the local DNS resolver issue?

**Comment by yodax** [comment]
You can have a look at resolve.conf and if you can ping a domain from the box. Also you could try rerunning the setup.

**Comment by geekafy** [comment]
resolve.conf resets after each reboot and did not make a difference. 
I tried re-running the install and still the same thing.
I don't have any other ideas.....

**Comment by yodax** [comment]
After rerunning the setup and not rebooting is it different? It shouldn’t reset after reboot. Can you ping hosts from the box right after rebooting? And what about after running the setup again?

**Comment by geekafy** [comment]
OK, I found the issue. The issue had nothing to do with MIAB. I went back to my notes and noticed that I upgraded the version of PostFix as well. During that upgrade I chose the wrong config optin when I shoud have chosen "none - Leave config unchanged". 

Sorry for the trouble.

**Comment by geekafy** [comment]
Closing issue.
