### ISSUE TITLE
Cannot connect to IMAP anymore from older Macs.

### ISSUE THREAD

**Issue by ponychicken** [mail-in-a-box/mailinabox#1300]
After the changes to the TLS ciffers, any older Mac (version 10.11 or older) cannot connect to the IMAP port anymore. You can only look at the email in a browser, no desktop client works anymore (Tried Mac Mail and Thunderbird), as the openssl version is too old.

    $ openssl s_client -connect example.com:993
    +CONNECTED(00000003)
    7081:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/ssl/s23_clnt.c:593:

On some of these macs it impossible to update to the latest OS as they are not supported anymore :(

**Comment by ponychicken** [comment]
Changing it to https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.18&openssl=0.9.8zg&hsts=yes&profile=intermediate fixes it

**Comment by bizonix** [comment]
I have the same problem

> my Mac
```
# system_profiler SPHardwareDataType | grep Model
      Model Name: MacBook Pro
      Model Identifier: MacBookPro8,3

# sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114

# openssl s_client -connect box.MyDomain.com:993

CONNECTED(00000003)
96455:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/ssl/s23_clnt.c:593:
```
> my Box
```
$ uname -a
Linux box.MyDomain.com 3.13.0-63-generic #104~precise1-Ubuntu SMP Tue Aug 18 17:03:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

$ tail /var/log/mail.log
Dec 22 07:19:39 imap-login: Info: Disconnected (disconnected before auth was ready, waited 1 secs): user=<>, rip=my.real.ip.addr, lip=box.real.ip.addr, TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher, session=<B79kWO9g6QBPspGb>
Dec 22 07:20:41 imap-login: Info: Disconnected (no auth attempts in 0 secs): user=<>, rip=my.real.ip.addr, lip=box.real.ip.addr, TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher, session=<EVkPXO9g7wBPspGb>
```

**Comment by JoshData** [comment]
You're both using the master branch, right?

I could revert the change that changed the cipher list (#1233). I'd like to keep the modern cipher list tho. Are there any updates for the Macs that add support for the newer ciphers?

**Comment by RBSystems** [comment]
right I'm using the master branch

**Comment by JoshData** [comment]
Hi all. I've reset the dovecot cipher list to the Mozilla intermediate list. Please pull master and let me know if that fixes the connection issues. Thanks!

**Comment by stan3** [comment]
Does mac actually use OpenSSL?  I would have thought Mac Mail uses Secure Transport and Thunderbird would uses NSS.

**Comment by ponychicken** [comment]
I did some more testing. The macs that I used used the DHE-RSA-AES128-SHA cipher to connect:
````
SSL handshake has read 3413 bytes and written 456 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES128-SHA
    Session-ID: 0FA87781B5C5AC423D731F868BD9CB90311E1769BA84C6AEEED1CFA0F9C1D69E
    Session-ID-ctx: 
    Master-Key: 6E6BECA2BEA7F371CEC907AC4BE10414D3992D55386031219329D451BD64D150F97339FC784BAAB3363FF762E16C6A75
    Key-Arg   : None
    Start Time: 1514207957
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
````

I tried to use just the modern set, adding the above mentioned cipher and it works :-)
That way we also don't read ciphers mentioned in #1301 
For completeness here's the set that I am using:
    ssl_cipher_list=ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA
