### ISSUE TITLE
Cannot install checksum error on fresh machine

### ISSUE THREAD

**Issue by ajimix** [mail-in-a-box/mailinabox#1304]
Hello,

I'm trying to install on a fresh machine and I'm getting the following checksum error:
```Installing Z-Push (Exchange/ActiveSync server)...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of http://download.z-push.org/final/2.3/z-push-2.3.8.tar.gz did not match expected checksum.
Found:
66b1613faef61590836682ff1a43d559827fe08b  /tmp/z-push.tar.gz

Expected:
aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb  /tmp/z-push.tar.gz```

Thanks

**Comment by yodax** [comment]
Thanks for reporting this!

They seem to hove dropped a new version over the old one. All the file dates in it have changed. 

Z-push have announced that they will (for future) version not offer tar balls any more, just git or packages.

Might be best to start tracking git, so this doesn't happen any more. When I have a moment I can change the installer to use git instead of the tar bal. (Or if someone else has some time to pick it up)

**Comment by yodax** [comment]
I have a prelim fix for this. So far the differences between the git version and the tar bal seem limited. That setup works on my dev box, but it will require some more testing.

```root at box in /usr/local/lib
$ diff z-push z-push-bup/
Common subdirectories: z-push/autodiscover and z-push-bup/autodiscover
Common subdirectories: z-push/backend and z-push-bup/backend
diff z-push/composer.json z-push-bup/composer.json
2,5c2,9
<     "autoload": {
<         "classmap": ["autodiscover/", "backend/", "include/", "lib/"],
<         "files": ["version.php", "lib/core/zpushdefs.php", "lib/utils/compat.php"]
<     }
---
> 	"name": "z-push/z-push-dev",
> 	"description": "Z-Push is an open-source application to synchronize ActiveSync compatible devices",
> 	"time": "2015-09-02",
> 	"homepage": "http://z-push.org/",
> 	"license": "AGPL-3.0",
> 	"require": {
> 		"php": ">=5.4.0"
> 	}
Common subdirectories: z-push/include and z-push-bup/include
Common subdirectories: z-push/lib and z-push-bup/lib
Only in z-push-bup/: tools
Common subdirectories: z-push/vendor and z-push-bup/vendor
diff z-push/version z-push-bup/version
1c1
< 2.3.8
---
> aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb
diff z-push/version.php z-push-bup/version.php
26,36c26
< if (!defined("ZPUSH_VERSION")) {
<     $path = escapeshellarg(dirname(realpath($_SERVER['SCRIPT_FILENAME'])));
<     $branch = trim(exec("hash git 2>/dev/null && cd $path >/dev/null 2>&1 && git branch --no-color 2>/dev/null | sed -e '/^[^*]/d' -e \"s/* \(.*\)/\\1/\""));
<     $version = exec("hash git 2>/dev/null && cd $path >/dev/null 2>&1 && git describe  --always 2>/dev/null");
<     if ($branch && $version) {
<         define("ZPUSH_VERSION", $branch .'-'. $version);
<     }
<     else {
<         define("ZPUSH_VERSION", "GIT");
<     }
< }
\ No newline at end of file
---
> define("ZPUSH_VERSION", "2.3.8");
\ No newline at end of file```

I'll post a WIP PR when I have a second.

**Comment by yodax** [comment]
I've posted a PR for this. If you want to test that, that would be great! :smile:

**Comment by ajimix** [comment]
Ok I tested your branch and it worked 👍

**Comment by praveenbhat** [comment]
@ajimix  Could you please tell me how to use the branch posted by @yodax

**Comment by ajimix** [comment]
@praveenbhat you need to manually clone his branch and manually run the `setup/start.sh` script instead of following the normal installation procedure

**Comment by rootion** [comment]
I cloned this branch https://github.com/yodax/mailinabox/tree/zpushgit
but keep having issues. I can't continue the installation after this:

```
Download of http://download.z-push.org/final/2.3/z-push-2.3.8.tar.gz did not match expected checksum.
Found:
66b1613faef61590836682ff1a43d559827fe08b  /tmp/z-push.tar.gz

Expected:
aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb  /tmp/z-push.tar.gz
```

**Comment by yodax** [comment]
Can you show the output of git status?

**Comment by rootion** [comment]
You are absolutely right. I cloned the master branch! should have done:
`git clone -b zpushgit https://github.com/yodax/mailinabox/tree/zpushgit`

Now git status is correctly displaying
```
On branch zpushgit
Your branch is up-to-date with 'origin/zpushgit'.
```

Installation is now successful. Thank you!

**Comment by yodax** [comment]
👍🏻

**Comment by edwardstechncial** [comment]
Hi there, Having the same problem and tried
 git clone -b zpushgit https://github.com/yodax/mailinabox/tree/zpushgit
It returns 

Cloning into 'zpushgit'...
fatal: repository 'https://github.com/yodax/mailinabox/tree/zpushgit/' not found

I am sure I am doing something wrong, maybe someone can point me in the right direction 

Thx

**Comment by donsicilly** [comment]
@edwardstechncial
Your not doing anything wrong...the whole issue is pissed off and tired.. i got same error too
git clone -b zpushgit https://github.com/yodax/mailinabox/tree/zpushgit
It returns

Cloning into 'zpushgit'...
fatal: repository 'https://github.com/yodax/mailinabox/tree/zpushgit/' not found

NO ONE IS READY TO PASTE STEP BY STEP SSH CODE to install MAILINABOX SUCESSFULLY without the error of zpush.

i am tired bro for the past 6 days now.

**Comment by rootion** [comment]
I typed the wrong command from my terminal, it should have been:
`git clone -b zpushgit https://github.com/yodax/mailinabox.git`
Just tested it. It works.

**Comment by donsicilly** [comment]
@yodax 
Since you have solution to fix this problem..
WHY CAN'T YOU PASTE STEP BY STEP SSH CODE to install MAILINABOX SUCESSFULLY without the error of zpush...Starting from cloning your branch till the mailinabox successfully installed?

**Comment by donsicilly** [comment]
FOR THOSE WHO KNOW PROGRAMMING MORE THAN US BELOW IS THE EXAMPLE WHAT TO TEACH AND HELP FIX PROBLEM AND SITUATIONS NOT BY JUST GIVEN HALF INFORMATION.

zpush error fixed

Follow below steps to sucessfully install mailinabox

sudo apt-get update && sudo apt-get upgrade
apt-get install git nano curl
git clone -b zpushgit https://github.com/yodax/mailinabox.git
cd mailinabox
sudo setup/start.sh

**Comment by edwardstechncial** [comment]
Thank you
installed successfully. 

sudo apt-get install git-all
sudo apt-get upgrade
sudo apt-get update
sudo git clone -b zpushgit https://github.com/yodax/mailinabox.git
cd mailinabox
sudo setup/start.sh

**Comment by yodax** [comment]
I deliberately didn’t give any detailed instructions. This is just to test if the fix works. If you don’t know how to clone a different branch it is very likely you also don’t know how to change remotes when you want to go to the upstream/master again. Meaning a second support issue.

**Comment by fedpettinella** [comment]
Looking forward to this being in the master branch.

**Comment by JoshData** [comment]
I merged the PR above. Thanks all.

**Comment by dkemmet** [comment]
Hi All, 

I would like to post my work around that allowed to successfully install MIAB, AND get back to @JoshData's official branch after working around the z-push packages schenangians. 

[](1. New DO Droplet accoring to instructions
2. apt-get install git
3. cd ~ (to be safe)
4. git clone -b zpushgit https://github.com/yodax/mailinabox.git
5. cd mailinabox
6. bash setup/start.sh
7. (installation ensues, once complete you will have v0.13 installed, however the latest is v0.25 so we're gonna do the following to get back on track)
8. Take snapshot of Droplet
9. cd ~ && rm -rf mailinabox/*
10. git clone https://github.com/mail-in-a-box/mailinabox
11. bash setup/start.sh
12. ???
13. profit?)

Hope this helps while we wait for a push to release!

**Comment by yodax** [comment]
It should just work if you start with step 10. My changes are in master.

**Comment by NimKulia** [comment]
fatal: destination path 'mailinabox' already exists and is not an empty directory
solution: - ubuntu 14.04
sudo apt-get install git-all
sudo apt-get upgrade
sudo apt-get update
apt-get install trash-cli
trash mailinabox
sudo git clone -b zpushgit https://github.com/yodax/mailinabox.git
cd mailinabox
sudo setup/start.sh

**Comment by yodax** [comment]
Don’t do it that way. Don’t clone my fork. Remove the existing directory. Clone the master branch from miab directly.

**Comment by fedpettinella** [comment]
@JoshData Could we have this in the release so we can do `curl -s https://mailinabox.email/setup.sh | sudo bash`?

**Comment by JoshData** [comment]
There are some other issues that I'd really like to square away before making another release https://github.com/mail-in-a-box/mailinabox/labels/release%20blocker%21 since they're preventing new installs.

**Comment by ali3seven** [comment]
Thanks yodax, It works fine for me too. (Ubuntu 14.04.3)
didn't show no zpush wrong checksum again and installation continued:

sudo apt-get install git-all
sudo apt-get upgrade
sudo apt-get update
sudo git clone -b zpushgit https://github.com/yodax/mailinabox.git
cd mailinabox
sudo setup/start.sh

**Comment by hachre** [comment]
It's amazing how nobody listens... :P

**Comment by meglio** [comment]
Step 9 should be `cd ~ && rm -rf mailinabox`, not `cd ~ && rm -rf mailinabox/*` (in order to remove the whole mailinabox directory. Otherwise git clone in the following steps won't work.

Step 11. Before doing `bash setup/start.sh`, you'll need to `cd mailinabox`.

**Comment by yodax** [comment]
I’ve deleted my branch.

**Comment by ali3seven** [comment]
> You don't need the yodax fork. The fix is in the official repo in master.
Please just use that!

@hachre  Thanks but I'm afraid that it works now. 
here is the output after got clone official repo and run start.sh: 
`#bash start.sh`
`start.sh: line 5: setup/functions.sh: No such file or directory `
`start.sh: line 10: setup/preflight.sh: No such file or directory `
`start.sh: line 34: setup/migrate.py: No such file or directory `

Actually I saw these file in the directory but I don't know why prompt. 
Completely reboot and remove old folder, no luck. 
Are you sure it works? or Any idea?

**Comment by hachre** [comment]
You need to be in the `mailinabox` folder and run `bash setup/start.sh`. It looks like you were within `mailinabox/setup` and ran `bash start.sh`. That doesn't work!

**Comment by ali3seven** [comment]
@hachre Thanks for your hint and very quick reply, You are absolutely right. I followed the installation. it seems all the things done well. Installation was completed.
But after cannot access admin url. infact it seems there is not any 80, 443 port for listen web access. Also nginx service status shows _running_. I was wondering if you have any hint for that too. Thanks.

**Comment by rootion** [comment]
First time I installed I had the same issue and couldn't access the IP address/admin. So I deleted `mailinabox` folder, cloned the repository again, ran the install again and it worked perfectly.

**Comment by ali3seven** [comment]
@fedpettinella @rootion Thanks all, I will try it and continue on #1298 . 
Also It's very nice to see bodies help each other without expecting anything. Plenty of Thanks for OpenSource and Plenty Thanks Guys.
