### ISSUE TITLE
Why so much memory?

### ISSUE THREAD

**Issue by hynese** [mail-in-a-box/mailinabox#131]
Hi, 

My VPS is 512MB. Why is 1GB needed?

I hacked the script to allow installation on 512MB.

I added 1GB of swap space. 

Will I be ok? My server does about 100 to 1000 emails an hour...

Thank you for this great project!

**Comment by gnite** [comment]
I've been running miab for about a year now on a 512MB machine and everything is working awesome, maybe change the script to only give a warning when less than 768MB instead of completely stopping so one doesn't have to go modifying files before every upgrade?

**Comment by JoshData** [comment]
Now that we turn on swap space, we could reconsider the minimum.

**Comment by yodax** [comment]
The memory requirements have gone down by dynamically allocating and reducing the size of the thread pool of the management daemon. 

My typical allocation on my prod box went down from 600mb to around 250-300. That is with 5 users. That could be considered home use. 

The status checks also report memory issues. 

I think swap should only be used during peak allocation, to prevent crashes of spamassasin. 

Given all that, I think it can be lowered to 512mb.

**Comment by dhpiggott** [comment]
I converted my Digital Ocean Droplet from 1GB to 512MB a month or two ago. It has continued to run perfectly so far.

The current check in setup did mean that I had to temporarily override the minimum when I upgraded to v0.19 the other day. So I would see permanently lowering it to 512MB as a good thing.

**Comment by ezraholm50** [comment]
```
Here you go, whole totorial about zRam in Ubuntu:

    zRam is a code inside kernel, that once activated, creates a RAM based block device which acts as a swap disk, but is compressed and stored in memory, allowing very fast I/O and increasing the amount of memory available before the system starts swapping to disk.

    zRam is integrated into the Linux kernel 3.2 and above, so it's included already in Ubuntu 12.04.

    Previously on my 2GB machine, without zRAM, when i open lots of browser tabs, the system start choking, while HDD start copying data to SWAP causing a total slowdown. Now after activating zRam, instead of freezing after running out of RAM, the system worked like nothing happened. I didn't notice any difference at all. It looked just like adding more RAM ;)

    From my experience, zRam is useful for people using computers with 1GB or 2GB RAM. Since zRam is compressing data, it require some processor resources. Not much, but always. For that reason i do not recommend to use it with old processors. Also if you have 4GB RAM most likely it won't be necessary to use it.

    To activate it, type in terminal:

  `  sudo apt-get install zram-config`
```

```
All depends of what you use.... there is no "one size fits all"

If you use heavy memory aplications and little cpu, you will probably see a increase in performance with ZRAM. On the other side, a CPU bound application with little memory usage will see a possible DECREASE in performance (as RAM usage might trigger the ZRAM and steal some cpu cycles that would otherwise would go to the app)

you need to monitor your machine for cpu and ram/swap usage to view it's the long term usage.

    If free RAM, no swap, ZRAM is useless.
    If free RAM, some swap usage, but less than the free RAM, ZRAM is useless, just tune the swappiness so the swap is less used
    If free RAM, some swap usage, but a lot more than free RAM, try first to tune the swappiness and the apps, to decrease the ram usage. If no change, try ZRAM is our cpu is free most of the time
    IF no free RAM, swap usage high, ZRAM might be a good idea, even if CPU is used, as IO operation might be blocking the CPU more than what you would lose with ZRAM

```

Might be something to look in to.

https://raspberrypi.stackexchange.com/questions/34179/can-zram-improve-performance-when-running-rpi2-os-partition-from-usb

http://raspberrypi.stackexchange.com/questions/8053/use-of-zram-module-in-raspberry-pi-kernel

**Comment by anoma** [comment]
What command best summaries RAM usage in this context, so we can post some results.

**Comment by yodax** [comment]
I think the munin memory graph shows it best.

**Comment by anoma** [comment]
![screenshot 53](https://cloud.githubusercontent.com/assets/1133344/17769178/50b48dbe-652f-11e6-9be6-46f9dae83297.jpg)

6 domains, 11 addresses, 20+ aliases, ~5 humans

**Comment by yodax** [comment]
<img width="505" alt="schermafbeelding 2016-08-18 om 15 43 24" src="https://cloud.githubusercontent.com/assets/5643940/17775885/9bd3cfd2-655a-11e6-906f-9623cc126ec0.png">

Most of the allocation is caches. The box has 2GB of memory. The apps just fit in 512 with a bit of swapping. That is with 5 domains, 6 mailboxes, 4 users. 

Perhaps we can lower the check to 512, but recommend 768?

On @anoma's graph you can see the apps memory drop after the release that contained the thread pool stuff.

**Comment by JoshData** [comment]
Ok. I'll accept a PR that changes the minimum to 512 but emits a warning on the console recommending 768 if the user is below 768. The problem with too little memory is that spamassassin just crashes, and that's hard for many users to recover from.
