### ISSUE TITLE
z-push checksum mismatch breaks install

### ISSUE THREAD

**Issue by dkemmet** [mail-in-a-box/mailinabox#1310]
Hi all, 

I'm trying to install mailinabox on an ubuntu 14.04 droplet on Digital Ocean however I'm running into the following issue:

```
Installing Z-Push (Exchange/ActiveSync server)...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of http://download.z-push.org/final/2.3/z-push-2.3.8.tar.gz did not match expected checksum.
Found:
66b1613faef61590836682ff1a43d559827fe08b  /tmp/z-push.tar.gz

Expected:
aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb  /tmp/z-push.tar.gz
root@box:~#
```

Is there a way to force install or sanely resolve this issue? will [the manual install instructions for z-push ](https://wiki.z-hub.io/display/ZP/Installation) suffice?

Thanks!

**Comment by hachre** [comment]
Hi there,

this has already been discussed (and fixed) here:
https://github.com/mail-in-a-box/mailinabox/issues/1304

Instructions in there as well!

**Comment by dkemmet** [comment]
@hachre I'm not sure if something is still broken but I cloned master according to the instructions on the home page of the project git and it was still broken (v25). However I pulled @yodax 's branch and it worked perfect. 

Thank you both for your help and engagement!

**Comment by hachre** [comment]
The fix is in master, but not in a release yet. 
Just remember that you will have to switch back to the official mail-in-a-box repo to get updates!

**Comment by dkemmet** [comment]
@hachre is there a difference between the updates I will get through git pulls v. in-software updates? This is only my second time deploying this software so all the contextual information I can get the better!

**Comment by hachre** [comment]
`git pull` in your case would try to pull from yodax's fork, which won't receive any updates.

The integrated update system takes care to only update you to actual releases (it switches the branch accordingly and pulls). I am pretty sure the integrated updating will not work while you're on yodax's fork. 

You will need to manually change the origin of the git tree on your server or delete it and run the official setup line again to fix it. But don't do it before an official release is out with this fix. Just write it on a todo list for now ;)

**Comment by dkemmet** [comment]
@hachre appreciate it this. Thank you! merry christmas!
