### ISSUE TITLE
use certbot to provision TLS certificates

### ISSUE THREAD

**Issue by ppKrauss** [mail-in-a-box/mailinabox#1314]
https://certbot.eff.org is so simple to install and maintain.

**Comment by JoshData** [comment]
If you or anyone can replace our custom TLS cert provisioning stuff with certbot, that'd be great.

**Comment by ppKrauss** [comment]
I was tested with [Apache](https://certbot.eff.org/#ubuntutrusty-apache) and [NGINX](https://certbot.eff.org/#ubuntutrusty-nginx), it is fine to install with default instructions of these links... But need to decide (with others) to use MailInABox (to test and suggest a concrete procedure here)... Otherwise I can help here with my certbot experience, if you show your procedure: perhaps we can suggest alternative for [nginx-ssl.conf](https://github.com/mail-in-a-box/mailinabox/blob/master/conf/nginx-ssl.conf).

**Comment by JoshData** [comment]
Done via PR above.
