### ISSUE TITLE
Error installing due to Z-Push update on Dec 22

### ISSUE THREAD

**Issue by terrymacdonald** [mail-in-a-box/mailinabox#1327]
HI,

Z-Push was updated on Dec 22 2017 which breaks the installation script. See here for more info: http://z-push.org/z-push-2-3-8-final-release-update/

The SHA1 has changed to 66b1613faef61590836682ff1a43d559827fe08b. Please update the install script to include this version.

Example output:

....
Installing SpamAssassin...
Removing apache...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of http://download.z-push.org/final/2.3/z-push-2.3.8.tar.gz did not match expected checksum.
Found:
66b1613faef61590836682ff1a43d559827fe08b  /tmp/z-push.tar.gz

Expected:
aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb  /tmp/z-push.tar.gz

**Comment by yodax** [comment]
Thanks for posting! This has been fixed in master, but not released yet. If you want you can clone master or wait for the release. (Master is the release candidate)
