### ISSUE TITLE
reduce munin-node log_level

### ISSUE THREAD

**Issue by barrybingo** [mail-in-a-box/mailinabox#1329]
Ubuntu packaged munin-node.conf has default [log_level](http://guide.munin-monitoring.org/en/latest/reference/munin-node.conf.html#cmdoption-arg-log-level) 4.  On my system the logs are now multiple gig.

0=err, 1=warning, 2=notice, 3=info, 4=debug.

Propose reducing log_level in /etc/munin/munin-node.conf to 0 or 1

**Comment by JoshData** [comment]
Setting it to 1 is fine with me.
