### ISSUE TITLE
this is not a valid mail

### ISSUE THREAD

**Issue by JK44** [mail-in-a-box/mailinabox#1333]
see here http://prntscr.com/i3lsi8     i changed it many time. but not working

**Comment by gcampedelli** [comment]
Same here

**Comment by gcampedelli** [comment]
Hello, I did git checkout v0.25 and it worked

**Comment by JoshData** [comment]
Dup of #1326. We can leave this one open so people see it, until the next release.

**Comment by grinay** [comment]
same thing. Cant install This is not a valid email.

**Comment by JK44** [comment]
@gcampedelli  please let me know how can i install v0.25. thank you

**Comment by grinay** [comment]
So .I solve this just download latest version from this hub.

git clone https://github.com/mail-in-a-box/mailinabox.git
cd mailinabox
./setup/start.sh

And it works for me.

**Comment by gcampedelli** [comment]
Hello everyone. While I tried every possible solution to install Mail-in-box, I finally found the solution. 
Mail-in-box requires us to have a server for it. It has to be Ubuntu 14.04. Usually when we proceed to install we type the command "apt-get update && apt-get upgrade". At least we know it as best practice. So, I tried to install master without git checkout and without prior doing apt-get update and upgrade. It just installed last version and it works ok. After installing you can apt-get update and upgrade.
