### ISSUE TITLE
Please, help, how can I solve this? DNS and certificate

### ISSUE THREAD

**Issue by gcampedelli** [mail-in-a-box/mailinabox#1336]
cd mailinabox
command: sudo ./management/ssl_certificates.py --force

Result:
No TLS certificates could be provisoned at this time:

box.domain.com: DNS isn't configured properly for this domain: DNS resolution failed (AAAA: The DNS response does not contain an answer to the question: box.domain.com.br. IN AAAA).
espressivo.com.br: DNS isn't configured properly for this domain: DNS resolution failed (AAAA: The DNS response does not contain an answer to the question: espressivo.com.br. IN AAAA).
www.domain.com: Domain control validation cannot be performed for this domain because DNS points the domain to another machine (A XX.XX.XX.XX).

**Comment by KeiroD** [comment]
Did you register your nameservers at your domain registrar? If not, you need to do that and then after that, you should be able to delegate DNS to your `mailinabox` nameservers.

**Comment by gcampedelli** [comment]
Hello KeiroD, thank you for answering. I actually registered everything. The problem was coming from the fact that I didn't configure Custom DNS in Mail-in-a-box admin panel. Once I did that, I could provide a certificate for subdomain. Everything is up and running.

**Comment by yeah** [comment]
Just a general polite reminder that the Github issues should be used for bugs and features in order to improve Mail-in-a-Box.

For user questions and help, please use the [Discourse forum](https://discourse.mailinabox.email). Thanks!
