### ISSUE TITLE
Broken admin screen on v0.26

### ISSUE THREAD

**Issue by KeiroD** [mail-in-a-box/mailinabox#1337]
Hi,

I have a broken upgrade with v0.26 on Ubuntu Server LTS 14.04.

See screenshot

![broken-admin](https://user-images.githubusercontent.com/3938118/35382693-a15e5b8e-0185-11e8-9bc6-c6fb7f2f165d.png)

Reverting to v0.25 doesn't work because of the stupid ZPUSH checksum error and using the master branch doesn't resolve this issue.

So... what am I supposed to do now? The admin panel is horribly broken and reinstalls are not working for either v0.25 or v0.26.

Also...

```
root@heimkoma:~/mailinabox# git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

So uh... yeah.

**Comment by JoshData** [comment]
I've posted a new release. Please try it and let us know?

**Comment by KeiroD** [comment]
Trying now, will post results shortly.

Stand by.

**Comment by KeiroD** [comment]
Hi,

Negative. That did not work. The only error that popped was the following:

`The management daemon refused access. The API key file may be out of sync. Try 'service mailinabox restart'.`

Full output of setup script:

```
Primary Hostname: heimkoma.com
Public IP Address: 71.45.197.138
Private IP Address: 172.16.0.6
Mail-in-a-Box Version:  v0.26b

Updating system packages...
Installing system packages...
Initializing system random number generator...
Opening alternate SSH port 2200.
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
Incorrect username or password
Incorrect username or password
No domains hosted on this box need a new TLS certificate at this time.
The management daemon refused access. The API key file may be out of sync. Try 'service mailinabox restart'.

-----------------------------------------------

Your Mail-in-a-Box is running.

Please log in to the control panel for further instructions at:

https://heimkoma.com/admin

If you have a DNS problem put the box's IP address in the URL
(https://71.45.197.138/admin) but then check the TLS fingerprint:
```

**Comment by JoshData** [comment]
Try a reboot?

**Comment by KeiroD** [comment]
Hi,

No change, alas. Any particular logs you want me to pull snippets from?

**Comment by jookk** [comment]
Im running on v0.25. So, it is safe to uprade to latest 0.26b or not?

**Comment by yodax** [comment]
I think this will be solved be rebooting the server, pulling master and starting the setup again. I suspect something went wrong with locking the files. I wonder what version you were upgrading from @KeiroD ? It looks you haven't received the assets moved change yet. If you still see the broken admin try CTRL (or CMD if you're on macOS) + R in the browser.

**Comment by yodax** [comment]
From your first post I couldn't for sure determine it was v.0.25, just checking. Can you run tools/dns_update and report back what it says?

This tries to access the deamon from the console. (if it works it doesn't break anything). You could try removing the key and starting the service again and see if the key is replaced.

**Comment by jookk** [comment]
So I upgraded my box successfully. Admin ui working. All fine.
After upgrade I rebooted box

**Comment by KeiroD** [comment]
```
root@heimkoma:~/mailinabox# tools/dns_update
Incorrect username or password
```
Oh hey, it looks like I have my admin control panel back. About damn time. Unfortunately my e-mail is now no longer working.

**Comment by yodax** [comment]
This tells me that the old deamon is still running. Can you try rebooting again or follow the kill the existing process (not via service stop) and restart the service.

**Comment by KeiroD** [comment]
I'm back in now. Killed it off via `htop`. Started with `service mailinabox start` and all is well.

Not sure what's up with the broken assets stuff though... but I restarted nginx and that seems to have done the trick in restoring everything. I guess it wasn't properly picking up the change?

**Comment by yodax** [comment]
I guess so, glad it's working now :)
