### ISSUE TITLE
Error mails from Cron Daemon

### ISSUE THREAD

**Issue by henningwerner** [mail-in-a-box/mailinabox#1341]
Since the upgrade to v0.26b I got every day error mails from the cron daemon:

> /etc/cron.daily/mailinabox-dnssec:
> Incorrect username or password
> /etc/cron.daily/spamassassin:
> rules: failed to run FORGED_GMAIL_RCVD test, skipping:
> 	(Can't locate object method "check_for_forged_gmail_received_headers" via package "Mail::SpamAssassin::PerMsgStatus" at (eval 1323) line 19.
> )
> channel: lint check of update failed, channel failed
> sa-update failed for unknown reasons

Strange is, the error mails are different from day to day - here the first mail:
> /etc/cron.daily/mailinabox-dnssec:
> Incorrect username or password

I have also re-run the install script but no effect onto the error mails.

But on upgrade/re-run I got following error from Munin:
```
Installing Munin (system monitoring)...
Incorrect username or password
Incorrect username or password
```
Also got following error:
> The management daemon refused access. The API key file may be out of sync. Try 'service mailinabox restart'.

How can I fix this credential issue (little bit strange because I changed no password)?

**Comment by just4t** [comment]
Hope this helps:  https://discourse.mailinabox.email/t/error-upgrading-from-v0-25-to-v0-26/2798/9?u=just4t
