### ISSUE TITLE
Discourse is down?

### ISSUE THREAD

**Issue by mitchellurgero** [mail-in-a-box/mailinabox#1342]
I am getting 403 errors all over the discourse site, just wanted to give a heads up.

**Comment by JoshData** [comment]
I tried to upgrade it this morning after putting off upgrading Discourse versions for at least a year or two.... and things went wrong. Right now the site should be serving pages (not 403'ing), but I'm unable to log in because of something related to cookies and CSRF tokens, I think.

**Comment by JoshData** [comment]
Ok everything should be working again now.

**Comment by mitchellurgero** [comment]
Looks good, will close issue.
