### ISSUE TITLE
Let’s Encrypt SSL manual renew

### ISSUE THREAD

**Issue by KrasBras** [mail-in-a-box/mailinabox#1350]
Hello, please tell is it possible to renew the Let’s Encrypt SSL manually. For the past year i had to reinstall all from scratch 2 times as the auto renew does not work. Here is the message i get
**Something unexpected went wrong: [NeedToInstallFile…**
Can i install certbot and renew the SSL manually?

**Comment by grant-herman** [comment]
This is causing issues in forks as well, I believe it is due to LetsEncrypt changing syntax/retrieval methods. They do it quite often, for reasons unknown to me. Looking in the recent documentation would be my suggestion.

**Comment by Dibbyo456** [comment]
@KrasBras Can you post the exact error?

**Comment by mcblum** [comment]
We've been getting the same errors and this time moving to a new box didn't work. I just spent the day doing it only to have the same errors. For me when I try to renew via the command line I get
```
root@box:~/mailinabox# python ./management/ssl_certificates.py
  File "./management/ssl_certificates.py", line 500
    % request["url"], end='', flush=True)
                         ^
SyntaxError: invalid syntax
```

**Comment by JoshData** [comment]
(Let's go over to #1362...)
