### ISSUE TITLE
Sending mail internal without authentication

### ISSUE THREAD

**Issue by Jelle0637** [mail-in-a-box/mailinabox#1356]
It's possible to send internal mail without authentication from a remote server:
```
telnet mail.xxx smtp
Trying xxx...
Connected to mail.xxx.
Escape character is '^]'.
220 mail.xxx ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
EHLO mail.xxx
250-mail.xxx
250-PIPELINING
250-SIZE 134217728
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
MAIL FROM:jelle@xxx
250 2.1.0 Ok
RCPT TO:systeem@xxx 
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Subject: Test message

This is a test message
.
250 2.0.0 Ok: queued as 735AC8021E

```
If you get:
`450 4.2.0 <systeem@xxx>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/xxx.html`
Then try again in 5 minutes.

**Comment by JoshData** [comment]
Hi. So to clarify the issue you're raising, it's that if the box is managing mail for domain xxx, it accepts mail "from" xxx without user authentication, thereby allowing spoofed "envelope from" addresses.

This is to some extent by design. There are no universal rules about rejecting email based on the "envelope from" domain because there are so many non-compliant senders universal rules tend to cause some trouble for just about everyone. SPF rules are largely ignored by mail servers --- we set SPF records but we don't check them. And DKIM checks the From: header address which is independent of the "envelope from" domain, and as with SPF we do it on outbound mail but don't enforce the rules on inbound mail.

**Comment by SchneidersJelle** [comment]
Hi,

Well if we add the from and to headers like this:
```
telnet mail.xxx smtp
Trying xxx...
Connected to mail.xxx.
Escape character is '^]'.
220 mail.xxx ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
EHLO mail.xxx
250-mail.xxx
250-PIPELINING
250-SIZE 134217728
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
MAIL FROM:jelle@xxx
250 2.1.0 Ok
RCPT TO:systeem@xxx
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Subject: Test
From: jelle@xxx
To: systeem@xxx

This is a test message
.
250 2.0.0 Ok: queued as A6BF78021E
```
It will be received without any errors to the user:
<img width="734" alt="screen shot 2018-02-19 at 22 23 18" src="https://user-images.githubusercontent.com/11708616/36397570-9ff59a76-15c3-11e8-8cee-29182c01c953.png">

See also this mail headers:
```
Return-Path: <jelle@xxx>
Delivered-To: <systeem@xxx>
Received: from mail.xxx ([127.0.0.1])
	by mail.xxx (Dovecot) with LMTP id eEj+Fdw/i1qDXQAA8p8XQw
	for <systeem@xxx>; Mon, 19 Feb 2018 22:21:32 +0100
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on
	mail.xxx
X-Spam-Level: **
X-Spam-Status: No, score=2.6 required=5.0 tests=BAYES_40,MISSING_DATE,
	MISSING_MID,RDNS_NONE autolearn=no autolearn_force=no version=3.4.0
X-Spam-Report: 
	* -0.0 BAYES_40 BODY: Bayes spam probability is 20 to 40%
	*      [score: 0.3743]
	*  0.8 RDNS_NONE Delivered to internal network by a host with no rDNS
	*  1.4 MISSING_DATE Missing Date: header
	*  0.5 MISSING_MID Missing Message-Id: header
X-Spam-Score: 2.6
X-Greylist: delayed 276 seconds by postgrey-1.35 at mail.xxx; Mon, 19 Feb 2018 22:21:01 CET
Authentication-Results: mail.xxx; dmarc=fail header.from=xxx
Received: from mail.xxx (unknown [EXTERNAL_SERVER_IP])
	by mail.xxx (Postfix) with ESMTP id A6BF78021E
	for <systeem@xxx>; Mon, 19 Feb 2018 22:20:48 +0100 (CET)
Subject: Test
From: jelle@xxx
To: systeem@xxx

This is a test message
```

I don't think this should even be possible?

**Comment by JoshData** [comment]
I'm not sure what you mean by not being possible.

As I said, we don't reject any incoming mail based on content (including headers). Most mail systems don't. I'm certainly open to changing that, but it is not simple.
