### ISSUE TITLE
Allowing custom CSS or implementing a quick CSS theme changer?

### ISSUE THREAD

**Issue by mitchellurgero** [mail-in-a-box/mailinabox#1357]
Since you are using bootstrap for the admin UI, If someone were to implement a bootstrap theme changer, would you accept the pull request?

themes, which are MIT licensed, like https://bootswatch.com/ are really nice looking and can keep the UI the same while allowing an admin some basic customization options.

EDIT: The changes are subtle, but they do look very nice.
Screens for reference:
![box2](https://user-images.githubusercontent.com/4168998/36603694-38425a16-1881-11e8-9115-b3f736dd36a5.png)
![box3](https://user-images.githubusercontent.com/4168998/36603695-38521726-1881-11e8-826e-11bedd460f9a.png)
![box1](https://user-images.githubusercontent.com/4168998/36603696-385f149e-1881-11e8-8a16-3471032be428.png)

**Comment by JoshData** [comment]
I'm not really interested in spending time on customization, but if you have a few small CSS changes that make the admin look better for everyone, that's easy enough to merge.
