### ISSUE TITLE
Being used for internal spam emails

### ISSUE THREAD

**Issue by johnnytv1** [mail-in-a-box/mailinabox#1360]
Hi, several of my clients and those of another agency we work with are receiving spam emails (regarding asking a member of staff to make fraudulent BACS payments) that appear to be being sent using this tool.

They are using domains such as uk-c.eu and then using subdomains of this such as CLIENTDOMAIN.uk-c.eu as a reply to address but have the email coming from the original email address. DKIM and SPF are set up for these accounts correctly yet appear to be being bypassed.

This is a very concerning attack as they will use names and details of the Directors to appear legitimate so could easily be viewed as genuine. I wanted to raise this as I don't know how much of a part Mail-in-a-Box is required by them to do so but stopping access could obviously only be a positive.

**Comment by biermeester** [comment]
Are you positive that the emails originate from your MiaB host? It's easy enough to send emails _claiming_ to come from your host, and DKIM/SPF is often enough (softly) ignored by mail servers.

You may try running `mailinabox/management/mail_log.py -lv` from the command line, and see if there's an unusual number of IP addresses logging in for the offending email addresses.

**Comment by johnnytv1** [comment]
Hi, I don't have a MiaB account - I'd found it because the emails originate from different subdomains of uk-c.eu and when visiting http://uk-c.eu in a web browser it shows a message of:

this is a mail-in-a-box

take control of your email at https://mailinabox.email/

**Comment by biermeester** [comment]
Ah, now I get it. Just to be clear, Mail-in-a-Box is not a tool, but rather a collection of tools, partially pre-configured to easily setup a mail server. Once it's installed no one but the administrator of that system can control it, meaning no one here can "stop" a MiaB installation sending spam.

There's a few things that might be going on:

- The MiaB installation at uk-c.eu is compromised
- The credentials of one or more email addresses handled by uk-c.eu have been compromised
- The spam messages just claim to come from the uk-c.eu  domain, but in actuality are being sent from somewhere else

So, your options are to try and contact the administrator of uk-c.eu and/or to report the domain at various email blacklists.

**Comment by johnnytv1** [comment]
Ok no problem thanks for your help

**Comment by just4t** [comment]
https://discourse.mailinabox.email/t/mail-in-a-box-being-used-to-send-internal-spam-emails/2989/2?u=just4t

**Comment by JoshData** [comment]
Closing this just so we keep the conversation to one place, but feel free to continue on the discussion forum.
