### ISSUE TITLE
Correct DNS settings to prevent being marked as spam (by gmail, outlook, etc)

### ISSUE THREAD

**Issue by olback** [mail-in-a-box/mailinabox#1361]
My DNS settings currently look like this: 
![screenshot from 2018-03-07 17-53-00](https://user-images.githubusercontent.com/8039145/37105846-7c00fd80-2230-11e8-9fc6-7019ce932522.png)

I've tried a bunch of settings but I can't get it to work and the install instructions only cover Nameserver DNS records. My domain is over two years old. mail.olback.net points to my box.

I know that issues like this are common but I feel like there should be a MIAB DNS-guide that covers external DNS settings like this.

**Comment by aroundmyroom** [comment]
Actually, what is your issue? I see that you have a MX record and the MX record is mail.olback.net this means that mail.olback.net needs to be your box. You state it is. So next issue.

under System within MIAB you see External DNS
here you see all kinds of lines you can add to your own DNS
so you can add your dmarc setting your SPF (you did), your domainkey etc.. 
If you add this your mail would be probably fine received.

When testing your mailserver with: https://mxtoolbox.com it is not responding.

I would love to know your issue(s) but it is unclear what. I think the external DNS part of MIAB is telling me what to do in my external DNS server, I cannot expect MIAB to tell how to  handle various different kinds of implementations of a DNS server out in the wild.

**Comment by olback** [comment]
I never noticed the external DNS settings page in my Admin panel, my bad. I added all the DNS settings to Cloudflare and outlooks seem to accept me. Google still thinks I'm sending spam. mail-tester is giving me a 10/10. Google seems to be more restrictive than other mail providers. I have no clue on how to get around/fix this and I'm not the only one having this issue. Closing for now though.

**Comment by olback** [comment]
Yeah, Google is really strict. Please post your response here.
