### ISSUE TITLE
Syntax error in ssl_certificats.py

### ISSUE THREAD

**Issue by mcblum** [mail-in-a-box/mailinabox#1362]
Hello! Woke up to expired certs and went to manually renew them and I'm getting the following error after running `python ./management/ssl_certificates.py`:

```
  File "./ssl_certificates.py", line 500
    % request["url"], end='', flush=True)
                         ^
SyntaxError: invalid syntax
```

I saw a couple of other suggestions to uninstall and reinstall pyOpenSSL, but that has not worked in this case. Does anyone have any ideas?

Thank you!

**Comment by mcblum** [comment]
I've also tried running the `mailinabox` command but it returns a series of errors:

```
/etc/resolvconf/update-libc.d/sendmail: 7: .: Can't open /usr/share/sendmail/dynamic
run-parts: /etc/resolvconf/update-libc.d/sendmail exited with return code 2
run-parts: /etc/resolvconf/update.d/libc exited with return code 1
```

I'll keep Googling in the meantime.

**Comment by mcblum** [comment]
Should anyone come across this, here's the fix for the sendmail issue:
http://e-mats.org/2013/04/dpkg-etcresolvconfupdate-libc-dsendmail-7-cant-open-usrsharesendmaildynamic/

**Comment by mcblum** [comment]
After that fix, I did a MIAB update and it went pretty well until, ironically, the thing that I started working on the first place:

```
ERROR:acme.challenges:Unable to reach http://box.domain.net/.well-known/acme-challenge/X033TQ...: HTTPConnectionPool(host='box.domain.net', port=80): Max retries exceeded with url: /.well-known/acme-challenge/X033TQ... (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff32b1df208>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by mcblum** [comment]
In order to try and troubleshoot this, I moved to a new box. I migrated all of our data and the results are exactly the same - still the cryptic `Something went wrong` and nothing in the logs.

**Comment by mcblum** [comment]
@JoshData thank you! I know that having an open source project this successful is probably, in a way, a curse. I wish I understood enough about how this works in order to fix it / contribute.

**Comment by JoshData** [comment]
I'll see if I can help you get to the bottom of this today. Let's go back to your old server if it's still running and try to see what the error is.

"python ./management/ssl_certificates.py" isn't the right way to launch this script (anymore). Just run:

    ./management/ssl_certificates.py

Let me know what happens when you do that?

If you're committed to using the new server, try running that *and*:

    ./management/status_checks.py

and let me know what/if anything comes back with an ex instead of a checkmark.

**Comment by mcblum** [comment]
I can't tell you how much I appreciate it. Mail being down is probably one of the most stressful thing.

I ran the script (the correct way this time) and it hangs for quite a while with no output. Then I get:
```
ERROR:acme.challenges:Unable to reach http://box.domain.net/.well-known/acme-challenge/X033TQrWxaHWfuu0DHT7wMFQveZYGiJnvPL9hE-7Mxc: HTTPConnectionPool(host='box.domain.net', port=80): Max retries exceeded with url: /.well-known/acme-challenge/X033TQrWxaHWfuu0DHT7wMFQveZYGiJnvPL9hE-7Mxc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f25e224b748>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
This is actually different than what I was getting through the UI, so at least it's giving feedback. Could this have to do with my redirecting to port 443?

**Comment by JoshData** [comment]
>  Could this have to do with my redirecting to port 443?

Say more about what you mean here. :)

What happens if you run

    curl -v http://box.domain.net/.well-known/acme-challenge/X033TQrWxaHWfuu0DHT7wMFQveZYGiJnvPL9hE-7Mxc

from on the box itself, and from a different machine (e.g. your desktop)?

**Comment by mcblum** [comment]
Well if LE is trying to renew the cert by hitting http://whatever and we're redirecting all requests to https://whatever but the cert is expired, maybe it's failing somehow?

When I curl literally nothing happens - it just times out. That said, I can reach the web interface just time and the IP is correct when I ping / curl.

**Comment by mcblum** [comment]
If I had to guess as to why the box can't resolve that itself it's because we run 1-to-1 NAT and split-horizon DNS. Basically all services with internal and external IPs need entries in our internal DNS to prevent them from leaving the network and coming back (because I never could get hairpin NAT to work).

**Comment by mcblum** [comment]
Also one other error that it just threw:
```
Something unexpected went wrong: [NeedToInstallFile('http://box.domain.net/.well-known/acme-challenge/X033TQrWxaHWfuu0DHT7wMFQveZYGiJnvPL9hE-7Mxc', 'X033TQrWxaHWfuu0DHT7wMFQveZYGiJnvPL9hE-7Mxc.8T3Z-1WKG1HjJn36AvE0dA7rHv23_mPJPbozJZFx_-o', 'X033TQrWxaHWfuu0DHT7wMFQveZYGiJnvPL9hE-7Mxc'), NeedToInstallFile('http://domain.net/.well-known/acme-challenge/scA0hBX3BI7er90kAkGal2kTCXRW4MhSMitKjWghkEM', 'scA0hBX3BI7er90kAkGal2kTCXRW4MhSMitKjWghkEM.8T3Z-1WKG1HjJn36AvE0dA7rHv23_mPJPbozJZFx_-o', 'scA0hBX3BI7er90kAkGal2kTCXRW4MhSMitKjWghkEM'), NeedToInstallFile('http://www.domain.net/.well-known/acme-challenge/7cDYAnvpQOJPWPrhRZUEDSNpWy909Ix4_AwikALMrYY', '7cDYAnvpQOJPWPrhRZUEDSNpWy909Ix4_AwikALMrYY.8T3Z-1WKG1HjJn36AvE0dA7rHv23_mPJPbozJZFx_-o', '7cDYAnvpQOJPWPrhRZUEDSNpWy909Ix4_AwikALMrYY')]
```

**Comment by mcblum** [comment]
Also, one thing that's weird about the split-horizon thing. We run internal nameservers and I was 99% sure that we had an entry for the mailserver. I checked `/etc/network/interfaces` and it's set correctly, but the dreaded `/etc/resolv.conf` is set to use `127.0.0.1` and I'm not sure exactly how the MIAB DNS is configured. Either way, it's resolving box.domain.net to the external IP which because of not using hairpin NAT would fail at the router. 

What I don't quite understand is why LE cares about our internal setup. If my machine can access the confirmation files then LE should be able to as well. Does MIAB do some sort of verification itself to make sure those files are accessible before sending the request to LE?

**Comment by JoshData** [comment]
> we're redirecting all requests to https://whatever 

Is that something you're doing outside of the box (or as a modification on the box)? Or are you just referring to the standard redirects that Mail-in-a-Box provides?

> If I had to guess as to why the box can't resolve that itself it's because we run 1-to-1 NAT and split-horizon DNS.

I don't know what any of that means. :)

> /etc/resolv.conf is set to use 127.0.0.1 and I'm not sure exactly how the MIAB DNS is configured

There's a bind server running locally to support DNSSEC resolution.

> it's resolving box.domain.net to the external IP which because of not using hairpin NAT would fail at the router.

That's almost certainly the root problem here.

> Does MIAB do some sort of verification itself to make sure those files are accessible before sending the request to LE?

That's exactly right. So, you could disable that verification, but if there's a way to adjust the DNS so that you don't have to change Mail-in-a-Box, that'd be preferable.

**Comment by mcblum** [comment]
> Is that something you're doing outside of the box (or as a modification on the box)? Or are you just referring to the standard redirects that Mail-in-a-Box provides?

Just the standard redirects which now after trying to curl the LE files, seems like it's definitely not an issue.

> If I had to guess as to why the box can't resolve that itself it's because we run 1-to-1 NAT and split-horizon DNS.

Honestly it's not important :) Basically just means that if MITB tries to resolve nationalmachine.net and it's using itself for DNS that request will be forwarded and it will resolve to the public IP, which will fail because the request will leave the network and immediately turn around and try to come back. 

> That's exactly right. So, you could disable that verification, but if there's a way to adjust the DNS so that you don't have to change Mail-in-a-Box, that'd be preferable.

Ok, I can do that. I didn't realize that was part of the process having only used Certbot in the past. What's the preferred way to add DNS to MITB? I can just add the local IP for all of the associated sites and I think that would fix it right away.

Once again, thank you for assisting with this.

**Comment by mcblum** [comment]
Ok so I added A records and set the IP to the IP of the box. That did not seem to fix the error. I'm going to try changing the IP to 127.0.0.1

**Comment by mcblum** [comment]
<img width="666" alt="screen shot 2018-03-11 at 1 33 18 pm" src="https://user-images.githubusercontent.com/1761867/37256984-cbe6eba4-2530-11e8-953c-d774b7128b43.png">

**Comment by mcblum** [comment]
Yeah a reboot did not seem to fix it. I'm going to modify /etc/hosts and just override this and see if that works.

**Comment by mcblum** [comment]
Ok, it's fixed. I don't know what's up with the DNS or why things went crazy, but adding everything to `/etc/hosts` fixed it.

I really, really appreciate the help on this. If you ever need help with the frontend stuff let me know - I owe you one.

**Comment by JoshData** [comment]
Glad it's working again!

**Comment by drpain** [comment]
@JoshData  I am running into the same issue. As a note, my server sits behind a Floating IP, so it will never resolve to the machine's IP Address.

**Comment by drpain** [comment]
^^^^^ I just installed certbot added an acme_challenge dns record and got a new cert. Symlinked it into /home/user-data. 

I don't know python well enough to be able to help fix the issue. Definately seems to have to do with the `acme` python module not containing the `jose` submodule. Probably renamed it to something proper instead of an oke's name

**Comment by goto-bus-stop** [comment]
@drpain The fix for me was to downgrade the acme dependency using `pip install acme==0.20.0` and rerun the ssl_certificates script. https://github.com/mail-in-a-box/free_tls_certificates/pull/12
