### ISSUE TITLE
admin: not possible to delete mails via IMAP

### ISSUE THREAD

**Issue by xatage** [mail-in-a-box/mailinabox#1364]
It is not possible to delete mails that are stored in my main admin account via IMAP. They are just marked as deleted and not moved to trash (no, it's not because of that setting in roundcube, via webUI it is possible to delete them). At the end I have a copy of that mail in trash as well.

First I thought that it's all because of that many redirections and the "+alias":
_admin+alias@example.net_ (=> _admin@example.net_) => _administrator@box.example.net_ => _me@example.net_
But no, with a user account and the same level of redirections and "+alias" it could be done without any problems. So, that issue exists only on the main admin account.

Is that a bug or a feature? Could somebody check it out and confirm, please?

**Comment by JoshData** [comment]
This is up to the mail client --- it's usually a setting. What you're describing sounds like normal IMAP behavior.

The box doesn't treat admin accounts differently from other accounts.

**Comment by xatage** [comment]
But that only happens on my main admin account. All the other accounts are performing the delete action very well as it should be (mails are moved to trash, not just marked as deleted). 

My mail client ist the standard Apple Mail.

**Comment by xatage** [comment]
I was a little bit wrong, sorry for that!

That is only happening when I delete mails from macOS Apple Mail and it's happening on every account (no matter admin or user). When I'm doing the same thing from iOS Apple Mail then everything is done the correct way. But I can't understand why? I never had those troubles with any other mail server before and now I'm using the same _.mobileconfig_ for both: iOS and macOS.

**Comment by zatricky** [comment]
@xatage / @JoshData - sounds like this one can be closed based on the last response

**Comment by xatage** [comment]
@JoshData 
Some days ago I finally figured out what was the issue. It was happening only in connection with macOS' Apple Mail client when deleting a message no matters on which account. It was just marked as deleted but was not removed from the inbox.

In roundcube's settings (Settings => Preferences => Server Settings) there is a point: "Do not show deleted messages". When it's enabled, no deleted messages are shown in the inbox (and possibly other places) anymore. By default it's disabled.

**Maybe you could consider to tick this point by default to avoid any confusion?**
