### ISSUE TITLE
Install setup.sh script broken

### ISSUE THREAD

**Issue by jvolkenant** [mail-in-a-box/mailinabox#1367]
You get this if you pull down the setup.sh script currently:

root@m:~# curl -s https://mailinabox.email/setup.sh
Loop detected on cache-lcy19247-LCY: TuFMEtJVICCO9h0Zpde/N9L9b7tugV9xeSSEt9M0!LCY!cache-lcy19247-LCY

**Comment by biermeester** [comment]
Weird. I cannot reproduce this behavior. Where is your box running?

**Comment by jvolkenant** [comment]
Yep, it's working now, maybe a hosting/cache issue.
