### ISSUE TITLE
Show mails sent with SMTP in SentMail

### ISSUE THREAD

**Issue by forteco** [mail-in-a-box/mailinabox#1370]
I use an api to send outgoing mail via mail-in-a-box via SMTP.

When I send mails via Thunderbird via SMTP, then this mails show in the Sent Inbox in IMAP.
When I send mails via SMTP via a program, they don't.
I guess that Thunderbird is doing additional things to move the mail to the Sent mail folder.
I think a feature "KeepSentMailsInSentMailMailbox" would make sense.
Regards
Andreas

**Comment by gholt** [comment]
SMTP has no access to your incoming mail; it is simply for outgoing mail. There is no easy way for SMTP to save copies like this.

Yes, Thunderbird can automatically save a copy of all mail it sends, but it uses IMAP to do that.

One thing you could do is to BCC yourself to have a copy of direct-SMTP emails also be sent to you. That would place them in your inbox, but perhaps a filter can move it to Sent for you automatically.

There are also other ways: https://www.chilkatsoft.com/p/p_461.asp
But, as you can see if you look at their code examples, they all send the email via SMTP and then save a copy via IMAP.
