### ISSUE TITLE
[RFC] Allow non-static sites in nginx templates

### ISSUE THREAD

**Issue by shakaran** [mail-in-a-box/mailinabox#1371]
I would like add some custom config in sites (for example load passenger and other tweaks) for each site.

I see that conf/nginx-alldomains.conf store all the config template which is rebuild in each management/web_update.py execution.

Probably it would be very useful if you can add something like:

`include /etc/nginx/mailinabox-custom/$host.*.conf`

In the first line of nginx-alldomains.conf so, it will be very easy to customize the nginx config per domain creating just a file, and nobody get hurts if the no file is used.

What do you think?

**Comment by JoshData** [comment]
That's a good idea but because $host is based on the HTTP Host header of the request, I don't think we can trust that it's safe to put in a filename. There's a hidden feature to do this though:

https://github.com/mail-in-a-box/mailinabox/blob/master/management/web_update.py#L168
