### ISSUE TITLE
Changing NGINX config to work with socket.io

### ISSUE THREAD

**Issue by 1337Steven1337** [mail-in-a-box/mailinabox#1372]
Hi guys,

Love this project, it got me set up and ready to go with ease! 
However I wanted to change the nginx config files using the configs defined in the mailinabox folder, but for some reason they did not apply/alter the config used by nginx itself.
Instead I had to alter /etc/nginx/conf.d/local.conf and make some changes there, but in that file it states that it is continuously updated by mailinabox and that changes will be overwritten by the mailinabox configuration. Where should I define my configuration?

Changes I made so far are:
Redirecting box.domain.com -> (https://)domain.com
I'm using a reverse proxy to my NodeJS server since im using socket.io in my project

Everything works as intended, but I'm afraid that my changes will be lost once mailinabox updates.

**Comment by just4t** [comment]
> Changes  I made so far are:  Redirecting box.domain.com -> (https://)domain.com

- This old post may help you to achieve what you exposed by using an _index.html_ file to redir rather than touching the nginx  _*.conf_ file : https://discourse.mailinabox.email/t/access-mailbox-from-a-subdomain/696/2?u=just4t

**Comment by 1337Steven1337** [comment]
@just4t Thanks for the response, that might help with redirecting indeed. But since I need the proxy to work aswell I still need to alter the config sadly.

**Comment by JoshData** [comment]
See  #1371 maybe?

**Comment by 1337Steven1337** [comment]
@JoshData Thanks for the comment, so if I am correct I should create a file at /home/user-data/{domainname}.conf and put my config in there?
If so, how should that config look like since I'd need to extend the (HTTPS) server block and proxy it to my NodeJS server.
