### ISSUE TITLE
Unable to SSH in to box.

### ISSUE THREAD

**Issue by kenken17** [mail-in-a-box/mailinabox#1378]
This morning i found out i cant access to my box any more. SSH port refused. Then I take a screen shot of the box. Found out need a box login? That is why is stuck and havent launch the system?

I am hosting on AWS. Any one have experience with this? I cant SSH in, how can i even input my box login credentials?

**Comment by Thomvh** [comment]
This is an AWS problem. Open up the ssh session via the AWS site and try that. That you need to login to the box is just normal.
