### ISSUE TITLE
Miab reports SSL certificate provision error

### ISSUE THREAD

**Issue by koningsvh** [mail-in-a-box/mailinabox#1384]
MIAB reports that the provisioning of a new SSL certificate failed, while it provisioned it correctly.
![image](https://user-images.githubusercontent.com/9131625/41219113-a622f60e-6d5d-11e8-80c3-8037148b7a27.png)

**Comment by tieroumpo** [comment]
Having the same issue

**Comment by geanttechnology** [comment]
upgrade your system by running the following this will resolve the issue:
curl -s https://mailinabox.email/setup.sh | sudo bash
