### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by cxdy** [mail-in-a-box/mailinabox#1404]
Hey.

My main server (example.com) is running a website. At my domain registrar, the nameservers point to the host of the server (ns1/ns2.vultr.com). I can set up DNS records from the Vultr control panel.

My MIAB box is running on a different server at mail.example.com. How should I set my DNS up so I leave my site on the main server up but can use email properly?

My current errors are:
**mail.example.com**
`Nameserver glue records (ns1.mail.example.com and ns2.example.com) should be configured at your domain name registrar as having the IP address of this box (111.111.111.111). They currently report addresses of [Not Set]/[Not Set]. If you have set up External DNS, this may be OK.`

`Your box's reverse DNS is currently 111.111.111.111.vultr.com, but it should be mail.example.com. Your ISP or cloud provider will have instructions on setting up reverse DNS for your box.`

**example.com**
`The nameservers set on this domain are incorrect. They are currently ns1.vultr.com; ns2.vultr.com. Use your domain name registrar's control panel to set the nameservers to ns1.mail.example.com; ns2.mail.example.com.`

(This one I will change when I get everything else in order.
`This domain's DNS MX record is incorrect. It is currently set to '10 mx.zoho.com; 20 mx2.zoho.com' but should be '10 mail.example.com'. Mail will not be delivered to this box. It may take several hours for public DNS to update after a change. This problem may result from other issues listed here.`

`This domain should resolve to your box's IP address (A 111.111.111.111) if you would like the box to serve webmail or a website on this domain. The domain currently resolves to 222.222.222.222 in public DNS. It may take several hours for public DNS to update after a change. This problem may result from other issues listed here.`

`This domain's DNSSEC DS record is not set. The DS record is optional. The DS record activates DNSSEC. To set a DS record, you must follow the instructions provided by your domain name registrar and provide to them this information:`

Sorry to ask something so stupid, I'm just absolutely braindead when it comes to DNS records.

**Comment by cxdy** [comment]
Nevermind, figured it out. Added the recommended records on the Custom/External DNS page. Works great.

**Comment by MohamedKabia** [comment]
Am having the same problem. Please how did you solve it

**Comment by cxdy** [comment]
> Am having the same problem. Please how did you solve it 
@MohamedKabia 

On the status page it tells you what DNS records to use, I just followed them. 

I have an A record for mail pointing to the mail server's IP.
Two MX records, one for mail.domain.com and one for domain.com
Two TXT records `"v=spf1 mx -all"`, one blank and one for mail.
A TXT record for mail._domainkey (DKIM)
Two TXT records `"v=DMARC1; p=quarantine"` one blank and one for mail.

Hope this helps!

**Comment by MohamedKabia** [comment]
Thanks a lot, your response helped me identify my error, my MX record was not box.domainname.
