### ISSUE TITLE
z-push source is unavailable, unable to complete install

### ISSUE THREAD

**Issue by nlivingstone** [mail-in-a-box/mailinabox#1414]
z-push.org is currently unavailable which causes the install process to hang when it attempts to download the z-push source.

is there an alternative source that would be suitable?

**Comment by dduong42** [comment]
@nlivingstone I have the same issue, and I hacked something with this: https://github.com/Z-Hub/Z-Push/releases/tag/2.3.9

**Comment by colinhall17** [comment]
Having the same issue, what did you hack together @dduong42 ?

**Comment by nlivingstone** [comment]
@dduong42 I tried that however it did not work for me. Can you provide some details on how you achieved this?

**Comment by atistrcsn** [comment]
@nlivingstone Same issue here but I have succeeded with the followings:
* Overwrite the `zpush.sh` file with the attached one in the zip (it contains the github url - thanks to @dduong42) in the `/root/laininabox/setup/` directory.
* run the installer again:
`$ sudo mailinabox`

[zpush.sh.zip](https://github.com/mail-in-a-box/mailinabox/files/2290514/zpush.sh.zip)

**Comment by colinhall17** [comment]
Thanks  @atistrcsn , now passed the z-push installer.  Fingers crossed the rest completes!

**Comment by nlivingstone** [comment]
@atistrcsn Thanks for the remedy, it worked like a charm. As a side note x-push.org is back online.
