### ISSUE TITLE
Error updating from .27 to .28

### ISSUE THREAD

**Issue by tecguru** [mail-in-a-box/mailinabox#1416]
I am getting the following message when trying to update

Updating Mail-in-a-Box to v0.28 . . .
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
error: Your local changes to the following files would be overwritten by checkout:
        tools/owncloud-unlockadmin.sh
Please, commit your changes or stash them before you can switch branches.
Aborting
Update failed. Did you modify something in /root/mailinabox?

I have not changed anything and when I run git diff management/status_checks.py it returns no results. Any advise?

**Comment by JumpLink** [comment]
This is a git error.
Git has detected local changes to a repository (the update script seems to try to update) and refuses to download the new changes until you have saved your local changes.

Did you change the file `tools/owncloud-unlockadmin.sh`?

Try to run `git stash` within the folder in which the error appears to put aside your local changes on `tools/owncloud-unlockadmin.sh` (and any other changes) and try to update mailinabox again.

**Comment by tecguru** [comment]
I had changed the file tools/owncloud-unlockadmin.sh I had forgot about that. Thanks for the help, moving that file to a different directory fixed the issue. 

On that note does anyone know when NextCloud 13 will be supported?

Thanks for your help

**Comment by JumpLink** [comment]
I think you should create a new issue for NextCloud and close this
