### ISSUE TITLE
[Question] How are users automatically added to NextCloud?

### ISSUE THREAD

**Issue by JumpLink** [mail-in-a-box/mailinabox#1418]
I would like to upgrade NextCloud to version 13 and wanted to see if the automatic addition of the e-mail user and other stuff would still work, but I did not find the corresponding code. How does this work?

I found that the mail user is added in the [mailconfig.py/add_mail_user method](https://github.com/mail-in-a-box/mailinabox/blob/master/management/mailconfig.py#L274) and user stuff needed to do after a user was added is in the [mailconfig.py/kick method](https://github.com/mail-in-a-box/mailinabox/blob/master/management/mailconfig.py#L553). But I have not found anything about OwnCloud / NextCloud

**Comment by JoshData** [comment]
NextCloud queries Dovecot over IMAP to check if a login is valid, and if so NextCloud will create its own user record the first time the user logs in. So there's nothing in Mail-in-a-Box that actually touches NextCloud's user database.

**Comment by JumpLink** [comment]
Oh good to know, thank you!
