### ISSUE TITLE
Upgrading to NextCloud 13

### ISSUE THREAD

**Issue by tecguru** [mail-in-a-box/mailinabox#1419]
Does anyone know if/when NextCloud 13 will be supported or how to update if it is?

**Comment by JumpLink** [comment]
I have update NextCloud manually [with this guide](https://docs.nextcloud.com/server/13/admin_manual/maintenance/manual_upgrade.html) and so far I have no problems.

Please note that Mail-in-a-Box installs NextCloud to `/usr/local/lib/owncloud` and not to `/var/www/nextcloud` as described in the guide.

**Comment by tecguru** [comment]
When I get to step 11 I get this error:

root@box:/home/user-data/owncloud# sudo -u www-data php occ upgrade
Nextcloud is not installed - only a limited number of commands are available

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "upgrade" is not defined.

**Comment by JumpLink** [comment]
The path you need to run this command is `/usr/local/lib/owncloud` and not `/home/user-data/owncloud`, I mentioned that in my previous comment.

In `/home/user-data/owncloud` there are only the config files.

**Comment by tecguru** [comment]
That worked. Thanks!
