### ISSUE TITLE
ubuntu_bionic memcached checks are not needed if memcached is retired

### ISSUE THREAD

**Issue by jvolkenant** [mail-in-a-box/mailinabox#1422]
https://github.com/mail-in-a-box/mailinabox/blob/ccc276903d3ce5b5eee91607e71243c0a746dbc2/management/status_checks.py#L31

**Comment by JoshData** [comment]
Thanks. I force-pushed to the branch and this is fixed now in e0fdd73421649d4b98a3b91b0f8bcae3b373e922.

**Comment by JoshData** [comment]
... I mean https://github.com/mail-in-a-box/mailinabox/commit/5e8839a77243b636aa459521597f9fad374c998e.
