### ISSUE TITLE
Customize config files

### ISSUE THREAD

**Issue by oliversturm** [mail-in-a-box/mailinabox#1429]
I need a custom value for dovecot default_vsz_limit in my setup. However, the logic in `setup/mail-dovecot.sh` is written to overwrite the value in `/etc/dovecot/conf.d/10-master.conf` every time I run `setup/start.sh`. What's the idea here? It's quite error-prone to have to apply any customizations manually each time the setup script is run. It's quite short-sighted to assume such modifications will never be needed. I'm sure I'm missing something! What is it?

**Comment by JoshData** [comment]
> It's quite short-sighted to assume such modifications will never be needed.

And yet after 5 years this project is doing just fine!

If you need to make modifications, you are free to do so. The project is open source and you have total control over your server. If you don't want to apply changes manually, you can do so using scripts just like we do.

> What's the idea here?

Idempotence and simplicity.

**Comment by oliversturm** [comment]
You sound offended. I apologize - it was not my goal to offend you or others who have worked on this project.

Of course I'm free to do what I want. However, I doubt I'm the only person, or the first, to come across the problem that idempotency and simplicity don't cover all use cases - and maintaining manual customizations across version updates in a reliable fashion requires some care and thought. My assumption was that this had already been invested somewhere in those five years. It probably has, more than once - I'll do it again and see if I can come up with something reusable.

**Comment by JoshData** [comment]
> it was not my goal to offend you or others

Apology accepted. Thank you. Just as some advice, if you avoid telling people they're short-sighted then you'll be less likely to offend them.

> idempotency and simplicity don't cover all use cases

They certainly don't, but they are the use cases of this project. There's no one-size-fits all in technology. I picked a narrow use case and the folks here are doing our best to make that use case be as good as possible. More use cases is more work, which no one here has time for.
