### ISSUE TITLE
ubuntu_bionic rsync backup not working

### ISSUE THREAD

**Issue by jstummbillig** [mail-in-a-box/mailinabox#1431]
I am having troubles getting rsync backup to work with the ubuntu_bionic branch unter 18.04. It might or might not carry over to 14.04, which I have never used an

Here is where I am at: I set up rsync got an “ok” status in the webinterface and, confirming back at the destination, the first backup files were created. Perfect.

Now, a few days later I noticed that no further backup files were created on the backup server. Checking back in the web interface I am now receiving a rather cryptic error popup, just saying ‘20180910T100118Z’. Also there is nothing but “Loading…” listed at the bottom of the page under “Available Backups”.

I tried rebooting, rerunning the miab setup, I also tried removing and recreating user and backup folders on the remote location, but the result stays the same: The initial setup seems to work, a set of backup files are being created on the remote and from that point on things seem to stop working.

Any ideas would be much appreciated! :)

**Comment by zatricky** [comment]
In case anyone remembers this mentioned elsewhere, it was also posted by OP (link below) a couple of days prior. I haven't found other references to this problem however.

https://github.com/mail-in-a-box/mailinabox/pull/1398#issuecomment-419866066

**Comment by JoshData** [comment]
I'm having the same error. It looks like duplicity changed a bit in Ubuntu 18.04 and some of the backup files it creates have an inconsistent date in the file name. Duplicity itself seems confused when I run it to verify the backup files.

**Comment by JoshData** [comment]
I've pushed a commit that prevents the Mail-in-a-Box control panel from failing when there are invalid backup files, but duplicity itself can't figure out what's going on and incremental backups halt after a few days. This is a huge blocker for the ubuntu_bionic release.....

**Comment by JoshData** [comment]
Duplicity seems to be working again for me. I'm not sure if there was a bug that was fixed in the last few weeks, but I kept re-running the install lines for the relevant tools from our scripts and now it's been working for about a week. I'll keep this issue open a bit longer but if no one has a problem still hopefully we can close it soon.

**Comment by JoshData** [comment]
Ok so this is embarrassing. After creating a new box to run the ubuntu_bionic branch, I forgot to shut down my old Mail-in-a-Box. The old box was writing backups at the exact time to the same backup destination, which was confusing duplicity. Anyway, I figured out why my backups were crazy. Hopefully no one else is still having a problem. So I'm closing this.
