### ISSUE TITLE
Master is now the 0.29 release candidate

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#1440]
Hi all,

The master branch is new a release candidate for the next release v0.29. I'd appreciate everyone's help testing it for those who know how. If there are no problems, I'll post a release in about 10 days.

This may be the last release before the Ubuntu 18.04 branch is released. Because of Nextcloud upgrade issues, this will be a required upgrade for everyone, meaning upgrading from Mail-in-a-Box v0.28 or earlier to the Ubuntu 18.04 will not be supported. Only upgrades from v0.29 (or later, if we have subsequent Ubuntu 16.04 releases) will be supported.

Thanks everyone.

**Comment by yodax** [comment]
I’m running master without issues. I haven’t tested a new install.

**Comment by just4t** [comment]
@JoshData As requested installed as fresh, over an up-to-date VULTR 14.05 image smoothly without issues ... I didn't test it in deep yet as that has been just an install test.
Reported as Mail-in-a-Box Version:  v0.28-10-g6eb9055
- Going now to update my production server after snapshot it and I'd report here if any issue arise.

**Comment by jvolkenant** [comment]
Upgrade wen't ok so far v0.26c -> v0.28-10-g6eb9055

**Comment by tdulcet** [comment]
#1435 fixes dozens of bugs in the bash scripts (found by [ShellCheck](https://www.shellcheck.net/)) and adds continuous integration...

See the install log [here](https://travis-ci.org/tdulcet/mailinabox).

**Comment by JoshData** [comment]
I'm not going to include #1435 in the next release because it needs to be reviewed etc.

**Comment by rfrush** [comment]
I pulled the master branch to /root/mailinabox and ran ./setup/start.sh.  

Old version: v0.28
New version:  Mail-in-a-Box Version:  v0.28-10-g6eb9055

The upgrade completed without any errors or issues.   A basic status check suggests everything is working fine.

**Comment by rpatrick1** [comment]
Tried a new build with this - all worked without any problems at all.

**Comment by KeiroD** [comment]
Hi,

Only error I get is this:

```
Log:
Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags. 
```

I provisioned TLS cert, though via the admin screen. Everything is updated. At least, it seems so, since it's running v28.

**Comment by DeviantEng** [comment]
Interestingly, I started getting the same issues as @KeiroD.  I had to bounce my VPS to get to the admin page, and I can't get LE to update a cert.  Getting that same error message:

```
Log:
Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.
```

Thoughts?

**Comment by jvolkenant** [comment]
@DonaldKBrown, v0.29 (and current master branch) only supports 14.04.  The branch ubuntu_master is the testing branch for 18.04.

**Comment by JoshData** [comment]
No. This is just a routine update. Only Ubuntu 14.04 is supported. Work on Ubuntu 18.04 is ongoing.

**Comment by JoshData** [comment]
Ooops sorry I didn't see @jvolkenant already replied.
