### ISSUE TITLE
secondary nameserver with multiple addresses breaks secondary check and status screen

### ISSUE THREAD

**Issue by steadfasterX** [mail-in-a-box/mailinabox#1485]
MIAB v0.28 (yea i have to update - but thats not the issue here ..)

Follow up to (the unsolved closed): #666 

The same issue catched me today while it took me a while to find the root cause:

I have configured the (free! and DNSSEC supporting!) secondary DNS service of www.1984.is and defined "ns2.1984.is" as my secondary NS in MIAB. 

The zones get transferred correctly (after setting the correct xfr ..) but the status screen of MIAB broke after I added all domains at 1984.is. 
It breaks just with a "Something went wrong, sorry" which is defined in the [default_error (click)](https://github.com/mail-in-a-box/mailinabox/blob/master/management/templates/index.html#L325) function (yea the **_default_error_** one - not the other).
So I moved on and started the status_check.py from the cmdline and it states on all "ns2.1984.is" secondary queries a [[timeout] (click)](https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L688). _dig_ and _nslookup_ on "ns2.1984.is" answered both very quickly though.

I adjusted the timeout but that was not the reason so I played a bit with the code and printed the content of the ["[at]" (click)](https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L675) list which prints the 2 (two!) IP's of "ns2.1984.is" separated by a ";" .
So I dived deeper and found that when I hard-code one of these IP's to that list (I replaced **[at]** with **["93.95.226.52"]**).. it just works without an issue. Status Screen displays fine again and ofc no timeouts or error messages anymore.

So I guess multiple A records of a secondary NS server is causing that issue.

**Comment by just4d** [comment]
> So I guess multiple A records of a secondary NS server is causing that issue.

- As per your words you did it wrong as you don't need to create/ add A records for that... 

The place where you need to add the additional (sub)domains given by the DNS slave service providers is at the **Using a secondary nameserver** section inside **hostname** field. As an example, mine are:

`ns2.1984hosting.com ns6.gandi.net puck.nether.net xfr:93.95.224.6 xfr:204.42.254.5`

- Where the first is one from **1984.is**, the second one is the one given by domain registar provider, the third the one by **puck.nether,net** and finally the two XFR from **[1984.is](https://www.1984.is/product/freedns/)** and **[puck.nether](https://puck.nether.net/dns/login)**

Hope this helps.

**Comment by steadfasterX** [comment]
I haven't created any A records here. Just resolve ns2.1984.is by yourself and you will see you get 2 A records for that fqdn. That's set by them not me.

**Comment by just4d** [comment]
Sounds good. congrats!

**Comment by steadfasterX** [comment]
I'm lost. What sounds good? And why congrats?

**Comment by Snacho** [comment]
@JoshData with the approval of my PR #1633 this issue is fixed for me. Can it be marked as resolved or should we wait for @steadfasterX to confirm?

**Comment by steadfasterX** [comment]
> @JoshData with the approval of my PR #1633 this issue is fixed for me. Can it be marked as resolved or should we wait for @steadfasterX to confirm?

great! works as it should now! :)
