### ISSUE TITLE
Ubuntu Bionic Daemon Issues

### ISSUE THREAD

**Issue by EliterScripts** [mail-in-a-box/mailinabox#1489]
So when creating a server on Ubuntu 18.04 (ubuntu_bionic branch), the daemon didn't appear to magically be running. I've been doing a little reverse engineering of the 14.04 version to see how to get the 18.04 version working, and there seems to be no files that match this (* are wildcards): /etc/rc*.d/*mail*.

When I manually started the daemon, I got this:
```
root@t1:~# python mailinabox/management/daemon.py
Traceback (most recent call last):
  File "mailinabox/management/daemon.py", line 6, in <module>
    from flask import Flask, request, render_template, abort, Response, send_from_directory, make_response
ImportError: No module named flask
```
Did a quick `apt-get install python-flask`, and now there is a different error in the code. I'll keep you guys updated.

**Comment by JoshData** [comment]
The daemon is now started by

https://github.com/mail-in-a-box/mailinabox/blob/ubuntu_bionic/conf/mailinabox.service

which launches a script created at

https://github.com/mail-in-a-box/mailinabox/blob/ubuntu_bionic/setup/management.sh#L88

**Comment by EliterScripts** [comment]
Okay, so I looked at /usr/local/lib/mailinabox/start to find that it just executes a Python script using:
`exec python /root/mailinabox/management/daemon.py`
So when I tried (after installing Flask):
`python /root/mailinabox/management/daemon.py`
it gave me this error:

```
root@t1:~# python /root/mailinabox/management/daemon.py
Traceback (most recent call last):
  File "/root/mailinabox/management/daemon.py", line 8, in <module>
    import auth, utils, multiprocessing.pool
  File "/root/mailinabox/management/auth.py", line 6, in <module>
    from mailconfig import get_mail_password, get_mail_user_privileges
  File "/root/mailinabox/management/mailconfig.py", line 266
    + [get_domain(address, as_unicode=False) for address, *_ in get_mail_aliases(env) if filter_aliases(address) ]
                                                          ^
SyntaxError: invalid syntax
root@t1:~# 
```
Now that I check the admin panel, it is now running (NOTE: I had to manually force nginx local.conf to work). So I don't know if this somehow uses Python3 and I should have used the python3 command, or if this works or doesn't.

**Comment by EliterScripts** [comment]
I'm trying to figure out where to properly insert to have MIAB install the apt package python-flask, so then I can do a PR.

**Comment by EliterScripts** [comment]
It appears `mailinabox/setup/management.sh` was never ran.

**Comment by EliterScripts** [comment]
It looks like I needed to look at both commits, now everything works on Ubuntu bionic.
