### ISSUE TITLE
Any docker container for mailinabox?

### ISSUE THREAD

**Issue by hiqbn** [mail-in-a-box/mailinabox#1496]
It's still needing to use ubuntu 14.04 (which is kind of obsolete on aws lightsail)

Possible to create a mailinabox docker container?

**Comment by just4d** [comment]
About **Ubuntu 18.04 LTS** alternaive option  (officially, still in development) you may wish to read this post from here: https://discourse.mailinabox.email/t/ubuntu-migration-plan/4145/16

**Comment by hiqbn** [comment]
what a disappointment and a waste without docker container

**Comment by whalehub** [comment]
@hiqbn If it's a modern mail server stack in Docker that you're looking for, you should check out [mailcow](https://github.com/mailcow/mailcow-dockerized).

**Comment by zatricky** [comment]
I agree, Docker would be nice. To call a project a "waste" because it doesn't meet your requirements is a whole other level. o.O

**Comment by tropyx** [comment]
Yeah, bit harsh.  You could always put the effort in and make the container for the community yourself.
