### ISSUE TITLE
Configure secondary DNS

### ISSUE THREAD

**Issue by hjjg** [mail-in-a-box/mailinabox#151]
Hi,

for .de-domains, you cannot use the how to you provided. If you set both ns1.box.example.com and ns2.box.example.com to the same IP address, DENIC will answer the request with:

ERROR: 107 Insufficient diversity of nameserver's IP addresses (# expected, # found) (2, 1)

Regards,

hjjg

**Comment by ponychicken** [comment]
But it seems 
````
provide-xfr: 0.0.0.0/0 NOKEY
`````
is not added yet? At least I had to manually edit /etc/bind/named.conf.options to make buddydns work

**Comment by JoshData** [comment]
No, but see #476. Please open a new issue if you really need to allow zone transfers from unknown IP addresses.
