### ISSUE TITLE
missing package 

### ISSUE THREAD

**Issue by karlo1941** [mail-in-a-box/mailinabox#1518]
i know, that arm is not supported but however ....
if you try install on ARM cpu (aarch64), then missing package **libffi-dev**

and this should be revised with manual file permission correction(:
/usr/local/lib/mailinabox/env/bin/pip install --upgrade rtyaml email_validator>=1.0.0 exclusiveprocess flask dnspython python-dateutil idna>=2.0.0 cryptography==2.2.2 boto psutil

**Comment by frank-dspeed** [comment]
@karlo1941 i am frank from https://www.canonical.com/ i just talked to some maintainer from this repo and can tell you they simply don't care you can close this :dagger: https://github.com/mail-in-a-box/mailinabox/issues/1519

**Comment by JoshData** [comment]
I blocked Frank. His comment does not reflect our goals.

That said, since we aren't currently supporting ARM I'm not sure there's anything for us to do for this issue.
