### ISSUE TITLE
Sorry just wanted to install and found out your missing packages

### ISSUE THREAD

**Issue by frank-dspeed** [mail-in-a-box/mailinabox#1519]
```
apt install curl sudo lsb-release locales net-tools iproute2
locale-gen en_US.UTF-8 
```
you should some how add that i could not find the right .sh file in your messy distro sorry but this packages are needed

**Comment by alento-group** [comment]
Most VPS providers have this already installed within their Ubuntu image.  It is not possible for MiaB to be written to cover inadequacies of some VPS providers when there are literally 100's to choose from.  When I encounter the issue I simply add the locale files as needed.  I'd suggest the same to you.

**Comment by frank-dspeed** [comment]
@alento-group ehm ok i will forward that to the ubuntu core team that you think our distro is inadequat i will also blog about that. i keep you updated lol i wish i could revert your ubuntu licence

**Comment by JoshData** [comment]
I blocked Frank because of another comment he left in this repo that was antagonizing.

For future reference, we _can_ and perhaps should add any apt-install commands for packages we assume are installed but might not be. That's an easy fix. There's no reason not to do it.
