### ISSUE TITLE
NSD not running on v0.41 

### ISSUE THREAD

**Issue by alento-group** [mail-in-a-box/mailinabox#1527]
People are reporting that NSD is not running .... it looks like the port is already in use by BIND.  Isn't BIND supposed to only listen on localhost?  Something is not right here.

https://discourse.mailinabox.email/t/problems-with-nsd4-on-a-fresh-server/4686

**Comment by 0xFelix** [comment]
According to this output BIND is exactly doing what it is supposed to. It is listening on port 53 on localhost (127.0.0.1) but not on the public ip address of the host. I'd suggest to rather read nsd's logfile before jumping to false conclusions.

**Comment by virse** [comment]
Hey 0xFelix,
the logs gives me:

```
[2019-03-02 17:02:12.756] nsd[13631]: error: can't bind tcp socket: Cannot assign requested address
[2019-03-02 17:02:12.756] nsd[13631]: error: cannot open control interface ::1 8952
[2019-03-02 17:02:12.756] nsd[13631]: error: could not open remote control port
[2019-03-02 17:02:12.756] nsd[13631]: error: could not perform remote control setup
[2019-03-02 17:02:12.973] nsd[13637]: notice: nsd starting (NSD 4.1.17)
[2019-03-02 17:02:12.977] nsd[13637]: error: can't bind tcp socket: Cannot assign requested address
[2019-03-02 17:02:12.977] nsd[13637]: error: cannot open control interface ::1 8952
[2019-03-02 17:02:12.977] nsd[13637]: error: could not open remote control port
[2019-03-02 17:02:12.977] nsd[13637]: error: could not perform remote control setup
```

Thx for helping

Best reards

**Comment by alento-group** [comment]
I'd suggest answering a question without the attack!  There was no false conclusion - there was a question of whether or not that was the proper behaviour.
I have posted on the discussion board asking the users in question for output of the nsd.log file.
Logs have already been posted in the discussion board thread.

**Comment by 0xFelix** [comment]
Sorry, did not mean to be rude. Yes it is proper behaviour for bind to use port 53 on localhost.

@virse Did you disable IPv6 by chance?

**Comment by alento-group** [comment]
@0xFelix No problem, thanks!  I somehow imagined that BIND was listening on the external IP - not sure where I saw that, but it is not in the posts now.  I realized that BIND should be listening on localhost but not on the external IP which is what prompted the question, which you have now clarified, thanks again!

**Comment by virse** [comment]
0xFelix:

No IPv6 is running:

```
# lsof -c nginx -a -i6
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx   19483 www-data   12u  IPv6 106316      0t0  TCP *:http (LISTEN)
nginx   19483 www-data   14u  IPv6 106318      0t0  TCP *:https (LISTEN)
nginx   19484 www-data   12u  IPv6 106316      0t0  TCP *:http (LISTEN)
nginx   19484 www-data   14u  IPv6 106318      0t0  TCP *:https (LISTEN)
nginx   29753     root   12u  IPv6 106316      0t0  TCP *:http (LISTEN)
nginx   29753     root   14u  IPv6 106318      0t0  TCP *:https (LISTEN)
```

Best regards

**Comment by virse** [comment]
Interesting with netstat there is no nsd with ipv6:

    netstat -tlnp
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 127.0.0.1:10023         0.0.0.0:*               LISTEN      15680/postgrey --pi 
    tcp        0      0 0.0.0.0:4200            0.0.0.0:*               LISTEN      24461/shellinaboxd  
    tcp        0      0 127.0.0.1:10025         0.0.0.0:*               LISTEN      12579/perl          
    tcp        0      0 127.0.0.1:10026         0.0.0.0:*               LISTEN      23957/dovecot       
    tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      24146/master        
    tcp        0      0 127.0.0.1:10222         0.0.0.0:*               LISTEN      8175/python         
    tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      19483/nginx: worker 
    tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      453/perl            
    tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      12310/named         
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      448/sshd            
    tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      24146/master        
    tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      12310/named         
    tcp        0      0 127.0.0.1:8891          0.0.0.0:*               LISTEN      13616/opendkim      
    tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      19483/nginx: worker 
    tcp        0      0 127.0.0.1:8893          0.0.0.0:*               LISTEN      21029/opendmarc     
    tcp        0      0 0.0.0.0:4190            0.0.0.0:*               LISTEN      23957/dovecot       
    tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      1/init              
    tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      23957/dovecot       
    tcp6       0      0 :::587                  :::*                    LISTEN      24146/master        
    tcp6       0      0 :::80                   :::*                    LISTEN      19483/nginx: worker 
    tcp6       0      0 :::4949                 :::*                    LISTEN      12729/perl          
    tcp6       0      0 :::22                   :::*                    LISTEN      448/sshd            
    tcp6       0      0 :::25                   :::*                    LISTEN      24146/master        
    tcp6       0      0 :::443                  :::*                    LISTEN      19483/nginx: worker 
    tcp6       0      0 :::4190                 :::*                    LISTEN      23957/dovecot       
    tcp6       0      0 :::993                  :::*                    LISTEN      1/init              
    tcp6       0      0 :::995                  :::*                    LISTEN      23957/dovecot 

best regards

**Comment by 0xFelix** [comment]
What does `ip ad` say on your system?

**Comment by virse** [comment]
ip ad says:

```
ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:3e:2c:d6 brd ff:ff:ff:ff:ff:ff
    inet 167.86.81.230/24 brd 167.86.81.255 scope global ens18
       valid_lft forever preferred_lft forever
```

**Comment by 0xFelix** [comment]
IPv6 seems to be globally disabled on your system? Your loopback interface has no v6 address (::1) but nsd requires it in the configuration deployed by mailinabox.

**Comment by alento-group** [comment]
I am a bit confused ... I have many MiaB installs running without IPv6.  Are you saying that it is supposed to be a requirement?  Or is it now a requirement that MiaB is running on Ubuntu 18.04?

**Comment by 0xFelix** [comment]
Even though you have no external IPv6 connectivity the system may still have IPv6 enabled for the loopback interface (::1) and link-local adresses (fe80::) on other interfaces. Therefore yes, IPv6 is a requirement for mailinabox. See this old issue https://github.com/mail-in-a-box/mailinabox/issues/296

**Comment by virse** [comment]
thank you 0xFelix!

```
sysctl -w net.ipv6.conf.all.disable_ipv6=0
and
sysctl -w net.ipv6.conf.default.disable_ipv6=0
```

did the trick. my provider disabled ipv6 in his installations on Ubuntu 18.04.

Best regards

**Comment by JJJ** [comment]
Thank you @virse for posting how you got NSD running again 🙌

I had disabled IPv6 on my Mail-in-a-Box (via entries opposite yours in `/etc/sysctl.conf`)  which meant they kept being re-disabled when I would reboot, which causes NSD not to start on boot 😅

(This, obviously, caused all of my domains to disappear off the public web for a bit, as none of the DNS records were available until I got this resolved)

Moral: MIAB requires NSD which requires IPv6 to not be explicitly disabled (and temporarily enabling IPv6 manually does not accomplish very much for very long).
