### ISSUE TITLE
Custom DNS API - GET; Filter not working correctly

### ISSUE THREAD

**Issue by rverst** [mail-in-a-box/mailinabox#1532]
If you use the GET method to see the DNS records for a domain, setting the `qname` to filter a specific domain and omitting the `rtype`, the result lists only the A-records for that domain.

To reproduce that issue create some DNS records, e.g.:

| Domain Name   | Record Type | Value   |
| ------------------ |--------------|---------|
| test.example.org| A                 |  1.1.1.1  |
| test.example.org| A                 |  1.0.0.1  |
| test.example.org| AAAA	  |   fe80::1 |
| test.example.org| TXT              |  test 1   |
| test.example.org| TXT              |  test 2   |

Now if you call: `curl -X GET --user {email}:{password} https://box.example.org/admin/dns/custom/test.example.org` you will get this:
```json
[{
        "qname": "test.example.org",
        "rtype": "A",
        "value": "1.1.1.1"
    },
    {
        "qname": "test.example.org",
        "rtype": "A",
        "value": "1.0.0.1"
    }
]
```

I would expect something like this:
```json
[{
        "qname": "test.example.org",
        "rtype": "A",
        "value": "1.1.1.1"
    },
    {
        "qname": "test.example.org",
        "rtype": "A",
        "value": "1.0.0.1"
    },
    {
        "qname": "test.example.org",
        "rtype": "AAAA",
        "value": "fe80::1"
    },
    {
        "qname": "test.example.org",
        "rtype": "TXT",
        "value": "test 1"
    },
    {
        "qname": "test.example.org",
        "rtype": "TXT",
        "value": "test 2"
    }
]
```

If you GET all custom records from your box, it works like expected.

**Comment by jvolkenant** [comment]
This looks to be expected behavior, the default is to return A record.  I imagine it's purpose is to check for a record that would ultimately be set via PUT/POST

https://github.com/mail-in-a-box/mailinabox/blob/ccd153065b74debf87a1dd63747d96d00d6931bd/management/daemon.py#L272

**Comment by rverst** [comment]
I agree with that for `dns_set_record`. If you PUT/POST without a type, A is the default.
But i don't think, that's the intended behavior for GET. From the _Custom DNS_ page:
> GET - Returns matching custom DNS records as a JSON array of objects. Each object has the keys qname, rtype, and value. The **optional** qname and rtype parameters in the request URL **filter** the records returned in the response. 

Right now there is no possibility, to fetch all records for a domain, than:
1.  Try every record type for the domain
2.  Get all custom records and filter the desired domain afterwards.

**Comment by jvolkenant** [comment]
The text in that paragraph should be updated then to clearify that if qname is specified, rtype=A is implied without setting rtype.

To get what your after, at this time you would need to filter from the complete list of entries

```
curl -X GET --user {email}:{password} https://box.example.org/admin/dns/custom/ | jq '.[] | select(.qname=="test.example.com")'
```

**Comment by rverst** [comment]
Yes, like I said. "Get all custom records and filter the desired domain afterwards."
It is just not my understanding of a RESTful API. But I can handle that. No offence!

**Comment by jvolkenant** [comment]
Yea, to be honest, I'm not sure what the typical RESTful API way to return the data is.  If typically one would have the server return filtered results, or if the client would do the filtering.

**Comment by rverst** [comment]
Well, at the end I think that's a design question and there is no right or wrong ;-)
