### ISSUE TITLE
SMTP certificate STARTTLS denied

### ISSUE THREAD

**Issue by Omroth** [mail-in-a-box/mailinabox#1535]
Since yesterday I can no longer send email via smtp. My details are correct.  The error I receive is: Sending of the message failed.
An error occurred while sending mail: Unable to establish a secure link with Outgoing server (SMTP) box.mode7games.com using STARTTLS since it doesn't advertise that feature. Switch off STARTTLS for that server or contact your service provider.

This is happening on two devices only from yesterday.

Thanks,
Ian

**Comment by rfrush** [comment]
It is my experience that services don't change behavior without some sort of change on the server and/or client side.   Can you think of anything that changed?  Have you verified that DNS resolves to the expected address?  To be of any help, we're going to need more data from you to work from!

--
Ray

**Comment by Omroth** [comment]
Thanks rfrush.  Nothing has changed that I can think of, and receiving works fine... if you can point me towards any commands that would give you more data I will try.

**Comment by Omroth** [comment]
----------SMTP----------
220 box.mode7games.com ESMTP Service ready
EHLO ian-Sabre-17WV8
250-Requested mail action okay, completed
250-SIZE 20000000
250-ETRN
250-8BITMIME
250 OK
QUIT

SMTP Last Response Code: 250

SMTP Last Response: Requested mail action okay, completed
SIZE 20000000
ETRN
8BITMIME
OK


mailsmtp Last Error Code: MAILSMTP_ERROR_STARTTLS_NOT_SUPPORTED

mailsmtp Last Error Location: 3

mailsmtp Last Auth Type: 0

**Comment by rfrush** [comment]
What happens when you try to telnet to your SMTP port?  I get this:
```
# telnet box.mydomain.net 25
Trying IPADDRESS...
Connected to box.mydomain.net.
Escape character is '^]'.
220 box.mydomain.net ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)

ehlo some.hostname.net

250-box.mydomain.net
250-PIPELINING
250-SIZE 134217728
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```

**Comment by Omroth** [comment]
telnet box.mode7games.com 587
Trying <ip address>...
Connected to box.mode7games.com.
Escape character is '^]'.
220 box.mode7games.com ESMTP Service ready

**Comment by rfrush** [comment]
Need to see the output of 'ehlo' command....

**Comment by alento-group** [comment]
compaq@HP-Compaq-8000:~$ telnet box.mode7games.com 587
Trying 46.43.2.57...
Connected to box.mode7games.com.
Escape character is '^]'.
220 box.mode7games.com ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
ehlo box.mode7games.com
250-box.mode7games.com
250-PIPELINING
250-SIZE 134217728
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

**Comment by rfrush** [comment]
So, what was different about the first test and this most recent one?

**Comment by Omroth** [comment]
It's a firewall issue at my current location, apologies guys.

**Comment by alento-group** [comment]
@Omroth Is this resolved then?  Please close if it is. :)

**Comment by alento-group** [comment]
@Omroth Sorry to reopen this but a colleague is experiencing the same issue.  Can you please be more specific concerning what the firewall issue was?  Thank you!

**Comment by Omroth** [comment]
Hi. Unfortunately I never found out what the actual problem was, I just stopped trying to connect via that public network.
