### ISSUE TITLE
Warning: reject_authenticated_sender_login_mismatch ignored: no SASL support

### ISSUE THREAD

**Issue by insideTheFlux** [mail-in-a-box/mailinabox#1536]
This appears in miab's mail.log when I send an email to it from an outside source.

_Mar 13 18:39:34 box postfix/smtpd[12153]: warning: restriction `reject_authenticated_sender_login_mismatch' ignored: no SASL support_

But I've noticed you have this here: https://github.com/mail-in-a-box/mailinabox/blob/dd7a2aa8a6702de0cbe0e7f766bd05d03dff9733/setup/mail-postfix.sh#L200
_reject_authenticated_sender_login_mismatch_

The line above requires that sasl be enabled, this is from main.cf
_smtpd_sasl_auth_enable=no_

Setting sasl to yes makes the warning go away.
I know it is just a warning, email gets delivered nonetheless. 

-Dying_Star

**Comment by lorrin** [comment]
I've been seeing this as well since upgrading (rebuilding) on 18.04 / 0.41.

**Comment by lorrin** [comment]
As discussed in #1463, however, `smtpd_sasl_auth_enable=no` is intentional:
```
# We *disable* it here
# And have Postfix use that service.
# so that authentication is not permitted on port 25 (which
# Starting with Ubuntu Bionic, smtpd_sasl_auth_enable=yes is required
# does not run DKIM on relayed mail, so outbound mail isn't
# for certain main.cf options to function.
# correct, see #830)
```
