### ISSUE TITLE
Can't login after first setup

### ISSUE THREAD

**Issue by binarykitchen** [mail-in-a-box/mailinabox#1541]
After running `mailinabox` I want to log into admin panel but all my attempts failed. Not sure what email address to enter.

Would be good to display it at end of setup here

```
Please log in to the control panel for further instructions at:

https://3.104.18.129/admin

--> use email address blahblah@yousetup.com
```

And for now, how can I find it out with some commands?

**Comment by jvolkenant** [comment]
https://discourse.mailinabox.email/t/reset-admin-password/726

**Comment by binarykitchen** [comment]
ah, this is gold. should be documented better. thanks!

**Comment by jl2035** [comment]
Doesn't work for me. Also tried creating a new user, but no success logging in.
