### ISSUE TITLE
Replace domain for user email account

### ISSUE THREAD

**Issue by andyjeffries** [mail-in-a-box/mailinabox#1542]
Hi, is there any easy way of replacing the domain used for a user account?

We're changing company names, so want to keep all email accounts the same in terms of password, mailbox contents - but change the username used to login and receive email to.

Thanks.

**Comment by doofpot** [comment]
I didn't test it, but if you want to change your company name, I think - without recreating the mailboxes - is:
- change in the user.sql file the domain name and path with an sql - editor
- rename the folder of the mailbox from "company-a.com" to "company-b.com"

**Comment by andyjeffries** [comment]
This worked perfectly, thank you! I just re-provisioned the TLS certificate from the admin web UI and it's all great.

**Comment by doofpot** [comment]
And you can make a forward from your old domain by adding a domain mapping to the new domain.
Mail will still work, until the old domain is removed

**Comment by andyjeffries** [comment]
Yep, did that too using the handy mailinabox API ;-)

**Comment by andyjeffries** [comment]
Oh wait, I used aliases. Didn't know about domain mapping!?

**Comment by doofpot** [comment]
You can create aliases but you can also say (from the email aliases menu: @domain-a > @domain-b

**Comment by andyjeffries** [comment]
THAT'S AWESOME!

**Comment by doofpot** [comment]
By the way, you can also the website, but that one is not officially supported;)

When you host a website on MIAB, it's in 'default' or in the domain names directory
so, you have your old "company-old.com", you can add a company-old.com.conf file (with contains regular NGINX config directives and you can also redirect your site to a new location.

`
rewrite ^/$ https://company-new.com permanent;
rewrite ^/(.*)$ https://company-new.com/$1 permanent;
`
