### ISSUE TITLE
utils.py Never Closes Files

### ISSUE THREAD

**Issue by EliterScripts** [mail-in-a-box/mailinabox#1548]
I was reading some of the code in management/utils.py, and noticed that there is no code that closes the files that get opened.

Example:
```
def write_settings(config, env):
    import rtyaml
    fn = os.path.join(env['STORAGE_ROOT'], 'settings.yaml')
    with open(fn, "w") as f:
        f.write(rtyaml.dump(config))
```

I would think to write:
```
def write_settings(config, env):
    import rtyaml
    fn = os.path.join(env['STORAGE_ROOT'], 'settings.yaml')
    with open(fn, "w") as f:
        f.write(rtyaml.dump(config))
        f.close()
```

**Comment by JoshData** [comment]
It is not necessary to call close on a file opened with a with-block. The with-block calls close.

**Comment by zatricky** [comment]
What Josh said. See [PEP 343](https://www.python.org/dev/peps/pep-0343/)

Essentially:
```
with open(fn, "w") as f:
  pass
```
is the same as:
```
f = open(fn, "w")
f.__enter__()
try:
    pass
finally:
    f.__exit__()
```

The __enter__() might initialise some things, while the __exit__() de-initialises it. In this case, it closes the file so you don't have to. The difference is that it's easier to read, write, and debug.

**Comment by EliterScripts** [comment]
I think this issue should be closed, right?
