### ISSUE TITLE
Possible to use with SMTP relay?

### ISSUE THREAD

**Issue by crislin2046** [mail-in-a-box/mailinabox#1582]
Just investigating SMTP relay solutions for cases where I cannot open outbound 25. Do you think it would be possible to get MIAB to work with an SMTP relay?

**Comment by jvolkenant** [comment]
Postfix can relay mail to another server, it's unsupported for use with mailinabox.

**Comment by crislin2046** [comment]
I'm afraid I don't get it. Sorry by unsupported do you mean it can't work?

**Comment by crislin2046** [comment]
@jvolkenant I'm sorry I'm still not sure what you mean by unsupported. Do you mean it will not work with mailinabox?

**Comment by alento-group** [comment]
@crislin2046 

'Unsupported' here means that IF you attempt to do this then you will not be offered any support if anything goes wrong ... iow, do so at your own risk.  MiaB runs daily cron jobs that will reverse any changes made to some of the config files ... so your changes may not stick and you will have to repeat them.  Additionally, when you upgrade MiaB many of the changes a user would make would be erased ... so in this sense, it is easier for the MiaB developers to not offer any support for someone who has made 'Unsupported modifications' to their system.   I hope that this clears the issue up.

Now, for the main question, YES it can be done.

**Comment by crislin2046** [comment]
Thanks @alento-group !
