### ISSUE TITLE
Any ETA on OATH?

### ISSUE THREAD

**Issue by johnyradio** [mail-in-a-box/mailinabox#1583]
https://github.com/mail-in-a-box/python-oath

**Comment by JoshData** [comment]
OAuth or OATH?

On May 19, 2019 2:30:03 AM EDT, johnyradio <notifications@github.com> wrote:
>https://github.com/mail-in-a-box/python-oath
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/1583

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by johnyradio** [comment]
sorry, OATH

**Comment by JoshData** [comment]
There aren't any particular plans to add any additional functionality to Mail-in-a-Box. See #10 for more on this.

**Comment by JoshData** [comment]
(I've also now deleted the repo above which was a fork whose changes were merged upstream at https://github.com/bdauvergne/python-oath/pull/17.)
