### ISSUE TITLE
Open relay on port 25

### ISSUE THREAD

**Issue by ckeschnat** [mail-in-a-box/mailinabox#1586]
I just configured mail in a box for a domain and it is an open relay (Port 25, Port 587 is fine). According to https://github.com/mail-in-a-box/mailinabox/blob/master/security.md this should not be the case.

I deviated from the default installation in two ways (because I have miab running inside a LXC-Container):

1. I use external DNS
2. I got the Let's Encrypt certificates on another machine and copied them over

Test port 25:
```
$  telnet 46.232.250.231 25
Trying 46.232.250.231...
Connected to 46.232.250.231.
Escape character is '^]'.
helo me
ma220 box.catsu.it ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
250 box.catsu.it
mail from: foo@bar.com
250 2.1.0 Ok
rcpt to: aehnee@gmail.com
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Subject: foo

bar

.
250 2.0.0 Ok: queued as 241941863E
QUIT
221 2.0.0 Bye
Connection closed by foreign host.
```

Test port 587
```
$  telnet 46.232.250.231 587
Trying 46.232.250.231...
Connected to 46.232.250.231.
Escape character is '^]'.
220 box.catsu.it ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
helo me
250 box.catsu.it
mail from: bla@blub.com
530 5.7.0 Must issue a STARTTLS command first
rcpt to: aehnee@gmail.com
530 5.7.0 Must issue a STARTTLS command first
DATA
530 5.7.0 Must issue a STARTTLS command first
Subject: meh
221 2.7.0 Error: I can break rules, too. Goodbye.
Connection closed by foreign host.
```

Postfix:
```
root@box:~# cat /etc/postfix/main.cf
# See /usr/share/postfix/main.cf.dist for a commented, more complete version


# Debian specific:  Specifying a file name will cause the first
# line of that file to be used as the name.  The Debian default
# is /etc/mailname.
#myorigin = /etc/mailname

#smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
smtpd_banner=$myhostname ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h
delay_warning_time=3h

readme_directory = no

# See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
# fresh installs.
compatibility_level = 2

# TLS parameters
#smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_cert_file=/home/user-data/ssl/ssl_certificate.pem
#smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_key_file=/home/user-data/ssl/ssl_private_key.pem
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
# information on enabling SSL in the smtp client.

#smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_relay_restrictions=permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination
myhostname = box.catsu.it
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
#mydestination = $myhostname, localdomain, localhost, localhost.localdomain, localhost
mydestination=localhost
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all
smtp_bind_address=10.25.45.175
smtp_bind_address6=
maximal_queue_lifetime=2d
bounce_queue_lifetime=1d
smtpd_tls_security_level=may
smtpd_tls_auth_only=yes
smtpd_tls_dh1024_param_file=/home/user-data/ssl/dh2048.pem
smtpd_tls_protocols=!SSLv2,!SSLv3
smtpd_tls_ciphers=medium
smtpd_tls_exclude_ciphers=aNULL,RC4
smtpd_tls_received_header=yes
smtp_tls_protocols=!SSLv2,!SSLv3
smtp_tls_mandatory_protocols=!SSLv2,!SSLv3
smtp_tls_ciphers=medium
smtp_tls_exclude_ciphers=aNULL,RC4
smtp_tls_security_level=dane
smtp_dns_support_level=dnssec
smtp_tls_CAfile=/etc/ssl/certs/ca-certificates.crt
smtp_tls_loglevel=2
virtual_transport=lmtp:[127.0.0.1]:10025
lmtp_destination_recipient_limit=1
smtpd_sender_restrictions=reject_non_fqdn_sender,reject_unknown_sender_domain,reject_authenticated_sender_login_mismatch,reject_rhsbl_sender dbl.spamhaus.org
smtpd_recipient_restrictions=permit_sasl_authenticated,permit_mynetworks,reject_rbl_client zen.spamhaus.org,reject_unlisted_recipient,check_policy_service inet:127.0.0.1:10023
message_size_limit=134217728
smtpd_sasl_type=dovecot
smtpd_sasl_path=private/auth
smtpd_sasl_auth_enable=no
smtpd_sender_login_maps=sqlite:/etc/postfix/sender-login-maps.cf
virtual_mailbox_domains=sqlite:/etc/postfix/virtual-mailbox-domains.cf
virtual_mailbox_maps=sqlite:/etc/postfix/virtual-mailbox-maps.cf
virtual_alias_maps=sqlite:/etc/postfix/virtual-alias-maps.cf
local_recipient_maps=$virtual_mailbox_maps
smtpd_milters=inet:127.0.0.1:8891 inet:127.0.0.1:8893
non_smtpd_milters=$smtpd_milters
milter_default_action=accept
```

**Comment by JoshData** [comment]
Would you also give https://mxtoolbox.com/diagnostic.aspx a try?

**Comment by ckeschnat** [comment]
Sure:
  | Test | Result |  
-- | -- | -- | --
  | SMTP Open Relay | May be an open relay. | More Info
  | SMTP Reverse DNS Mismatch | OK - 46.232.250.231 resolves to box.catsu.it |  
  | SMTP Valid Hostname | OK - Reverse DNS is a valid Hostname |  
  | SMTP Banner Check | OK - Reverse DNS matches SMTP Banner |  
  | SMTP TLS | OK - Supports TLS. |  
  | SMTP Connection Time | 0.794 seconds - Good on Connection time |  
  | SMTP Transaction Time | 3.159 seconds - Good on Transaction Time

**Comment by ckeschnat** [comment]
Also I opened port 25 because the setup guide said so. I have closed it now. I think the port is not necessary if I use somewhat modern clients?

**Comment by JoshData** [comment]
It's required to receive incoming mail from other systems but not to submit outbound mail which is on port 587 only.

But for the issue-

So, my box isn't an open relay. And Mail-in-a-Box users are checking against MXToolbox from time to time, so I don't think this is a general problem with Mail-in-a-Box. The postfix configuration you pasted seems fine. But of course I'm concerned if it's possible for something to go wrong and leave people with an open relay...

**Comment by ckeschnat** [comment]
I might have a hint and the problem might be with LXC after all.

When I connect to the server the following line is logged:

```
Jun  1 10:31:19 box postfix/smtpd[5105]: connect from localhost[127.0.0.1]
```

I'm not sure if this is normal behavior or if this comes from the lxc network bridge. If normally the real outgoing IP is normally logged I guess this ticket can be closed because of an unsupported configuration.

**Comment by ckeschnat** [comment]
I checked with a friend who has mail-in-a-box running on a real vps. The real IP is logged there so I think I was right.

**Comment by ckeschnat** [comment]
Just if someone reads this in the future:
Unsetting mynetworks solves the problem. But now I think I won't receive mails from mail in a box itself (cronjobs) as localhost is not trusted anymore and the setting needs to be changed after running the mailinabox script. Unsatisfying workaround but it works.
Maybe adding a second loopback interface might solve the first problem.

**Comment by ckeschnat** [comment]
Disregard the previous comment. Mail is not accepted anymore.

**Comment by ckeschnat** [comment]
Solved.
Stupid mistake by me - I forwarded to 127.0.01 inside the container. Changing this to the IP of the container solved the problem.

**Comment by JoshData** [comment]
Great I'm glad you figured it out!
