### ISSUE TITLE
Enhancement: update Postgrey whitelist definitions

### ISSUE THREAD

**Issue by pandruszkow** [mail-in-a-box/mailinabox#1587]
**Problem:**
The greylisting whitelist included with postgrey in Bionic is about 4 years behind the upstream version. Several modern transactional email services (email-as-a-service for those who don't want to run their own mass-mailing servers), such as Mailgun, Mailjet and Mandrill (aka MailChimp) are not on it, causing delays in receiving registration confirmation emails and password reset emails.

**Proposed solutions:**
1. Overwrite the package version of the whitelist with an [updated version of the definitions from upstream](http://postgrey.schweikert.ch/pub/postgrey_whitelist_clients) after Mail-in-a-Box is deployed.
2. Maintain a list of additional whitelisted servers as part of MiaB, then append that whitelist to the upstream whitelist, then replace the package version of the whitelist with the result.

Short-term, solution 1 would be a minimal amount of work that captures the most benefit. Longer-term, solution 2 would be even more effective since we could presumably add servers faster than the upstream, leading to a better user experience, without expending that much effort.

I think this might be worth doing, since these mass-mailing services are serving thousands of companies. Greylisting won't help much, since any malicious senders will be using the same servers as spammers anyway.

I'm willing to take a crack at this if this seems like a valuable contribution to the project.

**Comment by jvolkenant** [comment]
I would be in favor for solution 1,  They already have a framework to add those entries and it would add some workload to maintain MIAB if we also had to maintain this separate list.

**Comment by JoshData** [comment]
I agree. Let's do it.

**Comment by pandruszkow** [comment]
OK, I have created a fork and will work on this whenever I have a bit of time. I'll submit a PR back to the project when I'm done.

**Comment by yodax** [comment]
https://github.com/mail-in-a-box/mailinabox/pull/1611

**Comment by yodax** [comment]
@pandruszkow Thanks for raising the issue. I was running in to this so I created a quick patch.
