### ISSUE TITLE
upgrade v0.22 to v0.30 fails at php7.0-cli

### ISSUE THREAD

**Issue by brenzi** [mail-in-a-box/mailinabox#1591]
I was following these instructions, coming from v0.22:
https://discourse.mailinabox.email/t/mail-in-a-box-version-v0-40-and-moving-to-ubuntu-18-04/4289

So at first, I'd expect an upgrade to 0.30, the last ubuntu 14.04 version. However, the script tries to install php7.0 which isnt available 

```
Primary Hostname: xxxxxxxxxxxx
Public IP Address: xxxxxxxxxxxxx
Mail-in-a-Box Version:  v0.30

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...

FAILED: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install nginx php7.0-cli php7.0-fpm
-----------------------------------------
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-cli
E: Couldn't find any package by regex 'php7.0-cli'
E: Unable to locate package php7.0-fpm
E: Couldn't find any package by regex 'php7.0-fpm'
-----------------------------------------
```

**Comment by brenzi** [comment]
I was able to revert to 0.22 like this:

```
TAG=v0.22 curl -s https://mailinabox.email/setup.sh | sudo bash
```

Now the box works again, but no upgrade done

**Comment by brenzi** [comment]
I saw you're using a ppa starting from v0.24. Not sure if the issue lies with the ppa, or the utf-8 characters in the authors name:
```
apt-get install -y language-pack-en-base
LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
```
This at least gives me the right characters (which it didn't before):
```
gpg: keyring `/tmp/tmp45vr0ug5/secring.gpg' created
gpg: keyring `/tmp/tmp45vr0ug5/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp45vr0ug5/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
```

still, I can't install php7.0

**Comment by brenzi** [comment]
ah, that PPA doesn't support trusty anymore :-(

What's the risk if I backup v0.22 and then restore on 0.40 ubuntu 18.04?

**Comment by JoshData** [comment]
Ugh sorry the PPA ended support.

The steps through PHP7 are for upgrading ownCloud/Nextcloud data. So if you were using contacts, calendar, or some other part of ownCloud/Nextcloud, I'm not sure if an upgrade is possible without stepping through intermediate versions of ownCloud/Nextcloud.

If you're not using that functionality, then a backup/restore directly to 0.40 should be totally fine.

If you are using that functionality, I would give it a try so long as you can restore from a backup if things don't work.

**Comment by brenzi** [comment]
OK, I'm not using owncloud, only mail. So I should be fine. Thanks!

**Comment by brenzi** [comment]
```
FAILED: openssl genrsa -out /home/user-data/ssl/ssl_private_key.pem 2048
-----------------------------------------
genrsa: Can't open "/home/user-data/ssl/ssl_private_key.pem" for writing, No such file or directory
-----------------------------------------
```
I then deleted that broken symlink. This brought me to the next issue:
```
Installing Nginx (web server)...

FAILED: service nginx restart
-----------------------------------------
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
-----------------------------------------
```
and the logs say:
```
-- Unit nginx.service has begun starting up.
Jun 22 20:43:51 box.brenzi.ch nginx[18103]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/home/user-data/ssl/ssl_private_key.pem") failed (SSL: error:0B080074:x509 certificate rout
Jun 22 20:43:51 box.brenzi.ch nginx[18103]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jun 22 20:43:51 box.brenzi.ch systemd[1]: nginx.service: Control process exited, code=exited status=1
Jun 22 20:43:51 box.brenzi.ch systemd[1]: nginx.service: Failed with result 'exit-code'.
Jun 22 20:43:51 box.brenzi.ch systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```
so I guess I have to re-create certificates?

**Comment by brenzi** [comment]
this fixed it:
```
cp user-data.empty/ssl/box.brenzi.ch-selfsigned-20190622.pem user-data/ssl/
cp user-data.empty/ssl/ssl_private_key.pem user-data/ssl/
cd user-data/ssl
rm ssl_certificate.pem 
ln -s box.brenzi.ch-selfsigned-20190622.pem ssl_certificate.pem 
```

**Comment by brenzi** [comment]
and I had to delete the owncloud folders from `/home/user-data` ...so finally mailinabox script ran through

Now my browsers reject the admin page because of wrong certificate (no exceptions allowed). Guess I'll have to wait until the new cert works....

**Comment by ccnoyes** [comment]
I'm having the same problem going from v.24 to v.30:

Installing Nginx (web server)...

FAILED: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install nginx php7.0-cli php7.0-fpm
-----------------------------------------
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.0-cli
E: Couldn't find any package by regex 'php7.0-cli'
E: Unable to locate package php7.0-fpm
E: Couldn't find any package by regex 'php7.0-fpm'

Where did you get the setup.sh script? I'd like to go back to v.24.

**Comment by brenzi** [comment]
the setup.sh is the normal miab scrip which you might've called with curl. I just downloaded it, but you can replace it with the usual one-liner

**Comment by ccnoyes** [comment]
How can I download the setup.sh script? I'm not too familiar with github. I'd just like to be able to get back to v0.24 with a fully functioning server. After looking at /mailinabox/setup/bootstrap.sh, I think I can put the setup.sh file in /mailinabox/setup, I can run:

TAG=v0.24 /mailinabox/setup/setup.sh

and that will get me back to v0.24.  Right now, there are too many missing pieces (e.g. no python and nginx is not happy.
