### ISSUE TITLE
TLS/SSL for mail sending?

### ISSUE THREAD

**Issue by eddiejibson** [mail-in-a-box/mailinabox#1592]
Hi,

So it's obvious you can easily create/renew SSL certificates in the panel for the domain for web purposes, but what about for actually sending mail? And for multiple domains e.g customer's domains, you can't require from A records or whatever...

Can you point me in the right direction for this?

Cheers

Edward

**Comment by eddiejibson** [comment]
Gmail still marks a lot of email as spam despite it having "Standard encryption (TLS)". Or it cannot verify it was sent from the domain. I'm assuming encryption has something to do with it? All the records are existing and live...

**Comment by JoshData** [comment]
There's some information at https://github.com/mail-in-a-box/mailinabox/blob/master/security.md.
