### ISSUE TITLE
Nextcloud update failed in v42 update

### ISSUE THREAD

**Issue by chris13524** [mail-in-a-box/mailinabox#1598]
I tried to update my v41 MIAB instance to v42 using the standard update command. However, the update failed while attempting to upgrade Nextcloud.

```
...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2019-07-05-08:39:05...

Upgrading to Nextcloud version 15.0.8

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Reset log level
```

**Comment by weslimitless** [comment]
I'm having a similar issue.  Upgrading from v41 to v42 failed at upgrading Nextcloud.   Now whenever trying to run the setup command again I see:

curl https://mailinabox.email/setup.sh | sudo bash

Primary Hostname: XXXXX
Public IP Address: XXXX
Mail-in-a-Box Version:  v0.42

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...

FAILED: sudo -u www-data php /usr/local/lib/owncloud/console.php app:disable firstrunwizard
-----------------------------------------
Nextcloud is not installed - only a limited number of commands are available


  Command "app:disable" is not defined.

  Did you mean this?
      app:check-code


-----------------------------------------

**Comment by chris13524** [comment]
I ran the command again too, but rather than getting a different error like @whathome did, I got the same error I got the first time.

**Comment by JoshData** [comment]
Sorry folks. I've pulled v0.42 until we get this fixed. The Nextcloud install script is missing a step to do an upgrade through Nextcloud 14 for those upgrading from v0.40, which had Nextcloud 13. I'm pretty sure you both must have been on v0.40? Otherwise Nextcloud has messed something up maybe.

**Comment by whathome** [comment]
Okay cool.  Was definitely on v41 trying to go to v42 tho.

Nextcloud is now hosed (going to /cloud the UI is now prompting me to continue my setup - but if I do that it'll wipe the DB and start fresh).  

Any ideas what I can do at this point to roll the box back cleanly to v41?

**Comment by chris13524** [comment]
@JoshData I'm pretty sure I was running v0.41 (not v0.40). Reason being when I ran the update script it only pulled down tag v0.42:

```
From https://github.com/mail-in-a-box/mailinabox
 * [new tag]         v0.42      -> v0.42
```

Furthermore, I always keep all (4) my instances running the most up-to-date version and checking them all they are all running v0.41 as well.

**Comment by jvolkenant** [comment]
I did a fresh install of v0.40 -> v0.41 -> v0.42 (master) successfully. (I didn't duplicate @whathome's issue above, will do some more tests)

I confirmed that a fresh install of v0.40 -> v0.42 does result in @chris13524's issue above. We'll need to add the Nextcloud 13 to 14 intermediate step.
