### ISSUE TITLE
Upgrade to v0.42 no reporting correctly in Status Checks

### ISSUE THREAD

**Issue by britannic** [mail-in-a-box/mailinabox#1599]
Upgraded from v0.41 to v0.42. However, System Status Checks reports:

  | System
-- | --
✓ | All system services are running.
✓ | SSH disallows password-based login.
✓ | System software is up to date.
✖ | A new version of Mail-in-a-Box is available. You are running version v0.42. The latest version is v0.41. For upgrade instructions, see https://mailinabox.email.

**Comment by JoshData** [comment]
Well at least the upgrade worked for _someone_! After #1598 I pulled v0.42 until we figure out what went wrong. So you're now ahead of the current release.

**Comment by britannic** [comment]
Thanks for your quick response Josh. Should I downgrade?

**Comment by JoshData** [comment]
If you didn't have any error during upgrade, you should be fine.

**Comment by britannic** [comment]
Thanks Josh, I'll close this issue, since you already pulled version 0.42.
