### ISSUE TITLE
“Error Provisioning TLS Certificate”

### ISSUE THREAD

**Issue by rody64** [mail-in-a-box/mailinabox#1604]
See old post but still problem in v0.43:
[https://discourse.mailinabox.email/t/error-provisioning-tls-certificate-but-doesnt-seem-like-there-were-any-errors/3946](url)

Problem is that a perfectly "installed" (renewed) certificate is reported as an error in an email to the administrator. (Subject of email: [box.foo.bar] **Error** Provisioning TLS Certificate)

Possible solution is to remove the word Error from subject in email and only add it when an error was reported.
Adjust management/email_administrator.py
add after
_# If there's nothing coming in, just exit.
if content == "":
sys.exit(0)_
the following two lines:
_if (content.find('error:') != -1):.
    subject = "Error " + subject_

and remove from management/daily_tasks.sh the word Error:

_management/ssl_certificates.py -q | management/email_administrator.py "Error Provisioning TLS Certificate"_
to
_management/ssl_certificates.py -q | management/email_administrator.py "Provisioning TLS Certificate"_

Roddy

Edited issue on: 
20-09-2019. Changed solution so that informative emails about renewing certificate are send, only removed the word Error in subject when there is no error.
10-10-2019 Added missing ".

**Comment by netsec** [comment]
Same problem

**Comment by dan-jensen** [comment]
@rody64 thanks for mapping out a solution to this.  I used it for MR https://github.com/mail-in-a-box/mailinabox/pull/1653, which is intended to resolve this issue.
