### ISSUE TITLE
How to migrate all my emails from cpanel to mailinabox

### ISSUE THREAD

**Issue by blueray453** [mail-in-a-box/mailinabox#1608]
Recently I decided to change my hosting provider.

When I asked the prospective providers to transfer my emails, they said and I quote -

> We offer free data migration service if you are using cPanel control panel with your current hosting company (most companies use cPanel, such as GoDaddy/HostGator/etc) and are planning to purchase any of our cPanel packages (Linux Shared, VPS/Cloud with cPanel control panel).

I have CPanel in my current hosting, however I am feeling a little locked down as the prospective provider is saying that I must have CPanel. 

Now, I want to migrate all my CPanel email to mailinabox (installed in a VPS). How can I do that?

**Comment by alento-group** [comment]
You would need to create the user accounts manually, then you could use imapsync to transfer the mail.

IMHO this would be the path of least resistance as cPanel uses a completely different format for mailbox storage. So it is not possible to backup and restore the files as they would have to be converted first.

**Comment by blueray453** [comment]
I got my answer. Should I close this issue?

**Comment by alento-group** [comment]
> I got my answer. Should I close this issue?

Yes, please. :)
