### ISSUE TITLE
Public DNS (nsd4) is not running (port 53).

### ISSUE THREAD

**Issue by netsec** [mail-in-a-box/mailinabox#1613]
This issue is pervasive and none of my installations are working, and all have this same message.

**Comment by anoma** [comment]
Not a lot to go on but by any chance is the service provider the issue. In the past weird cases like this have often been due to a non standard base OS tweaked by the provider in some way that mailinabox didnt know to cater for.

**Comment by netsec** [comment]
Well, I haven't had this problem until I've done a fresh installation in 1804. After the installation is complete when I navigate to the admin page, Status. 

The top of the list showing potential system errors. 
NSD not running is one error listed. The red Reboot button is on the right, with the click to enable version checking. to give you some context of the window where this message appears.

**Comment by netsec** [comment]
Furthermore, when I checked for systemctl status, to see what services were running. NSD was not running, however, I did find BIND running, oddly enough.

**Comment by 0xFelix** [comment]
Is IPv6 disabled on your system? NSD somehow fails to cope with that.

**Comment by alento-group** [comment]
> This issue is pervasive and none of my installations are working, and all have this same message.

Who is your VPS provider?  Do they offer IPv6?  Is IPv6 in fact enabled or disabled?  Do you have an AAAA record for the IPv6 for the box?

**Comment by netsec** [comment]
> Is IPv6 disabled on your system? NSD somehow fails to cope with that.

I do have IPv6 disabled on my system..... you think that's the problem?

**Comment by alento-group** [comment]
There could be many potential problems.  I am not certain that it is specifically IPv6 in this case.  It would really help if we had more information to work with.  Please consider posting on the Discourse forum, or on Slack so I or someone can help you work through the possibilities.  GitHub is more for proven bugs.

**Comment by alento-group** [comment]
My first question outside of the ones that you haven't answered yet, will be did you have DNSSEC enabled with your registrar and did you turn it off before you reinstalled your box?

**Comment by netsec** [comment]
Oh, this is not a VPS. This is a server I hack rack-mounted in a datacenter. IPv6 is not offered. I do not have a AAAA record for the box, as NSD is supposed to be supplying the DNS records, including the AAAA record.

**Comment by netsec** [comment]
> There could be many potential problems. I am not certain that it is specifically IPv6 in this case. It would really help if we had more information to work with. Please consider posting on the Discourse forum, or on Slack so I or someone can help you work through the possibilities. GitHub is more for proven bugs.

This certainly is a bug.

**Comment by alento-group** [comment]
> Oh, this is not a VPS. This is a server I have rack-mounted in a datacenter. IPv6 is not offered. I do not have a AAAA record for the box, as NSD is supposed to be supplying the DNS records, including the AAAA record.

Ok.  IPv6 is not required, but does cause issues if it is available and ignored.  So we can rule anything IPv6 out until we get to LE.  Can you show the status page (or output of ./mailinabox/management/status_checks.py ... which again would make Discourse or Slack a better place to troubleshoot.  Also, what is the hostname of the MiaB server?

**Comment by netsec** [comment]
moving to Discourse.

**Comment by 0xFelix** [comment]
See https://github.com/mail-in-a-box/mailinabox/issues/1613
