### ISSUE TITLE
Home page still says last version is v0.41

### ISSUE THREAD

**Issue by fmonts** [mail-in-a-box/mailinabox#1619]
https://mailinabox.email/ still says the Current Version is: v0.41 / February 26 2019

Is the 0.42b safe to upgrade?

**Comment by alento-group** [comment]
As long as you are upgrading from 0.40 or 0.41, yes it should be.

**Comment by Dibbyo456** [comment]
> A new version of Mail-in-a-Box is available. You are running version v0.41. The latest version is v0.42b. For upgrade instructions, see https://mailinabox.email.

v0.42b is beta. I think it's better to wait for a stable release.

**Comment by alento-group** [comment]
> v0.42b is beta. I think it's better to wait for a stable release.

Actually 0.42b is a stable release ... the b in this case refers to the fact that it was a second release due to a bug in the original 0.42 release.

**Comment by Dibbyo456** [comment]
Oh, I see. Did not know that. Thank you. I just updated..

**Comment by JoshData** [comment]
Fixed, thanks.
