### ISSUE TITLE
fail2ban do not block managesieve login attempts

### ISSUE THREAD

**Issue by dmitrijszv** [mail-in-a-box/mailinabox#1622]
Hi,
MIAB use fail2ban filter conf/fail2ban/filter.d/dovecotimap.conf

this regex finds lines in log:
`failregex = ^%(__prefix_line)s(pop3|imap)-login: .....  `

and this regex is ok for pop3|imap logins:
`Aug 09 15:02:37 imap-login: Info: Disconnected: Inactivity (auth failed, 2 attempts in 135 secs)`

but, managesieve has its own prefix **managesieve**-login:
`Aug 09 15:34:05 managesieve-login: Info: Disconnected (auth failed, 2 attempts in 53 secs)`

if I change the regex adding `|managesieve`:
`failregex = ^%(__prefix_line)s(pop3|imap|managesieve)-login: .....  `
fail2ban starts to block managesieve failed login attempts.

**Comment by JoshData** [comment]
Good catch! Fix coming.
