### ISSUE TITLE
Postgrey whitelist recipients broken

### ISSUE THREAD

**Issue by sdudley** [mail-in-a-box/mailinabox#1659]
Hi all,

Running MIAB v0.43, I see that Postgrey is no longer respecting local recipient whitelisting. It looks like this could be related to commit 1d6793d1 (@yodax ) which seems to be targeted at regularly updating the whitelist **client** list (which is different from the whitelist **recipients** list).

I previously added some whitelisting recipients in `/etc/postgrey/whitelist_recipients.local` but these no longer seem to be used.

Upon further investigation, I see this:

    # ps ax |grep postgrey
    11703 ?        Ss     0:00 postgrey --pidfile=/var/run/postgrey/postgrey.pid 
    --daemonize --inet=127.0.0.1:10023 --delay=180
    --whitelist-recipients=/etc/postgrey/whitelist_clients

According to the postgrey man page, there are `--whitelist-recipients` and `--whitelist-clients` options which can provide overrides of the existing default files. The default locations for those files are already `/etc/postgrey/whitelist_{clients|recipients}`. In addition, manually specifying the whitelist_recipients file seems to prevent Postgrey from manually looking at the `/etc/postgrey/whitelist_recipients.local` file.

In addition, it looks like the defaults in `/etc/default/postgrey` are providing the `whitelist_clients` file to the `whitelist-recipients` option, so I think Postgrey will be using the `/etc/postgrey/whitelist_clients` file for both whitelist-clients and whitelist-recipients.

I think this commit meant to use the `--whitelist-clients` option instead of `--whitelist-recipients`?

Scott

**Comment by jvolkenant** [comment]
I would agree, "whitelist-recipients" should not be using the file "/etc/postgrey/whitelist_clients"

Manpage reports taht these files are read anyways, so the option shouldn't be needed.
```
   Whitelists
       Whitelists allow you to specify client addresses or recipient address, for which no greylisting should be done. Per default postgrey will read the following files:

        /etc/postgrey/whitelist_clients
        /etc/postgrey/whitelist_clients.local
        /etc/postgrey/whitelist_recipients
        /etc/postgrey/whitelist_recipients.local
```

If you remove `--whitelist-recipients=/etc/postgrey/whitelist_clients` from `/etc/default/postgrey` does it read your `/etc/postgrey/whitelist_recipients.local` after `service postgrey restart`  I believe there was another issue raised where someone's custom additions to `/etc/postgrey/whitelist_clients` was being overwritten.  We could document that *.local should be used for custom changes then.

**Comment by jvolkenant** [comment]
yea, checking `/etc/sbin/postgrey`
postgrey will either use the `--whitelist-clients=` or `--whitelist-recipients` a user provided or use the defaults.
```
            whitelist_clients_files    => $opt{'whitelist-clients'} ||
                [ "$CONFIG_DIR/whitelist_clients" ,
                  "$CONFIG_DIR/whitelist_clients.local" ],
            whitelist_recipients_files => $opt{'whitelist-recipients'} ||
                [ "$CONFIG_DIR/whitelist_recipients" ,
                  "$CONFIG_DIR/whitelist_recipients.local" ],
```

`--whitelist-recipients=...` should be removed from `/etc/defaults/postgrey`

**Comment by yodax** [comment]
I’ll try and pick this up soon. During the pr process I checked for some docs on this, but had a hard time getting everything clear.

**Comment by yodax** [comment]
I've created a PR: https://github.com/mail-in-a-box/mailinabox/pull/1675 Would you mind having a look?
