### ISSUE TITLE
"Unable to resolve host" during installation.

### ISSUE THREAD

**Issue by alento-group** [mail-in-a-box/mailinabox#1661]
> During installation I get this "unable to resolve host [box.xxxxx.org](https://slack-redir.net/link?url=http%3A%2F%2Fbox.xxxxx.org&v=3): Resource temporarily unavailable

I have been having people mention this to me on Slack and have noticed it myself during installation/reinstallation.  Sadly, some are seeing that error message and believing that there is actually an error when there is not.

Any ideas why this is happening?  I think I first noticed it about 2 releases ago, but I did not pay close enough attention to the timing. :(

**Comment by jvolkenant** [comment]
At what point during the install does it happen? Could we get a full console showing to see what script this error might be in?

**Comment by alento-group** [comment]
I will spin up a test install to see.

**Comment by alento-group** [comment]
> I will spin up a test install to see.

Hmm, an absolutely perfect no problem install. :(  Trying again!

**Comment by alento-group** [comment]
```
Installing Roundcube (webmail)...
sudo: unable to resolve host test.mailinabox.info
Installing Nextcloud (contacts/calendar)...
sudo: unable to resolve host test.mailinabox.info
Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
sudo: unable to resolve host test.mailinabox.info
```
Ok, I have managed to reproduce the issue and IMHO it is a non-issue.  My suspicion is that when DNS has not fully propogated this comes up during the install process.
My suggestion would be to note this scenario in the install guide.
