### ISSUE TITLE
Allow for custom scripts to be run during setup

### ISSUE THREAD

**Issue by victorlap** [mail-in-a-box/mailinabox#1668]
Right now it is not possible to extend the default scripts or overwrite them with your own, without the changes being reversed during the next upgrade.

It would be nice to include some sort of extension points in the setup scripts. For example, if I wanted to change the roundcube config, I can add a file `/extend/webmail.sh` which mailinabox can run during setup.

A change can look like this in any of the setup scripts, for example at the end of [setup/webmail.sh](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/webmail.sh).

```bash
if [ ! -f extend/webmail.sh ]; then
  source extend/webmail.sh
fi
```

Then the `extend/webmail.sh` can look something like this:

```bash
tools/editconf.py $RCM_CONFIG \
	"\$config['product_name'] = 'My custom roundcube name';"
```

If some people are interested in this, I am willing to take a shot at submitting a PR for this.

**Comment by JoshData** [comment]
Is there a reason you can't just run the script yourself after setup completes?

**Comment by victorlap** [comment]
That is a good question. I guess my main motivation for this change is the fact that you can update MIAB via the web gui, and that would then automatically call these scripts. Instead of having to ssh into the server afterwards.
