### ISSUE TITLE
Error line 155 - Nextcloud 17

### ISSUE THREAD

**Issue by bertusdebruin** [mail-in-a-box/mailinabox#1690]
After upgrading my test system (v0.43) with the latest master including Nextcloud 17 https://github.com/mail-in-a-box/mailinabox/pull/1676 @yodax 
The following error appears: 

> Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2019-12-02-09:31:46...
> setup/nextcloud.sh: line 155: InstallNextCloud: command not found

The same goes for upgrading the master to master.
Or freshly installing master branch to a server, restoring a backup and restarting the setup again.

**Comment by yodax** [comment]
I just tested with every change merged and it seems to be working for me.

When you run the installer do you do this on the mailinabox repo?

Would you mind running ```git diff upstream/master``` to see if anything has changed?

**Comment by jvolkenant** [comment]
I hadn't tested upgrading to 17.0.1 yet but worked ok.

upgrade to master: f53b18ebb9b1c4c9aba95b3a26bee2be85f8002f
Was at nextcloud 16.0.x, to 17.0.1
```
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2019-12-02-07:41:29...

Upgrading to Nextcloud version 17.0.1

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
...snip...
Done.
All tables already up to date!
Nextcloud is already latest version
```

master to master worked as well

**Comment by bertusdebruin** [comment]
@yodax Nothing changed.
Even Hashed the specific file nextcloud.sh to verify if there where problems related to downloading and writing the file on the disk.

Based on the [installation parameters written on this Git project](https://github.com/mail-in-a-box/mailinabox/blob/master/README.md). 
I performed the following:

```
git clone https://github.com/mail-in-a-box/mailinabox
cd mailinabox
git checkout v0.43
sudo setup/start.sh
git checkout master
sudo setup/start.sh
```
@jvolkenant As you where on 16.0*. What about upgrading from v0.43's Nextcloud 15.0.8 to 17.*?

**Comment by yodax** [comment]
Sorry I missed this use case. 

https://github.com/mail-in-a-box/mailinabox/blob/master/setup/nextcloud.sh#L155 Has a typo Cloud is capitalized. Would you mind trying to lowercase it and see if it works?

**Comment by yodax** [comment]
If that works, the same issue exists https://github.com/mail-in-a-box/mailinabox/blob/master/setup/nextcloud.sh#L151. Not sure why it would fail on a clean install though. I need to give that a test, but I wont have time until the weekend at the earliest.

**Comment by bertusdebruin** [comment]
@yodax Tested. Worked.

**Comment by jvolkenant** [comment]
> @jvolkenant As you where on 16.0*. What about upgrading from v0.43's Nextcloud 15.0.8 to 17.*?

It worked for me as I had 15.0.8 and tested 889118aeb65ded96df76d43e67a7bae8a81ac387.  And then tested 54b1ee9a3da88b30364a9223420d1ba81f4e97b0

If you are one version back, you only ever run
https://github.com/mail-in-a-box/mailinabox/blob/f53b18ebb9b1c4c9aba95b3a26bee2be85f8002f/setup/nextcloud.sh#L160

I installed master on a test vm a few days ago and it installed ok. (as it only runs line 160 above)  But yes "InstallNextcloud" needs to be slammed one way or the other.  master would fail if doing an upgrade from 15+ or 16+

```
root@m:~/mailinabox# grep -i InstallNextcloud setup/nextcloud.sh 
InstallNextcloud() {
                        InstallNextcloud 14.0.6 4e43a57340f04c2da306c8eea98e30040399ae5a
                        InstallNextCloud 15.0.8 4129d8d4021c435f2e86876225fb7f15adf764a3
                        InstallNextCloud 16.0.6 0bb3098455ec89f5af77a652aad553ad40a88819
        InstallNextcloud $nextcloud_ver $nextcloud_hash
```

**Comment by yodax** [comment]
Fixed by: https://github.com/mail-in-a-box/mailinabox/pull/1693
Thanks @jvolkenant !
