### ISSUE TITLE
no DNS propagation after 24 hours

### ISSUE THREAD

**Issue by g0rbe** [mail-in-a-box/mailinabox#1695]
Hi!

I setted up miab ~24 hours ago.
https://dnschecker.org/ shows nothing.
The glue DNS is ok.

I found interesting that localhost cant resolve my domain.

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43167
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: c142e21c592667aa0bcf0b6f5df13f650050e041b433d6d7 (good)
;; QUESTION SECTION:
;example.com.		IN	A

;; AUTHORITY SECTION:
example.com.	7200	IN	SOA	ns1.notmydomain.com ns2.motmydomain.com 2019121101 86400 10800 3600000 86400

;; Query time: 27 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Dec 11 21:11:33 EET 2019
;; MSG SIZE  rcvd: 137
```

I see a some repeating error in journald about `named`:
```
broken trust chain resolving 'anything.example.com/A/IN': [MYIP]#53
```
```
validating anything.example.com/A: no valid signature found
```

My setup is a fresh Ubuntu 18.
No more error found.

Thanks,
    g0rbe

**Comment by jvolkenant** [comment]
https://www.whatsmydns.net/#NS/example.com


I would recommend doublechecking your Nameserver (NS) and glue records.  They don't look to be working right.  They look to be pointing to (ns1.box.example.com, ns2.box.example.com) in some places and (ns.second-ns.com, ns1.your-server.de, ns3.second-ns.de) in others.

**Comment by g0rbe** [comment]
I tried `A`, `AAAA`, `MX` and `NS`.
Only NS is 100%.
Interesting... I should wait other 24 hours

**Comment by g0rbe** [comment]
I solved it!

Hetzner need two different name server and the TTL was too low in the zone file, changed from 1800 to 7200
