### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#17]
Add monitoring for:

* Free disk space
* Whether the IP has been blacklisted in common DNSRBLs & whether the domain is in URIBL.
* General system checks (like, is it actually functioning to receive mail?)
* Updated packages (`apt-get -qq update && apt-get -qq --simulate upgrade` or https://wiki.debian.org/UnattendedUpgrades)
* ...

**Comment by hnk** [comment]
I think monitoring could be implemented into the admin dashboard using [the python module psutil](https://github.com/giampaolo/psutil).

I'll play around with it and maybe hack together a little example page.

**Comment by JoshData** [comment]
Between the status checks and the new nightly change emails (4d22fb9b2a395cb1873f1dd98951efbf4eef48cf), I've finished what I had in mind with this issue. Happy to discuss further if anyone has other thoughts.
