### ISSUE TITLE
Disable webmail access for non-primary domains

### ISSUE THREAD

**Issue by bf** [mail-in-a-box/mailinabox#1709]
First of all, thanks for this great project. It helped me set up my own mailserver.

The webmail interface is very helpful, but I'd like to restrict it to the primary domain. I found that webmail is also accessible on the `autodiscover` and `autoconfig` subdomains, so I was looking for a way to disable this.

I've found the `nginx-alldomains.conf` file, in which the `/mail/` forward to roundcube is enabled. There, I removed the lines which activated webmail. 

As webmail is also enabled in `nginx-primaryonly.conf`, I want to ask why we can't just remove the webmail from the  `nginx-alldomains.conf` file. Has this been considered before? Thank you.

**Comment by JoshData** [comment]
I agree that it doesn't make sense to expose it on `autodiscover` and `autoconfig`. But other users have said they like having services exposed on other domains.

**Comment by bf** [comment]
Do you think we should give users a choice whether they want to enable it or not? 
I would be happy to implement a configuration option somewhere. 

For the time being, I have solved this by adding `deny from all;` to each vhost's nginx config file, e.g. to `/home/user-data/www/autodiscover.mydomainname.tld.conf`.

**Comment by JoshData** [comment]
> Do you think we should give users a choice whether they want to enable it or not?

No.
