### ISSUE TITLE
usage reports and system notifications go to spam

### ISSUE THREAD

**Issue by robjloranger** [mail-in-a-box/mailinabox#1714]
I've changed nothing as far as filters go and have not moved any to my spam folder manually. Any ideas?

**Comment by downtownallday** [comment]
Try examining the X-Spam headers of the message (open the message source and look at the headers). The X-Spam-Report header should give you a clue. Focus on lines with high numbers (scores).

**Comment by remyabel** [comment]
You will need to add your domain/IP to the whitelist. Something like this:

```
trusted_networks EXTERNAL_IP
trusted_networks 127.0.0.1/8

whitelist_from_rcvd *@box.remyabel.xyz box.remyabel.xyz
whitelist_from_rcvd *@remyabel.xyz remyabel.xyz
whitelist_from_rcvd *@box.remyabel.xyz [EXTERNAL_IP]
whitelist_from_rcvd *@box.remyabel.xyz [127.0.0.1/8]
whitelist_from_rcvd *@remyabel.xyz [EXTERNAL_IP]
whitelist_from_rcvd *@remyabel.xyz [127.0.0.1/8]
whitelist_to *@box.remyabel.xyz
whitelist_to *@remyabel.xyz
```

**Comment by robjloranger** [comment]
ah, thank you @remyabel :+1:

**Comment by robjloranger** [comment]
I will open again if somehow whitelisting doesn't work out

**Comment by cmasterdelphi** [comment]
That helped me too. Thanks.
Maybe this could be mentioned in some FAQ or already placed at greylist while the installation.
I've got one question: will this be deleted after the next upgrade of mailinabox? how is this greylist updated?
