### ISSUE TITLE
Tag 44 doesn't exist

### ISSUE THREAD

**Issue by robert2411** [mail-in-a-box/mailinabox#1722]
The script refers to TAG=v0.44 (as like the manual)

But the tag doesn't exist on GitHub 

Script error:
Updating Mail-in-a-Box to v0.44 . . .
fatal: Couldn't find remote ref refs/tags/v0.44
error: pathspec 'v0.44' did not match any file(s) known to git.
Update failed. Did you modify something in /root/mailinabox?
root@box:~# curl -s https://mailinabox.email/setup.sh

**Comment by methyphobia** [comment]
This affects new installations as well (understandably):

```
root@box:~# curl -s https://mailinabox.email/setup.sh | sudo bash
Downloading Mail-in-a-Box v0.44. . .

bash: line 68: cd: /root/mailinabox: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
bash: line 71: [: v0.44: unary operator expected
bash: line 82: setup/start.sh: No such file or directory
```
There's a 0.44 changelog as of today but no 0.44 release, yet.

**Comment by JoshData** [comment]
Sorry I forgot to push the tag! Will fix in a moment. Thanks!

On February 15, 2020 2:27:44 PM EST, methyphobia <notifications@github.com> wrote:
>This affects new installations as well (understandably):
>
>```
>root@box:~# curl -s https://mailinabox.email/setup.sh | sudo bash
>Downloading Mail-in-a-Box v0.44. . .
>
>bash: line 68: cd: /root/mailinabox: No such file or directory
>fatal: not a git repository (or any of the parent directories): .git
>bash: line 71: [: v0.44: unary operator expected
>bash: line 82: setup/start.sh: No such file or directory
>```
>There's a 0.44 changelog as of today but no 0.44 release, yet.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/1722#issuecomment-586633387

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
