### ISSUE TITLE
autoconfig.* subdomains now are not pointing at the correct certificate

### ISSUE THREAD

**Issue by zoof** [mail-in-a-box/mailinabox#1732]
If I go to autoiscover.tld or autoconfig.tld, I now get a privacy error.  Looking at the certificate info, it shows box.tld, tld and www.tld.  The problem is not that the certificate is missing as the "TLS (SSL) Certificates" shows that tld has a certificate but clearly not the same one as it has a different expiration date.

**Comment by zoof** [comment]
Either the system should generate a new certificate for tld that includes all relevant subdomains or the  nginx configuration needs to be fixed.

**Comment by jvolkenant** [comment]
Have you provisioned certificates for those subdomains yet? Go to https://box.domain.com/admin, System > TLS (SSL) Certificates, are there certificates to issue?

**Comment by zoof** [comment]
Yes, they all have certificates.  E.g., box.tld expires in 21 days but autoconfig.box.tld expires in 74 days.

But this is weird -- it is all now working as it was before I upgraded to 0.44.  I even tried different web browsers at home be here at work on a different computer all is fine.
