### ISSUE TITLE
Gmail missimg ptr record after a few months of working fine 

### ISSUE THREAD

**Issue by albertoxamin** [mail-in-a-box/mailinabox#1746]
Whenever an user sends an email to gmail this is the error, started happening today
```
    gmail-smtp-in.l.google.com[2a00:1450:4013:c07::1b] said: 550-5.7.25
    [MY_IPV6] The IP address sending this message does not
    550-5.7.25 have a PTR record setup. As a policy, Gmail does not accept
    messages 550-5.7.25 from IPs with missing PTR records. Please visit
    550-5.7.25  support.google.com/mail/answer/81126#authentication for
    more 550 5.7.25 information. s12si10692358edy.381 - gsmtp (in reply to end
    of DATA command)
```

**Comment by albertoxamin** [comment]
![image](https://user-images.githubusercontent.com/6067659/78015003-04e2ca00-7349-11ea-96dc-30ec592488cf.png)
Mail tester score

**Comment by MasterPCUK** [comment]
Hi

Have you checked if you actually have a PTR record? It's usually set by your server provider.

Please do check with https://mxtoolbox.com/SuperTool.aspx ,  select Reverse Lookup and input your IPv6.

**Comment by albertoxamin** [comment]
Ok I've checked, there is none.
So I contacted my provider (Scaleway) and they responded that they don't support ipv6 reverse DNS yet.

Is there a way to always send emails only from ipv4?

**Comment by MasterPCUK** [comment]
Perhaps you can disable ipv6 on Scaleway for your server?

Otherwise, you would have to edit configurations manually as it's not officially supported and my get overridden after updates.

**Comment by albertoxamin** [comment]
Ok I disabled ipv6 and it seems to work, thanks.
I'll enable it again once they start supporting reverse dns for ipv6.
