### ISSUE TITLE
Installs php7.4 but looking for php7.2

### ISSUE THREAD

**Issue by DeltaKiloz** [mail-in-a-box/mailinabox#1753]
I get the following error when the script installs the web.sh module:

_Installing Nginx (web server)...
Traceback (most recent call last):
File "tools/editconf.py", line 71, in <module>
    input_lines = list(open(filename))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/php/7.2/fpm/php.ini'_

The script installs the latest version of php which is 7.4, however the web.sh script has hard references to php7.2 which doesn't exist during the installation.

**Comment by JoshData** [comment]
Are you setting up Mail-in-a-Box on a normal Ubuntu 18.04 system?

**Comment by DeltaKiloz** [comment]
Yes, a digitalocean Ubuntu 18.04 server.

**Comment by DeltaKiloz** [comment]
I did a fresh spin up of another Digitalocean Ubuntu 18.04 server and this seems to have cleared our this error. However, I had this error when it was installing Nextcloud:

_Installing Nextcloud (contacts/calendar)...
FAILED: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install php php-fpm php-cli                                                                                                                         php-sqlite3 php-gd php-imap php-curl php-pear curl php-dev php-gd php-xml php-mbstring php-zip php-apcu php-json php-                                                                                                                        intl php-imagick_

I just re-ran the start.sh script and it finished the install without anymore issues and I did not see either the original php error nor this one.

**Comment by tweenietomatoes** [comment]
it means that you tried to install mailinabox in a server with existing php installation with php packages from somewhere else.
