### ISSUE TITLE
Fail2ban Roundcube Config error

### ISSUE THREAD

**Issue by yeuna92** [mail-in-a-box/mailinabox#1757]
In the config file /etc/fail2ban/jail.d/mailinabox.conf

In the roundcube section logpath is incorrect. It should be /var/log/roundcubemail/errors.log

The default config file is missing the .log extension. 

I just tested this, the file /var/log/roundcubemail/error is empty. Also tested to see if fail2ban would ban a user per the settings in the file and yes it does work as intended.

**Comment by JoshData** [comment]
Thank you. Would you mind opening a pull request here that makes that change?

**Comment by yeuna92** [comment]
Just created that pull request. Awesome project btw.

**Comment by JoshData** [comment]
Thanks!
