### ISSUE TITLE
Link to nextcloud absent

### ISSUE THREAD

**Issue by woodholly** [mail-in-a-box/mailinabox#1764]
There is no link to Nextcloud login page.

**Comment by Mustard** [comment]
Could you explain more about the issue?

Nextcloud is at the `/cloud` path so `yourdomain.tld/cloud`

It is also linked from the Admin portal under "Contacts & Calendar"

**Comment by woodholly** [comment]
Try to find a link to /cloud/ in admin panel.

**Comment by S4-Hosting** [comment]
Under Contacts & Calendar in Admin panel:

Not directly to `/cloud` but to `/cloud/contacts` and to `/cloud/calendar`

![contacts-calendar-miab](https://user-images.githubusercontent.com/64874788/82246712-09b00d00-98fa-11ea-96c0-ed91523afa77.jpg)

**Comment by woodholly** [comment]
LOL. I don't understand, it is hidden by design ?

**Comment by JoshData** [comment]
Yes. The only parts of Nextcloud that are supported are Contacts and Calendar. Everything else is subject to change.
