### ISSUE TITLE
Nginx config for all domains

### ISSUE THREAD

**Issue by woodholly** [mail-in-a-box/mailinabox#1765]
I have checked /etc/nginx/conf.d/local and found something strange, why Roundcube and autoconfig/z-push aliases exist in all domains ? Shouldn't it be only on a primary domain ?

**Comment by doofpot** [comment]
I'm not sure, but round cube on all the domains is a choice by design.

autoconfig/autodiscover aliases is probably on all domains, because the intention is to have mail accounts on those domains;) These records are not necessary when you have a domain with only aliases

**Comment by karlo1941** [comment]
... and, please, create nginx config (local.conf) backup before upgrade.
