### ISSUE TITLE
Security update required for roundcube

### ISSUE THREAD

**Issue by yodax** [mail-in-a-box/mailinabox#1776]
We should probably install 1.4.6:

https://roundcube.net/news/2020/06/02/security-updates-1.4.5-and-1.3.12

**Comment by stvharman** [comment]
Plus 1. This is highly important.

**Comment by JoshData** [comment]
Just posted v0.46 with the update. Thanks for the nudge!

**Comment by yodax** [comment]
Thanks!

**Comment by stvharman** [comment]
Thank you!
