### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by gisdinhoo** [mail-in-a-box/mailinabox#1777]
Hello community. I'm new to mail-in-a-box. I've install it and after login via my web browser to : _**my-ip-address/admin**_ I got an error message show in the image bellow.
I'm using an ubuntu 18.04 machine on microsoft azure cloud.
Thank you
![error](https://user-images.githubusercontent.com/66759704/84337122-50ef8d80-ab88-11ea-888b-e66fd43f0d37.PNG)

**Comment by dms00** [comment]
I believe this post would be more suited to the community forum at mailinabox.email or on their slack channel.

**Comment by yodax** [comment]
I’ve tried running on azure once, it was a major headache and I couldn’t get it working. 

For this specific issue you could run the status checks from the command line and see what that does.

**Comment by gisdinhoo** [comment]
> I’ve tried running on azure once, it was a major headache and I couldn’t get it working.
> 
> For this specific issue you could run the status checks from the command line and see what that does.

Okay, Thank you. And could I run it from command line?

**Comment by gisdinhoo** [comment]
> > I’ve tried running on azure once, it was a major headache and I couldn’t get it working.
> > For this specific issue you could run the status checks from the command line and see what that does.
> 
> Okay, Thank you. And could I run it from command line?

How to run the status from command line?

**Comment by gisdinhoo** [comment]
> I believe this post would be more suited to the community forum at mailinabox.email or on their slack channel.

Okay, thank you!!
