### ISSUE TITLE
_mta-sts.domain.com TXT record has non alphanumeric ID

### ISSUE THREAD

**Issue by jvolkenant** [mail-in-a-box/mailinabox#1779]
https://github.com/mail-in-a-box/mailinabox/blob/9db2fc7f0551b6ea9b7c73f447495fda722473fb/management/dns_update.py#L347

Per https://tools.ietf.org/html/rfc8461 section 3.1.  MTA-STS TXT Records id= records should be alphanumeric.

I get an error when testing one of my domains at https://aykevl.nl/apps/mta-sts/ since the base64 string happens to have a + character in it.

**Comment by jvolkenant** [comment]
Perhaps just skip the base64 step, if the file changes by even one bit, the sha1 would be different anyway, no need to do base64 i wouldn't think.
```
mta_sts_policy_id = hashlib.sha1(f.read()).hexdigest()[0:20]
```

**Comment by JoshData** [comment]
Good catch. Fix coming. hexdigest also makes sense but I'm going to just fix the base64 string.
