### ISSUE TITLE
Adding user will not create directories under `/home/user-data/mail/mailboxes/`

### ISSUE THREAD

**Issue by tasmo** [mail-in-a-box/mailinabox#1796]
The first effect I recognized was that I cannot login in Roundcube with a freshly added user. I got an error `504 Gateway Time-out`. The log says that nginx cannot connect to port 443 at the machine.

Older users can login easily.

After searching some issues and in the [forum](https://discourse.mailinabox.email/) I tried to set up users from the admin panel as well as with the API method. In neither method the corresponding directories have been created under `/home/user-data/mail/mailboxes/`. There is enough space left on the disk.

I tried to reinstall MiaB and rebooted before and after user creation with no effect on the issue.

MiaB version: v0.46

**Comment by alento-group** [comment]
> In neither method the corresponding directories have been created under /home/user-data/mail/mailboxes/.

Simply adding a user does not automatically create the MailDir directories.  They are created upon receipt of email.

This is not related to your issue of adding users however.

**Comment by tasmo** [comment]
Found a solution:

A new user had to login in Nextcloud first. Then mail works as expected.
