### ISSUE TITLE
Upgrade Nextcloud to version > 17

### ISSUE THREAD

**Issue by heinrich-ulbricht** [mail-in-a-box/mailinabox#1803]
Currently Nextcloud version 17 will be installed with MiaB:
https://github.com/mail-in-a-box/mailinabox/blob/65983b8ac73e164b612427ce7895b2f89b138933/setup/nextcloud.sh#L94

According to the [maintenance and release schedule](https://docs.nextcloud.com/server/15/admin_manual/release_schedule.html) this version reaches end of life in September 2020.

So Nextcloud should be upgraded?

**Comment by yodax** [comment]
Probably. However the next upgrade won’t be a straight forward one. 

We would need to install different versions of the plug in during the upgrade. The latest versions of the plugins (cal and carddav) aren’t compatible with the older releases, thus breaking the upgrade path < 17.

**Comment by JoshData** [comment]
It sounds like it's time to do it. Can we continue this in the existing PR #1720?

**Comment by heinrich-ulbricht** [comment]
Of course, didn't see this one.
