### ISSUE TITLE
Upgrading to boto3

### ISSUE THREAD

**Issue by hija** [mail-in-a-box/mailinabox#1806]
I would suggest to upgrade to boto3.

boto3 is considered stable and is recommended to use. boto is not actively updated anymore.

Is there a reason why we stick to boto? Otherwise I would like to update from boto to boto3, since it seems to work better with other s3-compatible storage providers 👍

**Comment by JoshData** [comment]
I think boto is the dependency required by duplicity.

**Comment by hija** [comment]
Okay. I missed that. Thank's for pointing that out!
