### ISSUE TITLE
SMTP port 25 blocked by Amazon EC2 

### ISSUE THREAD

**Issue by ridaeh** [mail-in-a-box/mailinabox#1815]
**Amazon EC2 restricts traffic on port 25** of all EC2 instances and as **mailinabox use this port to send mail** we are n**ot able to send any mail.** is there a way to use an other port ?

**Comment by Synchro** [comment]
It's not that mailinabox uses port 25 for sending (I'd expect it to use randomised high port numbers for outbound ports; their numbers don't matter), it's that every SMTP server in the world expects to _receive_ inbound SMTP on that port.

What you're running into is a specific limitation of EC2; Amazon wants you to pay for their outbound email service. If you need to do lots of email, I'd recommend using a different hosting provider.
