### ISSUE TITLE
MIAB Upgrade failing due to failed wget of NextCloud

### ISSUE THREAD

**Issue by qualitycoder** [mail-in-a-box/mailinabox#1833]
`Mail-in-a-Box Version:  v0.50

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2020-10-07-08:39:24...

Upgrading to Nextcloud version 17.0.6

FAILED: wget -O /tmp/nextcloud.zip https://download.nextcloud.com/server/releases/nextcloud-17.0.6.zip

-----------------------------------------

--2020-10-07 08:39:29--  https://download.nextcloud.com/server/releases/nextcloud-17.0.6.zip
Resolving download.nextcloud.com (download.nextcloud.com)... 95.217.64.181, 2a01:4f9:2a:3119::181
Connecting to download.nextcloud.com (download.nextcloud.com)|95.217.64.181|:443... failed: Connection timed out.
Connecting to download.nextcloud.com (download.nextcloud.com)|2a01:4f9:2a:3119::181|:443... failed: Network is unreachable.

-----------------------------------------

`

**Comment by jvolkenant** [comment]
retry again after download.nextcloud.com fixes their connectivity issues

**Comment by qualitycoder** [comment]
This is working now. Thanks
