### ISSUE TITLE
External DNS - DKIM TXT Record error too long

### ISSUE THREAD

**Issue by plittlefield** [mail-in-a-box/mailinabox#1839]
When trying to add the DKIM TXT Record to my DNS Zone at AWS Route 53, it fails with the following error:-

(InvalidChangeBatch 400: Message was too long, it was truncated. [Invalid Resource Record: FATAL problem: CharacterStringTooLong (Value is too long) encountered with '"v=DKIM1; h=sha256; k=rsa; s=email; p=MIIBIjANBgkqhkiG9wxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx3Zp/GqtHGHlu77Vsq45Y+P96SUCRzth1OPlxOq3o0kuLIbXQpSKeBs6gSH2g24CFYwcH+Ii8dyZuB5H4XvMB/Q9C666UJHifVrxz1ajsbF1gH)

**Comment by Synchro** [comment]
Divide it up into quoted chunks like this:

```
"v=DKIM1; h=sha256; k=rsa; s=email; p=MIIBIjANBgkqhkiG9wxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "3Zp/GqtHGHlu77Vsq45Y+P96SUCRzth1OPlxOq3o0kuLIbXQpSKeBs6gSH2g24CFYwcH+Ii8dyZuB5H4XvMB/Q9C666UJHifVrxz1ajsbF1gH)"
```

**Comment by plittlefield** [comment]
Yes, that worked!

The original 'p=' string was nearly 400 characters long so I divided it in half.

Thanks :)
