### ISSUE TITLE
Add WAF Modsecurity

### ISSUE THREAD

**Issue by LoVoltage** [mail-in-a-box/mailinabox#1840]
Request adding web application firewall modsecurity to protect the open ports from hacking. This will greatly increase the security of the open web ports. 

Info https://blog.nexcess.net/why-modsecurity-should-be-your-web-application-firewall/

How with nginx
https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/

Apache Install contains info for additional configuration
https://hostadvice.com/how-to/how-to-setup-modsecurity-for-apache-on-ubuntu-18-04/

**Comment by Synchro** [comment]
MIAB uses nginx, not apache, and mod_security on nginx is quite painful, not easy to maintain at all. WAFs are to a large extent snake-oil, and on a resource used by people from many different locations, often suffer from false positives. So I'd be -1 on this, FWIW.

**Comment by LoVoltage** [comment]
Understood. Thanks for looking at this
