### ISSUE TITLE
Nextcloud 17 is EOL. Upgrade to version 20?

### ISSUE THREAD

**Issue by stateless** [mail-in-a-box/mailinabox#1846]
Nextcloud 17 is now [EOL](https://nextcloud.com/blog/minor-releases-19-0-4-18-0-10-and-17-0-10-are-here-end-of-support-for-17/). Is the upgrade to version 20 being considered?

**Comment by ddavness** [comment]
I think @JoshData should be able to answer this better

**Comment by JoshData** [comment]
Well I guess we have to now....

**Comment by stateless** [comment]
[Discussion](https://help.nextcloud.com/t/review-nextcloud-release-cycle/95501/1) about the release cycle for Nextcloud.

"This is a review of the Nextcloud release cycle. I’ve been testing on NextcloudPi in addition to regular Nextcloud. All with Mariadb, Redis, fpm. I’ve found admins should expect their Nextcloud system to be fully upgraded at a minimum of every 10 calendar months. This is the most conservative release cycle available for general admins."

**Comment by jvolkenant** [comment]
Are we looking to upgrade to 18, 19, or 20? We typically stay behind the latest release.

**Comment by ddavness** [comment]
> I’ve found admins should expect their Nextcloud system to be fully upgraded at a minimum of every 10 calendar months.

Well, looking back at the release lists, Nextcloud 17 was introduced in MIAB in Februrary, so we've got effectively 8 months. This is not much longer than how long it takes Canonical to launch a new interim (non-LTS) Ubuntu release. And the fact that they're dropping new major versions every couple months does not help much :/

**Comment by stateless** [comment]
I like Nextcloud. I use the file sync function a lot.  But should MIAB consider switching to a different lower maintenance option?

**Comment by JoshData** [comment]
We can go straight to 20.

@stateless That's a separate conversation. I would like to have something simpler, but we haven't yet found a better alternative that covers contacts and calendar and someone will have to do the work to figure out how existing data can be migrated to a new app.

**Comment by yodax** [comment]
> We can go straight to 20.

Just to be clear (for anyone pondering creating a PR), we need to do all the intermediate upgrades (so 17=>18=>19=>20). Also for anyone attempting this PR, the current calendar and contacts plugins can't be upgraded the way we've been doing it up till now. Up till 17 we need to use the current versions, then we can start using the latest versions again. So some changes need to be made to the upgrade mechanism. 
I'm still very much time constraint at the moment. I don't mind reviewing/coaching/testing.

**Comment by jvolkenant** [comment]
@yodax For now, the install/upgrade logic installs the specific version or intermediate version, but then the latest contacts/calendar/user_external.  But the addons are not enabled until after the latest version has been installed anyway. (It has been this way for a long time)  I was hoping to not have to have nextcloud.sh be rewritten to match plugin versions to nextcloud releases.

You are right about having to do the intermediate upgrades. We'll need to make sure that is a part of the PR when its submitted.

**Comment by yodax** [comment]
Even though the plugins are not enabled, upgrades are run when present. The newer plugins always were backwards compatible. They stopped doing that when they did a major version bump. At least they’re supposed to do the upgrades and they were running upgrades before.

**Comment by jvolkenant** [comment]
I don't remember from previous upgrades if I remember seeing any line items for plugins when occ upgrade was run (its been so long)
