### ISSUE TITLE
SMTP port 587 Error

### ISSUE THREAD

**Issue by Akmaling** [mail-in-a-box/mailinabox#1862]
Please I can't connect to installed mailinabox smtp port 587, I always get 
Socket error code 10060: timeout error waiting for response. Please can anyone help.

**Comment by yodax** [comment]
Your hosting provider might have a firewall installed blocking mail traffic. Most of them do. You need to check with them how to open it.

**Comment by Akmaling** [comment]
Thanks @yodax , but I can send and receive mail from browser/roundcube. 
Although some servers I can't  receive nor send mail to them. Example: Protonmail and mail.ru, could it be same problem.

**Comment by yodax** [comment]
What do the status checks say?

**Comment by Akmaling** [comment]
Status Check seems fine, 

Network
--
✓ | Firewall is active.
✓ | Outbound mail (SMTP port 25) is not blocked.
✓ | IP address is not blacklisted by zen.spamhaus.org.

the warming I have here is SSH and Reverse DNS, everything is checked good.

@yodax thanks again

**Comment by Akmaling** [comment]
✓ | All system services are running.
-- | --
✖ | The SSH server on this machine permits password-based login. A more secure way to log in is using a public key. Add your SSH public key to $HOME/.ssh/authorized_keys, check that you can log in without a password, set the option 'PasswordAuthentication no' in /etc/ssh/sshd_config, and then restart the openssh via 'sudo service ssh restart'.
✓ | System software is up to date.
✓ | Mail-in-a-Box is up to date. You are running version v0.51.

**Comment by yodax** [comment]
> but I can send and receive mail from browser/roundcube.

Sorry I missed this. This uses localhost to send. So no firewall is hit. Meaning that the box is probably configured properly and that a firewall is between your mail client and the server.

**Comment by Akmaling** [comment]
> > but I can send and receive mail from browser/roundcube.
> 
> Sorry I missed this. This uses localhost to send. So no firewall is hit. Meaning that the box is probably configured properly and that a firewall is between your mail client and the server.

Thanks ..please how do I resolve it , because I connected with foxmail app on my pc, I can receive mail but cant send, tried it with thunderbird on rdp same problem, "port 587 refused connection"

**Comment by yodax** [comment]
I'm pretty confident this is a firewall between you and the server. Probably at the provider where you are hosting the machine. For instance if you host at scaleway you need to open a support ticket to be able to submit email.

**Comment by Akmaling** [comment]
> I'm pretty confident this is a firewall between you and the server. Probably at the provider where you are hosting the machine. For instance if you host at scaleway you need to open a support ticket to be able to submit email.

Thanks for your time...Grateful

**Comment by fspoettel** [comment]
@Akmaling can this issue be closed?

**Comment by Akmaling** [comment]
@fspoettel  Yes please ...thanks to @yodax.  The provider confirmed the firewall and on change of provider the problem was resolved.

**Comment by fspoettel** [comment]
@Akmaling Glad to hear that! There is a _Close issue_ button on the bottom of the page next to the comment button. Please click that to close the issue. I don't have permission to do that for you. Thanks!
