### ISSUE TITLE
Munin fails to authenticate with TOTP enabled

### ISSUE THREAD

**Issue by fspoettel** [mail-in-a-box/mailinabox#1865]
(Brought up [on Discourse](https://discourse.mailinabox.email/t/how-to-access-munin-after-succesfully-enabling-2fa/7216/3))

Munin uses the `@authorized_personnel_only` decorator while only supplying `username:password` via a HTTP basic auth prompt. This is not enough when TOTP is enabled - either a `user:api_key` combination or a token header need to be provided.

The quickest solution would be to remove the token check for munin routes altogether. I don't think we can do much else since we only proxy requests to their handlers which we do not control. ~~Happy to provide a PR if this solution is acceptable.~~ :ballot_box_with_check: Edit: PR open

**Comment by jacobisreal** [comment]
Same issue - when 2fa is enabled, Munin does NOT allow login.  When disabled, the reaction is as expected.

**Comment by NewbieOrange** [comment]
Can we just assign a token cookie for the user when they passed the mfa, and after that they can visit munin (or any other admin api) with the token? Ofc the token expires after like half an hour.

I can make a PR if the approach looks good to you. @JoshData

**Comment by JoshData** [comment]
We don't use cookies for the admin APIs because they create a cross-site request forgery vulnerability if they're not handled correctly. I would accept a cookie token for the munin routes only, although you will have to construct a token that can be checked for authenticity without using a session database (in the same way the current login API works, but maybe not exactly the same way so that the cookie can't be used to circumvent a login).

**Comment by NewbieOrange** [comment]
I was thinking to generate a random token and store it in redis (set an expiry time) or use `expiringdict`, and modify `mfa.py` to allow both `x-auth-token` and the token cookie to pass the authentication check.

If we set the cookie to `SECURE`, `HTTPONLY` and `SAMESITE`, the browser should help us prevent any CSRF attacks relatively easily.

**Comment by JoshData** [comment]
>  and store it in redis

Nope.

> or use expiringdict

That would actually be fine, and, come to think of it, we could use this to create an in-memory session database to improve the authentication security generally.

> modify mfa.py to allow both x-auth-token and the token cookie to pass the authentication check

That would be fine as long as the cookie only applies to the munin route.

> If we set the cookie to SECURE, HTTPONLY and SAMESITE, the browser should help us prevent any CSRF attacks relatively easily.

Those do not guard against a typical CSRF attack.
