### ISSUE TITLE
Ignore certain requests from z-push

### ISSUE THREAD

**Issue by jkaberg** [mail-in-a-box/mailinabox#187]
Currently my access log is so spammed (and quite large) its become a problem for me

>127.0.0.1 - joel@jkaberg.com [09/Sep/2014:19:27:46 +0200] "REPORT /caldav/calendars/joel@jkaberg.com/personlig/ HTTP/1.1" 207 568 "-" "ModifiedDAViCalClient"
>5.39.92.137 - joel@jkaberg.com [09/Sep/2014:19:27:59 +0200] "REPORT /cloud/remote.php/caldav/calendars/joel@jkaberg.com/contact_birthdays/ HTTP/1.0" 207 3864 "-" "ModifiedDAViCalClient"
>127.0.0.1 - joel@jkaberg.com [09/Sep/2014:19:27:59 +0200] "REPORT /caldav/calendars/joel@jkaberg.com/contact_birthdays/ HTTP/1.1" 207 3876 "-" "ModifiedDAViCalClient"
>5.39.92.137 - joel@jkaberg.com [09/Sep/2014:19:27:59 +0200] "REPORT /cloud/remote.php/caldav/calendars/joel@jkaberg.com/personlig/ HTTP/1.0" 207 556 "-" "ModifiedDAViCalClient"
>127.0.0.1 - joel@jkaberg.com [09/Sep/2014:19:27:59 +0200] "REPORT /caldav/calendars/joel@jkaberg.com/personlig/ HTTP/1.1" 207 568 "-" "ModifiedDAViCalClient"
>46.249.234.21 - joel@jkaberg.com [09/Sep/2014:19:28:09 +0200] "PROPFIND /cloud/remote.php/webdav/ HTTP/1.1" 207 4177 "-" "Mozilla/5.0 (Windows) mirall/1.6.3"
>46.249.234.21 - joel@jkaberg.com [09/Sep/2014:19:28:09 +0200] "PROPFIND /cloud/remote.php/webdav/ HTTP/1.1" 207 498 "-" "Mozilla/5.0 (Windows) mirall/1.6.3"
>5.39.92.137 - joel@jkaberg.com [09/Sep/2014:19:28:12 +0200] "REPORT /cloud/remote.php/caldav/calendars/joel@jkaberg.com/contact_birthdays/ HTTP/1.0" 207 3864 "-" "ModifiedDAViCalClient"
>127.0.0.1 - joel@jkaberg.com [09/Sep/2014:19:28:12 +0200] "REPORT /caldav/calendars/joel@jkaberg.com/contact_birthdays/ HTTP/1.1" 207 3876 "-" "ModifiedDAViCalClient"
>5.39.92.137 - joel@jkaberg.com [09/Sep/2014:19:28:12 +0200] "REPORT /cloud/remote.php/caldav/calendars/joel@jkaberg.com/personlig/ HTTP/1.0" 207 556 "-" "ModifiedDAViCalClient"
>127.0.0.1 - joel@jkaberg.com [09/Sep/2014:19:28:12 +0200] "REPORT /caldav/calendars/joel@jkaberg.com/personlig/ HTTP/1.1" 207 568 "-" "ModifiedDAViCalClient"

Got any ideas? I'm not very good with regex, otherwise one could maybe use 
>location = /caldav/calendars/ {
>	access_log off;
>}

**Comment by fmbiete** [comment]
It's correct to have those lines in the log file, since z-push will be checking the backend servers almost continously. If that's a problem, you could add a server in nginx for 127.0.0.1 and disable login in it. Something like this:

```
server {
     listen 127.0.0.1:80;
     server_name dav_server;

     access_log off;
}
```

Of course, your z-push config should use 127.0.0.1 as the address for the dav server.
