### ISSUE TITLE
CNAME breaks zone file (follow-up?!)

### ISSUE THREAD

**Issue by steadfasterX** [mail-in-a-box/mailinabox#1870]
MIB version: v0.51
Ubuntu version: 18.04.5

exactly the issue what I currently have is described here: https://github.com/mail-in-a-box/mailinabox/issues/1041

I want to create a CNAME for _thisdoesnotexists.com_ (I do not own that one, its just for this example) and point it to another domain _thisismycname.com_ .

note: (afaik) in MIB you have to create a mail alias or user account to make the domain available in custom DNS settings page (and others). This automatically creates a zone file containing MX (and others) lines. 

As described in the mentioned issue these additional lines causing NSD to fail - likely MX but same applies to TXT and others!

Error:

```
[2020-11-26 11:49:30.943] nsd[30708]: notice: nsd starting (NSD 4.1.17)
[2020-11-26 11:49:30.986] nsd[30710]: error: thisdoesnotexists.com.txt.signed:8: CNAME and other data at the same name
[2020-11-26 11:49:30.986] nsd[30710]: error: thisdoesnotexists.com.txt.signed:9: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:10: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:11: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:12: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:13: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:14: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:15: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:16: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:17: CNAME and other data at the same name
[2020-11-26 11:49:30.987] nsd[30710]: error: thisdoesnotexists.com.txt.signed:18: CNAME and other data at the same name
[2020-11-26 11:49:30.988] nsd[30710]: error: zone thisdoesnotexists.com file thisdoesnotexists.com.txt.signed read with 11 errors
```

Zone file (signed). Note: this shows the first 18 lines only and I marked line 8 with "->":

```
thisdoesnotexists.com.	1800	IN	SOA	ns1<REMOVED>. hostmaster.<REMOVED>. 2020112601 7200 1800 1209600 1800
thisdoesnotexists.com.	1800	IN	RRSIG	SOA 7 2 1800 20201226000000 20201126104930 36212 <REMOVED>
thisdoesnotexists.com.	1800	IN	NS	ns0.1984.is.
thisdoesnotexists.com.	1800	IN	NS	ns1.<REMOVED>.
thisdoesnotexists.com.	1800	IN	NS	ns1.1984.is.
thisdoesnotexists.com.	1800	IN	NS	ns2.1984.is.
thisdoesnotexists.com.	1800	IN	RRSIG	NS 7 2 1800 20201226000000 20201126104930 36212 <REMOVED>
-> thisdoesnotexists.com.	1800	IN	CNAME	thisismycname.com.
thisdoesnotexists.com.	1800	IN	RRSIG	CNAME 7 2 1800 20201226000000 20201126104930 36212 <REMOVED>
thisdoesnotexists.com.	1800	IN	MX	10 <REMOVED>.
thisdoesnotexists.com.	1800	IN	RRSIG	MX 7 2 1800 20201226000000 20201126104930 36212 <REMOVED>
thisdoesnotexists.com.	1800	IN	TXT	"v=spf1 mx -all"
thisdoesnotexists.com.	1800	IN	RRSIG	TXT 7 2 1800 20201226000000 20201126104930 36212 <REMOVED>
thisdoesnotexists.com.	1800	IN	DNSKEY	256 3 7 <REMOVED>
thisdoesnotexists.com.	1800	IN	DNSKEY	257 3 7 <REMOVED> ;{id = 29883 (ksk), size = 2048b}
thisdoesnotexists.com.	1800	IN	RRSIG	DNSKEY 7 2 1800 20201226000000 20201126104930 29883 <REMOVED>
thisdoesnotexists.com.	3600	IN	NSEC3PARAM	1 0 1 - 
thisdoesnotexists.com.	3600	IN	RRSIG	NSEC3PARAM 7 2 3600 20201226000000 20201126104930 36212 
```

unsigned zone file:

```
$ORIGIN thisdoesnotexists.com.
$TTL 1800           ; default time to live

@ IN SOA ns1.<REMOVED>. hostmaster<REMOVED>. (
           2020112601     ; serial number
           7200     ; Refresh (secondary nameserver update interval)
           1800     ; Retry (when refresh fails, how often to try again)
           1209600  ; Expire (when refresh fails, how long secondary nameserver will keep records around anyway)
           1800     ; Negative TTL (how long negative responses are cached)
           )
	IN	NS	ns1<REMOVED>.
	IN	NS	ns0.1984.is.
	IN	NS	ns1.1984.is.
	IN	NS	ns2.1984.is.
	IN	CNAME	thisismycname.com.
	IN	MX	10 <REMOVED>.
	IN	TXT	"v=spf1 mx -all" 
_dmarc	IN	TXT	"v=DMARC1; p=quarantine" 
mail._domainkey	IN	TXT	"v=DKIM1; k=rsa; s=email; p=<REMOVED>" "<REMOVED>" 
_caldavs._tcp	IN	SRV	0 0 443 <REMOVED>.
_carddavs._tcp	IN	SRV	0 0 443 <REMOVED>.
autoconfig	IN	A	85.214.<REMOVED>
autodiscover	IN	A	85.214.<REMOVED>
mta-sts	IN	A	85.214.<REMOVED>
www	IN	A	85.214.<REMOVED>
www	IN	TXT	"v=spf1 -all" 
_dmarc.www	IN	TXT	"v=DMARC1; p=reject" 
```

the fix of the mentioned issue #1041 has been "solved" because he removed the MX entry but is that really the way to go here?

If so what is the best process to follow in achieving this -> without overwriting accidentally the changes some when? .. and as the NSD error log shows it might be not enough just doing that?!

**EDIT:**

Found a reason / workaround:

The above described issue occurs only when setting the CNAME on just the domain (here: thisdoesnotexists.com). 

What seems to work well is when using a subdomain like **www**.thisdoesnotexists.com. This will add the CNAME to the existing thisdoesnotexists.com zone file and NSD is happy.

Problem: I still cannot use a CNAME on the domain itself (i.e thisdoesnotexists.com). Is that expected behavior? Is there any way to allow a CNAME here?

**EDIT2:**

it seems clear defined here: https://tools.ietf.org/html/rfc2181#section-10
so (e.g) no MX allowed but SIG is etc. 

so.. what would be the way to go then? I mean.. we need a MX record here to allow receiving emails right? and we also need it because its the way how MIB knows about a new domain. I am a bit stuck atm..

**Comment by alento-group** [comment]
> Problem: I still cannot use a CNAME on the domain itself (i.e thisdoesnotexists.com). Is that expected behavior? Is there any way to allow a CNAME here?

You cannot CNAME the apex of a domain.  You must use an A record.  This is a RFC and has nothing to do with Mail-in-a-Box.

What exactly are you trying to do?

**Comment by steadfasterX** [comment]
> > Problem: I still cannot use a CNAME on the domain itself (i.e thisdoesnotexists.com). Is that expected behavior? Is there any way to allow a CNAME here?
> 
> You cannot CNAME the apex of a domain. You must use an A record. This is a RFC and has nothing to do with Mail-in-a-Box.
> 
> What exactly are you trying to do?
what I am trying to do is very detailed described above. so like I thought this is a restriction by the RFC and not mib. thx for confirming.
