### ISSUE TITLE
Is there a reason to leave Unattended-Upgrade::Remove-Unused-Kernel-Packages "false";

### ISSUE THREAD

**Issue by myfirstnameispaul** [mail-in-a-box/mailinabox#1874]
Just wondering if there was some reason to enable `unattended-upgrades` but leave `Unattended-Upgrade::Remove-Unused-Kernel-Packages "false";` (the default) in `/etc/apt/apt.conf.d/50unattended-upgrades`?

Otherwise I'll figure out how to submit a PR to set to `true`.

**Comment by hija** [comment]
I don't see this in my configuration:

```
// Remove unused automatically installed kernel-related packages
// (kernel images, kernel headers and kernel version locked tools).
//Unattended-Upgrade::Remove-Unused-Kernel-Packages "false";
```
This line is commented out and according to the documentation (https://help.ubuntu.com/community/RemoveOldKernels#Configure_Unattended_Upgrades_to_Remove_Unneeded_Kernels_Automatically) the default value is true:

> Version 1.1 that is also currently available for Ubuntu 16.04 adds yet another option called Unattended-Upgrade::Remove-Unused-Kernel-Packages. It removes unused kernel packages before installing new one (or even if nothing is installed). It is enabled by default, too. 


So this is not an issue for me. Have you verified that unused kernels do not get removed?

**Comment by myfirstnameispaul** [comment]
I have not observed MiaB to remove unused kernels. Occasionally there are updates that Ubuntu requires I run manually, for whatever reason, and when I run them I will be informed there are a bunch of unused kernels and I should run `apt-get autoremove` to remove them. If I haven't done this in a while it's usually ~1 GB storage freed.

Is there anywhere other than the community pages this is documented? In the past, I have discovered issues with community pages. I do know it is possible that `unattended-upgrades` intentionally does not remove all unused kernels compared to `apt autoremove`, so I'm not entirely certain it isn't doing its job. It's just that my experience with a lot of the default config files is they will provide the default configuration option even when commented out.

I'll look at this more later this weekend.

**Comment by hija** [comment]
Looking at the sourcecode https://github.com/mvo5/unattended-upgrades/blob/c0ff8afc027144640e2559c202f252ea284a3fbc/unattended-upgrade#L2300 I think that the value in fact does default to true.

But look into it this weekend, I am curious to learn about your findings :)

**Comment by myfirstnameispaul** [comment]
Thanks for finding that.

Just for the heck of it, I have just gone however many kernel upgrades after autoremoving once simultaneously with another 18.04 server that doesn't have any auto upgrades whatsoever, and already there are at least two versions deleted from the mail server, so it does seem to be working as intended.
