### ISSUE TITLE
Using SSL (port 465) and not TLS for SMTP (outgoing mails)

### ISSUE THREAD

**Issue by rikoz** [mail-in-a-box/mailinabox#1889]
Please how can i configure mail-in-a-box to start using SSL encryption on port 465 and not TLS.

Also i was able to host my PHP based website after making some tweaks, to the cron jobs rewriting the nginx local.conf, but the box.domain.com/mail/ says `FILE NOT FOUND`. Roundcube disappeared.

**Comment by hija** [comment]
> Please how can i configure mail-in-a-box to start using SSL encryption on port 465 and not TLS.

Not possible yet, but others have thought about it already: #1849 If you want to have the feature sooner available, you could try to contribute to the issue :)

> Also i was able to host my PHP based website after making some tweaks, to the cron jobs rewriting the nginx local.conf, but the box.domain.com/mail/ says FILE NOT FOUND. Roundcube disappeared.

Usually, it is recommended to use MIAB standalone without installing further software on the server (that's also why a clean ubuntu installation is required). If you are installing new software (e.g. PHP) to MIAB, change settings and code, it gets hard to help fixing problems. Furthermore, some config files get overwritten once you do an MIAB upgrade. Thus, I recommend against installing custom software and code on the MIAB service/server/instance, and using an own instance for your PHP based website instead.

**Comment by rikoz** [comment]
Thanks @hija, for the direction to the existing issue. On the other hand, I was able to modify MIAB config and cron jobs in management. All fixed now. I wouldn't be needing any latest versions soon

**Comment by hija** [comment]
Good job  👍 

> I wouldn't be needing any latest versions soon

Don't forget we provide security updates for roundcube and new features with new versions. 

Have fun with MIAB :)

**Comment by JoshData** [comment]
Implemented in d510c8ae2a5b55ef1b22cc57c8ff8a2fe8597546.
