### ISSUE TITLE
What domain/TLD did you use? Did it work?

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#189]
Some top-level domains have quirks. For instance:

* in #151 it was discovered that .de domains require two distinct namesevers, which is a problem for the recommended setup for Mail-in-a-Box
* I wasn't able to set DS records on my .us and .email domains (using Godaddy)

What top-level domain did you try with Mail-in-a-Box and did it work? Did you try setting a DS record and did that work too?

I'm compiling a list at https://mailinabox.email/tld-quirks.html. Please either reply to this thread with any info or [submit a pull request to edit this file](https://github.com/mail-in-a-box/mailinabox.email/blob/master/tld-quirks.html) directly. Thanks!

**Comment by foobarbecue** [comment]
I can't get .is to work because it requires your nameservers to be "registered." I'm not sure what registered means.

**Comment by JoshData** [comment]
Did you do the glue records step?

**Comment by foobarbecue** [comment]
Tried to, but I'm confused about how to set them... isnic has a place you can set nameservers, which you get to by pressing a button labelled "redelegate" and then it has a place you can set "DS records". I tried putting ns1.box.mydomain.is and ns2.box.mydomain.is in for the nameservers under "redelegate" and I get 

> Please fix the following input errors:
> The nameserver ns1.box.mydomain.is has not been registered

**Comment by JoshData** [comment]
That's probably the next step (not the glue record step), and if those are the only options isnic may not support it.

**Comment by foobarbecue** [comment]
Yep, looks that way. I have cloudflare handling it now. I guess I'll try and setup mailinabox with cloudflare for my .is then.

**Comment by foobarbecue** [comment]
Actually it does say something about [glue records in their faq.](https://www.isnic.is/en/faq)

**Comment by foobarbecue** [comment]
Ah, just found a link called "nameserver registration" in the lefthand navigation. Trying.

**Comment by foobarbecue** [comment]
So I put my hostname and IP in under register nameserver and isnic ran a test which failed, presumably because I don't have a nameserver running yet. 

> The nameserver BOX.MYDOMAIN.IS (123.123.123.123) seems to ignore test queries to UDP port 53
> The nameserver BOX.MYDOMAIN.IS (123.123.123.123) seems to reject connections to TCP port 53

**Comment by foobarbecue** [comment]
Ok, I was able to register box.mydomain.is after installing mailinabox. However, isnic won't let me register ns1.box.mydomain.is :

> The nameserver NS1.BOX.MYDOMAIN.IS is not correctly registered in DNS (The PTR RRset for 123.123.123.123 does not include the name NS1.BOX.MYDOMAIN.IS)

**Comment by JoshData** [comment]
We're off topic here because this issue is about TLDs and the problem here is about your registrar.... But the conclusion seems to be that the registrar is being annoying and you will probably not be able to use it the way Mail-in-a-Box recommends.

**Comment by foobarbecue** [comment]
Hm, anyone using .is without these problems? I'm guessing these rules are enforced for all .is domains.

I'm pretty new to DNS... but it seems if I could set the PTR records in the nsd config so that it points to the ns1.box. subdomain instead of to box. then it would work. Does that seem right? I was going to try and do it but there's so much stuff in the nsd config and I'm pretty confused as to what's what... what file has the reverse stuff in it?

**Comment by JoshData** [comment]
Please start a new topic on the forum.
