### ISSUE TITLE
Switch from sqlite to mariadb/mysql for nextcloud allowing file sync

### ISSUE THREAD

**Issue by divansantana** [mail-in-a-box/mailinabox#1907]
File sync in nextcloud currently fails when using the desktop client.

Nextcloud recommends mysql rather then sqlite.  I know this project is primarily aimed at mail + contacts.

Perhaps consider switching from sqlite to mysql allowing a functioning nextcloud file sync, while keeping previous functionality.

See also #273 #514

**Comment by divansantana** [comment]
One can convert from sqlite to mysql by doing the below.  Guess this is going to make upgrades of mailinabox a bit painful.

See also https://docs.nextcloud.com/server/20/admin_manual/configuration_database/db_conversion.html

First, probably better to disable some apps, before doing the
conversation.  They can cause failures during the conversion.

Like disable/uninstall nextcloud news.

Login to sqlite and cleanup nextcloud news data.

sqlite3 /home/user-data/owncloud/owncloud.db
DROP TABLE oc_news_feeds;
DROP TABLE oc_news_folders;
DROP TABLE oc_news_items;

apt-get install -y mariadb-server mariadb-client php-mysql

mysql -u root
create database nextcloud;
create user 'oc_mysql_user'@'127.0.0.1' identified by 'SomePassword';
create user 'oc_mysql_user'@'localhost' identified by 'SomePassword';
grant all privileges on nextcloud.* to 'oc_mysql_user'@'127.0.0.1';
grant all privileges on nextcloud.* to 'oc_mysql_user'@'localhost';
FLUSH PRIVILEGES;

cd /usr/local/lib/owncloud
sudo -u www-data php occ db:convert-type --port 3306 --password SomePassword --all-apps mysql oc_mysql_user 127.0.0.1 nextcloud

Then can configure 4byte support.

https://docs.nextcloud.com/server/20/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by JoshData** [comment]
This doesn't fall within the project's goals and would make the project significantly harder to maintain, so it's not a change I would accept.

**Comment by divansantana** [comment]
Thought so. OK.
