### ISSUE TITLE
Restoring(migrating) install - nextcloud.sh: line 27: $7: unbound variable

### ISSUE THREAD

**Issue by MalakymR** [mail-in-a-box/mailinabox#1909]
I’m trying migrate my Ubuntu 14 to 18. MAIB is fully updated on 14 (so is Ubuntu).

I’ve restored with duplicity, then run mailinabox setup again, which ends with this…

```
Upgrading Nextcloud — backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2021-01-05-12:49:13…

setup/nextcloud.sh: line 27: $7: unbound variable
```

Full process: https://pastebin.com/Y214UaVc

I’m not sure what is meant to come after this to know what to expect to be broken - from looking myself I have no IMAP access or (webmail) /mail access. Admin panel works okay. I’ve had to go back to the old Ubuntu 14 installation for the moment.

Line 27: version_user_external=$7

Edit: This seems to happen when going from v0.40 to v0.51 as well - does not seem related to the Ubuntu migration itself.

**Comment by jvolkenant** [comment]
What was your specific order of mail in a box versions on ubuntu 14 and 18 when you did the upgrade?  There is a specific flow in doing it, there is a link on the homepage.

**Comment by MalakymR** [comment]
I was already on the newest whilst on Ubuntu 14 anyway, I'm aware a specific version is needed before migrating, I never had to go upgrade to 0.30 before I started this.


`A  new version of Mail-in-a-Box is available. You are running version  v0.30. The latest version is v0.51. For upgrade instructions, see  https://mailinabox.email`


https://discourse.mailinabox.email/t/mail-in-a-box-version-v0-40-and-moving-to-ubuntu-18-04/4289

I was following this, although it boils down to making sure I'm on v0.30 (I am), then fresh install on Ubuntu 18 and run the setup fresh then restore the backup. Nothing much else to do really.

**Comment by jvolkenant** [comment]
Problem is likely here, it does not define the user_external version and hash:
https://github.com/mail-in-a-box/mailinabox/blob/879467d358d375c83225e57056569f305a1d969d/setup/nextcloud.sh#L156

I would guess that you tried going from v0.30 to v0.51 or something similar. Off the top of my head, you should be upgrading your install on 14.04 to v0.30, then doing a backup. Installing that backup on 18.04, running v0.40 (or v0.41 or similar), then doing a higher version install afterwards.

**Comment by MalakymR** [comment]
If v0.51 was current a few weeks ago, then yes that would have been it. The install doesn't specify any specific versions - is that even possible?

**Comment by jvolkenant** [comment]
Yes, you can git checkout tagged versions.

I would recommend this flow.

- Restore the v0.30 backup to a fresh 18.04 VM
- `git clone https://github.com/mail-in-a-box/mailinabox.git`
- `cd mailinabox`
- `git checkout v0.40`
- `setup/start.sh`
- `git checkout v0.51` (or some more interm steps in between
- `setup/start.sh`

**Comment by MalakymR** [comment]
setup.sh would suggest setting an environment variable $TAG=v0.40

I will give that a try as its less steps - git may not exist on the fresh install.

**Comment by jvolkenant** [comment]
Yea, if the intention is that you can go from v0.30 copied to an 18.04 vm without going to v0.40 (or some interim version), the code for nextcloud.sh needs to be adjusted since nextcloud 13 includes user_external, so calling the InstallNextcloud function with less than 8 variables will fail.

@JoshData can you confirm the intended flow for 14.04 -> 18.04? is it v0.30 on 14.04, restored to 18.04 and run v0.40 or run latest tag?

**Comment by jvolkenant** [comment]
> 
> I will give that a try as its less steps - git may not exist on the fresh install.

true, bootstrap.sh would install this.  You could probably do `TAG=v0.40 setup/bootstrap.sh` to accomplish similar to the git checkout above

**Comment by JoshData** [comment]
> can you confirm the intended flow for 14.04 -> 18.04? is it v0.30 on 14.04, restored to 18.04

Right.

>  and run v0.40 or run latest tag

It would be nice if it worked with the latest tag, but since @MalakymR might be the last person to do it, it might not be worth fixing it to work and requiring that folks use the v0.40 tag first.

**Comment by MalakymR** [comment]
> > and run v0.40 or run latest tag
> 
> It would be nice if it worked with the latest tag, but since @MalakymR might be the last person to do it, it might not be worth fixing it to work and requiring that folks use the v0.40 tag first.

I agree. Better to have a consistent migration with the extra upgrade step than having to confirm every tag.

Granted its worth the setup knowing which upgrades would fail if we're allowed to jump intermediate releases.

**Comment by MalakymR** [comment]
Migrating to v0.40 has completed okay.

Putting _TAG=v0.40_ in front of the curl line doesn't work as it pipes to bash. Setting that var on its own line is how I sorted it (before bash -E would probably work too).

**Comment by MalakymR** [comment]
I tried to jump to v0.51 from v0.40 in situ and got the same error I started with above.

Going to finalise this move right now (DNS updates and such) then will have to look at it again. Assuming this hasn't broken the install as it has done some database schema updates.

```
Mail-in-a-Box Version:  v0.51

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Updating database schema (2018021600)... [OK]
Updating database schema (2018122300)... [OK]
Updating database schema (2019092900)... [OK]
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2021-01-28-20:56:43...
setup/nextcloud.sh: line 27: $7: unbound variable
```

**Comment by MalakymR** [comment]
Using v0.45 as an intermediate seems to work. Updates NextCloud from 14 to 17.

v0.40 > v0.45 > v0.51 works - NextCloud 20

I will try and find the newest that will update from v0.40 soon - my snapshots are extremely slow to restore/create.

I've yet to try this with any restored data though, but I'm not sure that matters.

**Comment by jvolkenant** [comment]
The code that uses $7 was added between v0.50 and v0.51.

https://github.com/mail-in-a-box/mailinabox/blob/e3d98b781ea44218a9b063c01d3f9b603ac26427/setup/nextcloud.sh#L27-L28
There is already a check later in the function for an empty `version_user_external`

maybe it's as simple as changing those two lines on v0.51 to these which would initialize empty variables:
```
version_user_external="${7:-}"
hash_user_external="${8:-}"
```

**Comment by MalakymR** [comment]
> maybe it's as simple as changing those two lines on v0.51 to these which would initialize empty variables:
> 
> ```
> version_user_external="${7:-}"
> hash_user_external="${8:-}"
> ```

I have just tested this to upgrade from v0.40 to v0.51 and it works.

I can't do a v0.30 restore any more though.

**Comment by malord** [comment]
Just to confirm the blank arguments fix above, I encountered this myself and fixed it in a similar way. 

I edited ~/mailinabox/setup/nextcloud.sh, changing the InstallNextcloud call that migrates from Nextcloud 13 to 14:

`# If we are running Nextcloud 13, upgrade to Nextcloud 14`
`InstallNextcloud 14.0.6 4e43a57340f04c2da306c8eea98e30040399ae5a 3.3.0 e55d0357c6785d3b1f3b5f21780cb6d41d32443a 2.0.3 9d9717b29337613b72c74e9914c69b74b346c466`

by adding two blank arguments to the end:

`InstallNextcloud 14.0.6 4e43a57340f04c2da306c8eea98e30040399ae5a 3.3.0 e55d0357c6785d3b1f3b5f21780cb6d41d32443a 2.0.3 9d9717b29337613b72c74e9914c69b74b346c466 "" ""`

This allowed the migration to continue and the mail server has been working perfectly for a few months now.

**Comment by jvolkenant** [comment]
> 
> 
> > maybe it's as simple as changing those two lines on v0.51 to these which would initialize empty variables:
> > ```
> > version_user_external="${7:-}"
> > hash_user_external="${8:-}"
> > ```
> 
> I have just tested this to upgrade from v0.40 to v0.51 and it works.
> 
> I can't do a v0.30 restore any more though as I don't have any way to repeat this process.

Thanks for testing this and confirming v0.40 to v0.51 works (when this patch is added)
