### ISSUE TITLE
Receiving "fatal: No annotated tags can describe '90d63fd208ebeca9378a31d97f844363296d6f51'" on upgrade from v0.51 to v0.52

### ISSUE THREAD

**Issue by marqaaron** [mail-in-a-box/mailinabox#1910]
Good morning @JoshData. I just attempted to upgrade my box to v0.52 from v0.51 after seeing during my morning system checks that you cut a new version.  I ran the usual upgrade/install command and I received the following error in my logs:

```
# IP Addresses and hostnames redacted

Primary Hostname: box.xxxxxx.net
Public IP Address: xxxxxxx
Public IPv6 Address: xxxxxxxxxx
fatal: No annotated tags can describe '90d63fd208ebeca9378a31d97f844363296d6f51'.
However, there were unannotated tags: try --tags.
Mail-in-a-Box Version:
```

While I received the above error, the upgrade process appears to have completed successfully.  Once returning to the Status Checks panel I could see the warning about"A new version is available" but with "Unknown" as my current version tag.  See below.

![Screen Shot 2021-01-31 at 7 15 53 AM](https://user-images.githubusercontent.com/57965459/106388605-2a3ecb00-6394-11eb-8015-55b51caed292.png)

Is this just a build and tagging issue as the message suggests?

Best!

Mark

**Comment by Dibbyo456** [comment]
Same here...!

**Comment by ddavness** [comment]
Looks like there are two types of Git tags, and Josh happened to pick the wrong one. There is a fix for this but Josh could just re-do the tag and push it properly.

**Comment by JoshData** [comment]
Yep, apologies. I have re-done the tag. Does this fix it?

**Comment by marqaaron** [comment]
Running the upgrade command again generates the same warning for me.  Do I need to rollback to the previous version so that the new tag can be picked up?  If so, what's the command to install a specific version?

**Comment by stuartfletcheruk** [comment]
Did not fix it for me. Re-ran the install and rebooted

**Comment by etiago** [comment]
Also didn't fix it here. Just reran the script and still get the same.

**Comment by dannyvankooten** [comment]
Just ran `curl -s https://mailinabox.email/setup.sh | sudo bash`, works for me.

**Comment by etiago** [comment]
Maybe the script has been fixed for new runs, but doesn't work for those who are stuck in a non-annotated tag.

Just tried running it again and still getting the same, I assume because I'd ran the broken version.

**Comment by yodax** [comment]
You could try removing the mailinabox directory. It's under the path where you run the curl command. Alternatively you could try manually resetting the git repo.

**Comment by etiago** [comment]
Thanks, that did the trick indeed :slightly_smiling_face: . I nuked the repo, ran the script again and it started cleanly from scratch.

**Comment by marqaaron** [comment]
Thanks @yodax, I can confirm that removing the existing mailinabox directory under the path where I run the curl command followed by rerunning the install/upgrade command solved my problem just like @etiago.

@JoshData. Closing this as resolved.

**Comment by mannp** [comment]
@JoshData does this method reset the mail-in-a-box instance completely by doing this? Not liking the thought of nuking my instance being the resolution?

Cheers

**Comment by marqaaron** [comment]
@mannp "Nuking" was probably the wrong term for us to use.  I can confirm for you that this method does not completely delete your instance, since all of my data and configs remained intake after I used it.

If you want peace of mind, go to directory usually run your command from which for me was simply my home directory.  List out the files/directories and you should see a directory named 'mailinabox'.  Move into this directory and list out the files again.  You'll see that the 'mailinabox' directory contains nothing more than the exact contents of the git repository for mailinabox.  By deleting this directory and rerunning the install command you simply end up with a refresh copy of the repo.

**Comment by yodax** [comment]
All the user data is stored under /home/user-data. Your safe. If you don’t trust it, just move the directory. But as said above, it’s just the gut repo.

**Comment by etiago** [comment]
Yes, apologies for my wording, `nuking` was prone to confusion... But indeed, it's perfectly safe as it's just the repo containing all the management scripts.

You're not destroying your instance unless you're touching the `/home/user-data` as @yodax mentioned.

**Comment by JoshData** [comment]
This issue is also totally harmless, so you can also ignore it and just wait for it to resolve when we get to the next release.

**Comment by mannp** [comment]
Thanks @marqaaron I saved to '-save- and updated again, success and deleted the save dir. Cheers

Extra reassurance, thanks @yodax 

Np @etiago, just wanted to check :)
