### ISSUE TITLE
Setup / UpGrade Routine shows wrong (previous) Version number

### ISSUE THREAD

**Issue by cmasterdelphi** [mail-in-a-box/mailinabox#1911]
**Problem:**
When starting the install routine to upgrade mailinabox, it always shows the wrong version number as current.

**Steps to reproduce.**
Have a 'old' version of mailinabox
run install/upgrade script
notice wrong version number

**Pictures:**
I started the install/upgrade routine from v0.51 but it shows v0.52 -> 0.52
![image](https://user-images.githubusercontent.com/56067322/106481554-d70c6b80-64ac-11eb-8dc4-eb94a791e74a.png)

**Comment by JoshData** [comment]
This is just output from `git` as a part of fetching the current version tag and isn't meant to indicate the previous version installed.

**Comment by cmasterdelphi** [comment]
Thanks for the clarification. Issue can be closed.
