### ISSUE TITLE
backup.py rsync_ssh_options

### ISSUE THREAD

**Issue by edwhardo** [mail-in-a-box/mailinabox#1914]
Backing up over rsync is forced on port 22 by the variable set in line 19 of backup.py because of "-p 22"

If the "-p 22" were omitted rsync would use ssh over port 22 anyway.

With "-p 22" set, one cannot create an entry in /root/.ssh/config such as:

Host hostnameof.your.backupserver
    Port 2345

which would override the ssh port

I have seen discussion about adding a way to change the port on the admin interface to enter an alternate port, which would also work, but it seems that this isn't a priority.

changing line 19 from
"--rsync-options= -e \"/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab\"",
TO
"--rsync-options= -e \"/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -i /root/.ssh/id_rsa_miab\"",

would be my suggestion.

BTW, I'm reporting this because I received git errors on the upgrade from 0.51 to 0.52. It caught me off guard for a bit as I usually don't modify code that could change with upgrade, but it seems backup.py hasn't been touched in a while.

**Comment by jvolkenant** [comment]
Sounds reasonable, removing "-p 22" doesn't affect normal users and leaves a workaround for unsupported uses

**Comment by jvolkenant** [comment]
Also, what git errors did you have was it regarding line 19? That line hasn't been modified in years.

**Comment by edwhardo** [comment]
I modified line 19 a couple of years ago. First to specify my custom ssh port, then later just to remove the "-p 22" and use the ssh config. I knew both would break a future upgrade when I did it, but I had forgotten about it until I tried to upgrade from 0.51 to 0.52.
The error was this:

`From https://github.com/mail-in-a-box/mailinabox
 * [new tag]         v0.52      -> v0.52
error: Your local changes to the following files would be overwritten by checkout:
	management/backup.py
Please commit your changes or stash them before you switch branches.
Aborting
Update failed. Did you modify something in /root/mailinabox?
`
At which point, I knew exactly what caused the Abort, and then thought about suggesting the change here. It won't break anything for those who use port 22 and if anyone who has already changed the "-p 22" option to a custom port, it takes a few seconds to edit /root/.ssh/config

**Comment by jvolkenant** [comment]
Resolving conflicts is all part of running your own fork/unsupported changes.

**Comment by edwhardo** [comment]
Indeed!
It seems best to not make unsupported changes with mailinthebox, but I'll stick with this one even if the team doesn't want to integrate it. Hopefully it could make things easier for some?
Anyhow, I'm happy if you want to close this issue (or would like me to close it). I've got nothing else to add except congratulations to the team for a very slick product.
Cheers

**Comment by aroundmyroom** [comment]
in previous versions the -p 2345 was working fine. Even now, but the only thing the frontend does not want to do is to show what is available on the other end. the ./backup.py -- verify is working fine after I made my -p changes

A lot of users are unable to connect over port 22 when transferring backups to another system

**Comment by DerBunteBall** [comment]
I'm giving this a push.

Actually I have the SSH port problem too. You can't use e.g. Hetzners  Storage Boxes due to the fact that they have rsync only available on port 23. Port 22 only supports SCP and SFTP. Port 23 supports SCP, SFTP, RSYNC and BorgBackup.

Best Regards

**Comment by captainwasabi** [comment]
I'd definitely like to have the port configurable too.  While security by obscurity isn't enough, it is a part of a defense in depth.  Yes, firewall limits and fail2ban take care of the problem, but changing the port will knock out hundreds of thousands of attempts.

**Comment by schlypel** [comment]
@edwhardo this is merged in 61 and works now, can this be closed?
Thanks.

**Comment by edwhardo** [comment]
Thanks!
