### ISSUE TITLE
Cannot send emails: "Outbound mail (SMTP port 25) seems to be blocked by your network.…"

### ISSUE THREAD

**Issue by maacpiash** [mail-in-a-box/mailinabox#1928]
Everything has worked out pretty well for me, except for two issues:

- The SSH server on this machine permits password-based login. A more secure way to log in is using a public key. Add your SSH public key to $HOME/.ssh/authorized_keys, check that you can log in without a password, set the option 'PasswordAuthentication no' in `/etc/ssh/sshd_config`, and then restart the `openssh` via '`sudo service ssh restart`'.
- Outbound mail (SMTP port 25) seems to be blocked by your network. You will not be able to send any mail. Many residential networks block port 25 to prevent hijacked machines from being able to send spam. A quick connection test to Google's mail server on port 25 failed.

The first one is probably not a major issue, but the second one is. I can receive emails from the outside, but cannot send any. I can only send emails to myself.

Specifications:
- Bought the domain on GoDaddy. Hostnames and Nameservers are there.
- DNS records are managed on Netlify.

Thanks in advance!

**Comment by SandeepGusain** [comment]
As the error states the probability of SMTP  port being unblocked, have you confirmed the same? Where is you mail server hosted currently?

**Comment by maacpiash** [comment]
@SandeepGusain It used to be on Tutanota, but I have removed Tutanota's MX records and added this new one:
![image](https://user-images.githubusercontent.com/13682652/107940528-79b00880-6fdc-11eb-882c-5e53dbe0935f.png)

As for the port, I ran `ufw status` and it showed the following outupt:
![image](https://user-images.githubusercontent.com/13682652/107940689-bbd94a00-6fdc-11eb-8d20-43eca3cf5ac1.png)

**Comment by maacpiash** [comment]
I ran `mailinabox` again. This was the output:

```sh
Public IP Address: 172.XXX.YYY.ZZ
Public IPv6 Address: XXXX:YYYY::ZZZZ:XXXX:YYYY:ZZZZ
Mail-in-a-Box Version:  v0.52

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Nextcloud is already latest version
No such app enabled: photos
No such app enabled: dashboard
No such app enabled: activity
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...

-----------------------------------------------

Your Mail-in-a-Box is running.

Please log in to the control panel for further instructions at:

https://box.maacpiash.com/admin

If you have a DNS problem put the box's IP address in the URL
(https://172.XXX.YYY.ZZ/admin) but then check the TLS fingerprint:
B1:2C:4E:E3:36:09:6D:E6:4C:7F:DF:98:75:17:3A:21:B2:50:03:A8:CE:B3:DD:A7:E5:B7:AE:6F:06:52:CF:EA
root@box:~#
```

The issue still remains.

**Comment by anoma** [comment]
You redacted the second octet of `Public IP Address: 172.XXX.YYY.ZZ` but the `172` makes me suspicious that is not a public IP address.

If it is in the range `172.16.0.0 – 172.31.255.255` it is a private address

**Comment by maacpiash** [comment]
@anoma that is the IP address I use to `ssh` into my box.

**Comment by ddavness** [comment]
Digging a little bit:
- Querying the A record on `box.maacpiash.com` returns `172.105.16X.YYY` - the second and third octets are important.
- Querying the IP on a BGP database, for example, Hurricane Electric, tells us that this IP is owned by Linode - https://bgp.he.net/net/172.105.160.0/19

If I recall correctly, Linode started to block outbound port 25 on their end for new users (i.e. who signed up after a certain date) - this is a common practice from some VPS providers to deter spammers, and the only way to resolve this is opening a support ticket requesting the port to be unblocked.

**Comment by maacpiash** [comment]
@ddavness Yes, my VPS is hosted on Linode. I will open a support ticket. Thank you!

**Comment by maacpiash** [comment]
@ddavness This solved my problem quite easily. Thank you so much!
