### ISSUE TITLE
RoundCube Security update 1.4.11

### ISSUE THREAD

**Issue by ccooll** [mail-in-a-box/mailinabox#1931]
There has been a security update for roundcube : 
https://roundcube.net/news/2021/02/08/security-update-1.4.11

I don't know the impact, but could be looked into.

Best Regards,

**Comment by davDevOps** [comment]
Submitted a PR for this Update earlier this Afternoon, so we should be good once approved

**Comment by JoshData** [comment]
Done in 055ac076630241afe3464c09e2dd37886a497a47. Thanks.
