### ISSUE TITLE
Allow Opt-In for extra Nextcloud Features

### ISSUE THREAD

**Issue by jzaia18** [mail-in-a-box/mailinabox#1936]
On closing #1864 it would seem that mail-in-a-box removed the Nextcloud dashboard and file syncing features. I understand these are not explicitly supported mail-in-a-box features as Nextcloud is only supported for use with contacts and calendar, but it would be nice to have an "opt-in" button for these features on the install script. Personally, I find these features work perfectly right out the box and I don't mind fixing problems as they come. I'd imagine I'm not the only one in this camp so it would be nice to have a checkbox on the install script that says something to the effect of "Opt-in to additional Nextcloud functionality (NOTE: not officially supported, use at your own risk)" .

**Comment by JoshData** [comment]
No, sorry. I won't accept changes that are "use at your own risk".
