### ISSUE TITLE
Externally managed email with MTA-STS

### ISSUE THREAD

**Issue by chr-1x** [mail-in-a-box/mailinabox#1937]
Going to preface this with: this is probably not a standard MIAB use-case and I understand if you don't want to support this configuration; I can work around the problem but I might drop some mail for a few days and I'd rather not if there's an alternative.

I use MIAB to manage DNS, but not mail, for two domains which I instead configured as ProtonMail custom domains. That is, I have custom DNS MX records configured in MIAB for these domains pointing to protonmail's servers, as well as all the necessary security glue records that ProtonMail requires for custom domains.

https://github.com/mail-in-a-box/mailinabox/pull/1731 added support for publishing MTA-STS information for all domains "that we are expecting to be handling email for." Unfortunately, the only way to manage DNS for a domain in MIAB is by adding an email user or alias for that domain, thus making "all domains we are expecting to be handling email for" equivalent to "all domains we are managing DNS for" from the user's perspective.

Consequently, after I updated to MIAB 0.52, suddenly I stopped getting email from certain mail servers (notably gmail) because MIAB is publishing MTA-STS info that conflicts with my custom MX record. In particular, gmail will bounce the email back to the sender with the message: "The MX host does not match any MX allowed by the STS policy.".

IMO, there's a simple fix. MIAB should be able to tell that I'm managing my email with an external provider due to my setting an MX record in the custom DNS configuration. In this case, it should generate an appropriate `.well-known/mta-sts.txt` that agrees with my custom MX record(s). 

The longer term solution might be to explicitly handle the case of managing DNS, but not mail, for a domain. However I understand if that might be outside mailinabox's scope 🙂.

**Comment by chr-1x** [comment]
Ah I've just found https://github.com/mail-in-a-box/mailinabox/issues/1782, this is probably a duplicate

**Comment by JoshData** [comment]
Right.
