### ISSUE TITLE
errors for additional domains are not really errors, are they?

### ISSUE THREAD

**Issue by aristosv** [mail-in-a-box/mailinabox#1938]
First I would like to say, great work on MiaB. Especially the "System Status Checks" and "External DNS" pages, makes it perfect for setting up correct DNS records and making sure the server is properly configured.

But once the **first domain** is set up correctly and all the checks are green, is there a reason the **additional domains** have so many errors, that are not really errors?

Why does MiaB think that it's an error if I'm using my registrar's DNS and I host my websites (A) on shared hosting providers? Also when using my registrar's DNS, there's no way I can set a DNSSEC record (at least on name.com).

I understand that, me knowing that it's not really a problem makes it ok. But does it have to show red X's and red messages, as if there's something horribly wrong with my configuration? Shouldn't those messages be informative, or at least warnings?

![Greenshot 2021-03-06 14 05 30](https://user-images.githubusercontent.com/528302/110206201-07b53b80-7e85-11eb-9e48-0cddf1e9c852.png)

**Comment by jvolkenant** [comment]
From the image above, you do not have your nameservers pointed to 104.207.131.45 since you are using external namesevers (or just haven't changed it yet).  I suggest going over the guide at https://mailinabox.email/guide.html

**Comment by jvolkenant** [comment]
Checking the domains, you may have already set the external dns entries for wviiv.com, in that case, those will always show as red since the MIAB assumes it would be doing dns for the domains it hosts.

**Comment by aristosv** [comment]
Why would a mail server assume that it's responsible **for all the DNS records for all my domains**? I understand the need to do it for the first domain, but why all the rest?

I don't need it to host my domains. My registrar does that. I just need it to be **responsible for the email** for those domains.

No need to handle nameservers or A records. The registrar is perfect for that.

**Comment by JoshData** [comment]
> Why would a mail server assume that it's responsible for all the DNS records for all my domains?

Because that's what our setup guide directs people to set up.

> I just need it to be responsible for the email for those domains.

No one is forcing you to use Mail-in-a-Box.

**Comment by aristosv** [comment]
> > Why would a mail server assume that it's responsible for all the DNS records for all my domains?
> 
> Because that's what our setup guide directs people to set up.
> 
> > I just need it to be responsible for the email for those domains.
> 
> No one is forcing you to use Mail-in-a-Box.

No need for hostility. This is actually constructive criticism. MiaB is a very good product. I think this would make it better.

**Comment by JoshData** [comment]
You think what would make it better?

**Comment by JoshData** [comment]
The first error is a critical error for anyone following this project's documented setup procedure.

The second two errors (about A records) can be changed to warnings - I would accept a pull request for that.

**Comment by aristosv** [comment]
The first error is applicable for the primary domain only. Not the secondary domains.

Forcing multiple domain's nameservers to be served by a mail server doesn't make sense. The mail server should be concerned with email functionality

1. 'MX' records
2. 'A' records for:
     - autoconfig
     - autodiscovery
     - webmail (if needed)
3. Multiple 'TXT' records for:
    - policies
    - spam filtering
    - whatever else

Changing a domain's nameservers to simply facilitate email functionality does not make sense. The name servers can stay on the registrar, where DNS records can be created for email functionality. 

I've read the setup guide multiple times and I still don't see a technical reason to point a **secondary** domain's name servers on the mail server.

Perhaps I'm lacking the knowledge, so some feedback would be appreciated.

**Comment by JoshData** [comment]
> Changing a domain's nameservers to simply facilitate email functionality does not make sense.

It makes sense to a lot of people using this project because it is easier to set up and achieve reliable email with minimal maintenance. This is not up for debate, and this is the main thrust of this issue, so I am closing and locking this issue. No one's got time for a fake conversation around what makes sense and what doesn't make sense to you.
