### ISSUE TITLE
MIAB Management UI

### ISSUE THREAD

**Issue by tranquilo** [mail-in-a-box/mailinabox#1939]
Hi,
Is the project open to contributions on the Management UI?
I feel maybe we could give it a little love.
Good job with the project btw.

Thanks

**Comment by JoshData** [comment]
We're open to contributions everywhere as long as the contribution supports the mission of the project and doesn't make maintaining this project harder. So, for example, cosmetic changes that don't improve the usability of the UI but create a new burden for maintaining the HTML/CSS would not be accepted.
