### ISSUE TITLE
DNSSEC specification recommends not signing with DNSSEC algorithm 7 (RSASHA1NSEC3SHA1)

### ISSUE THREAD

**Issue by myfirstnameispaul** [mail-in-a-box/mailinabox#1953]
When looking at some DNSSEC records at [dnsviz.net](https://dnsviz.net), I noticed the following warning with MiaB servers:

> RRSIG example.com/A alg 7, id 18734: DNSSEC specification recommends not signing with DNSSEC algorithm 7 (RSASHA1NSEC3SHA1).

I'm a little outside my comfort zone for proposing a config, but I do see that algorithm 13 is used by Cloudflare and Namecheap.

Here is the IANA list of of Algorithm numbers [1]:

Number | Description | Mnemonic | ZoneSigning | Trans.Sec.
-- | -- | -- | -- | -- |
0 | Delete DS | DELETE | N | N | 
1 | RSA/MD5 (deprecated, see 5) | RSAMD5 | N | Y | 
2 | Diffie-Hellman | DH | N | Y | 
3 | DSA/SHA1 | DSA | Y | Y | 
4 | Reserved |   |   |   |
5 | RSA/SHA-1 | RSASHA1 | Y | Y | 
6 | DSA-NSEC3-SHA1 | DSA-NSEC3-SHA1 | Y | Y |
7 | RSASHA1-NSEC3-SHA1 | RSASHA1-NSEC3-SHA1 | Y | Y | 
8 | RSA/SHA-256 | RSASHA256 | Y | * | 
9 | Reserved |   |   |   | 
10 | RSA/SHA-512 | RSASHA512 | Y | * | 
11 | Reserved |   |   |   | 
12 | GOST R 34.10-2001 | ECC-GOST | Y | * |
13 | ECDSA Curve P-256 with SHA-256 | ECDSAP256SHA256 | Y | * |
14 | ECDSA Curve P-384 with SHA-384 | ECDSAP384SHA384 | Y | * |
15 | Ed25519 | ED25519 | Y | * | 
16 | Ed448 | ED448 | Y | * | 
17-122 | Unassigned |   |   |   |  
123-251 | Reserved |   |   |   | 
252 | Reserved for Indirect Keys | INDIRECT | N | N | 
253 | private algorithm | PRIVATEDNS | Y | Y | 
254 | private algorithm OID | PRIVATEOID | Y | Y | 
255 | Reserved |   |   |   | 

\* There has been no determination of standardization of the use of this algorithm with Transaction Security.

[1] https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml

**Comment by JoshData** [comment]
Each TLD and registrar support a different subset of the algorithms and it's a moving target --- at least, this was true when I added DNSSEC to Mail-in-a-Box originally. RSASHA1-NSEC3-SHA1 appeared to be the most supported algorithm at the time.

I would be happy to target a newer algorithm.

But we also have to be careful about not breaking anyone's existing DNSSEC configuration.

**Comment by myfirstnameispaul** [comment]
I've gone about as far on researching this as I am able.

Cloudflare DNSSEC is now exclusively algorithm 13. Their page [Understanding and configuring DNSSEC in Cloudflare DNS](https://support.cloudflare.com/hc/en-us/articles/360006660072#h_54ExRbSpzRaSHdIZa7l1Sp) includes an overview and discussion on their service as well as what to do when a registrar does not support DNSSEC or algorithm 13, and they even go so far as to recommend reporting the registrar to ICANN with a link to the ICANN complaint page, as registrars are required to support DNSSEC. (I find this at least somewhat hypocritical, as ICANN also states that algorithm 8 is `MUST`, but I digress.)

The above linked page also includes a list of registrars and instructions on how to enable DNSSEC with those registrars. It is the best list like this I have discovered, though it is obviously very incomplete.

There is also a post in the Cloudflare community forums that includes a discussion on algorithm 8 and a response from a team member: [DNSSEC Algorithm 8](https://community.cloudflare.com/t/dnssec-algorithm-8/254268). It seems noteworthy that dropping algorithm 8 generated only one post to the Cloudflare community forums that I can find.

The [Root Canary](https://rootcanary.org/) project links to the [NLnet Labs' DNSthought platform](https://dnsthought.nlnetlabs.nl/), which includes reports on resolver support for DNSSEC algorithms. According to the reports, [algorithm 7](https://dnsthought.nlnetlabs.nl/can_rsansec3/) supported by 11,050 resolvers, [algorithm 8](https://dnsthought.nlnetlabs.nl/can_rsasha256/) by 14,522 resolvers, and [algorithm 13](https://dnsthought.nlnetlabs.nl/can_ecdsa256/) by 13,977 resolvers. >75% of the algorithm 8 and 13 resolvers support algorithm 7; >98% of algorithm 7 resolvers support 8 and 13; >95% of algorithm 8 resolvers support 13; and >99% of algorithm 13 resolvers support 8.

It seems like if there is a disparity where resolvers are not supporting an algorithm, then the registrar support may not be the only factor in deciding on an algorithm.

My best guess at this point is that using algorithm 8 may be only slightly more available than 13, and 7 seems to actually be on its way out. However, given that Cloudflare recently (March 2021) began supporting algorithm 13 exclusively, this will likely put more pressure on registrars to support algorithm 13, if they don't already. This with the resolver data, and it may be that algorithm 13 is a better option than algorithm 8 since support appears similar and algorithm 13 will likely be supported longer by the RFC.

**Comment by JoshData** [comment]
That's really helpful. I've worked on this issue today and I'll push a commit tomorrow that hopefully addresses this by encouraging users to migrate to algorithm 13 by 1) signing zones with algorithms 7 (for existing MiaB boxes), 8, and 13 simultaneously, and 2) providing a warning in the status checks for users not using algorithm 13 (which would be everyone that has DNSSEC activated).

**Comment by JoshData** [comment]
Pushed, see 8cda58f. I hope this works! I've updated a few of my domains to ECDSAP256SHA256 and hopefully everything is valid. I tested with `drill -DT domain` but real-world evidence would be good...

(Also note that I have just renamed the master branch to `main`.)

**Comment by myfirstnameispaul** [comment]
Wow, awesome. I can test with a test domain in a week or so, but not at this moment.

**Comment by jvolkenant** [comment]
Updated my box with a newer DNSSEC key, added "DOMAINS=none" to cat /home/user-data/dns/dnssec/RSASHA1-NSEC3-SHA1.conf, dnsvis is happy.

**Comment by JoshData** [comment]
Great!
