### ISSUE TITLE
Supporting POP 110 (non-TLS)

### ISSUE THREAD

**Issue by acicali** [mail-in-a-box/mailinabox#1957]
Just wanted to mention this here in case anyone is in need of hosting insecure POP on port 110.

Before you slap me... my use of mail-in-a-box was to support a legacy software integration in which data is exchanged via a shared email account (I know, it's gross). This software was outside of my control. Mail-in-a-box worked like a charm, but I had to dig a little to learn how to enable insecure POP.

So... if you need to support it as well:

1. write the below config to /etc/dovecot/local.conf
2. service dovecot restart
3. ufw allow 110 && sudo ufw reload

```
service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    #port = 995
    #ssl = yes
  }
}
```

**Comment by myfirstnameispaul** [comment]
It seems the forums recently had a [Guides category](https://discourse.mailinabox.email/c/guides/10) added, and this seems like the sort of thing that would be useful there.

**Comment by jvolkenant** [comment]
This exposes communication without encryption. I would not recommend this.

**Comment by myfirstnameispaul** [comment]
I didn't perceive the intent was to recommend this for all installations. However, there are many cases where this is a desirable solution. Probably the best example is when install on local hardware (commonly replacing an Exchange server) a local device (e.g., printer) is no longer able access the mail server because it doesn't support modern encryption protocols, assuming it ever supported any protocols.

**Comment by rfrush** [comment]
The original author (acicali) didn't seem to suggest this should be a change to MIAB, but was helpfully offered up as a workaround for a thorny legacy support issue.   POP really doesn't have a place in a modern IT shop, but not everyone can afford to get all their systems/printers/whatever updated.

I wish more of these type of "Issues" were posted in https://discourse.mailinabox.email instead as Paul suggested above.

I would propose closing this issue, as it's not suggesting any changes to MIAB code.
