### ISSUE TITLE
Using 'apt' or 'apt-get' reports different upgrade options.

### ISSUE THREAD

**Issue by myfirstnameispaul** [mail-in-a-box/mailinabox#1962]
Throughout the install code of MiaB I find `apt-get` is the command used, so that's what I've always run.

Without going into my personal history as to why I do this, just to state that on my other servers I use `aptitude` and they all have zero available packages to be upgraded. In my world, the `apt` command still feels new so I haven't been using it. To summarize: I don't know a whole lot about the differences in these commands.

Right now, I get the following on my MiaB (which, BTW, is still .52):
```
$ sudo apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libnetplan0 motd-news-config
The following packages will be upgraded:
  base-files netplan.io ubuntu-server
3 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 161 kB of archives.
After this operation, 185 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
$ sudo apt-get upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  base-files netplan.io ubuntu-server
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```
Should I continue using `apt-get upgrade`?

**Comment by downtownallday** [comment]
FWIW, I'd leave apt-get in the scripts. apt is okay for interactive use. From 'man apt":

The apt(8) commandline is designed as an end-user tool and it may change behavior
       between versions. While it tries not to break backward compatibility this is not
       guaranteed either if a change seems beneficial for interactive use.

apt-get upgrade requires using --with-new-pkgs (in the example above), but apt includes automatically.

**Comment by myfirstnameispaul** [comment]
Thank for that.

So in the context of managing the server, using `apt` is the better tool?

**Comment by downtownallday** [comment]
I guess it's a personal preference. apt will be more friendly.

**Comment by ddavness** [comment]
`apt` and `apt-get` are functionally the same. However, `apt-get` has a stable interface which makes it better for scripts (i.e. command line options won't change from one day to another), while `apt` is, as said already, focused on usability/interactive use.

The TLDR of this is that `apt-get` is the way to go when writing the bootstrap scripts.
