### ISSUE TITLE
B2 Backblaze: I get the error message:“substring not found”.

### ISSUE THREAD

**Issue by JvdBBBB** [mail-in-a-box/mailinabox#1964]
I get the error message:“substring not found” when I try to configure MIAB backup to use B2 Backblaze.

I have created an appkey in Backblaze and used my key ID and application Key in MIAB.

Also I am not so sure what to set in “B2 Bucket”, I have tried a lot of combinations

- s3.us-west-000.backblazeb2.com/bucketname
- bucketname
- s3.us-west-000.backblazeb2.com/buckedID
- etc.

but everything I try gives the same error message.

**Comment by aaronmweiss** [comment]
I too am receiving the same issue and had initially created a thread on the [Discourse fourm](https://discourse.mailinabox.email/t/adding-backblaze-backup-substring-not-found/7930/2). 

I'm positive my keys and ID are working because I currently have a script working to B2 sending the backup files already. I'm looking forward using this within MiaB itself.

**Comment by JvdBBBB** [comment]
I have generated new keys and now it works.
The old application key had "/" in it, maybe that had something to do with it?

**Comment by gumida** [comment]
> I have generated new keys and now it works.
> The old application key had "/" in it, maybe that had something to do with it?

I've noticed the same. Wasn't working until I've got an key without a slash in it.

**Comment by aaronmweiss** [comment]
I can confirm that generating a new key that does not have a "/" in it corrected the issue.

**Comment by yashjain0** [comment]
I read the documents of Backblaze and found that names can contain letters, numbers, and "-", and are limited to 100 characters.

**Comment by TomBuyvoets** [comment]
For me is a key with a `/` also not working. After creating multiple keys until I had one without a `/` fixed this specific issue. Now I have a new issue. Will create a new issue for that.

**Comment by kappuchino** [comment]
Problem persists. I had this error message, found about the issue via google. I, too, have a key with a slash. New key without worked. Please add check for slashes in key and advise to regen or escape the slash for use. (BTW: Thanks for this great software)

**Comment by dmytrokyrychuk** [comment]
#2281 contains a possible solution to this problem. I have tested the PR by adding new key with a slash, and running `sudo management/backup.py` manually.
