### ISSUE TITLE
Certbot PPA deprecated

### ISSUE THREAD

**Issue by myfirstnameispaul** [mail-in-a-box/mailinabox#1971]
I just looked at the [Certbot PPA](https://launchpad.net/~certbot/+archive/ubuntu/certbot) and saw:

> The PPA has been DEPRECATED.
> 
> To get up to date instructions on how to get certbot for your systems, please see https://certbot.eff.org/docs/install.html.

Don't know that this is an actual "issue" but thought I'd post as at least an FYI.

The Ubuntu main repository version for [bionic-updates](https://packages.ubuntu.com/bionic-updates/certbot) is .27 and the latest for [focal-updates](https://packages.ubuntu.com/focal-updates/certbot) is .40, and master on the project GitHub is 1.15.

Here is the changelog up through master: https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md

There also seems to be well supported project that is a shell script: [acme.sh](
https://github.com/acmesh-official/acme.sh).

**Comment by jvolkenant** [comment]
Could likely retire the PPA when we move to 22.04.  If we retire it now, we would be using an older version of certbox (which might not be a problem depending on what of certbot we use), looks like 22.04 has a newer version than what is in PPA right now anyway.

**Comment by Synchro** [comment]
I admit to being quite anti-snaps in the past, however, I've found that certbot in particular is far more reliable with it. The main advantages I see (since we are on Ubuntu):

* it's officially certbot's  preferred installation method
* updates are not tied to Ubuntu's release schedule, of particular note since MIAB skips alternate LTS releases.
* it provides some improvements in isolation relative to deb-based installation, so improves security. PPAs are mostly pushing in the the opposite direction.

The plumbing amounts to installing snapd, which may have other deps – I've not looked at that too closely.

The problem I've had most often with certbot is the cron jobs failing for renewals and self-updates, usually because of frequent changes in packaging that certbot has had in the past! I have suffered none of these issues with the snap installs.

As for what's different in newer versions, it's [mostly bug fixes and security updates](https://github.com/certbot/certbot/releases), which we should be installing anyway, plus it occasional new features.

I appreciate that MIAB doesn't need more than is necessary, but here my experience of snaps for certbot suggests they may offer the path of least resistance.

**Comment by myfirstnameispaul** [comment]
Just wondering if anyone has any opinions on acme.sh? I've got it on an OpenBSD server so I can have automated wildcard cert renewals, though I don't know if newer versions of certbot offer the same feature. It's been working as advertised.

**Comment by wxs4274** [comment]
This appears to cause new installs to fail.. To work around this I preformed the following:
<code>
sudo apt-get install snap
sudo snap install certbot --classic
</code>

Then commented out the following from the setup/system.sh:
<code>
hide_output apt-add-repository -y ppa:certbot/certbot
</code>

Install succeeded, and certbot functionality appears intact.

**Comment by myfirstnameispaul** [comment]
Can you share the error?

**Comment by wxs4274** [comment]
Sorry, install was done on console with no scroll back.

Preforming install attempt in VM did not reproduce this behavior, indicating that it may have been an extended temporary issue.

Seems this was a general timeout just after the hostname/primary email selection, after it printed hostname, external IPs, and version (0.53a). It hung there for ~5 minutes and exited with:
`error retrieving gpg key timed out`

Tried 3/4 times..

This lead me to run the following (excluding the -y):
`sudo apt-add-repository ppa:certbot/certbot`

Which returned the following:

>  The PPA has been DEPRECATED.
>
>To get up to date instructions on how to get certbot for your systems, please see https://certbot.eff.org/docs/install.html.
> More info: https://launchpad.net/~certbot/+archive/ubuntu/certbot
>Press [ENTER] to continue or Ctrl-c to cancel adding it.
>
>Error: retrieving gpg key timed out.
>

That is when I found this issue, and decided to try to work around it using snap as recommended here:
https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

**Comment by JoshData** [comment]
The pip installation instructions might be our best way forward: https://certbot.eff.org/lets-encrypt/pip-nginx. I also really dislike snaps.

**Comment by myfirstnameispaul** [comment]
That seems like an excellent solution. As obvious as it seems, I hadn't thought to go looking for a different method of installing `certbot`. So basically just remove the PPA, install with `pip` and add somewhere in the maintenance scripts a `pip install certbot -U`.

In looking through all of this, I've also noticed that Cloudflare is using ECDSA keys on all of their certs, which is now supported by `certbot`.

Also, one of the reasons I was looking more into acme.sh is they offer automated DNS-01 certs and have a script for [MiaB](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_miab.sh), should we ever decide to use wildcard certs with MiaB.

However, what I am concerned for both ECDSA and wildcard certs is support from many of the various sending servers that may not be able to use such certs. Probably wait another 10 years? Sometimes I think it is better to leave them behind, but I digress.

**Comment by BloodyIron** [comment]
Hi Folks,

I have to say that I'm actually completely gobsmacked that nobody seems to see the value in a repo/ppa for certbot in this, or other related issue disucssions for certbot.

I know that snapd and pip can work for many, but there are very reasonable scenarios where that is an unacceptable option. The way my ecosystem works, we centrally manage software with aptitude, and are working towards doing that moreso with landscape. This means deb packages, and not snapd, or pip. Furthermore, all other software installed in our ecosystem leverages the same package manager ecosystem (aptitude/deb packaging). So snapd and pip is a non-option. But we still need certbot to do Let's Encrypt cert issuance.

The primary system that's relevant in our case is running Ubuntu 18.04, which has a highest certbot of 0.31 available to it, and even from the main repos for 20.04, it is I believe 0.40. NEITHER of which is v1.6.0, which makes the "--preferred-chain "ISRG Root X1"" function available, which is expected to solve a cert issue we're having right now. I have to upgrade certain systems to 21.04 just to get v1.12.0 available! That's a 6-mo release, not a LTS/Long-Term-Support version.

Any other software we work with, we get updates through the mainline repos, or we add a ppa to get even newer versions. This WORKS. This is reliable. Snapd and pip does not work for how we manage software.

So when I go and discover that not only are the main repos this way, and then the certbot github discussions are talking about "depricating repos for 22.04" my jaw drops.

PLEASE. I BEG YOU. Do NOT abandon repos for certbot. Many sys admins globally still need this served through repos! And a maintained and updated ppa would help many people massively! Please reverse this decision! :(

**Comment by jvolkenant** [comment]
@BloodyIron We don't have anything to do with the Certbot PPA.

FWIW, 22.04 has Certbot 1.21 in the Ubuntu Repo's so Certbot ppa isn't really needed past 18.04

**Comment by myfirstnameispaul** [comment]
At this moment, it seems like this project support might be marginally in favor of using PIP for certbot.

**Comment by BloodyIron** [comment]
> @BloodyIron We don't have anything to do with the Certbot PPA.
> 
> FWIW, 22.04 has Certbot 1.21 in the Ubuntu Repo's so Certbot ppa isn't really needed past 18.04

20.04 doesn't have anything higher than 0.40 last I checked. So the PPA for 18.04 and 20.04 need to be updated with latest versions (or at least v1.6.0) of certbot in order to actually be able to issue trustable certs.

**Comment by myfirstnameispaul** [comment]
It looks like 22.04 will have the latest version of `certbot`, but this was true for previous LTS versions when the versions were released.

The `certbot` package is in `universe` which means community managed, so likely only to get updates until the first interim release, after which it will be stuck again.

Would it be better to move to PIP for 22.04?

**Comment by BloodyIron** [comment]
Pulling software out of the package manager ecosystem makes system administration more costly to centrally manage across many systems. That's the whole point of using aptitude. Having PIP as an option is one thing, having it be the only way is unacceptable.

**Comment by myfirstnameispaul** [comment]
@BloodyIron The Mail-in-a-Box project does not manage the package repos or PPAs for `certbot`. What happens there is beyond our control, as already stated above.

The EFF project maintains the PIP package directly, so it is still an official source for the package, as already stated above.

**Comment by myfirstnameispaul** [comment]
I just noticed in reviewing the changelogs it appears that `certbot` received life-support updates on both [18.04](https://changelogs.ubuntu.com/changelogs/pool/universe/p/python-certbot/python-certbot_0.27.0-1~ubuntu18.04.2/changelog) and [20.04](https://changelogs.ubuntu.com/changelogs/pool/universe/p/python-certbot/python-certbot_0.40.0-1ubuntu0.1/changelog) `main`, including support for ACMEv2, but this didn't upgrade the version.

**Comment by rfrush** [comment]
It is common for packages in a repo to get back-ports of changes from the upstream project without changing the major version number to keep the repository version numbers consistent for a particular release (18.04, 20.04, etc) as it is customary that for a particular repository version, that the package  major versions in the repo don’t change.

Unless there’s an indication that the debian/ubuntu certbot package maintainers are not keeping the package up to date for LTS releases, my opinion is to use the distribution package version instead of a more complex process of managing certbot via pip.

**Comment by JoshData** [comment]
Let me put an end to this. 😀 When we move to 22.04 we'll use the Ubuntu package, and if it stops working at some point then we'll consider other options.

**Comment by myfirstnameispaul** [comment]
Here is what updates to 18.04 look like in the changelog:

> python-certbot (0.27.0-1~ubuntu18.04.2) bionic; urgency=medium
> 
>   * Interpret the Let's Encrypt ACMEv1 endpoint in renewal configs as Let's
>     Encrypt's ACMEv2 endpoint instead, as the former is deprecated and will
>     stop being functional soon (LP: #1893274).
> 
>  -- Robie Basak <robie.basak@ubuntu.com>  Tue, 27 Oct 2020 16:00:51 +0000
> 
> python-certbot (0.27.0-1~ubuntu18.04.1) bionic; urgency=medium
> 
>   * Backport to bionic (LP: #1837673):
>     - d/letsencrypt.postrm: purging the transitional package shouldn't
>       remove the logs (Closes: #921423)
> 
>  -- Andreas Hasenack <andreas@canonical.com>  Thu, 10 Oct 2019 20:57:31 +0000
> 
> python-certbot (0.27.0-1) unstable; urgency=medium
> 
>   * New upstream version 0.27.0
>   * Refresh patch after upstream migration to codecov
>   * Bump python-sphinx requirement defensively; bump S-V with no changes
>   * Bump dep on python-acme to 0.26.0~
>  -- Harlan Lieberman-Berg <hlieberman@debian.org>  Wed, 05 Sep 2018 20:29:44 -0400

I think the update to .27 was coincidental timing as `certbot` was updated just before 18.10 release. The question seems to be whether we just want to live with the features frozen after September and rely on the `certbot` package maintainers to provide the most critical updates, which historically they have done.

BTW, I'm fine with either, but prefer not to use deprecated by project, as we ended up in with the PPA (the original reason for this issue).
