### ISSUE TITLE
Z- push failing in installation

### ISSUE THREAD

**Issue by vishnukv64** [mail-in-a-box/mailinabox#1974]
Hey guys, 
i dont know why z-push is failing, so when i checked the link ( the link is broken )
![Screenshot from 2021-05-06 02-13-01](https://user-images.githubusercontent.com/33051467/117206657-bdaeee80-ae10-11eb-9337-a7888c1a0119.png)

**Comment by 494029a** [comment]
I have the same problem :/

**Comment by jvolkenant** [comment]
The link is broken because the host is down. This has happened with the nextcloud URL's. I recommend trying again later.

```
root@pdxutil:/data/Applications# dig stash.z-hub.io

; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> stash.z-hub.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8023
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;stash.z-hub.io.                        IN      A

;; ANSWER SECTION:
stash.z-hub.io.         7181    IN      A       195.201.215.164

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Wed May 05 15:36:55 PDT 2021
;; MSG SIZE  rcvd: 59

root@pdxutil:/data/Applications# nmap -p443 stash.z-hub.io

Starting Nmap 7.60 ( https://nmap.org ) at 2021-05-05 15:37 PDT
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 2.99 seconds

```

**Comment by GedMarc** [comment]
Same :(

**Comment by GedMarc** [comment]
Sigh... 

https://www.isitdownrightnow.com/stash.z-hub.io.html

**Comment by vishnukv64** [comment]
Worst possible time .. Sigh !!!!!

**Comment by kriball** [comment]
Ahh, I just upgrade one of my server and got this error too, host is down.
I will waiting for new next update.

Send and receive mail still normal.

**Comment by vijaymishra1105** [comment]
> Sigh...
> 
> https://www.isitdownrightnow.com/stash.z-hub.io.html

When this is going to be resolved?

**Comment by kriball** [comment]
> > Sigh...
> > https://www.isitdownrightnow.com/stash.z-hub.io.html
> 
> When this is going to be resolved?

Depending on z-host.io, if they want to up their host, then this problem should be mark as solved.

**Comment by vijaymishra1105** [comment]
Guys, I am totally new to github. 

I need step by step instructions to make a email server on VPS which has IP rotation facility. Any body who can guide me?

**Comment by vijaymishra1105** [comment]
and also I need to build 3 to 5 email server on VPS. Mailinabox previously was having problem of nextcloud & now zpush. Can anybody suggest me quality email server other than mailinabox. I can't wait any further.

**Comment by JoshData** [comment]
@vijaymishra1105 This is not the appropriate place to be asking for generic help. This page is for a specific issue that people are dealing with. The appropriate place to ask for help is on the Mail-in-a-Box forum.

**Comment by lorena1976** [comment]
> 

> > @vijaymishra1105 This is not the appropriate place to be asking for generic help. This page is for a specific issue that people are dealing with. The appropriate place to ask for help is on the Mail-in-a-Box forum.
> 
> Ok. Josh. I am a huge fan of yours & following you for long. I am redirecting to Mail-in-a-Box forum

**Comment by vijaymishra1105** [comment]
> Why not configure MiaB to download directly from the Z-Hub/Z-Push GitHub?

will you please be able to give step by step command to do so

Thanks

**Comment by myfirstnameispaul** [comment]
@vijaymishra1105 

There is a running thread in the MiaB forums with a user reporting a successful method. My question here in GitHub is about modifying the MiaB install code.

https://discourse.mailinabox.email/t/installation-fails-failed-wget-o-tmp-z-push-zip-https-stash-z-hub-io/8018/6

**Comment by elliryc-niamreg** [comment]
#!/bin/bash
#
# Z-Push: The Microsoft Exchange protocol server
# ----------------------------------------------
#
# Mostly for use on iOS which doesn't support IMAP IDLE.
#
# Although Ubuntu ships Z-Push (as d-push) it has a dependency on Apache
# so we won't install it that way.
#
# Thanks to http://frontender.ch/publikationen/push-mail-server-using-nginx-and-z-push.html.

source setup/functions.sh # load our functions
source /etc/mailinabox.conf # load global vars

# Prereqs.

echo "Installing Z-Push (Exchange/ActiveSync server)..."
apt_install \
	php-soap php-imap libawl-php php-xsl

phpenmod -v php imap

# Copy Z-Push into place.
VERSION=2.6.2
TARGETHASH=f0e8091a8030e5b851f5ba1f9f0e1a05b8762d80
needs_update=0 #NODOC
if [ ! -f /usr/local/lib/z-push/version ]; then
	needs_update=1 #NODOC
elif [[ $VERSION != $(cat /usr/local/lib/z-push/version) ]]; then
	# checks if the version
	needs_update=1 #NODOC
fi
if [ $needs_update == 1 ]; then
	# Download
	wget_verify "https://github.com/Z-Hub/Z-Push/archive/refs/tags/2.6.2.zip" $TARGETHASH /tmp/z-push.zip

	# Extract into place.
	rm -rf /usr/local/lib/z-push /tmp/z-push
	unzip -q /tmp/z-push.zip -d /tmp/z-push
	 mv /tmp/z-push/Z-Push-2.6.2/src /usr/local/lib/z-push
	rm -rf /tmp/z-push.zip /tmp/z-push

	rm -f /usr/sbin/z-push-{admin,top}
	ln -s /usr/local/lib/z-push/z-push-admin.php /usr/sbin/z-push-admin
	ln -s /usr/local/lib/z-push/z-push-top.php /usr/sbin/z-push-top
	echo $VERSION > /usr/local/lib/z-push/version
fi

# Configure default config.
sed -i "s^define('TIMEZONE', .*^define('TIMEZONE', '$(cat /etc/timezone)');^" /usr/local/lib/z-push/config.php
sed -i "s/define('BACKEND_PROVIDER', .*/define('BACKEND_PROVIDER', 'BackendCombined');/" /usr/local/lib/z-push/config.php
sed -i "s/define('USE_FULLEMAIL_FOR_LOGIN', .*/define('USE_FULLEMAIL_FOR_LOGIN', true);/" /usr/local/lib/z-push/config.php
sed -i "s/define('LOG_MEMORY_PROFILER', .*/define('LOG_MEMORY_PROFILER', false);/" /usr/local/lib/z-push/config.php
sed -i "s/define('BUG68532FIXED', .*/define('BUG68532FIXED', false);/" /usr/local/lib/z-push/config.php
sed -i "s/define('LOGLEVEL', .*/define('LOGLEVEL', LOGLEVEL_ERROR);/" /usr/local/lib/z-push/config.php

# Configure BACKEND
rm -f /usr/local/lib/z-push/backend/combined/config.php
cp conf/zpush/backend_combined.php /usr/local/lib/z-push/backend/combined/config.php

# Configure IMAP
rm -f /usr/local/lib/z-push/backend/imap/config.php
cp conf/zpush/backend_imap.php /usr/local/lib/z-push/backend/imap/config.php
sed -i "s%STORAGE_ROOT%$STORAGE_ROOT%" /usr/local/lib/z-push/backend/imap/config.php

# Configure CardDav
rm -f /usr/local/lib/z-push/backend/carddav/config.php
cp conf/zpush/backend_carddav.php /usr/local/lib/z-push/backend/carddav/config.php

# Configure CalDav
rm -f /usr/local/lib/z-push/backend/caldav/config.php
cp conf/zpush/backend_caldav.php /usr/local/lib/z-push/backend/caldav/config.php

# Configure Autodiscover
rm -f /usr/local/lib/z-push/autodiscover/config.php
cp conf/zpush/autodiscover_config.php /usr/local/lib/z-push/autodiscover/config.php
sed -i "s/PRIMARY_HOSTNAME/$PRIMARY_HOSTNAME/" /usr/local/lib/z-push/autodiscover/config.php
sed -i "s^define('TIMEZONE', .*^define('TIMEZONE', '$(cat /etc/timezone)');^" /usr/local/lib/z-push/autodiscover/config.php

# Some directories it will use.

mkdir -p /var/log/z-push
mkdir -p /var/lib/z-push
chmod 750 /var/log/z-push
chmod 750 /var/lib/z-push
chown www-data:www-data /var/log/z-push
chown www-data:www-data /var/lib/z-push

# Add log rotation

cat > /etc/logrotate.d/z-push <<EOF;
/var/log/z-push/*.log {
	weekly
	missingok
	rotate 52
	compress
	delaycompress
	notifempty
}
EOF

# Restart service.

restart_service php7.2-fpm

# Fix states after upgrade

hide_output z-push-admin -a fixstates

**Comment by elliryc-niamreg** [comment]
Hi, 
I have make a file for the problem:
https://github.com/elliryc-niamreg/Zpush-temp-formailinabox

Replace the zpush.sh in the setup folder.

**Comment by GedMarc** [comment]
You didn't reference the version variable...

**Comment by lorena1976** [comment]
> You didn't reference the version variable...

**Comment by lorena1976** [comment]
![Uploading 5310FED2-4338-47A9-9046-E31F6592AE76 2.jpeg…]()

**Comment by vijaymishra1105** [comment]
> https://github.com/elliryc-niamreg/Zpush-temp-formailinabox

I have used this just now. - https://github.com/elliryc-niamreg/Zpush-temp-formailinabox. It had worked. https://www.isitdownrightnow.com/stash.z-hub.io is still down. Thanks a lot.

My question is if stash.z-hub.io is up will I face any problem running or updating mailinabox.

Thanks again

**Comment by JoshData** [comment]
New release made using the new download link that @elliryc-niamreg found. Thanks!

**Comment by GedMarc** [comment]
you da man Josh!
