### ISSUE TITLE
FYI: Duplicity / Backblaze error

### ISSUE THREAD

**Issue by hija** [mail-in-a-box/mailinabox#1985]
Backblaze did a change to their internal api. Since duplicity used their internal API and the internal API has been changed, this currently breaks the Backblaze and duplicity backup. 
See: https://github.com/Backblaze/b2-sdk-python/issues/251

I see two options:
1. Wait until duplicity fixes their API usage
2. Pin to an older b2sdk version, so duplicity can still use their internal API 

More information: https://whistl.com/2021/05/attributeerror-inmemoryaccountinfo-object-has-no-attribute-get_minimum_part_size/

What do you prefer?

**Comment by hija** [comment]
Has been fixed by duplicity but has not yet been released: https://gitlab.com/duplicity/duplicity/-/commit/718ccc9032008df7b20e766fd197839ba7aa040f (only a snap is available afaik, but not the right one in repo)

**Comment by gumida** [comment]
It seems like it's fixed now, isn't it? https://gitlab.com/duplicity/duplicity/-/blob/master/CHANGELOG.md

I was getting the following error message since the last couple of days:
```
BackendException: Could not initialize backend: No module named 'b2sdk.download_dest'
Something is wrong with the backup: ERROR 23 BackendException
. BackendException: Could not initialize backend: No module named 'b2sdk.download_dest'
```
I really hope, this is gone now after updating duplicity to version 0.8.20 :thinking:

**Comment by hija** [comment]
I don't think so, since the PPA has not yet been updated with the most current duplicity version: https://launchpad.net/ubuntu/+source/duplicity

If you want to fix it yourself for now you could try running

    pip3 uninstall b2sdk b2
    pip3 install b2sdk==1.6.0 b2==1.4.2

Keep in mind this is not supported and you should do a backup before doing this.

**Comment by gumida** [comment]
> I don't think so, since the PPA has not yet been updated with the most current duplicity version: https://launchpad.net/ubuntu/+source/duplicity
> 
> If you want to fix it yourself for now you could try running
> 
> ```
> pip3 uninstall b2sdk b2
> pip3 install b2sdk==1.6.0 b2==1.4.2
> ```
> 
> Keep in mind this is not supported and you should do a backup before doing this.

I think there is something wrong here. According to the duplicity website and to this:
https://github.com/mail-in-a-box/mailinabox/blob/4cb46ea4658b91240c5676c52746e48aaaba7b3f/setup/system.sh#L97
https://code.launchpad.net/~duplicity-team/+archive/ubuntu/duplicity-release-git should be the correct repository.
My system was getting 0.8.20 via this repo last week and everything is working without any issues since.

**Comment by hija** [comment]
My bad - looked into the wrong PPA. But so it's resolved since the 26th of June and we can close this issue :)
Thanks for pointing that out, @gumida
