### ISSUE TITLE
mailinabox is used to create spam accounts on our website

### ISSUE THREAD

**Issue by jodoox** [mail-in-a-box/mailinabox#1992]
Hello, I work for Slite, a collaborative communication tool for remote teams. We're seeing an influx of fake accounts created on our app. For instance, the domains listed in the screenshot below have the `comapny` typo in common and redirect to a "mailinabox" home page (we have many more fake accounts than that, but these were fairly easy to spot). Seems like these accounts are created for SEO purposes given they all share public pages with external links. That's really unfortunate: all these efforts are 100% worthless as we don't allow for web crawlers on these pages.

Do you have protection mechanisms against such a toxic usage of your library? 

![image](https://user-images.githubusercontent.com/10785783/121913807-fefcbd00-cd31-11eb-9d20-a9edf903a6e9.png)

**Comment by JoshData** [comment]
We don't have any means to prevent people from using this project for nefarious purposes. Similar to how if these folks are using Mac laptops, Apple can't prevent them from buying Macs for nefarious purposes either.

**Comment by jodoox** [comment]
True. Thanks
