### ISSUE TITLE
Can't update TLS certificates manually

### ISSUE THREAD

**Issue by qinjian623** [mail-in-a-box/mailinabox#1995]
While running ssl_certificates.py manually, I got this error:

```
  File "ssl_certificates.py", line 625
    re_pem = rb"(-+BEGIN (?:.+)-+[\r\n]+(?:[A-Za-z0-9+/=]{1,64}[\r\n]+)+-+END (?:.+)-+[\r\n]+)"
                                                                                              ^
SyntaxError: invalid syntax
```

**Comment by JoshData** [comment]
You're probably invoking the script with Python 2 instead of Python 3.

From the mailinabox directory, just run

    ./management/ssl_certificates.py

(Don't put a command before that.)
