### ISSUE TITLE
v0.53a status_checks.py fails in multprocessing, worked before upgrading ubuntu 18.04 to latest

### ISSUE THREAD

**Issue by JLA4444** [mail-in-a-box/mailinabox#1997]
Installed a fresh Ubuntu 18.04 VPS from provider. Installed Mail In a Box. All worked except issues due to newly created domain. After upgrading the OS to latest version, status check stopped working in the admin panel. Tried re installing MIB without it solving the issue.

Maybe MIB can lock what package versions should be used so this issue can't arise due to upgrades?

./status_checks.py 

System
======
✓  All system services are running.
✖  The SSH server on this machine permits password-based login. A more secure way to log in is using
   a public key. Add your SSH public key to $HOME/.ssh/authorized_keys, check that you can log in 
   without a password, set the option 'PasswordAuthentication no' in /etc/ssh/sshd_config, and then 
   restart the openssh via 'sudo service ssh restart'.
✓  System software is up to date.
✓  Mail-in-a-Box is up to date. You are running version v0.53a.
✓  System administrator address exists as a mail alias. [administrator@box.xxxxxx]
✓  The disk has 42.04 GB space remaining.
✓  System memory is 81% free.

Network
=======
✓  Firewall is active.
✖  Outbound mail (SMTP port 25) seems to be blocked by your network. You will not be able to send 
   any mail. Many residential networks block port 25 to prevent hijacked machines from being able to
   send spam. A quick connection test to Google's mail server on port 25 failed.
✓  IP address is not blacklisted by zen.spamhaus.org.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "./status_checks.py", line 369, in run_domain_checks_on_domain
    check_mail_domain(domain, env, output)
  File "./status_checks.py", line 627, in check_mail_domain
    mxhost = mx.split('; ')[0].split(' ')[1]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./status_checks.py", line 1031, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "./status_checks.py", line 66, in run_checks
    run_domain_checks(rounded_values, env, output, pool)
  File "./status_checks.py", line 337, in run_domain_checks
    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

**Comment by JLA4444** [comment]
After installing version 0.54 the issue was resolved.

**Comment by JoshData** [comment]
Perfect!
