### ISSUE TITLE
Feature proposal: Customizable security prefix in HTTP resources

### ISSUE THREAD

**Issue by deadeye64** [mail-in-a-box/mailinabox#2006]
Hi,

Since this project is made for personal use I would like to propose the adoption of a customizable security prefix to be used along with /mail, /cloud and /admin HTTP resources.

This would hide the presence of Roundcube, Nextcloud and the MiaB admin panel from the sight of eventual attackers.
With today's configuration an attacker needs only to know the box's domain, which is not difficult at all to obtain.
By adding a prefix like **/3ffba3c7/cloud** it would be much more difficult for someone to guess the path of the application.

We are talking about an attacker in posses of an unpatched vulnerability, which is not impossible.

Thanks.

**Comment by JoshData** [comment]
Hi. This has come up a few times before. I don't accept changes that are for hypothetical vulnerabilities, optional features, or things like security through obscurity. This sort of hits the trifecta of being all three. You're of course welcome to modify your box any way you like.
