### ISSUE TITLE
Issue when loading Custom DNS page

### ISSUE THREAD

**Issue by albertohernandez-sfe** [mail-in-a-box/mailinabox#2007]
I've recently updated MIAB to version 0.54

Now every time I try to open "custom DNS" page an error message is displayed: "Something went wrong, sorry"

Any suggestions

**Comment by alento-group** [comment]
What do the nginx error logs report?

**Comment by JJJ** [comment]
I am also seeing this. Here's a screen shot:

<img width="764" alt="jjj-on-2021-09-14-at-17-55-03@2x" src="https://user-images.githubusercontent.com/88951/133344369-42ed34a5-a4f1-4932-9f21-36b2692a6745.png">

Tried Chrome/Firefox/Safari on macOS.

Seeing this in console:

```
Failed to load resource: the server responded with a status of 500 ()

https://example.com/admin/dns/custom?_=1631660244033
```

**Comment by kiekerjan** [comment]
You might want to check that the file custom.yml only contains domains that are currently hosted by your Mail in a box. If that's the issue, see [here](https://github.com/mail-in-a-box/mailinabox/issues/1961) for more details.

**Comment by JJJ** [comment]
@kiekerjan 🙏 that was it for me 👍

Recommend to close this issue in favor of that one.
