### ISSUE TITLE
[Feature request] Don't do status checks after login 

### ISSUE THREAD

**Issue by espressoelf** [mail-in-a-box/mailinabox#2014]
Don't get me wrong, the status page is extremely important and shouldn't be somewhere hidden in the menu. But I often find myself wanting to do one quick thing, like adding a DNS entry or an account/alias. Waiting for the checks to finish increases the time a lot (compared to just doing the task).

I nice compromise would be an uncheck checkbox at login that, when checked, disables the status checks for this login. With that, administrators would still have to actively choose not to check the status, but people like me could work a bit faster.

Instead of the status page, there could be a warning page explaining the importance of regularily checking that everything's working fine.

**Comment by JoshData** [comment]
That's fine with me. We can default to just a nice welcome page with an explanation of what the admin site can do and recommended first steps after setting up a new box.
