### ISSUE TITLE
[BUG] Unable to decrypt backups with correct secret key

### ISSUE THREAD

**Issue by starsoccer** [mail-in-a-box/mailinabox#2016]
Hi all, I am in a weird state with MIAB. I have backups to S3 working and have even done a local backup manually but when trying to restore any of the backups they fail with the following error:

```
root@box:/home# sudo -E duplicity restore --force file:///home/backup /home/user-data/
Synchronizing remote metadata to local cache...
Copying duplicity-full-signatures.20210721T000411Z.sigtar.gpg to local cache.
GPGError: GPG Failed, see log below:
===== Begin GnuPG log =====
gpg: AES256 encrypted data
gpg: encrypted with 1 passphrase
gpg: decryption failed: Bad session key
===== End GnuPG log =====
```

I originally posted this on the forum but as I am still in this weird state I decided it best to cross post to github as well - https://discourse.mailinabox.email/t/how-to-clear-secret-key-and-reset-miab/8254

**Comment by geetanshmalhotra** [comment]
Any update on this? I am also stuck on restore. Tried every suggestion.

**Comment by starsoccer** [comment]
Seems like something is either getting broken or corrupt and breaking backups. At this point Im tempted to just nuke my whole install without a backup and start from scratch. Or possibly switch to some other more reliable software

**Comment by mmeidlinger** [comment]
I suppose this is related to  #2209

**Comment by hughsw** [comment]
If you use `management/backup.py --restore` you will get your files back.  Only the first line of the secret key used for the PASSPHRASE.
