### ISSUE TITLE
Syntax Errors in multiple files since upgrade to 0.54

### ISSUE THREAD

**Issue by HeatherFeuer** [mail-in-a-box/mailinabox#2022]
Since the last upgrade, I have been consistently getting the message "Something went wrong, sorry" whenever attempting to load the System Status Checks page on the web. When I try to manually run status_checks.py I get the following error message:

`  File "status_checks.py", line 479
    mail_aliases = dict([(address, receivers) for address, receivers, *_ in get_mail_aliases(env)])
                                                                      ^
SyntaxError: invalid syntax`

Double checking other .py files, dns_update.py returns the following error:

`  File "dns_update.py", line 1098
    print(record['qname'], record['rtype'], record['value'], sep="\t")
                                                                ^
SyntaxError: invalid syntax`

ssl_certificates.py returns:

`  File "ssl_certificates.py", line 625
    re_pem = rb"(-+BEGIN (?:.+)-+[\r\n]+(?:[A-Za-z0-9+/=]{1,64}[\r\n]+)+-+END (?:.+)-+[\r\n]+)"
                                                                                              ^
SyntaxError: invalid syntax`

I have double-checked that I am running the current version of Python 3 and the default coding is set to UTF-8.  Is this a coding error that will be fixed in the next release or am I missing something in my Python install?

**Comment by JoshData** [comment]
Closing since discussion is at https://discourse.mailinabox.email/t/errors-running-status-checks-py-in-vers-54/8325/26 and https://discourse.mailinabox.email/t/help-with-broken-install/8417/7.
