### ISSUE TITLE
Backup: "invalid literal for int() with base 10: 'WARNING:'"

### ISSUE THREAD

**Issue by stsievert** [mail-in-a-box/mailinabox#2026]
My rsync backup server recently got a new SSH fingerprint, and I upgraded from v0.52 to v0.54.

Now, when I visit "System > Backup," I see this message:

<img width="631" alt="Screen Shot 2021-09-01 at 10 09 01 AM 1" src="https://user-images.githubusercontent.com/1320475/131697094-48d1b06a-4622-4f64-a5d3-d2468ca486a0.png">

**Comment by stsievert** [comment]
This same error also appears in the email to administrator@box.foo.com:

> **Subject:** [box.foo.com] Backup Status
> **Body:** invalid literal for int() with base 10: 'WARNING:'

(`foo` is a stand-in for my domain)

**Comment by jvolkenant** [comment]
Remove your destination host entry from /root/.ssh/known_hosts

**Comment by stsievert** [comment]
Thanks! That worked. Closing.

I deleted both lines in `/root/.ssh/known_hosts`. After that, I got an email saying "Warning, found signatures but no corresponding backup files." Now, three backups show up in "System > Backup status > Available backups."
