### ISSUE TITLE
Change admin panel failed login message

### ISSUE THREAD

**Issue by myfirstnameispaul** [mail-in-a-box/mailinabox#2029]
Currently, if I attempt to log into the admin panel with a user account `user@example.com` which doesn't exist, it prints the message:

> That's not a user (user<span></span>@example.com)

If I attempt to log with an account `username@example.com` that does exist but with a wrong password, it prints the message:

> Invalid password.

The 'Invalid password' message appears even for email user accounts.

This seems a sort of privacy issue where someone could start guessing what email addresses are on the box.

It seems a better option would be to print the same message no matter the failure (as Roundcube does):

> Login failed.

**Comment by JoshData** [comment]
Quite right. I've been working on some large changes to the login process, and I've just incorporated your suggestion and pushed those changes.

I should add that this doesn't wholly guard against knowing if an email address is a local user or not. For one, you can just try to email the user and see what happens. I also don't know if all of the other services on the box do this (e.g. Nextcloud login). And I haven't written the control panel login to guard against timing attacks (and the same may be true of the other services), so it may very well be that the error message is consistently faster if the user doesn't exist.

**Comment by myfirstnameispaul** [comment]
Thank you. I'll take a look at some of the other stuff.

For admins that understand it, an option to protect against failed sent email is to create a catch-all, for which there are several ways to auto-delete messages, even if only a simple filter rule in a mail client.
