### ISSUE TITLE
namecheap requires nsx.domain.tld

### ISSUE THREAD

**Issue by wraithgar** [mail-in-a-box/mailinabox#204]
It would appear that namecheap does not allow glue records for anything other than ns1/2/etc on top of the main domain. So the example ns1.box.occams.info is not possible to set up.  Is there a way to set the SOA records to something else or has someone figured out how to make glue records in namecheap go to anything other than nsx.domain.tld?

**Comment by brylie** [comment]
Namecheap have recently re-designed their contrl panel, and now the form validation appears to be done on the server. I.e. it will not allow me to create a sub-subdomain nameserver.

**Comment by 0x27** [comment]
Anyone found a workaround for this? I left them a support ticket today, hoping they have a fix of some variety...

**Comment by n-s-k** [comment]
@0x27 I think I did. 

In **Advanced DNS > Personal DNS Server > Register Nameserver**: 
-**Nameserver** type: **ns1.box** (then press Enter)
-**IP Address**:  **xxx.xxx.xxx.xxx**
then click **Done**. 

Now the trick, to see your entry, in **Find Nameservers** select **Custom Nameserver**  and enter in **Host** : **ns1.box._example.com_** with **_example.com_** the name of your domain, then press **Search**. You should see the new entry below.

**Comment by brylie** [comment]
@n-s-k nice work :-)

@JoshData would this be alright to include in the documentation?

**Comment by brylie** [comment]
I went ahead and added @n-s-k's instructions to the [mail-in-a-box FAQ](https://github.com/mail-in-a-box/mailinabox/wiki/FAQ)

**Comment by JoshData** [comment]
Better would be a PR for https://github.com/mail-in-a-box/mailinabox.email/blob/master/guide.html.

**Comment by nikksno** [comment]
I have a .cx domain and I verified with my registrar that the CX registry doesn't allow fourth level glue records. Therefore I had to set it up as such:

glue records:
  ns1.domain.cx ip.ad.dre.ss
  ns2.domain.cx ip.ad.dre.ss

nameservers:
  ns1.domain.cx
  ns2.domain.cx

Now intodns.com marks my domain as having a mismatch between the parent and mailinabox nameservers. Is there any way to override the NS settings on mailinabox? I know it still works, but it's not a 100% clean configuration without the override.

I read your comment on [this](https://github.com/mail-in-a-box/mailinabox/issues/568#issuecomment-144488886) thread. Do I understand correctly that if I use the ns1.domain.cx ns2.domain.cx method I should avoid pointing domain.cx to a separate server?

Thank you for your brilliant work.

**Comment by JoshData** [comment]
> if I use the ns1.domain.cx ns2.domain.cx method I should avoid pointing domain.cx to a separate server?

The box won't let you do it - it would break everything.

**Comment by nikksno** [comment]
Ok thank you I understand. How about the ovverride? I also added back secondary DNS and noticed that it too [of course] takes the config from MiaB so I have:

parent ns [CX registry] :
  ns1.domain.cx
  puck.nether.net

MiaB:
  ns1.mb.domain.cx
  puck.nether.net

Puck:
  ns1.mb.domain.cx
  puck.nether.net

How can I add NS records on MiaB?

Thanks

**Comment by nikksno** [comment]
Any ideas? Thanks again!

**Comment by viogq** [comment]
my idea is: scrap namecheap, use cloudns.net  instead

**Comment by Amalinda** [comment]
> @0x27 I think I did.
> 
> In **Advanced DNS > Personal DNS Server > Register Nameserver**:
> -**Nameserver** type: **ns1.box** (then press Enter)
> -**IP Address**: **xxx.xxx.xxx.xxx**
> then click **Done**.
> 
> Now the trick, to see your entry, in **Find Nameservers** select **Custom Nameserver** and enter in **Host** : **ns1.box._example.com_** with **_example.com_** the name of your domain, then press **Search**. You should see the new entry below.

nice work!
