### ISSUE TITLE
persistent_login plugin causing session-related issues with new Roundcube 1.5 release

### ISSUE THREAD

**Issue by ashdowntech** [mail-in-a-box/mailinabox#2052]
The latest update of MIAB included RoundCube 1.5. Once we updated, we began having trouble with two items:

**Issue 1**

When selecting a layout in the Larry or the Classic theme, you can choose "List (no mail preview)" as an option in Preferences > Mailbox View > Main Options. If you save this option and then return to the main Mail screen, there will just be list of email with no preview pane as expected.

However, if you simply allow the browser screen to sit idle with no interaction for 5 or 10 minutes, the preview pane will suddenly appear.

Once the preview pane has appeared, you cannot get rid of it by using the small gear dropdown in the header row of the email listing and trying to set it back to list in the pop-up window that appears. Only going to Settings and saving Preferences > Mailbox View, will reset it. However, after several minutes, the preview pane will reappear automatically again.

**Issue 2**

For those customers who have their Roundcube refresh set to "every 10 minutes" or higher and then don't interact with their browser for a while, an error occurs and appear in the area of the screen where the email listing usually is. It is titled, "File Not Found" and says, "The requested resource was not found! Please contact your system administrator. _Failed request mail.redactedmailservername.com/mail/?_task=mail&action=keep-alive"

This is always accompanied by an error in the logs on the server that say, "PHP Error: Error loading template for in /usr/local/lib/roundcubemail/program/include/rcmail_output_html.php on line 804 (GET /mail/?_task=mail&_action=keep-alive)"

You'll note that there is a blank between "for" and "in" that is where a template name should appear. However, there isn't one.

The workaround is to set the refresh to less than 10 minutes. That works, but this was not an issue in previous RC versions and some people would prefer less frequent auto-refreshing or to manually refresh the page themselves as needed.

**Notes**

After posing both of these to the Roundcube folks, they indicated they thought it might be a plugin-related issue. I went in and temporarily deactivated all of the defined plugins in config.inc.php. The problems went away. I then reactivated all of the plugins EXCEPT persistent_login. The problems were still gone.

The persistent_login plugin appears to no longer be fully compatible with RC as of 1.5. We can temporarily disable the plugin and increase the session_lifetime from the very short 10 minutes, but that is only a stopgap measure and those changes will be lost when the next update is done.

A remedy that preserves the important log-in persistence feature while not causing these other issues in RC would be most appreciated.

Thank you!

**Comment by ashdowntech** [comment]
I will absolutely try out those changes to see their impact on the stated problems. My question is whether these same changes will be rolled into the next update of MIAB? Otherwise the changes will be lost and will have to be applied after every update. Thanks!

**Comment by JoshData** [comment]
The best way to get this fixed is to work with the maintainer of the plugin at https://github.com/mfreiholz/persistent_login. If it's not fixed there, I'll probably have to remove the plugin from Mail-in-a-Box.

**Comment by ashdowntech** [comment]
I've just put an issue in with the persistent_login folks. The package hasn't had any activity in a couple of years, but I'm hopeful they are still paying attention to it.

If the plugin has to be removed due to incompatibility, I certainly understand that. However, this is functionality that every web-based login system has for people who use webmail as their everyday email client. To lose that would be a big step backwards. Some replacement for this functionality, even the ability to set the Roundcube session timeout from the MIAB admin panel, would be most helpful in reducing the impact.

Many thanks for your excellent mail server package!

**Comment by JoshData** [comment]
Of course I agree with you that it's important functionality, but I don't want to be in the business of maintaining a webmail application. :)

Either the original plugin, another plugin, or the Roundcube project itself has to take responsibility for the feature for us to include it without it becoming a new burden on this project.

**Comment by ashdowntech** [comment]
I totally understand the conundrum here. Let's hope the persistent login folks are responsive to the issue. I seriously doubt that RC is going to address this as core if they haven't already done so by now. I'm sure they would just say, "turn up the session lifetime", which is fine, but the nature of MIAB means that a change like that would be lost with the next update. Catch-22.

**Comment by jvolkenant** [comment]
Might be fixed downstream https://github.com/downtownallday/persistent_login/commit/e06b4607d1201d4b1cf201cb6406bdc990e2d7e8

**Comment by ashdowntech** [comment]
Looks like this is a perfect solution.  @downtownallday commented up this thread with this solution and has implemented it in the referenced downstream pull.

**Comment by ashdowntech** [comment]
@mfreiholz has rolled the @downtownallday fixes into the master, so including the latest release of persistent_login in the next update of MIAB should resolve these issue with RC 1.5

**Comment by jvolkenant** [comment]
Thanks @ashdowntech @downtownallday @mfreiholz

**Comment by JoshData** [comment]
Good work, all. Someone could open a PR that updates the commit hash that we pull, and add a line to CHANGELOG.md.
