### ISSUE TITLE
Unable to forward emails in bulk

### ISSUE THREAD

**Issue by annkoxx** [mail-in-a-box/mailinabox#2053]
first question:
After I set the domain name mailbox forwarding, it can't work normally.
I want to set up email forwarding on my domain name azcloud.me to forward all emails sent to xxxx@azcloud.me to admin@azcloud.me. I set it up but it doesn't work, I provided a photo
![image](https://cdn.jsdelivr.net/gh/zsxwz/tuchuang@latest/2021/10/30/593cfee4bce684db35bef95356aef9c0.png)
After success is like this
![image](https://cdn.jsdelivr.net/gh/zsxwz/tuchuang@latest/2021/10/30/2ca45c080a763396ffeb6ab30615b4de.png)
But when I send an email to all-encompassing@azcloud.me, it cannot be forwarded to admin@azcloud.me, which makes me very confused

second question:
Why do I use @qq.com to send emails to admin@cloud.me, the emails will go to spam, how can this be avoided?

**Comment by JoshData** [comment]
Could you say more about what "it cannot be forwarded" means? Is there an error message?

**Comment by annkoxx** [comment]
> 你能不能多说一下“无法转发”是什么意思？有错误信息吗？

I want to send mail to @azcloud.me, I just set up admin@azcloud.me, Others like aaa@azcloud.me or bbb@azcloud.me or ccc@azcloud.me or an infinite number of possible xxx@azcloud.me. All emails to these mailboxes are forwarded to admin@azcloud.me. Since I didn't add aaa@azcloud.me to my server, it will be forwarded to admin@azcloud.me. If I add user aaa@azcloud.me, Then he will give aaa@azcloud.me, and if I don't add aaa@azcloud.me, forward it to admin@azcloud.me. How do you do that?

**Comment by myfirstnameispaul** [comment]
I think there are three tools maybe are not clear for you that you use to do all of those things:

The normal user account where the user can log in and send and receive mail.

The default alias configured to forward mail to one or more users on the server.

The catchall alias that forwards all mail not addressed to users or aliases to one or more user accounts on the server.

**Comment by JoshData** [comment]
@annkoxx I understand what you want to do. The photo shows that you did it correctly. I asked: Is there an error message?

**Comment by annkoxx** [comment]
> 我认为您可能还不清楚用于执行所有这些操作的三个工具：
> 
> 用户可以登录并发送和接收邮件的普通用户帐户。
> 
> 默认别名配置为将邮件转发给服务器上的一个或多个用户。
> 
> 将所有未发送给用户的邮件或别名转发到服务器上的一个或多个用户帐户的通用别名。

Yes, as you said, I would like to engage in the second scenario you mentioned, which is forwarding mail to one or more users on the server. I would like to forward all emails sent to @azcloud.me to admin@azcloud.me. Is the operation of my photo correct?

**Comment by annkoxx** [comment]
> @annkoxx我明白你想做什么。照片表明你做对了。我问：有错误提示吗？

I want to forward messages to one or more users on the server. Imagine forwarding all emails to @azcloud.me to admin@azcloud.me. The operation of the photo you said is correct, but THE email I sent to aiushdiowqahd@azcloud.me cannot be forwarded to admin@azcloud.me

**Comment by JoshData** [comment]
@annkoxx It seems like we are having trouble communicating since you didn't answer my question either time. It is very difficult to provide help when we aren't able to communicate well. My time is limited, so I won't be able to help.

**Comment by myfirstnameispaul** [comment]
I recommend reviewing `/var/log/mail.log` and finding the failed message delivery and posting here.

**Comment by annkoxx** [comment]
> /var/log/mail.log
I uploaded my log, can you see why domain forwarding doesn't work?
![image](https://user-images.githubusercontent.com/50774548/139541602-7be4aefc-c5cc-47d4-b248-19c2cc67d134.png)

**Comment by myfirstnameispaul** [comment]
You have to send an email to the server and then find the entry where the sending server tried to send a mail and see what happened in the logs that the email was not delivered.

**Comment by alento-group** [comment]
MiaB will not allow you to create the email address `admin@`.

You need to forward to a different email address.
