### ISSUE TITLE
Cron Daemon: killed: sudo -u www-data php -f /usr/local/lib/owncloud/cron.php

### ISSUE THREAD

**Issue by lorrin** [mail-in-a-box/mailinabox#2057]
Cron Daemon is sending me email every 5 minutes with the subject `Cron <root@crabapple> sudo -u www-data php -f /usr/local/lib/owncloud/cron.php` and message `Killed`.

`/etc/cron.d/mailinabox-nextcloudcron` is the associated cron job. There are corresponding OOM kill entries in the syslog. I can see that when the kill is triggered, PHP is using 136820 pages (4kB each) ≈ 550 MB. That seems like a lot of memory for a cron job. Maybe there’s something in my Nextcloud I need to clean up?
```
Nov  6 18:15:09 crabapple kernel: [940509.213275] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
Nov  6 18:15:09 crabapple kernel: [940509.213344] [29587]    33 29587   266123   136820  1851392     4878             0 php
...
Nov  6 18:15:09 crabapple kernel: [940509.213347] Out of memory: Kill process 29587 (php) score 370 or sacrifice child
Nov  6 18:15:09 crabapple kernel: [940509.214558] Killed process 29587 (php) total-vm:1064492kB, anon-rss:545924kB, file-rss:0kB, shmem-rss:1356kB
```

When the cron is not running, I have what I believe is plenty of memory:
```
# free -hw
              total        used        free      shared     buffers       cache   available
Mem:           985M        328M        362M         14M         36M        257M        501M
Swap:          511M        433M         78M
```

If I run the cron manually on the command line, it either completes silently or reports `Killed`. Is there somewhere I could see more logs about what it is attempting to do?

**Comment by jvolkenant** [comment]
Your server is out of memory, either upgrade the VM to one that has more memory, or try adding more swap space. I'll leave it to you to google how to do this with your specific provider.

**Comment by yodax** [comment]
The log for the process is here: /home/user-data/owncloud/nextcloud.log

I doubt you’ll find anything because the OS is killing the process. But it’s worth a look. If you’ve got fileshares and more importantly external share that calculate stats it’s going to be slow

**Comment by lorrin** [comment]
Thanks. @yodax alas, nothing is getting logged, like you suspected. I have been using a small fileshare to store notes with [Joplin via WebDAV](https://joplinapp.org/help/#nextcloud-synchronisation), and I've got a decently sized address book I sync with CardDAV. But overall I would say my NextCloud use is very light. By external share, do you mean using NextCloud as a front-end to storage that resides externally to the VM? I am not doing that.

@jvolkenant yup, I can definitely add more memory beyond the 1GB I currently have, and I agree that it's clearly running out of memory at the moment. Do you think it's normal for it to run out if 500MB is available at the time the cron job runs? Given that the minimum system requirements [say 512MB of RAM](https://mailinabox.email/guide.html#machine), I figured something must be wrong for the cron job to need so much.

**Comment by yodax** [comment]
Joplin could generate a lot of activity. Nextcloud does change tracking. This happens in the cron job I believe. Those processes require more memory. The MIAB 512 minimum is set for just email/cal/carddav. The file sharing is a nice bonus, but you might run into problems like this. I'd just increase the swap size and see if that helps.

**Comment by lorrin** [comment]
@yodax , thanks for the thoughts on what be causing the memory usage. I've bumped the swap from 512 MB to 2 GB.
