### ISSUE TITLE
can not support Ubuntu 20.04.3 LTS?

### ISSUE THREAD

**Issue by mgl-pub** [mail-in-a-box/mailinabox#2075]
Mail-in-a-Box only supports being installed on Ubuntu 18.04, sorry. You are running:

Ubuntu 20.04.3 LTS

We can't write scripts that run on every possible setup, sorry.

**Comment by jvolkenant** [comment]
MIAB is only going to work on 18.04. Next OS will likely be 22.04.

**Comment by Dibbyo456** [comment]
Ubuntu 18.04 is supported until **Apr 2028**, so there is absolutely no need for it as of now.
This is a open source project so if you want any customization you have to do it yourself or hire someone who can do it for you.

**Comment by nomandera** [comment]
Ubuntu 18.04 is only supported until Apr 2028 if you sign up for ESM. In the context of this project it is support until April 2023.

![image](https://user-images.githubusercontent.com/1133344/148054285-0da29ac7-cd62-40c6-8595-3fee2d1d939b.png)

**Comment by Dibbyo456** [comment]
Yeah right, my bad. 🤦‍♂️

**Comment by Dibbyo456** [comment]
Yeah right.. my bad.

**Comment by ValdikSS** [comment]
The easiest solution is to install MiaB into system container with Ubuntu 18.04 image. You can use LXD or systemd-machined for that.

**Comment by melato** [comment]
Mailinabox now runs on Ubuntu 22.04 LTS.  This issue should be closed.
