### ISSUE TITLE
Version upgrade v56 reported, doesn't exist yet

### ISSUE THREAD

**Issue by stchris** [mail-in-a-box/mailinabox#2085]
Hello!

This morning my box emailed me this status check:

-  A new version of Mail-in-a-Box is available. You are running version v55. The latest version is v56. For upgrade instructions, see https://mailinabox.email.

There seems to be no v56 available. 

If there's anything I can do to help fix this, please let me know.

**Comment by victorlap** [comment]
Version 0.56 is available.

Just use the upgrade instructions and you'll see:

```sh
# curl -s https://mailinabox.email/setup.sh | sudo -E bash
Updating Mail-in-a-Box to v56 . . .
[...]
```

**Comment by TheNomad11** [comment]
There are no release notes either

**Comment by victorlap** [comment]
They are in the changelog:

https://github.com/mail-in-a-box/mailinabox/blob/main/CHANGELOG.md

**Comment by tkforbes** [comment]
If the release notes are always published in a static location, a link to that location in the email could help. I always like to read the release notes. And I ended up here this morning because my system advised me of availability of the v56 version and I was unable to find any documentation.

**Comment by JoshData** [comment]
Apologies for the confusion. I do this intentionally to allow for a soft roll-out in case there are any unexpected issues. I've now updated the website.
