### ISSUE TITLE
NextCloud Administration

### ISSUE THREAD

**Issue by AntoninHL** [mail-in-a-box/mailinabox#2091]
Hello,

I'm looking for the admin page of the nextcloud instance installed with Mail-In-A-Box, but in vain.

Could you give me the way to configure NextCloud, in particular for Sharing adminitration.

Thanks

**Comment by Venem** [comment]
I'm having the same issue, but trying to set up Nextcloud as oauth for my personal instance.

Quite hilariously we made our issues within five minutes of each other lmao

**Comment by Venem** [comment]
I found [this](https://github.com/mail-in-a-box/mailinabox/blob/main/setup/nextcloud.sh) little gem:
`sudo -u www-data php /usr/local/lib/owncloud/occ upgrade`
This allows us to access occ, which in theory allows us to manage nextcloud from the cli.

So by running
`sudo -u www-data php /usr/local/lib/owncloud/occ group:adduser admin <YOUR-EMAIL-HERE>`
The user <YOUR-EMAIL-HERE> will become an admin?

I'm going to test it now

**Comment by Venem** [comment]
Seems to work! Thanks for this, seems like shared confusion helps me find solutions.

From there, if you log in with that specific email and its preconfigured password, you will be able to access the admin page from where you can sort out your sharing config.

Thanks!

**Comment by AntoninHL** [comment]
Brilliant!!!

It works!

Many thanks
