### ISSUE TITLE
Spamhaus instantly bans my domain name after installing mailinabox

### ISSUE THREAD

**Issue by MaxALEau** [mail-in-a-box/mailinabox#2119]
Hello,

I installed mailinabox but Spamhaus instantly bans my domain name after installing it.

How does this happen?

**Comment by myfirstnameispaul** [comment]
However it happens, it has nothing to do with Mail-in-a-Box.

**Comment by MaxALEau** [comment]
In this case, do you think it could come from digitalocean or Freenom (my domain name distributor)?

**Comment by MaxALEau** [comment]
Yes, but there is no specific indication of the problem

![image](https://user-images.githubusercontent.com/52678500/167668939-229d543c-bf0e-4917-8c02-fe60a398cb0d.png)

And that's what scares me

![image](https://user-images.githubusercontent.com/52678500/167669134-82d3cadf-6e32-4f2c-8f73-25bf1fdb8303.png)

**Comment by MaxALEau** [comment]
After looking at mxtoolbox, I think the problem is with digitalocean being banned from the IPs they have.

What host are you with?

**Comment by i0t4** [comment]
@MaxALEau Yeah your probably lies with DigitalOcean, I would recommend Vultr. I personally use it and it is really amazing + its on no blacklists You can get vultr here `https://www.vultr.com/?ref=9107490`

**Comment by nomandera** [comment]
I too would recommend Vultr although you will probably need to contact them to declare you need to run a mail server, I did.

Full disclosure: that link above is almost certainly an affiliate link. This is the proper use of affiliate links but typically they are declared as such.

**Comment by i0t4** [comment]
oh yeah that link is a affiliate my bad for not disclousing so

**Comment by i0t4** [comment]
> I too would recommend Vultr although you will probably need to contact them to declare you need to run a mail server, I did.
> 
> Full disclosure: that link above is almost certainly an affiliate link. This is the proper use of affiliate links but typically they are declared as such.

I did not have to ask them to unblock the ports but it may vary
