### ISSUE TITLE
S3 Backups failing with `ModuleNotFoundError: No module named 'boto3'`

### ISSUE THREAD

**Issue by malord** [mail-in-a-box/mailinabox#2123]
I received the following email from my mail-in-a-box (with the subject "Backup status"):

```
Giving up after 5 attempts. ModuleNotFoundError: No module named 'boto3'
Something is wrong with the backup: Attempt of list Nr. 1 failed. ModuleNotFoundError: No module named 'boto3'
WARNING 1
. Attempt of list Nr. 1 failed. ModuleNotFoundError: No module named 'boto3'

Attempt of list Nr. 2 failed. ModuleNotFoundError: No module named 'boto3'
WARNING 1
. Attempt of list Nr. 2 failed. ModuleNotFoundError: No module named 'boto3'

Attempt of list Nr. 3 failed. ModuleNotFoundError: No module named 'boto3'
WARNING 1
. Attempt of list Nr. 3 failed. ModuleNotFoundError: No module named 'boto3'

Attempt of list Nr. 4 failed. ModuleNotFoundError: No module named 'boto3'
WARNING 1
. Attempt of list Nr. 4 failed. ModuleNotFoundError: No module named 'boto3'

ERROR 50 list
. Giving up after 5 attempts. ModuleNotFoundError: No module named 'boto3'
```

I then upgraded to v56 (I had been on v55) and discovered that System > Backup Status isn't working either, giving the message "Something went wrong, sorry".

I tried manually running management/backup.py but it produced the same output. I've also confirmed that a second box I have is also failing to take backups.

I tried manually installing boto3 (`pip3 install boto3`) but then I get different errors:

```
/usr/local/lib/python3.6/dist-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)
Giving up after 5 attempts. AttributeError: 'NoneType' object has no attribute 'objects'
Something is wrong with the backup: Attempt of list Nr. 1 failed. ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
WARNING 1
. Attempt of list Nr. 1 failed. ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden

Attempt of list Nr. 2 failed. AttributeError: 'NoneType' object has no attribute 'objects'
WARNING 1
. Attempt of list Nr. 2 failed. AttributeError: 'NoneType' object has no attribute 'objects'

Attempt of list Nr. 3 failed. AttributeError: 'NoneType' object has no attribute 'objects'
WARNING 1
. Attempt of list Nr. 3 failed. AttributeError: 'NoneType' object has no attribute 'objects'

Attempt of list Nr. 4 failed. AttributeError: 'NoneType' object has no attribute 'objects'
WARNING 1
. Attempt of list Nr. 4 failed. AttributeError: 'NoneType' object has no attribute 'objects'

ERROR 50 list
. Giving up after 5 attempts. AttributeError: 'NoneType' object has no attribute 'objects'
```

**Comment by johnstcn** [comment]
Ran into this issue as well. [This workaround](https://discourse.mailinabox.email/t/cannot-backup-since-duplicity-update/9119/3) (downgrading duplicity) solved it for me.

**Comment by aalbinati** [comment]
Same issue here

**Comment by mbong** [comment]
Yep, same here. Not yet enabling the workaround, waiting for an official option.

**Comment by myfirstnameispaul** [comment]
I don't use S3, but wanted to mention that Duplicity docs mention [support for Rclone](http://duplicity.nongnu.org/vers8/duplicity.1.html#sect28):

> Rclone is a powerful command line program to sync files and directories to and from various cloud storage providers.
> 
> Once you have configured an rclone remote via
> 
>     rclone config
> 
> and successfully set up a remote (e.g. gdrive for Google Drive), assuming you can list your remote files with
> 
>     rclone ls gdrive:mydocuments
> 
> you can start your backup with
> 
>     duplicity /mydocuments rclone://gdrive:/mydocuments
> 
> Please note the slash after the second colon. Some storage provider will work with or without slash after colon, but some other will not. Since duplicity will complain about malformed URL if a slash is not present, always put it after the colon, and the backend will handle it for you.

**Comment by geek-baba** [comment]
> Ran into this issue as well. [This workaround](https://discourse.mailinabox.email/t/cannot-backup-since-duplicity-update/9119/3) (downgrading duplicity) solved it for me.

The [package](https://launchpad.net/~duplicity-team/+archive/ubuntu/duplicity-release-git/+files/duplicity_0.8.22-ppa202203041847~ubuntu18.04.1_amd64.deb) 0.8.22-ppa202203041847 is now removed, any other way to make it work...

**Comment by myfirstnameispaul** [comment]
I'm just kind of wondering why Rclone is not an option. I realize my quote above is for Google and an older version of Duplicity, but I'm pretty sure that is just the chosen example service for the Duplicity docs.

Rclone includes configuring for [S3](https://rclone.org/s3/) (and pretty much everything else), and I can see in recent changes to Duplicity they are clearly supporting Rclone and the most recent update includes [additional Rclone documentation](https://gitlab.com/duplicity/duplicity/-/commit/0b45cbf7d73463022d00bd5f3c8a0edfadd0a538).

Given how well supported Rclone is across nearly all platforms, it seems like a reasonable option, but since I just use trusty ol' `rsync`, I can't test and verify.

**Comment by JoshData** [comment]
> I'm just kind of wondering why Rclone is not an option. 

Please keep this thread on topic since we're dealing with a significant (and somewhat stressful) problem here. If you want to open a discussion about something else, feel free to open an issue or start a topic on the discussion forum.

**Comment by JoshData** [comment]
I have a fix coming. If all goes well, I'll post an update to Mail-in-a-Box tomorrow.

**Comment by JoshData** [comment]
I've posted version 57 which fixes our backup to work with the latest version of duplicity (https://github.com/mail-in-a-box/mailinabox/commit/99474b348f0dd2632057c18c6a8c4e6464962878).

**Comment by beemach** [comment]
Version 57 works perfectly for me for S3 compatible backups to Wasabi. Thanks so much @JoshData

**Comment by malord** [comment]
Do the website instructions on how to restore also need updating? 

Looking at the fix in 57, I think this:

`sudo -E duplicity restore --force s3://s3.amazonaws.com/your-bucket-name/your-backup-path /home/user-data/`

needs to become:

`sudo -E duplicity restore --force --s3-endpoint-url https://s3.amazonaws.com boto+s3://your-bucket-name/your-backup-path /home/user-data/`

**Comment by pckilgore** [comment]
I had to explicitly set my region (example: `us-east-2` on restore):

`sudo -E duplicity restore --force --s3-region us-east-2 s3://my-bucket-name /home/user-data/`

**Comment by mattbillenstein** [comment]
> o

Ah, thanks for that - setting up a new box from s3 backup - this should probably be in the docs...
