### ISSUE TITLE
Any way to paginate the user list? 

### ISSUE THREAD

**Issue by JoshWho** [mail-in-a-box/mailinabox#2130]
A MIAB instance with over 1000 users makes that page in the admin dashboard hard to load. Is there a way to not list the names or make multiple pages out of the name list?

![2687f6bb-9e87-4a55-94a6-c5478c80e3c0](https://user-images.githubusercontent.com/39392449/173210161-b04fbed5-bb4c-4ea1-aac8-88d418f1c9c8.png)

**Comment by JoshWho** [comment]
Do you need money for this I can arrange that

**Comment by alento-group** [comment]
Off-topic:  @JoshWho are there multiple domains, or a single domain?

**Comment by JoshData** [comment]
See https://discourse.mailinabox.email/t/how-can-we-change-the-user-admin-page-to-multiple-pages/9235.
