### ISSUE TITLE
backup.py assumes "virtual hosted style" urls for S3, fails on "path style"

### ISSUE THREAD

**Issue by pckilgore** [mail-in-a-box/mailinabox#2132]
[As Amazon explains, there's a few different ways to construct s3 URLs.](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html). Prior to the [recent backups fix](https://github.com/mail-in-a-box/mailinabox/commit/99474b348f0dd2632057c18c6a8c4e6464962878), duplicity seemed to understand this and handled both kinds of URLs (as I certainly used the "Path Style Access" in my config.yaml

```yaml
target: s3://s3.ca-central-1.amazonaws.com/BUCKET
```

However, this part of the fix:

https://github.com/mail-in-a-box/mailinabox/blob/99474b348f0dd2632057c18c6a8c4e6464962878/management/backup.py#L211

Assumes that the mail-in-a-box user selected the newer "virtual-hosted-style" of URL when assigning targets.

## Possible fixes

1. Try to be smart when parsing and handle both kinds of URLs in `get_duplicity_target_url`
2. Clearly document that we only support virtual-hosted-style of S3 URLs.

Happy to PR either if you have an opinion @JoshData

**Comment by pckilgore** [comment]
Hmm, did I misread urlsplit docs....

**Comment by JoshData** [comment]
I think Mail-in-a-Box constructs the URL from the user's options in the control panel and that it always has the longer form, so I think we can assume the URL looks like s3://amazonhost/bucket[/path]. The problem that folks raised on the forum is that I didn't correctly handle the absence of a path (i.e. backups to the root of the bucket).

(And just to be clear for others reading, it's duplicity (not us) that stopped accepting the longer target URL format with the S3 hostname.)
