### ISSUE TITLE
Provision a Certificate is missing on TLS (SSL) Certificates page - Fresh install

### ISSUE THREAD

**Issue by Pingd0m** [mail-in-a-box/mailinabox#2142]
Hello,

I'm new to mail-in-a-box and decided to give it a try on a fresh Linode Ubuntu 18.04 LTS instance.
I was checking the Youtube video to get started, and I can't get easily a Lets encrypt certificates as its demonstrated.
I can't see any Provision blue button on my admin TLS (SSL) Certificates page. Only have 2 sections on that page: Certificate status and Install certificate.

Some ideas what could be wrong? Is it because I manage my DNS externally?

Cheers!

**Comment by alento-group** [comment]
Check to be certain that you have all necessary DNS records set up on your external DNS.
It sounds to me like you missed an A/AAAA record.  What does your status page say?
