### ISSUE TITLE
Z-Push authentication fails

### ISSUE THREAD

**Issue by DreamTexX** [mail-in-a-box/mailinabox#2148]
After the nightly backups (custom script), z-push cannot connect to IMAP, so I cannot authenticate through exchange. Only deleting the account and setting it up again on my phone fixes this error.

Log from z-push (password and username are correct, it worked before):
```
08/08/2022 08:13:40 [32720] [FATAL] [example.name] Exception: (ProvisioningRequiredException) - Retry after sending a PROVISION command
08/08/2022 08:13:43 [32718] [WARN] [example.name] /usr/local/lib/z-push/backend/imap/imap.php:127 imap_open(): Couldn't open stream {127.0.0.1:993/imap/ssl/norsh/novalidate-cert} (2)
08/08/2022 08:13:43 [32718] [ERROR] [example.name] BackendIMAP->Logon(): can't connect as user 'example.name' on '{127.0.0.1:993/imap/ssl/norsh/novalidate-cert}': Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Authentication failed.
08/08/2022 08:13:43 [32718] [FATAL] [example.name] Exception: (AuthenticationRequiredException) - Access denied. Username or password incorrect
08/08/2022 08:13:43 [32718] [WARN] [example.name] Unknown:0 Unknown: Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Authentication failed. (errflg=2) (8)
```

Why custom backup script:
I do backups on a custom s3 storage and mailinabox doesn't seem to support this kind of s3 (path-style), so I needed to write my own script and disable builtin:

```bash
#!/bin/bash
systemctl stop php7.2-fpm
systemctl stop postfix
systemctl stop dovecot

PASSPHRASE=$(cat /home/user-data/backup/secret_key.txt) \
AWS_ACCESS_KEY_ID=xxx \
AWS_SECRET_ACCESS_KEY=xxx \
/usr/local/bin/duplicity incr \
	--archive-dir /home/user-data/backup/cache \
	--exclude /home/user-data/backup \
	--volsize 150 \
	--asynchronous-upload \
	--s3-use-multiprocessing \
	--s3-multipart-chunk-size 50 \
	--gpg-options \
	--cipher-algo=AES256 \
	--s3-endpoint-url "https://xxx" \
	--allow-source-mismatch \
	--progress \
	--full-if-older-than 30D \
	/home/user-data \
	boto3+s3://backup-mail-server

systemctl start php7.2-fpm
systemctl start postfix
systemctl start dovecot
```
(this script is running as a cron job in root user every night at 3am)

MailInABox-Version: v57a

Would really appreciate some help with this. I use exchange to sync the calendar and contacts with my phone, so it is rather important.

**Comment by downtownallday** [comment]
FWIW, I don't know a whole lot about z-push, but a couple of ideas you could consider that might help:

Look at /var/log/nginx/error.log. It would have stderr output from FastCGI php attempts by nginx to z-push (may not be any, but worth a look).

Look at /var/log/mail.log for login failures such as "imap-login: Info: Disconnected: Connection closed (auth service reported temporary failure" or "imap-login: Info: Disconnected: Connection closed (auth failed". It appears z-push is attempting a imap login, so there should be an imap log entry.

Try turning on z-push debug logging by editing /usr/local/lib/z-push/config.php and setting LOGLEVEL to LOGLEVEL_DEBUG. Detailed output will appear in /var/log/z-push/z-push.log.

Try running /usr/local/lib/z-push/z-push-admin.php -a lastsync (or -a listdetails) before and after the backup to see what the z-push device manager has stored (device details are persisted by z-push in files stored in directory /var/lib/z-push).

**Comment by DreamTexX** [comment]
Thanks for your answer!

/var/log/mail.log does not report any failed auth attempts.

/var/log/nginx/error.log does contain some upstream errors but nothing seems to be related to the problem, as it is from other things. 

Just enabled debug logging, will take a look at it, when it happens again. Lastsync and Listdetails do not report any interesting stuff.

Interestingly enough, just made a backup by hand (running the script from the shell), and nothing happened, everything just works like charm. It only seems to get this weird behavior when running from a corn job. I will see what happens tonight after the backup.

**Comment by DreamTexX** [comment]
Seems like the order of starting the services again is important. Postfix needs to be started before php-fpm. Haven't had any issues since.
