### ISSUE TITLE
External Zone file settings, Some providers complain about p tags in _dmarc settings

### ISSUE THREAD

**Issue by sudheesh001** [mail-in-a-box/mailinabox#2149]
The admin page for external DNS shows the `_dmarc` settings policy `v=DMARC1; p=quarantine`. However, some external DNS providers throw errors about valid policy tags. Terminating the policy with `;` is recommended.

`v=DMARC1; p=quarantine` --> `v=DMARC1; p=quarantine;`

**Comment by JoshData** [comment]
The DMARC specification is clear that the last `;` is optional, but I would happily accept a pull request that makes that change.
