### ISSUE TITLE
Question: Password reset feature

### ISSUE THREAD

**Issue by soupdiver** [mail-in-a-box/mailinabox#215]
I use the setup to also to host emails for other people. For migrating from my old setup I implemented a simple password reset feature. Which is currently in PHP, which is my main language.
If you want I would prepare it to integrate in your admin panel.

**Comment by dertobes** [comment]
Re "I'm not sure your use case is exactly reusable by others." -- this is very reusable by others. This applies to anyone who is running an e-mail server for other people and wants to shift that server to mail-in-a-box.
Of course you don't know your user's passwords and you do not want to pre-set a password for them manually. Hence you need some mechanism for users to reset their password before they start using the new server.

How is that scenario currently handled? 
Is mail-in-a-box just for people who had no e-mail before?
Can people even change their e-mail password?

I hope I'm not too late to the party after more than a year, but maybe soupdiver could post some php ...?

Cheers

**Comment by soupdiver** [comment]
I'm still happily using maininabox and amde it to migrate all my users. Since they can change their password from within roundcube, in most cases I simply create a random long password, send it to them and they can change it.

I think I abandoned the code somewhen ago.. but it shouldn't take longer then an afternoon to reimplement a system like I did.
