### ISSUE TITLE
How to install on existing Nginx Server?

### ISSUE THREAD

**Issue by sinhpn92** [mail-in-a-box/mailinabox#2150]
Hi all,

I have installed the Mail-in-a-box on my server with existing Nginx server. When I access to the admin by my Ip, It doesn't working.
What's wrong here? How can I fix it? Thank you so much!

**Comment by Synchro** [comment]
I think the answer here is "don't do that". MIAB is intended to be on a server dedicated to what it does, not to coexist with other things. If you try doing that and it doesn't work, your'e on your own.

**Comment by sinhpn92** [comment]
Thank you @Synchro ,
I installed the MIAB on my existing server. Now It's working fine.
