### ISSUE TITLE
Prevent intra-domain spoofing

### ISSUE THREAD

**Issue by dhpiggott** [mail-in-a-box/mailinabox#217]
(Original discussion is in #212, just the relevant parts are below).

I briefly dug into Postfix/Dovecot docs and the mailinabox scripts and what I've read so far makes me think that mailinabox doesn't actually check MAIL FROM against the user's main address and aliases. 

So as an example, if I have an account on a mailinabox that runs the domain example.com - let's say the account is chuck@example.com (with no aliases) - I could currently can send email as alice@example.com. The task is to make Postfix reject such attempts.

A few docs that may help in implementation:
* http://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL (it describes "Verification of alias ownership via Login Maps ")
* http://www.postfix.org/postconf.5.html#smtpd_sender_login_maps
* http://serverfault.com/questions/147921/forcing-the-from-address-when-postfix-relays-over-smtp

**Comment by dhpiggott** [comment]
Note for future:
If #365 is accepted and if/when we handle this we'll need to take into account the implied support for allowing other hosts to send as any FROM address by allowing the creation of privileged accounts for relaying.

**Comment by milani** [comment]
As it is a security issue for organizations (sending email on behalf of others!), I think mailinabox should add extra effort for resolving this issue.

**Comment by JoshData** [comment]
Looks doable with `reject_authenticated_sender_login_mismatch`.
