### ISSUE TITLE
z-push-admin broken in v60

### ISSUE THREAD

**Issue by stylnchris** [mail-in-a-box/mailinabox#2178]
z-push-admin broken in v60

**Comment by stylnchris** [comment]
z-push-admin doesn't work.

**Comment by hija** [comment]
Seems like you found the solution yourself: https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/42
@JoshData any idea why the two lines got initially deleted?

**Comment by beemach** [comment]
Just adding the summary from the MIAB forum into this specific issue to help it get resolved. The link @hija has provided above only provides part of the solution. 

cinergi summarises here: https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/53

I managed to get Z-Push to work with a few changes to the PHP files, without resorting to installing PHP 7.4:

Edit /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php as per [this post](https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/13).

Edit /usr/local/lib/z-push/policies.ini as per the above post.

Add the symbolic links as per [this post](https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/43).

Edit /usr/local/lib/z-push/backend/caldav/caldav.php as per bob4os's instructions at the end of [this thread](https://forum.kopano.io/topic/3680/caldav-sync-error-unsupported-operand-types-string-int).

**Comment by hija** [comment]
Good points, @beemach.

Do you know why changing the policies.ini is required? I don't see how this fixes any issues caused by using PHP8 instead of PHP7.

**Comment by Loomaanaatii** [comment]
> Just adding the summary from the MIAB forum into this specific issue to help it get resolved. The link @hija has provided above only provides part of the solution.
> 
> cinergi summarises here: https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/53
> 
> I managed to get Z-Push to work with a few changes to the PHP files, without resorting to installing PHP 7.4:
> 
> Edit /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php as per [this post](https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/13).
> 
> Edit /usr/local/lib/z-push/policies.ini as per the above post.
> 
> Add the symbolic links as per [this post](https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/43).
> 
> Edit /usr/local/lib/z-push/backend/caldav/caldav.php as per bob4os's instructions at the end of [this thread](https://forum.kopano.io/topic/3680/caldav-sync-error-unsupported-operand-types-string-int).

Will this fix be pushed to the master branch any time soon? I don't want to be messing with the filesystem on my MITB box incase these changes break an official fix that get's released.

**Comment by hughsw** [comment]
I ran a script based on the above links and comments.  It fixed z-push for some basic usage by a Microsoft Mail client...  Your mileage may vary.

[z-push-fix.sh.txt](https://github.com/mail-in-a-box/mailinabox/files/10259926/z-push-fix.sh.txt)

**Comment by matidau** [comment]
Now that Z-Push is updated to 2.7.0 for v62, I've opened a PR to fix the rest of this issue https://github.com/mail-in-a-box/mailinabox/pull/2263

You can create he below bash script and run as sudo to achieve the same. 

```
#!/bin/bash
PHP_VER=8.0
rm -f /usr/sbin/z-push-{admin,top}
echo '#!/bin/bash' > /usr/sbin/z-push-admin
echo php$PHP_VER /usr/local/lib/z-push/z-push-admin.php '"$@"' >> /usr/sbin/z-push-admin
chmod 755 /usr/sbin/z-push-admin
echo '#!/bin/bash' > /usr/sbin/z-push-top
echo php$PHP_VER /usr/local/lib/z-push/z-push-top.php '"$@"' >> /usr/sbin/z-push-top
chmod 755 /usr/sbin/z-push-top
```

Feedback welcome.
