### ISSUE TITLE
Mail-in-a-box via Gmail (Active Sync) Error

### ISSUE THREAD

**Issue by daygle** [mail-in-a-box/mailinabox#2181]
Attempted to connect to my mail-in-a-box mail server using the Gmail application on my Android (with the exchange option) and I am receiving the below message.

Is anyone else receiving this message? Why does Google think that my Main-in-a-box is not secure enough to view emails?

I should mention my mail-in-a-box has been correctly setup with certificates and isn't showing any errors on the status page.

![image](https://user-images.githubusercontent.com/5925233/197132428-706a5122-abc9-4c58-af0b-93dba5be5eb6.png)

**Comment by jbandholz** [comment]
Yep, same problem for me.  I can login directly to the zpush page, but Gmail continues to complain.  I tried modern auth as well and that does not work either.

**Comment by matidau** [comment]
Hey there,

I have a working repo [https://github.com/matidau/Z-Push](https://github.com/matidau/Z-Push) 

And a working script to patch standard MIAB, if your willing to test it. 
`curl -s https://mat.id.au/zpushpatch.sh | sudo bash`
Feedback is welcome. 

Cheers, 
Mat

**Comment by kiekerjan** [comment]
You don't need to be using the exchange option on the gmail android app. You can also choose "other", select imap, then use box.<yourdomain> as the mail server.

**Comment by matidau** [comment]
#2236 
PR to fix this with updated repo

**Comment by matidau** [comment]
@daygle Updated in v62, is this working now?

**Comment by daygle** [comment]
Yes, working now.

Thankyou.
