### ISSUE TITLE
Internet disconnection with Ubuntu 22.04

### ISSUE THREAD

**Issue by pachadotdev** [mail-in-a-box/mailinabox#2213]
the problem seems to be here https://github.com/mail-in-a-box/mailinabox/blob/main/setup/system.sh#L351

**Comment by extric99** [comment]
The issue seems to depend on the image from the VPS provider.
See here https://discourse.mailinabox.email/t/ionos-ubuntu-22-04-1-miab-v60-1-installation-failure/9753
