### ISSUE TITLE
MIAB Install fails on Nextcloud step

### ISSUE THREAD

**Issue by StoryHack** [mail-in-a-box/mailinabox#2229]
Install process goes fine until the step where the script tries to install Nextcloud.

`Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2023-01-30-13:13:00...

Upgrading to Nextcloud version 21.0.7

sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of https://github.com/nextcloud-releases/contacts/archive/refs/tags/v4.0.7.tar.gz did not match expected checksum.
Found:
0ba30284b0a8878ea3607cad4d7d777c9a5ad301  /tmp/contacts.tgz

Expected:
45e7cf4bfe99cd8d03625cf9e5a1bb2e90549136  /tmp/contacts.tgz`

I've tried probably a dozen times on a couple of different boxes now using 22.04 & 18.04 (just to see)

**Comment by VK2XXY** [comment]
Same issue here...

Upgrading to Nextcloud version 23.0.10

sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of https://github.com/nextcloud-releases/contacts/archive/refs/tags/v4.2.2.tar.gz did not match expected checksum.
Found:
d70a0d0b7640b8bc73c41a7312f5d21404c17796  /tmp/contacts.tgz

Expected:
ca13d608ed8955aa374cb4f31b6026b57ef88887  /tmp/contacts.tgz

**Comment by StoryHack** [comment]
Working now. I think somebody updated the nextcloud repo?
