### ISSUE TITLE
Bump nextcloud from v23.0.10 to v23.0.12

### ISSUE THREAD

**Issue by binarykitchen** [mail-in-a-box/mailinabox#2243]
Because it contains lots of bugfixes and has zero breaking changes. Will submit a PR shortly.

Also apply any patches of existing Nextcloud apps.

**Comment by jvolkenant** [comment]
👍 
I've been running the same for a few weeks just fine.

Looks like Nextcloud 23 is unsupported, https://nextcloud.com/changelog/
We should probably look to go to Nextcloud 24, would still be one version off of the latest https://docs.nextcloud.com/server/24/admin_manual/installation/system_requirements.html#server

**Comment by binarykitchen** [comment]
I asked that myself too, but would delay the bump to v24 in a separate PR because it might require some migrations and more tests.

This one PR is just small and simple. I think it can go out at a very low risk for the next release. And we can take more time about the v24 bump in the next sprint.

**Comment by JoshData** [comment]
Yeah separate PR please. I'll merge this after another day of testing on my box.

**Comment by binarykitchen** [comment]
Cool, thanks. Once this is out, I will help with v24 in a separate PR later.

**Comment by binarykitchen** [comment]
@JoshData how's looking? Did the tests on your box pass?

**Comment by babywhale321** [comment]
@JoshData How did that work out?

**Comment by JoshData** [comment]
Sorry for the delay. Merging now.

**Comment by binarykitchen** [comment]
@JoshData great thanks - when do you intend to release this change?

Now, let's elaborate on the next steps: the next Nextcloud version, v24, is also unsupported as well. Would you accept another PR of mine, upgrading to the latest version 26 right away, including any necessary required code for migrations?

Or to reduce risks, prefer to do this in smaller iterations, v24 first, then v25 and then v26?

To be honest, it's a bit hard to find what the breaking changes are. They don't mention any in the release notes, but you have to find them in their GitHub issues. What I've found so far is the newer, required PHP version v8.2 for Nextcloud v26. Do you know more about it? Thoughts?

**Comment by JoshData** [comment]
I'm going to give a week for anyone to test the main branch (although no one may do that), and then I'll try to post a release next weekend.

We can jump to the latest version of Nextcloud. 26 still supports PHP 8.0 according to https://docs.nextcloud.com/server/26/admin_manual/installation/system_requirements.html, so hopefully there won't actually need to be any major changes (fingers crossed!). Thanks!

**Comment by binarykitchen** [comment]
Thank you. I will help test the main brain this week.

Ok, once this is out, I'll consider submitting another PR to jump to v26 and test it carefully.

**Comment by yodax** [comment]
There currently is a problem with going to 26 right away. The user_external plugin isn’t supported. I suspect that will be solved later, but it’s worth waiting until that’s resolved.

**Comment by binarykitchen** [comment]
@yodax do you have a link to that original issue about the user_external plugin I could watch and follow?

**Comment by yodax** [comment]
https://github.com/nextcloud/user_external/issues/222

Some report that it works. I upgraded my MIAB to 25 yesterday to then try 26. That doesn’t work when we reinstall the plug-in. In the Nextcloud App Store it is also listed as unsupported.

**Comment by binarykitchen** [comment]
> Some report that it works.

Where?

**Comment by yodax** [comment]
> > Some report that it works.
> 
> Where?

In the issue I linked. It doesn’t work for me. But some report that after going through some restarts it does work for them. So what I mean it is not a very clear problem

**Comment by binarykitchen** [comment]
> I upgraded my MIAB to 25 yesterday

@yodax did you manually upgrade Nextcloud to 25 by forking the latest code of MIAB without any issues? Does MIAB run well on Nextcloud v25 at all?

**Comment by yodax** [comment]
I was already running 24 for a while. 25 hasn’t had any issues since Saturday either. 

https://github.com/yodax/mailinabox/blob/jammy2/setup/nextcloud.sh

I have disabled the update of the calendar and contacts app in that script. I keep those updated in the ui so I’m always running the latest versions. But you can at least borrow the Nextcloud version code if you like. 😀

Nextcloud reports no errors in the admin overview. Our current update scripts will handle index upgrades during the 24->25 move on their own.

**Comment by binarykitchen** [comment]
Ah, interesting, thank you @yodax 

In that case, I will re-consider submitting another PR just for bumping to v25 alone.

**Comment by binarykitchen** [comment]
@yodax Now that the user_external works on NC v26 as well, I'll consider another PR to bump to v26 soon.
