### ISSUE TITLE
"subdomain  IN  MX  0 ." not RFC compatible

### ISSUE THREAD

**Issue by phant** [mail-in-a-box/mailinabox#2250]
MIAB adds MX records for subdomains like "n1.box" "ns2.box" that points to "."
"subdomain  IN  MX  0 ."
My hoster's DNS panel said this reconds is not RFC compatible:
"Error in specifying mail server for MX-record '.' RFC 974, 1035, 3363, 4343"

Who is right?

**Comment by jvolkenant** [comment]
Those are considered 'Null MX' records https://www.rfc-editor.org/rfc/rfc7505#section-3

IF MIAB is not doing DNS, your external DNS provider would need to support it.
