### ISSUE TITLE
Nextcloud Administrator Account

### ISSUE THREAD

**Issue by nanaksingh13** [mail-in-a-box/mailinabox#2255]
I want access Nextcloud Administrator account can anyone tell me what to do

**Comment by matidau** [comment]
Did you search the forum?

Here is a recentish post https://discourse.mailinabox.email/t/nextcloud-administration-web-ui-to-setup-disk-quota/6133

**Comment by nanaksingh13** [comment]
@matidau thx will try that. one more thing if can i enable additional plugins then

**Comment by matidau** [comment]
> @matidau one more thing if can i enable additional plugins then

Personally haven't, but I would start searching on the forum first and then ask there instead of Github. It is more active and is the best avenue for support.

**Comment by nanaksingh13** [comment]
ok thx
