### ISSUE TITLE
fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by binarykitchen** [mail-in-a-box/mailinabox#2274]
When running MIAB on a fork, the `git describe` command under `setup/bootstrap.sh` produces this error every day and it also gets sent by email every day to the administrator:

```
fatal: No names found, cannot describe anything.
```
To silence this and to cope with forks properly, recommend amending the `--always` option. Like that:
```
michael-heuberger@abc.com /home/michael-heuberger/mailinabox-v25 ❯❯❯ git describe --always
848392c
```
If you agree, I'll do a tiny PR for that.

**Comment by JoshData** [comment]
Are you sure it's not the invocation at

https://github.com/mail-in-a-box/mailinabox/blob/8b19d157359e402f751c86f7e0a1276011277648/management/status_checks.py#L919

?

Adding `--always` there makes sense. As would normal Python error handling (or both).

**Comment by binarykitchen** [comment]
Yeah @JoshData, that file too. Ok, I will create a PR to amend `--always` for all `git describe` commands we have in our code base.

**Comment by binarykitchen** [comment]
Done, PR is here. See link above.

**Comment by binarykitchen** [comment]
PR is merged. All good. Closing.
