### ISSUE TITLE
blinker error 

### ISSUE THREAD

**Issue by Wayno** [mail-in-a-box/mailinabox#2278]
Going from 61.1 to 62 gets stuck on this error

Installing collected packages: blinker, flask, cryptography
  Attempting uninstall: blinker
    Found existing installation: blinker 1.4
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Manually updated blink to 1.6.2

blinker                  1.6.2
Flask                    2.3.2
cryptography             41.0.1

still cannot complete update

**Comment by matidau** [comment]
The forum is sometimes the best place for support questions.

https://discourse.mailinabox.email/t/error-with-v62-upgrade/10463

**Comment by Wayno** [comment]
Thanks Matidau

https://discourse.mailinabox.email/t/error-with-v62-upgrade/10463/4

worked.

**Comment by GedMarc** [comment]
For those that follow xD
```
sudo apt purge python-pip python3-pip
rm -r /usr/local/lib/mailinabox
rm -r ~/mailinabox

curl -s https://mailinabox.email/setup.sh | sudo -E bash
```
I think something is on the digital ocean ubuntu images, but this solved for the entire chain of errors 

[Error with V62 upgrade](https://discourse.mailinabox.email/t/error-with-v62-upgrade/10463)
https://discourse.mailinabox.email/t/pip-error-setup-functions-sh-line-19-usr-local-lib-mailinabox-env-bin-pip-no-such-file-or-directory/11153
https://github.com/rsmusllp/king-phisher/issues/300
