### ISSUE TITLE
Backup fails after duplicity updated to 2.0.0

### ISSUE THREAD

**Issue by jeremitu** [mail-in-a-box/mailinabox#2294]
```
duplicity collection-status: error: argument --gpg-options: expected one argument
Something is wrong with the backup:
```
gpg-options' argument must be single, quoted

**Comment by jeremitu** [comment]
It seems to be duplicity 2.0.0 problem
```
# duplicity collection-status --gpg-options "cipher-algo=AES256" --log-fd 1
CommandLineError: Source should be url, not directory.  Got '1' instead.
```

**Comment by imelya** [comment]
When installing `duplicity==1.2.3`, it was necessary to install `librsync-dev`

**Comment by jeremitu** [comment]
I did:
```
git clone --depth 1 --branch rel.1.2.3 https://gitlab.com/duplicity/duplicity.git
sudo apt install librsync-dev
cd duplicity
python3 setup.py build
sudo python3 setup.py install --prefix=/usr/local
which duplicity #should be local
```

**Comment by gwhitney** [comment]
Rather than reverting, one could try to adapt the commands in management/backup.py to the new duplicity syntax. For the first one, to get the collection status, the following argument order seems to work:
```
/usr/bin/duplicity --log-fd 1 collection-status --archive-dir /home/user-data/backup/cache --gpg-options "cipher-algo=AES256" file:///home/user-data/backup/encrypted
```

**Comment by jeremitu** [comment]
Tried that and ran from one problem into another. We need to wait until duplicity 2.x becomes stable and standard, and break compatibility with duplicity 1,x.

**Comment by gwhitney** [comment]
Ah, yes, I see https://gitlab.com/duplicity/duplicity/-/issues/732 that duplicity 2.0 is buggy specifically in the `--gpg-options` option.

**Comment by keithdanielll** [comment]
So, even a year later, there is nothing we can do except roll back the duplicity version?

**Comment by JoshData** [comment]
Duplicity fixed this issue within a few weeks of this issue being opened, but I think there was a newer issue recently which has also already been resolved by Duplicity: https://discourse.mailinabox.email/t/m-in-a-b-doing-daily-full-backups/12244/5
