### ISSUE TITLE
DNS - GEO redirection

### ISSUE THREAD

**Issue by redimongo** [mail-in-a-box/mailinabox#2318]
So we are using mail-in-a-box but we have an issue where we need to have domains able to be pointed to different servers depending on where the user is located.

For example if the user is located in Australia we need to them to do the Australian server but if the user is in America then we want them to go to the New York server.

How do we achieve this using this mail-in-a-box DNS?

**Comment by JoshData** [comment]
That is far, far outside of the scope of this project. A better place to ask would be https://serverfault.com/.
