### ISSUE TITLE
Version string bug in v65 Release

### ISSUE THREAD

**Issue by rainyskye** [mail-in-a-box/mailinabox#2324]
It's appearing like there is a bug in the latest v65 release, when running the status check, it reports:

```
A new version of Mail-in-a-Box is available. You are running version 03145542076c80ab2af3a3b12b94c0da50a631fa. The latest version is v65. For upgrade instructions, see https://mailinabox.email. 
```

During the installer you can also see `Mail-in-a-Box Version:  0314554`

This is the git hash of v65 (https://github.com/mail-in-a-box/mailinabox/commit/03145542076c80ab2af3a3b12b94c0da50a631fa)

I've also noticed v65 has been tagged on GitHub, but not as a "Release"? Not sure if this would affect the installer or something else.

**Comment by m0rp30** [comment]
I have same version issue

**Comment by rainyskye** [comment]
> I have same version issue

Yeah I've seen others with the same report on the fourm (https://discourse.mailinabox.email/t/version-number-corrupted-after-upgrade/10990)

So seems to be relatively widespread, I'm assuming it's since v65 isn't marked as a "Release" even though it's tagged with `v65`

**Comment by dms00** [comment]
So, I'm not at all certain of this, but I see that the prior tags are annotated tags, but v65 is a lightweight tag, so this may be the cause of the difference in how it's presenting the version. For example, I see some scripts run `git describe --always`, but `git describe --help` says, "By default (without --all or --tags) git describe only shows annotated tags".

**Comment by babywhale321** [comment]
yeah iv noticed the same issue

**Comment by aminir1400** [comment]
Hi,

The version that is already installed on my server is v64, and I want to update it to v65. I ran the following instruction on my terminal server, but I got the following error:

`curl -s https://mailinabox.email/setup.sh | sudo bash

error:
fatal: not a git repository (or any of the parent directories): .git
bash: line 76: [: v65: unary operator expected
bash: line 87: setup/start.sh: No such file or directory

Please help me.

**Comment by blok82** [comment]
It is ok now.  I just did the upgrade again (i also had the weird version number) and now it says v65

**Comment by rainyskye** [comment]
> Hi,
> 
> The version that is already installed on my server is v64, and I want to update it to v65. I ran the following instruction on my terminal server, but I got the following error:
> 
> `curl -s https://mailinabox.email/setup.sh | sudo bash
> 
> error:
> fatal: not a git repository (or any of the parent directories): .git
> bash: line 76: [: v65: unary operator expected
> bash: line 87: setup/start.sh: No such file or directory
> 
> Please help me.

Please create a separate issue for this. This issue is referring to the misreporting of version numbers.

**Comment by liny-fox** [comment]
This can be closed now with release 66 as this maybe seems to have fixed itself.

✓  Mail-in-a-Box is up to date. You are running version v66.

**Comment by rainyskye** [comment]
> This can be closed now with release 66 as this maybe seems to have fixed itself.

Yep, same here :)
