### ISSUE TITLE
Installation script is failing on ubuntu 22.04 

### ISSUE THREAD

**Issue by LuD1161** [mail-in-a-box/mailinabox#2335]
First of all thanks for the awesome project 👋 

I've previously install MIAB on ubuntu 22.04 LTS, almost 4-5 months back. But now it's failing.
There are multiple issues and some solutions that I did for them - 
1. `virtualenv` installation folders, path have changed. Hence now this is failing at `setup/management.sh` line number 34 & 39. 
I fixed this by adding the correct path like this -
<img width="1617" alt="image" src="https://github.com/mail-in-a-box/mailinabox/assets/17861054/45b4c3d4-302b-47b6-addd-ebc89d10ca41">

However, I am getting into this error - 

```
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: pypng, expiringdict, exclusiveprocess, rtyaml, qrcode, pyotp, pycparser, psutil, pillow, multidict, MarkupSafe, itsdangerous, gunicorn, frozenlist, click, blinker, attrs, async-timeout, yarl, Werkzeug, Jinja2, cffi, aiosignal, pycares, flask, cryptography, aiohttp, aiodns, postfix-mta-sts-resolver
  Attempting uninstall: blinker
    Found existing installation: blinker 1.4
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Has someone faced a similar issue ?

## OS version
<img width="745" alt="image" src="https://github.com/mail-in-a-box/mailinabox/assets/17861054/95e4a565-e1d8-4e33-8918-96666565f8e6">

**Comment by MarcosBL** [comment]
+1 breaking here with the exact steps and errors

**Comment by kiekerjan** [comment]
There is some discussion [here](https://askubuntu.com/questions/1406304/virtualenv-installs-envs-into-local-bin-instead-of-bin) that seems to describe the same issue. However, I would first like to get some additional information, like:
 * Did you get a fresh Ubuntu 22.04 VPS? Or upgrade an existing one?
 * How did you install the system, which command are you using?
 * There might be a VPS specific issue. Which provider are you using?

Instead of changing code, could you post the original issues (errors, messages, installation output etc) you're facing?

**Comment by samos028** [comment]
To make things work quickly I removed blinker (dpkg -r python3-blinker) and its associated packages, and it worked. Definitively not the ideal method, but good enough for now and for my needs.

**Comment by dms00** [comment]
Okay, after a quick review, the tl;dr version is, if you add this to your environment it should fix how the venv is being built:

`export DEB_PYTHON_INSTALL_LAYOUT='deb'`

The setup script only appears to build the virtualenv if the directory is missing, so you will need to *first* remove that venv directory, `/usr/local/lib/mailinabox/venv`, before re-running the install. And if you're using `sudo` to run mailinabox, make sure that the environment variable is being preserved by using the `--preserve-env` option.

**Comment by awkto** [comment]
This worked for me, adding the env var as per @dms00 
`export DEB_PYTHON_INSTALL_LAYOUT='deb'`

**Comment by dms00** [comment]
Thanks for the feedback. Glad it worked.

I didn't have any way to test this fix because I cannot reproduce this problem on my MiaB server. So, there's more going on here than I understand at this point.

**Comment by dms00** [comment]
This comment from the "askubuntu.com" link I posted seems to be crucial:

<img width="654" alt="Screenshot 2023-11-27 at 19 46 37" src="https://github.com/mail-in-a-box/mailinabox/assets/10622016/f606210b-e872-4527-97e5-8fb7eb8c2a0d">

Could someone who has this problem on their system, please check if you have python3-distutils installed on your system? And if you do not, please install it and see if that resolves the issue.

**Comment by RobWW** [comment]
My bad luck, tonight I decided to test installing mailinabox on a fresh Ubuntu 22.04 (LTS) x64  Digital Ocean instance and have run into the above error.  Python3-distutils version 3.10.8-1~22.04 does appear to be installed:

```
sudo apt-get install python3-distutils
python3-distutils is already the newest version (3.10.8-1~22.04).

dpkg -S python3-distutils
python3-distutils: /usr/share/lintian/overrides/python3-distutils
python3-distutils: /usr/share/doc/python3-distutils/copyright
python3-distutils: /usr/share/doc/python3-distutils
python3-distutils: /usr/share/doc/python3-distutils/changelog.Debian.gz
python3-distutils: /usr/share/doc/python3-distutils/README.Debian
```

**Comment by LuD1161** [comment]
Hey Everyone 👋 

Thanks for helping resolve the issue.  
@kiekerjan I had a look at your fork, I see a lot of improvements there. Thanks for maintaining it.

**Comment by LuD1161** [comment]
I've just set the env var on a fresh machine ( didn't even run `apt update` or `apt upgrade` ) and it worked 😄 
`export DEB_PYTHON_INSTALL_LAYOUT='deb'` Thanks @dms00 for the suggestion 😄 
<img width="1063" alt="image" src="https://github.com/mail-in-a-box/mailinabox/assets/17861054/85cadd87-05af-46d7-ae4d-21c45e7b983c">

**Comment by MarcosBL** [comment]
@dms00 suggestion worked like a charm, thanks mate !

`export DEB_PYTHON_INSTALL_LAYOUT='deb'`

**Comment by ypeskov** [comment]
But maybe it should be at least documented somehow?  I yesterday also stuck with it and the above solution worked. But it looks like a workaround and not a robust solution.

**Comment by kiekerjan** [comment]
And depending on the cause we might want to include a code change to management.sh

**Comment by JoshData** [comment]
Great sleuthing! We'll set this environment variable automatically in the next Mail-in-a-Box update (see 371f5bc1).

**Comment by capitancurt** [comment]
I tried everything I could think of last night.
This morning, I tried a bare metal install, no updates, ran 
"export DEB_PYTHON_INSTALL_LAYOUT='deb'"
prior to any command, then ran the install, and this happens...still....


*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*
Installing nsd (DNS server)...
Generating DNSSEC signing keys...
No keypair found. Generating daemon's PGP keypair...
Generated key with fingerprint 9288A8DBC35E8C7CB22A63940AB01FD56FF954BC
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Creating new user database: /home/user-data/mail/users.sqlite
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...

Upgrading to Nextcloud version 24.0.7

Nextcloud is already latest version
photos 1.6.0 disabled
dashboard 7.4.0 disabled
activity 2.16.0 disabled
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...

FAILED: /usr/local/lib/mailinabox/env/bin/pip install --upgrade pip
-----------------------------------------
setup/functions.sh: line 17: /usr/local/lib/mailinabox/env/bin/pip: No such file or directory

**Comment by ypeskov** [comment]
> I tried everything I could think of last night. This morning, I tried a bare metal install, no updates, ran #export DEB_PYTHON_INSTALL_LAYOUT='deb' prior to any command, then ran the install, #sudo apt install curl locales -y #sudo dpkg-reconfigure locales #sudo curl -L https://power-mailinabox.net/setup.sh | sudo bash
> 
> and this happens...still....
> 
> _++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_++_ Installing nsd (DNS server)... Generating DNSSEC signing keys... No keypair found. Generating daemon's PGP keypair... Generated key with fingerprint 9288A8DBC35E8C7CB22A63940AB01FD56FF954BC Installing Postfix (SMTP server)... Installing Dovecot (IMAP server)... Creating new user database: /home/user-data/mail/users.sqlite Installing OpenDKIM/OpenDMARC... Installing SpamAssassin... Installing Nginx (web server)... Installing Roundcube (webmail)... Installing Nextcloud (contacts/calendar)...
> 
> Upgrading to Nextcloud version 24.0.7
> 
> Nextcloud is already latest version photos 1.6.0 disabled dashboard 7.4.0 disabled activity 2.16.0 disabled Installing Z-Push (Exchange/ActiveSync server)... Installing Mail-in-a-Box system management daemon...
> ## FAILED: /usr/local/lib/mailinabox/env/bin/pip install --upgrade pip
> 
> setup/functions.sh: line 17: /usr/local/lib/mailinabox/env/bin/pip: No such file or directory

you should run --preserve-env

#sudo curl -L https://power-mailinabox.net/setup.sh | sudo --preserve-env  bash

in my case it was like this:
sudo --preserve-env curl -s https://mailinabox.email/setup.sh | sudo -E bash

**Comment by capitancurt** [comment]
After a "successful installation", I get a new error on the Admin Backup page.
[Errno 2] No such file or directory: '/usr/local/bin/duplicity'

**Comment by awkto** [comment]
It is still failing for me. I tried the solutions proposed

```
export DEB_PYTHON_INSTALL_LAYOUT=  'deb'
sudo --preserve-env curl -L https://power-mailinabox.net/setup.sh | sudo --preserve-env bash
```

Still fails at 
```
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...

FAILED: /usr/local/lib/mailinabox/env/bin/pip install --upgrade pip
-----------------------------------------
setup/functions.sh: line 17: /usr/local/lib/mailinabox/env/bin/pip: No such file or directory
```

Can't install Mailinabox on Ubuntu 22.04

**Comment by demha-theFirstOne** [comment]
Hello
I have the same issue. I try the work arround with --preserve and that's not better.
I'm starting from a fresh install, nothing on the vps , I try with an apt update or from scratch and the issue always occur.
I also try to create a virtual link to pip as it works fine (if I try "pip install --upgrade pip", it s ok, thats only the path who is wrong)  , but its another fail. There is a fix or a previous stable release I can try ?

**Comment by capitancurt** [comment]
I just repeated the experiment...baremetal...tried Ubuntu server 23...but Dave hasn't addressed 23 yet...so, I loaded Ubuntu Server 20.04

Only commands given prior to installation was to change the root password.

I ran the standard install procedure, and everything appears to be working just fine...seems that Jammy just broke itself. Bummer.

So, at lease I have an option. ( I have a large project where I will be loading up a few dozen iterations of PMIAB..so I was about to panic.)

**Comment by nishchayjeet** [comment]
Quick note if still getting error -  /usr/local/lib/mailinabox/env/bin/pip: No such file or directory
1. Set the Environment Variable: 
 export DEB_PYTHON_INSTALL_LAYOUT='deb'
2. . Remove the Existing Virtual Environment:
sudo rm -r /usr/local/lib/mailinabox/env
3. sudo --preserve-env curl -s https://mailinabox.email/setup.sh | sudo -E bash

These 3 steps should run the installation without errors

**Comment by HusseinKhazem** [comment]
Remove Current Python Enviroment and then re create it and try running the script again. Worked for me


rm -rf /usr/local/lib/mailinabox/env  >> REMOVE ENVIROMENT

apt install python3.10-venv   >> DOWNLOAD VENV 

python3 -m venv /usr/local/lib/mailinabox/env >> CREATE NEW VIRTUAL ENV

Run the Script Again, It definitely should work, i updated 5 mail servers all of them faced this problem and i fixed all of them like this.
