### ISSUE TITLE
Migrate away from CDNs hosting the CSS / Font / JS assets

### ISSUE THREAD

**Issue by bnvk** [mail-in-a-box/mailinabox#234]
Wearing my slightly paranoid / infosec / privacy hat for a moment- I noticed that currently the `/admin` area of Mail-in-a-box serves all the front-end assets from numerous CDNs

* https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
* https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css
* https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js
* https://fonts.googleapis.com/css?family=Raleway:400,700
* https://fonts.googleapis.com/css?family=Ubuntu:300

It would be nice to have these assets served locally from my trusted Mail-in-a-box server instead of via CDN. There will be a very tiny performance hit the first time I access my 'box but then caching will take care of it. I believe the privacy / security implications far outweigh the performance.

I'm happy to send a pull req with this modification if you agree @JoshData

**Comment by martindale** [comment]
+1!  Yes, please.

**Comment by lloydsmart** [comment]
If you [I]really[/I] want to avoid making a call to a server, you could download them via a magnet link.

**Comment by dhpiggott** [comment]
Nice!

**Comment by fkooman** [comment]
In 0.16 this is still an issue. It still requests CDN versions of at least jQuery and Bootstrap. Adding integrity check does not solve all problems with CDN versions of libraries. For example, every time those libraries are not obtained from cache, Google finds out what site is using them through the Referer/Origin header.

If those libraries are self-hosted (and inline scripts moved to files) a really strict CSP [1] can also be used to further secure the user.

[1] https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_Content_Security_Policy

**Comment by tasmo** [comment]
Please avoid forcing Mail-in-a-Box admins be tracked by Google and Bootstrap.
