### ISSUE TITLE
Github, website and GUI show different latest version numbers (v64, v65, v66)

### ISSUE THREAD

**Issue by nomandera** [mail-in-a-box/mailinabox#2341]
As per title:

- [Github ](https://github.com/mail-in-a-box/mailinabox/releases) is currently showing v64 as latest release
- the [website ](https://mailinabox.email/)shows v65
- MIAB itself show v66

**Github**
![image](https://github.com/mail-in-a-box/mailinabox/assets/1133344/fc4a71cc-514e-4bbc-b708-7a39229a410a)
**Website**
![image](https://github.com/mail-in-a-box/mailinabox/assets/1133344/6f6452a9-35d7-48d7-b7d1-34515a1fa33d)
**MIAB GUI**
![image](https://github.com/mail-in-a-box/mailinabox/assets/1133344/ae6c4ec6-afb5-4b8f-92f4-a8825064e9db)

v66 appears hot of the press so today specifically is likely a worst case scenario

**Comment by SConaway** [comment]
And now with v67 out, this mismatch is still going on.

**Comment by nomandera** [comment]
@JoshData if you have a moment could you line these up to close this ticket please. Suspect it is just a matter of confirming all should be latest (v67 as today).

**Comment by JJJ** [comment]
This is fixed now. Everything is showing v68. 👍

**Comment by nomandera** [comment]
Confirmed. Everything shows v68. Thanks for the update.
