### ISSUE TITLE
z-push won't push to iOS when /etc/timezone is incorrect

### ISSUE THREAD

**Issue by nstanke** [mail-in-a-box/mailinabox#235]
iOS users didn't recieved push notifications until the correct timezone were set (/etc/timezone). 

``dpkg-reconfigure tzdata``

Which is used at https://github.com/mail-in-a-box/mailinabox/blob/5714b3c6b735cf42bde34e77ab21e7d0274f8cfc/setup/zpush.sh#L48

I would suggest to make sure the correct timezone is set before executing ``zpush.sh``

**Comment by JoshData** [comment]
Commit above sets the timezone, so closing.
