### ISSUE TITLE
Weird output (from Roundcube?) during install

### ISSUE THREAD

**Issue by JJJ** [mail-in-a-box/mailinabox#2354]
See screenshot for `wal`:

![jjj-2024-01-24-at-22-34-06-UTC@2x](https://github.com/mail-in-a-box/mailinabox/assets/88951/d5e2c374-fd8f-4353-a499-96ad46044437)

**Comment by solomon-s-b** [comment]
It's just the output of the following command:

```shell
sqlite3 $STORAGE_ROOT/mail/roundcube/roundcube.sqlite 'PRAGMA journal_mode=WAL;'
```
which runs at the end of the bash script: "webmail.sh".

It can be suppressed by adding "| 2>&1" at the end of that command:

```shell
sqlite3 $STORAGE_ROOT/mail/roundcube/roundcube.sqlite 'PRAGMA journal_mode=WAL;' | 2>&1
```

However I'm not sure if it is necessary.

**Comment by JJJ** [comment]
🫶
