### ISSUE TITLE
owncloud-unlockadmin.sh has incorrect path for mail.py

### ISSUE THREAD

**Issue by goop32** [mail-in-a-box/mailinabox#2370]
I was trying to unlock the Nextcloud admin when I kept running into an error:

root@box:~/mailinabox/tools# ./owncloud-unlockadmin.sh 
./mail.py: line 3: management/cli.py: No such file or directory
I am going to unlock admin features for .
You can provide another user to unlock as the first argument of this script.

WARNING: you could break mail-in-a-box when fiddling around with Nextcloud's admin interface
If in doubt, press CTRL-C to cancel.

Press enter to continue.

Not enough arguments (missing: "user").  
                                           

group:adduser <group> <user>

When mail.py tried to use cli.py, it kept saying there was no such file or directory and wouldn't find my email address. I opened it up and found the path is incorrect and should have a ../ at the beginning. The "management" folder is not kept inside of the tools directory and therefore will not launch the correct script. I fixed this by making it use the path to the file (/root/mailinabox/management/cli.py in my case) but there's probably a better way to do that.

**Comment by goop32** [comment]
You mean I should be in /root/mailinabox and then run ./tools/owncloud-unlockadmin.sh? It still doesn't work.
<img width="682" alt="Screenshot 2024-03-21 at 16 49 11" src="https://github.com/mail-in-a-box/mailinabox/assets/34921800/d755115b-2dcf-45cf-9e54-50ff9b7cc530">

**Comment by goop32** [comment]
You mean run it from /root/mailinabox (parent directory) and do ./tools/owncloud-unlockadmin.sh? That still isn't working for me.
<img width="682" alt="Screenshot 2024-03-21 at 16 49 11" src="https://github.com/mail-in-a-box/mailinabox/assets/34921800/b84ce152-923c-4a04-baab-b578735eb4b3">

**Comment by JoshData** [comment]
Ah ok the error is in owncloud-unlockadmin.sh then. Thanks, yeah, that's a bug.

**Comment by JJJ** [comment]
I wasn't able to quickly figure out how to variablize the path, so I used `$PWD` because I saw it was used elsewhere:

```bash
ADMIN=$($PWD/mailinabox/tools/mail.py user admins | head -n 1)
```

and...


```py
$PWD/mailinabox/management/cli.py "$@"
```

If that's acceptable I'll put together a PR (but I also suspect there must be a better way.)

**Comment by goop32** [comment]
Confirmed working on latest update, closing.
