### ISSUE TITLE
No password prompt during v69 install which causes install to quit

### ISSUE THREAD

**Issue by mattfraley1** [mail-in-a-box/mailinabox#2408]
I am attempting to move from digital ocean to a different host. I installed at digital ocean just a couple of months ago and everything we just fine. 

I am running through the install at the new provider and when when it asks for an email address in a box that says, "Let's create your first mail account". Immediately after selecting OK, the setup ends with "No password provided". 

I rebuilt the server and tried again just to make sure I didn't mess something up, but I still got the same result.

I rebuilt the server one more time and added an environment variable TAG=v68 and then this installation worked just fine. It would seem there is some issue with the latest version.

**Comment by JoshData** [comment]
The bug is probably caused by the change at https://github.com/mail-in-a-box/mailinabox/pull/1457/files#diff-218a250cb0ddbfa432b6d0ea10ded1103300de84cf5309effb9cf870ab70a99dL50.

Paging @tdulcet. Seems like you may have broken the entire project.

**Comment by MartinBalerio** [comment]
Can confirm.

**Comment by tdulcet** [comment]
> Paging @tdulcet. Seems like you may have broken the entire project.

Sorry about that. 😔 I will create a new PR shortly to fix this...

Note that I add added automated testing with GitHub Actions in #1455 specifically to catch issues like this.

**Comment by MartinBalerio** [comment]
Thank you @tdulcet for the prompt fix, now able to upgrade to 69a via curl.
