### ISSUE TITLE
Fresh install does not load admin page

### ISSUE THREAD

**Issue by JoshWho** [mail-in-a-box/mailinabox#2412]
I tried this about 8 times now and it keeps showing a page with no css or graphix. 
![image](https://github.com/user-attachments/assets/cb0d05ce-d719-476c-81ea-55bdb11a491d)

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/2fa46be8-4d68-4863-bbda-f95600020e80)

**Comment by JoshWho** [comment]
on the css assists and images nginx is giving a 403 error. THis is a fresh install I changed nothing

**Comment by JoshWho** [comment]
I am now seeing others talk about this on the main website forums here https://discourse.mailinabox.email/t/admin-panel-broken-after-restore-upgrade/12112/10

**Comment by JoshWho** [comment]
It is missing the whole www directory admin assets everything for the panel. There is a huge bug in this

**Comment by JoshData** [comment]
Fixed (hopefully) in 60a2b58e5735308c1f6f3292271948f8730b9559. I believe it was broken by https://github.com/mail-in-a-box/mailinabox/pull/1457/commits/67bcaea71e8d59e34787f5fd708ab4f664967e9d.

**Comment by JoshWho** [comment]
> Fixed (hopefully) in [60a2b58](https://github.com/mail-in-a-box/mailinabox/commit/60a2b58e5735308c1f6f3292271948f8730b9559). I believe it was broken by [67bcaea](https://github.com/mail-in-a-box/mailinabox/commit/67bcaea71e8d59e34787f5fd708ab4f664967e9d).

Giving it a try now

**Comment by JoshWho** [comment]
> Fixed (hopefully) in [60a2b58](https://github.com/mail-in-a-box/mailinabox/commit/60a2b58e5735308c1f6f3292271948f8730b9559). I believe it was broken by [67bcaea](https://github.com/mail-in-a-box/mailinabox/commit/67bcaea71e8d59e34787f5fd708ab4f664967e9d).

That did the trick. Thank you
