### ISSUE TITLE
How do you add a second domain to this?

### ISSUE THREAD

**Issue by JoshWho** [mail-in-a-box/mailinabox#2414]
I have exhausted chatgpt and Grok trying to figure this it. Every instruction it tells me is not a option in this new version of mail in a box.

THis is what it say to do

Step 2: Add the Domain to Mail-in-a-Box
Log in to your Mail-in-a-Box admin interface (usually at https://box.example.com/admin).

Navigate to the Domains section:

Go to System -> Domains.
Add your second domain:

Enter your second domain (e.g., secondexample.com) and click Add Domain.

There is no menu that says domains

**Comment by JoshWho** [comment]
I think I figured it out. adding a user for the new domain seems to add the domain also.

**Comment by JoshData** [comment]
Please don't post ChatGPT bullshit in this project. It wastes the time of everyone trying to help.

**Comment by JoshWho** [comment]
Sorry was just trying to figure out the new method to adding domains and there was nothing out there that said what I figured out. JUst showing an example what is publicly found trying to add a domain. SHould be some kind of wiki or instructions for the new method.

**Comment by JoshData** [comment]
There is no new method. It's been like this for 10 years.

**Comment by JoshWho** [comment]
I don't remember the Ubuntu 18 version like that. It use to have a conf to put the domains in.

**Comment by JoshData** [comment]
If that's the case and I am mis-remembering, I need to go on a very long vacation.
