### ISSUE TITLE
Ability to configure as purely email server

### ISSUE THREAD

**Issue by jbailey74** [mail-in-a-box/mailinabox#2443]
I love mail-in-a-box, makes it so easy to setup my email server.....but that is all I want it for, an email server. I control my DNS via my server provider, and I have a separate server for hosting the web content of my domain.  I would love to see the ability to not have mail-in-a-box want to provide these options, and complain about them in the system checks (e.g. that www.domain isn't pointing to this box, etc)

**Comment by JoshData** [comment]
Same as #2397 and many earlier issues.
