### ISSUE TITLE
Add Ubuntu 24.04 support?

### ISSUE THREAD

**Issue by melroy89** [mail-in-a-box/mailinabox#2449]
Ubuntu 24.04 is the official latest LTS release. I believe it makes sense to add support for 24.04: https://github.com/mail-in-a-box/mailinabox/blob/1699ab8c02e6813075a65fff9903c85e31d52445/setup/bootstrap.sh#L23

Currently only 22.04 is supported too bad.

**Comment by lostsightt** [comment]
are u fucking schizo?

**Comment by Synchro** [comment]
That's very nice for you. Are you offering to do all the necessary upgrades and handle all the support requests that result from it? 22.04 is fine; it will be supported for years.

**Comment by arachnotaurus** [comment]
@lostsightt That's unnecessarily rude.

@melroy89 Josh has answered this in the past, there's kind of an "every other LTS" pattern with MIAB. The next LTS supported will probably be 26.04.

**Comment by JoshData** [comment]
I blocked the user and hid the comment. I'm going to lock the conversation and close the issue since @arachnotaurus answered it (thanks).
