### ISSUE TITLE
Contacts not syncing to iOS 8.1 device, Z-Push 403 error

### ISSUE THREAD

**Issue by bl00513** [mail-in-a-box/mailinabox#253]
I am running the latest version of mailinabox on a DO Droplet, Ubuntu 14.04. I haven't noticed any problems, except for syncing contacts to my iOS 8.1 device. Everything but the contacts syncs just fine, including calendar events. I haven't touched the carddav backend config file at all, so I don't think it's something I've done wrong. I checked the z-push error file, and I'm seeing the following error over and over: 

>27/10/2014 15:23:43 [ 8911] [ERROR] [user@domain] BackendCardDAV->GetMessageList - Error     >getting the vcards in   >'https://localhost:443/cloud/remote.php/carddav/addressbooks/user@domain/contacts/': Woops,   >something's gone wrong! The CardDAV server returned the http status code 403.
>27/10/2014 15:23:43 [ 8911] [ERROR] [user@domain] BackendCardDAV->GetMessageList - Error >getting the vcards

Is this possibly a bug? Do you have any ideas to help troubleshoot or test? Thanks!

**Comment by sphildreth** [comment]
BackendCardDAV->ChangesSinkInitialize - Error doing the initial sync for 'https://localhost:443/cloud/remote.php/carddav/addressbooks/stev
en@hildreth.email/contacts/': Woops, something's gone wrong! The CardDAV server returned the http status code 403.
    
Same here trying to use Outlook 2013 Exchange ActiveSync setting.

**Comment by fmbiete** [comment]
Your carddav server should show more info about the authentication error. But I would say that's related to the config option: USE_FULLEMAIL_FOR_LOGIN being false as default (unknowed reasons of Zarafa for doing that).
So, if your email is steven@domain.com only steven will be used as your username.
Be very careful with that.

**Comment by JoshData** [comment]
We set `USE_FULLEMAIL_FOR_LOGIN` to `true` ([here](https://github.com/mail-in-a-box/mailinabox/blob/3d21f2223e83f09a94368608952933f3e3843741/setup/zpush.sh#L44)), so that shouldn't be the problem. Thanks for weighing in here.

**Comment by bl00513** [comment]
I wanted to update this issue. @JoshData, you may want to consider closing this issue. I am on MIAB v0.13b and iOS version 8.4. Contacts and Calendars both seem to be syncing fine through z-push. I believe one of the previous versions of z-push contrib fixed whatever the compatibility issue with Owncloud was.

**Comment by JoshData** [comment]
Ok.
