### ISSUE TITLE
Allow configuration of backups.

### ISSUE THREAD

**Issue by cooperaj** [mail-in-a-box/mailinabox#262]
I see you're using duplicity for backups. I love this and use it on my servers for nightly backups to S3. It is highly configurable in that regard.

I think exposing some of the options it provides (such as S3 or Google Drive) in the UI would make a lot of sense.

**Comment by PortableTech** [comment]
I think a process for automating the transfer of backups to another server such as S3 is very important and should be given consideration.  Despite the fact that this replaced https://github.com/mail-in-a-box/mailinabox/issues/11 the last entry in that issue has a great S3 solution.  If we are not looking to use duplicity to accomplish this, perhaps a simple interface to provide S3 info to use in a script with this solution. 

 I have implemented this on my own box and it works great.

**Comment by JoshData** [comment]
Yes, let's use Duplicity for this.

**Comment by JoshData** [comment]
Let's combine this issue with #228.
