### ISSUE TITLE
iOS 8.1: Exchange account doesn't save Sent mail or Drafts

### ISSUE THREAD

**Issue by qwzybug** [mail-in-a-box/mailinabox#266]
I suspect this is not significantly different from other issues (e.g., #126, #256), but it seemed worth writing down.

From a fresh mail-in-a-box install, I set up my only email account as an Exchange account on my iPhone, and configured it to push new mail. I set the account to Archive deleted messages, rather than Trash them. When I tried to archive a message, I got an error that the message couldn't be moved; creating a mailbox named "Archive" in the webmail client seemed to fix this.

However,
- Messages sent from iPhone don't appear in Sent mailbox on server (though they do appear there in the iPhone client)
- Messages drafted on iPhone don't appear in Drafts mailbox on server (though they do appear there in the iPhone client)

When I deleted the account and re-made it as an IMAP account, everything seemed to work properly, and I was able to see edits made to drafts on the iPhone and webmail client stay in sync, etc.

Exchange support would be a killer feature—push mail, theoretically, uses less battery than IMAP IDLE (or even polling, they say), and Google no longer offers Exchange or push support for hosted domains. It would be a good reason to suffer roundcube, and shoulder the burden of sysadminning an important system.

I'd love to help diagnose this problem. I'm running mailinabox on a non-critical domain currently; let me know what I could do to poke around and try to figure out what's going wrong with z-push, or what have you.

**Comment by bl00513** [comment]
+1 to what @fpgaminer said... I am also unable to replicate the sent items issue.
