### ISSUE TITLE
Using DAVdroid with self-signed cert fails.

### ISSUE THREAD

**Issue by hnk** [mail-in-a-box/mailinabox#271]
Hi there,

I tried to sync my contacts with DAVdroid, but it fails with a "Cannot verify hostname" error.

This seems to happen because the self-signed certificate is not setting "Basic Constraints ("CA flag")" correctly.
From DAVdroid (http://davdroid.bitfire.at/faq/entry/importing-a-certificate):
>Important: If you can import the certificate with errors, but it doesn't show up in the certificate list, >make sure that the CA extension is available and Basic Constraints ("CA flag") are set correctly. The >certificate details must have the X509v3 Basic Constraint "CA:TRUE".

I am no expert with ssl, but would encourage proper use of syncing mechanisms even with self signed certificates.

**Comment by SourcemakerHD** [comment]
Why do we need this? No one is creating a self signed certificate with a CA FLAG :-1: Other android apps also work like a charm without CA flag.

**Comment by JoshData** [comment]
Fixed by #268 - there's no longer a reason to use self-signed certs.
