### ISSUE TITLE
ownCloud fails to sync, Internal Server Error 500

### ISSUE THREAD

**Issue by 0xFelix** [mail-in-a-box/mailinabox#273]
Yesterday I tried to sync the contents of my Dropbox to my new ownCloud.
However ownCloud reported "500 Internal Server Error" several times.

Further investigation shows that ownCloud writes "SQLSTATE[HY000]: General error: 5 database is locked" to its logfile.
Researching this issue shows a lot of discussions, but no real solution other than migrating away from SQLite.

I assume mailinabox is not intended for only a single user per instance and this state makes it more or less useless. File syncing via the ownCloud client should work for multiple users / heavier loads. :(

Is a migration to MySQL possible?

**Comment by JoshData** [comment]
I don't see it in 7.0.4.

You can actually turn it on without ownCloud's cooperation.

    $ sqlite3 /home/user-data/owncloud/owncloud.db
    sqlite> PRAGMA journal_mode=WAL;

https://www.sqlite.org/wal.html

**Comment by 0xFelix** [comment]
My fault, seems like it will not be available until version 8.0 is released.

I will give it a try!

**Comment by 0xFelix** [comment]
The errors still occur :-1: 

Being able to use ownCloud to its full extent would be really nice.

**Comment by JoshData** [comment]
Closing because of #514.
