### ISSUE TITLE
Only primary domain can access /cloud/ endpoint

### ISSUE THREAD

**Issue by hnk** [mail-in-a-box/mailinabox#278]
I just noticed that any extra domain I host on my miab can reach roundcube via the "/mail/" endpoint.
But I cannot reach "/cloud/".

For example:

My domain is: foo.com
Hostname is: box.foo.com
I add a second domain: bar.io
And create a subdomain by creating an alias address: box.bar.io

Now I can reach the following things:

* box.foo.com/admin
* box.foo.com/mail
* box.foo.com/cloud
* www.foo.com/admin
* www.foo.com/mail
* www.foo.com/cloud
* www.bar.io/admin
* www.bar.io/mail
* www.bar.io/cloud <- this actually gives an owncloud error. I will file another report for that :)

But then it gets weird:
* foo.com/mail works
* foo.com/cloud does not
* foo.com/admin does not
* bar.io/mail works
* bar.io/cloud does not
* bar.io/admin does not
* box.bar.io/mail works
* box.bar.io/cloud does not
* box.bar.io/admin does not

I can understand that one may not want to expose the "/admin/" endpoint on all domains. But if "/mail/" is reachable everywhere, shouldn't "/cloud/" be as well?

Maybe we can talk about what should work and not and I can create some pull requests.

**Comment by dofl** [comment]
I've been digging in the trusted_domains config of owncloud, but it's no more then a simple list of domains. It wouldn't be too hard to implement that upon adding or removing a domain, this list gets updated too.

If i'm correct, the only thing needed then is the same /cloud entries in nginx for the domains other then the hostname of the box. Am I missing something as you are talking about re-architecting owncloud?

**Comment by JoshData** [comment]
I was just saying that the code that generates the owncloud config will have to be changed.

**Comment by JoshData** [comment]
Closing because of #514.
