### ISSUE TITLE
Namecheap SSL keys

### ISSUE THREAD

**Issue by busla** [mail-in-a-box/mailinabox#284]
To all of you that are having trouble adding the Namecheap SSL keys.

The intermediary keys need to be added in this order:
COMODORSADomainValidationSecureServerCA.crt
COMODORSAAddTrustCA.crt

**Comment by shageman** [comment]
Thanks @busla! I was stuck until I saw this.

I added the info to the FAQ and think this issue should be closed in favor of keeping the info there: https://github.com/mail-in-a-box/mailinabox/wiki/FAQ

**Comment by chuckpeters** [comment]
The FAQ is displaying the URL for issue 284. but the link posted is going to the wrong place.

**Comment by shageman** [comment]
Fixed. I suggest this issue be closed.
