### ISSUE TITLE
Raspberry PI support

### ISSUE THREAD

**Issue by patrickjohncollins** [mail-in-a-box/mailinabox#285]
Could Mail-in-a-box conceivably run on a Raspberry PI one day?  What would be the main challenges to overcome?  I quite like the idea of having my own mail server for €36/year : http://raspberrycolocation.com/

**Comment by fritzy** [comment]
Ubuntu may eventually support the Raspberry Pi, like SUSE did. https://www.raspberrypi.org/blog/suse-linux-enterprise-server-for-raspberry-pi/

**Comment by spock** [comment]
@patrickjohncollins , @fritzy - there exists a [no longer maintained Ubuntu 14.04 RPi image](https://wiki.ubuntu.com/ARM/RaspberryPi#Ubuntu_14.04_LTS).
