### ISSUE TITLE
owncloud from OBS

### ISSUE THREAD

**Issue by grepwood** [mail-in-a-box/mailinabox#286]
Wouldn't it be easier to just use OBS repositories to install owncloud rather than pull the official .zip?
http://software.opensuse.org/download.html?project=isv:ownCloud:community&package=owncloud
Both Ubuntu and CentOS have up-to-date versions of owncloud there.

**Comment by grepwood** [comment]
Just tried it out. owncloud from OBS depends on Apache and `php`, which is version 5.4.

**Comment by JoshData** [comment]
That explains why we don't do that. Close?

**Comment by grepwood** [comment]
For now, yeah. It's possible to trick OBS into thinking that the package `php` is actually php 5.5 from Remi's repository, but the tight coupling with Apache really spoils the rest.
