### ISSUE TITLE
MIAB confuses users with little memory

### ISSUE THREAD

**Issue by grepwood** [mail-in-a-box/mailinabox#289]
`setup/preflight.sh` originally computes TOTAL_PHYSICAL_MEM from KiB of RAM present on the system. You can see this if you omit the awk part of the derivation of this variable.
Using the erroneous value later on can cause confusion as MIAB will claim to demand anywhere up to "786431 MB RAM", as in line 43.
Additionally, I changed the units to MiB in https://github.com/grepwood/mailinabox/commit/b24f40e8a373d111cfaa3a3749a0d2e38cea0910 because that is way more accurate and it won't confuse people who use powers of 1000 in their VM's memory allowance. With QEMU, the value in powers of 1000 is around 790MB.

**Comment by JoshData** [comment]
Thanks, I've improved it.
