### ISSUE TITLE
hide_output causing trouble when a conflict needs to be resolved by the user

### ISSUE THREAD

**Issue by angurise** [mail-in-a-box/mailinabox#291]
I was stuck during the installation when I was waiting for:
```installing bind9 resolvconf ...```

It seems to take forever for it to install. I lost patience and hit Ctrl+C. Seems like dpkg was actually waiting for me to make a choice:

```
Setting up bind9utils (1:9.9.5.dfsg-3ubuntu0.1) ...
Setting up bind9 (1:9.9.5.dfsg-3ubuntu0.1) ...
Configuration file '/etc/init.d/bind9'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** bind9 (Y/I/N/O/D/Z) [default=N] ? E: Sub-process /usr/bin/dpkg exited unexpectedly
W: Operation was interrupted before it could finish
```

So the function hide_output (and apt_install using it) was actually causing trouble because the user didn't get a chance to make a choice, and it seems to be stuck at this step.

The same issue happened again during another installation, when the installation seems to be stuck at "Updating system packages..."

```
Installing new version of config file /etc/init/udev-fallback-graphics.conf ...
udev stop/waiting
udev start/running, process 4989
Removing 'diversion of /bin/udevadm to /bin/udevadm.upgrade by fake-udev'
update-initramfs: deferring update (trigger activated)
Setting up upstart (1.12.1-0ubuntu4.2) ...

Configuration file '/etc/cron.daily/upstart'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** upstart (Y/I/N/O/D/Z) [default=N] ? E: Sub-process /usr/bin/dpkg exited unexpectedly
W: Operation was interrupted before it could finish
```

Edit: #270 seems to be similar to this.

**Comment by JoshData** [comment]
We don't touch either of those files, which means you're using an Ubuntu image that has been modified by your cloud provider in a way we can't predict.

Can you reproduce the problem? I'm not sure we can support that situation, but maybe we can at least have Mail-in-a-Box report a problem and not stall.

**Comment by angurise** [comment]
@JoshData I can reproduce problem on every Ubuntu installation of the specific provider, so I believe it is either that provider's or SolusVM's supplied OS images fault.

So it would be great if the installation script can show up error messages when a selection needs to be made, or maybe an option can be added to disable hide_output.

**Comment by h8h** [comment]
I also have a few boxes with a preinstalled bind9 causing the same problems @angurise described. Maybe we could get rid of it, if we simply set the `DEBIAN_FRONTEND` enviroment variable to `noninteractive`.

Credits: [How to answer an apt-get configuration change prompt](http://stackoverflow.com/questions/22957939/how-to-answer-an-apt-get-configuration-change-prompt-on-travis-ci-in-this-case)

**Comment by JoshData** [comment]
Yes please try that.

The `apt_get` macro in the install scripts already sets that, but the `apt-get upgrade` doesn't and should.

From that SO page, we should possibly do (for both `apt_get` and `apt-get upgrade`):

    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" . . .

To just force the reset of any file that packages want to update. Mail-in-a-Box will re-patch any file that it needs to modify.

**Comment by JoshData** [comment]
This should be fixed by the above commit.
