### ISSUE TITLE
Calendars not synced as expected with Windows Phone 8.1 Exchange ActiveSync

### ISSUE THREAD

**Issue by rockman73** [mail-in-a-box/mailinabox#293]
Successful install of mailinabox which includes owncloud 7.0.4 (stable) and Z-Push.

I've added my owncloud account to Windows Phone 8.1 using Exchange ActiveSync settings. Mail and Contacts appear to sync. Calendars do not sync as expected. What I see synced on my phone is just one single Birthday Calendar that I don't see in owncloud. I expect to see my primary calendar with events synced. I also have one shared calendar that does not sync either.

My bug with owncloud was closed https://github.com/owncloud/calendar/issues/664 and redirected to filling a bug here.

**Comment by JoshData** [comment]
Because of all of the problems with Z-Push, I don't recommend using it with Mail-in-a-Box. Fixing them is way over my head. We'll keep the issue open but don't hold your breath for a fix. :|

**Comment by rockman73** [comment]
I understand. 

In the meantime, the work-around for utilizing Card/CalDAV on Windows Phone 8.1 is to add a new iCloud account with Main-in-a-box credentials. Afterwards, go back into advanced settings and change the Card/CalDAV URLs to Mail-in-a-box owncloud specs and it appears to work. So far, so good here. 

It also helps to have at least a free class 1 SSL cert from StartSSL. Self-signed certs cause problems with authentication using this work-around.

**Comment by elwebmaster** [comment]
I think this is caused by lack of SYNC support in ownCloud, similar to the CardDav bug (see 6efeff6fceeae83d807e851cc5fb5b818dc38d07). I think I was able to fix it by changing 'CALDAV_SUPPORTS_SYNC' to 'false' in /usr/local/lib/z-push/backend/caldav/config.php .

**Comment by h8h** [comment]
I've tested this (Android 4.4.4 and its [`Corporate`](http://doc.zarafa.com/7.1/User_Manual/en-US/html/_setting_up_a_mobile_device.html) account)  and for me `CALDAV` works fine even with `CALDAV_SUPPORTS_SYNC` is set to `true`. But `CARDDAV` has this error I described in the issue so I only fixed this one.

**Comment by elwebmaster** [comment]
It wasn't working for me on BB10. I was getting these errors in the z-push.log:
z_caldav.php:908 Undefined index: /caldav/calendars/****@***/personal/ (8)
z_caldav.php:908 Undefined index: /caldav/calendars/****@***/contact_birthdays/ (8)
I created the 'contact_birthdays' calendar in ownCloud and renamed the personal to lowercase 'personal' but it didn't fix it. Then I set the 'CALDAV_SUPPORTS_SYNC' to 'false'. After disabling/enabling calendar sync on the device the errors disappeared. The calendar is now syncing properly both ways. May be @rockman73 can try this and report?

**Comment by rockman73** [comment]
@elwebmaster Thank you for the suggestion. I've changed 'CALDAV_SUPPORTS_SYNC' to 'false' in /usr/local/lib/z-push/backend/caldav/config.php, setup Exchange sync on my WP8.1 to my Mail-in-a-box server, but I sill do not see my personal and shared calendars, just "Contact birthdays" calendar syncing.

**Comment by elwebmaster** [comment]
@rockman73 do the personal and shared calendars exist in ownCloud? If not, try creating them. Then may be you can try creating a test event, forcing a sync and sharing some of the relevant logs from /var/log/z-push/z-push.log .

**Comment by rockman73** [comment]
@elwebmaster I created a "Personal" calendar and yes, I now see it synced. However, the 'CALDAV_SUPPORTS_SYNC' setting does not appear to make any difference for me. Why do I only see Personal and Contact birthdays calendars and not others? I do not see any errors in z-push-error.log and I see what appears to be normal operations in z-push.log.
