### ISSUE TITLE
some systems don't have /etc/timezone

### ISSUE THREAD

**Issue by grepwood** [mail-in-a-box/mailinabox#294]
Not having the timezone set will cause a trivial error while installing miab. However I'm not entirely sure if this is alright for the proper operation of the mailserver, so here's a quick fix:
add
```
if [ ! -f "/etc/timezone" ]; then
	tzselect > /etc/timezone
fi
```
before
```
TIMEZONE=$(cat /etc/timezone)
```

**Comment by JoshData** [comment]
`tzselect` is some interactive utility. If the file doesn't exist we might want to just default to `Etc/UTC` (in both Z-Push and owncloud setup), or during setup we can see if the file doesn't exist and run `dpkg-reconfigure tzdata` which I think should generate that file, but I'm not sure. Someone would need to test that that would work.

**Comment by JoshData** [comment]
See #328 for a warning about changing the timezone once it's been set.

**Comment by anoma** [comment]
I have not run this yet but looking at the commit perhaps we need to clarify best practice i.e. set timezone to physical location or mail server or principal user.

I personally set to my timezone as the "principal user" however now that I think about it I do not know if this has any implications with spam scoring etc.

Perhaps it does not matter?

**Comment by JoshData** [comment]
I don't think it matters.... so I'm closing the issue, for my sanity.

**Comment by anoma** [comment]
Agreed. I suspect it probably does matter but only in a very small and completely undocumented way.
