### ISSUE TITLE
nsd fails to start with ipv6 disabled

### ISSUE THREAD

**Issue by 0xFelix** [mail-in-a-box/mailinabox#296]
I have disabled ipv6 on my server and since then nsd fails to start.

Log output:

    [1421741915] nsd[15070]: error: can't bind tcp socket: Cannot assign requested address
    [1421741915] nsd[15070]: error: cannot open control interface ::1 8952
    [1421741915] nsd[15070]: error: could not open remote control port
    [1421741915] nsd[15070]: error: could not perform remote control setup

Adding `ip4-only: yes` to `/etc/nsd/nsd.conf` fixes the problem, however it seems like a periodic task replaces the config file and deletes the directive.

This breaks nsd for me, and adding the directive every day is kinda annoying.

**Comment by JoshData** [comment]
Why did you disable ipv6?

**Comment by 0xFelix** [comment]
Because I don't need / want it

**Comment by JoshData** [comment]
Then I'm going to say that the box doesn't support being modified like that.

**Comment by lorenzyannick** [comment]
@0xFelix : Same problem... I want to disable IPV6 for some DNS/provider reason
Did you find a fix ?

**Comment by 0xFelix** [comment]
As I said you can add `ip4-only: yes` to `/etc/nsd/nsd.conf` but that gets overwritten by some kind of periodic task. Because I use external DNS I simply deactivated nsd.
