### ISSUE TITLE
Support for naked domains running on google app engine

### ISSUE THREAD

**Issue by smewp** [mail-in-a-box/mailinabox#299]
Naked domain on google app engine is supposed to have four specific A records in DNS per the page instructions found at https://support.google.com/a/answer/2579995.

However, in box admin control panel can only list one (out of four) A records for the naked domain. If try to list an additional A record it is overwritten.  At least my domain will not work if I only use one of the four A records.  It was working fine using Godaddy dns with the four A records.

**Comment by toadkicker** [comment]
I don't use mailinabox's dns and turn them off. The idea of my email server handling my domain's dns records is not my idea of a good setup. I'm sure @JoshData means well by providing this in the box, but DNS services should belong with your domain provider or hosting a DNS server separately if you have the infrastructure/privacy and time concerns to justify it.

**Comment by JoshData** [comment]
This is about to be fixed with the fix coming for #333. Thanks!
