### ISSUE TITLE
Feature Request: Support for Fetchmail

### ISSUE THREAD

**Issue by dimitrovs** [mail-in-a-box/mailinabox#301]
As users migrate from centralized mail services (GMail, Hotmail, etc. ) to mail-in-a-box they may find it useful to have their old emails retrieved into their new inbox. Fetchmail should be able to do this.

**Comment by mbardelmeijer** [comment]
+1 For migrating e-mail boxes from old providers, this would be quite handy!

**Comment by milani** [comment]
This reference can help.
http://wiki2.dovecot.org/Migration

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope.
