### ISSUE TITLE
Running on very small VPS

### ISSUE THREAD

**Issue by jprice** [mail-in-a-box/mailinabox#302]
Last night I installed Mail-in-a-Box on an [Atlantic.net](https://www.atlantic.net/vps/vps-hosting/) GO VPS which is 1vCPU and 256MB ram. I enabled 4GB of swap space just to be on the safe side.

```
root@xxxx:~# free -mh
             total       used       free     shared    buffers     cached
Mem:          238M       229M       8.5M        22M       5.7M        68M
-/+ buffers/cache:       155M        82M
Swap:         4.0G       164M       3.8G
```

The main reason I wanted to try this is because Atlantic offers the VPS for only .99 a month. You can't beat $12 a year for self hosted email, if it works. 
I haven't really noticed any problems so far, it seems to be running pretty smooth. Which I really didn't expect otherwise for 1 user.
If you guys would like I'll update if I have any problems out of it.

**Comment by JoshData** [comment]
Yes please do post an update!

**Comment by zkanda** [comment]
Wow, nice, since it's SSD I guess the disk can still cope with the RAM. :+1: 

Please don't forget about the update.

**Comment by jprice** [comment]
So far I haven't had any problems. I believe the SSD and my large swap file seem to be helping. There hasn't been that many emails delivered to the account I am using. Does anyone know of a good way to stress test it?

I have been wanting to move my main email from google apps for some time, and I just may end up using this setup. It's cheap, and 100% in my control.

**Comment by skosch** [comment]
I'd like to second this. I'm currently running MIAB on a VPS with 512 MB RAM and 256 MB "virtual swap", i.e. "bonus RAM". I'm averaging around 50 and 25 percent used RAM/VSwap, respectively, and am having no trouble at all so far. To be fair, it's a single-user instance (although I am getting a ton of spam). 

Maybe the not-enough-memory error can be turned into a proceed-at-your-own-risk warning?

**Comment by jprice** [comment]
I agree. With just one user, and low email volume I do not see a problem with low memory.

**Comment by mlissner** [comment]
@jprice It's been a couple months, mind providing another update, including RAM utilization stats? How much disk space do you get for that 99 cents? The price point for the bigger server is (unfortunately) something that's making me hesitate.

**Comment by jprice** [comment]
```
outlaw@box:pts/0-> /home > outlaw (0)
> free -mh
             total       used       free     shared    buffers     cached
Mem:          238M       226M       11.5M        22M       5.7M        68M
-/+ buffers/cache:       155M        82M
Swap:         4.0G       341M       3.7G

outlaw@box:pts/0-> /home > outlaw (0) 
> df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       9.8G  7.9G  1.4G  64% /
udev             10M     0   10M   0% /dev
tmpfs            49M   13M   37M  26% /run
tmpfs           122M     0  122M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           122M     0  122M   0% /sys/fs/cgroup
tmpfs            25M     0   25M   0% /run/user/1001
outlaw@box:pts/0-> /home > outlaw (0) 
> uptime
 18:37:29 up 23 days, 52 min,  1 user,  load average: 0.00, 0.01, 0.05
outlaw@box:pts/0-> /home > outlaw (0) 
```
This is the first time I've logged into the server in a couple weeks. I've pretty much forgotten about it. I have had no issues with it. 

You get 10GB for the 99cents. I have one domain, and 3 email accounts on it, one which gets around 100 emails a day.

**Comment by finid** [comment]
I think I'm going to  give this a shot. If it can run a mail server on 256 MB of RAM, it should run a low volume-trafficed WordPress site.

**Comment by skosch** [comment]
@JoshData, I understand this is a low-priority issue, but it doesn't seem like anyone is having trouble with their setup. Maybe it's possible to issue a warning message instead, e.g. like this:

````bash
echo "Your Mail-in-a-Box needs more memory (RAM) to function optimally."
echo "Please provision a machine with at least 768 MB, 1 GB recommended."
echo "This machine has $TOTAL_PHYSICAL_MEM MB memory."
echo "Some users with low email volume have successfully run Mail-in-a-Box on machines with as little as 256 MB or RAM, but this is not recommended."
read -p "Continue at your own risk? (y/n): " -n 1 -r
echo # skip a line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
     exit
fi
````

**Comment by phareous** [comment]
I found that the backups take up way too much disk space (almost requiring double). I ended up turning off the backups on my box. Most of the cloud providers I looked at tend to have very small disk space (SSDs)

**Comment by skosch** [comment]
Interesting! I have a few hundred MB worth of email in my inbox and not yet run into any problems with backups. That may be another thing worth asking the user about on install?

At the end of the day, this is about making MIAB financially accessible to more people. Josh recommends DO's $10/month setups; that's $120 over the course of a year. To many, that's a steep price to pay, compared with a much better all-around UX offered by Google and other data-kraken providers—especially because the MIAB server can't really be used for other things (at least not easily).

If we could tell people that a single-user MIAB setup shouldn't cost them more than $30 or $40 per year, instead of $120, that might convince more of them that privacy doesn't have to be a luxury for the wealthy.

**Comment by JoshData** [comment]
I'm all for cheap, but it's hard to have reliably good results on cheaper machines.

**Comment by phareous** [comment]
I have about 20 GB worth of mail across my whole family. That forces me into the third tier of DigitalOcean ($20 a month) to get a 40 GB drive since 30 GB wasn't enough. In fact once I went from 30 GB to 40 GB, the backups filled up the drive again and I had to just disable them. So its costing me $240 a year currently for the hosting

**Comment by anoma** [comment]
In my view it is simply a matter of setting expectations and perhaps even hard domain and user limits based on the available resources. Any VPS will be small to some people and large to others; that is the nature of different use cases.

I fundamentally agree with @skosch and will add that with the flexibilty of VPSs and the already quite simple migration forces us to consider that the cheapest initial adoption cost will encourage user take up. Its not like the bad old days of long contract/hard to move tie ins of bare metal servers.

I would suggest that given all this we look to monitor the three key metrics; CPU, memory and disk space and suggest in an elegant way when VPS upgrades and even downgrades (to save money) are necessary/possible. With a bit more work we could use these self same metrics along with some basic mail stats to start taking the guesswork out of this.

**Comment by JoshData** [comment]
We could ask users to submit anonymous data --- a future version could make it easy for the user to instruct the box to collect the system data and submit it to a central point. Like most OSes do with crash reports.

**Comment by anoma** [comment]
I think we should look to working towards this. I will create a separate ticket since whilst it related to this it is still OT.

I believe we should however remove the hard lower limit in favour of a patch similar to @skosch. If nothing else combined with stats colection it will allow brave users to experiment.

**Comment by skosch** [comment]
:+1: 

On a side note, prices *are* coming down. Scaleway is now offering their $10/month servers for $3/month: https://blog.scaleway.com/2015/09/02/we-are-slashing-the-c1-price-by-70-percent/ :)
