### ISSUE TITLE
Missing Static Web Hosting domain

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#303]
Whilst migrating to mailinabox I discovered that one of my domains has no entry in the "Static Web Hosting" section. Adding a folder to /home/user-data/www/ for this domain, resetting web via GUI does not work and simply shows the content of default. All other domains work correctly.

I have tried variations of the problem domain name and TLD and all work fine so I can only assume this is a glitch in the matrix.

Can you supply info on how to manually fix this preferably without removing and readding as I have many email clients already configured.

**Comment by JoshData** [comment]
Any domain that you have a user or alias on should appear in that list. Do you have a user or alias on that domain? (Exactly that domain. A subdomain wouldn't count.)

**Comment by anoma** [comment]
Yes I currently have two users setup for that domain both confirmed working.

These users are listed in "Existing mail users" section and we can also see all the DNS in External DNS section. In fact  it seems to be correct and working in every way except the domain is not listed at all in "Web>Uploading web files" or "Web>Different sites for different domains"

**Comment by JoshData** [comment]
Have you set a custom A or AAAA record in the Custom DNS page?

**Comment by anoma** [comment]
As a consequence of it not working in mailinabox I did in fact set A records for www and non www.

I went ahead and removed these and the entry for the domain is now visible in the web section. I can only assume something got confused here although one of those "somethings" could in fact have been me (although I dont think the timeline fits for that).

Once DNS expires and propagates naturally I will test again and close this ticket.

Perhaps off topic is there any supported method to allow plain old HTTP hosting (non SSL). I have not planned this well and did not realise I would need real SSL for the domains. I had hoped i could run HTTP until https://letsencrypt.org/ offered a less convoluted and expensive option (I can open a new ticket if preferred/acceptable).

**Comment by JoshData** [comment]
Glad you got it working.

I don't plan to add plain HTTP hosting because I don't want anyone to mistakenly end up with an insecure setup, but you can go back and put the A record back and creatively side-step Mail-in-a-Box's configuration to do it.
