### ISSUE TITLE
Backup Rotation

### ISSUE THREAD

**Issue by stevetoza** [mail-in-a-box/mailinabox#305]
Hello, 

For some odd reason my backups are not rotating see below from the backup status page. Is there a manual way, to run the rotation or any suggestions why its not rotating. 

01/29/15 06:45:53 GMT	1 hours, 17 minutes ago	increment	991 MB	n/a
01/28/15 06:35:46 GMT	1 day, 1 hours ago	increment	205 MB	n/a
01/27/15 06:27:15 GMT	2 days, 1 hours ago	increment	500 MB	n/a
01/26/15 06:52:00 GMT	3 days, 1 hours ago	increment	10 MB	n/a
01/25/15 06:52:40 GMT	4 days, 1 hours ago	increment	10.5 MB	n/a
01/24/15 06:30:47 GMT	5 days, 1 hours ago	increment	41 MB	n/a
01/23/15 06:34:48 GMT	6 days, 1 hours ago	increment	18.6 MB	n/a
01/22/15 06:35:56 GMT	7 days ago	increment	57.2 MB	n/a
01/21/15 06:25:32 GMT	8 days ago	increment	591 MB	n/a
01/20/15 06:54:10 GMT	9 days ago	increment	75.5 MB	n/a
01/19/15 06:38:57 GMT	10 days ago	increment	20 MB	n/a
01/18/15 06:54:35 GMT	11 days ago	increment	5.2 MB	n/a
01/17/15 06:40:24 GMT	12 days ago	increment	113 MB	n/a
01/16/15 06:38:22 GMT	13 days ago	increment	119 MB	n/a
01/15/15 06:36:36 GMT	14 days ago	increment	484 MB	n/a
01/14/15 06:52:11 GMT	15 days ago	increment	2 GB	n/a
01/13/15 06:30:45 GMT	16 days ago	increment	170 MB	n/a
01/12/15 06:34:36 GMT	17 days ago	increment	40.2 MB	n/a
01/11/15 06:34:26 GMT	18 days ago	increment	3.6 MB	n/a
01/10/15 06:55:01 GMT	19 days ago	increment	368 MB	n/a
01/09/15 06:53:27 GMT	20 days ago	increment	29.1 MB	n/a
01/08/15 06:49:00 GMT	21 days ago	increment	183 MB	n/a
01/07/15 06:34:16 GMT	22 days ago	increment	5.8 GB	n/a
01/06/15 06:37:50 GMT	23 days ago	increment	1.1 GB	n/a
01/05/15 06:53:23 GMT	24 days ago	increment	3 MB	n/a
01/04/15 06:47:29 GMT	25 days ago	increment	3.7 MB	n/a
01/03/15 06:54:13 GMT	26 days ago	increment	5.8 MB	n/a
01/02/15 06:41:05 GMT	27 days ago	increment	23.4 MB	n/a
01/01/15 06:44:13 GMT	28 days ago	increment	3.1 MB	n/a
12/31/14 06:41:52 GMT	29 days ago	increment	20.8 MB	n/a
12/30/14 06:39:42 GMT	30 days ago	increment	61 MB	n/a
12/29/14 06:27:14 GMT	1 month, 0 days ago	increment	3.3 MB	n/a
12/28/14 06:42:42 GMT	1 month, 1 days ago	increment	3.3 MB	n/a
12/27/14 06:38:58 GMT	1 month, 2 days ago	increment	4.7 MB	n/a
12/26/14 06:54:47 GMT	1 month, 3 days ago	increment	4.9 MB	n/a
12/25/14 06:47:58 GMT	1 month, 4 days ago	increment	9.5 MB	n/a
12/24/14 06:48:51 GMT	1 month, 5 days ago	full	25.9 GB	n/a

Thanks

**Comment by dhpiggott** [comment]
According to a comment in `management/backup.py`, a full backup is only forced "when the total size of the increments since the last full backup is greater than half the size of that full backup".

I've not exactly added up the size of the increments listed in your above backup status but it looks safe to estimate to me that they are below (25.9/2) GB; once they reach that, a full backup will be forced.

I see similar with my box; it still only has one full backup from when I first set it up:
09/26/14 06:47:15 UTC	4 months, 3 days ago	full	1.7 GB	n/a

**Comment by stevetoza** [comment]
Thanks for info
