### ISSUE TITLE
Outlook  compatibilty update for documentation

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#308]
Perhaps worth updating documentation somewhere. Also may be relevant to (https://discourse.mailinabox.email/t/unable-to-configure-mail-in-outlook/123)

I believe commit https://github.com/mail-in-a-box/mailinabox/commit/06e074bd323ea5637c6b30598e6c3fb562e806a0

made the minimum Outlook compatible version 2003 but only with SP1 and the post-Service Pack 1 hotfix package installed. Outlook 2007 is compatible by default however neither 2003 or 2007 will work with windows XP as it shares no compatible TLS options to stock mailinabox.

These are obviously quite old clients but still quite prevalent and the combination of OS and patch levels and terrible Outlook error message make it non obvious for users to debug.

**Comment by JoshData** [comment]
How do you know those are the affected versions? Can we simplify this to say Outlook 2007 or later on Windows 7 and later (or whatever it might be)?

**Comment by anoma** [comment]
Simple trial and error on a couple of machines that could not connect (whilst other similar machines could).

It is entirely possible there are other factors in play (OS patch levels etc) and I cannot comment on Windows Vista since I do not own a copy to try.

Given that I suggest you are right to go with  "Outlook 2007 or later on Windows 7 and later" as you suggest as the safest/simplest option.

**Comment by anoma** [comment]
As off v0.44 the minimum version is no longer `Outlook 2007 or later on Windows 7 and later` as 2007 no longer works. I assume 2010 does work but I have not tested this.
