### ISSUE TITLE
Changing STORAGE_ROOT has no effect.

### ISSUE THREAD

**Issue by h8h** [mail-in-a-box/mailinabox#309]
What is the purpose of this condition?
```bash
if [ -f /etc/mailinabox.conf ]; then
    # Run any system migrations before proceeding. Since this is a second run,
    # we assume we have Python already installed.
    setup/migrate.py --migrate
    # Load the old .conf file to get existing configuration options loaded
    # into variables with a DEFAULT_ prefix.
    cat /etc/mailinabox.conf | sed s/^/DEFAULT_/ > /tmp/mailinabox.prev.conf
    source /tmp/mailinabox.prev.conf
    rm -f /tmp/mailinabox.prev.conf
fi
```
[curious if block](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/start.sh).

Let's say I have a partitoned box, with plenty of gb's on /var and very less on /. So all I wanna do is to change the STORAGE_ROOT to /var.

I've install mailinabox to /home/user-data. Then I stop the daemon `service mailinabox stop`. Move all files to /var. Change the `/etc/mailinabox.conf` file, especially the `STORAGE_ROOT` var. And re-run the installation script `mailinabox`. Nothings happend, everthing is installed to `/home/`.

Why? I think all my settings in the  `/etc/mailinabox.conf` file got lost. Cause my `STORAGE_ROOT` var was renamed to `DEFAULT_STORAGE_ROOT` and then sourced. But miab never ask for `DEFAULT_STORAGE_ROOT`. Instead it creates a  `STORAGE_ROOT` depending on `functions.sh`.

So if you don't want to let users change their storage dir, then you needn't update / move the old config to /tmp and source it.

I would very appreciated it if advanced user could move / change the storage dir.

*Update*
Sry I haven't seen this one #106

**Comment by ikarus23** [comment]
:+1:

**Comment by JoshData** [comment]
> What is the purpose of this condition?

It loads in the other settings besides STORAGE_ROOT too, and the defaults are used in a few places.

The problem is lower down when STORAGE_ROOT is hard-coded, rather than checking if `DEFAULT_STORAGE_ROOT` is set first and using that instead if it is.

**Comment by h8h** [comment]
So I guess, you would like a PR from me?

**Comment by JoshData** [comment]
If such a PR were to be submitted, I would surely merge it. :)

**Comment by h8h** [comment]
Nice. What about the other variables in the config file? Isn't it better (for my PR :) ) to move the file back and redo the `GLOBAL` and source the file again? I mean what happend if the user change i.e. `STORAGE_USER`? I think this has also no effect. 
```bash
STORAGE_USER=$STORAGE_USER
STORAGE_ROOT=$STORAGE_ROOT
PRIMARY_HOSTNAME=$PRIMARY_HOSTNAME
PUBLIC_IP=$PUBLIC_IP
PUBLIC_IPV6=$PUBLIC_IPV6
PRIVATE_IP=$PRIVATE_IP
PRIVATE_IPV6=$PRIVATE_IPV6
CSR_COUNTRY=$CSR_COUNTRY
```

**Comment by JoshData** [comment]
`STORAGE_USER` also probably has the same issue. I believe I specifically handled the rest. The idea was that *actually setting* any of these variables in the environment prior to running the script will force those values, i.e.:

    PRIMARY_HOSTNAME=mydomain.com setup/start.sh

This should *override* any pre-existing settings. So sourcing the whole (original) file would break that because it would wipe out anything specified in the environment.

Maybe that was a bad approach, since it makes things more complicated. I'd be open to simplifying all that. I don't believe anything relies on that behavior.

**Comment by JoshData** [comment]
@h8h The part you're quoting is inside a `cat ... EOF` block. That's what writes the /etc file in the first place --- it's not setting variables.

**Comment by h8h** [comment]
I know. I want to source it again, after writing it in /etc. And i dont want heredoc, I want to get the old file :), to have all the things the user configured there. 

If you do 
`PRIMARY_HOSTNAME=mydomain.com setup/start.sh`
aren't you overwrite PRIMARY_HOSTNAME, after the source on line [20](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/ssl.sh#L20)?

So my plan is no to move the /etc/ file to /tmp, but why do you need the defaults (maybe wrong) variables?
> It loads in the other settings besides STORAGE_ROOT too, and the defaults are used in a few places.

Maybe I've to get more in touche with the bash files to get you right. Is been a long time since I stepped through it.

**Comment by JoshData** [comment]
Let's fix one problem at a time. Can we get a fix in that minimally gets DEFAULT_STORAGE_ROOT/USER working, and then look into simplifying after?

**Comment by h8h** [comment]
Yep. I can do a simply check for both DEFAULT vars and it overwrites the `$STORAGE_ROOT` and / or `$STORAGE_USER` if the DEFAULT var is set.
