### ISSUE TITLE
Dovecot - "Invalid settings: postmaster_address setting not given"

### ISSUE THREAD

**Issue by xxdesmus** [mail-in-a-box/mailinabox#31]
After a clean install it seems I can send email just fine, but receiving is a problem.

Checking /var/log/syslog I see this:

```
Invalid settings: postmaster_address setting not given
```

Here's the full block of the incoming email:

```
Apr 24 00:27:56 mail postfix/smtpd[24841]: connect from mail-vc0-f171.google.com[209.85.220.171]
Apr 24 00:27:56 mail postgrey[7956]: action=pass, reason=client whitelist, client_name=mail-vc0-f171.google.com, client_address=209.85.220.171, sender=NAME@gmail.com, recipient=NAME@DOMAIN
Apr 24 00:27:56 mail postfix/smtpd[24841]: 689491610F0: client=mail-vc0-f171.google.com[209.85.220.171]
Apr 24 00:27:56 mail postfix/cleanup[24844]: 689491610F0: message-id=<CAH=oei_D8NrJ5T_zwSasKzfJwLh0a7uf=W-1Vx-T2PqhozryzQ@mail.gmail.com>
Apr 24 00:27:56 mail opendkim[15755]: 689491610F0: s=20120113 d=gmail.com SSL
Apr 24 00:27:56 mail postfix/qmgr[9306]: 689491610F0: from=<NAME@gmail.com>, size=1851, nrcpt=1 (queue active)
Apr 24 00:27:56 mail dovecot: lmtp(24846): Fatal: Error reading configuration: Invalid settings: postmaster_address setting not given
```

I had to add:

```
postmaster_address=postmaster at DOMAIN
```

Change DOMAIN with your actual domain obviously.

to  

```
/etc/dovecot/dovecot.conf
```

and then  

```
service dovecot restart
```

All good now.

**Comment by Jannik2017** [comment]
how ic can fix this

eu,)Error: Error reading configuration: Invalid settings: postmaster_address set                                                                                           ting not given lda: Fatal: Internal error occurred. Refer to server log for more                                                                                            information. 4.2.1 Message can not be delivered at this time )
