### ISSUE TITLE
Ana/cron daemon emails should deliver to admin email address

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#314]
Currently ana/cron daemon emails are addressed to root@primarydomain. e.g. "/etc/cron.daily/mailinabox-backup" report

This leaves the possibility open that the mail will not reach the system administrator.

Since by definition we always know the system administrator email address this is what we should use.

Two obvious solutions are to change MAILTO= cron parameter or setup and root alias for system administrators email.

**Comment by JoshData** [comment]
I want to simplify those emails (currently the backup) before turning that on.

**Comment by dhpiggott** [comment]
For what it's worth, I have a patch that implements this - it's one of four patches I apply to mailinabox for my deployment. Currently its hash is dhpiggott/mailinabox@434ddeaf5f0c248825b3da3ac44db2a87c705853, though that's liable to change when I next rebase the patches onto master.

I've been happy receiving the current cron output but I appreciate that it could be simplified.

**Comment by JoshData** [comment]
Oh one of the other things I want to do first is have some internal monitoring in these emails. I want to run the status checks each night and compare the output from run to run. I'm mentioning in case anyone wants to work on that.

**Comment by JoshData** [comment]
v0.16 ensures anything important that we run as a cron job is mailed to the administrator.
