### ISSUE TITLE
Could not resolv local mirror on a Numergy's VM

### ISSUE THREAD

**Issue by Gwerlas** [mail-in-a-box/mailinabox#315]
After the resolv.conf file is automatically changed, we have resolution failures for the provider package repo :
Err http://ubu-update.cloud.local/ubuntu/ trusty-updates/main libevent-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1
  Could not resolve 'ubu-update.cloud.local'
[...]

**Comment by JoshData** [comment]
Your provider is messing around with the system in a way that Mail-in-a-Box doesn't support (currently).

**Comment by Gwerlas** [comment]
I failed to user the provider's DNS servers in Bind. I'm not skilled enough in DNS & Bind.
I solved my troubles by adding a DNS firewall rule through the provider's selfcare.

When I'll find how to setup Bind to use provider's DNS servers, I'll make a PR
