### ISSUE TITLE
Update to ownCloud 8.0.0

### ISSUE THREAD

**Issue by nstanke** [mail-in-a-box/mailinabox#316]
Owncloud 8 is available now. https://owncloud.org/eight/

**Comment by JoshData** [comment]
The current way we do updates did not work for me. We'll need a patch that:

* deletes the existing ownCloud directory
* preserves the config file and copies it back into place
* fixes file permissions and adds some `su`/`sudos` that ownCloud is now more picky about
* explicitly activates the calendar and contacts apps

As far as I could tell, there are no improvements in calendar and contacts, which are the only parts truly supported by Mail-in-a-Box anyway, so I'm not really in a rush to update.

**Comment by JoshData** [comment]
See https://github.com/mail-in-a-box/mailinabox/commit/d6ddb094e74f8fb122e36fab181288a3621ac064.

ownCloud 8 doesn't ship with the contacts or calendar apps, so we need a whole new installation/update method for that. This is a real pain in the neck.

**Comment by nstanke** [comment]
Got ownCloud 8 with contacts & calendar running on a fresh box. See db84f159ff4fc04a0dca8fb523007bd4b33838d3 

Maybe we should wait for ownCloud 8.0.1 though? https://forum.owncloud.org/viewtopic.php?f=31&t=26310

**Comment by JoshData** [comment]
That commit is really helpful thanks. We're still missing a bit about tracking versioning for the apps though. E.g. If an app has a security update but ownCloud doesn't, we'll have a hard time updating.

**Comment by nstanke** [comment]
We could checkout app (contacts, calendar) releases by their git-tag? See 1db9c81b4e74973eca50a708e7fb33fb1e49101c

**Comment by JoshData** [comment]
I like that. We just need separate `if` blocks to compare against the installed version. Thanks for working through this!

(Side question: What was the reason you suggested waiting until 8.0.1?)

**Comment by JoshData** [comment]
(I think there was a comment deleted in the middle there. <g>)

**Comment by nstanke** [comment]
I'm sorry for deleting my comment. Fixed a typo. 1df8c0c4918c4b0b70d577deae86c32b32825d2c

**Comment by JoshData** [comment]
Fixed in dd6a8d99981e04a21d4855da3568ad93c3cf9682.
