### ISSUE TITLE
Enable / Configure fail2ban jails

### ISSUE THREAD

**Issue by h8h** [mail-in-a-box/mailinabox#319]
Today my box was under attack, mostly stupid login attempts on dovecot, 50 times same IP. But the remote IP never gets blocked by iptables and I figure out that fail2ban isn't configured very well.
I.E.:
```
[dovecot]
enabled = false
port    = smtp,ssmtp,submission,imap2,imap3,imaps,pop3,pop3s
filter  = dovecot
logpath = /var/log/mail.log
```
or
```
[roundcube-auth]
enabled  = false
filter   = roundcube-auth
port     = http,https
logpath  = /var/log/roundcube/userlogins
```
Both are disabled and roundcube-auth has a wrong `logpath`.

So what I'm going to do is to create a `jail.conf` especially for miab, put it in `conf/` folder and roll it out on every installation / update (`setup/system.sh`).

Some thoughts?

I'm not that fail2ban expert, so if someone have better experience with this tool I'm happy if the person can do that for me :).

**Comment by anoma** [comment]
My first thought is that before we increase the chances of locking legitimate users out it may be prudent to encourage users to setup fail2ban exceptions e.g.

> "ignoreip" can be an IP address, a CIDR mask or a DNS host. Fail2ban will not  ban a host which matches an address in this list. Several addresses can be defined using space separator.   

Not everyone will have access to a static IP either via their ISP or bouncing off another box but those that do may be saved some headache with this.

Even if we only add an exceptions at install time it is likely a good safety measure i.e. the time most people make multiple auth errors is at setup and config.

My second though is we should cron up a fail2ban log summary. The internet is full of fairly ugly examples that would suffice until email reporting is formalised.

**Comment by h8h** [comment]
Thank you!

If the user is legitimate and an admin and he has i.e. 5 login attempts, he is not worthy anymore to login for 10 mins (i guess this is the fail2ban default time). I think this is fair, isn't it?

>My second though is we should cron up a fail2ban log summary. The internet is full of fairly ugly examples that would suffice until email reporting is formalised.

Thats a fantasic thought! Maybe something similar to this one: [mail-log](https://github.com/mail-in-a-box/mailinabox/blob/master/management/mail_log.py)

**Comment by anoma** [comment]
I would certainly agree that 5 login attempts triggering a 10 minute ban on the face of it seems like a small penalty to pay when triggered by a legitimate user. I see no reason to change this however my experience is that once you start refining fail2ban you can easily end up in a sitation where the increases in matches triggers this ban more often than expected.

A scenario to highlight the point. A new user makes a mistake with their client setup and the entire office is banned for 10 minutes including the admin. The same user sets update mail interval to one minute by mistake and now the only solution to getting access to the server again by the admin is to find this user (currently without knowing anything at all about what caused the problem as you dont have access and no email alerts).

This is why I suggest that "ignoreip" should be strongly encouraged before we start increasing security.

I am open to what alerting is used although it might be worth giving some thought to also having some non mail related options since in this scenario the admin would be IP banned from receiving the alerts.

**Comment by h8h** [comment]
You're right. Blocking a whole office, because of some shitty, but legitimate user who has 5 login attempts is worst. 

> This is why I suggest that "ignoreip" should be strongly encouraged before we start increasing security.

Option 1:
What about restarting the box to get access earlier? Due to iptables non-persistents on reboots, the admin can simply restart the server to gain access. This a little drawback, but you get rid of storing the admins ip addresses and putting them into `ignoreips`.

Option 2:
Figure out the CIDR (e.g. `whois` / `inetnum`) and put it to `ignoreips`. Additionally store the ip to `ignoreips` of every successful login into the admin web or ssh.

**Comment by anoma** [comment]
I dont think we need to over complicate this. I suggest this is simply a matter of giving the admin a GUI option of adding trusted IP(s) and explaining to them why it is a good idea.

Currently the only way you know fail2ban is even part of MIAB is to have done some research here so there is a small chance admins will not even know it could be an issue and that is not good when we are tlaking about making it more prevalent.

I dont want to take your thread OT as fundamentally more fail2ban actions can only be a good thing I just present a word of caution if you hope it to be the default.

Once a strong base is in place for this there are lots of tricks we could add e.g. detect php-my-admin in nginx to ban attack bots also if you change the SSH port kill the IP on even one connection to port 22 etc

**Comment by h8h** [comment]
So here my Roadmap:
* Configure jails for dovecot, postfix, maybe webadmin, roundcube, owncloud, ssh in  fail2ban.
* Create an extra fail2ban page in webadmin with logs, ip ignore rules and so on
* Disable fail2ban till the admin enables it on the admin page, because if the whole system is blocked and an inexperienced admin don't know what happend with the box.

Atm fail2ban is more disabled than enabled, so in fact is an improvement. So @JoshData is fail2ban enabling / disabling too optional for miab?

**Comment by JoshData** [comment]
I would like to enable fail2ban by default, but with settings that aren't going to lock out a whole office indefinitely. Can you come up with some sane defaults that can be turned on for everyone?

**Comment by anoma** [comment]
Perhaps this could be covered with manipulation solely of (maxretry) and (findtime).

This way by default MIAB could ship with all the jails configured and live but with less sensitive (and therefore less risky) triggers.

Conceptually then three options for settings could be given to the admin "off", "safe" and "sensitive" covering most use cases without presenting too much complication or a learning curve.

**Comment by anoma** [comment]
@h8h as per the OP not only is the [roundcube-auth] path wrong I dont believe the REGEX works either.

Testing with 

`fail2ban-regex /var/log/roundcubemail/errors /etc/fail2ban/filter.d/roundcube-auth.conf`

I see no line matches and to my eye the REGEX is for a slightly different log format.
