### ISSUE TITLE
Owncloud shared contacts

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#320]
As I understand it currently the only way to configure owncloud shared contacts is to first run

https://github.com/mail-in-a-box/mailinabox/blob/master/tools/owncloud-unlockadmin.sh

which in turn removes support and makes MIAB "for testing & experimentation purposes only".

This is too extreme for me, are there any current or planned options to allow shared/group contacts. The scenario I am trying to cater for is family wide contact lists finally banishing every person maintaining a separate list or relying on Google contacts.

**Comment by JoshData** [comment]
Link me to the ownCloud documentation for this?

**Comment by anoma** [comment]
Owncloud documentation leaves a lot to be desired (as in its not documented at all that I can see).

However it is pretty simple.

admin>user>create a user group (or skip and use an existing group)
as a user of this new user group...
       contacts > cogwheel "Add Address Book"
       contacts > cogwheel > select this new address book > share > share with user group we defined above

That set up all the sharing for this group. Now when you add a contact you have a new drop down called "Address book" which by default uses "contacts (local)" but also has the option to choose the new address book we just setup. If you choose this all users in the user group can see and edit this contact. Very powerful feature.

Calendar has a similar process.

I can setup a dev server to grab some screen shots if it helps but its pretty self evident once you try it.

Perhaps the least effort way would be to by default create one or several contacts-group-shared and calendar-group-shared for users to select. this would be less flexible but removes the need to have admins.

Another option is to allow group admins. I am not sure what powers they have but I believe they are not superusers and cannot break the actual OC instance. If this is the case you could potentially leverage more OC features without running the risk of bricking the instance.

**Comment by JoshData** [comment]
Maybe we can just automatically create an "everyone" group and add everyone to it.

**Comment by JoshData** [comment]
Closing because of #514.
