### ISSUE TITLE
Integrate w/ CloudFlare and DigitalOcean API

### ISSUE THREAD

**Issue by webknjaz** [mail-in-a-box/mailinabox#325]
Both of services have easy to use `REST API`. 
It's a nice way to do optional autoconfiguration of mailing.
What do you think about this?

**Comment by JoshData** [comment]
For DNS you mean, I guess?

**Comment by webknjaz** [comment]
Yes. Just for DNS (CloudFlare).

Regarding DigitalOcean:
- I think at least PTR record may be set via API
- It's even possible to create and provision droplet from end-user's localhost

**Comment by JoshData** [comment]
Well I'm not opposed to these things, but I am not going to get around to doing them myself any time soon. I'll leave the issue open for a while if anyone else wants to comment/work on it, but if not I will close the issue.

**Comment by pycode-biz** [comment]
this feature will be nice.

**Comment by JoshData** [comment]
Closing due to inactvitiy.

**Comment by chamunks** [comment]
@JoshData literally the only reason I've been holding back on using MiaB as my solution is I would need CloudFlare support I can't be hosting my own DNS that would just be bad for uptime.  I think that it's somewhat self-defeating to worry about privacy and control and put the hardware inside of someone else's datacenter.   So I've been really hoping that at some point either poste.io would stabilize or this would get CloudFlare support.

IF you need someone else to do the legwork, maybe I could recommend something I commissioned way back.  https://github.com/TunkDesign/SimpleCloudflare should be a shell accessible API abstraction layer for you.  IDK if that helps at all.

**Comment by jooize** [comment]
@chamunks What do you want automated? Is there something that can't be done manually?

**Comment by chamunks** [comment]
Just CloudFlare is a pretty common DNS provider and they have a great API.  Could possibly assert the DNS records that you would using MiaB's DNS server.
