### ISSUE TITLE
timezone not set

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#328]
I had assumed that the install script set timezone but it seems not.

Obviously "dpkg-reconfigure tzdata" works after the fact but I was sure the MIAB install script asked me to define the timezone.

**Comment by anoma** [comment]
Small relevant point. If you change the timezone fail2ban gets very confused and essentially stops working until it is restarted.

**Comment by JoshData** [comment]
Closing in favor of #294.
