### ISSUE TITLE
Add better support for external DNS in status checks

### ISSUE THREAD

**Issue by mathuin** [mail-in-a-box/mailinabox#330]
There are many useful nameserver-related checks that apply in the simple case which is recommended by the setup guide.  Some of these checks will not pass if external DNS is used.  There are also some additional checks that would be as helpful for external DNS as the existing checks are for internal DNS.

It would be nice if the status checker could perform different checks based on whether internal or external DNS is desired.  This could be done with a checkbox somewhere, or automatically based on which situation is detected.

This may augment or replace the existing system page for external DNS.  That's up to someone else. ;-)

**Comment by JoshData** [comment]
Can you be more specific?

**Comment by mathuin** [comment]
Sorry about the massive delay:  just finished winter term. :-)

The setup guide recommends that folks using MIAB to add glue records to their real DNS pointing to MIAB's DNS, but it acknowledges that some folks can't (or won't) do that due to other considerations such as running a website on the domain name.  These latter folks are using "external DNS".

Included among the system status checks are a number of tests for internal DNS configuration.  The box itself checks for nameserver glue records, as are the individual domains.  If the internal DNS configuration is not detected, then the box and each domain has a X for nameservers.

It would be nice if there was some way to tell MIAB's status checkers that the user is intentionally using external DNS -- perhaps with a check-box on the external DNS status page?  If this check-box is set, then the status checker could replace the search for glue records with a more intensive check comparing the recommended values on the external DNS status page with the values retrieved from external DNS, much as the MX record checks are already done.  The fact that the external DNS page gives exactly the keys and values required for MIAB to function helps.

Does that help?

**Comment by JoshData** [comment]
I made some quick tweaks. Hopefully this is an improvement for now.

**Comment by mathuin** [comment]
Finally got a chance to look at your changes, and they look great.  Thanks!
