### ISSUE TITLE
Connection issue when using Thunderbird

### ISSUE THREAD

**Issue by aetherius0** [mail-in-a-box/mailinabox#331]
Thunderbird frequently displays the error message below. Restarting Thunderbird does not seem to fix the issue, but rebooting my server seems to fix the issue for a day or two after which point it starts acting up again. Any ideas for why this may be happening or if there's a fix?

![error](https://cloud.githubusercontent.com/assets/3969230/6281154/653ae26a-b888-11e4-82a7-0e0868a54087.png)

**Comment by JoshData** [comment]
No idea. I use Thunderbird myself and haven't seen any problem like that. Maybe there's something in the logs? (`tail -f /var/log/mail.log`)
