### ISSUE TITLE
Failure to add multiple TXT records for specific subdomain

### ISSUE THREAD

**Issue by djradivip** [mail-in-a-box/mailinabox#333]
When using the box's DNS servers, it forbids for adding multiple TXT records to one subdomain. Instead, it allows you to add only 1. When you try to add another one, it replaces the existing record. Same thing happens, if you do it for the main domain. 
However, registrar allows that so it is not a DNS limitation.

**Comment by JoshData** [comment]
I just committed an overhaul of the DNS API to allow for multiple records of the same type for a domain.
