### ISSUE TITLE
Nasty bug: authentication + ownCloud

### ISSUE THREAD

**Issue by ikarus23** [mail-in-a-box/mailinabox#339]
Today one of my box users encountered a nasty bug. He logged using
his new installed ownCloud iOS-Client.... and all the data were gone...
only the default file structure of ownCloud was there.

After some testing I think I know what is causing this issue:
As far as I know mailinabox creates ownCloud users on first login.
So this is what happened:
* Created user via admin
* User logs in with **`user@domain.tld`** on the ownCloud interface
* Access is grated by dovecot (user an password were correct)
* A new ownCloud user is created because there is no user like `user@domain.tld`

So far so good.

* User logs out.
* User logs in with **`User@domain.tld`**
* Access is grated by dovecot (user an password were correct)
* A new ownCloud user is created because there is no user like **`User@domain.tld` (capital U)** !!!

So the data of my box user is still there after all.
But by using a capital letter at the beginning of his mail address
he was not able to find his old data (because it was logged into a new ownCloud account)

In order to fix this bug email addresses should be modified before testing. e. g.
`ownCloudUserExists(toLowerCase(username))`

**Comment by JoshData** [comment]
I guess this is an ownCloud bug? I'm not sure. Probably good to ask wherever they do bug tracking.

**Comment by ikarus23** [comment]
I don't think it's an ownCloud bug. At least when I login into https://demo.owncloud.org/ with
**`Test`** instead of **`test`** I get the same result (I'm logged in as `test`).

Is there a script within MIAB that creates a new user when it does not exists? I think there
must be the issue...

**Comment by JoshData** [comment]
No.

**Comment by ikarus23** [comment]
Ok, maybe it is a ownCloud bug. To be more precisely: a bug in the `user_external` plugin. This would explain why MIAB is affected and https://demo.owncloud.org/ is not (because the site doesn't user `user_external`).

I will dig more into it and keep you posted.

**Comment by JoshData** [comment]
Closing because of #514.
