### ISSUE TITLE
IOS and IMAP path Prefix

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#340]
I only just noticed that by default IOS 7 (cant test 8) doesn't support IMAP sub folders correctly using the default MIAB settings.

Whilst you can use  a different view to see the contents of sub folders they are not sync'd by default resulting in no mail apart from the the root being seen or notified on.

The internet suggests that this is fixable one of two ways:

Alter the path prefix in IOS settings (this does not work for me as the setting is locked and would likely need a complete removal to fix) http://kb.mediatemple.net/questions/720/How+can+I+set+up+email+on+my+iPhone+or+iPod+Touch%3F#gs

The second fix is apparently to set the "set the 'mail_location' correctly" as mentioned on the last post here https://discussions.apple.com/thread/1631415?tstart=0

I know not of these things so thought it best to report for comment.

**Comment by JoshData** [comment]
Is this still a problem?

**Comment by anoma** [comment]
The symptoms persist but I havent experimented with the dovecot options as this is not an area i know much about or feel confident understanding the implications of changing random settings.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
