### ISSUE TITLE
Postfix SMTP headers not correctly anonymised

### ISSUE THREAD

**Issue by jonaslejon** [mail-in-a-box/mailinabox#341]
The following will show up in the receiving E-mail headers:
```
Received: from authenticated-user (unknown [127.0.0.1]) (unknown [127.0.0.1])nd2.com [83.233.122.91])
```
As you can se at the end of the line. The Postfix REPLACE is not working and I did some testing, the following works:
```
/^Received:.*\(Postfix/ REPLACE Received: from authenticated-user (unknown [127.0.0.1])
```
In the file /etc/postfix/outgoing_mail_header_filters

**Comment by JoshData** [comment]
Could you disable the replace and post here what the original received header looks like?
