### ISSUE TITLE
Anonymise more outgoing SMTP headers

### ISSUE THREAD

**Issue by jonaslejon** [mail-in-a-box/mailinabox#342]
Please add the following two lines to the file outgoing_mail_header_filters:

```
/^\s*Mime-Version:/  IGNORE
/^\s*X-Pgp-Agent:/  IGNORE
```
Since the headers disclose information like this:
```
X-Pgp-Agent: GPGMail 2.3
Mime-Version: 1.0 (Mac OS X Mail 8.1 \(2010.6\))
```
Maybe the Mime-version needs to be there and can be replaced instead.

**Comment by JoshData** [comment]
reference: http://www.freesoft.org/CIE/RFC/1521/3.htm

**Comment by JoshData** [comment]
I just committed a fix for this. If you could try it out that would be super helpful.
