### ISSUE TITLE
OAuth Provider

### ISSUE THREAD

**Issue by martindale** [mail-in-a-box/mailinabox#346]
As MailInABox provides a relatively secure authentication store, it would be useful as a OAuth provider.

**Comment by JoshData** [comment]
Totally agree.

**Comment by bronson** [comment]
Is this page spam?  https://www.bountysource.com/issues/9166334-oauth-provider

I don't quite understand why someone would open a bounty but not contribute to it...?

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope.
