### ISSUE TITLE
stty: standard input: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by domgolonka** [mail-in-a-box/mailinabox#354]
Your Mail-in-a-Box is running.

Please log in to the control panel for further instructions at:

stty: standard input: Inappropriate ioctl for device
https://xxxxxxxx/admin3

You will be alerted that the website has an invalid certificate. Check that
the certificate fingerprint matches:

**Comment by hnk** [comment]
On a new 0.7 install I get the same error.

It must be happening somewhere [between Lines 166 and 169 in setup/start.sh](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/start.sh#L166-L169).

If I run the command "management/status_checks.py --check-primary-hostname" manually I do not get that error... I will try and see what I can find.

**Comment by hnk** [comment]
This may be related to a completely different thing. I found mentions of this popping up when one was issuing commands on a server connected to via ssh. Will look into it further and update.

**Comment by hnk** [comment]
Ok I just did another rollout and did not see this pupping up... I am not sure what causes this.

**Comment by JoshData** [comment]
I think this was fixed by 5033042b.
