### ISSUE TITLE
CSR Missing Organization, State, and Locality (City)

### ISSUE THREAD

**Issue by shido6** [mail-in-a-box/mailinabox#355]
I am attempting to replace the self-signed certificate for the host hosting mailinabox. (blah.mydomain.com)

Select SSL certificates from the control panel..
Select the domain you are getting an SSL for..
Click on Install Certificate

The CSR generated is missing Organization , State, and Locality.

I get this from ssls.com (PositiveSSL):

Error
Parsing CSR error. 
The following mistakes were found in your CSR-code:
Organization cannot be blank. Use "NA" if it is not defined
State cannot be blank. Use "NA" if it is not defined
Locality (City) cannot be blank
Please generate a new CSR avoiding mistakes that shown above.

How do I include the missing pieces for the main host and all others I need to add certs for?
I am using the PositiveSSL cert.

**Comment by JoshData** [comment]
I would just try a different certificate provider....

**Comment by dazuaz** [comment]
@shido6, You could create a new CSR using openssl and pointing to the private key that miab created on install:

`openssl req -out wildcard_sign_req.csr -key ssl_private_key.pem -new`
