### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by yswery** [mail-in-a-box/mailinabox#356]
Sorry not really any issues but more questions.

Currently I am using iredmail that I had to customise since it didnt suit my needs.

- Does MainInABox support IPv6 out of the box?

- I see you say that your are trying to ``Not be customizable by power users`` Does this mean you do not support or encourage people to fiddle with the configs/setup at all? 

- Also how easy/hard would it be to migrate my emails from iredmail setup to mailinabox? I dont mind recreating the accounts manually since its only ~20 of them, but I do how ever want to have the email contents moved over, any ideas?

- Will the auto installer work just as well on a debain 7 as it does on ubunutu? is there something i should look out for when doing this?

Cheers

**Comment by JoshData** [comment]
> Does MainInABox support IPv6 out of the box?

Yes.

> Does this mean you do not support or encourage people to fiddle with the configs/setup at all?

Correct. If you tinker, you are on your own.

> Also how easy/hard would it be to migrate my emails from iredmail setup to mailinabox?

There are a few ways to do it. I think I used [fetchmail](http://www.catb.org/~esr/fetchmail/fetchmail-man.html) when I did this.

> Will the auto installer work just as well on a debain 7 as it does on ubunutu?

It will stop immediately if it is not running on Ubuntu 14.04.

**Comment by yswery** [comment]
Thanks

**Comment by anoma** [comment]
Perhaps this is the start of a FAQ
