### ISSUE TITLE
How to train and/or manually test the spam filter?

### ISSUE THREAD

**Issue by skosch** [mail-in-a-box/mailinabox#357]
Hi Josh & friends,
I'm getting the same junk messages over and over. I move them into the spam folder every time, but judging by the result (which is invariably another city in my inbox the next morning), either the automatic training isn't being triggered or spamd isn't rejecting working at all. Is there another step I'm missing, and if not, what steps could I take to troubleshoot?
Thanks!

**Comment by dhpiggott** [comment]
On 20 March 2015 12:17:01 GMT+00:00, Sebastian Kosch <notifications@github.com> wrote:
>Hi Josh & friends,
>I'm getting the same junk messages over and over. I move them into the
>spam folder every time, but judging by the result (which is invariably
>another city in my inbox the next morning), either the automatic
>training isn't being triggered or spamd isn't rejecting working at all.
>Is there another step I'm missing, and if not, what steps could I take
>to troubleshoot?
>Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/357

You could take a look at https://github.com/mail-in-a-box/mailinabox/issues/231 for troubleshooting ideas - the output of dump magic and listings showing file permissions would be useful. Also you could tail /var/log/mail.log when receiving/moving mail. It would be useful if you could state which commit you deployed too. FWIW I'm on my way away for the weekend so probably won't engage with this further till next week.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skosch** [comment]
Thanks David. My dump-magic says
````
0.000          0          3          0  non-token data: bayes db version
0.000          0        673          0  non-token data: nspam
0.000          0        199          0  non-token data: nham
0.000          0      79236          0  non-token data: ntokens
0.000          0 1382651168          0  non-token data: oldest atime
0.000          0 1426855709          0  non-token data: newest atime
0.000          0          0          0  non-token data: last journal sync atime
0.000          0          0          0  non-token data: last expiry atime
0.000          0          0          0  non-token data: last expire atime delta
0.000          0          0          0  non-token data: last expire reduction count
````
I suppose I'm getting a lot more spam than ham on this account, which I realize doesn't exactly help the filter in deciding. Still, the bulk of the spam happens to be non-English for some reason, and those ones should be relatively easy to distinguish from my ham. I often get dozens of copies of the same message over several weeks. My Thunderbird catches them, but they still get through. Any ideas, or do I simply need a much larger training set before I can expect results?

According to `git show` I'm on 0aa39418 (from January 4th).

**Comment by dhpiggott** [comment]
OK, so you are running from a relatively recent commit and it doesn't look like it's related #231.

I agree the cause is probably as you suppose - that you're getting a lot more spam than ham. Unfortunately I don't have any ideas for how to help SpamAssassin work well with that.

What I am somewhat surprised at though is that that much spam is getting through Postgrey - I hadn't used Postgrey until I started using MIAB and was pleasantly surprised at how effective it is.

**Comment by stevetoza** [comment]
I have the same issue where, the learning doesn't seem to be working.

I have checked the permissions on the files and they seem to be correct

    root@box:/home/user-data/mail/spamassassin# ls -lah
    total 4.6M
    drwxrwx--- 2 spampd spampd   4.0K Mar 28 13:45 .
    drwxrwxr-x 7 root   www-data 4.0K Mar 17 15:12 ..
    -rw-rw---- 1 spampd spampd   644K Mar 28 13:45 bayes_seen
    -rw------- 1 spampd spampd   5.3M Mar 28 13:45 bayes_toks

When moving an Email from SPAM and into the inbox, leave it there for a couple days, then delete it. Get another email from the same address still goes into spam.

**Comment by dhpiggott** [comment]
Hi Steve. In Sebastian's case we are both of the opinion that learning *is* working, it's just that SpamAssassin isn't able to apply what it knows very well to the type of mail that Sebastian is receiving. And if that is the case, I'd argue the issue isn't a bug in mailinabox as such (though it would be nice if we could improve the situation in some way).

Do you believe that your case is the same (i.e. that learning is working but that SpamAssassin simply doesn't work well on the mail you receive), or do you think it isn't learning at all? I only ask because if it's the former then what would be more useful would be to see the output of dump-magic (ideally before and after receiving a ham and/or a spam).

**Comment by stevetoza** [comment]
Hello, 

When checking the magic-dump, when moving the mail from the spam folder to the inbox, I can see the nspam increases. So implies to me that the learning is working as it should, but the next email coming in isnt then being handled correctly. If you want to check this out on one of my miab, I can can replicate it from an certain email address. Welcome to add me on skype "stevetoza"

**Comment by dhpiggott** [comment]
Could you post the output of running `sudo grep spampd /var/log/mail.log | tail` on the box (munging anything you don't want seen)?

As an example the last two lines of mine are:
```
Mar 28 14:39:13 elm spampd[27336]: processing message <mail-in-a-box/mailinabox/issues/357/87236466@github.com> for <david@piggott.me.uk>
Mar 28 14:39:13 elm spampd[27336]: clean message <mail-in-a-box/mailinabox/issues/357/87236466@github.com> (-0.09/5.00) from <noreply@github.com> for <david@piggott.me.uk> in 0.13s, 4553 bytes.
```

**Comment by stevetoza** [comment]
Sure, 

    root@box:~# grep spampd /var/log/mail.log | tail
    Mar 28 13:45:05 box spampd[17359]: processing message     <5516b05f1835a_31a442d330927d0@app-06-east.us.flowdock.com.mail> for <rachel@domain.com>
    Mar 28 13:45:05 box spampd[17359]: clean message <5516b05f1835a_31a442d330927d0@app-06-    east.us.flowdock.com.mail> (0.01/5.00) from <bounces+35443-8363-     rachel=domain.com@email.flowdock.com> for <rachel@domain.com> in 0.24s, 7625 bytes.
    Mar 28 13:58:39 box spampd[16097]: processing message <0000014c60a4aba5-a8d830d8-bb4e- 4f5c-9c53-e06ca03f03e9-000000@email.amazonses.com> for <steve@domain.com>
    Mar 28 13:58:39 box spampd[16097]: clean message <0000014c60a4aba5-a8d830d8-bb4e-4f5c-  9c53-e06ca03f03e9-000000@email.amazonses.com> (2.22/5.00) from <0000014c60a4aba5-a8d830d8-   bb4e-4f5c-9c53-e06ca03f03e9-000000@amazonses.com> for <steve@domain.com> in 0.07s, 15839   bytes.
     Mar 28 14:04:38 box spampd[29652]: processing message <0000014c60a4ab9c-403df7e5-5074-4f98-b5dd-3dc482952527-000000@email.amazonses.com> for <chris@domain.com>
    Mar 28 14:04:38 box spampd[29652]: clean message <0000014c60a4ab9c-403df7e5-5074-4f98- b5dd-3dc482952527-000000@email.amazonses.com> (2.22/5.00) from <0000014c60a4ab9c-403df7e5- 5074-4f98-b5dd-3dc482952527-000000@amazonses.com> for <chris@domain.com> in 0.07s, 15841  bytes.
    Mar 28 14:10:32 box spampd[17359]: processing message <0000014c60a4a9f0-420ff3e4-d332-49a9-b1a5-fa52f332c614-000000@email.amazonses.com> for <steve@domain.com>
    Mar 28 14:10:32 box spampd[17359]: clean message <0000014c60a4a9f0-420ff3e4-d332-49a9-b1a5-  fa52f332c614-000000@email.amazonses.com> (2.22/5.00) from <0000014c60a4a9f0-420ff3e4-d332-  49a9-b1a5-fa52f332c614-000000@amazonses.com> for <steve@domain.com> in 0.07s, 15749 bytes.
    Mar 28 14:10:48 box spampd[16097]: processing message <0000014c60a4aa42-9c29fc79-b6c2-4316-9b34-2e9e78c2a07f-000000@email.amazonses.com> for <chris@domain.com>
    Mar 28 14:10:49 box spampd[16097]: clean message <0000014c60a4aa42-9c29fc79-b6c2-4316-9b34-2e9e78c2a07f-000000@email.amazonses.com> (2.22/5.00) from <0000014c60a4aa42-9c29fc79- b6c2-4316-9b34-2e9e78c2a07f-000000@amazonses.com> for <chris@domain.com> in 0.07s, 15840  bytes.

**Comment by dhpiggott** [comment]
Thanks. So it looks like SpamAssassin has no problems processing incoming mail, it's just that it isn't always correctly applying what it has learned.  I'm not sure what else to suggest, sorry!

**Comment by stevetoza** [comment]
I agree with that, I have never managed to get it to apply anything that has learnt its never not played nice :smile: Do you know if there is a way to whitelist a domain or IP to stop it from going into the spam folder / could be a handy feature.
