### ISSUE TITLE
Trash folder not created on user create

### ISSUE THREAD

**Issue by stevetoza** [mail-in-a-box/mailinabox#359]
Hello, 

Fresh install of MIAB, when a user is added to miab, it doesn't seem to be creating the "Trash" folder all other folders are created, Drafts, Sent, Junk. When going to delete any emails getting in roundcube:

    Server Error: UID MOVE: Mailbox doesn't exist: Trash

Cheers

Steve

**Comment by fizzytsai** [comment]
See https://gist.github.com/xdobro4/e1436f79f3707917e57b

# Dovecot automatically create a folders for us :)

# vim /etc/dovecot/conf.d/20-imap.conf
mail_plugins = $mail_plugins autocreate

# At the end of file paste following code
plugin {
  autocreate = Trash
  autocreate2 = Junk
  autocreate3 = Drafts
  autocreate4 = Sent
  autosubscribe = Trash
  autosubscribe2 = Junk
  autosubscribe3 = Drafts
  autosubscribe4 = Sent
}

**Comment by JoshData** [comment]
See #554.
