### ISSUE TITLE
Use built in duplicity encryption (GPG) for backups

### ISSUE THREAD

**Issue by dhpiggott** [mail-in-a-box/mailinabox#362]
I've just started overhauling the backup setup I have in place for my webserver. Currently it's just a couple of scripts that wrap rsync - really nothing special, but it's been doing the job OK. After reading about but dismissing bup as not yet mature enough I've decided to go with duplicity, and therefore am using MIAB's rather nice `management/backup.py` script as a model.

On reviewing backup.py I'm reminded that MIAB does not use duplicity's built in encryption support, instead encrypting the files output by duplicity with openssl.

I wondered why it does things this way, because I believe there are a few disadvantages to this approach:
1. The disk space used for backups is more than twice what it would be if duplicity's built in encryption were used (*more* than twice because the encrypted files are being base64 encoded).
2. The openssl command doesn't sign the encrypted files, so there's no way of detecting tampering before a restore. Having duplicity encrypt using GPG would include signatures that would make any tampering evident before a restore.
3. Restorations will require that openssl first be invoked for each encrypted file before they can be fed to duplicity, whereas if duplicity's GPG support were used restoration would be a single-step process.

(If any of these statements are wrong/invalid please correct me!).

I looked at the history of backup.py and found this commit message for 5490142df5da780e9f072d365d6529ad32a7da77 which was when the switch from rdiff-backup to duplicity was made:
>re-do the backup script to use the duplicity program
>
>Duplicity will manage the process of creating incremental backups for us.
>Although duplicity can both encrypt & copy files to a remote host, I really
>don't like PGP and so I don't want to use that.
>
>Instead, we'll back up to a local directory unencrypted, then manually
>encrypt the full & incremental backup files. Synchronizing the encrypted
>backup directory to a remote host is a TODO.

So I have a few questions:
1. Is there a reason for encoding the openssl encrypted backup files in base64?
2. Out of curiousity, @JoshData what is the reason you don't like PGP/GPG? Until a few weeks ago I'd actually never used GPG myself, but I've recently been exposed to it as I've started using git-annex and am using GPG as the encryption backend for a git-annex remote on a Linode.
3. Is there any possibility you might reconsider using duplicity's built in encryption in order to benefit from the advantages I believe it would provide? I could take the lead on making the changes (including making sure upgrades work in a sane way).

For ease of finding them I note that #11 and #262 are somewhat related.

**Comment by JoshData** [comment]
Hey,

> Is there a reason for encoding the openssl encrypted backup files in base64?

No reason. I may not have even realized that was happening. Definitely am open to changing that.

> Out of curiousity, @JoshData what is the reason you don't like PGP/GPG?

It's an extremely complicated system. This is why no one uses it. The complexity of its key management makes it basically impossible for non-experts to know if they're doing things correctly. Normally I'd say "well, it's the best we have", but in GPG's case I think its complexity completely undermines its security --- it gives a false sense of security when, for a non-expert, possibly no security exists at all because of using GPG incorrectly.

I don't trust myself at all to use GPG correctly. And if I can't do it, I can't ask Mail-in-a-Box users to do it.

> Is there any possibility you might reconsider using duplicity's built in encryption in order to benefit from the advantages I believe it would provide?

Yes. We just need an easy and impossible-to-screw-up method for performing the encryption and a restore. So, e.g., Mail-in-a-Box needs to totally manage the keystore used for encryption / decryption. I wouldn't even persist the keystore anywhere so there is no possibility that the backup/restore doesn't know exactly what's in it: Just recreate a one-off keystore (from a key persisted in /home/user-data) each time there is a GPG operation.

And we need a restore script + instructions (which embarrassingly we don't even have for the existing method, except someone did an amazing blog post explainer a while back).

How does that sound?

**Comment by dhpiggott** [comment]
>It's an extremely complicated system. This is why no one uses it. The complexity of its key management makes it basically impossible for non-experts to know if they're doing things correctly...

I share that sentiment - the learning curve is steep and (for example) it took me quite a bit of searching to get a satisfactory answer to my question of why GPG generated me two keys (in case anyone reading this wants to know, I found point 2 of http://security.stackexchange.com/a/43591 and http://security.stackexchange.com/a/8563 - which it links to - to be good explanations).

>I don't trust myself at all to use GPG correctly. And if I can't do it, I can't ask Mail-in-a-Box users to do it.

I am also cautious of getting something wrong. With regard to MIAB users, my idea was that we would take care of it for users in the sense of making the required reading and understanding minimal (perhaps/ideally no more than the current system).

>So, e.g., Mail-in-a-Box needs to totally manage the keystore used for encryption / decryption.

Yes :)

>I wouldn't even persist the keystore anywhere so there is no possibility that the backup/restore doesn't know exactly what's in it:

Not sure I follow this entirely - it reads as contradictory to me. At minimum the public encryption key would need to persist on the MIAB, and the private signing key (and possibly/probably the public verification key [if we go for signing] would need to as well) (so nothing extra - so far - that users would need to know was happening or care about).

The private decryption key would need to be retained by the user separately from the backups (as the current decryption key must be), and the public verification key (if we go for signing) ought also to be kept by the user so they can know when restoring that the backups have not been tampered with.

>Just recreate a one-off keystore (from a key persisted in /home/user-data) each time there is a GPG operation.

I don't understand the bit about one-off keystores. I do follow and agree with the idea of a GPG keystore in a home directory, but I think it should be and would need to be `/root`, because the keystore itself shouldn't be included in backups, and because duplicity is run as root (and in my experiments just now I found that duplicity only supports overriding the path to the private keyring via `--encrypt-secret-keyring`; it does not support overriding the path to the public keyring`).

I've been playing around with duplicity's encryption/signing options on and off this afternoon, and while I'm now happy that I understand its asymmetric mode (which I think is probably what we should use), I don't yet fully understand its symmetric mode (which allows encrypted backups to be made without use of any GPG keystore, just a passphrase given to duplicity - and I believe they are signed too). I will probably continue digging until I understand how the symmetric mode actually works, but from what I've learned so far I'm in favour of the asymmetric mode we've primarily been discussing.

>And we need a restore script + instructions (which embarrassingly we don't even have for the existing method, except someone did an amazing blog post explainer a while back).

I would make any changes with consideration of restores in mind; I might go on to develop a restore script + instructions.

**Comment by JoshData** [comment]
> I don't understand the bit about one-off keystores.

Maybe I mean keyring. The problem I have in mind is that GPG may know about many keys.  What key does it encrypt/sign with? What keys does it consider trusted when verifying a signature? This is the part of GPG that is totally incomprehensible and why I want to avoid the possibility that the wrong key is used at any part of the process (because of course the wrong key during verification could mean trusting something you shouldn't). So it's the stash of keys that GPG knows about that I'm concerned about --- as opposed to persisting the key itself. 

As for the key itself - Can it be the same key used for signing & decryption? I think so (in principle).

And I really want to keep it in /home/user-data so that it won't get accidentally lost if the user changes servers. If the backup is encrypted, there's no issue if the key itself is inside the backup, right? Currently I think I have a special exclusion rule in duplicity to exclude the key anyway.

> duplicity only supports overriding the path to the private keyring via --encrypt-secret-keyring; it does not support overriding the path to the public keyring

That could be a problem.

**Comment by dhpiggott** [comment]
>Maybe I mean keyring. The problem I have in mind is that GPG may know about many keys. What key does it encrypt/sign with? What keys does it consider trusted when verifying a signature?

Ah, right. Yes, I was implying in my above reply but not directly stating that backup.py would generate a GPG keypair on first run, and it would be stated in the documentation for MIAB that using GPG on the box is not supported. That would ensure the keyring would only contain the keys duplicity should use. Though in fact I would also make backup.py "pin" itself to using the keys that it generated (just by writing the short form fingerprints to a text file or two in user-data/backup), so it wouldn't be a problem if someone did end up adding other keys for some reason.

>As for the key itself - Can it be the same key used for signing & decryption? I think so (in principle).

I think it can in principle, yes. And I know in this case that the normal reasons (given in that security.stackexchange answer) for having two keys don't really apply. However I was going to use two keys simply because that is what GPG generates by default and it might complicate the auto-generation that I'd make backup.py do if I made it get GPG to generate only one key.

>And I really want to keep it in /home/user-data so that it won't get accidentally lost if the user changes servers. If the backup is encrypted, there's no issue if the key itself is inside the backup, right? Currently I think I have a special exclusion rule in duplicity to exclude the key anyway.

I don't see any reason why it shouldn't be in the backup, though if we did have it within `/home/user-data` I would exclude it in the same way that you've excluded the current key. I don't entirely follow the reasoning about changing servers though; if a user has not already got a copy of the key(s) at the point that they change server, it would surely be because they do not care about (MIAB's built in) backups and so do not have off-server copies, in which case they would be no worse off if they lost the key.

>That could be a problem.

Yes, but maybe no. If we do go for asymmetric encryption I think it would either mean the GPG keyring would have to be in /root/.gnupg (and you've explained your objection to that above), or - perhaps - we might be able to workaround with some hackery e.g. hard/sym-linking /root/.gnupg into /home/user-data. But something tells me that would be a bad idea and it's just that I don't know why.

However... having said what I said about symmetric encryption above (that I still need to understand what duplicity does in that mode), I've yet to find a reason why we couldn't/shouldn't just use that. I've yet to see that it would be inferior for this use case in any way, and on switching to it the existing secret key given to openssl could instead simply be given to duplicity as a passphrase.

**Comment by dhpiggott** [comment]
I figured out what the symmetric mode does. My mistake was in thinking that duplicity does something special itself, but it doesn't - symmetric encryption is actually just a feature of GPG and duplicity calls through to that. Hence I didn't find any documentation from duplicity about it but plenty from GPG.

And now I know that I really see no reason for us to make things complicated by involving GPG keyrings - much as reasoning about asymmetric key management can be fun, this use case doesn't really require it.

Unless you have any objections I may proceed directly to creating a (first draft of a) PR - it should be very simple.

**Comment by hopfi2k** [comment]
As MIAB usually is doing all the DNS stuff (if not using an external DNS-Server), one could consider using PKA (e.g. https://keyserver.mattrude.com/guides/public-key-association/ <https://keyserver.mattrude.com/guides/public-key-association/> or http://lists.gnupg.org/pipermail/gnupg-devel/2015-February/029544.html <http://lists.gnupg.org/pipermail/gnupg-devel/2015-February/029544.html>) or OPENPGPKEY (https://tools.ietf.org/html/draft-ietf-dane-openpgpkey-02 <https://tools.ietf.org/html/draft-ietf-dane-openpgpkey-02>) to store the PGP key in the corresponding DNS record. Although still not widely adopted it is quite easy to implement and could be an approach to avoid all the keyring/keyserver problems…

Just my 2cents...

**Comment by JoshData** [comment]
@dhpiggott That sounds great.

@hopfi2k I don't think that will solve anything with duplicity, but certainly could be handy for other purposes.

**Comment by dhpiggott** [comment]
Oops... looks like my bad habit of continually amending and pushing commits* has resulted in a lot of automatically generated spam here. I wish GitHub didn't do that, or that it would at least let me remove the auto-references.

Sorry!

Anyway, PR is imminent now.

*I've suffered enough hardware and user failures I'm somewhat paranoid about data loss.

**Comment by JoshData** [comment]
Haha no worries.
