### ISSUE TITLE
Release candidate v0.08

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#364]
Hey, if anyone has some spare cycles, please try out the current master branch! Changelog (from CHANGELOG.md) follows.

---

Mail:

* The Roundcube vacation_sieve plugin by @arodier is now installed to make it easier to set vacation auto-reply messages from within Roundcube.
* Authentication-Results headers for DMARC, added in v0.07, were mistakenly added for outbound mail --- that's now removed.
* The Trash folder is now created automatically for new mail accounts, addressing a Roundcube error.

System:

* ownCloud updated to version 8.0.2.
* Brute-force SSH and IMAP login attempts are now prevented by properly configuring fail2ban.
* Status checks are run each night and any changes from night to night are emailed to the box administrator (the first user account).

Control panel:

* The new check that system services are running mistakenly checked that the Dovecot Managesieve service is publicly accessible. Although the service binds to the public network interface we don't open the port in ufw. On some machines it seems that ufw blocks the connection from the status checks (which seems correct) and on some machines (mine) it doesn't, which is why I didn't notice the problem.
* The current backup chain will now try to predict how many days until it is deleted (always at least 3 days after the next full backup).
* The list of aliases that forward to a user are removed from the Mail Users page because when there are many alises it is slow and times-out.
* Some status check errors are turned into warnings, especially those that might not apply if External DNS is used.

**Comment by dhpiggott** [comment]
I've been running 298e19598bdb609fca5ad392c0c1ed0fa04a2a4b for about a week now, and I've just updated to 3d21f2223e83f09a94368608952933f3e3843741. I've not had any problems - everything is working nicely. Thanks to you and all who contributed for your efforts.

**Comment by hnk** [comment]
Just rolled this out on a testbox.

Installed 0.7 via official guide, added master branch and did a git pull and subsequent 'mailinabox' command.
* Upgrade to owncloud 8.0.2 went smooth.
* Vacation sieve plugin is added in roundcube. I cannot test it, as this testbox is not able to send or receive mail.

I would say this is looking good. Can't wait for you to pull in @dhpiggott's duplicity encryption changes ;)

**Comment by hnk** [comment]
And another info, for the people that, like me, run owncloud using mariadb (as sqlite just did not work out with the amount of data that is actually in owncloud among all my users):

Updating to v0.08 works like a charm also and owncloud starts up without an issue and all data on my testbox is there ;)

**Comment by ianberinger** [comment]
I've been running https://github.com/mail-in-a-box/mailinabox/commit/3d21f2223e83f09a94368608952933f3e3843741 since yesterday. So far I haven't encountered any problems. Thanks for all the great work!

**Comment by stevetoza** [comment]
Same no issues found

**Comment by JoshData** [comment]
Thanks all. I pushed two more commits last night. Will give it a few more days of testing and then will release.

**Comment by stevetoza** [comment]
Hey Josh, 

Wondering if you was going to release the update today or tomorrow, holding off installing miab on a new server until this one is out.

Cheers

**Comment by JoshData** [comment]
It's now posted:

https://github.com/mail-in-a-box/mailinabox/releases/tag/v0.08

The simple upgrade is:

    curl -s https://mailinabox.email/bootstrap.sh | sudo bash

Thanks everyone.
