### ISSUE TITLE
owncloud 8 complains that default_charset is unset.

### ISSUE THREAD

**Issue by hnk** [mail-in-a-box/mailinabox#367]
This is not directly related to miab but I think it should be configured when using owncloud.

When owncloud 8 is installed and one opens the admin console, it advises you of misconfigurations.

It tells you that `default_charset = "UTF-8"` should be set in the files `/etc/php5/fpm/php.ini` and `/etc/php5/cli/php.ini`.

I am not sure if this is a critical issue, but I think it may be a good idea to configure it nonetheless.

**Comment by JoshData** [comment]
I don't know what the practical ramifications are, but we might as well. We'll do it after the next release, though.

ref: http://php.net/manual/en/ini.core.php#ini.default-charset
