### ISSUE TITLE
owncloud 8 complains that php5-apcu is below version 4.0.6

### ISSUE THREAD

**Issue by hnk** [mail-in-a-box/mailinabox#368]
This is not directly related to miab but I think it should be configured when using owncloud.
When owncloud 8 is installed and one opens the admin console, it advises you of misconfigurations.

Apparently there are some critical issues in the php5-apcu version 4.0.2 that is supplied with Ubuntu 14.04.

There is a new version 4.0.6 which *may* be backported to ubuntu 14.04 as [per this bugreport](https://bugs.launchpad.net/ubuntu/+source/php-apcu/+bug/1374892) but there has not been much progress as of late.

See [this issue at the owncloud repo](https://github.com/owncloud/core/issues/14386) for a fix by installing directly the release deb of the developers. Should this fix be applied here as well?

**Comment by JoshData** [comment]
Ugh. Is this a new problem with ownCloud 8?

**Comment by JoshData** [comment]
Per https://github.com/owncloud/core/pull/14273, ownCloud is smart enough to just not use APCu at the version installed with Ubuntu 14.04. There will be less caching of things, but at least no crashes.

**Comment by hnk** [comment]
Ok that would close this, once it is backported. Then we can only hope that upstream ubuntu will backport the new packages...

**Comment by jackbravo** [comment]
Here is the issue for ubuntu: https://bugs.launchpad.net/ubuntu/+source/php-apcu/+bug/1374892

**Comment by hnk** [comment]
From what I understand owncloud now works around this issue by checking acpu version and disabling usage of acpu if the version is below 4.0.6.
So this issue here can be closed.
