### ISSUE TITLE
Fail2Ban doesn't monitor input connection from IPV6

### ISSUE THREAD

**Issue by Xoib** [mail-in-a-box/mailinabox#374]
Hello,

Keeping ipv6 enabled and setup for all services is very good. But fail2ban should also be configured to monitor that ip stack. Like the ipv4 do.

Thanks,

**Comment by anoma** [comment]
Unless I am mistaken ipv6 support in Fail2ban is still experimental beyond even the 0.9 branch (and we are still on 0.8)

https://github.com/fail2ban/fail2ban/issues/39

To my eye this is an upstream problem.

**Comment by Xoib** [comment]
So doesn't we should disable ipv6 input support to be fully secure ? Because knowing that fail2ban on ipv4 is useless as an attacker will simply focus on ipv6 address to hack the services...

**Comment by JoshData** [comment]
There is no such thing as fully secure. :)

**Comment by Xoib** [comment]
True. Anyway letting access to ipv6 side of services but protecting ipv4, it's kind of a false sentiment of security (against flood and bruteforces).

**Comment by dhpiggott** [comment]
Perhaps, but retaining fail2ban doesn't do any harm and does provide some benefit*, and it ensures the groundwork remains in place ready for when fail2ban does support IPv6.

*most attacks against most boxes will likely just be bots looking for weak targets, so it may well be that they do just move on to another target when they are IPv4 blocked - as opposed to targeting the same box by IPv6, as an attacker specifically interested in a given box may do.

**Comment by Xoib** [comment]
So the point is shared. Thanks for your answers.
