### ISSUE TITLE
Owncloud issues 

### ISSUE THREAD

**Issue by stevetoza** [mail-in-a-box/mailinabox#375]
Hello, 

Just wondering if anyone else is having issues with Owncloud version 8 when using the Owncloud client, after an hour or so its causing php-fpm to crash and show 502 Bad gateway errors only way to get it back going again is to restart php-fpm then it dies again after a little while 

Same as the issue that has been reported here [14187](https://github.com/owncloud/core/issues/14187)

Just testing the workaround by disabling APC(u) see if that makes any difference:

Disabling APC(u)

    In /etc/php5/fpm/conf.d/20-apcu.ini
    ;extension=apcu.so
    apc.enabled=0

Suppose could be something to do with [368](https://github.com/mail-in-a-box/mailinabox/issues/368)

Cheers

Steve

**Comment by sqeezy80** [comment]
i can report the same problem. Will try disabling apcu.

**Comment by JoshData** [comment]
ownCloud 8.0.3 fixed some problem where disabling acpu wasn't actually disabling it or something, fyi.

**Comment by stevetoza** [comment]
Cheers Josh for checking this out, Is 8.0.3 going to the default in the next release?

**Comment by JoshData** [comment]
No I'm holding off because I want to get the next MiaB update out (this weekend) without having to wait on testing ownCloud.

**Comment by stevetoza** [comment]
Makes sense :+1:

**Comment by jackbravo** [comment]
I don't know if this issue could be related:

https://discourse.mailinabox.email/t/consider-listening-on-port-instead-of-socket-for-php5-fpm/434

If this keeps happening maybe switching to port instead of socket could be worth while?

**Comment by JoshData** [comment]
I really don't think that has anything to do with it.

I just committed a new commit to update to 8.0.3. Let me know if anything helps.

**Comment by JoshData** [comment]
Closing because of #514.
