### ISSUE TITLE
"key data is not secure" warnings from opendkim

### ISSUE THREAD

**Issue by stinos** [mail-in-a-box/mailinabox#379]
For every mail sent mail.log has an entry like
```
key data is not secure: opendkim is in group 33 which has multiple users (e.g., "www-data")
```
because the `/home/user-data/mail` directory has `www-data` as group (this is set near the end of setup/webmail.sh), see explanation [here](http://lists.opendkim.org/archive/opendkim/users/2014/12/3331.html). 

After I changed the owner of the mail directory to root opendkim doesn't complain anymore and as far as I can tell there are no other problems either: the roundcube subdirectory of mail does have www-data as group which should be sufficient?

**Comment by JoshData** [comment]
The thing to check would be Roundcube's password changing function.

**Comment by stinos** [comment]
Good point, didn't realize the sqlite db there. And indeed I get `DB Error: [14] unable to open database file` when trying to change the password now..

**Comment by JoshData** [comment]
Btw, similar issue as #369.

**Comment by JoshData** [comment]
Also #125.
