### ISSUE TITLE
Switch to Mailpile

### ISSUE THREAD

**Issue by martindale** [mail-in-a-box/mailinabox#384]
Roundcube is pretty rough around the edges.  We should switch over to something nice and clean – I really like [Mailpile](https://github.com/mailpile/Mailpile).

**Comment by JoshData** [comment]
Mailpile is nowhere near ready to be deployed, last I checked. Happy to reevaluate when they drop the beta label.

**Comment by luxpir** [comment]
<ping>Looks like they've dropped the beta label and are actively developing again.</ping>
