### ISSUE TITLE
Cannot download files via ownCloud.

### ISSUE THREAD

**Issue by sbidin** [mail-in-a-box/mailinabox#385]
I can create ownCloud directories and upload files to them just fine, but when I try to download any of these uploaded files (by clicking on one of them in the directory view), I get a 404. Here's an example URL that cannot be found when I clicked on `singlefile.epub` within the `somedirectory` directory:

    https://mydomain.tld/cloud/index.php/apps/files/ajax/download.php?dir=/somedirectory&files=singlefile.epub.

**Comment by sbidin** [comment]
That was using the newest stable Firefox.

Using Chromium 42, I get Chromium's ERR_INVALID_RESPONSE page instead.

**Comment by sbidin** [comment]
Here's the error I get in `nginx/error.log`:

    2015/04/28 21:56:41 [error] 1985#0: *6460 open() "/home/user-data/www/default/home/user-data/owncloud/myname@mydomain.tld/files/somedirectory/singlefile.epub" failed (2: No such file or directory), client: 123.456.78.9, server: mydomain.tld, request: "GET /cloud/index.php/apps/files/ajax/download.php?dir=%2Fsomedirectory&files=singlefile.epub HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "mydomain.tld", referrer: "https://mydomain.tld/cloud/index.php/apps/files?dir=%2Fsomedirectory"

So it seems `/home/user-data/owncloud` is getting appended to `/home/user-data/www/default` somehow.

**Comment by sbidin** [comment]
OwnCloud sets the `X-Accel-Redirect` header to:

    /home/user-data/owncloud/myname@mydomain.tld/files/somedirectory/singlefile.epub

I don't know much about this, but it seems to me that no nginx conf location matches this URI. Therefore, adding this to nginx.conf fixes the issue for me:

    location /home/user-data/owncloud {
        internal;
        root /;
    }

**Comment by sbidin** [comment]
Gods, this was fixed 8 days ago.

This should teach me to try the newest version before complaining.

**Comment by JoshData** [comment]
Yep sorry! I saw your posts coming in and couldn't warn you in time. Thanks for looking into it though!

**Comment by JoshData** [comment]
For posterity: This was fixed in 6bb8f5d889b5880c75d3fba9768ebd0db3f5d6e2.
