### ISSUE TITLE
Blacklisted on RATS-Dyna. Missing PTR Record ?

### ISSUE THREAD

**Issue by Toilal** [mail-in-a-box/mailinabox#386]
After running a check on [mxtoolbox blacklist](http://mxtoolbox.com/blacklists.aspx) tool, it appears my server is blacklisted on RATS-Dyna.

> RATS-Dyna - Probable PC or home connection infected with a Trojan, Bot, or Emailer Program -- If you are listed in the Spamrats / RATS-Dyna blacklist and you operate your own mail-server, you likely have no valid PTR-Record. If you are simply a home email user, you have a dynamic IP Address and may need to contact your ISP for assistance. If you operate a domain name and are using your ISP for SMTP-Authentication, try contacting your DNS Provider to use their SMTP-Services instead.

I think it's because of a missing PTR-Record. I'm using External DNS, but it can't see any check in "Advanced DNS" configuration page for this PTR-Record.

Does the internal DNS Server registers a PTR-Record ?

**Comment by JoshData** [comment]
PTR is the same as reverse DNS. There's a check for IPv4 reverse DNS in the status checks, so you should see that there. If you have an IPv6 address there's no check for that yet. Both are set at your cloud server provider --- it's not something the box can do itself.

It could be that you ended up with an IP address that was previously used to send spam.

**Comment by Toilal** [comment]
Ok, thanks for the explanations ! The blacklist occurs in a single list, so it's probably a temporary false positive as you've stated. Thanks.
