### ISSUE TITLE
Version 0.09 release candidate - help me check!

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#388]
Hello all,

If anyone has some spare time, please try out the master branch and let me know if you run into any issues or not. If this looks good, I'll release it as v0.09 next weekend.

As soon as it goes up I'll also be posting a video tutorial for setup, which I am excited about.

Thanks.

**Comment by JoshData** [comment]
Preview of video: https://www.youtube.com/watch?v=HQOj-Mm1fYs

**Comment by dhpiggott** [comment]
I deployed master earlier today - it's all working nicely so far.

I've just watched your video - it looks good. I imagine that having concrete examples for each setup step will make the prospect less intimidating for potential users who are not yet familiar with the things each step entails.

Did you mean to say don't share the certificate with anyone at https://www.youtube.com/watch?v=HQOj-Mm1fYs&feature=youtu.be&t=1065?

Thanks as always for your efforts.

**Comment by JoshData** [comment]
Thanks! 

> Did you mean to say don't share the certificate with anyone

Oh. That was dumb. Obviously it gets shared with everyone. I'll strike it from the script for the next time I update the video.... but that won't be soon. (And probably on a day when I'm less nasal...)

The v0.09 release is posted!
