### ISSUE TITLE
DKIM signature is missing from the SMTP sending

### ISSUE THREAD

**Issue by nephthys** [mail-in-a-box/mailinabox#39]
Hi,

The mail server works fine but I have a question about DKIM. When I send a message from my server via mail command line, the DKIM signature is added. When I send via SMTP (from my mail client), the signature is missing. Is this normal?

Thanks for your help.

**Comment by rajkotraja** [comment]
Having same problem. i havent added any new user. only the one created as admin while installation.
Signs when sending mail from roundcube, but does not sign when sending using SMTP.
