### ISSUE TITLE
System Status Page fails when installing into Container

### ISSUE THREAD

**Issue by efries** [mail-in-a-box/mailinabox#398]
I have installed mailinabox into a LXD Container.

I'm port forwarding to the private Container IP.

Every Service seems to work fine, but the system status page fails because it can not connect to the public ip address from the container.

Not sure if this is something that could or should be fixed in code or if there is just an other workaround?

You can see here how I have installed the LXD/LXC Container. 
http://blog.inetpeople.net/mail-in-a-box-with-lxd-container/

Here the forum post for the issue in the discussion forum:
https://discourse.mailinabox.email/t/system-status-pages-shows-errors-when-port-forward-to-container/470?u=efries

**Comment by JoshData** [comment]
I think it could be a problem if the box can't connect to itself. Can you revise your networking settings?

**Comment by efries** [comment]
@JoshData: true, that's the problem. I have commented the post on discourse with my setting and error log.

Regarding your code:
I'm asking me if it makes sense to set an Environment Variable to test against the local IP, if the server runs with NAT? 

Something like:
NAT_NETWORK=1

if $NAT_NETWORK set $PUBLIC_IP == $LOCAL_IP

**Comment by JoshData** [comment]
You can override PUBLIC_IP with whatever you want by setting the environment variable prior to starting the setup, but you're on your own if you lie to the system.

Discussion moved to https://discourse.mailinabox.email/t/system-status-pages-shows-errors-when-port-forward-to-container/470/3, so closing this here.
