### ISSUE TITLE
A little bit of security backup.

### ISSUE THREAD

**Issue by bizonix** [mail-in-a-box/mailinabox#399]
I am not strong in python, but I noticed some "mistakes" in the code!

https://github.com/mail-in-a-box/mailinabox/blob/febfa72d60e03568c31a865cd15f5b8ed9f71d45/management/backup.py#L179
firstly in the function "perform_backup" only read one line from a file.

https://github.com/mail-in-a-box/mailinabox/blob/febfa72d60e03568c31a865cd15f5b8ed9f71d45/management/backup.py#L257
secondly, as a function of "run_duplicity_verification" file is read together with line breaks, which is not correct, because GPG will take only the first line of text.

Examples:
```
root at box in  /tmp
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, os.path
>>> backup_root='/tmp/'
>>> with open(os.path.join(backup_root, 'secret_key.txt')) as f:
...     print f.readline().strip()
...
HaZ6azVz0LR5U1ed30gn+AASAlwz15/6fBl3bmZC0Wvv3KzcKj6PGWPwQorKh7t4
>>> print open(os.path.join(backup_root, 'secret_key.txt')).read()
HaZ6azVz0LR5U1ed30gn+AASAlwz15/6fBl3bmZC0Wvv3KzcKj6PGWPwQorKh7t4
eiGyFZgkYhgBcQ9rBKAMv9lryWj1rMNy/zTWG1oT0HUsMmmUqH4hjBAivjQus/a/
more 39 lines
hJ+6/tgY/EzjbuYYc47qGpkq7Wpv6oPDouNBfgmVau9+2qBD9QrpmC2XsfW2W4Ag
udw5rHjZsN/1MAX7pGEe2uLqX4bQEea+UTh7PGQ6gAk=

>>>
```

**Comment by JoshData** [comment]
It's not elegant, but it's not incorrect. I would accept a pull request to make the code clearer, but I'm going to close this issue because there's no actual bug.

**Comment by bizonix** [comment]
ok, only why was to generate keys of size 2048 bits if only the first 64 bits of this key are used?
excuse for my English!

**Comment by JoshData** [comment]
We were using a different encryption method earlier.

**Comment by bizonix** [comment]
So you know that you are using only 64 bits?

**Comment by JoshData** [comment]
We're using a cipher (AES256) that uses a 32 byte key. We're checking that the input (the first line of the passphrase file) is at least 65 base-64 encoded characters, which means it has at least 32 bytes of entropy. I don't think anything is "64 bits".
