### ISSUE TITLE
Try my postgrey for less wait times

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#400]
Hello all,

I've packaged an [alternative version of postgrey](https://github.com/mail-in-a-box/postgrey/commit/6e741dbce993e8d9fa6465467ce806f389ed9a9e) in a new [Mail-in-a-Box PPA](https://launchpad.net/~mail-in-a-box/+archive/ubuntu/ppa) on Launchpad.

As you may know, postgrey implements greylisting. The first time a new sender emails you, their message is rejected with a temporary failure error. Spammers don't usually bother re-sending, but all protocol-compliant senders will retry after usually 10-15 minutes, at which point greylisting lets the mail through.

My [fork of postgrey](https://github.com/mail-in-a-box/postgrey/commit/6e741dbce993e8d9fa6465467ce806f389ed9a9e) whitelists all senders whitelisted by [dnswl.org](https://www.dnswl.org): Any email from IP addresses that have good reputation are delivered immediately without greylisting. You'll see something like this in your `/var/log/mail.log`:

> May 19 10:58:34 box postgrey[32473]: action=pass, reason=client whitelisted by dnswl.org (3/highly unlikely to send spam), client_name=github-smtp2-ext6.iad.github.net, client_address=192.30.252.197, sender=noreply@github.com, recipient=myname@example.com

I've been using this for about a year (and [tried to submit a patch upstream](https://github.com/schweikert/postgrey/pull/12)), but this is the first time I've packaged up the changes into a deb & PPA.

To install, add the PPA and then just upgrade packages. The PPA's postgrey will replace the stock postgrey package:

    apt-add-repository ppa:mail-in-a-box/ppa
    apt-get update
    apt-get upgrade

Also note [dnswl's license terms](https://www.dnswl.org/?page_id=9):

> Every user with more than 100’000 queries per day on the public nameserver infrastructure and every commercial vendor of dnswl.org data (eg through anti-spam solutions) must register with dnswl.org and purchase a subscription.

But I don't think anyone using a Mail-in-a-Box would (or even could) hit that volume.

Please try it out and let me know if it works and helps!

(You may also be interested in my [build script](https://github.com/mail-in-a-box/mailinabox/tree/master/ppa) which updates the PPA, and my [changes to the Debian postgrey package](https://github.com/mail-in-a-box/postgrey/commit/master).)

**Comment by stevetoza** [comment]
Hello, 

Trying this out on 2 mail servers I run. Makes a good improvement and helps out a lot with the delay in grey listing.

**Comment by hnk** [comment]
Installed just now, thanks for supplying that ppa! Will report any issues, but judging from your track record, this will work out just fine ;)

**Comment by cooperaj** [comment]
Got this installed. We'll see how it goes.

**Comment by PortableTech** [comment]
Installed, testing now.

**Comment by stevetoza** [comment]
Had this installed for days, working like a charm :+1:

**Comment by nstanke** [comment]
After an reboot I had to manually purge postgrey and reinstall to make it work again. 

`POSTGREY_OPTS=--inet=127.0.0.1:10023: not found`

**Comment by JoshData** [comment]
Sounds like you pulled https://github.com/mail-in-a-box/mailinabox/pull/403, but the PR wasn't right. You'll need to roll that back and just clean up that line in `/etc/default/postgrey`. (I wiped the merge from the `master` history.)

**Comment by nstanke** [comment]
Sorry, I knew I saw someone reporting this issue before but couldn't find it. Everything seems to work now. 

Thank you. :+1:

**Comment by JoshData** [comment]
No worries.

**Comment by Xoib** [comment]
My bad @nstanke, fixed in #412.

**Comment by JoshData** [comment]
Thanks all. The PPA is now added to boxes, via #406, so the next release of MiaB will have the patched postgrey.
