### ISSUE TITLE
fail2ban jail.local IGNOREIP and other enhancements

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#401]
Currently we overwrite jail.local on mailinabox upgrades.

Whilst I realise that customisation at the OS level is unsupported ideally we would either support the addition of fail2ban INGOREIPS via the admin GUI or maintain any list added to jail.local.

Since we now run Fail2Ban v0.8.11 I believe this might be more elegantly solved with

https://github.com/fail2ban/fail2ban/pull/121

which opens the door for further enhancements

**Comment by JoshData** [comment]
Can you write a pull request?

**Comment by anoma** [comment]
Let me look into this. I haven't used this layout before but it should be easy enough.

**Comment by JoshData** [comment]
This didn't seem important enough to do, so ok to close this issue?

**Comment by anoma** [comment]
I got sidetracked with jails. Please let me have a bit more time or close and I will reopen

**Comment by anoma** [comment]
After far too much reading of vague documentation as discussions I have hit the gold mine that explains exactly how this works:

https://www.digitalocean.com/community/tutorials/how-fail2ban-works-to-protect-services-on-a-linux-server

the tl;dr version is that we can stop using jail.local completely and use .conf files. This will allow us to ship with the stock config (which can be controlled by apt in the normal way), specific MIAB overides we can track in git and deploy during install time and upgrades but also leave the door open permanent config changes the user puts in place.

I am however going to close this ticket. A later PR will make use of this technique when introducing a bunch more changes.
