### ISSUE TITLE
NSA-hackable?

### ISSUE THREAD

**Issue by filipecatraia** [mail-in-a-box/mailinabox#402]
Hi,

I'm having trouble with this bit:

> _Not be a mail server that the NSA cannot hack._

The double-negative means you're trying to make this a mail server that the NSA __can__ hack?

**Comment by JoshData** [comment]
Correct!

(Define "can hack" and I can be more specific.)

**Comment by benschumacher** [comment]
I think the intention is to not make grand claims that are difficult to prove. Claiming that this software is unhackable by NSA is nearly impossible to prove and sets an unreasonable expectation. The goal (in my opinion) is to provide greater privacy than many of the shared services (i.e. Gmail reads your email) and, by default, attempt to inhibit passive surveillance by preferring encryption over-the-wire.

**Comment by filipecatraia** [comment]
@benschumacher Yes, I think so. I got that from the project itself, and as an engineer I wouldn't presume anything to be _unhackable_. Not even air-gapped computers. But then I would say it's best to remove that particular sentence, or refrase it as you've put it.

**Comment by JoshData** [comment]
Early on a lot of the feedback was about how whatever I was doing wasn't helpful because the NSA could still crack it. Being up front that unhackable security isn't the number one goal has been helpful. 

I've tweaked the language, though. Thanks.

**Comment by filipecatraia** [comment]
Nah, no thanks. I was bitching about language. But sorry about the NSA thing, people can be stupid some times.
