### ISSUE TITLE
Sync Contact Llist Between RoundCube and ownCloud

### ISSUE THREAD

**Issue by PortableTech** [mail-in-a-box/mailinabox#405]
I would like to have a way to allow the contact list in RoundCube to be able to sync with the contact list in ownCloud.  Obviously when one considers outside sync sources such as Android, having a common contact list would be greatly beneficial.  And honestly, no one wants to have to maintain the same contact list in two locations.  

This issue was addressed previously, but the issue ticket was changed into a different item and eventually closed.

Ref: https://github.com/mail-in-a-box/mailinabox/issues/169

Additionally, there is a RoundCube plugin for this that has been very recently updated that may solve this easily.  

Ref: https://myroundcube.com/myroundcube-plugins/carddav-plugin

Thoughts, ideas, or suggestions welcome.

**Comment by h8h** [comment]
Write a PR and I like you :-) Otherwise I'll do it asap

**Comment by PortableTech** [comment]
You want me to write a Press Release?  I am sure I am being dense here, but I am not quite following you. :)

**Comment by h8h** [comment]
I'am sorry - Pull Request. I want you to write some code :-)  and yeah some good documentation to that code is also not bad.

**Comment by PortableTech** [comment]
Actual code writing is not my forte.  I am sure I could get it working on my box, but I figure an integrated solution is all the better.

**Comment by h8h** [comment]
No matter.

**Comment by PortableTech** [comment]
If there is any other way I can help please let me know.  Don't get me wrong, I am technical, and a SysAdmin by trade, just would hate to send crappy code to such a great project.

**Comment by h8h** [comment]
Sorry I don't want to force you to contribute code to this project. I think this project needs coders as well as idea generators. So thanks for contributing your idea and I think that this plugins makes absolutely sense and I don't know why its not implemented yet.

**Comment by PortableTech** [comment]
Tell you what, if someone can get it worked in, I would be happy to contribute to the buy the coder a beer fund.

**Comment by h8h** [comment]
:+1:

**Comment by JoshData** [comment]
See #409.

**Comment by PortableTech** [comment]
Now, where did you place that buy a coder a beer button?
