### ISSUE TITLE
Whiteout Mail

### ISSUE THREAD

**Issue by rockman73** [mail-in-a-box/mailinabox#416]
Been using the Chrome App mail client and it is quite nice. Consider including the webmail component?
https://github.com/whiteout-io/

It would also be nice if their Whiteout Mailbox Service is Open Sourced.
https://whiteout.io/technology.html

**Comment by JoshData** [comment]
There's a lot I like about Whiteout. But I actually find the crypto aspects very confusing (and some parts are buggy). And the UI is extremely unfriendly to accessibility (the color palette has extremely low contrast --- I can hardly read the menus, and when installed as a Chrome app I can't zoom in/enlarge text). So I have mixed feelings here.

They have built some very nice infrastructure though.

**Comment by rockman73** [comment]
I agree. I would a higher contrast UI myself. I suspect they spent most of the dev work on the infrastructure. I jsut created a new issue: https://github.com/whiteout-io/mail-html5/issues/362

**Comment by JoshData** [comment]
Great.

**Comment by JoshData** [comment]
I'm going to close this. As in #169, there's really nothing for us to do on this.
