### ISSUE TITLE
Trouble with DNSSEC signing keys, and docker run example ?

### ISSUE THREAD

**Issue by fab5741** [mail-in-a-box/mailinabox#417]
Hi, i am running the project in a docker.

I have some troubles with the generating "DNSSEC" key,  it makes so long long time, almost 30 min, and still no key, should i wait more time ? 

Can i have a docker run exemple of the project ?

**Comment by JoshData** [comment]
Did you use the docker branch? It's not really finished yet. See #377, #112.
