### ISSUE TITLE
Trisquel support

### ISSUE THREAD

**Issue by Calinou** [mail-in-a-box/mailinabox#425]
If this project supports [Trisquel GNU/Linux](http://trisquel.info/), it would be nice to mention it in the documentation. The version 7 is based on Ubuntu 14.04, and is available for 32-bit and 64-bit. It is basically Ubuntu with the non-free components removed.

**Comment by JoshData** [comment]
If it's just a rebranded Ubuntu 14.04 then it should work fine(-ish). But I don't intend to actively support more than one distro (making it work correctly on Ubuntu 14.04 is difficult enough as it is).
