### ISSUE TITLE
TLSA entry for the websites

### ISSUE THREAD

**Issue by TabTwo** [mail-in-a-box/mailinabox#428]
How about adding a TLSA entry for every website?

**Comment by JoshData** [comment]
What would that do?

**Comment by dhpiggott** [comment]
Would it allow TLSA capable clients to detect if a MITM had occurred even if the MITMer had obtained a CA's key and created an otherwise valid cert for their proxying purposes?

**Comment by JoshData** [comment]
There are a lot of if's there!

**Comment by dhpiggott** [comment]
I didn't say I thought it would be advantageous to most use cases :)

Are there any cases where it could be problematic?

**Comment by JoshData** [comment]
No, for the same reason there are no actual cases where it would be useful. :)

**Comment by JoshData** [comment]
@TabTwo: If you have a use case that I'm missing let me know, otherwise I will close this issue.
