### ISSUE TITLE
Mailman

### ISSUE THREAD

**Issue by pemrouz** [mail-in-a-box/mailinabox#43]
I tried this project out today and everything worked like a charm. The only thing keeping me from switching over currently is the lack of ability to administer mailing lists. Would it be possible to consider adding installing/setting-up mailman (perhaps as an optional step?) onto the roadmap for this project? Or would that be outside of it's scope?

**Comment by PortableTech** [comment]
I would like to suggest we revisit this.  It is one thing I would find quite useful.  It would be nice if we had a central solution that integrates into the existing authentication database, but it is not imparitive  I do believe mailman 3.0.0 stable is out at this time.

Ref: https://launchpad.net/mailman/+milestone/3.0.0

And I have seen comments about past versions being easily interfaced mail-in-a-box.

Other than that, I am not opposed to any other option, but allowing mailing lists to be managed without the need to assign full admin privileges, and with options beyond a simple list of email addresses would be a nice feature improvement.

**Comment by nateisch** [comment]
:+1:

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope.

**Comment by alexgleason** [comment]
Why? This is critical for small organizations, most of which rely on Google Groups. Offering an easy way for these people to have their own mailing list will further Mail In A Box's goals of re-decentralizing the web.

Background: I am part of a grassroots activist group that needs mailing lists to communicate with our members and organizers. There are about 40+ chapters with the same needs. We were relying on a centralized mail server to do this until the server admin started abusing his power. We need to decentralize, and I'm tasked with installing a mail server and lists on about 40 servers. Surely there's a way to do this.

**Comment by anoma** [comment]
FWIW while thinking about it... every company I work with that uses Google mail rely heavily on google groups.

**Comment by JoshData** [comment]
A lot of things will further our goals. We can't do them all, and there are far more critical existing problems in this project that need to be addressed.

**Comment by almereyda** [comment]
@alexgleason Could you try getting in touch with me on another channel? At @ecobytes we are hosting infrastructure for activists and may be able to help you. If you want to self-host your infrastructure, it's still good to check out the other https://github.com/indiehosters/awesome-librehosters
