### ISSUE TITLE
nginx configs

### ISSUE THREAD

**Issue by ikarus23** [mail-in-a-box/mailinabox#432]
Hi,

I saw some lines like
```console
[...]
rewrite ^/admin$ /admin/;
location /admin/ {
[...]
```
in the `nginx` configs (e.g. [here](https://github.com/mail-in-a-box/mailinabox/issues#L4)).

You can simplify those lines to
```console
location /admin {
```
Notice that there is no `/` at the end of `/admin`. A location like this will work for `https://box.example.com/admin` and `https://box.example.com/admin/`.

**Comment by JoshData** [comment]
Try it and see if the admin pages still work. Maybe there was a reason I put it in. :)

**Comment by ikarus23** [comment]
Hehe, I see. After implementing the changes shown above, it is no longer possible to login into the admin interface.

Well, I guess we just leave it there...
