### ISSUE TITLE
Deleting subdomains does not work

### ISSUE THREAD

**Issue by h8h** [mail-in-a-box/mailinabox#434]
I've created a new subdomain via Mail -> Aliases
Alias
admin@subdomain.domain.tld
Forward To
admin@domain.tld
Miab wrote the new dns entries, web updates and at least the mail alias.

But how can I remove this subdomain? There is no trashbin icon near the admin@subdomain.domain.tld in Mail -> Aliases. I think the problem here is that every admin@ alias needs one existing mailbox user. But I've created the admin@ alias `manually` and there is no real mailbox user, which I can delete and miab then can delete the admin@ part.

Hint: I've created the subdomain in a very early state of miab and there was no fancy `Set Custom DNS Records` Webinterface, so thats why I've done it this way. Nowadays I think its better to use this interface and maybe we should prohibit people doing it `my way` :-).

**Comment by h8h** [comment]
GREAT! By adding a new subdomain, all old subdomains are now removeable, too! Thanks for that fast fix!

**Comment by JoshData** [comment]
It's bug-fixing Saturday! :) A related issue (with the same solution) had also been on my mind for a while.
