### ISSUE TITLE
"There is a problem with the SSL Certificate"

### ISSUE THREAD

**Issue by dquancey** [mail-in-a-box/mailinabox#443]
Hi there.

I've install MIAB without issue, but trying to install my Positive SSL from namecheap is proving troublesome.

Keeps coming up with the error in the subject title.

I'm using OVH if that makes any difference. I've followed steps here: https://github.com/mail-in-a-box/mailinabox/issues/245 with no luck.

Any suggestions welcome.
Thanks

**Comment by JoshData** [comment]
You'll need to look at `/var/log/syslog` to see if there are any further messages posted there when you try to install the certificate. OVH provides a busted Ubuntu image, however, so I am going to close the issue now on the assumption that it is OVH's fault. But if you find something please post again.
