### ISSUE TITLE
Replace fail2ban with Sshguard

### ISSUE THREAD

**Issue by m4rcs** [mail-in-a-box/mailinabox#446]
As fail2ban doesn't really support IPv6 it should be replaced with [Sshguard](http://www.sshguard.net/). It natively supports ssh and dovecot which are the services which are protected by fail2ban.

**Comment by JoshData** [comment]
Sounds good to me. Want to put together a pull request?

**Comment by nstanke** [comment]
Is Fail2ban even working at the moment? +1

**Comment by JoshData** [comment]
I'm not sure. If we switch, we will also need a test script to demonstrate that it is actually working.

**Comment by m4rcs** [comment]
I can try replacing it. The problem is that I don't have much experience with neither fail2ban nor Sshguard. So if somebody knows how to test it, feel free to tell me. I just know somthing like [wrk](https://github.com/wg/wrk) for HTTP testing. Maybe there is something for SSH and IMAP.

**Comment by nstanke** [comment]
Just noticed that the last SSHGuard release is over 4 years ago (http://freecode.com/projects/sshguard/releases) . Hence Fail2ban is still in active-development.

**Comment by JoshData** [comment]
There's active development here:

https://bitbucket.org/sshguard/sshguard/commits/all

Took me about 15 minutes to find that. Not sure why it's not clearly linked from the sshguard website. Maybe it's transitioned to a new maintainer.

**Comment by m4rcs** [comment]
Ubuntu has the current version in their [repo](http://packages.ubuntu.com/trusty/sshguard). So I think it is usable.

**Comment by nstanke** [comment]
My bad. Ubuntu Trusty provides version 1.5-5, if a more recent version is required we would've to compile it or add it to the ppa.

**Comment by m4rcs** [comment]
Well ok. Not THE current version. But for Ubuntu LTS one minor version behind the VCS is pretty current ;)

Lets take fail2ban. In the [Ubuntu repo](http://packages.ubuntu.com/trusty/fail2ban) the version is 0.8.11. The [VCS version](https://github.com/fail2ban/fail2ban/blob/master/ChangeLog) is 0.9.2. So I think we should not be concernd about that.

**Comment by JoshData** [comment]
In any case, since it looks like sshguard is maintained and it has support for IPv6, I'm still OK with switching.

**Comment by anoma** [comment]
I am not so sure this is as good idea at I initially thought. It certainly seems to be a better solution for SSH etc and a viable solution for IPv6 when compared to Fail2ban but from what I can see it is far less capable overall than Fail2ban.

Specifically you cannot add any matches and are limited to only what it supports by default and/or any you can submit upstream.

My vote would be to not change this over without much more thought.

**Comment by JoshData** [comment]
If it provides fewer customization options but works at least as well, that's actually a +1 to me.

**Comment by anoma** [comment]
It works "works at least as well" for some services and not at all for others.

Apart from IPv6 fail2ban does everything we need and can be trivially customized to watch for issues specific to MIAB.

Conversely sshguard can work with IPv6 but can only monitor a subset of services and cannot be customized for the MIAB "appliance like" services. 

To me this is a step back. Almost no one uses IPv6 but everyone benefits from monitoring all MIAB services, especially things like owncloud and other high level stuff.

**Comment by m4rcs** [comment]
Well that's a non-argument for me. Clearly IPv6 is on its move forward! In some parts of asia IPv6 has replaced IPv4 completly. In Germany a big provider has switched on IPv4 NAT for his costumers and delivers native IPv6. And even though IF nobody is using IPv6 why not switch it on for those who use it?

In my opinion if MiaB wants to support IPv6 for all its services it should switch to Sshguard as [fail2ban's IPv6](https://github.com/fail2ban/fail2ban/issues/39) might not come somewhat soon.

**Comment by anoma** [comment]
We are not at cross purposes merely that that "perhaps" no one product does everything we need.

At the very minimum we should define what we need to protect and compare that to available product options. e.g. IPv4, IPv6, SSH, dovecot, owncloud, ngnix etc

We also have to review on what IPv6 bans would be put in place for users because simply banning single IPv6 addresses is almost pointless but whole subnets extreme.

As I said originally "My vote would be to not change this over without much more thought."

**Comment by JoshData** [comment]
> banning single IPv6 addresses is almost pointless but whole subnets extreme

Interesting point.

Relatedly, it seems like `ufw` provides some rate limiting features for IPv4 too.

**Comment by m4rcs** [comment]
The question now basically is should MiaB now support fully support IPv6 or should we wait?

**Comment by JoshData** [comment]
I think that's right. If we don't have proper things in place for IPv6, we might recommend avoiding IPv6 networks for now. I'm not sure.

**Comment by benschumacher** [comment]
FWIW- I have a deployment that is IPv6 _ready_, though it also provides an IPv4 address. Not sure what would happen if I turned of the IPv4 DNS records... I'd expect that I'd start missing emails as other servers aren't prepared for that environment.

**Comment by m4rcs** [comment]
I talked to someone who is already running  a complete IPv6-ready Mailserver (with IPv4) and he said that 99.9% of the attacks are over IPv4. (Cloudflare)[http://de.slideshare.net/TomPaseka/hknog-ddos-attacks-in-ipv6-world sees it different but keep in mind that Cloudflare sees mainly dDoS attacks.

So I think we should see this as a chance to get a stable IPv6 setup without being attacked permanently. For the attacker that already use IPv6 I think it is suffient to ban single IPs.

**Comment by JoshData** [comment]
fail2ban is working well enough, and IPv6 may not be a fixable problem because addresses aren't scarce and so attackers can change more easily. So I'm closing this issue.
