### ISSUE TITLE
Mime Message Errors

### ISSUE THREAD

**Issue by PortableTech** [mail-in-a-box/mailinabox#447]
Greetings All,

It seems that Mime based emails will hang up RoundCube in the Mail-In-A-Box distribution due to two missing php PEAR packages that are required for RoundCube.

You can identify the error in your /var/log/roundcube/error log file as they will look like this

[21-Jun-2015 23:27:38 UTC] PHP Fatal error:  Class 'Mail_mimeDecode' not found in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_mime.php on line 71
[21-Jun-2015 23:27:42 UTC] PHP Fatal error:  Class 'Mail_mimeDecode' not found in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_mime.php on line 71
[21-Jun-2015 23:27:48 UTC] PHP Fatal error:  Class 'Mail_mimeDecode' not found in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_mime.php on line 71
[21-Jun-2015 23:27:52 UTC] PHP Fatal error:  Class 'Mail_mimeDecode' not found in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_mime.php on line 71

In the web interface this will cause the opening of a Mime message to hang indefinably on the "Loading" message until you select another message.  No other commands will work until you select a different message.

This can be corrected by running the following two commands

sudo pear install Mail_Mime
sudo pear install Mail_mimeDecode

No reboot was required and the fix was instant even for users currently logged in.  The need for these two packages are documented in the RoundCube install docs on line 20 and 21 at

https://github.com/roundcube/roundcubemail/blob/master/INSTALL

**Comment by JoshData** [comment]
Could you check if these packages are available by apt-get?

**Comment by PortableTech** [comment]
I don't think those pear packages can be installed directly from apt-get.  I know in the past I have used apt-get to install pear, but in looking at the installed list on my Ubuntu system that is not even an installed package, so it must be included in a larger one.  

In the past i have always just used the pear command to install those, it works much the same way as apt-get does.  

ubuntu@mail:/usr/share/php$ sudo pear install Mail_mimeDecode
downloading Mail_mimeDecode-1.5.5.tgz ...
Starting to download Mail_mimeDecode-1.5.5.tgz (11,554 bytes)
.....done: 11,554 bytes
install ok: channel://pear.php.net/Mail_mimeDecode-1.5.5
ubuntu@mail:/usr/share/php$ sudo pear install Mail_Mime
downloading Mail_Mime-1.8.9.tgz ...
Starting to download Mail_Mime-1.8.9.tgz (33,796 bytes)
.........done: 33,796 bytes
install ok: channel://pear.php.net/Mail_Mime-1.8.9

**Comment by JoshData** [comment]
I am trying to avoid dependencies that dont come from the package manager because then we're not checking for updates (e.g. security updates). `php-mail-mime` (which we are already installing) and `php-mail-mimedecode` (which we're not) might be the corresponding apt packages though. Could you try removing them via pear and then installing `php-mail-mimedecode` via apt?

**Comment by PortableTech** [comment]
That seems to do the trick.  Just add the php-mail-mimedecode package.

**Comment by PortableTech** [comment]
Well, that was interesting.....

I uninstalled the two previously installed pear packages and indeed the mime decode issue went away.   What I did not realize at that point in time is it completely broke sending mail in roundcube with the following error in the roundcube logs

PHP Fatal error:  Class 'Mail_mime' not found in /usr/local/lib/roundcubemail/program/steps/mail/sendmail.inc on line 363

I reinstalled the Mail_mime pear package and the issue resolved itself.

This does not mean that the php-mail-mimedecode package is not a fix, and when I went to reinstall both pear packages it told me that the mail_mimeDecode one was already installed.  It is possible that the pear uninstall took something away it should not have when I cleaned up.  

Just wanted you to now.  I would still include the additional php-mail-mimedecode package.

**Comment by JoshData** [comment]
Can you send me an email that demonstrates the problem? `jt@occams.info`

**Comment by PortableTech** [comment]
Did any of the emails i sent you, or the email addys you can email to generate them help you on this, or do you need me to do more?

**Comment by JoshData** [comment]
Haven't had the chance to look yet.

**Comment by skertchly** [comment]
I was having the same problem, installed php-mail-mimedecode and it solved it. I should note that I did not have to deal with pear at all.

**Comment by PortableTech** [comment]
Perfect, I suspected that would be the case, but d.id not have a clean install handy to test on.  Sounds like we have a simple solution to just include that single package
