### ISSUE TITLE
Update to v0.10 failed

### ISSUE THREAD

**Issue by agriffaut** [mail-in-a-box/mailinabox#449]
The checksum verification of owncloud-8.0.3.zip fail.. (see https://github.com/owncloud/core/issues/17121)
The update fail and the /usr/local/lib/owncloud directory doesn't exist anymore..
Please move the owncloud directory after checksum verification passed

**Comment by JoshData** [comment]
This isn't related to that upstream issue. (The checksum is stored in Mail-in-a-Box, not pulled from ownCloud.) Is it possible you just had a temporary network error?

Things can go wrong when an ownCloud update fails. You should back up `/tmp/owncloud-config.php` (where your old config went) and `/home/user-data/owncloud`, and then try the upgrade again. If that works, restore the config to `/usr/local/lib/owncloud/config/config.php` and put back the data directory.

**Comment by agriffaut** [comment]
Indeed, but the file downloaded from owncloud community site is not good (md5 nor sha1 passed)

**Comment by JoshData** [comment]
I just checked it by hand, but maybe there's some mirroring issue/delay.

**Comment by agriffaut** [comment]
https://download.owncloud.org/community/owncloud-8.0.3.zip is in fact v8.0.4 for now..

I think the install script should download & check the file before modifying anything..
If the check fails, the script exits and leaves a broken system.

**Comment by nstanke** [comment]
So this should be fixed by moving [L46](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/owncloud.sh#L46) to [L36](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/owncloud.sh#L36), so we call `wget_verify` before we `mv` OwnCloud.
