### ISSUE TITLE
install 0.10 owncloud checksum issue

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#453]
HI,

I was upgradeing from 0.10 and at then end it shows this. Can you kindly let us know what the cause is for this?

How do we check the version "0.10" in admin page?

thanks

installing ownCloud...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of https://download.owncloud.org/community/owncloud-8.0.3.zip did not match expected checksum.
Found:
625b1c561ea51426047a3e79eda51ca05e9f978a  /tmp/owncloud.zip

Expected:
3192f3d783f81247eaf2914df63afdd593def4e5  /tmp/owncloud.zip
peng@mx:/tmp$ ^C
peng@mx:/tmp$

**Comment by JoshData** [comment]
ownCloud messed up their downloads. We're waiting on the resolution of https://github.com/owncloud/core/issues/17121.

(Also see #449.)

**Comment by piecam** [comment]
HI Josh 
Thanks a lot

**Comment by JoshData** [comment]
I pushed version 0.11 of Mail-in-a-Box which updates to ownCloud 8.0.4. Please try that.

**Comment by piecam** [comment]
Hi Josh,
I just upgraded my system and things are working fine.

Thanks a lot.
