### ISSUE TITLE
openSMTPd

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#454]
Hi Dear Josh,

Would openSMTPd be a consideration for future versions? I heard it workes nicely with Dovecot as well.

I know there's a lot invested in postfix, but just throw this out, in case that you consider an idea worth going.

Thanks a lot for your great work.

**Comment by JoshData** [comment]
What advantage does it have?

**Comment by piecam** [comment]
https://www.opensmtpd.org/
People are talking about simplicity, and well thought design, as well as security. Anyway, I am not an expert and I just want to let you know. So that, you may find out more.

thanks

**Comment by piecam** [comment]
It's from OpenBSD project, a FYI

**Comment by piecam** [comment]
They also work on LibreSSL, a rewrite of openSSL, a fyi. Thanks

**Comment by piecam** [comment]
another tutorial FYI
https://wiki.archlinux.org/index.php/OpenSMTPD

**Comment by JoshData** [comment]
Postfix works just fine for us, and I doubt openSMTPD supports everything we're curring doing (e.g. greylisting w/ milters).
