### ISSUE TITLE
mailinabox in private home network, instead of cloud.

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#455]
HI Josh,

Again, this is a great work you have done. Working out of cloud is also great! However, I do not feel comfortable in running it into other's facility with my data. I managed to get it running in my home network. What I did is to fake a SMTPd server with Google DNS record with one of my private ip. 

I have been using it for almost one year now. Hope in your future version, you may allow it running in private personal home environment; don't let the script stop, but you can provide some advice of sending email out via third party email provider (such as, your "trusted" email account) instead.

I am fully aware of ISP banning outbound tcp/25 (Rogers, one of Canada's, blocked that last year). I am using one of my DNS provider's free email account (which I have more trust than Google/Yachoo,s) to forward email out through tcp/587 to their server, then out again. I have no problem receiving incoming email via TCP/25. 

Hope you can accomodate that in the future version.

A side note about ISP blocking tcp/25 with a reason of reducing "spam". This is crazy point. They may well be just deny all HTTP traffic as well, which is also a source of attack for denied service. Anyway, we work around it.

Thanks again.

Oh, If you don't mind, by the way, you may have this posted in your guide so that people who really like your software solution and really want to run in their home , can do so now, till you decide to accomodate in your officical version.

Once again, many thanks

**Comment by JoshData** [comment]
Hi. Thanks. I'm not necessarily opposed to supporting these kinds of use cases, but it's not something I plan to work on myself any time soon. So to continue discussion, you'll need to propose specific changes that would need to be made to Mail-in-a-Box to make residential hosting possible.

**Comment by piecam** [comment]
Here's some of my reference link and details I followed, hope it helps. As you may see it, it's quite an easy fix and get this working in a private home network relaying email out via a trusted/not trusted email account. However, I do understand your busy work. Hope this will be something for your quick reference, in case you have some bit time looking into this.

Many thanks again.


https://www.linode.com/docs/email/postfix/postfix-smtp-debian7

peng@mx:/tmp$ sudo cat /etc/postfix/sasl_password
[mailout.myfriendlyemail.com]:587 username:password

sudo postmap /etc/postfix/sasl_passwd

sudo chown root:root /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db
sudo chmod 0600 /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db

/etc/postfix/main.cf
relayhost = [mailout.myfriendlyemail.com]:587 

#from https://www.linode.com/docs/email/postfix/postfix-smtp-debian7
#enable send mail out through Teksavvy server
# enable SASL authentication 
smtp_sasl_auth_enable = yes
# disallow methods that allow anonymous authentication. 
smtp_sasl_security_options = noanonymous 
# where to find sasl_password
smtp_sasl_password_maps = hash:/etc/postfix/sasl_password
# Enable STARTTLS encryption 
smtp_use_tls = yes
#If your ISP is retarded and uses sender authentication, you can force all mails sent through postfix to originate from an address they deem "valid"
#http://jennyandlih.com/using-your-isps-smtp-server-postfix
#smtp_generic_maps = hash:/etc/postfix/generic

#I was having problems relaying emails to my ISPs mail relay. I had to add the following line to my /etc/postfix/main.cf
##smtp_sasl_mechanism_filter = plain, login
#smtp_sasl_tls_security_options = noanonymous
smtpd_tls_ciphers=medium
smtpd_tls_exclude_ciphers=aNULL

**Comment by piecam** [comment]
Here's some system status output, fyi, (masking out some my specific info) thanks a lot.

System Status Checks

System
✖	
SSH Login (ssh) is running but is not publicly accessible at x.x.x.x:22 (timed out).
✖	
Public DNS (nsd4) is not running (timed out; port 53).
✖	
Outgoing Mail (SMTP 587/postfix) is running but is not publicly accessible at x.x.x.x:587 (timed out).
✖	
IMAPS (dovecot) is running but is not publicly accessible at x.x.x.x:993 (timed out).
✖	
HTTP Web (nginx) is running but is not publicly accessible at x.x.x.x:80 (timed out).
✖	
The SSH server on this machine permits password-based login. A more secure way to log in is using a public key. Add your SSH public key to $HOME/.ssh/authorized_keys, check that you can log in without a password, set the option 'PasswordAuthentication no' in /etc/ssh/sshd_config, and then restart the openssh via 'sudo service ssh restart'.
✓	
System software is up to date.
✓	
System administrator address exists as a mail alias. [administrator@x.x.x.com ↦ peter.pan@x.com]
✓	
The disk has 431.6 GB space remaining.
Network
✓	
Outbound mail (SMTP port 25) is not blocked.
✓	
IP address is not blacklisted by zen.spamhaus.org.
x.x.com
?	
Nameserver glue records (ns1.xx.x.com and ns2.x.x.com) should be configured at your domain name registrar as having the IP address of this box (x.x.x.x). They currently report addresses of [Not Set]/[Not Set]. If you have set up External DNS, this may be OK.
✓	
Domain resolves to box's IP address. [mx.x.com ↦ x.x.x.x]
✖	
Your box's reverse DNS is currently xxx.cable.teksavvy.com, but it should be mx.xxx.com. Your ISP or cloud provider will have instructions on setting up reverse DNS for your box at x.x.x.x.
✓	
Hostmaster contact address exists as a mail alias. [hostmaster@mx.xxx.com ↦ administrator@mx.xxx.com]
✓	
Domain's email is directed to this domain. [mx.xxx.com ↦ 10 mx.xxxx.com]
✓	
Postmaster contact address exists as a mail alias. [postmaster@mx.xxxx.com ↦ administrator@mx.xxxx.com]
✓	
Domain is not blacklisted by dbl.spamhaus.org.
✖	
The SSL certificate for this domain is currently self-signed. You will get a security warning when you check or send email and when visiting this domain in a web browser (for webmail or static site hosting). Use the SSL Certificates page in this control panel to install a signed SSL certificate. You may choose to leave the self-signed certificate in place and confirm the security exception, but check that the certificate fingerprint matches the following:
show more
xxxx.com
?	
The nameservers set on this domain at your domain name registrar should be ns1.mx.xxxx.com; ns2.mx.xxxx.com. They are currently xxxxx.org; xxxx.net; rush.easydns.com. If you are using External DNS, this may be OK.
✓	
Domain's email is directed to this domain. [xxxx.com ↦ 10 mxxxxxx.com]
✓	
Domain is not blacklisted by dbl.spamhaus.org.
✓	
Domain resolves to this box's IP address. [xxxxx.com ↦ x.x.x.x]
?	
The SSL certificate for this domain is currently self-signed. Visitors to a website on this domain will get a security warning. If you are not serving a website on this domain, then it is safe to leave the self-signed certificate in place. Use the SSL Certificates page in this control panel to install a signed SSL certificate.
?	
This domain's DNSSEC DS record is not set. The DS record is optional. The DS record activates DNSSEC. To set a DS record, you must follow the instructions provided by your domain name registrar and provide to them this information:

**Comment by piecam** [comment]
I am only using mail/address book for now, so it's working fine for me. I may use other functions as well later and I will work around it over my router for that one later.

thanks again

**Comment by githubatf2f10** [comment]
Just leave a message here for people liking to have this wonderful solution in their own home...
1. Get a $5/month static IP from provider.
2. Ask them do a reverse domain setting pointing back to your MAIB.
3. Get service like easydns.com to set up Glue records to your public IP and box.xxxx.xxx mapping.
4. Use a OpenWRT or pfSense (opnSense 18.1.2 below seems having issue nat redirection working) firewall with proper portforwarding.
5. Use ubuntu 16.04 or what ever, with LXC of 14.04 working wonderfully...
Good luck!
