### ISSUE TITLE
tutorial video seems not finished.

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#456]
Hi Josh,

Your tutorial video is great ! However, it seems not finished and got cut at the end. I was just wondering whether it's intended or some techincal issue.

https://mailinabox.email/

thanks a lot

**Comment by JoshData** [comment]
Hmm. Well that's frustrating. Thanks I'll have a look.

**Comment by michaelshmitty** [comment]
Perhaps a youtube video length / upload limit hard cut off?

**Comment by bronson** [comment]
Ha, this is true.  I didn't even notice because it seems like all information was conveyed, but it stops in the middle of the word "log out".

**Comment by JoshData** [comment]
I've update the video. https://github.com/mail-in-a-box/mailinabox.email/commit/e51cec9309b1c8e4844e61215bcf0b677486c50a
