### ISSUE TITLE
jabberd

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#457]
HI Josh,

I am just wondering whether there's a plan/interest integrating a Jabber dameon function with your solution in the road ahead?

thanks

**Comment by JoshData** [comment]
No plans. It's highly unlikely I'd add it.

**Comment by piecam** [comment]
no worries. Just thought trying to get my kid off Gmail chat to my own Jabber server, so that he can completely be off google.

Thanks

**Comment by phenobarbital** [comment]
Using jappix4roundcube? I'm using ejabberd with bosh+jappix4roundcube with
LDAP authentication.

**Comment by piecam** [comment]
HI phenobarbital,

Can you elaborate a bit the steps you took? Was it integrated with MainInaBox, same machine? thanks in advance.
