### ISSUE TITLE
Feature Request: MLMMJ (Mailing List Management Made Joyful) for MIAB

### ISSUE THREAD

**Issue by h8h** [mail-in-a-box/mailinabox#461]
This is more a milestone than an issue, maybe its a good idea to have some simple mailing list onto miab for i.e. creating groups. 

[MLMMJ](http://mlmmj.org/) is very basic (BTW Everything is a file) and does not blow the system up as i.e. mailman would / could do. It only needs some config changes on postfixs master / main cfgs and thats it. 

MLMMJ has a lack for being fancy at the front, therefore it has no really webinterface ATM. The webinterface it ships is only a php script which sends an email from your email address to `yourlist+subscribe@domain.tld`. Thats its, simplicity is everything ;). 

There is a project [Mlmmj Simple Web Interface](https://github.com/tchapi/mlmmj-simple-web-interface) to get rid of this lack, but I don't test it yet. 

For me its fine to control everything via emails (hint: `yourlist+help@domain.tld` :-)).

I don't know how to achieve this milestone, should we integrate MLMMJ without webinterface first and then ship the webinterface or should we brought all-together into MIAB?!

Follow up [MIAB Discourse: Does Mail-in-a-Box list support mailing lists?](https://discourse.mailinabox.email/t/does-mail-in-a-box-list-support-mailing-lists/220/7?u=h8h)

See #43

**Comment by nikolay** [comment]
This actually looks like a good alternative.

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope.

**Comment by denji** [comment]
It is necessary to newsletter subscription on the inside corporate e-mail, I think it is very useful.
Usually have to raise the mailman, but this solution is more flexible.
