### ISSUE TITLE
Migrating cPanel e-mail accounts?

### ISSUE THREAD

**Issue by sikhlana** [mail-in-a-box/mailinabox#462]
Hello,
Just wanted to know if there's any way to migrate my emails from cPanel? Maybe create the accounts manually then copy the directories from cPanel and paste it somewhere?

Thanks! :smiley:

**Comment by Hoekynl** [comment]
Yes it is. I did it this way : Backup the mail folders from cPanel
Create the accounts on Mail in a box
Copy (only) the email from cPanel folders to Mail in a box folders

Example : 
User Harry's email is backed up. (you should have a "cur" folder which is the inbox)
Made Harry on Mail in a box
Copy the files in the folder "cur" to "/home/user-data/mail/mailboxes/yourdomain/harry/cur

**Comment by sikhlana** [comment]
Cool! :grin:
