### ISSUE TITLE
SNI Support

### ISSUE THREAD

**Issue by eberkund** [mail-in-a-box/mailinabox#464]
Are there any planes to support separate SSL certificates for each domain like cPanel does?

**Comment by sikhlana** [comment]
Yes! I would like to see that :+1:

**Comment by dhpiggott** [comment]
Unless I've misunderstood your question I believe this is already supported.

**Comment by Hoekynl** [comment]
This is supported.. I guess?
![knipsel](https://cloud.githubusercontent.com/assets/10139932/8403996/ecb82f64-1e49-11e5-9994-37a942452267.PNG)

**Comment by JoshData** [comment]
Right ^.

**Comment by eberkund** [comment]
That is for static website hosting, no?

If I have two domains both of them connect through the first domain using the first domain's SSL certificate.

<img width="636" alt="screen shot 2015-07-03 at 2 02 07 am" src="https://cloud.githubusercontent.com/assets/4555959/8493419/b786ff7e-2127-11e5-914c-30ffbcd2d20a.png">

What I am requesting is the ability to have separate SSL certificates for IMAP and SMTP, not just HTTPS.

**Comment by JoshData** [comment]
A few minutes of research seems to indicate this is not possible for SMTP because Postfix, the MTA we use, does not support it.
