### ISSUE TITLE
Support for e-mail piping.

### ISSUE THREAD

**Issue by sikhlana** [mail-in-a-box/mailinabox#465]
Hello,
Would it be possible to add support for piping incoming messages via aliases to an external program?

Thanks!

**Comment by JoshData** [comment]
No that's not something I intend to support. (I have found that it is more reliable to poll an account with IMAP than to pipe mail to a program, fwiw.)

**Comment by hadifarnoud** [comment]
could you point us to the right direction to do it ourselves? does a .forward work? if so, how should it be written?

**Comment by JoshData** [comment]
This isn't a forum for general mail server system administration help.
