### ISSUE TITLE
You must add a mail alias for postmaster@box.domain.com and direct email to you or another administrator.

### ISSUE THREAD

**Issue by RoldanLT** [mail-in-a-box/mailinabox#468]
I have this on system check mark as X.
I thought this is auto created on initial install?

**Comment by JoshData** [comment]
Thanks. Fix coming.

**Comment by JoshData** [comment]
Ooops I meant to post that in #470. I'm not sure what caused this problem. Works for me on a fresh box (with my #470 fix applied, so maybe that fixed it).

**Comment by RoldanLT** [comment]
Yeah, maybe related issue.
I just created this manually to fix it on system check.
