### ISSUE TITLE
'PasswordAuthentication no' in /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by RoldanLT** [mail-in-a-box/mailinabox#469]
I still seeing this on system check even if I already did it.
Already restart ssh and reboot the server.

Why is that?
Using Vultr VPS by the way.

**Comment by JoshData** [comment]
See https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L155.

**Comment by RoldanLT** [comment]
All fine now, Vultr added duplicate of this enabled at the very bottom of the config.
