### ISSUE TITLE
Version 11b new install has wrong default of Email Alias?

### ISSUE THREAD

**Issue by RoldanLT** [mail-in-a-box/mailinabox#470]
Is this intended, to have one alias:
administrator@box.domain.com > administrator@box.domain.com

It will redirect to itself.

On old version install, it is pointing to the email use on installation, like:
administrator@box.domain.com > me@box.domain.com

**Comment by JoshData** [comment]
Thanks, fixed!

**Comment by RoldanLT** [comment]
I just edited that alias and pointed to the email I use when installing MiaB.
Thanks!
