### ISSUE TITLE
High-Availability & Roadmap

### ISSUE THREAD

**Issue by crazybaud** [mail-in-a-box/mailinabox#472]
Hi,

Is someone working on High-Availability for a multiple server redundancy ? If no, do you have a Trello Roadmap to see how many people would be interested ?

Basic usage : 3 servers in 3 different countries.

Thanks for your great work :)

Antoine

**Comment by crazybaud** [comment]
Related post https://discourse.mailinabox.email/t/maintaining-a-local-dovecot-mirror/16

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope.
