### ISSUE TITLE
cipher

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#473]
Hi Josh,

You mentioned that some "export-grade" ciphers not used in MIAB and cipher key lenghth 112bits.

What are thoe "export-grade" ciphers?
If I want to enable/add those ciphers and change key lengths, can you provide a mini how-to?

We are in Canada, which is not restricted by this. In the mean time, these ciphers may be widely available from opensource channel, i.e. openbsd, mosailar, etc.

Many thanks

https://github.com/mail-in-a-box/mailinabox/blob/master/security.md
The services all follow these rules:

    SSL certificates are generated with 2048-bit RSA keys and SHA-256 fingerprints. The box provides a self-signed certificate by default. The setup guide explains how to verify the certificate fingerprint on first login. Users are encouraged to replace the certificate with a proper CA-signed one. (source)
    Only TLSv1, TLSv1.1 and TLSv1.2 are offered (the older SSL protocols are not offered).
    Export-grade ciphers, the anonymous DH/ECDH algorithms (aNULL), and clear-text ciphers (eNULL) are not offered.
    The minimum cipher key length offered is 112 bits. The maximum is 256 bits. Diffie-Hellman ciphers use a 2048-bit key for forward secrecy.

**Comment by JoshData** [comment]
"Export grade" refers to old 1990s-era ciphers that were restricted at the time. They have no practical value today.
