### ISSUE TITLE
"Invalid domain name." When Adding www.* SSL Cert

### ISSUE THREAD

**Issue by macinjosh** [mail-in-a-box/mailinabox#475]
I am trying to add my SSL cert for the www subdomain. I keep getting an error popup saying "Invalid domain name." I have verified that the CSR and cert are for my www subdomain.

**Comment by JoshData** [comment]
Please paste the certificate here. (It's safe to share the certificate.)

**Comment by macinjosh** [comment]
-----BEGIN CERTIFICATE-----
MIIEqzCCA5OgAwIBAgIDBWXBMA0GCSqGSIb3DQEBCwUAMEcxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMSAwHgYDVQQDExdSYXBpZFNTTCBTSEEy
NTYgQ0EgLSBHMzAeFw0xNTA2MjkyMTMwNDhaFw0xNjA3MDEwODI3MTVaMIGSMRMw
EQYDVQQLEwpHVDg3NTEzNDQwMTEwLwYDVQQLEyhTZWUgd3d3LnJhcGlkc3NsLmNv
bS9yZXNvdXJjZXMvY3BzIChjKTE1MS8wLQYDVQQLEyZEb21haW4gQ29udHJvbCBW
YWxpZGF0ZWQgLSBSYXBpZFNTTChSKTEXMBUGA1UEAxMOd3d3Lm1hY2luam8uc2gw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDUZjfGi3mx7igJd6eYSnde
ho9lDtRdmiGbahVPGdFvkUh4CUwtFe9dNzsWp9D8tKe10VjbxlKW7775zysxxRkW
OvLK6X1kr+EV477EuVgQIszQ7OB0DSwDw4mBAsQcbJuspfG3jc4+ZJEDVXLNhRJ3
cvMWDwyONFpd8z/z8RRs64dVjpez+OV7nHw/yb0yzj093SQdn6CM6XbrnTZii+eA
9UWVfvnMTdtqiaAzruUh8QVf7Zv3QIzHR/cdAKnxTc9If1x/7PMLcWCMpI3Ft5Yx
WYsrSaIboN0a3Vwl8kPhZxAT8PJMhsLWY+/avFlDA+VzLRUlMfYGKWrYWtqyBiux
AgMBAAGjggFSMIIBTjAfBgNVHSMEGDAWgBTDnPP800YINLvORn+gfFvz4gjLWTBX
BggrBgEFBQcBAQRLMEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly9ndi5zeW1jZC5jb20w
JgYIKwYBBQUHMAKGGmh0dHA6Ly9ndi5zeW1jYi5jb20vZ3YuY3J0MA4GA1UdDwEB
/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwJQYDVR0RBB4w
HIIOd3d3Lm1hY2luam8uc2iCCm1hY2luam8uc2gwKwYDVR0fBCQwIjAgoB6gHIYa
aHR0cDovL2d2LnN5bWNiLmNvbS9ndi5jcmwwDAYDVR0TAQH/BAIwADBBBgNVHSAE
OjA4MDYGBmeBDAECATAsMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5yYXBpZHNz
bC5jb20vbGVnYWwwDQYJKoZIhvcNAQELBQADggEBAI1ZceeJLPtnHerNU4otmfzE
GZSnzUbl1mXgHAKfuaYCd0WZ2vmCgjqM1cq5YtW05Cq6udmZMcMbjgJCoMOTPHXi
+chpmbWnyOJzUcMmpRDBNyW44TThLiE/serFqMa4VVuWG/yp0ByqGr27vSpWOXck
Dp3bwzIKsiDcN8YXLqd9K1Xa+Yc9T3Ks428eEbkKk+gNwYyAXWlBkXm6B7bD/deZ
QFIEvfR6+WgkxnDPzDXb5HTPzaT5zBHJPutFcbYxRF3j5XfyWk39bonYj0Uham6S
dTQ6F/ExGOrvMCVmYsXK4N8y7oRbhVltIO/lSm/kR3ddfGdIBQyXbw/qPqafFxc=
-----END CERTIFICATE-----

**Comment by JoshData** [comment]
Thanks. So it had nothing to do with the certificate after all, sorry. It was just impossible to install certs for the 'www' subdomains. It's fixed now. I'll post a new release in a few days.
