### ISSUE TITLE
SSL Certificate Installation fails

### ISSUE THREAD

**Issue by xolf** [mail-in-a-box/mailinabox#487]
I bought a signed SSL certificate at Comodo. I pasted the CSR into their box and I received their email with all the files included. So I tried to install them via mail-in-a-box. I copied all the content from the my_domain.crt into the little box. After hitting install, this little box showed up. 
![unbenannt](https://cloud.githubusercontent.com/assets/8250052/8530338/c554851c-2420-11e5-84f8-5c921be59414.PNG)
I tried several things, but removing all the line breaks was the solution for this problem. Perhaps you could write it into this error message. However I hit install again and this message were displayed. 
![unbenannt](https://cloud.githubusercontent.com/assets/8250052/8530403/14d03e6a-2421-11e5-88fc-8850895d3885.PNG)
No I don't have any idea what could be a solution for this problem. Someone wrote, that copying the .pem file into the SSL folder coul help. However, by the file /tmp/tmpfv1qxgjg.pem does not exists. I did not changed any lines of the certificate. 
It would be great, if you could help me.
Cheers...

**Comment by JoshData** [comment]
The second error is worse. You should not remove line breaks.

The first error is probably correct. You'll need to consult Comodo's documentation regarding intermediate certificates and paste them into the second box in the control panel.

**Comment by xolf** [comment]
Thank you, I needed another certificate from Comodo in the second textbox.
Now it's working. 
Have a nice day and go on creating awesomestuff like this!
