### ISSUE TITLE
Update from <0.11 to 0.12b causes sqlite3 error

### ISSUE THREAD

**Issue by mitchellurgero** [mail-in-a-box/mailinabox#488]
After running "sudo mailinabox" to upgrade to latest, I got the following error:

Running migration to Mail-in-a-Box #4...
Error: duplicate column name: privileges

Error running the migration script:

Command '['sqlite3', '/home/user-data/mail/users.sqlite', "ALTER TABLE users ADD privileges TEXT NOT NULL DEFAULT ''"]' returned non-zero exit status 1

Your system may be in an inconsistent state now. We're terribly sorry. A re-install from a backup might be the best way to continue.

**Comment by JoshData** [comment]
What version were you running before the upgrade?

**Comment by mitchellurgero** [comment]
I want to say version 0.09 I believe. or 0.10.

**Comment by JoshData** [comment]
What does your `/home/user-data/mailinabox.version` file say? If it says `3`, change it to `4` and try again. Let me know.

**Comment by mitchellurgero** [comment]
I already rebuilt the server so it is no big deal now, It was most likely caused by my server having too low a version to really upgrade properly. I now check daily for upgrades just incase.
