### ISSUE TITLE
Webmail change password corrupt password 

### ISSUE THREAD

**Issue by matteofabbri** [mail-in-a-box/mailinabox#489]
If you change password from the webmail instrument panel it change the password of the webmail to the new one but corrupt everyone other access.
After password change is not possible to log in via imap even with the old password

**Comment by hnk** [comment]
I don't completely understand your issue, but is it maybe related to #407 ?

Can you please provide some more information, maybe the exact error you receive, what version of MIAB you are using etc.

**Comment by matteofabbri** [comment]
It was reported by my users into 0.11, now it's look like resolved
