### ISSUE TITLE
Pango-WARNING during installation from munin

### ISSUE THREAD

**Issue by thejaswip** [mail-in-a-box/mailinabox#495]
I have frequently seen this error during the initial installation and also , after "reinstallation" by doing mailinabox command line again . 

(process:5723): Pango-WARNING **: error opening config file '/root/.config/pango/pangorc': Permission denied

**Comment by JoshData** [comment]
Yeah it's something coming from munin. It's not causing problems for me, but I don't know the cause.

**Comment by thejaswip** [comment]
I have reached it is being caused by
sudo -u munin munin-cron

**Comment by h8h** [comment]
Its something Xorg related. But there no Xorg on the server, so that should be O.K.

**Comment by JoshData** [comment]
I think fixed by 6c71abbb09313dde279968e86cdfa43a9675d69e.
