### ISSUE TITLE
Single secondary nameserver is listed twice in web UI and web API

### ISSUE THREAD

**Issue by dhpiggott** [mail-in-a-box/mailinabox#497]
Web UI:
![screenshot from 2015-07-19 19 51 46](https://cloud.githubusercontent.com/assets/6965859/8767294/f1cf0ae8-2e4f-11e5-87df-f2f6deef5af6.png)

Web API:
```
david@ash:~$ curl --user david@piggott.me.uk https://elm.dhpiggott.net/admin/dns/secondary-nameserver
Enter host password for user 'david@piggott.me.uk':
{
  "hostnames": [
    "ns6.gandi.net",
    "ns6.gandi.net"
  ]
}
```

Custom config content:
```
david@elm:~⟫ cat /home/user-data/dns/custom.yaml 
_secondary_nameserver: ns6.gandi.net
maple.dhpiggott.net:
  A: 139.162.219.218
  AAAA: 2a01:7e00::f03c:91ff:fe26:125a
...(truncated for brevity)...
```

**Comment by dhpiggott** [comment]
Updating the secondary nameserver (just removing the duplicate from the form and clicking update) appears to fix it. I review the custom YAML and find that the entry has been moved to the end of the file. If I manually edit the file moving it back to the start, the web UI and API report duplicates again.

**Comment by dhpiggott** [comment]
I see that the duplicate is added here: https://github.com/mail-in-a-box/mailinabox/blob/415f95b7921ced371b3592f582dbb9be883d5444/management/dns_update.py#L809

**Comment by dhpiggott** [comment]
I don't see why the duplicate only seems to appear when `_secondary_nameserver:` is the first line of `custom.yaml` though.

**Comment by dhpiggott** [comment]
Oops. It turns out the position of `_secondary_nameserver:` in `custom.yaml` doesn't make any difference - it was just that the web UI was continuing to show the value I'd submitted rather than round tripping the submitted value and then showing the re-parsed result. So that explains that bit.

**Comment by JoshData** [comment]
Got it, thanks!
