### ISSUE TITLE
Certificate with .crt instead of .csr

### ISSUE THREAD

**Issue by bkniffler** [mail-in-a-box/mailinabox#498]
Hey, 
I got a StartCom Class 2 certificate. I'm not able to generate a second one based on the .csr, as StartCom would only allow one certificate at a time for a certain domain.

Is there any possibility to use my .crt certificate for mail-in-a-box?

**Comment by JoshData** [comment]
Your questions is really whether you can use a private key file that you generated elsewhere (the control panel will let you install any certificate).

See https://discourse.mailinabox.email/t/allow-own-ssl-private-keys/183/6.
