### ISSUE TITLE
0.12c upgrade broken cffi-....so: failed to map segment from shared object: Operation not permitt

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#499]
Attempted to run 0.12c hoping it would fix the previous failed 0.11>0.12b sourceforge failure.

New error:

Installed /tmp/pip_build_root/cryptography/pycparser-2.14-py3.4.egg

running install

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/cryptography/setup.py", line 342, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 973, in run_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/tmp/pip_build_root/cryptography/setup.py", line 120, in finalize_options

    self.distribution.ext_modules = get_ext_modules()

  File "/tmp/pip_build_root/cryptography/setup.py", line 79, in get_ext_modules

    from cryptography.hazmat.bindings.commoncrypto.binding import (

  File "/tmp/pip_build_root/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 14, in <module>

    class Binding(object):

  File "/tmp/pip_build_root/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 37, in Binding

    "-framework", "Security", "-framework", "CoreFoundation"

  File "/tmp/pip_build_root/cryptography/src/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding

    extra_link_args=extra_link_args,

  File "/tmp/pip_build_root/cryptography/src/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi

    ffi = FFI()

  File "/tmp/pip_build_root/cryptography/cffi-1.1.2-py3.4-linux-x86_64.egg/cffi/api.py", line 56, in __init__

    import _cffi_backend as backend

ImportError: /tmp/pip_build_root/cryptography/cffi-1.1.2-py3.4-linux-x86_64.egg/_cffi_backend.cpython-34m.so: failed to map segment from shared object: Operation not permitt                                                       ed

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().r                                                       eplace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t6do9qgw-record/install-record.txt --single-version-externally-managed --compile failed with error code 1                                                        in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log
-----------------------------------------

**Comment by JoshData** [comment]
I have no idea. Some googling suggests that this could be due to trying to run an executable from /tmp. Is /tmp mounted with special options to prevent running binaries?

**Comment by anoma** [comment]
As far as I can remember with the exception of modifying fail2ban config files this box is stock Ubuntu built from scratch solely for MIAB.

The only unusual thing that has happened is the recent failed updates apart from that its vanilla.

But to answer directly /tmp is default, nothing special at all.

**Comment by anoma** [comment]
I am at a complete loss, there seems to be no easy fix and more curiously why is this only me. I am very careful with this box and treat it like an appliance to avoid this exact scenario.

Can I remove specific packages using pip and reinstall them? If so can you recommend any procedures as I know next to nothing about python package management

**Comment by JoshData** [comment]
Yeah that's what I would try. 

    pip3 uninstall cryptography cffi

**Comment by anoma** [comment]
hmmm

# pip3 uninstall cryptography 
Cannot uninstall requirement cryptography, not installed
Storing debug log for failure in /root/.pip/pip.log
# pip3 uninstall cffi
Cannot uninstall requirement cffi, not installed
Storing debug log for failure in /root/.pip/pip.log

very odd so I installed cffi and then cryptography manually.

The upgrader then bails out with

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

also very odd so I 

rm /var/lib/apt/lists/* -vf
apt-get update
apt-get upgrade

now when I run the upgrade it completes without error. I have no clue what gremlin caused all this but I will leave it open for a day or two for you to comment if you like then close.

**Comment by JoshData** [comment]
I wonder if cffi installs differently if it's installed before cryptography vs during the automatic install of cryptography's dependencies.

Anyway, I have no idea but I am glad it is working.
