### ISSUE TITLE
Owncloud calendar

### ISSUE THREAD

**Issue by matteofabbri** [mail-in-a-box/mailinabox#500]
When try to share an event the calendar fail why the error:
"For this site has been specified an invalid header Strict-Transport-Security"

Over those files:

sendmail.php
 idtype.php
share.php
 events.php

On Mozzilla Firefox and MIAB 0.12b

**Comment by JoshData** [comment]
Sorry what steps are you taking exactly? I have never shared an event.

**Comment by matteofabbri** [comment]
- Open your calendar
- Create an event
- Click on the event
- A modal appears
- Go on the modal -> Share

**Comment by JoshData** [comment]
The error occurs when you click Share?

**Comment by matteofabbri** [comment]
Errors occurs:
- When you add a user to share with him the event and click on "can modify"
- When you mark the "Send mail" option (2 errors occurs, invalid token and no mail sent)

**Comment by matteofabbri** [comment]
looks like part of them are fixed in the current version (the issue as open in 0.12b) and all those problem are fixed in owncloud current version, so probably an update to current ownlcoud will fix them all

**Comment by JoshData** [comment]
Okay, closing then.

**Comment by matteofabbri** [comment]
maybe you didn't understood, it look fixed in owncloud 8.2, the MIAB owncloud is 8.1
