### ISSUE TITLE
AutoDiscovery of domains pointing to the main one through MX

### ISSUE THREAD

**Issue by bkniffler** [mail-in-a-box/mailinabox#501]
Hey, 
With external DNS I'm using the suggested approach of having a single mail-hostname (box.example.com) and creating a MX record from other domains to the main domain (in example2.com -> MX box.example.com). But somehow, autodiscovery breaks with emails from the other domains, xxx@example2.com (tested on Thunderbird and Outlook). With xxx@example.com, everything works great!

Am I missing something?

**Comment by JoshData** [comment]
Autodiscovery uses HTTP. What are your A records?
