### ISSUE TITLE
owncloud/config.php not changed when server migrated.

### ISSUE THREAD

**Issue by dofl** [mail-in-a-box/mailinabox#503]
I've moved my mailinabox to a new server with help of the tutorial.
An error came up when it was handling owncloud, but running the setup again fixed it.

After checking everything, only one thing was not converted: /home/user-data/owncloud/config.php
The old domain was still in the config file.

**Comment by 5boro** [comment]
I've had the same issue, and running the script again fixed it.
But I didn't change domain, only host...
