### ISSUE TITLE
Secondary DNS server 

### ISSUE THREAD

**Issue by ponychicken** [mail-in-a-box/mailinabox#505]
Right now if you add a secondary dns server, the ip of that server is added as an `provide-xfr` entry. Some systems such as [BuddyDNS](https://www.buddyns.com/), query from more than a different than the nameserver itself IP so the AFXR transfer fails.

**Comment by ponychicken** [comment]
For example http://freedns.afraid.org/ uses 174.37.196.55 to query AFXR, but ns2.afraid.org resolves to 208.43.71.243

**Comment by JoshData** [comment]
This is already addressed in https://github.com/mail-in-a-box/mailinabox/pull/476, which will be included in the next update.
