### ISSUE TITLE
Make backups more configurable

### ISSUE THREAD

**Issue by ponychicken** [mail-in-a-box/mailinabox#506]
[Duply](http://duply.net/) is a wrapper script for duplicity that makes the managment of recurring backup jobs much easier. Settings are stored in profile file and stuff like managing after how many incremental backups to force a full backup, when to delete old backups etc, comes out of the box.

Using duply would reduce the code you need to maintain to make backups work and at the same time open the way to a more configurable backup system.

**Comment by ponychicken** [comment]
Would you accept a pull request which makes some aspects of the backups user configurable?

**Comment by JoshData** [comment]
Turning backups on/off (#228) and changing the backup destination URL to anything duplicity supports, yes.

**Comment by JoshData** [comment]
Fixed in c2e5f5cb2b80ecf516d9f967b2e52c62ff57842b.
