### ISSUE TITLE
Sender address rejected: not owned by user

### ISSUE THREAD

**Issue by Xoib** [mail-in-a-box/mailinabox#511]
Hello,

Apparently since the latest release (0.12c) I am unable to send e-mail from the administrator account because of the error below but it should as the e-mail from the sender match the login.

```
NOQUEUE: reject: RCPT from localhost.localdomain[127.0.0.1]: 553 5.7.1 <bob@domain.com>: Sender address rejected: not owned by user bob@domain.com; from=<bob@domain.com> to=<bob@gmail.com> proto=ESMTP helo=<ks.domain.com>
```

Is this happened to other also ?

**Comment by JoshData** [comment]
Do you have an alias on the same address?

**Comment by Xoib** [comment]
As a matter of fact, yes. I only use the smtp side (sending) for this account.

**Comment by JoshData** [comment]
Aliases are, for now, used to determine who is allowed to send on behalf of an address. You'll need to add the address in as another target of the alias (i.e. forwards to itself, in addition to elsewhere). (This will be fixed by #460 but I'm backlogged and haven't had a chance to get it in yet.)

**Comment by Futurama56** [comment]
+1

**Comment by Xoib** [comment]
Still getting this issue with 0.13b. I was thinking that it would be fixed by #460. #522 is different also.

**Comment by JoshData** [comment]
#460 added a new box to the admin. You have to now put your email address in the permitted senders list for the alias. Can/did you try that?

**Comment by Xoib** [comment]
@JoshData Ok it worked as expected. But I still find it kind of weird to have to do that. Should we close the issue ?

**Comment by JoshData** [comment]
Weird can be a new issue. :)

**Comment by benbyford** [comment]
having the same issue with a domain with two emails, how does one do "#460 added a new box to the admin. You have to now put your email address in the permitted senders list for the alias. Can/did you try that?"
