### ISSUE TITLE
z-push update 2.2.2 (Build 1981)

### ISSUE THREAD

**Issue by PortableTech** [mail-in-a-box/mailinabox#513]
I see on z-push.org that z-push has been update to 2.2.2 and looks like we are currently using 2.1.3.  This might be something we want to consider upgrading to.  

I will try and play around with it the next few days and see how stability, but would love to hear if anyone has already, or if there was a reason we were sticking with 2.1.3.

**Comment by nstanke** [comment]
Please keep in mind that MiaB uses Z-Push-contrib (https://github.com/fmbiete/Z-Push-contrib).

**Comment by PortableTech** [comment]
Turns out the issues that I thought were related to z-push were not.  Additionally, as stated, I was looking at the wrong package as well.  Resolving this issue.
