### ISSUE TITLE
timeout on php-fpm after reaching pm.max_children

### ISSUE THREAD

**Issue by pumelo** [mail-in-a-box/mailinabox#515]
I do experience timeouts such as
[error] 1179#0: *83208 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XX, server: XX, request: "GET /mail/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "XX"

this happens after approximately one day of server up and blocks all connections to owncloud and roundcube. 

searching the logs I found that this is happening after:
WARNING: [pool www] server reached pm.max_children setting (8), consider raising it

after
service php-fpm restart

everything is fine again....

so there seems to be an error here which might be related to this one here:
http://stackoverflow.com/questions/8677493/php-fpm-doesnt-write-to-error-log
and here:
http://serverfault.com/questions/394888/nginx-and-php-fpm-running-out-of-connections

I don't have any expirience with this so I do not know if just raising pm.max_children will solve the problem. Any ideas?

**Comment by JoshData** [comment]
We can probably raise `pm.max_children`. Maybe 8 per CPU. Something like that. But I haven't looked into this closer.

**Comment by JoshData** [comment]
Is anyone experiencing this problem still?

**Comment by pumelo** [comment]
Recently did a fresh install and did not face the above mentioned problem so this can be closed.
