### ISSUE TITLE
apache instead nginx

### ISSUE THREAD

**Issue by tdguchi** [mail-in-a-box/mailinabox#518]
its difficult to change script to use apache instead of nginx? i have a website running on my vps, and it is using lamp server, and i need a mail server. but if i install mailinabox, it removes apache, dropping down my site.

is there any way to adapt it?

thanks

**Comment by JoshData** [comment]
Hello. This project is not intended to be installed on a machine with anything else on it. (It would be impossible to support.) Sorry.

(Changing from nginx to apache would take many hours of work to make sure it works right.)

**Comment by tdguchi** [comment]
ok, and if i migrate my website to nginx is will work?

**Comment by JoshData** [comment]
I don't have anything to add besides my earlier answer. If you do something against the instructions, you are proceeding at your own peril.

**Comment by tdguchi** [comment]
so, you are from that group of developers who doesnt care about any compatibility with the rest of the world, Good job man! "only in this and this case, in other case, it breaks" bad philosofy

**Comment by JoshData** [comment]
I'm not sure what the rest of the world has to do with it. This is a project I maintain in my spare time. It's going to have limitations. If you want to make it better, start a discussion on the forum or submit a pull request or fork the project or start your own mail server project. It's not my responsibility to make you a mail server.
