### ISSUE TITLE
OpenDMARC segfault; auto restart can be useful ?

### ISSUE THREAD

**Issue by Xoib** [mail-in-a-box/mailinabox#521]
Hello,

I know it is probably a upstream problem with opendmarc but for our case can't we have a daemon that automatically restart a service if there is a failure like a segfault ?

```
Aug 18 11:17:26 box kernel: [12753277.786337] opendmarc[25760]: segfault at 8 ip 0000000000407684 sp 00007fe27eebfec0 error 4 in opendmarc[400000+10000]
```

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope. When a service breaks, reboot and probably add more ram...

**Comment by ZinkDifferent** [comment]
Based on other threads, adding more RAM didn't appear to make a difference - I just encountered the same issue, and it's a Segfault:

Jul 11 10:11:13 box kernel: [335793.719191] opendmarc[1411]: segfault at 8 ip 0000000000407684 sp 00007f7c4c72aec0 error 4 in opendmarc[400000+10000]

A simple 

sudo service opendmarc start got it back up and running again (no reboot necessary).
