### ISSUE TITLE
Add WoSign as a suggested free SSL provider

### ISSUE THREAD

**Issue by OmgImAlexis** [mail-in-a-box/mailinabox#524]
I found this guide on how to get free multi domain ssl certs and I thought I'd be worth adding as a suggested SSL provider along with StartSSL.

https://www.ohling.org/blog/2015/02/wosign-free-2y-ssl-certificate.html

**Comment by aspdye** [comment]
I think we should better integrate Lets Encrypt until it will be released ;)

**Comment by JoshData** [comment]
@OmgImAlexis If you would like to submit a pull request that adds a link to WoSign in the control panel, I'd merge that.

**Comment by JoshData** [comment]
fixed via #572
