### ISSUE TITLE
Invalid domain name when adding SSL cert for www.*

### ISSUE THREAD

**Issue by OmgImAlexis** [mail-in-a-box/mailinabox#525]
I've got a multi domain SSL cert for these domains and when I try to add it to ``www.wvvw.me`` it gives me "Invalid domain name".
Could this be because the root domain on this isn't ``www.wvvw.me``?

``wvvw.me, www.wvvw.me, ssl.wvvw.me, x.wvvw.me, api.wvvw.me, xtend.wvvw.me, me.wvvw.me, test.wvvw.me, tumblr.wvvw.me, home.wvvw.me``

**Comment by JoshData** [comment]
That message isn't really ever supposed to occur. Nothing to do with the certificate. I'm not sure....

**Comment by mitchellurgero** [comment]
Try adding www.www.me to the DNS settings in MIAB and try again?

**Comment by OmgImAlexis** [comment]
@mitchellurgero it's already in there. I didn't have this issue with the self signed or the free single domain ssl cert I was using, it only seems to be an issue with multi-domain ssl certs.

**Comment by JoshData** [comment]
Oh. If you have an `A` record on the domain, you may be confusing the box about whether it is supposed to serve that domain or not.

**Comment by OmgImAlexis** [comment]
@JoshData it had the self signed SSL cert showing on the dashboard though. I can't test it anymore as it's "working" now that I've got the domain pointed at another server.

**Comment by JoshData** [comment]
In that case I'll close the issue.
