### ISSUE TITLE
munin installation runs `rm` with possibly no operand

### ISSUE THREAD

**Issue by mitchellurgero** [mail-in-a-box/mailinabox#527]
I got the following error when upgrading from 12c to 13a:

Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
/bin/rm: missing operand
Try '/bin/rm --help' for more information.
updated DNS: example.com

Which seems to be a minor issue, MIAB seems to still be stable and usable as far as I can tell. Just wanted to let everyone know.

**Comment by MasterPCUK** [comment]
Just did same upgrade, didn't have these errors...
