### ISSUE TITLE
S3 Access Key and S3 Secret Access Key should be obfuscated at admin panel...

### ISSUE THREAD

**Issue by just4t** [mail-in-a-box/mailinabox#529]
Hi, Following @JoshData request here: https://discourse.mailinabox.email/t/v13-upgrade-issue-with-calendar/757/15 I'm happy adding my feat. request here to be applied over Miab v.0.13a at any time, as follows:

'Tested backups to Amazon S3 and worked very well... Just the S3 Access Key and S3 Secret Access Key should be 'encrypted' or at least obfuscated or 'asterisk' masked at the admin panel right after hiting its save button.'

**Comment by NurdTurd** [comment]
+1
