### ISSUE TITLE
Privatize welcome banner

### ISSUE THREAD

**Issue by phareous** [mail-in-a-box/mailinabox#530]
setup/mail-postfix.sh:	smtpd_banner="\$myhostname ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)" \

This seems a bit reckless to me. You're advertising to every hacker that the software is mail-in-a-box. That tells them we're running ubuntu, dovecot, postfix, etc. and they could easily visit the project to know what versions that might entail. All they have to do is connect to port 25 and they get a free head start in hacking into the system. Why make it easier for them?

**Comment by anoma** [comment]
Duplicate? https://github.com/mail-in-a-box/mailinabox/issues/440

**Comment by phareous** [comment]
Seems more like a related issue than the same thing since the other one is for the web GUI (although the smtp banner is mentioned in the discussion). I'm fine with it being closed if it would be addressed in that one.
