### ISSUE TITLE
 Image locations on external domain pointing to MiaB server

### ISSUE THREAD

**Issue by finid** [mail-in-a-box/mailinabox#532]
Set MiaB to serve DNS for websites hosted on other servers.

Problem now is most images on those sites are not being displayed, because the image locations are pointing to the MiaB server, instead of the server the website they belong to is running from.

An example:

The MiaB server is at https://box.miabserver.com and it's the DNS server for http://anotherdomain.com. Email for Anotherdomain works fine, but images for posts on the domain are showing locations like https://box.miabserver.com/uploads/image.png when it should be http://anotherdomain.com/uploads/image.png
Not sure how to fix this.

Any clues?

**Comment by JoshData** [comment]
No need to post in two places at once. Let's stick with your post at https://discourse.mailinabox.email/t/image-locations-on-other-domains-messed-up/791/1.
