### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by imknight** [mail-in-a-box/mailinabox#539]
Mail-in-a-Box Version:  v0.13a

Updating system packages...
Installing system packages...
Firewall is active and enabled on system startup
Creating initial SSL certificate and perfect forward secrecy Diffie-Hellman parameters...
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing ownCloud (contacts/calendar)...

FAILED: sudo -u www-data php /usr/local/lib/owncloud/console.php app:disable firstrunwizard
-----------------------------------------
ownCloud is not installed - only a limited number of commands are available

  [InvalidArgumentException]
  Command "app:disable" is not defined.
  Did you mean this?
      app:check-code

{"reqId":"E\/\/ldFfJ8Q0srnttF902","remoteAddr":"","app":"PHP","message":"touch(): Unable to create file \/usr\/local\/lib\/owncloud\/data\/owncloud.log because No such file or directory at \/usr\/local\/lib\/owncloud\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-08-29T16:32:18+00:00"}

**Comment by JoshData** [comment]
Was ownCloud previously working?

**Comment by imknight** [comment]
yup it was.

**Comment by JoshData** [comment]
I don't know what was happening here and it was a long time ago, so closing.

**Comment by jrnk** [comment]
Coincidentally I have the same message today when trying to upgrade to 0.16 from 0.14, but never used ownCloud functionality so not sure if it never worked/stopped working.

**Comment by jrnk** [comment]
Tried commenting out, https://github.com/mail-in-a-box/mailinabox/blob/master/setup/owncloud.sh#L189:L192 
no dice, since the 'upgrade' command was also missing. Running
```sudo -u www-data php /usr/local/lib/owncloud/occ list```
yielded 
```
ownCloud is not installed - only a limited number of commands are available
ownCloud version 8.1.1

Usage:
 [options] command [arguments]

Options:
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question

Available commands:
 check                 check dependencies of the server environment
 help                  Displays help for a command
 list                  Lists commands
 status                show some status information
app
 app:check-code        check code to be compliant
l10n
 l10n:createjs         Create javascript translation files for a given app
maintenance
 maintenance:install   install ownCloud
```
So I completely removed the `/usr/local/lib/owncloud` directory and re-ran setup, then it worked.
