### ISSUE TITLE
./mail.py user not working - HELP

### ISSUE THREAD

**Issue by Futurama56** [mail-in-a-box/mailinabox#541]
root@mail:~/mailinabox/tools# ./mail.py user
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

This might be related to the https://github.com/mail-in-a-box/mailinabox/issues/531

This is huge problem now - can't modify users!

**Comment by Futurama56** [comment]
root@mail:~/mailinabox# python tools/mail.py user
  File "tools/mail.py", line 20
    print("The management daemon refused access. The API key file may be out of sync. Try 'service mailinabox restart'.", file=sys.stderr)
                                                                                                                              ^
SyntaxError: invalid syntax

**Comment by JoshData** [comment]
Please run it as `./mail.py`. It's written for Python 3 so running it with `python` won't work.

**Comment by JoshData** [comment]
And, yeah, this looks like the same problem. Under the hood, it's exactly the same thing as looking at the users in the admin. So closing this issue.
