### ISSUE TITLE
Admin and owncloud 404s, mail works

### ISSUE THREAD

**Issue by lingo** [mail-in-a-box/mailinabox#545]
I changed the catch-all (my main user) to point to an external email address.
I rebooted the server as updates had been installed.
At some point in this my nginx config broke and I no longer have an admin panel or any owncloud endpoints.
Roundcube still works.

I've read through here:
https://discourse.mailinabox.email/t/admin-panel-not-reachable-nginx-down/244/20
and here: https://discourse.mailinabox.email/t/resolved-box-mydomain-com-admin-suddenly-404s/374

I haven't managed to fix the issue.  There seems to be no nginx config that refers to the owncloud endpoints.  /etc/nginx/conf.d/local.conf has only aliases for the mail.

I can see [here](https://github.com/mail-in-a-box/mailinabox/blob/master/conf/nginx-primaryonly.conf) that I seem to be missing some config but can't work out where to put it.

**Comment by k0nsl** [comment]
Isn't this the relevant configuration:
https://github.com/mail-in-a-box/mailinabox/blob/master/conf/nginx-primaryonly.conf

Faithfully,
-k0nsl

Den 9/4/2015 kl. 10:44 AM, skrev Luke Hudson:
>
> I changed the catch-all (my main user) to point to an external email
> address.
> I rebooted the server as updates had been installed.
> At some point in this my nginx config broke and I no longer have an
> admin panel or any owncloud endpoints.
> Roundcube still works.
>
> I've read through here:
> https://discourse.mailinabox.email/t/admin-panel-not-reachable-nginx-down/244/20
> and here:
> https://discourse.mailinabox.email/t/resolved-box-mydomain-com-admin-suddenly-404s/374
>
> I haven't managed to fix the issue. There seems to be no nginx config
> that refers to the owncloud endpoints. /etc/nginx/conf.d/local.conf
> has only aliases for the mail.
>
> I can see here
> <https://github.com/mail-in-a-box/mailinabox/blob/master/conf/nginx-primaryonly.conf>
> that I seem to be missing some config but can't work out where to put it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mail-in-a-box/mailinabox/issues/545>.
>

-- 
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution,
copying or the taking of any action in reliance on the information
herein is prohibited.

**Comment by lingo** [comment]
That is the configuration I found, yes, but I'm not sure where it should be or why it's vanished.
I eventually just included it from the `/etc/nginx/conf.d/local.conf` file and replaced the variables for STORAGE_ROOT

Seems to work so far!

**Comment by lingo** [comment]
Anyway, I fixed the issue, but can't work out what caused it, or how to fix it without manual hacking at the files (which is generally to be avoided with mailinabox).

**Comment by k0nsl** [comment]
@lingo: sorry, yeah, I didn't catch your initial link (which is why I deleted my reply, by the way).

**Comment by lingo** [comment]
@k0nsl thanks anyway!
