### ISSUE TITLE
initcaps / iptables module error

### ISSUE THREAD

**Issue by mboersma** [mail-in-a-box/mailinabox#546]
I see this on upgrades of Mail-in-a-Box:
```
root@box:~# curl -s https://mailinabox.email/bootstrap.sh | sudo bash
Primary Hostname: box.mydomain.org
Public IP Address: 1.2.3.4
Mail-in-a-Box Version:  v0.13b

Updating system packages...
Installing system packages...
ERROR: initcaps
[Errno 2] modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-32-generic/modules.dep.bin'
iptables v1.4.21: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
...

Installing Roundcube (webmail)...
Installing ownCloud (contacts/calendar)...
ownCloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
updated DNS: OpenDKIM configuration

-----------------------------------------------

Your Mail-in-a-Box is running.
...
```
The error repeats multiple times, but the install/upgrade script completes successfully. Any ideas?

**Comment by mboersma** [comment]
This box first began with Mail-in-a-Box v0.05 I think, and has been continuously upgraded in-place. I wonder if this is a hangover from earlier firewall rules?

**Comment by JoshData** [comment]
My first guess is that your VM provider is using a kernel with incomplete support for the firewall.

**Comment by mboersma** [comment]
It's Ubuntu 14.04 on DigitalOcean, which I thought was the preferred setup.

**Comment by JoshData** [comment]
Then yeah, it could be a holdover from some earlier/mis- configuration. Really not sure.

**Comment by mboersma** [comment]
Kernel 3.13.0-32-generic.

**Comment by mboersma** [comment]
Is iptables still used or has ufw replaced it? I'll do some investigation this weekend to see if it's just cruft. Thanks!

**Comment by JoshData** [comment]
We've always used ufw, but it uses iptables under the hood.

**Comment by h8h** [comment]
I've the same problems in lxc containers and this work for me:
(http://askubuntu.com/questions/664668/ufw-not-working-in-an-lxc-container)[ufw not working in an lxc container].

Since DO uses something similar to lxc this could work.

**Comment by JoshData** [comment]
Anything to be done here?
