### ISSUE TITLE
Ability to block outgoing mail to a specific address

### ISSUE THREAD

**Issue by karlingen** [mail-in-a-box/mailinabox#547]
I want to be able to block emails sent to `*@example.com` or any other bogus e-mail address.

Is this possible?

**Comment by dhpiggott** [comment]
This isn't currently possible, no. I have some questions though:

1. Why do you want to do this?
2. What is your definition of a bogus e-mail address?
3. How would you want the fact an outbound e-mail had been blocked to be reported to the sender?

**Comment by JumpLink** [comment]
@karlingen you can just create a filter in roundcube for this
