### ISSUE TITLE
Add regexp map support.

### ISSUE THREAD

**Issue by istr** [mail-in-a-box/mailinabox#555]
Currently I set up mail in a box for a specific project and I am generally happy, because it "works out of the box".
As a long-term qmail user (the inbound mx servers are still qmail based, I just don't trust postfix that much) one specific feature is missing, though:
qmail-style aliases (could be mimicked using postfix regexp maps) such that
```foo-*@domain.com``` could be reassigned to ```foo@domain.com```

**It would be great if [regexp style alias tables](http://www.postfix.org/regexp_table.5.html) could be added as a fourth alias option.**

Alternatively, mail-in-a box could try to use the official mx for a (local domain, unknown user) tuple to prevent a "NOQUEUE" rejection for ```foo-bar@domain.com``` that a qmail-based inbound mx may handle correctly / gracefully.

(and finally: imho the "perfect" solution requiring a major effort would be to replace postfix with a patched qmail as the MTA for mailinabox... ;-) )

**Comment by istr** [comment]
Ok, simple "qmail" forwarding seems to be supported, but only [using the default delimiter "+"](https://github.com/mail-in-a-box/mailinabox/issues/556)

**Comment by JoshData** [comment]
Unfortunately I am deeming this out-of-scope.
