### ISSUE TITLE
Change recipient_delimiter to '-'

### ISSUE THREAD

**Issue by istr** [mail-in-a-box/mailinabox#556]
It would be great to change the default recipient_delimiter to '-' to embrace more (former) qmail users.
Apart from that [there are more reasons to do so](http://www.stevejenkins.com/blog/2011/03/how-to-use-address-tagging-usertagexample-com-with-postfix/).
Somebody [already tried that without success](https://discourse.mailinabox.email/t/problem-with-postfix-recipient-delimiter/653) and I can confirm that it needs something more than changing the setting in ```main.cf```.
Anybody an idea, how to achieve that? 
Maybe [setting it in dovecot too](http://superuser.com/questions/662966/postfix-change-recipient-delimiter-with-virtual-mailboxes)?

**Comment by JoshData** [comment]
That would be a majorly backwards incompatible change, so there would have to be a much bigger reason to switch.

**Comment by istr** [comment]
Ok, point taken. :-)
Closing in favor of https://github.com/mail-in-a-box/mailinabox/issues/558
