### ISSUE TITLE
Make recipient_delimiter configurable from web UI.

### ISSUE THREAD

**Issue by istr** [mail-in-a-box/mailinabox#558]
It would be great to be able to configure the default recipient_delimiter to '-' to embrace more (former) qmail users.
Apart from that [there are more reasons to do so](http://www.stevejenkins.com/blog/2011/03/how-to-use-address-tagging-usertagexample-com-with-postfix/).
Somebody [already tried that without success](https://discourse.mailinabox.email/t/problem-with-postfix-recipient-delimiter/653) and I can confirm that it needs something more than changing the setting in ```main.cf```.
Anybody an idea, how to achieve that?
Maybe [setting it in dovecot too](http://superuser.com/questions/662966/postfix-change-recipient-delimiter-with-virtual-mailboxes)?

**Comment by JoshData** [comment]
A setting like this would cause all sorts of trouble if people start changing it after users are using it.

I'm not trying to be everything to everyone here. There are very few user configurable settings. Almost none. And I'm trying to keep it that way to keep the project simple. So I'm going to close this issue.

**Comment by istr** [comment]
Ok, point taken. Thanks for clarification.
