### ISSUE TITLE
Installing on Scaleway ARM Server hangs

### ISSUE THREAD

**Issue by rogerbraun** [mail-in-a-box/mailinabox#559]
I tried installing mail in a box on an Ubuntu 14.04 ARM server hosted at Scaleway. The last lines of the setup are:

```
Mail-in-a-Box Version:  v0.13b

Updating system packages...
Installing system packages...
```

After that, the server hangs. Are some of the packages not available on ARM?

**Comment by JoshData** [comment]
See https://discourse.mailinabox.email/t/armhf-builds-of-dovecot-lucene-and-postgrey/837.
