### ISSUE TITLE
+tag addresses no longer function

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#560]
Mail-in-a-Box Version:  v0.13b

I just noticed when setting up a new +tag address for a new shopping site that this feature no longer works.

I have tested the +tag address to both an alias and a real mail box, both do not work and the mail gets caught by the last resort catch-all.

**Comment by anoma** [comment]
If anyone has a clue where to start I can have a look at this. Problem is I currently dont even know where to begin.

**Comment by haraldkoch** [comment]
The variable that controls this is "recipient_delimiter" in postfix's main.cf file. It's off by default, and I don't see any reference to it in a quick search of the miab source...

**Comment by JoshData** [comment]
Pretty sure in Ubuntu it's `+` by default.

**Comment by JoshData** [comment]
@anoma Run `postconf | grep ^recipient_delimiter` to see what your setting is.

**Comment by anoma** [comment]
>postconf | grep ^recipient_delimiter
>recipient_delimiter = +

Just to confirm I have not intentionally made any changes to config files outwith the defaults.

**Comment by JoshData** [comment]
So that's correct. It may be that catch-alls have precedence over +tag addresses somehow.

**Comment by anoma** [comment]
I am not sure how to check the priority or internal routing of this. Certainly this must have changed in the back end as I am almost certain I have made no front end config changes at all related to accounts or forwarding in months.

Is this only broken for me?

**Comment by JoshData** [comment]
Seems working for me.

**Comment by anoma** [comment]
OK. Definitely broke here.

If i send a mail to a user on a domain with no catch all I get an error like:

>An error occurred while sending mail. The mail server responded:  
5.1.1 <test+realuser@fake.org>: Recipient address rejected: User unknown in virtual mailbox table.
 Please check the message recipient "test+realuser@fake.org" and try again.

If i send the same mail to a user on a domain with a catch all it ends up forwarding to the external catch all box.

In both cases if i remove the "test+" the mail is delivered to the real mailbox.

**Comment by JoshData** [comment]
You're backwards! It's `realuser+test`. :)

**Comment by anoma** [comment]
Just goes to prove 2 things:

1. I am a moron
2. If i had done a proper error report in the first instance we could have established #1 quicker.

I might do a PR that makes it harder to be this moronic by changing the highlighting or something in the mail-guide.html template.

Apologies

**Comment by JoshData** [comment]
No worries.
