### ISSUE TITLE
curl|sudo bash antipattern

### ISSUE THREAD

**Issue by allo-** [mail-in-a-box/mailinabox#566]
On your documentation page you write

```(bash)
curl -s https://mailinabox.email/bootstrap.sh | sudo bash
```

Which is a big antipattern for security, see for example http://blog.emillon.org/posts/2014-12-27-on-the-curl-sh-pattern.html

Beside this, even copy & paste from a website is a big security risk: http://thejh.net/misc/website-terminal-copy-paste

**Comment by JoshData** [comment]
Like most things in life, there is a trade-off involved in the different ways the software can be acquired.

For copying and pasting from the website... It's turtles all the way down. At some point the user has to find the instructions from somewhere. But at least the website will be in the Chrome HSTS preload list in Chrome's next update.

This is sort of a dup of #250, so I'm closing this. Feel free to open new issues for specific proposals for how to make things better.
