### ISSUE TITLE
How to use Owncloud file storage through mail-in-a-box?

### ISSUE THREAD

**Issue by brylie** [mail-in-a-box/mailinabox#569]
We would like to be able to use more of the OwnCloud features, such as file storage, through the mail-in-a-box server. How can we access/activate the OwnCloud portal?

**Comment by JoshData** [comment]
If it's not there, it's not something I support.

**Comment by brylie** [comment]
OK, just wondering if there might be a path for us to add that feature. Our webserver has quite a bit of filestorage, so it would be useful. Either way, thanks for your work and quick responses :smile:

**Comment by JoshData** [comment]
See #514. :|

**Comment by brylie** [comment]
Ah dang. Didn't realize the problems you experienced. Thanks for the clarification.
