### ISSUE TITLE
Backups days work as expectd since upgraded to v0.13b

### ISSUE THREAD

**Issue by kuking** [mail-in-a-box/mailinabox#570]
*Apologies if v0.13b is not a release; I have just seen, there are release notes up to v0.12. Nevertheless, this might come in the future as a bug.*

Since I upgraded to v0.13b, the backup rolling is not working as expected. I have configured ```How many days should backups be kept? = 10.``` In the admin console, I get the following output:

When 	|Type 	|Size 	| Deleted in...
------------|-------------|------------|-----------------
10/06/15 10:48:56 EDT	2 hours, 44 minutes ago	|increment	|2.4 MB	|approx. 30 days
10/05/15 10:45:32 EDT	1 day, 2 hours ago	|full	|103 MB	|approx. 30 days
(notice the "delete in..." column)

**Before this behavior, it was more erratical displaying bogus delete times**. I assumed it was down to the upgrade and decided to deleted the whole set of backups. Unfortunatelly, to some extend the problem still persists.

Thanks for the great project!

**Comment by JoshData** [comment]
The text of the option should really read "How many days should full backups that are no longer needed by an incremental backup chain be kept?". You only have an incremental backup chain there, so the option doesn't yet apply and the "deleted in" column is an approximate guess related to when it will take the next full backup, which will allow the current set of files to be eligible for deletion.

It's working as intended to automatically just do the right thing.

**Comment by kuking** [comment]
AH! Thanks! It will trigger a full backup when the incremental gets too big 'I guess'. Thanks for the quick reponse. I close the ticket for now. 
I did python a few years, I might be able to colaborate with something ... let me know if you want/assign me something. Thanks.

**Comment by JoshData** [comment]
Actually, reopening because we should explain this in the control panel.

If you want to submit a pull request to make the control panel explain what's going on, that'd be great!

**Comment by kuking** [comment]
Will do.
