### ISSUE TITLE
z-push fails to capture cc'd people

### ISSUE THREAD

**Issue by amateurbutinterested** [mail-in-a-box/mailinabox#576]
Hi.

I have run a large number of tests but have not yet checked the logs. Given that I have been able to repeat the issue consistently and I thought to create the issue without going through the logs. If you would prefer to see the logs, please just tell me what to send.

When I connect via IMAP from a desktop client, iPhone, or the webmail client, I can send email with people CC'd and BCC'd without a problem. However, if my phone is configured to treat the server as an exchange server -- using z-push -- then the server never sends the email to the people who have been cc'd. 

It looks like an issue with the way z-push is working with the SMTP server.

(It too forever to even identify this problem as I send most mail from my desktop and it is never surprising that you don't get responses from people who are cc'd for those emails sent from my phone)

**Comment by nstanke** [comment]
Maybe we should update Z-Push-contrib. See https://github.com/fmbiete/Z-Push-contrib/issues/103

**Comment by JoshData** [comment]
@nstanke Yeah makes sense. Do you use z-push? I don't so it's cumbersome for me to test that updates don't totally break.

**Comment by nstanke** [comment]
Since I had so many problems with Z-Push I do not use it anymore, but maybe it's better now so I'll give it a try.

**Comment by amateurbutinterested** [comment]
I have been using it on iOS. It has worked fine until I found out that the CC wasn't working. I configured the account to use IMAP when I found the bug. I still use z-push to synchronize contacts and calendars which has worked perfectly.

**Comment by yodax** [comment]
I use z-push and forked the repo and changed the version of z-push used. There are some config changes necessary to be able to authenticate to mailinabox. Nothing major. It is working on my iOS 9.1 device. (I only use mail atm, no calendar or contacts) Will test this for a couple of days. And try contacts and calendars as well. 

What I did notice is that messages do end up in the Sent folder now. Als CC'ing works.
