### ISSUE TITLE
Invitations are not sent to Email recipients for events over CalDAV

### ISSUE THREAD

**Issue by flasheater** [mail-in-a-box/mailinabox#585]
Tested on Android using DAVDroid.

When creating an event and adding email recipients to be notified, those invitations never get sent.

**Comment by nstanke** [comment]
AFAIK OwnCloud doesn't support calendar invitations.

**Comment by aspdye** [comment]
I think this is not an Problem with Mailinabox ;) 
Maybe you should create an issue at the GitHub Repository owncloud\calendar ;) 

I Hope some of this CalDAV and Calendar Problems in General are solved with the calendar and contatcs replacement of @joshdata soon ;) 

But the ownClouders are also working at cool stuff (calendar-rework and Mail) ;) I Hope that - for the Future - Mailinabox and ownCloud Could Build a Great Team 😉

**Comment by JoshData** [comment]
Yeah, not our problem, I don't think.
