### ISSUE TITLE
Owncloud email configuration

### ISSUE THREAD

**Issue by flasheater** [mail-in-a-box/mailinabox#586]
This issue might be obsoleted by #514.

Owncloud is configured to use sendmail and the domain of the box ( "box.example.com" ). As such, emails get sent by "root@box.example.com".

I would have expected to see the primary domain (" example.com") set and emails sent via the admin account "admin@example.com".

**Comment by JoshData** [comment]
I'm not sure how you have the box sending any emails. It doesn't email me.

The box's primary hostname is _box.example.com_. That's the only domain that the box knows definitely is valid. So the primary administrator address is _administrator@box.occams.info_.

I'm committing a fix that (just) corrects the address part before the @-sign.

**Comment by flasheater** [comment]
@JoshData Thx for explaining. I seem to have misunderstood what "primary domain" means.

I unlocked the owncloud admin settings and used the "Send test mail" feature to simulate what it would look like if the calendar app would send out invitations. See #585 .

Btw, the "Status Checks Change Notice" mails indeed use "administrator@box.example.com" as sender.
