### ISSUE TITLE
Z-push on iPhone Multiple Accounts causes Errors

### ISSUE THREAD

**Issue by Futurama56** [mail-in-a-box/mailinabox#588]
Try adding more than 1 "Exchange" account to an iOS device, and Z-Push starts to freak out / lose connections - and not show the inbox. 

Is this expected behavior?  Can Z-push only handle 1 box per device?  

It seems only 1 box will work when multiple are added.  

On the device I get "The connection to the server failed" and see in logs...

Full device resync requested
06/11/2015 21:08:34 [15180] [WARN] [andrew@] Not possible to determine class of request. Request did not contain class and apparently there is an issue with the HierarchyCache.
06/11/2015 21:08:34 [13784] [INFO] [andrew@] StateNotFoundException: No hierarchy UUID linked to device. Requesting folder resync. - code: 0 - file: /usr/local/lib/z-push/lib/core/statemanager.php:489
06/11/2015 21:08:35 [14607] [INFO] [andrew@] Version='SVN-trunk-r1981' method='POST' from='69.69.69.69' cmd='FolderSync' getUser='andrew@' devId='6969696969696969696' devType='iPhone'
06/11/2015 21:08:35 [14780] [INFO] [andrew@] StatusException: SyncCollections->CheckForChanges(): HierarchySync required. - code: 4 - file: /usr/local/lib/z-push/lib/core/synccollections.php:477
06/11/2015 21:08:35 [14607] [INFO] [andrew@] StateNotFoundException: FileStateMachine->GetState(): Could not locate state '/var/lib/z-push/k/5/69696969696969696-bs-1446765000' - code: 0 - file: /usr/local/lib/z-push/lib/default/filestatemachine.php:138
06/11/2015 21:08:35 [14607] [WARN] [andrew@] BackendIMAP->getFolderIdFromImapId('INBOX') = not initialized!

Any ideas?

**Comment by yodax** [comment]
Can you run this on the machine:

z-push-admin -a list

And check if you actually have more than one connection. I could set up two connections to the box, with the same email. Never tried it with two different emails thought. If iOS generates a different device id it might work. 

Connecting from both an iPhone and an iPad using exchange for the same account works.

**Comment by Futurama56** [comment]
I am using different emails to the same box - see update logs!

**Comment by Futurama56** [comment]
@yodax - yes I see many connections and for my device it lists both addresses 

696969696969 (deviceid) = andrew@x.com, andrew@xy.com 

Is what I am seeing -

**Comment by yodax** [comment]
Seems to be correctly configured. It might be a know issue: https://github.com/fmbiete/Z-Push-contrib/issues/97

This is the library mail in a box uses. 

Your log says it can't find states, you could as a Hail Mary try: z-push-admin -a fixstates

If that doesn't work; use the tool to force a resync

**Comment by yodax** [comment]
Yesterday my wives phone was behaving weirdly as well. Same setup as mine, both an iPad and iPhone using exchange to connect to the box. But hers was giving some error messages that it could retrieve email. 

Running z-push-admin -a list -u a@email showed that there was a loop. Forcing a fixstates and resync solved the problem after a while. According to fmbiete it takes a while for z-push to figure out the problem with the offending message (usually an encoding issue).

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
