### ISSUE TITLE
Status Page Timeout

### ISSUE THREAD

**Issue by biophonc** [mail-in-a-box/mailinabox#591]
Since `v0.14` the Status page does not load because of a 504 Gateway Time-out. 
The `management/status_checks.py` does work but takes to long for the server. 

When run from terminal, only the "Network" checks (DNS) are taking long (up to 1:30 min).
This is due to a 2nd NS setting for one Domain, reporting: "It resolved this domain as [timeout]. It should be 0.1.2.3". 
Just right before the update from `v0.13.b` there was no such error and the 2nd NS seemed to be fine.

If you need further info, please let me know.

**Comment by JoshData** [comment]
Hi, thanks.

That check in the status checks is new with this version. Your secondary nameserver isn't responding, it seems. I'll commit a fix so that the status checks don't wait so long.
