### ISSUE TITLE
Roundcube reply-to address not set correctly

### ISSUE THREAD

**Issue by zoof** [mail-in-a-box/mailinabox#595]
With my prior experience with Roundcube, the reply-to address would be set to the sending alias's address.  I've just noticed that when I receive an email sent via my MiaB Roundcube installation, when I reply using Thunderbird, the "To:" address is blank.  I think this is a Roundcube configuration issue as mail from the MiaB installation using other email clients work as expected.

**Comment by JoshData** [comment]
Has anyone else encountered this?

**Comment by stan3** [comment]
Can't reproduce this - just tried emailing a non MiaB account from MiaB's Roundcube and then replying in Thunderbird.  The To field is populated as expected.

**Comment by JoshData** [comment]
Thanks. Closing since this is a very old one.
