### ISSUE TITLE
pick up remote email and feed to postfix 

### ISSUE THREAD

**Issue by piecam** [mail-in-a-box/mailinabox#600]
HI,

I understand to use postfix "remote" server/password configurations to send email out via one of my trusted DNS provider with user/pass provided by them. This could be used avoid sending email from home IP being blocked by ISP or your cloud IP being blocked for sending email.

I'd like to also collect email remotely from my trusted DNS provider, who can help set up an account to receive email for me and for me to access either through a webportal or a client. I am thinking about using "fetchmail" or "getmail".

Can we use this "fetchmail'/"getmail" to get email and feed it back locally to postfix on MIAB? So, to MIAB, it makes no different than receiving email directly from another email server with SMTP.
MIAB will take it from there.

I am thinking that, this might be useful in situation that I don't want my IP being public or targeted; I can just retrieve my mail from my provider's mailbox, even through VPN service.

Please kindly advise how.

Thanks a lot.
peng

**Comment by JoshData** [comment]
> So, to MIAB, it makes no different than receiving email directly from another email server with SMTP.

If that's so, then of course.

That's how fetchmail is supposed to work, but I haven't used it much.
