### ISSUE TITLE
Secondary MX Record

### ISSUE THREAD

**Issue by PortableTech** [mail-in-a-box/mailinabox#603]
I am attempting to create a secondary MX record for my primary domain.  Yes, I am aware this seems an odd thing to do, but there is a legit reason for it and what I need in the end is simple.

I attempt to create a new record such as

domain.com    MX     20 mail2.domain.com

Ideally, this should not change the pre-existing MX record which is at value 10 for the server itself, but if it were to then I can certainly enter both a 10 and 20 record to be specific.  But when I attempt to set the record I get the message

Something isn't right.

and the record is then added to the Custom DNS page.  It is not however added to the zone files.  Removing the record results in the same message. I am guessing this is not ideal behavior.

**Comment by dhpiggott** [comment]
Can you explain your reason for wanting to create a secondary MX record?

**Comment by PortableTech** [comment]
Sure,

It all stems from my arch-nemesis AOL.  About 15% of all email sent from AOL to my domain is returned to the sender with the following error (email, domain, and ip changed):

<user@domain.com>: connect to
    mail.domain.com[1.2.3.4]:25: Connection timed out

Now when this happens there is zero record of this connection ever reaching my firewalls, or email server.  From my perspective it never took place.  Additionally, AOL considers this a final delivery failure about 40 minutes after the AOL user sends the message and apparently never tries again.  A search on Google shows that I am not alone in this either.  In contacting AOL, once I can convince them it is really their problem, they do something (they will not tell me what) and it works perfect for about 2 weeks and then it starts again.  This obviously causes a lot of problems and convincing all the AOL users that this is not my problem is almost impossible.

It should also be noted that AOL is the only domain I have this issue with.  Also, all my email is delivered to their users just fine.

So, I decided to try a little test, I setup a second server on a completely different provider and used netcat to forward ports 25 and 465 from that server to my MiaB server.  This way I have a second entry point into the server that can be advertised as an MX record in hope that this might cause AOL to try and deliver this message through more than one MX, all the while it is only one server so standard rules apply for filtering and spam control.  

To add a little more, I am quite certain this is not on my side, though am happy to check anything extra anyone can think of.  I have gone so far as to whitelist the whole AOL ip range that AOL sent me, and the IPs in the rejection emails are in those ranges.  The firewall logs never show it being caught .  My primary server is on Amazon AWS, and the secondary "forwarding" server is on Azure.  

And yes, I know this all sounds a little convoluted, but it seems a good test to see how AOL reacts since working with them is almost impossible.

**Comment by Neopallium** [comment]
Pull request #763 fixes that error message.

**Comment by JoshData** [comment]
Closing, fixed by the PR above.
