### ISSUE TITLE
Missing default abuse mail alias

### ISSUE THREAD

**Issue by ariejan** [mail-in-a-box/mailinabox#604]
I just checked my setup with Pingability and it reports that mail is not accepted for the abuse@fqdn.com email address. 

Would it be possible to add this as a default alias (just like the postmater and administrator aliases)?

```
The mail server rejected the email address 'abuse@devroom.io' (550 5.1.1 <abuse@xxxxxxxx.io>: Recipient address rejected: User unknown in virtual mailbox table). It should have accepted the address.
```

If you can point me in the direction in the source where this happens, I'd be happy to create a pull request for this.

**Comment by dhpiggott** [comment]
Ah, nice find -- I would be happy to see a PR adding this as a default.

The place to start is https://github.com/mail-in-a-box/mailinabox/blob/v0.14/management/mailconfig.py#L523 and https://github.com/mail-in-a-box/mailinabox/blob/v0.14/management/mailconfig.py#L533, but you'll also need to search for other instances of "postmaster@" in mailconfig.py to find and update the other code regions that relate to default aliases (just lines 575 and 80, I think).

This is perhaps a separate discussion, but your observation prompted me to search to see if there are other established conventions. I found https://www.ietf.org/rfc/rfc2142.txt. We might want to add e.g. security@ as a default too.

**Comment by JoshData** [comment]
I'd actually like to see more recent evidence that this is still a convention. Under what circumstances would someone email the abuse@ address but not postmaster@, for instance? Since neither are publicized, will a sender assume abuse@ exists and try it first and not try postmaster@?

**Comment by ariejan** [comment]
@JoshData from what I know some ISPs or systems will mail _both_ abuse@ and postmaster@. If nothing else, this won't bounce mails to abuse@ and show the world you care.

From what I [read](https://www.abuse.net/users.phtml) both postmaster@ and abuse@ are viable options for reporting spam and the like.

I'm not sure about adding security@ though.

**Comment by dhpiggott** [comment]
I don't know about evidence of abuse@ being presumed to exist, but I myself used security@ once. I discovered a security issue in my bank's mobile app, and as their website didn't have anything about how to report such issues, I sent an email to security@theirdomain -- knowing that it is a reasonably well known convention.

Unfortunately my email to security@theirdomain went into a blackhole. No bounce, just no acknowledgement whatsover. Eventually I ended up phoning them. They responded very well once I did that. But the combination of security@ not going anywhere *and* it not bouncing my email delayed things by a few days (it wasn't such a terrible flaw that I felt it necessary to phone the same day).

**Comment by ariejan** [comment]
@dhpiggott IMHO that would be a good reason to add security@ out of the box. Also, I don't think it can hurt to add it.

**Comment by bronson** [comment]
Some ISPs require you to have an abuse@ address that they can use if you're hosting email on their servers.  This one seems like a no-brainer to me.

security@ seems like it should have the same treatment as hostmaster@ and webmaster@...  Sure, set them up if you want, and try to prevent accidental misconfiguration.

**Comment by JoshData** [comment]
> Some ISPs require you to have an abuse@ address

Example?

**Comment by bronson** [comment]
I had an ISP that required that but right now I can't figure out who it was...

Here's one that I found by googling: http://www.meyercomputer4.com/meyer-computer-policies.php

> All Meyer Computer, Inc. customers sending commercial or bulk email must have a working abuse@theirdomain address from EVERY domain associated with the email campaign. Additionally, the abuse@ address must be prominently posted on the front page of the associated web site. Customers must regularly answer any messages sent to the abuse@ address.

**Comment by JoshData** [comment]
An example from an ISP that Mail-in-a-Box users are likely to be using?

**Comment by bronson** [comment]
http://www.servercentral.com/legal-information/aup

**Comment by bronson** [comment]
That's also a bit of a stretch since it looks like they're only managed but I've got to stop reading TOSs now, my eyes are tired.  Maybe it's rare but I've been subjected to it.  :)

**Comment by JoshData** [comment]
If it's rare, we can leave this up to the box's owner to worry about.

**Comment by bronson** [comment]
It's less rare than `hostmaster`, that's for sure.  Treat them similarly?

**Comment by anoma** [comment]
This for me again falls into the camp of "pass more tests = more likely not to be blacklisted or treated as spam".

RFC 2142  lists abuse@ and others and since there is almost no cost for us to be more compliant I see no real argument yet not to be?

**Comment by dhpiggott** [comment]
It's not clear to me either -- what is the reason we shouldn't add abuse@ and security@?

**Comment by JoshData** [comment]
I want to see an evidence-based reason to add it. That adding abuse@ will lead to less blacklisting is just conjecture. I don't think I've ever had an abuse@ email address on any of my domains.

**Comment by anoma** [comment]
I am not sure evidence would ever be realistically possible as most/all? of the big players keep their scoring mechanisms secret e.g. Google, Outlook etc.

However I do not think it is beyond the realm of possibility to suggest that RFC compliance would be component of scoring (although to be fair we would need to really read the relevant RFCs to see what changes are needed).

I am going to stop posting on this subject now because I just dont understand why this is a debate at all. I see no real downsides and regardless of evidence, RFC compliance is enough justification in itself.

**Comment by ariejan** [comment]
I have to agree with @anoma, there's little to no penalty in adding these aliases. 

@JoshData I don't think there is one authoritative organization that is going to say abuse@ is required. We _do_ have the RFC and and a lot of internet data to suggest postmaster@ and abuse@ are required to be read by a human.

Let me show what convinces me to add abuse@ and security@ (and possibly others, after seeing 3.):

 1. RFC 2142 says so.
 2. There's lots of internet data that suggests having at least postmaster@ and abuse@ is highly recommended. [1](http://www.thewhir.com/blog/comply-comply-keep-your-mail-servers-off-blacklists-avoid-being-flagged-as-spam) [2](https://discussions.apple.com/thread/4613364?start=0&tstart=0)  (just pasting two examples)
 3. The default `/etc/aliases` from Debian does include abuse@, security@ and all other aliases from RFC 2142. See https://gist.github.com/ariejan/afffa93671d011afe34b
 4. The Postfix manual for 'standard configuration' suggests adding abuse@ as well. [ref](http://www.postfix.org/STANDARD_CONFIGURATION_README.html)
 5. What are the implications of bouncing abuse@ and security@ addresses? Best case it looks bad on the user (who will look to mail-in-a-box). Worst case it gets your domain/server/ip blacklisted or blocked by an ISP. 

I'm all for adding these. Changes are already ready for review in PR #605.

**Comment by dhpiggott** [comment]
I'm with @anoma and @ariejan on this -- I see only upsides and no downsides.

It might not be a large sample, but surely the thing with my bank and the security issue I had difficultly reporting to them counts as *acec*data? If by adding security@ as a default alias we speed up the process of even a single vulnerability being reported to a MIAB deployments administrator, I would say it would have been worth doing.

For the abuse@ alias, my thinking is that larger MIAB deployments quite plausibly will end up sending spam as a result of malware infected clients. It seems probable to me in that in some cases recipients of the spam will be aware of the abuse@ convention and will attempt to report the issue to it. So again, if we speed up reporting in one case, I would say it would have been worth doing.

**Comment by bronson** [comment]
Just ran across another datapoint.  I really don't want to pile on -- badgering the project lead is never a good way to get what you want -- but I thought this was interesting:

![screen shot 2015-12-02 at 9 53 58 pm](https://cloud.githubusercontent.com/assets/1776/11553031/92a2a696-993f-11e5-9733-ccff7a5b3cc5.png)

Pingability is mentioned at the bottom of https://mailinabox.email/guide.html

**Comment by ariejan** [comment]
That's what started all this ;-)

**Comment by bronson** [comment]
Doh, right.  So much for my new datapoint.

**Comment by JoshData** [comment]
OK to `abuse`, no to `security`. @ariejan can you update (force push) or redo the PR to just add `abuse`?

**Comment by ariejan** [comment]
@JoshData done. See #605. Closing this issue, review can take place in #605.
