### ISSUE TITLE
Bring back Mail in a Box to its root's (The Mailserver)

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#606]
Hi there,

First: I want to thank Josh for his great work ;)

I would like to begin a discussion on the evolution of mail-in-a-box here. Mail-in-a-Box is an great software. I love it :) The only problem are the Web clients (Roundcube and ownCloud). 
They are not only incompatible (ownCloud Calendar <> RoundCube Contacts), but in some places quite unstable.

What should mail-in-a-box can?
In my opinion it should only provide an email server with DANE and "good" security configuration. The Nameserver is also an good point. 

The additional stuff (ownCloud - which will be droped (soon?)) and the webserver are just ballast.

ownCloud, Webserver and Webclients are creating at least 40% of the bugs, and prevent rapid development of the product itself. The mailserver.
Without this ballast we can further develop the Mail server faster and make more stable.

For this reason, I would remove (or at least make it optional ... for these people really needing it) everything (web server, ownCloud, ...), which is not required compulsory for operation of the mailserver.

I would move stuff like Autoresponder etc. directly into the Mailinabox Admin UI, so that the users (not only admins) can login there, and change their password, their autoresponder etc.) This would make sense ... (even if we would not remove RoundCube and ownCloud.)

Note: I'm not a hater of ownCloud. ownCloud is an insanely great software and I am one of their biggest fans. However: The contacts and calendar part is currently not justifiable in its use. I have high hopes for version 9.0 and the ownCloud/calendar-rework. ;)
It is a big dream of me to combine a stable ownCloud with calendar, contacts and the fresh Mail app with mail-in-a-box. But that's not possible. Not yet. But lets wait until Spring/Summer 2016. 

Maybe we can work together with the developers of ownCloud (the Mail app) then (2016) more. Indeed, with both great parts(Mailinabox and ownCloud Calendar + Contacts + Mail)  in the software it would be better (or even perfect).

**Comment by JoshData** [comment]
As a matter of modularization, I agree to an extent. But throwing away webmail is a nonstarter. And as I've said in #514 I'm also committed to having a contacts manager.

The web server nginx is used for other things as well - please read through the nginx config file templates to see. It will also be a necessary component of SSL certificate procurement with Lets Encrypt if I can get that working.

**Comment by aspdye** [comment]
Ok, i see. And what do you think about moving "Autoresponder" and "Change Password" to the Admin Panel?

**Comment by JoshData** [comment]
Only admins can log into the admin panel, so that's not going to be very helpful. :)

We need a non-admin admin panel first.

**Comment by aspdye** [comment]
Exactly. Thats what I mean. But an "non-admin"-Panel is not planned yet, or? But this would be verry cool :D

**Comment by JoshData** [comment]
It would be. I have no plans to work on it, but I would like to see it. The admin panel could be adapted to allow non-admin access but it'll take some work.

**Comment by yodax** [comment]
I was thinking of spending some time on the non admin admin panel. I would like users to be able to 

- reset passwords 
- resync z-push
- delete devices from z-push

But I would also like to build a backup option to google cloud storage. 

Is there a milestone list or wish list? Currently I am debugging some z-push bugs. I can lend a hand on other things on and off.

**Comment by JoshData** [comment]
My wish-list is just the things that have issues here that I've said in the issue are good ideas. But mostly I'm just trying to find the time to finish #268.

**Comment by aspdye** [comment]
Maybe we could put the non-admin panel into the admin panel ;) It think it would not make sense to manage 2 Panels. Additionaly to that a feature for "Domain Administrators" could be interessting ;)

**Comment by ChlorideCull** [comment]
I feel like modularization would be perfect for this, not only for allowing a degree of customization, but to support smaller setups. For example, I have a small VPS which has 128+128MB RAM, and isn't blacklisted when it comes to mail. It can run nginx, dovecot and postfix easily (doubt ownCloud or Roundcube, maybe SquirrelMail), but configuration is a pain, really.
What would need to be done to modularize the install? I could try to spare some time working on it.

**Comment by aspdye** [comment]
Closing for now; see other issues :)
