### ISSUE TITLE
Preparing ownCloud instances with upgrade to ownCloud 8.2 on ownCloud 9

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#610]
What do you think about the new version? 
First Bugfix (8.2.1) is already released ;)

**Comment by JoshData** [comment]
Each time I update ownCloud I am left with severe bugs. See #514. So I'm not eager to make any changes.

**Comment by aspdye** [comment]
I Understand that ;)

**Comment by aspdye** [comment]
Reopening here because we should do this now. It is needed for an upgrade to ownCloud 9 (3/2016), as soon as the first bug fix release 9.0.1 will be out (4/2016).

**Comment by anoma** [comment]
Correct me if I am wrong but the miab in a box updater can jump version i..e it does not enforce that you run each stable version upgrade sequentially.

If I am correct then does this no open the door for failed upgrades where a slow to update user skips the version that upgrades OC to 8.2 and attempts a direct to OC9/10 update.

**Comment by JoshData** [comment]
Correct. We will need to have the Mail-in-a-Box setup take the user through each required OC version in order to get to 9. (Another lovely aspect of OC!)

**Comment by anoma** [comment]
I cant see any upstream reference to actually requiring to step OC versions other than this single case here.

perhaps @aspdye can clarify. If it is a single 8>9 issue then we can look at it as a one off

**Comment by aspdye** [comment]
#789 solved this. closing.
