### ISSUE TITLE
Icon of "Vacation" in Settings (Roundcube Plugin / Larry Theme)

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#612]
I know that that is an problem with the plugin and not with MiaB, but maybe we could simple change the logo to a one which looks better with the others ;) We could also remove this point completely, because the filters do the same thing ;)

![design](https://cloud.githubusercontent.com/assets/12893462/11452195/16114edc-95e0-11e5-9f95-9d70493678e3.PNG)

**Comment by JoshData** [comment]
Uh, yeah, this is an issue for https://github.com/arodier/Roundcube-Plugins. We're not going to start patching upstream libraries just because an icon isn't pretty.

**Comment by aspdye** [comment]
@JoshData Yes. And what about removing the Point "Vacation" completely. I think it is a Duplicate of the much more Advanced Filter System ;) 

By the way: is the roundstrap theme still in active Development? Id like to See a "well Designed" Alternative to the Themes Provided yet :D

**Comment by JoshData** [comment]
Someone specifically requested the vacation plugin. See #334.

The [roundstrap theme](https://github.com/mail-in-a-box/roundstrap) was never actually in active development.
