### ISSUE TITLE
hostname - unset

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#613]
I now realise I have had hostname issues in the past and get the impression from posts here that MIAB should set the hostname and that  ```hostname``` and ```hostname -f``` should provide useful info.

Previously I have naively manually set the hostname since I did not know MIAB should but this time I never done it right and was alerted by Ubuntu with a constrant stream of "*** SECURITY information for localhost ***" emails.

My gut here is I have found another provider bug. Can you point me at what should happen and the code so I can confirm.

**Comment by JoshData** [comment]
VM providers usually take care of this. And I don't think it should really matter for Mail-in-a-Box.

To set the hostname, I believe we just need to write PRIMARY_HOSTNAME into `/etc/hostname` and then call `service hostname restart`. But I'm not sure about the FDQN hostname (`hostname -f`).

We use hostname to guess the PRIMARY_HOSTNAME so it would be a little circular to set this field ourselves.

What are the security warnings?

**Comment by anoma** [comment]
Perhaps this is a consequence of this not being a VM but a physical server.

The warning emails are hourly with a subject off ```*** SECURITY information for boxname ***```are of the pattern ```boxname: Nov 28 22:17:01 : root : unable to resolve host boxname```

**Comment by anoma** [comment]
Comparing my old and new installs there are marked difference between both hosts and hostname. I am not sure where these differences originate although it is likely a combination of NOC defaults, MIAB install script and manual configuration.

Consulting the internet and using ```box.domain.com``` and ```10.11.12.13``` as a fake examples as I understand it the following would be the correct configuration we should actively set:

```
root@box:~# cat /etc/hostname
box
```

```
root@box:~# cat /etc/hosts
127.0.0.1       localhost
10.11.12.13   localhost.localdomain   localhost
10.11.12.13   box.domain.com           box

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

```
root@box:~# hostname
box
```

```
root@box:~# hostname -f
box.domain.com
```
For reference once I set this my warning emails went away.

What I am not sure about though is the IPv6 section. Ideas?

**Comment by anoma** [comment]
I took the opportunity to test if this ```VM providers usually take care of this``` also applies to physical providers.

In my case if the Reverse DNS is set well in advance of the OS install the hostname and FQDN is set correctly by the NOC at install time.  However it seems if you apply the rDNS settings too soon (and obviously after) to the OS install the hostname is not set correctly.

I believe this explains another scenario for mixed results.

**Comment by bronson** [comment]
So, should mailinabox ensure the hostname and hostname --fqdn are set correctly and bail out if not?  That doesn't seem real useful to me since (agreed) it won't affect the behavior of the box itself.  But, as long as I can proceed with the install anyway, I don't see much harm either.

I don't like the idea of MIAB taking over /etc/hosts and /etc/hostname itself...  Someone's always going to have a weird config.  How much more networking should MiaB take over?

**Comment by anoma** [comment]
What alternative do we have? Currently one of the few install/upgrade questions we ask is to define the hostname but then we dont actually set it.

For me this resulted in an error email hourly until I fixed it for another unknown percentage it result sin an incomplete Ubuntu setup but without errors.

I agree it is a can or worms but I cant see how we can leave that bug dangling?

**Comment by bronson** [comment]
Ah, right.  I pictured it just being a log message even though you said email.  Agreed, it's wrong to have a machine in that state.

What do you think of just checking and warning about the hostname instead of actually taking control?

**Comment by anoma** [comment]
That's an idea, in the interim we could at least just add it to the "Status Checks" page and then later decide if it is a big enough problem to escalate.

**Comment by JoshData** [comment]
#773 sets the hostname during setup.
