### ISSUE TITLE
OX Appsuite (Open Xchange) as Replacement for Roundcube and ownCloud

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#614]
We are currently searching for an replacement for ownCloud. It should not be only less buggy - It should also be more functional ;)

![open-xchange-appsuite-7 6 0-screenshot1](https://cloud.githubusercontent.com/assets/12893462/11455941/c15547d6-9675-11e5-9288-9ccc89effab5.jpg)

The OX App Suite is Open Source (in the main parts), has an modern and responsive Design and could unite Webmailer, Contacts and Calendar (aswell as Documents, Spreadsheets,...).

With the OX Guard it offers OpenPGP directly in the Webmailer - verry understadable also for beginners.

It would also work with ActiveSync :) 

What do you think?

Problems (are there to solve them :laughing:)
-License Problems - Not the whole software is open source :(
-Resource Problems - I would need more RAM AFAIK ;)
-...

**Comment by NurdTurd** [comment]
:+1: +1

**Comment by anoma** [comment]
Isnt ```Resource Problems - I would need more RAM AFAIK ;)``` a complete show stopper?

What are the minimum real world specs?

**Comment by NurdTurd** [comment]
@anoma I agree.

**Comment by OmgImAlexis** [comment]
Doesn't look like this would work AT ALL. "OX App Suite: Memory 8 GB - 12 GB" - http://oxpedia.org/wiki/index.php?title=AppSuite:OX_System_Requirements

**Comment by JoshData** [comment]
That, plus it runs on Java, plus no Ubuntu installation instructions - so it doesn't seem like this will be an improvement. Thanks for looking into it though.
