### ISSUE TITLE
Don't warn about DNSSEC DS record if the domain's DNS is not managed by the box

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#615]
Hi there,

Considering the fact that CloudFlare now provides DNSSEC for domains, it is an alternative to the using of the MiaB DNS ;)

Personally - i have created an instance with the hostname (1. Domain) on the MiaB DNS (for TLSA Record, ...). All other secondary domains are at the CloudFlare DNS and use the External DNS Records provided by the MiaB Control Panel. (They dont need an TLSA-Record and the SSHFP-Records [which are not supported by CloudFlare] as i learned by @JoshData here: https://discourse.mailinabox.email/t/dane-tlsa-record-for-secondary-domain/945)

According to https://discourse.mailinabox.email/t/cloudflare-external-dns/928, I think we should change the message that the DS Record is incorrect to: ",this may be ok, if you are using an external DNS with its own DNSSEC Keys".

**Comment by JoshData** [comment]
If the domain is using external DNS, we should not offer any DNSSEC info for that domain -- it is up to the primary nameserver to do it.

**Comment by aspdye** [comment]
:+1: we Could make a Checkbox called I am using an External DNS. Then we Would only Check if the Records are correct ;)

**Comment by JoshData** [comment]
Yep that's #404.
