### ISSUE TITLE
Self-Sign Secondary Domains

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#618]
Title says everything ;) - I don't know if we need this if we natively integrate Let's Encrypt (starting public beta today :fireworks:)

**Comment by JoshData** [comment]
That's the plan.

Even without letsencrypt, I don't think there is a reason to self-sign secondary domain certificates vs the current practice of using the main domain's certificate.

**Comment by aspdye** [comment]
:+1:
