### ISSUE TITLE
Control Panel - Refactoring

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#620]

**Comment by h8h** [comment]
First step run Control Panel as nonprivileged user than we could talk about the other "features". If we want to do all the stuff than the Control Panel should not longer run with superuser rights.

A second thought: Do not reinvent the wheel.  I think it's not such a good idea to integrate a mailbox, cal- and carddav system into a control panel.

My wishes for a new control panel:
* Create / Delete Mailaccounts :heavy_check_mark: 
* Create / Delete / Assign Mailaccounts to groups (i.e. for a mailinglist)
* Some monitoring stuff :heavy_check_mark: 
* DNS Stuff :heavy_check_mark: 
* Maybe ACL to have different admins for different domains

**Comment by OmgImAlexis** [comment]
@aspdye to make the checkboxes show correctly they need to be written like `- [ ] a task list item`.

Better control over DNS would be great. Currently you can't edit DNS records at all and have to either remove and re-add them or just let a new DNS record replace the old one which could be bad if you accidently replace the wrong one.

**Comment by aspdye** [comment]
@OmgImAlexis Thank you ;) Things like this happen if you make such issues after a long day ;)

**Comment by aspdye** [comment]
Updated some points; referenced some points with new issues ;) feedback welcome!

**Comment by bronson** [comment]
It would be nice to fix the flash-of-content before the login box appears.

As an example: select any menu item while logged out.  But this also happens when visiting the admin interface after your login has expired.

I don't think there's any sensitive information in there -- that's all ajaxed in later -- but it doesn't look so hot.

**Comment by aspdye** [comment]
And maybe also hide the Pages (from Menu) if you are not logged in :wink: @bronson

**Comment by OmgImAlexis** [comment]
@aspdye might want to update this.
