### ISSUE TITLE
Support POP3

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#623]
Hi there,

Is there any reason why we are not supporting POP3 on the MiaB-Instances?
You may ask why we should do if we have IMAP. But there are still some people who want to use POP3 because of the "download of the emails to their personal pc" :laughing: I know that this is also possible with IMAP - but I am not able to make this clear to some kind of people. Supporting POP3 would make this much easier. I think it should not be complicated - pryley told us already in the Forum how we could realize it: 

https://discourse.mailinabox.email/t/enable-pop3-protocol-for-incoming-mail/97/4

**Comment by nstanke** [comment]
Actually MiaB already supports POP3 - https://github.com/mail-in-a-box/mailinabox/blob/5d158c524d1dff5e3df810bbd6913202604af2ee/setup/mail-dovecot.sh

**Comment by aspdye** [comment]
Ok ... will test this ... but: Why do so many people say (Slack and Forum) that it is not supported :confused: 

I think we should update the instructions on the Admin-Page then ;) What would you say @JoshData if I create a PR for this? :v:

**Comment by JoshData** [comment]
Yeah. I don't want to encourage pop over imap  but yes to documenting. Thanks. 

On December 10, 2015 2:53:19 PM EST, Marius <notifications@github.com> wrote:
>Ok ... will test this ... but: Why do so many people say (Slack and
>Forum) that it is not supported :confused: 
>
>I think we should update the instructions on the Admin-Page then ;)
>What would you say @JoshData if I create a PR for this? :v: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/623#issuecomment-163732287

-- 
Josh Tauberer (@JoshData) 

// Sent from my phone.

**Comment by aspdye** [comment]
Solved via PR #624
