### ISSUE TITLE
Know-How: Changing Role Mailboxes

### ISSUE THREAD

**Issue by nikolay** [mail-in-a-box/mailinabox#625]
I have this issue: people at a non-profit play different roles and those change periodically. If somebody was the secretary, let's say, I want them to have access to old emails sent to secretary@nonprofit.org while they play that role without having to share email credentials and force people to check both emails (person@nonprofit.org and role@nonprofit.org).

Is there a way to handle this via some copy or share mechanism? For example, while you're in a certain role, the email sent to role@nonprofit.org also gets copied to your personal mailbox and you can reply from that role@nonprofit.org as well.

**Comment by aspdye** [comment]
You Could create the roles as aliasses and redict them to the users. You are able to Change the Role Settings Without sharing new Passwords because the Users will still exist.

**Comment by dhpiggott** [comment]
Unfortunately @aspdye that won't allow a current secretary to view emails that were sent to a previous secretary. So @nikolay you can do quite a bit of what you want using aliases but not everything. You would need to share the passwords to a single mailbox for that.

Perhaps you could manually copy a subset of outgoing secretaries' emails from one of their IMAP folders into an IMAP folder of the incoming secretaries? You'd need to communicate very clearly with both though so each secretary would know to file mail into folders based on the role it was associated with. I imagine there are a few command line IMAP sync tools that you could choose from to do this on the server with each time roles change.

**Comment by aspdye** [comment]
Or we see it as a feature request for collaborative inboxes :see_no_evil:

**Comment by nikolay** [comment]
@aspdye Yes, this would be a killer one, honestly, as those are now all very expensive paid services such as https://frontapp.com/ and there's no open-source solution.

**Comment by bronson** [comment]
@nikolay it probably wouldn't be too hard to copy incoming role@np.org messages into a shared imap folder, then use aliases to direct them to the correct person's inbox.  [Sieve would handle the copying](https://mailinabox.email/advanced-configuration.html#filtering) and [dovecot can hopefully handle the sharing](http://wiki.dovecot.org/SharedMailboxes).

So, the current secretary would receive new messages, and anyone with permission could access the archive of all messages.

Downside is, of course, that doesn't include the outgoing replies.  Solving that gets much harder.
