### ISSUE TITLE
S3 backups not working with AWS signature version 4 (Frankfurt, Seoul)

### ISSUE THREAD

**Issue by tuminoid** [mail-in-a-box/mailinabox#627]
I have two MIAB 0.14 boxes, both sharing S3 creds for backup, to different folders in same bucket. One works just perfectly, another one only tells me `OK` in a dialog, but `Backups are turned off.` on the page when I enable S3 backups. Local backups work just fine on both boxes.

**Comment by soupdiver** [comment]
@tuminoid also :+1: here from my side. Added credentials some days ago but the bucket is still empty

**Comment by tuminoid** [comment]
As noted in #672:
"issu resolved by change the region ,mail in a box not work with Signature Version 4 in aws s3 all region work with signature 2 and 4 only Frankfort and (Seoul) have only version 4 thats why backup failed in this region."

I tested this by creating another bucket in Ireland, instead of Frankfurt, and yes, it does work now.

**Comment by ponychicken** [comment]
Should be fixed with PR #714 (at least I am backing up to Frankfurt w/o problems)
