### ISSUE TITLE
Reboot Machine from the Panel

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#631]

**Comment by bronson** [comment]
Sounds easy.  @JoshData if this is something you'd like to see, I can look into it.

**Comment by JoshData** [comment]
Yep this would be convenient. Don't make it too easy - it should require at least two clicks and explain to the user what rebooting means.

**Comment by h8h** [comment]
I think thats not a good idea. Its a webgui and if something failed with the authentification an attacker can reboot / shutdown the box. SSH with pubkey auth and nonpriv user login is more secure, you need at least a key and the root password  / user password if you use sudo. The control panel has only one password, with no check if the password is strong.

**Comment by bronson** [comment]
If authentication fails, an attacker rebooting your box will be the least of your worries.

(don't worry, you'd never be able to shutdown the box from the admin panel)

**Comment by h8h** [comment]
DOS through Rebooting the box over and over again is a nice and maybe a new attack vector :)

**Comment by JoshData** [comment]
Haha well... yeah. I think @bronson is right. We need better auth there. But because rebooting is a necessary step to apply Ubuntu updates, and it's a common step when debugging issues, the benefits outweigh the costs.

**Comment by aspdye** [comment]
The option will only appear if a restart is necessary;)

**Comment by benschumacher** [comment]
(This is off-topic of main issue, but...)

Disagree re: alternate port. Port scanners are fast and effective. Why not provide ability for two-factor authentication?

(TOTP)[https://en.m.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm] would be effective, is widely used, and would increase complexity for attacks against admin UI. However, getting it supported in dovecot, ownCloud, etc., might be tougher.

Best practice might be encouraging users to have admin accounts that aren't mail users...

**Comment by aspdye** [comment]
@benschumacher this is a Duplicate of #10 :Wink: thank you for your Commit. I've added this to the Refactoring List (#620) - PR's welcome :smile:

**Comment by JoshData** [comment]
To be clear: If someone builds a Reboot Machine button, I will merge it. No need to wait for better auth.

**Comment by aspdye** [comment]
A discussion i've found: 
http://stackoverflow.com/questions/18438805/how-to-suspend-restart-linux-ubuntu-from-php-script

So we should may be not do this for Security reason ;)

**Comment by JoshData** [comment]
Uh.

**Comment by aspdye** [comment]
Reopen?

**Comment by bronson** [comment]
@aspdye I don't see how the link you gave is relevant to this issue...?  Can you say more?

That page links to ANOTHER page which says that giving PHP root perms is bad (duh!), but nobody's talking about doing that.

**Comment by aspdye** [comment]
But how do we want to realize rebooting without PHP root perms? @bronson

**Comment by bronson** [comment]
mailinabox-daemon is already running as root.  I suppose it would just do it itself.

An alternative is to put explicit entry in the sudoers file.  Or have a setuid binary.  Or have a reboot service listening on a unix-domain socket.

**Comment by JoshData** [comment]
Don't overthink it guys. Since the daemon is already running as root, there is no (new) permissions issue.
