### ISSUE TITLE
Warning about uninstalling Apache

### ISSUE THREAD

**Issue by alexweissman** [mail-in-a-box/mailinabox#635]
To my horror, and without any warning, MiaB uninstalled Apache on my Droplet!  A warning and/or confirmation would be greatly appreciated.  There is nothing in the README or front page of the website that tells me that MiaB's installer will automatically uninstall Apache.

**Comment by JoshData** [comment]
It says in several places that you are expected to install it on a fresh machine dedicated to Mail-in-a-Box.

**Comment by alexweissman** [comment]
All I see is:
> Technically, Mail-in-a-Box turns a fresh cloud computer into a working mail server. But you don’t need to be a technology expert to set it up.

"Fresh" isn't exactly a precise word (why not "dedicated"?), and it's very bad to assume that a user will automatically know that this translates into "if you don't do this, MiaB will uninstall Apache".

**Comment by dhpiggott** [comment]
https://mailinabox.email/guide.html does already have this:

>Can I modify my box after / use my box for something else too? (Advanced.)
>No. Mail-in-a-Box must be installed on a fresh machine that will be dedicated to Mail-in-a-Box, and you cannot modify the box after installation (configuration changes will get overwritten by the box’s self-management). If you are looking for something more advanced, try iRedMail, Sovereign, or Modoboa.

**Comment by alexweissman** [comment]
Ok.  I would still at least have a confirmation dialog (and explanation) in the installer.  Any time you are removing a component from someone's server, you should let them confirm (perhaps with a CL flag to override the dialog for users who already know what they're doing).

**Comment by aspdye** [comment]
Thats correct 👍🏼

**Comment by JoshData** [comment]
I'd accept a PR that clarifies the requirements (here and/or in https://github.com/mail-in-a-box/mailinabox.email).

**Comment by aspdye** [comment]
PR submitted ;)

**Comment by s4wny** [comment]
wow.. you just uninstalled apache from my server.....

You should really put a big warning in the installation script that clearly says that this is only intended for use at fresh boxes, that the script will uninstall existing packages. You should also put a warning at the website above the installation script snippet (https://mailinabox.email/guide.html#setup).

It's not clear that the script will uninstall software from your server. People will not read everything at your website before installing. Many people like me will probably find mail-in-a-box via some forum (like this [askubuntu thread](http://askubuntu.com/questions/227209/simple-method-to-install-a-mail-server)) or google and directly jump to the installation snippet and copy paste that. Usually script only _add_ things, never _delete_ existing software.

You really should accept and merge pull request #638 .

**Comment by 0xFelix** [comment]
Fifth point in the checklist at the top: https://mailinabox.email/guide.html

Excuse me, but installing / running a script on a server before knowing what it does is just plain stupid.
IMO that is your own fault, there is nothing to accuse @JoshData of.

**Comment by s4wny** [comment]
It's a really easy fix for you to just accept the pull request (takes two clicks?) and it would save people from a lot of trouble. It's just mean to not add that warning text.

Of course you could say that you should know what the script do before you install it. And of course you should. But in reality people do not have time to inform themselves of what every script they run do. People don't have time to read through all the source code and take time to understand what it do. Instead we rely on the fact that most software only _add_ things and if they _remove_ things they usually _warns_ the user before doing so. Also, if they remove/destroy things you usually can undo it with some other command.

Now, I only executed this script on a private toy box that I sat up during the weekend, so no "real" damage have been done, (except that I need to waste a few hours on reinstalling my box...). If it had been a production server I of course had taken the time to read through all instructions and had probably taken a backups before running the script. Hey, I probably had tested it on a different server first. But as a hobbyist, I don't do all of that and just want to get things done fast. And in these cases I rely on standard conventions. Like big warnings if the scripts does something dangerous.

**Comment by JoshData** [comment]
I posted some requests in the PR and, also, the text in it is ungrammatical. If someone submits a PR that is clear and not scary to novices and doesn't have grammatical errors, I'll merge it.

**Comment by JoshData** [comment]
Fixed by #712.
