### ISSUE TITLE
v0.15 release candidate - please test

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#639]
Hi all,

I've posted a `v0.15-rc1` tag, a release candidate for v0.15.

This doesn't have any of the Let's Encrypt functionality yet, but it's taking a long time so I wanted to get an update out in the meanwhile. See the [Changelog](https://github.com/mail-in-a-box/mailinabox/blob/master/CHANGELOG.md) for details.

Please help me test!

To move to this version, you can run:

    curl -s https://mailinabox.email/bootstrap.sh | sudo TAG=v0.15-rc1 bash

if you installed this way originally, or on a new machine. (Note the placement of `TAG=v0.15-rc1` between sudo and bash.)

Or:

    cd mailinabox
    sudo git fetch origin tag v0.15-rc1
    sudo git checkout v0.15-rc1
    sudo setup/start.sh

Please post any issues. Thanks.

**Comment by yodax** [comment]
I have updated my install. No issues yet, only looked at a few commits to test. Will try and look at the rest in the coming days.

**Comment by dhpiggott** [comment]
I just updated. Everything is working nicely so far. I reviewed most of the diffs from 0.14.0 to 0.15.0-rc1 and all looked good, though I glossed over some of the larger refactorings.

Thank you Josh and everyone who contributed!

**Comment by Gatewayy** [comment]
I have updated as well without issue thus far.  I am happy to see the Fail2Ban improvbments. :)

Brett Elliff

Written in smoke, translated by Warlock, and sent by carrier pigeon.

**Comment by aspdye** [comment]
Does work for me :)

**Comment by JoshData** [comment]
Released! Thanks all.
