### ISSUE TITLE
Status Check - Hardware Firewall & SPF etc. Records

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#641]
Check if all neccassary ports are open... not only SMTP ;)
Some providers block all ports by default, and the user must open ports in hardware firewall.

We could (and should!) also check whether the SPF and DKIM, DMARC Records are correct (if using External DNS).

**Comment by JoshData** [comment]
Firewalls usually just block inbound traffic, and there's no way we can test that from inside the firewall.

**Comment by aspdye** [comment]
With a Test Instance doing a Port Scan 😁😁

**Comment by bronson** [comment]
@aspdye do you mean that you (or someone) would set up a portscanning service that miab would use during the status check?

**Comment by aspdye** [comment]
Hehe ... Yes. That was what I meaned. But if i think about it ... Sounds insecure :wink:

**Comment by bronson** [comment]
I wonder if http://www.canyouseeme.org/ offers an API.

**Comment by JoshData** [comment]
Yeah not a great idea...
