### ISSUE TITLE
Domain resolving & Messages for external DNS

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#642]
Against the changelog, the external DNS Messages are still the same with 0.15-rc1? If not - they are still to agressive. If the MX is setted up correctly the NS Stuff should be at least yellow.

Same for:

For the primary domain or the hostname this is fine, but for all other domains, i think we should change this to yellow, and maybe add some text, that this might be ok., if you are using another webserver (shared-hosting, external webserver)

Current message:
[RED]
This domain should resolve to your box's IP address (XX) if you would like the box to serve webmail or a website on this domain. The domain currently resolves to XX in public DNS. It may take several hours for public DNS to update after a change. This problem may result from other issues listed here.

**Comment by JoshData** [comment]
Similar to #404.
