### ISSUE TITLE
Move Munin into Control Panel (with iFrame?)

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#651]

**Comment by JoshData** [comment]
An iframe sized to fit the browser window properly would be fine.

**Comment by bronson** [comment]
For this to work well, I suppose you'd want Munin to use the admin interface's cookie instead of using the browser-based auth-basic.

**Comment by guyzmo** [comment]
I personally believe the iframe is not the best option, we might prefer extract the few graphs that are really meaningful to put on the "status" page, and with a link see the others on the munin page?

**Comment by JoshData** [comment]
I think #674 pretty much took care of this.
