### ISSUE TITLE
Integrate Mail Settings (Filters, Password...) directly into the Panel

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#652]

**Comment by JoshData** [comment]
Password yes (requires non-admin access to the control panel, though), filters no (why duplicate what's already in Roundcube?).

**Comment by nstanke** [comment]
Thanks to #45 users already have the ability to change their password within Roundcube.

**Comment by JoshData** [comment]
Since we don't allow non-admin users to access the control panel, it's not going to help to put this functionality into it. We could make a non-admin control panel (I think that's in another issue?) but that's a big thing.
