### ISSUE TITLE
S3 Backup Credentials lost after upgrade to 0.15

### ISSUE THREAD

**Issue by ariejan** [mail-in-a-box/mailinabox#653]
Hey,

I've got backups to S3 enabled in 0.14. I can verify this, because my backup bucket is full of backups. 

Just upgraded to 0.15 and backups are not configured. Running `management/daily_tasks.sh` manually gives:

```
BackendException: No connection to backend
Traceback (most recent call last):
  File "management/backup.py", line 467, in <module>
    perform_backup(full_backup)
  File "management/backup.py", line 220, in perform_backup
    full_backup = full_backup or should_force_full(env)
  File "management/backup.py", line 134, in should_force_full
    for bak in backup_status(env)["backups"]:
KeyError: 'backups'
```

**Comment by JoshData** [comment]
Looks like it might be related to https://raim.codingfarm.de/blog/2015/03/12/backup-with-duply-to-amazon-s3-backendexception-no-connection-to-backend/, although I'm not sure why the problem would begin now.

**Comment by kimthostrup** [comment]
I get somewhat the same error, initially my local backup was working fine, then after trying to setup S3 backup, that failed I went back to local backup, but then I get a "Something went wrong, sorry" message in the UI.
If I try to run management/daily_tasks.sh
I get the following error message:
----snip----
management/daily_tasks.sh
Traceback (most recent call last):
  File "management/backup.py", line 467, in <module>
    perform_backup(full_backup)
  File "management/backup.py", line 220, in perform_backup
    full_backup = full_backup or should_force_full(env)
  File "management/backup.py", line 134, in should_force_full
    for bak in backup_status(env)["backups"]:
  File "management/backup.py", line 80, in backup_status
    backups[key]["size"] += size
KeyError: '20151127T054626Z'
----snip----

Any Idea what is wrong ?

Thanks in advance.

**Comment by flasheater** [comment]
I am having the same issue after upgrading from 13a to 15a.

management/daily_tasks.sh
-----------------------------------

   root@box:~/mailinabox# management/daily_tasks.sh
BackendException: No connection to backend
Traceback (most recent call last):
  File "management/backup.py", line 467, in <module>
    perform_backup(full_backup)
  File "management/backup.py", line 220, in perform_backup
    full_backup = full_backup or should_force_full(env)
  File "management/backup.py", line 134, in should_force_full
    for bak in backup_status(env)["backups"]:
KeyError: 'backups'


The file ´/home/user-data/backup/custom.yaml´ seems to be correct (credentials and path at least look correct), the web GUI however
![screenshot from 2016-01-11 17-22-33](https://cloud.githubusercontent.com/assets/876467/12239234/003f2852-b888-11e5-9fa6-74db031515f5.png) indicates backup is turned of and/or not configured.

If there is anything more I can show, let me know.

**Comment by JoshData** [comment]
All, please try with v0.16.

**Comment by ariejan** [comment]
Some, progress, I now get this (both in the admin interface as well as when running `backup.py` manually.

```
~/mailinabox/management# ./backup.py
BackendException: No connection to backend
Something is wrong with the backup: ERROR 23 BackendException
. BackendException: No connection to backend
```

**Comment by tempoturn** [comment]
Very simple worked for me:
sudo pip install --upgrade boto

**Comment by ariejan** [comment]
I can confirm that @tempoturn's solution works on my v0.16 install.

@tempoturn :+1:

**Comment by JoshData** [comment]
Reopening the issue - the Mail-in-a-Box installer should ensure that boto gets upgraded.

**Comment by kobby-w** [comment]
I have the same error after a fresh installation of 0.16.
I tried the solution from tempoturn, but it does not work for me.
S3 region us-east-1 (Oregon)

Error:
Something is wrong with the backup: ERROR 23 BackendException
. BackendException: No connection to backend

**Comment by kobby-w** [comment]
Hi,
I found out, the problem it, the backup works with some S3 regions, and with some not.
E.g. Sao Paulo sa-east-1 works and Oregon us-east-1 works not. 
It is because Amazon has change the version of the API. sa-east-1 is using the old version of the API and Oregon already API V4.
In the web I found, that we have to use this switch:
export S3_USE_SIGV4="True"
Can someone change this in the backup program?
I tried to use it in the config file for the backup, but it does not work.

**Comment by kobby-w** [comment]
Sorry: not Oregon, it is N. Virginia.

**Comment by kobby-w** [comment]
Meanwhile, it is working again for many S3 regions: Virgina, California, Oregon, Sao Paulo...
Maybe it was only a technical problem at AWS?

**Comment by ponychicken** [comment]
The fault is this commit: b32cb6229b5ca519f63603271078afc02169b4e8
The ap-get package lags behind and has currently an unfixed bug that makes it impossible to use with s3 locations that use the new signature version 4. 

That commit also made the problem only appear on an update, since before the new boto was installed and after the upgrade downgraded to the broken one.

**Comment by JoshData** [comment]
Ahha!! Thank you! Would you submit a PR that reverts that commit and explains why?

**Comment by ponychicken** [comment]
Sure, PR #714
