### ISSUE TITLE
Can't system check

### ISSUE THREAD

**Issue by nfodor** [mail-in-a-box/mailinabox#659]
root@(none):~# /root/mailinabox/management/status_checks.py

System
======
✓  All system services are running.
✖  The SSH server on this machine permits password-based login. A more secure way to log in is using a public key. Add your SSH 
   public key to $HOME/.ssh/authorized_keys, check that you can log in without a password, set the option 'PasswordAuthentication 
   no' in /etc/ssh/sshd_config, and then restart the openssh via 'sudo service ssh restart'.
✓  System software is up to date.
fatal: No tags can describe '06a0e7f3fe844a74d3dfa5770a3a8f0ebfbba197'.
Try --always, or create some tags.
Traceback (most recent call last):
  File "/root/mailinabox/management/status_checks.py", line 933, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "/root/mailinabox/management/status_checks.py", line 37, in run_checks
    run_system_checks(rounded_values, env, output)
  File "/root/mailinabox/management/status_checks.py", line 167, in run_system_checks
    check_miab_version(env, output)
  File "/root/mailinabox/management/status_checks.py", line 762, in check_miab_version
    this_ver = what_version_is_this(env)
  File "/root/mailinabox/management/status_checks.py", line 747, in what_version_is_this
    tag = shell("check_output", ["/usr/bin/git", "describe", "--abbrev=0"], env={"GIT_DIR": os.path.join(miab_dir, '.git')}).strip()
  File "/root/mailinabox/management/utils.py", line 193, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'describe', '--abbrev=0']' returned non-zero exit status 128

**Comment by nstanke** [comment]
How did you setup your MiaB instance? Disabling the update check should resolve your problem.

**Comment by nfodor** [comment]
Can I rerun the setup to turn it off if I set it to on without loosing the
config ?

**Comment by nstanke** [comment]
Set PRIVACY=True in ```STORAGE_ROOT/settings.yaml``` (```/home/user-data/settings.yaml``` by default)

**Comment by dhpiggott** [comment]
Can you paste the output of `git tag -l` and `git describe` in `/root/mailinabox/`?

**Comment by nfodor** [comment]
root@(none):~/mailinabox# git tag -l

14.08-beta

v0.01

v0.02

v0.03

v0.04

v0.05

v0.06

v0.07

v0.08

v0.09

v0.10

v0.11

v0.11b

v0.12

v0.12b

v0.12c

v0.13a

v0.13b

v0.14

v0.15

v0.15-rc1

root@(none):~/mailinabox# git describe

fatal: No tags can describe '06a0e7f3fe844a74d3dfa5770a3a8f0ebfbba197'.

Try --always, or create some tags.

**Comment by nfodor** [comment]
Disabling new version check through privacy setting allowed check to complete from the web UI.

**Comment by nstanke** [comment]
Perfect. I guess we need some error handling in https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L742 to resolve this issue completely.

**Comment by nstanke** [comment]
@nfodor Running ```curl -s https://mailinabox.email/bootstrap.sh | sudo bash``` should make the update check working again for you.

**Comment by dhpiggott** [comment]
@nstanke I'm still trying to understand how it is that git describe is failing in this way when the tags are present and the commit is a reasonable enough one to be on. What do you think is wrong and what is it that the bootstrap script does that you think will fix it?
