### ISSUE TITLE
munin lock exists

### ISSUE THREAD

**Issue by Mikopet** [mail-in-a-box/mailinabox#660]
I got this message on a simple install:

Installing Munin (system monitoring)...
[FATAL ERROR] Lock already exists: /var/run/munin/munin-update.lock. Dying.
 at /usr/share/perl5/Munin/Master/Update.pm line 128.

**Comment by aspdye** [comment]
Can you provide us more information about your Hosting Provider, the Image you use? (Did you use an clean install?)

**Comment by Mikopet** [comment]
Yes. This was a clean install, on a DigitalOcean 10$ VPS (ubuntu 14.04 x64)

**Comment by aspdye** [comment]
Have you done everything like in Guide? 
Try to reset the Droplet and reinstall everything.

**Comment by Mikopet** [comment]
Yes, i did.
It was only a beauty-issue. everythings works fine.
I just want to notice you, that message can appear

**Comment by aspdye** [comment]
Thank you Mikopet :)
Can anybody reproduce this? I can't :(

**Comment by flasheater** [comment]
I witnessed the same thing.

    Installing Munin (system monitoring)...
    [FATAL ERROR] Lock already exists: /var/run/munin/munin-update.lock. Dying.
     at /usr/share/perl5/Munin/Master/Update.pm line 128.
    updated DNS: bugabinga.net
    web updated

Happened during the upgrade of Version 13a to 15a.
DigitalOcean 10$ VPS (ubuntu 14.04 x64).

**Comment by JoshData** [comment]
I see this a lot too and don't know what the cause is.

**Comment by anoma** [comment]
fwiw i seen this recently and tracked it back to filesystem corruption causing heavy IO wait. i never looked any further since something was very sick on my server.

**Comment by illume** [comment]
I just saw this when running the mail in a box setup again. It stopped at the `Installing Munin (system monitoring)...` part and then gave that error. I rebooted, and ran the upgrade script again and it worked this time.
