### ISSUE TITLE
Secondary nameserver check fails

### ISSUE THREAD

**Issue by frootmig** [mail-in-a-box/mailinabox#666]
I get the error

Secondary nameserver XXX is not configured correctly. (It resolved this domain as [timeout]. It should be <IP>.)

On console I can query both IPv4 and both IPv6 adresses and they respond inside of 2-30ms.

External nameserver checks indicate no error, too.

**Comment by rainulf** [comment]
Do you mean secondary NS check fails, but shows no error on External DNS page? Sounds related to #692

**Comment by frootmig** [comment]
As I wrote: "External nameserver checks indicate no error, too."

My error is related to secondary NS that have more than one IPv4 and/or more than one IPv6.

This error hit me that bad (wait long after login to display the page) that I need to restructure the secondary NS systems and to only use one IPv4 and one IPv6. So I'm no longer able to reproduce this fatal error as I'm no longer using this secondary NS setup.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
