### ISSUE TITLE
Roundcube folder files ownership seems wrong

### ISSUE THREAD

**Issue by kri3v** [mail-in-a-box/mailinabox#667]
Hi everyone, 

I just tumbled upon this, looks like /usr/local/lib/roundcubemail files shiped with user 501 and group 80 (I dont have any user with those UID, Ubuntu starts on 1000, and below 1000 is for daemons)

Its not a new box, I have it since version 0.10. And I never made any changes on roundcube folder.

Despite this, Roundcube is working OK. No issues so far. 

http://pastebin.com/WE9rtif2

Regards,

**Comment by rainulf** [comment]
It is wrong lol. I don't see any lines that sets ownership/permission after roundcube was downloaded and extracted `setup/webmail.sh`. Perhaps it can be by root?

**Comment by kri3v** [comment]
Yes, when you extract a tar using root keeps the original owner of the
file. The person who uploaded this tar to sourceforge had his UID 501 has
owner.


Happened to me several times with wordpress tar.gz


2016-01-07 9:27 GMT-03:00 Rainulf Pineda <notifications@github.com>:

**Comment by JoshData** [comment]
Fixed, thanks!
