### ISSUE TITLE
Backup's page throws 500

### ISSUE THREAD

**Issue by gautambt** [mail-in-a-box/mailinabox#671]
Hi,

I just upgraded to 0.15a and the backups page is throwing a 500. I was previously on 0.14 and had upgraded by re-running bootstrap.sh. I had earlier configured S3 backups. When I now open the backups page the configurations seems lost. When I try to recreate the configuration, I get this message in a popup:

<pre>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p> 
</pre>

There are no backups listed in available backups section. Running management/backups.py manually seems to succeed with the following output:

<pre>
gautam@box:~/mailinabox$ sudo ./management/backup.py 
php5-fpm stop/waiting
 * Stopping Postfix Mail Transport Agent postfix
   ...done.
dovecot stop/waiting
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Sun Dec  6 06:46:35 2015
--------------[ Backup Statistics ]--------------
StartTime 1452410844.33 (Sun Jan 10 07:27:24 2016)
EndTime 1452410846.87 (Sun Jan 10 07:27:26 2016)
ElapsedTime 2.54 (2.54 seconds)
SourceFiles 7608
SourceFileSize 754038650 (719 MB)
NewFiles 7
NewFileSize 27347 (26.7 KB)
DeletedFiles 0
ChangedFiles 7
ChangedFileSize 6536845 (6.23 MB)
ChangedDeltaSize 0 (0 bytes)
DeltaEntries 14
RawDeltaSize 327091 (319 KB)
TotalDestinationSizeChange 231659 (226 KB)
Errors 0
-------------------------------------------------

dovecot start/running, process 29528
 * Starting Postfix Mail Transport Agent postfix
   ...done.
php5-fpm start/running, process 29642
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Sun Dec  6 06:46:35 2015
There are backup set(s) at time(s):
Sun Dec  6 06:46:35 2015
Mon Dec  7 06:27:26 2015
Wed Dec  9 06:49:37 2015
Thu Dec 10 06:37:31 2015
Fri Dec 11 06:42:53 2015
Sat Dec 12 06:26:14 2015
Sun Dec 13 06:25:48 2015
Mon Dec 14 06:53:57 2015
Tue Dec 15 06:49:11 2015
Wed Dec 16 06:50:49 2015
Thu Dec 17 06:34:09 2015
Fri Dec 18 06:38:01 2015
Sat Dec 19 06:38:25 2015
Sun Dec 20 06:28:26 2015
Mon Dec 21 06:45:35 2015
Tue Dec 22 06:52:28 2015
Wed Dec 23 06:35:24 2015
Thu Dec 24 06:25:50 2015
Fri Dec 25 06:33:55 2015
Sat Dec 26 06:33:10 2015
Mon Dec 28 06:26:06 2015
Tue Dec 29 06:31:35 2015
Wed Dec 30 06:34:01 2015
Thu Dec 31 06:44:01 2015
Fri Jan  1 06:50:14 2016
Sat Jan  2 06:44:25 2016
Sun Jan  3 06:49:08 2016
Mon Jan  4 06:42:49 2016
Tue Jan  5 06:28:26 2016
Wed Jan  6 06:50:51 2016
Thu Jan  7 06:38:56 2016
Which can't be deleted because newer sets depend on them.
No old backup sets found, nothing deleted.
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Sun Dec  6 06:46:35 2015
No extraneous files found, nothing deleted in cleanup.
</pre>

**Comment by JoshData** [comment]
Can you look in `/var/log/syslog` for errors when you try to load the page in the admin?

**Comment by gautambt** [comment]
/var/log/syslog has this:
 
<pre>
Jan 10 17:06:29 box Exception on /system/backup/config [GET]#012Traceback (most
recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py",
line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File
"/usr/lib/python3/dist-packages/flask/app.py", line 1477, in
full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File
"/usr/lib/python3/dist-packages/flask/app.py", line 1381, in
handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File
"/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012
raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475,
in full_dispatch_request#012    rv = self.dispatch_request()#012  File
"/usr/lib/python3/dist-packages/flask/app.py", line 1461, in
dispatch_request#012    return
self.view_functions[rule.endpoint](**req.view_args)#012  File
"/usr/local/bin/mailinabox-daemon", line 49, in newview#012    except
ValueError as e:#012  File "/usr/local/bin/mailinabox-daemon", line 415, in
backup_get_custom#012    def do_updates():#012  File
"/home/gautam/mailinabox/management/backup.py", line 15, in <module>#012
from utils import exclusive_process, load_environment, shell, wait_for_service,
fix_boto#012ImportError: cannot import name 'fix_boto'

Jan 10 17:06:29 box Exception on /system/backup/status [GET]#012Traceback (most
recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py",
line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File
"/usr/lib/python3/dist-packages/flask/app.py", line 1477, in
full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File
"/usr/lib/python3/dist-packages/flask/app.py", line 1381, in
handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File
"/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012
raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475,
in full_dispatch_request#012    rv = self.dispatch_request()#012  File
"/usr/lib/python3/dist-packages/flask/app.py", line 1461, in
dispatch_request#012    return
self.view_functions[rule.endpoint](**req.view_args)#012  File
"/usr/local/bin/mailinabox-daemon", line 49, in newview#012    except
ValueError as e:#012  File "/usr/local/bin/mailinabox-daemon", line 409, in
backup_status#012    "%s (%s)\n"#012  File
"/home/gautam/mailinabox/management/backup.py", line 15, in <module>#012
from utils import exclusive_process, load_environment, shell, wait_for_service,
fix_boto#012ImportError: cannot import name 'fix_boto'
</pre>

**Comment by JoshData** [comment]
Try `sudo service mailinabox restart`?

**Comment by gautambt** [comment]
That worked, Thanks!
