### ISSUE TITLE
Backup to s3 not work

### ISSUE THREAD

**Issue by gtari** [mail-in-a-box/mailinabox#672]
Any solution for the s3 backup I was try more solution but every time backup is turn off,local backup work great but to s3 not work.

**Comment by tuminoid** [comment]
Dupe of #627.

**Comment by gtari** [comment]
issu resolved by change the region ,mail in a box not work with Signature Version 4 in aws s3 all region work with signature 2 and 4 only Frankfort and (Seoul) have only version 4 thats why backup failed in this region.
thank you for this great project
good luck
