### ISSUE TITLE
Install Error OpenVZ without IPv6

### ISSUE THREAD

**Issue by gleert** [mail-in-a-box/mailinabox#680]
Hello,

When trying to install on an OpenVZ VPS without IPv6 support I get the following errors:

Updating system packages...
Installing system packages...
Initializing system random number generator...
WARN: uid is 0 but '/' is owned by 112
ERROR: initcaps
[Errno 2] modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab108.8/modules.builtin.bin'
modprobe: FATAL: Module ip6_tables not found.
ip6tables v1.4.21: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

WARN: uid is 0 but '/' is owned by 112
ERROR: initcaps
[Errno 2] modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab108.8/modules.builtin.bin'
modprobe: FATAL: Module ip6_tables not found.
ip6tables v1.4.21: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

Installing nsd (DNS server)...
WARN: uid is 0 but '/' is owned by 112
ERROR: initcaps
[Errno 2] modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab108.8/modules.builtin.bin'
modprobe: FATAL: Module ip6_tables not found.
ip6tables v1.4.21: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

Installing Postfix (SMTP server)...
WARN: uid is 0 but '/' is owned by 112
ERROR: initcaps
[Errno 2] modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab108.8/modules.builtin.bin'
modprobe: FATAL: Module ip6_tables not found.
ip6tables v1.4.21: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

WARN: uid is 0 but '/' is owned by 112
ERROR: initcaps
[Errno 2] modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab108.8/modules.builtin.bin'
modprobe: FATAL: Module ip6_tables not found.
ip6tables v1.4.21: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

FAILED: service postgrey restart

**Comment by gleert** [comment]
I have changed in /etc/default/ufw this line:
IPV6=yes to IPV6=no

Now I get the following errors:
Updating system packages...
Installing system packages...
Initializing system random number generator...
WARN: uid is 0 but '/' is owned by 112
WARN: uid is 0 but '/' is owned by 112
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
WARN: uid is 0 but '/' is owned by 112
Installing Postfix (SMTP server)...
WARN: uid is 0 but '/' is owned by 112
WARN: uid is 0 but '/' is owned by 112

FAILED: service postgrey restart

**Comment by gleert** [comment]
chown root.root / /etc has solved the issue "WARN: uid is 0 but '/' is owned by 112"

Now I get:

Mail-in-a-Box Version:  v0.15a

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...

FAILED: service postgrey restart
-----------------------------------------
-----------------------------------------


Any idea??

**Comment by gleert** [comment]
After a reboot of the VPS all installed just fine...

**Comment by JoshData** [comment]
OpenVZ has had other weird issues along the way. Closing, since it seems like you got it to work.
