### ISSUE TITLE
Can't change static directory of domain

### ISSUE THREAD

**Issue by OmgImAlexis** [mail-in-a-box/mailinabox#682]
After clicking update I just get a dialog saying "nothing changed" and the path is still the default.

![screen shot 2016-01-18 at 3 00 20 pm](https://cloud.githubusercontent.com/assets/6525926/12383300/459ee538-bdf4-11e5-9db2-b660a7d4fbe3.png)
![screen shot 2016-01-18 at 3 00 35 pm](https://cloud.githubusercontent.com/assets/6525926/12383301/45a39b6e-bdf4-11e5-9728-4c270b8e5c19.png)

**Comment by chrplace** [comment]
Try creating the the directory using the command line on the box, before hitting 'Update'.

It's not obvious I agree.

**Comment by OmgImAlexis** [comment]
@chrplace it works now. The UI either needs to make that for you or something needs to be added somewhere to indicate that.

**Comment by JoshData** [comment]
Dup of #415.
