### ISSUE TITLE
Use "Junk" folder instead of "Spam" for junk mail

### ISSUE THREAD

**Issue by cybercode** [mail-in-a-box/mailinabox#686]
MAIB is currently set up to move/auto-learn junk mail when it is moved in/out of the "Spam" folder. While i see that dovecot is configured to treat "Junk" as an alternative spam folder, i don't believe it can be used for auto-learning. IOS/Mac mail is configured to treat "Junk" as the junk mailbox (and don't seem to be reconfigurable on IOS) i would like to be able to/have the default spam mailbox changed to "Junk" from "Spam". FYI, the IETF (RFC 6154) folder recommendations are as follows:

  \All
      This mailbox presents all messages in the user's message store.
      Implementations MAY omit some messages, such as, perhaps, those
      in \Trash and \Junk.  When this special use is supported, it is
      almost certain to represent a virtual mailbox.

   \Archive
        This mailbox is used to archive messages.  The meaning of an
        "archival" mailbox is server-dependent; typically, it will be
        used to get messages out of the inbox, or otherwise keep them
        out of the user's way, while still making them accessible.

   \Drafts
        This mailbox is used to hold draft messages -- typically,
        messages that are being composed but have not yet been sent.  In
        some server implementations, this might be a virtual mailbox,
        containing messages from other mailboxes that are marked with
        the "\Draft" message flag.  Alternatively, this might just be
        advice that a client put drafts here.

   \Flagged
        This mailbox presents all messages marked in some way as
        "important".  When this special use is supported, it is likely
        to represent a virtual mailbox collecting messages (from other
        mailboxes) that are marked with the "\Flagged" message flag.

   \Junk
        This mailbox is where messages deemed to be junk mail are held.
        Some server implementations might put messages here
        automatically.  Alternatively, this might just be advice to a
        client-side spam filter.

   \Sent
        This mailbox is used to hold copies of messages that have been
        sent.  Some server implementations might put messages here
        automatically.  Alternatively, this might just be advice that a
        client save sent messages here.

   \Trash
        This mailbox is used to hold messages that have been deleted or
        marked for deletion.  In some server implementations, this might
        be a virtual mailbox, containing messages from other mailboxes
        that are marked with the "\Deleted" message flag.
        Alternatively, this might just be advice that a client that
        chooses not to use the IMAP "\Deleted" model should use this as
        its trash location.  In server implementations that strictly
        expect the IMAP "\Deleted" model, this special use is likely not
        to be supported.

**Comment by JoshData** [comment]
You're going to have to survey all of the common mail clients to see what they expect, and how configurable they are, to make the case that we should change the default to match iOS (which, btw, is going to cause trouble for any existing installs).

I'm going to close this, but feel free to request reopening if you can show that Spam would be an improvement for most users.

**Comment by cybercode** [comment]
Well, I found a work-around, putting it here incase anyone else runs across this issue.

 it seems that if you sync you mail info between IOS and OS X, if you select the "Spam" folder in OS X Mail app and use the menu Item `Mailbox -> Use the Mailbox As -> Junk Mailbox`, the setting will be picked up by the IOS devices.

But I still think it and the other "special" mailboxes:

* Drafts
* Trash
* Sent
* Archive

should be configurable. ;)

**Comment by JoshData** [comment]
> should be configurable. ;)

I'd love _everything_ to be configurable, but I also want to not spend my whole life maintaining this project. :-P

**Comment by ponychicken** [comment]
This could be nicely solved by aliasing the Junk folder to Spam: http://serverfault.com/questions/670584/dovecot-email-clients-and-duplicated-folders

**Comment by feketevarazslo** [comment]
I agree with the original poster. The server should default to follow applicable IETF RFCs where possible. It is not reasonable to suggest "to survey all of the common mail clients to see what they expect." Clients that deviate from IETF RFCs are the problem not the solution. This issue should be reopened IMHO.

**Comment by JoshData** [comment]
RFC 6154 does not specify what the folder should be called. The purpose of the quoted part of RFC 6154 is to allow for these folders to have any name, actually.
