### ISSUE TITLE
Use Let's Encrypt as replacement for current cert 

### ISSUE THREAD

**Issue by OmgImAlexis** [mail-in-a-box/mailinabox#689]
Is there currently anyway to force mailinabox to replace my currently SSL cert with a Let's Encrypt one?

Edit: I've also noticed that you can't use it for new domains or to replace self signed certs.

**Comment by JoshData** [comment]
you can force a new cert issuance by running

    sudo management/ssl_certificates.py _domainname_

It should work fine for new domains and it will definitely attempt to replace self-signed certs (so long as your DNS is working). Run

    sudo management/ssl_certificates.py

for details.

**Comment by OmgImAlexis** [comment]
Ah, good.

So I managed to get the replacement of manual certs working from the dash, I just had to restart the box.

**Comment by JoshData** [comment]
Not sure why, but ok. Closing.
