### ISSUE TITLE
Need option to use www.{domain} as the canonical url.

### ISSUE THREAD

**Issue by cybercode** [mail-in-a-box/mailinabox#691]
MIAB is configured to use the domain name (e.g my-domain.com) as the canonical url rather than www.my-domain.com. The long default standard (see, e.g, google.com or apple.com) is to use `www.{domain-name}` as the canonical url.

MIAB should either default to using the `www.` prefix as the default, or make this configurable.

My personal impetus for this is that i have recently moved my mail host to MIAB (mostly love it), and i believe that the new behavior is affecting access to my sites (since i had permanent redirect in the reverse direction of MAIB). 

Since there seems to be add a mail domain w/o it automatically creating the associated web domain, there is no way for me to manage this manually. This is a fairly critical issue for me and i really don't want to start over building a mail server again...

**Comment by JoshData** [comment]
Let's put preferences aside for a moment. What's the actual problem?

**Comment by cybercode** [comment]
The problem is that I have moved a some sites from a previous server, having (per internet convention) www.{domain-name} as the canonical (permanent redirect) url. Now all of a sudden they are permanent redirect to the base domain name and, among other things, google is not happy since it's indexing sees www.{domain} and {domain} separately when indexing and ranking.

Since MIAB wants to manage the website for any domain it's handing mail for, the only way to maintain my current ranking and standards is to create a second server for http, ignore the MAIB dns server and manage the domains elsewhere. This incurs a cost both in time and money, and I would prefer to host the sites on the MAIB server, but maintain my current canonical urls.

**Comment by JoshData** [comment]
I see now. You have two options:

a) Use the Custom DNS page to have the website hosted on another machine.

b) Add a dummy alias `whatever@www.yourdomain.com`. That'll tell the box to start serving `www.yourdomain.com` properly, not as a redirect.

**Comment by cybercode** [comment]
> b) Add a dummy alias whatever@www.yourdomain.com. That'll tell the box to start serving www.yourdomain.com properly, not as a redirect.

But then it will server BOTH `www.yourdomain.com` and `yourdomain.com`, which is exactly what canonical urls are supposed to avoid. Doing that, the only way to make it work is an empty index.html w/ a meta refresh, an awful solution.

I do like the way MIAB is setup for managing mail (imap, greylisting, etc). I don't really understand why it needs to be a (opinionated) web server and file/dav server as well. I truly wish there was a way to turn-off owncloud (which i see as something of a security hole) and manage website manually, leaving mail-in-a-box as just that --- a mail server.

**Comment by JoshData** [comment]
There's a hidden feature to add redirects, see #608.

> I don't really understand why it needs to be a (opinionated) web server

You're the one coming with the opinion about what domain should be canonical.

The web server is there as a bonus, if it's useful. If you don't like how it serves web, use your own server (per option (a) above), just as you would if Mail-in-a-Box hadn't existed. This isn't a web server project.

**Comment by TabTwo** [comment]
I'm also no a fan of naked domains.
Hosting www elsewhere makes it pretty impossible to use dane for it.
Also, here are some arguments for www: http://www.yes-www.org/why-use-www/
