### ISSUE TITLE
New TLDs showing "not a valid email address"

### ISSUE THREAD

**Issue by cdmackie** [mail-in-a-box/mailinabox#694]
Using v0.16.

First stage of setup, entering an email address with "something@smith.family" says "That's not a valid email address".

**Comment by JoshData** [comment]
We don't check the TLD against a list, so it must be something else.

**Comment by cdmackie** [comment]
Ok, thanks, yes domain was a red herring. The setup window has the field for email but it has inserted spaces before you type the email address. You have to backspace all the spaces out before typing. Maybe it could not do that or trim the email before validating.

**Comment by mirzalazuardi** [comment]
i'm using the "com" TLD. but it said not a valid email address. i'm using mirza@hyena-agency.com . anyone can help me bout this issue?
