### ISSUE TITLE
Error when provisioning cert with letsencrypt v0.16

### ISSUE THREAD

**Issue by qhrizz** [mail-in-a-box/mailinabox#695]
Hi! Just tried to provision a certificate with letsencrypt in MIAB 0.16 but after the "finish" button turns green I get the error message: "Error - Something went wrong, sorry." 

Is there a log where I can see what went wrong? Did I miss something?

Best regards
Christian

**Comment by JoshData** [comment]
`/var/log/syslog` should have something.

**Comment by qhrizz** [comment]
Thank you for your response JoshData, I tried to trigger the provisioning again while doing tail -f /var/log/syslog but all I see in the log are imap logins from my iPhone. 

Is there a flag I can reset so the "letsencrypt-provisioningscript" starts over from scratch? Or is reinstall the only way to go?

**Comment by cmsirbu** [comment]
I did have that same error message and it happened because I was blocking ports 80/443 on my box (my personal choice) and the ACME client failed the verification of domain ownership.

**Comment by JoshData** [comment]
@qhrizz Do you still get the error when you hit the button? I'd really like to figure that out before you reset things.

**Comment by qhrizz** [comment]
@cmsirbu I checked port 80 and 443, both open . Where is the ssl-certificate.py located?

@JoshData Yes, the problem still exists, unfortunately. Would it help if you gained access to the box? The mailserver is not critical, it is just for my internal servers to send statusmail to when they restart and stuff.

**Comment by JoshData** [comment]
That's the fastest. Can you add my public key?

    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy8tbNlXDjeFmFe5Gv5dZQIFXxY76oI5dBGrtFwf98GItMAnxJnZz3ZEh6N/CwGrtbOErORG8dwNzQg2yH5Xnfz64AZ3+60QBO87Ahsod4ng9DgybkO0kcmAeW1delJQGu8D2Z8CexX6KeClDBIygPU0fzoQQsg6Gxt7Jhg6bDz1co5U1TsOIaorc6rFaN9SmBl5TJUrczXLPvGo2D7czpdUfX0Vc/Ks2R4VM7TrXl4/tv43YoepxAx00SpGbm1r8a0K3vlkpQm7zDcZ8ywUyNUGIRc0TOhqlyqHGnBonesprnoxhp7VGIFeWERiDrJQxqXJ66+GnyOemY78ENj03J joshdata

**Comment by qhrizz** [comment]
@JoshData I sent you an email last week with the details - did you receive it?

**Comment by JoshData** [comment]
Just been very busy, sorry...

**Comment by rainulf** [comment]
I also got similar issue. The first domain I provisioned SSL on worked just fine. After that, I updated the NS of my second domain, and then attempted to provision SSL for that as well - I get the something went wrong message.

    Feb 15 14:48:11 mail Exception on /ssl/provision [POST]#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012    raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/usr/local/bin/mailinabox-daemon", line 57, in newview#012    return viewfunc(*args, **kwargs)#012  File "/usr/local/bin/mailinabox-daemon", line 383, in ssl_provision_certs#012    jsonable=True)#012  File "/root/mailinabox/management/ssl_certificates.py", line 323, in provision_certificates#012    logger=my_logger)#012  File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 80, in issue_certificate#012    challg = submit_domain_validation(client, regr, account, challenges_file, domain, validation_method, logger)#012  File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 376, in submit_domain_validation#012    raise ChallengeFailed(validation_method, domain, message, challg1.uri)#012free_tls_certificates.client.ChallengeFailed: The HTTP Validation challenge for domain.com failed: DNS problem: query timed out looking up A for domain.com.

... where domain.com is one of many domains I have that I want to provision SSL on. It could be related to this issue: https://github.com/letsencrypt/letsencrypt/issues/1610

I suspect that the records were just not up to date yet (it hasn't been 48-hours after all). I'll try maybe later today or tomorrow, although I will have to workaround the disabled Provision button as it stays disabled...

**Comment by JoshData** [comment]
Nice catch. Fix committed. Hopefully that solves the original issue too.

**Comment by rainulf** [comment]
Hi @JoshData ! 

1ba44b0 shows that error message now, and it also fixes the unresponsive Provision button. But it still prevented me from provisioning SSL even though my newly updated NS is propagated properly. 

After further investigation, `/home/user-data/ssl/lets_encrypt/challenges.json` seemed to have "cache" the invalid DNS lookup - domain status remained "invalid" (see [this](https://gist.github.com/rainulf/71932988a460f7181cc0)). So I removed it for science (although now that I think about it, changing it to "pending" would probably be suffice). Now, it generates SSL properly. 

Now, I'm not familiar with Let's Encrypt, but I assume that file was keeping track of cert expirations and other info... So the `challenges.json` for my other domains are lost. I assume it will have issue when it tries to regenerate new cert again haha

**Comment by JoshData** [comment]
I'll have to look closer, but deleting the lets_encrypt directory is totally safe. It's nice to keep around in principle but in practice doesn't mean much, probably.

**Comment by JoshData** [comment]
Perfect diagnosis. Fixed at https://github.com/mail-in-a-box/free_tls_certificates/commit/45fb07f90881dfc7fb16c147d97acab1809dc182 and the commit here upgrades that library on next setup.
