### ISSUE TITLE
Timezone issue with reported backups

### ISSUE THREAD

**Issue by kurt89523** [mail-in-a-box/mailinabox#700]
Hello,

I have a fresh installation of mailinabox, and set my timezone as America/Los_Angeles (PST) during install. When looking at the backups listed within the admin panel, it was reporting that a backup was performed at 11:00 PST. This reported time was many hours in the future. When I checked the last modified time of the backup files within the SSH terminal, the backup was listed as 3:00, which is correct. Since the time difference between UTC and PST is 8 hours, it appears that the admin panel is assuming that the system time is UTC, adding 8 hours to correct to PST.  Since the system time is already set for PST, the admin panel is adding another 8 hours, incorrectly reporting PST 8 hours into the future. 

Thank you.

**Comment by kurt89523** [comment]
Please note that I did not modify any time settings. I just selected the time zone as prompted during mailinabox install.

**Comment by JoshData** [comment]
Fixed, thanks.
