### ISSUE TITLE
v0.16 fresh installation fails with "checksum did not match" message

### ISSUE THREAD

**Issue by ZitRos** [mail-in-a-box/mailinabox#701]
The issue is as it described [here](https://discourse.mailinabox.email/t/roundcube-checksum-mismatch/1040):

```
wget -O - https://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.3/roundcubemail-1.1.3.tar.gz | sha1sum
```
returns `ea60df615387f47bdfdfe4da48f6567c4ec60f74`, but installer expects `4513227bd64eb8564f056817341b1dfe478e215e`. Seems like roundcubemail changed the file under this URL, but mailinabox wasn't aware of this.

Is there any beautiful ways to fix this?

Thanks!

P.S. Complete installer's output:
```
Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of https://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.3/roundcubemail-1.1.3.tar.gz did not match expected checksum.
Found:
ea60df615387f47bdfdfe4da48f6567c4ec60f74  /tmp/roundcube.tgz

Expected:
4513227bd64eb8564f056817341b1dfe478e215e  /tmp/roundcube.tgz
```

**Comment by aspdye** [comment]
Any official Reference by Roundcube. I think we should maybe ship our own Roundcube Packages, so that we have Control over such stuff :wink:

**Comment by ZitRos** [comment]
Good idea to mirror the installers on any server to make sure they never change.

Anyway, could you suggest any fast workaround to fix this and install MailInABox?

**Comment by JoshData** [comment]
Please just try it again --- the download hasn't been modified (the checksum still matches for me). It might have been a temporary Sourceforge issue.

**Comment by ZitRos** [comment]
Joshua, you're right - it was a temporary issue.

That time I tried several times, but it came up with no result, and now, when I tried one more time everything were installed properly.

Thanks for your help!
