### ISSUE TITLE
Custom SpamAssassin score

### ISSUE THREAD

**Issue by jabbink** [mail-in-a-box/mailinabox#703]
I currently have a problem where lots of spam reaches my inbox with a score of 4.9/5.0 for spam assassin with both the `BAYES_99` and `BAYES_999` trigger. The manpages for spamassassin tell me that I can overwrite scores (I wanted to set `BAYES_999` to >10) by creating a file called `~/.spamassassin/user_prefs`. I created this file in all home directories of all users, restarted `spampd`, rebooted the server, but still, these spam messages don't get a score of >= 5.0.

**Comment by JoshData** [comment]
You could try `/etc/spamassassin/local.cf`. But I really don't want to get into people modifying their boxes (unless you're going to propose that we change this for everyone), so I'm going to close this issue.
