### ISSUE TITLE
Control panel asks for login information twice

### ISSUE THREAD

**Issue by breakthecode** [mail-in-a-box/mailinabox#704]
Hi!

Fired up a box yesterday just to test if this will suite my needs, but this freaking bug is driving me away from MIAB.

Why do we need dual logins attempts on the admin page? Writing the correct password, promts do do it again, and after the second time the site let me in.

Running the setup on a brand new Ubuntu 14.04.3 LTS on DO, and I´m using Firefox 44.0.1 on my Mac Mini with El Capitan.

**Comment by aspdye** [comment]
I can confirm this :smile:

**Comment by ponychicken** [comment]
You are actually logged in already after the first try (use the menu to naviagte somewhere else). Looks like its not properly redirecting you.

**Comment by ponychicken** [comment]
More precisely it happens when miab-cp-credentials is set and miab-cp-lastpanel == login
