### ISSUE TITLE
API keys for custom dns API authentication

### ISSUE THREAD

**Issue by 0xFelix** [mail-in-a-box/mailinabox#706]
I think the custom dns API is a nice feature and I'd really like to use it, but using admin credentials to authenticate when using the API makes me feel rather uncomfortable.

I don't really like the idea of putting admin credentials for my box in a router or another possibly unsecure device.

How do you like the idea of implementing some kind of API key authentication for custom dns?

**Comment by JoshData** [comment]
DNS changes can be used to hijack your whole domain name and identity, so it's definitely an administrative-level function. You could create a separate admin account just for the DNS api, so it's not your own personal password, at least.

**Comment by anoma** [comment]
I do not currently use the API for DNS but it is on my todo list to look at as a means to replace DYNDNS.

Does this use case where the DNS is a subdmoanin host rather that a hosted site make more sense with the original request?

**Comment by JoshData** [comment]
For a known subdomain (not one arbitrarily entered by the user), it's probably safe, yes.

**Comment by 0xFelix** [comment]
@JoshData I understand your concern about second level domains, you are right.

But as anoma said, using a non-crucial and predefined subdomain would probably be the easiest and safest to implement.

Is this something you would consider for MIAB?

**Comment by JoshData** [comment]
This is similar to #393 so closing.
