### ISSUE TITLE
[Sugestion] Change OwnCloud with Radicale

### ISSUE THREAD

**Issue by mariusv** [mail-in-a-box/mailinabox#707]
Heya,

Would you consider to change OwnCloud fro contacts/calendars implementation with [Radicale](http://radicale.org/) ?

Thanks

**Comment by anoma** [comment]
Detailed debate here

https://github.com/mail-in-a-box/mailinabox/issues/514

**Comment by mariusv** [comment]
Thanks @anoma . I'll be closing this.
