### ISSUE TITLE
Notices of system memory under 30% are sent all the time

### ISSUE THREAD

**Issue by tuminoid** [mail-in-a-box/mailinabox#710]
Using MIAB 0.16 in 1GB physical memory box, I get notice of system memory status changed emails every day. Memory consumption is bouncing around 30% free regularly, and thus it gets triggered all the time. In my personal opinion, 30% free is a lot of memory and shouldn't be a trigger for sending status emails.

**Comment by dhpiggott** [comment]
I get these relatively frequently too (though not every day), on a 1GB Digital Ocean Droplet.

Screenshot of top sorting by memory use:

![screenshot from 2016-02-14 10 47 32](https://cloud.githubusercontent.com/assets/6965859/13033275/83ecaf18-d308-11e5-9427-e663419f08bb.png)

I would be in favour of reducing the threshold to 20%.

**Comment by yodax** [comment]
I don't mind changing these thresholds to 20% for the warning and 10% for the error respectively. I tried reducing the daemon pool to 5 workers, this reduces the memory allocation by 10% on a DO 1GB instance. The status checks still operate fast enough.

For the daemons see https://github.com/mail-in-a-box/mailinabox/issues/731

@JoshData shall I create a PR for 20% and 10%?

**Comment by JoshData** [comment]
OK.

**Comment by tuminoid** [comment]
:+1: Thank you.
