### ISSUE TITLE
Admin panel does not load in firefox 44 on ubuntu 15.10

### ISSUE THREAD

**Issue by gautambt** [mail-in-a-box/mailinabox#720]
Hi,

When I login to the admin panel I just see a blank screen. I am using firefox 44 on ubuntu 15.10. Firefox dev console shows these errors:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
None of the "sha256" hashes in the integrity attribute match the content of the subresource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
None of the "sha256" hashes in the integrity attribute match the content of the subresource.
Error: Bootstrap's JavaScript requires jQuery
bootstrap.min.js (line 6, col 37)
ReferenceError: $ is not defined

**Comment by JoshData** [comment]
Works for me.

**Comment by hnk** [comment]
Do you have any scripts running that might block external resources?

The admin panel loads resources from bootstrapcdn.com and ajax.googleapis.com and needs to be allowed to do that.

If I run umatrix and block access to these resources I get some of the errors you describe, though this is not an issue with mailinabox, but your configuration.

**Comment by gautambt** [comment]
Looks like this is an issue with some plugins I have installed. On a new firefox profile, the admin panel loads fine. The issue can be closed.
