### ISSUE TITLE
Please test master branch - 0.17RC

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#722]
If anyone can give the master branch a try, I'd appreciate it. I'd like to release it as 0.17 soon, as a bug fix update. Especially to fix the boto/S3 issue.

**Comment by kurt89523** [comment]
It appears that the master branch has a Roundcube checksum error during a fresh install. I restored the Digital Ocean image, checked out and installed v0.16, same issue.  Thanks!

**Comment by yodax** [comment]
I am running on the master branch for some time already. Usually update once or twice a week after verifying the commits. Fetched upstream a few moments ago with the changes of yesterday. 

I don't see the round cube issues and I am also on DO. I have been on 1.1.4 for a while.

No issues found so far.

**Comment by aspdye** [comment]
:white_check_mark: Works for me.

**Comment by kurt89523** [comment]
No Roundcube checksum error when I tried it today.

**Comment by dhpiggott** [comment]
I just updated to master, it worked fine for me. I like the intent behind 4ed23f44e6c7bb29cb08e035495a63db1195dfd6.

**Comment by yodax** [comment]
Just merged the latest commits. Will continue to use it (, of course :P).

**Comment by JoshData** [comment]
Thanks all. There have been a few additional commits, so please pull again. :)

**Comment by yodax** [comment]
Repulled and installed.

**Comment by dhpiggott** [comment]
Ditto, and it's working better than ever. Thank you @JoshData, @yodax and everyone else who has contributed since v0.16.
