### ISSUE TITLE
Where does the mail get stored?

### ISSUE THREAD

**Issue by joel-james** [mail-in-a-box/mailinabox#723]
How can I access mail-in-a-box database? I would like to create few APIs to manage mail data. How can I do that? What database you use?

**Comment by JoshData** [comment]
Mail data is managed by Dovecot. The only sensible way to access it is over IMAP or Dovecot's command-line tools (doveadm etc.).

**Comment by joel-james** [comment]
IMAP will be too slow :-1: That is why I wanted to develop an API. So no other way?

**Comment by almereyda** [comment]
Maybe you want to have a look at https://github.com/nylas/sync-engine

I suppose this issue could be renamed or closed.

**Comment by joel-james** [comment]
@almereyda But still, Nylas Sync Engine is also using IMAP to get data for RESTful API right?

**Comment by yodax** [comment]
The answer was given by @JoshData. The mail is stored in Dovecot. IMAP is Dovecot's interface or doveadm. That isn't something that was build by MIAB. 

Some Googling shows that there was an effort made by somebody; http://thevarguy.com/open-source-application-software-companies/072814/open-source-developers-promise-new-api-dovecot-email-data

The companies link seems to be offline though.

https://www.google.nl/#q=dovecot+rest+api

**Comment by almereyda** [comment]
If you prefer a more precise answer, MIAB stores all user data in the path `/home/user-data`
