### ISSUE TITLE
Opt-out for automatic renewing via Let's Encrypt

### ISSUE THREAD

**Issue by aspdye** [mail-in-a-box/mailinabox#724]
We can not just issue certificates when the user does not have used Lets Encrypt, and he may not have for a reason! We must create an option for completely removing this Let's Encrypt automatic ;)

**Comment by JoshData** [comment]
We can and we do. What's the use case?

**Comment by aspdye** [comment]
Maybe some people just don't want to use Let's Encrypt, because they want to have the control of certification issuance for the domains they are managing :grin:

**Comment by yodax** [comment]
First you have to enable let's encrypt, if you don't do that there will be no automatic renewal. I think if people don't want lets encrypt the will not go through the initial proces.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
