### ISSUE TITLE
Activesync with outlook 2013 and Iphone problem deleting

### ISSUE THREAD

**Issue by Timman70** [mail-in-a-box/mailinabox#730]
I have two problem when I setup the ActiveSync on my outlook when I delete a email it sometime it take a long time to appear in the trash.
on the Iphone it display in the trash but if I delete from the trash nothing get delete from the mailbox it only disappear until I delete more item from the inbox and it will display all the trash I delete

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
