### ISSUE TITLE
Daemon multiprocessing pool size 

### ISSUE THREAD

**Issue by yodax** [mail-in-a-box/mailinabox#731]
No rush on this question, just trying to familiarize myself more with the workings of mailinabox.

I have a question about [deamon.py line 18](https://github.com/mail-in-a-box/mailinabox/blob/master/management/daemon.py#L18)

It allocates a pool of 10 worker processes which allocate some resources.

```
pmap `pgrep mailinabox` | grep total | awk '{print $2}'

337408K
127496K
... ETC

top

PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 3295 root      20   0  127484  52136   4476 S  0.0  5.1   0:00.34 mailinabox-daem                                               
 3296 root      20   0  127544  52136   4476 S  0.0  5.1   0:00.35 mailinabox-daem                                               
 ... ETC 
```

A pmap -XX shows that only about 20mb per process is non shared memory:

```
pmap -XX 3289 | more
3289:   /usr/bin/python3 /usr/local/bin/mailinabox-daemon
         Address Perm   Offset Device   Inode   Size   Rss   Pss Shared_Clean Shared_Dirty Private_Clean Private_Dirty Referenced Anonymous AnonHugePages Swap KernelPageSize MMUPageSize Locked     
.... ETC
                                              ====== ===== ===== ============ ============ ============= ============= ========== ========= ============= ==== ============== =========== ====== 
                                              127416 51392 18410         3912        32260             0         15220      21332     47472          4096    0            712         712      0 KB 
```

- Is the size of 10 chosen for a specific reason? 
- Is my reasoning with the allocation of memory correct?
- Might it be beneficial for memory restricted systems to reduce the number of workers?

**Comment by yodax** [comment]
I ran a test on my DO 1GB droplet and reducing the pool to 5 workers doesn't seem to reduce the speed of the status checks noticeably, but it does release about 10% of the allocated memory.

**Comment by JoshData** [comment]
The status checks are multi-threaded by domain. So, 10 domains can be checked in parallel.

There's no real reason why multi-threading the checks needs 20 MB, but it might be hard to do it better without crazy Python.

**Comment by yodax** [comment]
I don't know how many domains people have on average on their MIAB. Do you think it would be a good idea to lower the default? Personally i don't mind waiting a bit longer on the status checks if that means spamd has a bit more breathing room.

Would it be a possibility to allocate the pool when the status checks are run?

I agree that it doesn't make much sense in doing it by hand.

**Comment by yodax** [comment]
I have a branch [here](https://github.com/yodax/mailinabox/tree/daemons) that I used to test the pool reduction.

**Comment by JoshData** [comment]
I did a quick check on my box. I have 26 domains (as the status checks would list them - that includes www's). A pool size of 5 is enough to get as much speed benefit as I can get:

```
pool time
1    12s
2    7.8s
5    5.3s
10   5.8s
```

We could allocate the pool on first use, and even size it dynamically depending on the number of domains, but for now let's just lower to 5.

**Comment by yodax** [comment]
Ok I will PR my branch. Good test!

**Comment by JoshData** [comment]
Fixed by the PR.
