### ISSUE TITLE
# Change to one to enable spamd ENABLED=0

### ISSUE THREAD

**Issue by laapsaap** [mail-in-a-box/mailinabox#740]
Hi,
I was wondering why I was getting port 10025 errors and I saw spamassassin was not running. When I tried to start it manually, I see this;

# /etc/default/spamassassin

# Change to one to enable spamd
ENABLED=0

This is a clean ubuntu 14.04 install and first thing I did after logging in was the install mailinabox cmd.

**Comment by JoshData** [comment]
The daemon is spampd, not spamassassin.

**Comment by laapsaap** [comment]
Ok, I found that out too. Spampd didnt start.

pyzor: check failed: util: cannot fork: Can't fork: Cannot allocate memory at /usr/share/perl5/Mail/SpamAssassin/Util.pm line 1520. at /usr/share/perl5/Mail/SpamAssassin/Util.pm line 1523.

It worked after a reboot, oh well.  Thanks!
