### ISSUE TITLE
issues in own cloud

### ISSUE THREAD

**Issue by laupkram** [mail-in-a-box/mailinabox#741]
I got the error below when installing MiaB when getting stucked for too long installing OwnCloud

`fatal: reference is not a tree: <then a random hash code>`

is there any way I can install MiaB without OwnCloud? if MiaB needs it, is there any workarounds?

**Comment by x1h32s** [comment]
I also experience this error today both on latest and lower version(v0.15 and v0.16)
`fatal: reference is not a tree: 4ff855e7c2075309041bead09fbb9eb7df678244`.

**Comment by yodax** [comment]
I have tried this as wel on a fresh machine. It is this line:

[Line 55 in own cloud.sh](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/owncloud.sh#L55)

It seems that they have changed the repo to prepare for 9.0. Simply picking up the latest hash won't work, also they advertise that it shouldn't be used in production... I can't verify this, but it looks like the repo was reloaded with a new history.

**Comment by JoshData** [comment]
Once again they mess up our deployment.

Fix coming....

**Comment by x1h32s** [comment]
@yodax : I did try changing the hash on [Line 55 in own cloud.sh](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/owncloud.sh#L55) with the latest commit history and as expected it did not work both on latest and lower version.

**Comment by JoshData** [comment]
Fixed and a new release is posted with this change.

**Comment by yodax** [comment]
I was searching for the old repo, couldn't find it. Must be blind, seeing you found it :smile:

**Comment by JoshData** [comment]
I got lucky - I searched github for the broken commit hash:

https://github.com/search?q=4ff855e7c2075309041bead09fbb9eb7df678244&type=Issues&utf8=%E2%9C%93
