### ISSUE TITLE
Custom storage_root * improvement

### ISSUE THREAD

**Issue by c0h1b4** [mail-in-a-box/mailinabox#742]
A custom STORAGE_ROOT would be great. If we use different drives to store the mailboxes, perhaps the config could ask for a different STORAGE_ROOT...

Thanks.

**Comment by JoshData** [comment]
You can change STORAGE_ROOT by setting a STORAGE_ROOT environment variable prior to running Mail-in-a-Box setup.

**Comment by victorlap** [comment]
I think this issue can be closed, seeing it has now been documented.
