### ISSUE TITLE
Add pflogsumm  

### ISSUE THREAD

**Issue by badsyntax** [mail-in-a-box/mailinabox#746]
Initial discussion: https://discourse.mailinabox.email/t/pflogsumm-is-very-helpful-perhaps-consider-using-it-yourself/1133

From http://manpages.ubuntu.com/manpages/trusty/man1/pflogsumm.1.html

> Pflogsumm is a log analyzer/summarizer for the Postfix MTA.  It is designed to provide an over-view of Postfix activity, with just enough detail to give the administrator a "heads up" for potential trouble spots.

Consider including pflogsumm in mailinabox, as it's a useful tool that can be used to discover issues that the default status checks do not. 

Daily summaries can be sent (via cron) to the box administrator's email address. 

An example cron entry:

```
@daily /usr/sbin/pflogsumm -d yesterday --problems --verbose_msg_detail /var/log/mail.log | mail -s "Mail-In-A-Box: Yesterday's mail activity" admin@box.example.com
```

**Comment by JoshData** [comment]
I took a look at this and didn't find the output helpful, so I don't think this is going to be usable by novices. Experts can figure out how to install it on their own.
