### ISSUE TITLE
Harden TLS SMTP configuration

### ISSUE THREAD

**Issue by gordon-** [mail-in-a-box/mailinabox#747]
MIAB is pretty good at configuring ciphersuites for Nginx, resulting in [A+ score](https://www.ssllabs.com/ssltest/analyze.html?d=bleu-de-laqueuille.opchee.se) in [Qualys SSLLabs](https://www.ssllabs.com) (however, [other checks](https://tls.imirhil.fr/https/bleu-de-laqueuille.opchee.se) shows weaknesses, especially on 3DES support).

But for SMTPS security, there is some [serious configuration problems](https://tls.imirhil.fr/smtp/mailinabox.email): deprecated and dangerous ciphers (MD5, RC4, SSLv3).

We should review Postfix TLS configuration to enhance security.

**Comment by JoshData** [comment]
dup of #611
