### ISSUE TITLE
ERROR: '/etc/ufw/ufw.conf' is not writable

### ISSUE THREAD

**Issue by henningwerner** [mail-in-a-box/mailinabox#753]
```BASH
ERROR: '/etc/ufw/ufw.conf' is not writable
open: Read-only file system
setup/functions.sh: line 9: $OUTPUT: ambiguous redirect

FAILED: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install bind9 resolvconf
```

Got following error during runtime.
I want to run Mail-In-A-Box on my Scaleway C1 Server.

**Comment by yodax** [comment]
I am currently working on a pull request for support for scaleway C2 VPS. This didn't come up, there were fixes required for ufw in general. 

It seems that on C1 /etc is mounted ro. Could you (doing this from memory) cat /proc/mounts or just type mount

**Comment by comvice** [comment]
@yodax I don't think it's read-only because I can manually edit those files.

I now followed this Gist:

> Apply ufw/nbd fix for Scaleway
> 
> Fix found in this thread: https://community.scaleway.com/t/problems-with-ufw-on-a-fresh-ubuntu/1016
> Further information in this thread: https://community.scaleway.com/t/how-to-configures-iptables-with-input-rules-with-dynamic-nbd/303/21
> Start with a root shell, and install ufw:
> 
>  apt-get install ufw -y
> And then edit /etc/default/ufw:
> 
>  DEFAULT_INPUT_POLICY="ACCEPT" -- change from DROP to ACCEPT
>  IPV6='no' -- change from yes to no
> Edit /etc/ufw/after.rules, add this line just before the final COMMIT line:
> 
>  -A ufw-reject-input -j DROP
>  # don't delete the 'COMMIT' line or these rules won't be processed
>  COMMIT
> Currently, ufw logging causes issues with Scaleway's default kernel.
> 
>  ufw logging off
> Finish ufw setup and turn on the firewall.
> 
>  ufw allow ssh
>  ufw enable
> Clone the Mailinabox repository and cd into the newly created mailinabox directory.
> 
> git clone https://github.com/schade/mailinabox.git
> cd mailinabox
> For the initial installer run you will need to disable the firewall portion of the Mailinabox installer and run setup as you normally would.
> 
> This does not actually disable the running firewall, it just causes Mailinabox to skip over the firewall geneartion rules without changing them. Subsequent runs of sudo mailinabox do not require prepending DISABLE_FIREWALL=1 to work properly.
> DISABLE_FIREWALL=1 ./setup/start.sh
> After much trial and error - including a three and a half hour DH Parameter Generation phase - mailinabox is serving my email and I have deleted my Google Apps for Work subscription for my domain.

I don't clone from his Git Repo, I use the original files, but installing ufw manually and edit the files above. Also I run the setup up with `DISABLE_FIREWALL=1` 

Source: [https://gist.github.com/schade/57b733a3acb546560900](https://gist.github.com/schade/57b733a3acb546560900)
Actually it is creating the DH parameters, but I don't know if these steps are really makes sense.

**Comment by yodax** [comment]
This https://github.com/yodax/mailinabox/tree/scaleway does all of that and I am testing that now on DO and vultr to make sure it doesn't break on those boxes. Branch is up to date with master.

Some of the gist isn't necessary: 

- -A ufw-reject-input -j DROP
- ufw logging off

**Comment by comvice** [comment]
> does all of that
What do you mean with that? @yodax 

Good to know, so I will turn it back on and remove the line, right?

**Comment by yodax** [comment]
Yes, that works on my C2. Should be the same for the C1 I think.

I am working on a branch that will have these changes in so you can install without modifications. (Pending approval from the maintainer of course)

**Comment by comvice** [comment]
@yodax I will give it a try.
But how can I start with a clean image?
Or what do you recommend to me?

**Comment by yodax** [comment]
The lines aren't that important, if it works I would leave it. :)

**Comment by comvice** [comment]
After the lines above the setup interrupts or get canceled. Is this the full setup?
Or what lines should be visible after complete setup?

**Comment by yodax** [comment]
What do you mean with full setup? Did you remove the lines in /etc/default/ufw?

**Comment by comvice** [comment]
I mean the complete setup.
Which lines you mean?

I don't think the setup is complete, so my question is how could I use yours?
If it is complete I should have services like nginx, postfix, dovecot - there are no of them.
I'm not familiar with Scaleway, this is my first Server from there.

**Comment by yodax** [comment]
The C1 is ARM based, that is not for the feint of hearth. Try the C2 VPS same cost only x86 based. If you clone my branch you can install. However @joshdata has brought up some good code review remarks that should be fixed. 

So you could try the normal approach as outlined on the website but read through my pull request (referenced above). If that is too technical it might be best to wait for me to fix the remaining issues. Or try a different provider.

**Comment by yodax** [comment]
Also beware that if you clone my branch you need to know how to revert back to a different remote. If this doesn't mean anything to you it might be best not to attempt it if you want to use this for a production server.

**Comment by comvice** [comment]
@yodax but with the VPS I cannot add additional storage.

So you recommend me to wait until @JoshData merge your changes?

#offtopic how can I reinstall the Scaleway server?

**Comment by yodax** [comment]
I think I might have mislead you, I saw you where installing on a ARM C1 and assumed you were aware of the unsupported nature of the platform. That said, there are people who have got it running. 

My branch will do only a part of supporting Scaleway. It will not tackle the ARM specific part. The problem with the ARM part are some custom x86 build packages we rely on. See [this](https://discourse.mailinabox.email/t/armhf-builds-of-dovecot-lucene-and-postgrey/837/12) topic on the forum for more detail. So if you are willing to go that route, you might as well tackle the UFW stuff as well.

> #offtopic how can I reinstall the Scaleway server?

Regarding that, I am not sure. I always deallocate the server and reassign the IP. Perhaps their support department has a better way. (I found them to be very responsive)

**Comment by comvice** [comment]
@yodax I seem to get it nearly running but I got following error two times during runtime:
> sudo: unable to resolve host scw-2ce21b

Yes, this the hostname from the Scaleway machine, should this be the public domain?
Or what should the local hostname be like?

**Comment by yodax** [comment]
Yes this should be the public domain. You need to do [line 24, 25 and 26](https://github.com/yodax/mailinabox/blob/scaleway/setup/system.sh#L24) from my branch to solve that. Make sure you substitute $PRIMARY_HOSTNAME with your hostname. (Or just set the variable, or load the vars from the miab config)

That sets the host name properly, sudo needs a proper hostname to resolve. At the very least it should be equal in /etc/hosts as the hostname from scaleway.

**Comment by comvice** [comment]
Thanks for your fast response @yodax 
I'm no going to reinstall my instance because I got following error:

```BASH
FAILED: pip3 install email_validator>=1.0.0
-----------------------------------------
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
```

**Comment by comvice** [comment]
@yodax so now I have a fresh installation of the Scaleway C1 server.
Which steps I need to perform a working install?

If I following the steps from @schade it might should work?
https://gist.github.com/schade/57b733a3acb546560900

But with one difference I would use the files from the original Git Repo and remove the lucene references as mention in the Gist.

After the installation I would do following:
https://discourse.mailinabox.email/t/armhf-builds-of-dovecot-lucene-and-postgrey/837/12

Are this the right steps?

**Comment by yodax** [comment]
I have never completed an install on a C1 server, gave it a go once. So I can't answer that. Keep in mind though it is unsupported and every upgrade you would have to reapply your _own_ patches. These are the gists of people who have got it working.

Regarding the hostname; I answered that above:

> You need to do [line 24, 25 and 26](https://github.com/yodax/mailinabox/blob/scaleway/setup/system.sh#L24) from my branch to solve that. 

It should indeed be box.domain.tld. 

However if this is all new to you you might be better of going with one of the supported providers first and see how a properly working system is configured. Then try the C1. That is pretty advanced without a working reference frame.

**Comment by comvice** [comment]
@yodax I seem to get it working but I cannot reach the Web interface.

Here to output from the installation:
```BASH
Primary Hostname: box.domain.tld
Public IP Address: Censored
Private IP Address: 10.1.6.142
Mail-in-a-Box Version:  v0.17b

Updating system packages...
Installing system packages...

Current default time zone: 'Europe/Berlin'
Local time is now:      Sun Mar 13 14:18:35 CET 2016.
Universal Time is now:  Sun Mar 13 13:18:35 UTC 2016.

Initializing system random number generator...
Archiving old resolv.conf (was /etc/resolvconf/resolv.conf.d/original, now /etc/resolvconf/resolv.conf.original).
Creating initial SSL certificate and perfect forward secrecy Diffie-Hellman parameters...
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
........+................................................................................+.+................................+......+..........................+.......................+................................++*++*
Installing nsd (DNS server)...
Generating DNSSEC signing keys...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Creating new user database: /home/user-data/mail/users.sqlite
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing ownCloud (contacts/calendar)...
creating sqlite db
ownCloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
updated DNS: box.domain.tld
web updated
No domains hosted on this box need a new TLS certificate at this time.

Okay. I'm about to set up comvice@domain.tld for you. This account will also
have access to the box's control panel.
password:
 (again):
mail user added
updated DNS: domain.tld
web updated

-----------------------------------------------

Your Mail-in-a-Box is running.

Please log in to the control panel for further instructions at:

https://CENSORED/admin

You will be alerted that the website has an invalid certificate. Check that
the certificate fingerprint matches:

A4:34:B0:33:1D:AD:3B:8E:D0:53:39:56:55:90:9F:88:34:97:95:D2

Then you can confirm the security exception and continue.
```

But Chrome says to me `ERR_TIMED_OUT`
Security group also set and applied to the C1:
https://puu.sh/nEZTm/91a65c1e32.png

**Comment by yodax** [comment]
Did you try a hard reset from the console? Is required for a firewall change on scaleway.

**Comment by comvice** [comment]
Do you mean hard-reboot from the Scaleway webinterface?
Or an simple `reboot` from the Terminal (SSH)?

**Comment by yodax** [comment]
Via the web interface.

**Comment by comvice** [comment]
@yodax now I got following in Chrome `ERR_CONNECTION_CLOSED`

Can I provide you any helpful logs?

**Comment by comvice** [comment]
After disabling it runs fine, but how should I set up a working UFW installation?

**Comment by yodax** [comment]
Ufw isn't absolutely necessary if you have configured the scaleway firewall. However keep in mind that the fail2ban service can't block brute force attacks on the service. So use at your own risk and determine if that is a risk to your setup.

**Comment by comvice** [comment]
Yes thats cleary not a good solution, but how should I configure it?

**Comment by yodax** [comment]
That is the nice thing about an unsupported platform, you get to figure it out your self. :smile: I don't know if anyone has done that yet.

You could stat by looking here at my x86 solution to the scaleway UFW setup: https://github.com/yodax/mailinabox/blob/scaleway/setup/system.sh#L184

**Comment by comvice** [comment]
First you say ufw isn't necessary and now it is necessary?
I already set ufw ssh allow but this is only for ssh?
And how to configure the jails for the other services, with banning?

**Comment by yodax** [comment]
> First you say ufw isn't necessary and now it is necessary?

I said it was a risk you would have to asses, I can't determine what your threat model is. I pointed to the starting point for the ufw setup.

This is an unsupported platform, you are going to have to do some digging yourself.

**Comment by comvice** [comment]
@yodax i've planned to managed an update/upgrade to the newest version of MIAB.

Can I perform the update with following command:
`curl -s https://mailinabox.email/setup.sh | sudo bash`

Or should I need additional parameters on my *custom* build?
Something like `DISABLE_FIREWALL=1`

**Comment by yodax** [comment]
If you have a custom build, you will have to recustomize after updating from github. Refetching the installer will undo the customizations. Alternatively you can fetch the updates and resolve the merge conflicts. Again; these are the perils of running an unsupported platform and release.
