### ISSUE TITLE
`service spampd restart` fails

### ISSUE THREAD

**Issue by frootmig** [mail-in-a-box/mailinabox#781]
Mail-in-a-Box Version:  v0.17c

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...

FAILED: service spampd restart
-----------------------------------------
Stopping spam checking proxy daemon: spampd No /usr/bin/perl found running; none killed.
   ...fail!
-----------------------------------------

spampd is running before the upgrade

**Comment by yodax** [comment]
It seems there is no perl on your system. Which is weird. Should be unrelated to the upgrade. 

Could you try '''which perl'''

**Comment by JoshData** [comment]
Also just try setup again. 

On April 1, 2016 9:25:58 AM CDT, Michael Kroes <notifications@github.com> wrote:
>It seems there is no perl on your system. Which is weird. Should be
>unrelated to the upgrade. 
>
>Could you try '''which perl'''
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/781#issuecomment-204416236

-- 
Josh Tauberer (@JoshData) 

// Sent from my phone.

**Comment by frootmig** [comment]
Perl is there:

which perl
/usr/bin/perl

I already retried the upgrade. Error is permanent.

**Comment by frootmig** [comment]
root@box:/# service spampd stop
Stopping spam checking proxy daemon: spampd No /usr/bin/perl found running; none killed.
   ...fail!
root@box:/# ps aux | grep perl
root      2338  0.0  0.0   8812   764 pts/3    S+   16:41   0:00 grep --color=auto perl
spampd   18018  0.0  3.3 158752 69276 ?        Ss   Mar01   0:26 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500
spampd   18021  0.0  3.2 158752 68468 ?        S    Mar01   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500
spampd   18022  0.0  3.2 158752 68468 ?        S    Mar01   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500
spampd   18023  0.0  3.3 159956 71072 ?        S    Mar01   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500
root     18851  0.0  0.5  51020 10568 ?        Ss   Mar01   2:33 /usr/bin/perl -wT /usr/sbin/munin-node

**Comment by yodax** [comment]
Could you try a reboot and then see if the service is running?

**Comment by frootmig** [comment]
root@box:/# w                                                                                
 16:46:02 up 0 min,  0 users,  load average: 0.24, 0.05, 0.02                                
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT                          
root@box:/# ps aux | grep perl                                                               
root       653  0.0  0.5  51000 10572 ?        Ss   16:45   0:00 /usr/bin/perl -wT /usr/sbin/munin-node                                                                                   
spampd    1325  0.0  3.2 156664 68800 ?        Ss   16:46   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500     
spampd    1326  0.0  3.2 156664 67596 ?        S    16:46   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500     
spampd    1327  0.0  3.2 156664 67596 ?        S    16:46   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500
spampd    1328  0.0  3.2 156664 67720 ?        S    16:46   0:00 /usr/bin/perl -T /usr/sbin/spampd --tagall --port=10025 --host=127.0.0.1 --relayport=10026 --relayhost=127.0.0.1 --pid=/var/run/spampd.pid --children=3 --user=spampd --group=spampd --logsock=unix --maxsize=500
root      1353  0.0  0.0   8816   888 pts/1    S+   16:46   0:00 grep --color=auto perl

**Comment by frootmig** [comment]
root@box:/# service spampd stop
Stopping spam checking proxy daemon: spampd    ...done.
root@box:/# service spampd start
 * Starting spam checking proxy daemon spampd
   ...done.

-> Will retry upgrade now

**Comment by yodax** [comment]
What does service spampd status say? Did you retry the setup? If you retry could you also tail syslog?

**Comment by frootmig** [comment]
Upgrade worked after rebooting the box, beside this error:

[FATAL ERROR] Lock already exists: /var/run/munin/munin-update.lock. Dying.
 at /usr/share/perl5/Munin/Master/Update.pm line 128.

Munin uses perl, too.

Wired. Don't know what caused the problem.

**Comment by frootmig** [comment]
The status is now running:

root@box:~# service spampd status
 * /usr/sbin/spampd is running as 3021

**Comment by yodax** [comment]
The munin is a known issue. Doesn't affect the working of the box. 

So once again the computer equivalent of kicking the tires worked, rebooting. So unsatisfactory.

**Comment by frootmig** [comment]
The syslog only showed up this:

spampd[1693]: Couldn't unlink "/var/run/spampd.pid" [Permission denied]

**Comment by JoshData** [comment]
This has been reported before but I couldn't find the report. I think spampd is just dying.

**Comment by MasterPCUK** [comment]
Hi,  I updated miab to. 17c without any problems..
