### ISSUE TITLE
Upgrade to 17c Fails

### ISSUE THREAD

**Issue by murf0** [mail-in-a-box/mailinabox#782]
```
Installing Munin (system monitoring)...
'EntryPoint' object has no attribute 'resolve'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
  File "management/ssl_certificates.py", line 793, in <module>
    provision_certificates_cmdline()
  File "management/ssl_certificates.py", line 436, in provision_certificates_cmdline
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "management/ssl_certificates.py", line 264, in provision_certificates
    domains, problems = get_certificates_to_provision(env, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "management/ssl_certificates.py", line 173, in get_certificates_to_provision
    certs = get_ssl_certificates(env)
  File "management/ssl_certificates.py", line 47, in get_ssl_certificates
    pem = load_pem(load_cert_chain(fn)[0])
  File "management/ssl_certificates.py", line 753, in load_pem
    return load_pem_x509_certificate(pem, default_backend())
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 21, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```
Tried removing SSL directory and reinstall. No luck, same as before

**Comment by murf0** [comment]
I'm suspecting that have an old version of setuptools however it's installed via apt-get install python3-setuptools so no luck upgrading... (already latest version via apt-get)

**Comment by murf0** [comment]
Solved.
* Remove the ubuntu package: sudo apt-get remove python3-pip
* Download official pip installer: wget https://bootstrap.pypa.io/get-pip.py
* Install pip by running downloaded installer: sudo python3 get-pip.py
* Rerun the installer curl -s https://mailinabox.email/setup.sh | sudo bash

**Comment by JoshData** [comment]
Also at https://discourse.mailinabox.email/t/python-error-while-installing/1159.

Replacing the installation of `pip` is probably not the right way to solve this. Upgrading one of the Python modules might fix it (`sudo pip3 install --upgrade cryptography`). (I investigated this issue previously but I can't remember where.)

**Comment by murf0** [comment]
I Agree, However the issue is not `cryptography` being old. It is that `setuptools` are of an old version which are incompatible with `cryptography` newer versions, `pip` refuses to upgrade system installed `setuptools`.
Hence the total destruction and replacing the system `pip`
Ubuntu 14.04 standard sources.
