### ISSUE TITLE
Idea: Prosody-Module

### ISSUE THREAD

**Issue by TabTwo** [mail-in-a-box/mailinabox#783]
I know, miab is a mailserver project and I realy like the "one toll - one job" way.
But, for me it would make sense to have a module/howto to integrate the Prosody XMPP Server with miab.
Prosdy could use a lot from the miab infrastructure on the host like 
- all the DNSSEC stuff with keyrollover/DANE
- the certificate stuff + reneval with letsencrypt
- userdb

Anyone want to join me for for brainstorming? The goal is to have every miab user to have a xmpp-account automatically.

**Comment by JoshData** [comment]
I don't have time to maintain a project that has more features than Mail-in-a-Box already does. 

On April 2, 2016 6:11:32 AM CDT, "Ralph J.Mayer" <notifications@github.com> wrote:
>I know, miab is a mailserver project and I realy like the "one toll -
>one job" way.
>But, for me it would make sense to have a module/howto to integrate the
>Prosody XMPP Server with miab.
>Prosdy could use a lot from the miab infrastructure on the host like 
>- all the DNSSEC stuff with keyrollover/DANE
>- the certificate stuff + reneval with letsencrypt
>- userdb
>
>Anyone want to join me for for brainstorming? The goal is to have every
>miab user to have a xmpp-account automatically.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/783

-- 
Josh Tauberer (@JoshData) 

// Sent from my phone.

**Comment by TabTwo** [comment]
I want to keep the impact to miab itself as low as possible plus I am really thankful for all the time you spend on miab.
The idea ist to interact with miab through defined interfaces like the one thats already there for DNS.
And maybe there are little changes required like starting the dovecot auth daemon to use that with mod_auth_dovecot from prosody.

**Comment by JoshData** [comment]
Can you try it as a separate project? If it works without requiring changes here, we can just link to your instructions.

On April 3, 2016 4:04:03 AM CDT, "Ralph J.Mayer" <notifications@github.com> wrote:
>I want to keep the impact to miab itself as low as possible plus I am
>really thankful for all the time you spend on miab.
>The idea ist to interact with miab through defined interfaces like the
>one thats already there for DNS.
>And maybe there are little changes required like starting the dovecot
>auth daemon to use that with mod_auth_dovecot from prosody.
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/783#issuecomment-204922407

-- 
Josh Tauberer (@JoshData) 

// Sent from my phone.
