### ISSUE TITLE
how to change template control panel?

### ISSUE THREAD

**Issue by bijism** [mail-in-a-box/mailinabox#784]
hi my friends 

How do I use this template?
these templates are currently available?

![image](https://cloud.githubusercontent.com/assets/5095139/14231037/aa02a972-f988-11e5-81e8-b500c8c90fb9.png)

or 

![image](https://cloud.githubusercontent.com/assets/5095139/14231041/ba1034ec-f988-11e5-91fd-6a325265d0cd.png)

**Comment by JoshData** [comment]
These were things some users were playing with. There's no (supported) way to configure the theme. 

On April 3, 2016 1:12:50 AM CDT, bijism <notifications@github.com> wrote:
>hi my friends 
>
>How do I use this template?
>these templates are currently available?
>
>![image](https://cloud.githubusercontent.com/assets/5095139/14231037/aa02a972-f988-11e5-81e8-b500c8c90fb9.png)
>
>or 
>
>![image](https://cloud.githubusercontent.com/assets/5095139/14231041/ba1034ec-f988-11e5-91fd-6a325265d0cd.png)
>
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/784

-- 
Josh Tauberer (@JoshData) 

// Sent from my phone.
