### ISSUE TITLE
Stop postfix from trying to send locally for certain domains/accounts

### ISSUE THREAD

**Issue by dieideeistgut** [mail-in-a-box/mailinabox#788]
Hello,

i have the following problem: I have set up Domains via Custom DNS where i don't do the mailing for. I just use the custom DNS to setup A, AAAA and MX records - pointing to other servers. I know this is not the intended use of MIAB but for some small domains i thought this would be doable as i don't want to run another NS just to do so. Now to the issue:

While mailing is working perfectly on all domains / accounts / sites i can't write from a miab-account to a custom DNS domain i set up. I assume Postifx is quitting this with `Recipient address rejected: User unknown in virtual mailbox table`. Logically i assume it is trying to reach the local user for this domain to deliver locally - but there is no user in the system.

Is there a way to tell Postfix (in our miab-environment) to treat domains as external ones? I tried to find a workarround with `virtual_alias_maps` and such - but i didn't succeeed.

**Comment by JoshData** [comment]
You might just be having a DNS issue if you only just added the records. The only domains postfix will try to handle mail for are ones listed in the users/aliases pages. (If you have a user/alias for this domain, then your MX record will be ignored, so make sure you don't have a user/alias for the domain.)

**Comment by dieideeistgut** [comment]
Thanks @JoshData  for your reply! Somehow this isn't right for me - the MX records are only served and not being ignored with a user/alias for this domain. Removing the user/alias will disable serving the MX. I'm trying this in a development environment so it isn't too important.

**Comment by JoshData** [comment]
Ah, I see what you're saying. So then the answer is no - you can't have a user/alias and then tell the box not to handle the mail for that user/alias. See #683.

**Comment by dieideeistgut** [comment]
Sorry for re-opening/re-replying to a closed issue again - just for competence: it is possible to skip the verification of certain accounts by modifying the `/etc/postfix/virtual-mailbox-domains.cf` request. Simply extending the query with a param to skip certain domains seems to work out.
