### ISSUE TITLE
Mail Filtering

### ISSUE THREAD

**Issue by CforED** [mail-in-a-box/mailinabox#790]
Dear Support:

Does 'Mail in a Box' Server provide Global eMail message filtering to a sub mail folder?  View attached image files. If so, provide referral documentation.

![4 global email filters](https://cloud.githubusercontent.com/assets/12884813/14369868/8d72a50c-fcdd-11e5-96b2-c3be304af1e4.PNG)
![5 globalemail](https://cloud.githubusercontent.com/assets/12884813/14369869/8d73e390-fcdd-11e5-9e17-2482fe7b1c14.PNG)
![6 webmail](https://cloud.githubusercontent.com/assets/12884813/14369870/8d7526c4-fcdd-11e5-8968-22a677c84daa.PNG)
![1 email message header](https://cloud.githubusercontent.com/assets/12884813/14369871/8d77af52-fcdd-11e5-9b8a-7fe4ff40ecd1.PNG)
![2 filter test](https://cloud.githubusercontent.com/assets/12884813/14369872/8d7c4a44-fcdd-11e5-84d5-437d930e3e2c.PNG)
![3 filtered results](https://cloud.githubusercontent.com/assets/12884813/14369873/8d7de67e-fcdd-11e5-95f4-fbc7faa9057a.PNG)

 for details.

**Comment by JoshData** [comment]
Mail-in-a-Box has roughly equivalent functionality, which can be set through the filter settings in Roundcube (or any Sieve client).

**Comment by CforED** [comment]
Josh:

There are no Roundcube document that discusses rules based mail box filtering.

Visit the following document links:
1. wiki.bitnami.com/Applications/BitNami_Roundcube
2. docs.roundcube.net/doc/help/1.0/en_US/index.html

The setting rules for mail box filtering are found on the mail server, e.g., cPanel, Mail in the Box.

Question: Can we migrate mail accounts from cPanel to Mail in a Box with the rules based mail box filtering?


Hal

**Comment by JoshData** [comment]
You would have to try it out to see if it will work for you.

**Comment by TabTwo** [comment]
Hi,

I use this Sieve-script to handle my mailinglist-subscriptions: https://github.com/Exim/exim/wiki/MailFilteringTips
which sorts mails from lists by there list-ids into subfolders.

Or you go the manual way and use a sievescript like this
`require [ "regex", "variables", "fileinto", "envelope" ];`
`if header :contains ["X-BeenThere"] "vim_use@googlegroups.com" { fileinto "listen.vim-use"; stop;}`

Further examples:
http://wiki2.dovecot.org/Pigeonhole/Sieve/Examples

So yes, miab can handle massive amounts of mail from lists.
