### ISSUE TITLE
Could not save new password. Encryption function missing

### ISSUE THREAD

**Issue by laupkram** [mail-in-a-box/mailinabox#792]
Hello Mail-In-A-Box community :) 

I would like to ask what i had missed in my configuration as one of my users wants to change his password but he faced an error of

`Could not save new password. Encryption function missing` in roundcube mail.

What may cause the issue? 

Thanks :)

**Comment by aspdye** [comment]
Does the problem occurs only when **this** user tries this, or does this happen to all users?

**Comment by laupkram** [comment]
it happens in all of my users
