### ISSUE TITLE
Zone update - Not signed

### ISSUE THREAD

**Issue by gcarignano** [mail-in-a-box/mailinabox#796]
Hi, I'm experiencing a problem with a secondary domain. 
Whenever I add a custom DNS record, it shows it's added, the _zone.txt_ file gets pdated but the _zone.txt.signed_ does not, so when I `dig _amazonses.maseventos.com.ar TXT` nothing shows, even if I have the custom record created.

Also when I try to override the SPF record, nothing seems to happen... I know there is an issue that fixed this, but it's not working for me and I'm on the latest version available. Any input on how can I force the signing of the zone file so that I have the same info on the .txt and .txt.signed? 

Thanks.

**Comment by JoshData** [comment]
You probably have entered an invalid custom DNS record that is blocking the update.
