### ISSUE TITLE
Whole domain => whole domain email forwarding

### ISSUE THREAD

**Issue by Hooloovoo** [mail-in-a-box/mailinabox#800]
As per: https://discourse.mailinabox.email/t/guide-to-using-multiple-domains/160
whole domain to whole domain email forwarding is not currently supported, but could be.

Assume that there are
bob@domain1.com
alice@domain1.com
susan@domain1.com
fred@domain1.com
but the user also owns domain2.com and domain3.com and would like the bob@, alice@ etc addresses to work on these domains as well. 

At the moment, I understand that the process to do this is to point the domain2.com and domain3.com nameservers to domain1.com, then manually create aliases for each of the four users for both domains.

It would be nice to be able to bring an additional domain into mail-in-a-box and just have forwarders for every user created and kept in sync.

**Comment by JoshData** [comment]
That thread was from a year and a half ago. We added domain aliases long ago --- see the aliases page of the control panel.

**Comment by Hooloovoo** [comment]
Sorry. I did search around, but only found that thread.

Thanks for clarifying and thanks for adding the feature!
