### ISSUE TITLE
Support for php 7.0?

### ISSUE THREAD

**Issue by VeeeneX** [mail-in-a-box/mailinabox#802]
Is it planned?

**Comment by JoshData** [comment]
Since this is a mail project and not a web project, we're not going to support PHP hosting at all.

**Comment by VeeeneX** [comment]
Anyway, installation should work on machines with php7

**Comment by JoshData** [comment]
Installation is only supported on clean Ubuntu 14.04 installations (i.e. you haven't done anything on the server before installing Mail-in-a-Box).
