### ISSUE TITLE
Something went wrong on Users

### ISSUE THREAD

**Issue by alexpli** [mail-in-a-box/mailinabox#803]
Hi,
When I go on the "Users" admin page, i've the following popup issue message : "Something went wrong, sorry."

By watching the browser debugger, I can see a 500 ERROR when requesting : https://box.mydomain.com/admin/mail/users?format=json&_=XXXXXXX 

So I try to open this URL in my browser and there is an "Internal Server Error" but not when I try : https://box.mydomain.com/admin/mail/users

I think it's appear after the v0.17c upgrade but I'm not sure.

Alias page works.

Scuse my poor english.

**Comment by OmgImAlexis** [comment]
After updating to v0.17c I'm getting this on most sections of the DNS page.

![screen shot 2016-04-27 at 6 18 47 pm](https://cloud.githubusercontent.com/assets/6525926/14846972/747dc310-0ca5-11e6-80b6-cf1690f8cd7a.png)

**Comment by JoshData** [comment]
See if anything is in /var/log/syslog.

**Comment by alexpli** [comment]
@JoshData : there is nothing related to this issue in syslog when I'm going on this page.

**Comment by OmgImAlexis** [comment]
I deleted a DNS A record on a domain.

````
Apr 27 12:24:49 box Exception on /dns/custom/www.REMOVED__.com/A [DELETE]#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012    raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/usr/local/bin/mailinabox-daemon", line 57, in newview#012    return viewfunc(*args, **kwargs)#012  File "/usr/local/bin/mailinabox-daemon", line 316, in dns_set_record#012    return do_dns_update(env) or "Something isn't right."#012  File "/home/xo/mailinabox/management/dns_update.py", line 80, in do_dns_update#012    sign_zone(domain, zonefile, env)#012  File "/home/xo/mailinabox/management/dns_update.py", line 564, in sign_zone#012    dnssec_keys["ZSK"],#012  File "/home/xo/mailinabox/management/utils.py", line 193, in shell#012    ret = getattr(subprocess, method)(cmd_args, **kwargs)#012  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call#012    raise CalledProcessError(retcode, cmd)#012subprocess.CalledProcessError: Command '['/usr/bin/ldns-signzone', '-e', '20160527', '-n', '/etc/nsd/zones/__REMOVED__.com.txt', '/tmp/K__REMOVED__.com.+007+10929', '/tmp/K__REMOVED__.com.+007+19667']' returned non-zero exit status 1
````

**Comment by JoshData** [comment]
@OmgImAlexis You probably have something invalid in your custom DNS settings.

**Comment by alexpli** [comment]
@JoshData : And me, what could I do in order to find the reason of this problem ?

**Comment by JoshData** [comment]
There really should be something in syslog.... If not, you'd have to go into the source code and start debugging.

**Comment by alexpli** [comment]
@JoshData : I forced debug mode in daemon.py and here are the logs in syslog : 

`May  3 22:32:20 box Exception message repeated 2 times: [ on /mail/users [GET]
#012Traceback (most recent call last):
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
#012    response = self.full_dispatch_request()
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
#012    rv = self.handle_user_exception(e)
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
#012    reraise(exc_type, exc_value, tb)
#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
#012    raise value
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
#012    rv = self.dispatch_request()
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
#012    return self.view_func] Exception on /mail/users [GET]
#012Traceback (most recent call last):
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
#012    response = self.full_dispatch_request()
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
#012    rv = self.handle_user_exception(e)
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
#012    reraise(exc_type, exc_value, tb)
#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
#012    raise value
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
#012    rv = self.dispatch_request()
#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
#012    return self.view_functions[rule.endpoint](**req.view_args)
#012  File "/usr/local/bin/mailinabox-daemon", line 57, in new view
#012    return viewfunc(*args, **kwargs)
#012  File "/usr/local/bin/mailinabox-daemon", line 150, in mail_users
#012    return json_response(get_mail_users_ex(env, with_archived=True, with_slow_info=True))
#012  File "/root/mailinabox/management/mailconfig.py", line 140, in get_mail_users_ex
#012    for user in os.listdir(os.path.join(root, domain)):
#012NotADirectoryError: [Errno 20] Not a directory: '/home/user-data/mail/mailboxes/foo.zip'`

**Comment by alexpli** [comment]
It's my fault. I found the problem. I created an archive in the directory **$STORAGE_ROOT/mail/mailboxes** so **mailconfig.py** tries to open it as a directory on line 140 : 
`root = os.path.join(env['STORAGE_ROOT'], 'mail/mailboxes')
		for domain in os.listdir(root):
			for user in os.listdir(os.path.join(root, domain)):`
