### ISSUE TITLE
Excessive Dovecot logging into syslog 

### ISSUE THREAD

**Issue by dscoduc** [mail-in-a-box/mailinabox#809]
I believe having Dovecot logging into syslog makes it difficult to leverage syslog for identifying other system issues.  I would like to recommend we change the logging to match how postfix does logging, into it's own log file (e.g. /var/log/dovecot.log).

Changing this is a simple matter of adding an entry into the setup/mail-dovecot.sh, /etc/dovecot/conf.d/10-master.conf, and /etc/dovecot/conf.d/90-plugin-fts.conf file.

I would be happy to do a pull request if there is agreement on the recommendation.

**Comment by JoshData** [comment]
#810

**Comment by JoshData** [comment]
Seems like we got this!
