### ISSUE TITLE
Changed of domain

### ISSUE THREAD

**Issue by jpalcantara** [mail-in-a-box/mailinabox#813]
I unfortunately lost my domain and was forced to create a new one.  As a result I can no longer access the "cloud" module as it still references the previous domain and ask to trust the new domain and the box that I was presented with is:
"the "trusted_domain" setting in config/config.php. An example configuration is provided in config/config.sample.php. "
I looked but I can not find it.

  The idea at this point it would be to start from scratch and I need to get the Calendar and Contact off the box.
Is the Owncloud.db under /home/user-data/owncloud sufficient to copy and start over.

  I have had no problems with the setup, but the domain change cause some headaches.

thanks

**Comment by JoshData** [comment]
answered at https://discourse.mailinabox.email/t/domain-change-issue/1213
