### ISSUE TITLE
+tag adresses are not working 

### ISSUE THREAD

**Issue by sqeezy80** [mail-in-a-box/mailinabox#815]
____________________________
Delivery to the following recipient failed permanently:

     test+mich...@xxx.email

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain my...email by .email. [2a03:4

The error that the other server returned was:
550 5.1.1 <test+mich..@xxx.email>: Recipient address rejected: User unknown in virtual mailbox table

**Comment by gitacticia** [comment]
It works on my mail-in-a-box.
Le 3 mai 2016 5:31 PM, sqeezy80 <notifications@github.com> a écrit :

Delivery to the following recipient failed permanently:

 test+mich...@xxx.email


Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain my...email by .email. [2a03:4

The error that the other server returned was:
550 5.1.1 : Recipient address rejected: User unknown in virtual mailbox table

**Comment by yodax** [comment]
Did you do alias+tag@domain? Is test the email or the tag?

**Comment by aspdye** [comment]
@sqeezy80 Can you please report back? I think, if nobody else can reproduce this, and if we don't get more specific information - we can close this here 😁 

@yodax I also think that he mixed up the order of tag and username :wink:

**Comment by MasterPCUK** [comment]
Works fine here,

Just tested it on latest release.

you+anythinghere@yourdomain.com ;)

**Comment by aspdye** [comment]
#close @JoshData

**Comment by sqeezy80** [comment]
just came back from my vacation trip. topic can be closed. i messed up some sieve filtering rules(i forgot i even had). sorry

**Comment by aspdye** [comment]
You can close by yourself by clicking comment & close 😉 THX @sqeezy80
