### ISSUE TITLE
Hardening Mail-In-A-Box transport security

### ISSUE THREAD

**Issue by laupkram** [mail-in-a-box/mailinabox#816]
I saw a link that may seem to work with Mail-In-a-Box I just can't really understand if its really for MiAB but a look guys may brought some light

https://yawnbox.com/index.php/2015/11/29/hardening-mail-in-a-box-transport-security/

**Comment by aspdye** [comment]
#611 😉

**Comment by JoshData** [comment]
I don't know what to say here. The guy is doing a lot at once and it's not really clear what he was trying to do and why it would be the right thing to do. If you have a particular question or suggestion please feel free to write more.
