### ISSUE TITLE
munin and target link

### ISSUE THREAD

**Issue by Arnaud69** [mail-in-a-box/mailinabox#820]
Hello,
I'm trying mailinabox, all is fine, ok, really cool, well written !
Suggestion : you should put target="_blank" on munin link.
Like this, i don't need to click back many times...
Arnaud

**Comment by aspdye** [comment]
Can you submit a Pull Request? :rocket:

**Comment by Arnaud69** [comment]
OK, and i close it

**Comment by aspdye** [comment]
Why? Without Pull Request :confused:

**Comment by Arnaud69** [comment]
i'm figthing to do it, and i don't know how to ...
