### ISSUE TITLE
Please, think again of fail2ban recidive jail

### ISSUE THREAD

**Issue by gitacticia** [mail-in-a-box/mailinabox#824]
The fail2ban recidive jail, which blocks long-duration brute force attacks, now no longer sends the administrator emails (which were not helpful).

It was, according to my opinion, it would be fantastic if a lot of people forward those emails to respective abuses@...

**Comment by kirrus** [comment]
Detecting / sending to the right person would be a pain. You would also need to ratelimit the outbound email, so some small webhost doesn't turn around to find 10,000 emails about hacked VPS in their network filling up their abuse mailbox.

**Comment by anoma** [comment]
For what it is worth as per my other post I will be reverting this change as well. Radical changes like these that assume users are "just" happy to change their work flow should always be optional.

**Comment by aspdye** [comment]
What about an webinterface in the Admin Panel with downloadable Logs and Informations about Fail2Ban (maybe with Integration the Status Checks) :wink:

**Comment by anoma** [comment]
Maybe we capture use cases and see if they fit? I would rather not receive a load of fail2ban emails but equally I also want to make sure:

* A user is not banned that shouldn't be (to be fair this has not happened so far)
* An bot is IP walking to bypass the IP bans. Happens ALL the time. If I dont step in and add subnet bans Chinese IPs etc will hop all day every day.
*An attack. If my box is telling me someone is up to no good i want to pay attention.

These emails are an inconvenient necessity of being a sysadmin in charge of a public facing mail server.

**Comment by gitacticia** [comment]
We can search for an info in case of diagnostic, then use log. In case of being under attack, it's safer to ask the system to search and warn us ...

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
