### ISSUE TITLE
pip3 missing during upgrade from 0.17 to 0.18b

### ISSUE THREAD

**Issue by tuminoid** [mail-in-a-box/mailinabox#825]
Standard Ubuntu 14.04 box, with 0.17 running:

```
$ curl -s https://mailinabox.email/setup.sh | sudo bash
Updating Mail-in-a-Box to v0.18b . . .
remote: Counting objects: 37, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 37 (delta 33), reused 15 (delta 11), pack-reused 0
Unpacking objects: 100% (37/37), done.
From https://github.com/mail-in-a-box/mailinabox
 * [new tag]         v0.18b     -> v0.18b

Installing packages needed for setup...

FAILED: pip3 install email_validator>=1.0.0
-----------------------------------------
setup/functions.sh: line 9: pip3: command not found
-----------------------------------------
```

**Comment by aspdye** [comment]
Try the following:

`sudo apt-get remove python3-pip`
`sudo apt-get install python3-pip`

**Comment by tuminoid** [comment]
@aspdye That worked, thank you.

Interesting question is why did it fail. `python3-pip` was installed before as well, and it didn't seem to install any new alternatives or similar either.

**Comment by anoma** [comment]
fwiw is worth the Ubuntu ppa repo (at least) was playing up for me this morning. I always run a manual apt upgrade before i upgrade mail in a box and it took some time for this to be 100% successful. Possibly a coincidence.

**Comment by aspdye** [comment]
@tuminoid Good :sweat_smile:

**Comment by aspdye** [comment]
@anoma Maybe we could/should add this to the installation/upgrade script :wink: @JoshData

**Comment by JoshData** [comment]
I think this was probably just a random issue.
