### ISSUE TITLE
Make configuration able to persist

### ISSUE THREAD

**Issue by sebwas** [mail-in-a-box/mailinabox#826]
There should be a way to create a permanent configuration for at least some of the components like nginx or roundcube, as well as certain files and directories. Otherwise, on each upgrade, roundcube plugins, skins etc. as well as the configuration of the machine, like the roundcube name are purged.

An idea is to check for the existence of these files and directories in `/home/default` or somewhere else.
Also, it should be possible to execute the installer/updater with a `--purge-config` that will replace the `/home/default` files with the default ones.

**Comment by JoshData** [comment]
What you're suggesting is difficult to do correctly while retaining all of the guarantees of the current setup (idempotence, upgrade always works), and it will lead to more questions from users when things fail, which I don't have the time to support.

**Comment by sebwas** [comment]
While I see the support issue, afai understand your support policy right now basically is, that you don't give more support than replying to issues and PRs here. (I might be wrong there)

Also, yeah, you're right, this makes it more complicated. But should you settle there? Not imo.

**Comment by JoshData** [comment]
This has nothing to do with settling. It has everything to do with meeting the stated project goals within the bounds of the amount of time I have to spend on the project.

**Comment by sebwas** [comment]
Then maybe you should take somebody else on this project who is willing to assist you.

I suppose you can see that this is an issue if you are only in any way customizing the config(s).
Also, with a good documentation of this feature, support overhead can be minimized.

**Comment by JoshData** [comment]
I'm not blocking anyone from assisting.

**Comment by sebwas** [comment]
Maybe you should explicitly ask :-)

**Comment by JoshData** [comment]
Ok:

@sebwas Would you help with #777?

**Comment by sebwas** [comment]
This was not exactly what I meant, but I will see what I can do.
