### ISSUE TITLE
Make use of newer PHP

### ISSUE THREAD

**Issue by sebwas** [mail-in-a-box/mailinabox#827]
PHP 5.5 end of life is near and PHP 7.0 is out, and will be compatible with the soon-to-be-released roudcube 1.2 (release candidate is currently out).

If PHP 7 is not feasible, use PHP 5.6.

**Comment by aspdye** [comment]
Yes. ownCloud 8.2 and 9 is also compatible with PHP 7 :wink: We should move (for Security and Performance reasons) :+1: @JoshData

**Comment by ianberinger** [comment]
Using PHP7.0 would also simplify #758. Ubuntu 16.04 doesn't offer every package we need for PHP5 (eg. php5-sqlite) and we'd end up supporting two PHP versions.

**Comment by JoshData** [comment]
We're using the PHP shipped with the OS. The best way to move that forward would be to help on #758, #777.

**Comment by sebwas** [comment]
I don't really see, how working on #777 would exactly help this issue.

However, I would see this issue independently of the other referenced issues.
While Canonical will support EOL software with security updates (as clarified [here](http://askubuntu.com/questions/318326/what-is-canonicals-lts-support-policy-for-eol-software)), this should not be where people settle.
Newer PHP versions usually mean enhanced security, more features and better performance.

**Especially** with PHP 7.0 the performance benefit has been enormous, and using ondrejs ppa it's easy to install the latest (or desired) version.

I can create a PR for this if you want ...

**Comment by JoshData** [comment]
#777 is the blocker for starting on #758.

**Comment by sebwas** [comment]
So?

**Comment by JoshData** [comment]
Since PHP 7 is in Ubuntu 16.04, fixing #758 would mean we would be shipping PHP 7.

**Comment by sebwas** [comment]
But that would leave users of 14.04 behind, and its EOL is in 2019.

**Comment by aspdye** [comment]
It will take a long time until Ubuntu 16.04 is provided by every cloud Provider (Nearly no one does yet :grin:) Thats why I think we will ship MiaB with an 14.04 base at least 1 year from now. We must decide wheter PHP7 is such Important that we ship it seperatly. In my opinion - yes - but i dont know how much work it would be for @JoshData and the Maintenance :grin:

**Comment by sebwas** [comment]
PHP7 has such a vast set of various improvements that I would say one has to argument against it instead of for it.

**Comment by JoshData** [comment]
> I would say one has to argument against it instead of for it

Great. We'll leave this issue open for folks to argue against upgrading PHP.

**Comment by btibor91** [comment]
I think Z-Push-contrib is not ready for PHP7, yet. (fmbiete/Z-Push-contrib/issues/243)

**Comment by yeah** [comment]
FWIW, I just noticed that Roundcube's CardDAV plugin complains about PHP 5.5 as well in its settings:

<img width="921" alt="carddav" src="https://cloud.githubusercontent.com/assets/2181/24341643/3f577a18-12e5-11e7-8d5c-bcda80776fc6.png">

However, I do see my ownCloud contacts when composing mails, so it doesn't seem to be a problem atm?!

**Comment by bronson** [comment]
Z-Push is just about ready for PHP7: https://jira.z-hub.io/browse/ZP-804
