### ISSUE TITLE
Consider using the latest nginx version

### ISSUE THREAD

**Issue by sebwas** [mail-in-a-box/mailinabox#828]
Use the latest nginx (currently 1.10.0 in the stable branch) and even consider re-compiling it with the latest openssl (maybe controllable via `--enable-latest-nginx` flag), so _http2_ can be supported.

Oh, and of course: use **http2**.

**Comment by aspdye** [comment]
cc @JoshData

**Comment by JoshData** [comment]
@aspdye I see all the issues. No need to CC me.

@sebwas I don't see many benefits (I actually considered this before in #269), and every step away from stock Ubuntu makes things more complex (which is bad).

**Comment by sebwas** [comment]
I see what you are talking about, but it's actually pretty straight forward. Please consider [this resource](https://alex.bouma.me/recompile-nginx-with-openssl-1-0-2-for-http-2-via-alpn-ubuntu-14-04). It's really easy. If you want me to create a PR for it, let me know.

**Comment by JoshData** [comment]
Those instructions have literally 14x more lines than what we need to install nginx today. That's 14x more opportunities for problems down the road.

**Comment by sebwas** [comment]
Not really. I've used these in production and they work greatly. It's just pulling the source and re-compiling it from source using default parameters, _but_ the updated openssl (which makes sense anyway).

In terms of the configuration it does only mean one more keyword.

**Comment by cmsirbu** [comment]
I'm not sure I see the benefit - mailinabox is not primarily a web server and this would add complexity in an area that is secondary to its function as a mail server (I know there's webmail in there, but does it really need http2 now?).

@sebwas Is the required openssl version in the Ubuntu repos or do you need a PPA for it?

**Comment by sebwas** [comment]
You're partially right about that. It's not primarily a web server,
although it claims a basic functionality.
It does only add a little complexity on the mail-in-a-box set up side. It
does, however, give a huge benefit in general and you don't have to care
about it later - eventually you will have to deal with it anyway.
Also, it would be an outstanding feature of mail in a box, would it use the
latest software.

At least from my pov. Don't forget that it also adds value to the package
in general and this will give it more attention, which then leads to faster
development in this area (which is a good thing imo).

Yes, you do have to use a ppa, that, if the other ticket about the upgrade
to PHP 7 is resolved, will be introduced anyway.

Cristian <notifications@github.com> schrieb am Mi., 25. Mai 2016 um
12:55 Uhr:

**Comment by cmsirbu** [comment]
As much as the engineer in me wants ALL the shiny things, when I look at my mail server I value stability and security over new features. I agree that eventually we will switch to http2, but that will be with help from the supported official repositories (perhaps from 16.04 onwards).

Introducing additional PPAs should be done very carefully, as they increase the attack surface of the server. Let alone pulling a pre-packaged version of the openssl library (one of the most important on that system!) from someone's personal repository.

Plus, having to recompile nginx from source every time a security vulnerability is found creates a dependency on mailinabox to perform said upgrades instead of the Ubuntu security team.

**Comment by JoshData** [comment]
So let's go to the first goal of this project:

> Make deploying a good mail server easy.

It's not making a _perfect_ mail server, or a _great_ web server. It's striking the right balance between having a mail server that meets modern mail standards and having it be easy to set up, maintain, and understand.

So for all of the reasons @cmsirbu mentioned, I'm going to close this issue. I want to add one more reason:

* We don't know (and @sebwas didn't investigate) how nginx's HTTP/2 would change the box's actual behavior. How it would affect webmail is easy to guess about. But how would it affect Z-Push/ActiveSync? CardDAV for contacts synchronization? Are there any clients (like old mobile phones) with known compatibility issues? How much bandwidth would actually be saved by HTTP/2's compression in a normal Mail-in-a-Box setup?

Making a significant change like moving to a new PPA and changing the HTTP protocol needs to be substantiated with actual benefits for actual Mail-in-a-Boxes.

**Comment by sebwas** [comment]
Ok, I see the issue with that. It is a problem of higher maintenance.

I, personally, though, prefer the newer software, especially since this software is used on thousands of production servers all over the world. So I might eventually fork this repo and implement the changes.

Consequently, #827 should be closed as well.

**Comment by gitacticia** [comment]
>  newer software, especially since this software is used on thousands of production servers all over the world
I think you, @sebwas prefer ubuntu versus debian too, and for the same reason ?
I disagree, as an admin running some production servers.

@JoshData is driving safely, I feel like a cool passenger ! Keep the good job !

**Comment by sebwas** [comment]
@gitacticia What exactly do you disagree on?

I do prefer Ubuntu, which, as well, is run on thousands of servers. (But that's more of a personal preference than anything else, as this was the first distribution I got in contact with)

I agree with you, he is driving safely and he has absolutely every right to do so. Though, as I said earlier, I prefer another way, and that's ok, too.

**Comment by gitacticia** [comment]
I just disagree on seeking the newest soft, when I search for stability above all.
If you just trust ubuntu because it is like-a-tsunami published you can.

ubuntu derives, and will derive for a long time from debian.
Debian's dedicace is *quando paratus est*

@JoshData not only have rights to do so, but have to drive safely, as a serious admin.
