### ISSUE TITLE
Domain control validation - skip the A record check?

### ISSUE THREAD

**Issue by malord** [mail-in-a-box/mailinabox#829]
I'd like to be able to have my Let's Encrypt certificates renew despite my domain's web server being a different box, so I tried this in my `nginx.conf` (on the web server, not on the MIAB, and on port 80):

```
	location /.well-known/acme-challenge/ {
		resolver dns.example.com;
		proxy_set_header Host "example.com";
		proxy_pass http://miab.example.com$request_uri;
	}
```

Domain control validation fails though because `ssl_certificates.py` spots that the A record isn't pointing to the MIAB. Would it be feasible/secure/sufficient to have `ssl_certificates.py` try to download a file from the `/.well-known` path rather than just testing A records?

**Comment by aspdye** [comment]
The CA needs to know that you have the domain under your control :wink: We are not able to skip this, because otherwise everybody would be able to get an certificate for every domain :grin:

I dont know wheter there are any other validation methodes :confused:

**Comment by malord** [comment]
Hi aspdye, I understand the need for domain validation and I'm not trying to circumvent it, I'm just trying to find a way to allow my MIAB to renew its Let's Encrypt certificate when my domain's web server is on a different machine. If domain validation is achieved solely through a file in `/.well-known/acme-challenges/` then I can achieve that without the A records pointing to the MIAB, but I don't want to do this or make a patch if there's some issue I've missed?

**Comment by JoshData** [comment]
@aspdye Slow down. :)

@malord If you have the A record pointing elsewhere, the Mail-in-a-Box won't actually use the certificate, right?

**Comment by malord** [comment]
Not for web, but it will for Postfix/Dovecot?

**Comment by JoshData** [comment]
No, it uses the machine hostname's certificate.

**Comment by malord** [comment]
Ah, good point, and I'm already doing nginx forwarding of /mail and the autoconfigure URLs via the MIAB's hostname (faking the Host header) so that'll only need the hostname cert too. Thank you.
