### ISSUE TITLE
disable SMTP AUTH on port 25 to stop it accidentally being used for submission

### ISSUE THREAD

**Issue by malord** [mail-in-a-box/mailinabox#830]
I had a client still using port 25 for submission after switching their mail server to a Mail-in-a-Box and it resulted in a  `Authentication-Results...dmarc=fail` header being added by, I think, opendmarc to all their outgoing mail. Now this is anecdotal, but their mails were going to either Spam or /dev/null on Hotmail.com before they switched to port 587 (where the `Authentication-Results` header goes away, I'm assuming because opendmarc isn't processing mails submitted on port 587?)

Is it somehow possible to either a) disable SMTP AUTH on port 25 to stop it accidentally being used for submission, b) prevent opendmarc processing mails from authenticated users.

(This is a minor and probably rare issue, if it even was the reason Hotmail was discarding their mail, and I've now checked that all my clients are using port 587, but option a would have saved me a ton of time)

**Comment by JoshData** [comment]
> Is it somehow possible to either a) disable SMTP AUTH on port 25 to stop it accidentally being used for submission

Probably and we should do that.
