### ISSUE TITLE
Network communication failed  Hostname was NOT found in DNS cache

### ISSUE THREAD

**Issue by ramoslin02** [mail-in-a-box/mailinabox#831]
experience such problem, How can I solve it.

sudo: unable to resolve host box.szanody.com.cn 

Updating system packages...
Installing system packages...
Initializing system random number generator...
May 18 19:42:47 box.szanody.com.cn pollinate[4000]: ERROR: Network communication failed [28]\n19:42:43.427295 \* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     019:42:46.940145 \* Resolving timed out after 3512 milliseconds
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
19:42:46.940348 \* Closing connection 0
curl: (28) Resolving timed out after 3512 milliseconds
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
