### ISSUE TITLE
Issue with Thunderbird connecting

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#833]
Hello so I deployed a new Mail-in-a-box server and everything is working perfectly with my VPS with the exception of not being able to connect it to my thunderbird. It automatically detects the configuration, and when I go to click next as far as I can tell everything is correct. Passwords are correct and everything
![screenshot_2016-05-20_21-56-45](https://cloud.githubusercontent.com/assets/19499446/15445804/1fcf4f94-1ed6-11e6-9a01-5a8b2b85f2e8.png)

**Comment by aspdye** [comment]
Are other clients like Outlook or any other IMAP client on your phone working? :grin:

**Comment by ChiefGyk** [comment]
I just added it to my iPhone no issue with the auto-configure link. Unfortunately I can't test Outlook as I am GNU/Linux only as far as laptops and desktops go

**Comment by aspdye** [comment]
So we now know that your Problem is Client specific :wink: (because iOS works with IMAP) ... I'll try reproducing later today, but i think it will work for me :sweat_smile:

**Comment by ChiefGyk** [comment]
I'm using Thunderbird 38.8.0 on Xubuntu 14.04 LTS if that helps out

**Comment by ChiefGyk** [comment]
I also just tried it in Evolution on the same laptop I use normally with thunderbird. No luck I am getting "host lookup box.mail_server.me failed" Yet works perfectly on my iPhone, and I can send as well as receive via the webmail to my other emails.

**Comment by ChiefGyk** [comment]
Same issue with Claws... So there is something wrong in how the clients need to be set up. But this same laptop works perfectly with an Office 365, Gmail, and Hotmail account all through IMAP as well via thunderbird. This is the first time I have had issues with Thunderbird in nearly 6 years so I am stumped. iPhone is still working perfectly

**Comment by ChiefGyk** [comment]
So I opened my Macbook Pro which has been gathering dust for a year, and opened up thunderbird and manually added my email the same exact way I did on my Xubuntu laptop... It worked perfectly so any guesses as to what could be going on?

**Comment by ChiefGyk** [comment]
Well that was weird... It just started working on my Xubuntu laptop all of a sudden. I just tried again, hit the SSL only option, when it failed flipped back and VOILA! worked... Think it's a bug with thunderbird

**Comment by yodax** [comment]
Could you try to ping the box from the failing laptop? Perhaps it's a firewall or dns issue.

**Comment by JoshData** [comment]
It was most likely that the old DNS was cached on the client.

**Comment by aspdye** [comment]
We should offer self-Service Guide for such Problems on mailinabox.email :wink:

**Comment by ChiefGyk** [comment]
Well now I woke up to find a new issue this morning... An error occurred while sending mail. The mail server responded:  5.7.60 SMTP; Client does not have permissions to send as this sender. Please check the message and try again.
Works perfectly from Webmail, and iOS

**Comment by ChiefGyk** [comment]
Found the issue thunderbird was defaulting to another SMTP for some reason. However Thunderbird is still having issues connect from laptop

**Comment by ChiefGyk** [comment]
Fixed the issue using Bleachbit and completely clearing out Mozilla Thunderbird on Xubuntu 14.04 LTS. Using Mozilla Thunderbird 45.1, after I rebuilt the index after deleting and readding the account seems to work perfectly. Worth the few hours resyncing a half dozen other emails though

**Comment by ChiefGyk** [comment]
*sigh* SMTP issues just on this thunderbird still

**Comment by ChiefGyk** [comment]
Seems to have been narrowed down to when I am on my own OpenVPN I made on Digital Ocean... Any fixes for it work when on a VPN, and can people replicate the issue?

**Comment by Hellenab** [comment]
So I just had this issue. After digging around, the solution for my case was this:
Right-click on any of your email accounts that you find in the left-hand panel and click on Settings.
Go to "Outgoing Sever (SMTP)".

The issue for me was that the default SMTP had for some reason changed. I have 2 outgoing SMTP adresses for two different accounts, one Gmail and one Outlook.

If you have two different Outlook SMTP adresses, try swapping between them and see if it helps but anyway: the default had been swapped and my main account was trying to use outlook's smtp instead of gmail's. There you go.

**Comment by junglee372018** [comment]
I am also facing the same issue. I am using on Windows 10 and thunderbird v60.6.1.  Please help me in solving this.

![image](https://user-images.githubusercontent.com/44200667/59503123-4212c400-8ebd-11e9-9abc-402e076bf75f.png)
