### ISSUE TITLE
Secondary nameserver check fails if multiple records are configured for a domain

### ISSUE THREAD

**Issue by jdno** [mail-in-a-box/mailinabox#834]
I have a domain, let's call it `example.com`, for which I have two `A` records configured:

```
;; ANSWER SECTION:
example.com.    1800    IN  A   192.30.252.154
example.com.    1800    IN  A   192.30.252.153
```

The status check fails for this domain with the following error message:

> Secondary nameserver ns2.example.com is not configured correctly. (It resolved this domain as 192.30.252.153; 192.30.252.154. It should be 192.30.252.153.)

The check shouldn't fail, since the domain is resolved correctly, and both primary and secondary nameserver return the same result. But since the check expects only a single IP to be returned, it fails.

For what it's worth, I'm running **v0.18b**.

**Comment by JoshData** [comment]
Good catch. The problem is at https://github.com/mail-in-a-box/mailinabox/blob/master/management/status_checks.py#L430.
