### ISSUE TITLE
Stop Using Piping To Bash For Install/Upgrade

### ISSUE THREAD

**Issue by TheRyanHowell** [mail-in-a-box/mailinabox#835]
Since #141, For install/upgrade, the how-to tells people to curl a script directly into bash ran by root, this is obviously a horrible idea in terms of security.
Instead you should either:
- Recommend people download the script, import a GPG key (which they can actually verify is correct), check a published signature and read the setup script to confirm it is not malicious.
- Use a external repository and native package management instead of shell scripts.

Recent practical attack:
https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

**Comment by JoshData** [comment]
dup of #250 (more or less), see the README, and please don't call my work horrible
