### ISSUE TITLE
Allow backup to B2 (BackBlaze Cloud Storage)

### ISSUE THREAD

**Issue by NurdTurd** [mail-in-a-box/mailinabox#836]
[B2](https://www.backblaze.com/b2/cloud-storage.html) is [BackBlaze](https://www.backblaze.com)'s form of Cloud Storage. It's highly affordable for $0.005/GB.
B2 is similar to S3 in the way that it uses buckets.

They have a very small but very comprehensive documentation for their API, which is friendly to most languages.

The reason I'm suggesting this is because sure, S3 is nice, and it's trusted, but it's expensive to some, and having a second option that's more affordable would be nice.

I wouldn't know how to go about implementing this since I'm not that skilled in Python, but if someone could implement this, I would greatly appreciate this.

**Comment by aspdye** [comment]
I think the same what i've written here about B2 applies here: https://github.com/owncloud/core/issues/21304

...or are there any API's which allow easy integration 😁

**Comment by yodax** [comment]
Duplictiy which we already use supposedly supports it. So it should be nearly identical to the s3 code. https://www.backblaze.com/b2/docs/integrations.html

**Comment by JoshData** [comment]
Consolidating into #717.
