### ISSUE TITLE
Add ability to read other users' mails

### ISSUE THREAD

**Issue by taylankasap** [mail-in-a-box/mailinabox#842]
However unethical it may seem, server admins already have access to these data through filesystem. Why not add it to the admin area itself?

I don't know if this is legal as it is but the box owner can make users agree to a ToS.

Reason behind reading other users' mails can be as simple as checking if they are sending mails considered good or bad — spam-wise —, or to see if they are up to any illegal activities etc.

**Comment by JoshData** [comment]
The admins in the control panel may not be the same people with SSH console access.

**Comment by taylankasap** [comment]
Should I assume adding a third role (i.e. super admin) is too much of a hassle?
What about making sudoers be able to login through mailinabox panel as a superuser?

**Comment by JoshData** [comment]
I'm not sure this is really a use case for Mail-in-a-Box. It's not really an enterprise product, and I'm not sure I'd want to make it easy for admins to read the emails of their users, who are probably their peers in real life (friends, relatives, coworkers). That aside, it's not a priority in any case - there are other more important things that need attention in this project first.

I'll keep the issue open if there's more discussion. I do see your point.

**Comment by gitacticia** [comment]
As a specialist of law-enabled forensic, I mention that it is stricly prohibited in FRANCE (and widely in Europe) to let achieved this goal by only one person. At least, there must be a technical root aside a lawyer that "allow" root to read. In fact, root stays root. But, please, do not facilitate this action.

**Comment by taylankasap** [comment]
@gitacticia Are you saying it is illegal to read mails or being able to read mails? If it is the latter, I don't know who **can't** read their users' mails.

And there are some well known tools that facilitate to read the mails sent — or received — through them. Virtualmin, Mandrill etc. Why aren't those tools affected by that law? Or are they?

> to let achieved this goal by only one person

Do you mean if multiple people were allowed to read mails, then it is okay?

**Comment by gitacticia** [comment]
Yes, you can understand that it is illegal to being able to read other's mails. I do not want to say that law is good or bad, thus being root it's is quite fun.

A cypher function is a must-have when you store mails.
Now, in France, public servers (acting as state programms) which store mails in clear are unusable.

If you really want to run a serious server with serious users, YOU have to not be abble to read their mail, respecting this law.

A simple "cat" could read a mail, this is why mail are created.

And I mean that ONE person have to be AUTHORISED (by law enforcement, justice, or by the owner) having a bypass and ONE ANOTHER person have to be technically authorised (by having the root).

One root AND one justice (or owner) representative.
It is the same way you have to follow to discole a locker door on a private.

Electronics documents, as mails are, are to be considered as PRIVATE.

In France, in special cases, you play for real if you read (and use your subservice knowledge againt owner or recipient) users mail.

@taylankasap : do you really ignore what PGP (or the well implemented GNUPG) is ?

**Comment by taylankasap** [comment]
@gitacticia Not really. I'm just not a mail savvy nor system admin.

If what you are saying is a thing then IMO this issue should be closed & a new issue should be opened about encrypting the mails.

**Comment by gitacticia** [comment]
I do not need an issue for that while miab's goal is not to be an encrypted mail server. But this one should be close, imo.

**Comment by taylankasap** [comment]
Does encrypting mails have any downsides?

**Comment by gitacticia** [comment]
Managing keys, as usual.

**Comment by msgerbs** [comment]
Just saw this issue and wanted to add, using sudoers to manage superusers in the web admin would be a terrible idea. I don't think I even have a password on my account as I only have RSA key authentication enabled on SSH.

**Comment by lloydsmart** [comment]
To be honest I assumed MiaB already encrypted the on-disk mail storage.

If not, maybe we could implement a system where the mail files on-disk are GPG-encrypted separately for each user, using their chosen email password. That way, even the admin couldn't access the contents.

The problem, of course, would be decryption on-the-fly. How would the system decrypt the mailboxes when the user logs into Roundcube without the admin being able to see the cleartext? Maybe this isn't as easy as it first seems...
