### ISSUE TITLE
aliases deliver mail to non-existing users

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#852]
Once an alias matches an address, no matter what destination address it is finally mapped to --- even if it does not correspond with a mail user --- the mail is delivered to that address. It ends up in a new Dovecot mailbox on disk. It should be rejected, not accepted.

https://discourse.mailinabox.email/t/domain-aliases-allowing-delivery-though-virtual-mailbox-does-not-exist/1262

A domain alias allows a sender to create mailboxes on disk for any address @ that domain (so long as the address doesn't have another alias mapping it to something else).

Regular aliases and catch-alls have a similar problem: The destination address is similarly not validated to be a mail user. If the destination address isn't a mail user, a mailbox will be created on disk anyway for any incoming mail, rather than the mail being rejected.

**Comment by just4t** [comment]
source: https://discourse.mailinabox.email/t/domain-aliases-allowing-delivery-though-virtual-mailbox-does-not-exist/1262/5?u=just4t

```
@JoshData

    Provided patch seems that at least, kills the owncloud login for default admin user right after been manually applied...
    Restoring to the earlier dovecot-sql.conf.ext file solves the mentioned owncloud login issue.

Can you reproduce the mentioned owncloud login issue at your end, too?
```

**Comment by JoshData** [comment]
There is no default admin user. That was a bug too, not a feature.

**Comment by just4t** [comment]
let me explain... when creating the first user like me@mydomain.com I understand that's the main and single user you have for admin MiaB, webmail & Owncloud... That's the 'admin' user I wrongly  named before.
- I know 'admin' rights for 'Owncloud' are disabled by default under the MiaB integrated version of it.

**Comment by JoshData** [comment]
Works for me.

Check that you're logging into ownCloud with the exact email address that the box's control panel says is an admin?

**Comment by just4t** [comment]
thanks for feedback... going to 'snapshot' the server I use for test the Miab 'dev. master' version before to run the 'mailinabox' setup again there. Will post again here with the results.

**Comment by JoshData** [comment]
K, lemme know what happens.

**Comment by just4t** [comment]
Done now! over a dev. server with a very basic MiaB setup by upgrading it from dev. master and this time worked correctly...!?. Now I have no problem to login to 'owncloud' as reported earlier.
I hate I can't see what I did wrongly before :-) . Sorry for that!

**Comment by JoshData** [comment]
Cool cool.
