### ISSUE TITLE
Emails that are sent out are always going into SPAM - Gmail, Outlook

### ISSUE THREAD

**Issue by JimZAH** [mail-in-a-box/mailinabox#855]
Hi Josh,

Firstly I really love mail in a box. It's nice to take control of my emails. Thank you for your hard work.

The one problem I'm having is that my emails are getting marked as SPAM. The miab is controlling DNS and DSEC is working. I've tested against the advised email tester and all is showing ok.

I hope you can assist :)

James@crewsome.com

**Comment by rebarber** [comment]
In my experience, many systems (gmail,Fastmail) check the date of domain registration. New domains are flagged a "High Risk" to send spam.

**Comment by JimZAH** [comment]
Hi,

Thank you for your response:), so you think time will help in the
situation?

-- 

James

**Comment by ChiefGyk** [comment]
Also curious as to what time period they want, I am dealing with Google on a gmail help forum about this same issue https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gmail/3rr2VB9-Mug/bWaQGE7-BQAJ

**Comment by jvolkenant** [comment]
Check that your IP is not on an RBL.  I.e. if you run a server from your home internet you'll surely be blocked.
Its also possible that if you got a VM from a VPS the IP you got might have been blacklisted from the user who was using your IP before you.

http://multirbl.valli.org/

**Comment by ChiefGyk** [comment]
@jvolkenant per your recommendation I looked up here which is more thorough than other tests I see. I was listed on 3 and have sent delisting emails to 2 of them however one doesn't seem to be loading at all ( http://www.dnsblchile.org/ )
Here is the report
[MultiRBL.valli.org - Results of the query 107.170.52.pdf](https://github.com/mail-in-a-box/mailinabox/files/344868/MultiRBL.valli.org.-.Results.of.the.query.107.170.52.pdf)

**Comment by jvolkenant** [comment]
those two blocklists don't look to be that popular.

There are many factors that could cause mail delivery issues. dkim/spf/reverse dns etc can all help with mail delivery but does not guarantee delivery.  It could be that they just discredit mail comming from that netblock

**Comment by JimZAH** [comment]
Hi Guys,

Thank you for all your feedback. I've tested my sent emails with a few online tools. All looks good but it appears the big providers still don't like mail.crewsome.com. Will keep trying but I really appreciate all your input.

It's been a dream of mine to move to my own mail server. At the minute I pay a charge per month just for email.

**Comment by JimZAH** [comment]
Further to my last comment. Here is a test result from https://www.mail-tester.com/

**Comment by JimZAH** [comment]
Hi All,

Thank you for your messages and advice. 

I'm happy to announce that emails are being received without spam flagging. 

Might have been the age of the domain name.
