### ISSUE TITLE
Public dns not running port 53

### ISSUE THREAD

**Issue by ezraholm50** [mail-in-a-box/mailinabox#860]
Hey thanks for the app.

The setup ran great for several weeks but recently I got this error at the status page that Public dns not running port 53. It only updated the box and i did nothing to mess it up. Also tried service nsd start but that gave no output.

I think this has led to some resolving errors on my domains as i have 6 domains setup on the box for dns. It shows connection refused ocasionally and i checked my reverse nginx proxy, also no errors, I searched and searched before posting here.

Im truly lost here, could any one shine a light or let me run some commands to check it out? I already ran the installer like 5 times over without any luck.

Kind regards,

Ezra

**Comment by ezraholm50** [comment]
Mobile wont let me edit, sorry.

The nginx reverse runs as a vm on my server where the domains are, at home with the dns api setup as dyn dns. The miab runs on a vps with a static ip 4 and 6.

**Comment by JoshData** [comment]
Hi, if you're still having trouble, please try on the discussion forum. That's a better place for working through issues like that.
