### ISSUE TITLE
can not delete DNS entries from orphaned domains

### ISSUE THREAD

**Issue by ausminternet** [mail-in-a-box/mailinabox#862]
Hi there,

I got rid of one of my domains and therefore I deleted all aliases for that domain. MIAB then deleted all the default aliases. At the status page and in users/alias configuration this domain is no longer listed.

Unfortunately it is still listed under custom DNS and if I try to delete it, I get the following error message: 
`domain.tld is not a domain name or a subdomain of a domain name managed by this box.`

Kind regards,
Jan

**Comment by JoshData** [comment]
The custom DNS records are stored in `/home/user-data/dns/custom.yaml`. You could delete them from there in the meanwhile.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
