### ISSUE TITLE
replace nginx+TLS utils with Caddy server

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#863]
We could delete an enormous amount of code related to TLS settings and certificate provisioning if we switch to https://caddyserver.com.

**Comment by yodax** [comment]
Looks promising! It looks feature complete. 

One thing that I couldn't easily find was how to keep it up to date. I couldn't find a Ubuntu package. But that should be workable.

**Comment by schlypel** [comment]
AFAIK caddy has no package yet, but its a static go binary, upgrading would just be

- curl new version
- check hash
- replace binary with new one

If this would be a vote, i'd give it a big thumbs up, as caddy would certainly make the tls provisioning and vhost configs very easy.

**Comment by ponychicken** [comment]
i switched to caddy for all dhe websites i maintain, it was pleasant and runs without any hickups

**Comment by ponychicken** [comment]
One small blocker: https://github.com/mholt/caddy/issues/972
