### ISSUE TITLE
Need Fail2Ban Filters for Nginx

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#866]
When making my other servers I was double checking fail2ban configurations and noticed there is no fail2ban settings for nginx seeing as the webmail runs on it. Not sure if it's an issue, or anything but I was hoping some other could tell me if I am on the right track, or if it's not even necessary

In the /etc/fail2ban/jail.local
```
[nginx-http-auth]
enabled  = true
filter   = nginx-http-auth
port     = http,https
logpath  = /var/log/nginx/error.log
```

```
[nginx-badbots]
enabled  = true
port     = http,https
filter   = nginx-badbots
logpath  = /var/log/nginx/access.log
maxretry = 2
```

then` cd /etc/fail2ban/filter.d`
`sudo nano nginx-http-auth.conf`

make sure it's like below
```
[Definition]


failregex = ^ \[error\] \d+#\d+: \*\d+ user "\S+":? (password mismatch|was not found in ".*"), client: <HOST>, server: \S+, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"\s*$
            ^ \[error\] \d+#\d+: \*\d+ no user/password was provided for basic authentication, client: <HOST>, server: \S+, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"\s*$

ignoreregex =
```

copy badbots config from apache
`sudo cp apache-badbots.conf nginx-badbots.conf`

**Comment by yodax** [comment]
Please see the discussion in this pr: https://github.com/mail-in-a-box/mailinabox/pull/767

We are currently working on a PR that would protect the public interfaces. See: https://github.com/mail-in-a-box/mailinabox/pull/798

**Comment by ChiefGyk** [comment]
Thanks I will look at it as I was just adding the filters myself to Fail2Ban and just added Owncloud

**Comment by JoshData** [comment]
I think `nginx-http-auth` is made unnecessary by @yodax's work (agreeing there), and I don't know what `nginx-badbots` does. @ChiefGyk can you explain `nginx-badbots`?

**Comment by yodax** [comment]
I'm also interest on what the security risk is of allowing spiders to crawl the site. No information is exposed on our sites since everything is behind logins.

**Comment by ChiefGyk** [comment]
I've just always added it for malicious bot request patterns as I do host some HTML on my MiaB as well. So for those who want to use the webserver side as well it could be of benefit. it may be worth looking into this https://github.com/mariusv/nginx-badbot-blocker

**Comment by JoshData** [comment]
Yeah I'm not convinced this provides any value now that @yodax's PR is merged, since it would just be protecting static assets, which don't really need protecting.
