### ISSUE TITLE
Cloudflare DDoS for MiaB

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#867]
What would be the steps for getting Cloudflare DDoS mitigation for my VPS to work, while restoring true IP's, working with cloudflare-blacklist in fail2ban. I am only familiar with Apache, so I am a bit out of my depth with Nginx but I am trying to learn

**Comment by Seeder101** [comment]
I think simply you can use an external DNS handling all domains

**Comment by MasterPCUK** [comment]
You can as usual put it behind CloudFlare, however email won't work then.

CloudFlare as you might know hides actual IP, so when another email server tries to send and email to your box, it just wont be able to do it.

**Comment by Seeder101** [comment]
@MasterPCUK  actually you can use the MX record to do that and pass the cloudflare network =D
I do that with the normal webhosting cpanel setup etc... and it works just fine

**Comment by Seeder101** [comment]
the bad side that if you want to use the cloudflare network then it won't work for example if you want the main domain for hosting sites you can do the cloudflare thing...it's fine but if you want the email thing you have to set the MX record without the cloudflare network = by pass it then it should work and our friend here needs the cloudflare network for blocking DDOS attacks

**Comment by MasterPCUK** [comment]
@Seeder101 Sorry, I was a bit unclear in my previous post, yes sure we can use CloudFlare and set MX to use just DNS without CloudFlare protection, but that was my point, IP of MX server is exposed, so it does not make any difference with regards to MX records in CloudFlare.
