### ISSUE TITLE
RootKit Hunter

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#869]
I believe Rootkit hunter should be added, and set to automatically scan for updates. I am working on copying my changes to the main install script on my fork as I write this

**Comment by JoshData** [comment]
As @yodax said in #870:

> Regarding the rootkit hunter. I'm not sure if that is something I would want. If someone can hack your server they can remove this tool. But I'll gladly defer to someone with more expertise on the matter. I do have some comments on the setup. (As stated before I think this should be a separate PR)

I've _never_ run a rootkit checker in my life, which means I'm either missing something obvious or it's really not necessary. I think maybe a rootkit checker is good for after-the-fact diagnosis, but probably not for live protection.

**Comment by ChiefGyk** [comment]
I've just always made it habit of having a rootkit checker. I think it might be something nice to add

**Comment by JoshHarmon** [comment]
I disagree with adding this. I don't think it's a worthwhile addition. The ways you get compromised are by:
- a) leaving SSH open to intruders (can be defended by publickey auth only, no root login, non-default ssh port, port knocking)
- b) running outdated versions of software (coughcough WordPress, Drupal) with plugins from questionable sources on old PHP versions and with poor configuration (not chrooted, no open_basedir protection, running as root, perhaps).
- c) not updating system packages (you can configure apt to do automatic security/maintenance updates)
- d) using insecure, easily-bruteforced passwords for services that grant administrative control of the server
- e) operating a server that a lot of less-than-trustworthy people (read: skids) also have some system access on (such as the typical crappy shared host who doesn't enable any of the security options clearly laid out for them in WHM)

If you don't do that stuff, you're not going to get shelled. And this is coming from someone who usually errs on the side of wearing a tin-foil hat.

**Comment by jerogee** [comment]
I agree with JoshHarmon: A rootkit hunter for MiaB is pretty pointless and if added please make it opt-in and switched off by default, as it only adds bloat and load. The strength of MiaB is that it installs a dedicated box with strict permissions etc., and a highly controlled web front-end. What is next on the bloatware list? Comodo Free Antivirus for Linux?

**Comment by ChiefGyk** [comment]
I can see the point. However I am still going to look into ClamAV for sending and receiving mail. Which is my next project

**Comment by yodax** [comment]
I haven't run antivirus in years. If you look at Google project zero testing AV products, it will make you machine more insecure by increasing the attack surface. 

Running it on a mail server doesn't seem practical and more of a security risk. You need to be very sure that the scanning service isn't publicly exposed. (See recent drama about public clamav instances) Also there would be extra management involved, what to do with false positives for instance.
