### ISSUE TITLE
so how to point my new machine website insteading mail machine ?

### ISSUE THREAD

**Issue by thefox41** [mail-in-a-box/mailinabox#873]
okay so  i can't use  wordpress?
i will use another VM  for my new website equipped with MYSQL and apache......etc so how to use DNS  in there so example.com web dirictroy  instead being  hosted there on the mail machine   will be hosted on another machine ?

**Comment by mar1u5** [comment]
> first what database mail* uses ?

SQLite 

> and what web server it uses is it nginx or apache2 ?

nginx

> also can i manage to have a wordpress frame work it self to setup my own website instead of using read built HTML website

No. PHP is missing for user-hosted pages, and also MySQL is missing. You should use an different server for this, because MiaB is used to be an just-work solution without any modifications from users.

**Comment by jvolkenant** [comment]
For security issues, i wouldn't recommend this

There is no Mysql installed with mailinabox, I would recommend setting an A record to point www.yourdomainhere.com to your other webhost hosting wordpress.
