### ISSUE TITLE
DKIM failing aol.com, gmail ending up in spam

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#881]
Sending email is resulting in some of it being placed in spam

`Return-Path: <alon@ganon.me>
Received: from box.ganon.me (box.ganon.me [107.170.52.74])
	(using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by mtaig-aao04.mx.aol.com (Internet Inbound) with ESMTPS id ECAE670000087
	for <alonganontest@aol.com>; Thu, 30 Jun 2016 15:28:12 -0400 (EDT)
Received: from authenticated-user (box.ganon.me [107.170.52.74])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by box.ganon.me (Postfix) with ESMTPSA id 27EB11A011F
	for <alonganontest@aol.com>; Thu, 30 Jun 2016 15:27:40 -0400 (EDT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=ganon.me; s=mail;
	t=1467314861; bh=yW2jSUlZKz0c7t15hK+GWn9dEFpTJ3RtD7W6Qj8Yz5I=;
	h=To:From:Subject:Date:From;
	b=Sn2rGhbGavN3767aviTPS9AB+HVnIhl/HXrKNj2PzPUI5vliQDhj/iMCR2OyrIyvj
	 wfk1AMQIavb++uBkZkVUVOxTHr2lKri3I34VYqQTD81igzfjujboq2tQSAc4Dnr2P3
	 RGnOyiiC8QhOYIIRIpYiJk/MijaY3c+Ogk0AqEtYhDbOBPjpaYjzl/zpT3CMBFouL2
	 bUegziehnCf7aswLTvFzZPq3eZorONZfcmd3NTLG8BVqH2f8lRab+0XhfcDyqfMT5l
	 5O7ZocRJlye6osAkzpgLnSSHPbaOkdpVGl2SKBLc/HClXjwSC7I96wduodUV6qb3b7
	 ZNGOmBZaSH0uw==
To: "alonganontest@aol.com" <alonganontest@aol.com>
From: Alon Ganon <alon@ganon.me>
Subject: testing
Message-ID: <e922b65c-2c55-a167-f827-a564dcd80749@ganon.me>
Disposition-Notification-To: Alon Ganon <alon@ganon.me>
Date: Thu, 30 Jun 2016 15:27:40 -0400
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------171E59867B01EBB167F1844E"
x-aol-global-disposition: S
X-AOL-VSS-INFO: 5800.7501/110599
X-AOL-VSS-CODE: clean
X-AOL-SCOLL-AUTHENTICATION: mtaig-aao04.mx.aol.com ; domain : ganon.me DKIM : fail
X-AOL-SCOLL-DMARC: mtaig-aao04.mx.aol.com ; domain : ganon.me ; policy : quarantine" ; result : Q
Authentication-Results: mx.aol.com;
	spf=pass (aol.com: the domain ganon.me reports 107.170.52.74 as a permitted sender.) smtp.mailfrom=ganon.me;
	dkim=fail (aol.com: Message body hash computation failed verification.) header.d=ganon.me;
	dmarc=pass (aol.com: the domain ganon.me reports that SPF is strictly aligned, DKIM is unaligned.) header.from=ganon.me;
X-AOL-REROUTE: YES
x-aol-sid: 3039ac1b1506577572cc2977
X-AOL-IP: 107.170.52.74
X-AOL-SPF: domain : ganon.me SPF : pass`

**Comment by ChiefGyk** [comment]
Weird Gmail is passing SPF, Dmarc, and DKIM, but still is going into spam
`Delivered-To: alonganontest@gmail.com
Received: by 10.202.83.84 with SMTP id h81csp602344oib;
        Thu, 30 Jun 2016 13:16:24 -0700 (PDT)
X-Received: by 10.55.114.69 with SMTP id n66mr1074123qkc.2.1467317784650;
        Thu, 30 Jun 2016 13:16:24 -0700 (PDT)
Return-Path: <alon@ganon.me>
Received: from box.ganon.me (box.ganon.me. [107.170.52.74])
        by mx.google.com with ESMTPS id q72si24188qka.110.2016.06.30.13.16.24
        for <alonganontest@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 30 Jun 2016 13:16:24 -0700 (PDT)
Received-SPF: pass (google.com: domain of alon@ganon.me designates 107.170.52.74 as permitted sender) client-ip=107.170.52.74;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@ganon.me;
       spf=pass (google.com: domain of alon@ganon.me designates 107.170.52.74 as permitted sender) smtp.mailfrom=alon@ganon.me;
       dmarc=pass (p=QUARANTINE dis=NONE) header.from=ganon.me
Received: from authenticated-user (box.ganon.me [107.170.52.74])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by box.ganon.me (Postfix) with ESMTPSA id C08451A0120
	for <alonganontest@gmail.com>; Thu, 30 Jun 2016 16:16:23 -0400 (EDT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=ganon.me; s=mail;
	t=1467317784; bh=QbKJCkes+WjZjTR5jqYqmKqzGkMM8NWtB1VvzRsWZ0s=;
	h=To:From:Subject:Date:From;
	b=HwU/YwYLxGj4znngPZ0+pOAlNYSwzp8/rNnqlJybk8dj9kxBoPJnibIpqbhrkyD3m
	 m9+ePas9XbWH/VTxHGzxY5JZJKOvHkoKm0kEbA3om3904Q0pmvZ9p3Ri5Eo8HDSECT
	 M2/C1VLigmrEdAlyDdQL3fEkNnIfjuiwg7TTg1vR7339SJkS7xD1YQV0OINaXdAI5Z
	 JqF6Qw1OI+FEhFFsPgi1I4RvouBM4qJLHplh3VzMGdvMfUz+1stt8d2biBgCufSuJM
	 WwOV8VOIX9+loLffnB6EjfjYlfrQN1AT4+WpJRpLsbbNIWX+GiHAGxVUpzLcpczOKX
	 ruFdITPK1rk+Q==
To: "alonganontest@gmail.com" <alonganontest@gmail.com>
From: Alon Ganon <alon@ganon.me>
Subject: testing
Message-ID: <38c74230-0466-b950-9064-c6ae9c22f297@ganon.me>
Disposition-Notification-To: Alon Ganon <alon@ganon.me>
Date: Thu, 30 Jun 2016 16:16:23 -0400
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------C11C03B2FDE78E67D0631B61"`

**Comment by MasterPCUK** [comment]
I can see that you are using DigitalOcean. I had an issue with email from few DO IP's, since I moved away to a new IP, I never had an email going in to spam..

Not sure if it's the same here, but perhaps you could spin up new test box with another provider to see it it makes any difference.

**Comment by ChiefGyk** [comment]
any recommendations what other providers I should use?

**Comment by MasterPCUK** [comment]
I use Hetzner, works well, cheap and has a lot more ssd space for same money.:

https://www.hetzner.de/en/hosting/produkte_vserver/cx20
