### ISSUE TITLE
Add MTA S/MIME and GPG signing of outbound email

### ISSUE THREAD

**Issue by ned14** [mail-in-a-box/mailinabox#888]
My ancient email client's S/MIME signing and encryption of email doesn't understand elliptic curve crypto and RSA signing of email adds very significant bloat, so I tried hacking the https://signing-milter.org/ into Postfix's SMTP milter filters. Seems to "just work", but I'd like to give it a month of empirical testing to be sure.

If there is interest in this for mailinabox, I can summarise my config here. The harder part would be some sort of GUI letting people configure which PEM cert to use for each possible sending email address. There is also two versions of https://signing-milter.org/, the old stable one and a just written complete rewrite in C++ 14. I'm testing the old stable one which is a bit obscure to configure due to lack of decent docs, but once you've read the milter's source code all becomes clear. I can shortcut that for you by copying and pasting my config here, but I'll only bother if there is significant interest.

There is of course the philosophical question of having the MTA do strong signing of email at all, but given mailinabox tends to be used by low numbers of users, and often those users use multiple devices to send their mail, pushing the signing function onto the MTA makes a great deal of sense rather than arsing around with configuring every device. Also, putting your S/MIME crypto keys onto mailinabox is likely far more secure than putting them onto your phone :)

**Comment by yodax** [comment]
What does this add next to dmarc and spf? Besides a signed icon in a mail client?

**Comment by ned14** [comment]
dmarc and spf are for mail servers to validate identity of mail servers to one another.

S/MIME and GPG are for individual people to validate identity of themselves to one another. They ensure that a reader of email knows that nobody other than the sender sent that email. It's quite useful for mailing lists and other such places where it is easy to spoof another person. dmarc and spf don't help with that.

**Comment by JoshData** [comment]
I [tried this](https://github.com/mail-in-a-box/mailinabox/commit/910b473ea7eeb3e3413dd08a72f2d9dad18b3eaf) long ago.

I would love to have this in principle. It was one of the first issues (#20). But in practice I think the pay off is relatively low and the work for us is relatively high.

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.

**Comment by FluffoTheFox** [comment]
Please add this 😄

**Comment by scottnzuk** [comment]
> PGP is a fantastic standard and has many uses and great implementations, but if you want to sign and encrypt email with a minimum of fuss, I think you'll find as I have that S/MIME is more well-supported. Many mail clients (including the stock Mail app on iOS and Mail.app on OS X, and other popular clients such as Microsoft Outlook) can handle S/MIME out of the box with no addons. Email certificates are authenticated by a CA, like SSL certificates for the Web, instead of requiring you to rely on the PGP web of trust to authenticate others' certificates and have them authenticate yours.
> 
> You can get a free S/MIME certificate from StartSSL. Once you've created it, you can export it from your browser (be sure to use a passphrase!), email it to yourself, then open it within the iOS mail application to install it. Your Mail account settings will then offer options to use the installed certificate to sign and/or encrypt your mail.
> 
> 

(I have no affiliation with StartSSL, other than as a satisfied (non-paying) customer.)
[https://apple.stackexchange.com/questions/99935/email-encryption-options-on-an-iphone](url)

@JoshData If I was to get a developer to design this in the "gig market" Fiver.com for example, at spec you set would this allow mailinabox to support S/Mime with limited overheads to you?

IMHO PGP is great but dog to setup and use for general public and will never become main steam. S/Mime I think is the way forward?


Kind Regards
a very grateful user.

**Comment by JoshData** [comment]
I won't be including any new features in Mail-in-a-Box in the near future. The only thing I have time for is fixing existing critical bugs and getting Mail-in-a-Box to work on Ubuntu 18.04 when it is released, since Ubuntu 14.04 will reach end of life soon.
