### ISSUE TITLE
httpoxy vulnerability mitigation

### ISSUE THREAD

**Issue by drmartinsweden** [mail-in-a-box/mailinabox#890]
Affects PHP, more information can be found here: https://httpoxy.org/

Can be blocked in NGINX by adding:
fastcgi_param HTTP_PROXY "";

And in Apache:
RequestHeader unset Proxy early

I would hope this gets fixed by Apache and NGINX but this is the recommended mitigation for now.

**Comment by JoshData** [comment]
I don't think Mail-in-a-Box is vulnerable.

If anyone thinks otherwise, please post more.

**Comment by yodax** [comment]
See [here](https://owncloud.org/blog/owncloud-9-0-4-8-2-7-8-1-9-8-0-14-released/) for owncloud's take on it. 

> If possible, we recommend an immediate update to 9.0.4, 8.2.7 or 8.1.9 respectively, which each contain a patch for Guzzle.

Mail-in-a-Box is at version 8.2.3.

I do think the proxy headers have no place in being sent to any cgi or proxied back-end. By stripping these headers you reduce your attack surface.

**Comment by JoshData** [comment]
Please demonstrate that the header isn't already stripped.

**Comment by yodax** [comment]
I don't know how you can inspect what is sent between nginx and php-fpm.

I think that if owncloud say they're vulnerable, they probably know best.

**Comment by JoshData** [comment]
> I don't know how you can inspect what is sent between nginx and php-fpm.

You can write a PHP script that demonstrates the vulnerability.

I tried - php-fcgid already protects us, as far as I can tell.

**Comment by MasterPCUK** [comment]
Just checked /mail and /cloud and they are **not** vulnerable.

More info on how to check: https://serverpilot.io/blog/2016/07/19/httpoxy-vulnerability.html

**Comment by JoshData** [comment]
Thanks.
