### ISSUE TITLE
use "bash strict mode"

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#893]
```
#!/bin/bash
set -euo pipefail
```

http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by yodax** [comment]
I like the idea of this. I have been doing some testing on and off for the last few weeks. My conclusion is that it will take some work. Is it an idea to do it per flag?

**Comment by JoshData** [comment]
What do you mean per flag? Like, add one flag at a time and see how it goes?

**Comment by yodax** [comment]
Yes one flag at a time and try it. (Would be better to have tests.)

I tried: 

```
find . -name *.sh -exec sed -i "/^#\!\/bin\/bash/a set -euo pipefail" {} \;
```

Which sets the option for all bash scripts in the project. Running setup/start.sh, just completes without any message at all. I would expect no silent failures, which seemed the point of the exercise. Maybe I don't understand all the options.

Starting with -u gives some good results. We check that some variables are null, that might not have been set. Those are trivial fixes to do.

**Comment by JoshData** [comment]
I think we can also just put it at the top of functions.sh.

At some point we'll just have to take the hit of releasing it and hoping that nothing breaks, and it's probably better to package all of the risky things into one unstable release. Maybe ownCloud 9 too.
