### ISSUE TITLE
Please test - master is a 0.19 release candidate

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#898]
Hello all.

I'd appreciate it if you all would test the master branch. If it looks good, I'll release it as version 0.19.

Thanks.

**Comment by yodax** [comment]
I was running on master already apart from the round cube change. I pulled that and installed. No issues for me.

**Comment by mar1u5** [comment]
Should we upgrade ownCloud from 8.2.3 to 8.2.7 as long as we have not integrated 9.1 :grin:
Upgrade should be running without problems, because it is only fixing bugs :wink:

**Comment by JoshData** [comment]
> Upgrade should be running without problems

Famous last words!

**Comment by JoshData** [comment]
Thanks all!
