### ISSUE TITLE
Nginx cannot start because /etc/nginx/nginx-ssl.conf is missing

### ISSUE THREAD

**Issue by systemovich** [mail-in-a-box/mailinabox#905]
I upgraded to 0.18c, but it did not work because of problems upgrading ownCloud. After trying to upgrade ownCloud via the occ command, then disabling maintenance mode, and trying to upgrade ownCloud via the web gui, nginx does not want to start anymore, giving this error:

    $ sudo nginx -t
    nginx: [emerg] open() "/etc/nginx/nginx-ssl.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/local.conf:46
    nginx: configuration file /etc/nginx/nginx.conf test failed

I saw in web.sh that "/etc/nginx/nginx-ssl.conf" has been removed. How can I get around this?

**Comment by yodax** [comment]
From which version did you upgrade? Have you tried rerunning the setup? What owncloud problems were you having?

**Comment by systemovich** [comment]
I do not know which version I had before. I tried rerunning the setup several times. The last time it tried to upgrade to 0.19c.

Whenever I run the upgrade, I get the following:

> Installing ownCloud (contacts/calendar)...
> ownCloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Set log level to debug - current level: 'Warning'
> Exception: Updates between multiple major versions and downgrades are unsupported.
> Update failed
> Maintenance mode is kept active
> Reset log level to 'Warning'

Running `grep -r "nginx-ssl.conf" /etc/nginx/*` gives:

> /etc/nginx/conf.d/local.conf:   include /etc/nginx/nginx-ssl.conf;
> /etc/nginx/conf.d/local.conf:   include /etc/nginx/nginx-ssl.conf;
> /etc/nginx/conf.d/local.conf:   include /etc/nginx/nginx-ssl.conf;

**Comment by yodax** [comment]
You are probably upgrading from version 8 to 8.2 and thus skipping 8.1. There is a PR in the works that would allow skipping owncloud versions, by installing the intermediate versions.

By going to 8.1 first it should work. Would you be comfortable doing this? Probably run setup for tag 13b then go to 19. I'm guessing this will cleanup the nginx-ssl issue as well. 

Otherwise we can purge nginx and rerun the setup. (Which should fix it)

As a general advice you should update faster, there where some security update you have missed.

**Comment by systemovich** [comment]
The last version I had seems to have been v0.08. I think I will have to install a fresh box then remember to update regularly. Thanks for your help @yodax .

**Comment by yodax** [comment]
No problem! Just another bit of unsolicited advice. A new box won't solve the owncloud problem. It will hide it. Owncloud upgrades the database every install where you go one minor version higher. 

So with the restored backup you still have to do the upgrades.
