### ISSUE TITLE
miab-roundcube causing fail2ban to fail

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#911]
Possibly broken since 0.19. Posted quickly before debugging just in case fail2ban is broken for many live installs.

```
service fail2ban start
 * Starting authentication failure monitor fail2ban                                                                                                                                             WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
ERROR  No file(s) found for glob /var/log/roundcubemail/errors
ERROR  Failed during configuration: Have not found any log file for miab-roundcube jail
```

```
file /var/log/roundcubemail/errors
/var/log/roundcubemail/errors: ERROR: cannot open `/var/log/roundcubemail/errors' (No such file or directory)
```

**Comment by JoshData** [comment]
Ergh yeah. The roundcube log file isn't created until someone logs into roundcube for the first time, and until then fail2ban won't start. 

I will make a new release....

(See #767, #798.)

**Comment by JoshData** [comment]
Could you test v0.19a or master?

**Comment by yodax** [comment]
I ran setup on an existing box, that worked fine. Testing now with a brand new one.

**Comment by yodax** [comment]
No issues with a fresh box with 0.19a.

2016-08-18 15:45:09,313 fail2ban.jail   : INFO   Creating new jail 'miab-roundcube'
2016-08-18 15:45:09,313 fail2ban.jail   : INFO   Jail 'miab-roundcube' uses pyinotify
2016-08-18 15:45:09,322 fail2ban.filter : INFO   Added logfile = /var/log/roundcubemail/errors
2016-08-18 15:45:09,409 fail2ban.jail   : INFO   Jail 'miab-roundcube' started

Nice quick fix and release @JoshData!

**Comment by JoshData** [comment]
Thanks!

**Comment by anoma** [comment]
Confirmed also fixed here. Thanks for the fast turn around.
