### ISSUE TITLE
Admin page won’t show the login part and all menu items become unavailable

### ISSUE THREAD

**Issue by bogao** [mail-in-a-box/mailinabox#912]
I created a new Ubuntu 14.04 VM in the cloud.
I purchased domain names in Gandi, set the glue records and the DNS server settings.
I set the reverse DNS setting on the VM.
I changed the hostname in VM, and ran the set up script.
I set the DNSSEC and everything worked like charm...
... until today.

When I opened http://box.vividity.net/admin4 and planned to add more users, I noticed the issue as the topic title indicates.
I rebooted the server but the issue persists.

What now?

See also: https://discourse.mailinabox.email/t/admin-page-wont-show-the-login-part-and-all-menu-items-become-unavailable/1411

**Comment by yodax** [comment]
It's probably due to mixed content:

Mixed Content: The page at 'https://box.vividity.net/admin#' was loaded over HTTPS, but requested an insecure script 'http://ajax.useso.com/ajax/libs/jquery/1.11.3/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by bogao** [comment]
Issue resolved.

Root cause is just as you described, @yodax . Thanks!
Let me describe the whole story:

1. The Chinese government banned Google everything. So that accessing the web part in MIAB requiring the Google API fails;
2. The try of replacing the https://*.googleapis.com with http://*.useso.com also fails, due to the mixed content stated by @yodax above;
3. By replacing https://*.googapis.com with https://*..lug.ustc.edu.cn , issue resolved.

Better if from now on you can make a special version for users from  China mainland. Thanks in advance.

**Comment by bogao** [comment]
Script from origin 'https://ajax.aspnetcdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://box.readmore.win' is therefore not allowed access.
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery

I started to receive this error and it again started to prevent the page from loading.

**Comment by bogao** [comment]
Script from origin 'https://ajax.aspnetcdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://box.readmore.win' is therefore not allowed access.
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery

I started to receive this error and it again started to prevent the page from loading.

**Comment by yodax** [comment]
You could try and host the files on the box itself.

**Comment by bogao** [comment]
Do you mean that googleapis.com origin has such header present?

**Comment by yodax** [comment]
No, I mean download jquery and upload it to the box, reference it from there. I think that might work
