### ISSUE TITLE
Specify a Vary: Accept-Encoding header

### ISSUE THREAD

**Issue by IMcPwn** [mail-in-a-box/mailinabox#913]
Since caching is enabled, shouldn't a "Vary: Accept-Encoding" header also be set?

This would be done by adding the following to the nginx configuration for each domain inside the "server" section(s).

gzip on;
gzip_min_length  1100;
gzip_buffers  4 32k;
gzip_types    text/plain application/x-javascript text/xml text/css;
gzip_vary on;

**Comment by bronson** [comment]
What would this solve?  I think we can assume that all browsers support gzip these days, and is anyone running their MiaB behind a proxy?

It might make sense to go full HTML5 Boilerplate: https://github.com/h5bp/server-configs-nginx/blob/master/nginx.conf#L68-L123

**Comment by IMcPwn** [comment]
I was putting my Web interface behind Cloudflare, most people won't do that though so I'll close this :)

**Comment by bronson** [comment]
Well, that makes one person!  Although, I'm guessing it didn't make any noticeable difference?

Personally, I'm not against this PR, I'm just mildly anti-change...  I like the idea of a PR that rethinks and documents all the gzip settings, much like that html5 boilerplate page does.
