### ISSUE TITLE
All emails are routed to Spam Folders!

### ISSUE THREAD

**Issue by Aravin** [mail-in-a-box/mailinabox#921]
Hello Team,

I have installed Mail-In-A-Box in my VPS http://box.webepix.in

I my emails are labelled as spam for all the email service provider like Gmail, Outlook, Zoho etc..

How to avoid spam?

**Comment by yodax** [comment]
Have you checked the ip? Is it blacklisted?

**Comment by Aravin** [comment]
Yes. Checked.

My IP is not blacklisted.

![image](https://cloud.githubusercontent.com/assets/4869265/18018034/41e04af2-6bf2-11e6-9499-487a24abc40d.png)

**Comment by yodax** [comment]
Is it a new domain? Sometimes it takes a while. Otherwise I have no idea.

**Comment by Aravin** [comment]
Bro Yodax?

Any other solution?

100% of emails are delivered to spam :/ Kindly do needful.

**Comment by yodax** [comment]
You could give this a go: https://gmail.com/postmaster/

**Comment by Aravin** [comment]
Hi Yodax,

How to add DNS records for Mail-in-a-box installed domain?

**Comment by yodax** [comment]
Have you checked under the Custom DNS menu item?

<img width="206" alt="schermafbeelding 2016-08-29 om 13 25 50" src="https://cloud.githubusercontent.com/assets/5643940/18050001/2b093176-6dec-11e6-9f9f-a1f1906899b8.png">

**Comment by Aravin** [comment]
Yes @yodax, I have checked with postmaster. My IP is not blacklisted.

But still all my mails are routed to spam.

**Comment by yodax** [comment]
Check this thread: https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gmail/3rr2VB9-Mug/bWaQGE7-BQAJ

It is from this issue: https://github.com/mail-in-a-box/mailinabox/issues/855

On the google thread in the 3rd to last post someone mentions that there might be a bad apple in your ip range affecting you. You might try just switching your ip. Or wait it out.

**Comment by biermeester** [comment]
If you are using custom DNS records, you might consider changing the SPF record to:

`v=spf1 mx ~all`

Notice that I changed the default `-all` ('hard' fail) to `~all`, which is a soft fail. 

I often got complaints about emails from users getting flagged as spam on Gmail and Outlook. Also, there is a lot of bad mail forwarding going on, where forwarded mails gets SPF checked against the original server, causing them to get flagged.

**Comment by yodax** [comment]
@biermeester Shouldn't that only happen if you don't use mail-in-a-box as the smtp server? Maybe that is what is happening? (PS: We are probably from the same country :smile:)

@Aravin Are you sending via the box or your provider smtp server? Also you could check the header of the email that was send to spam, maybe that contains a hint.

**Comment by biermeester** [comment]
@yodax I've seen weird behavior from both Gmail and Outlook, where people using my Miab machine would send mail to some address, where it would get flagged as spam (Even when they explicitly white-list the sender and add them to their contacts). But when they send the same mail to any of _my_ Gmail/Outlook addresses, everything gets delivered just fine. 

After reading [this article](https://emailcopilot.com/blog/how-should-i-end-my-spf-record-all/), I decided to change my SPF records to `~all` and the complaints seem to have gone away. (Of course correlation does not necessarily mean causation :wink:  )

This is besides the bad forwarding that I mentioned.

Like you say, it _should_ only happen when mail is sent from some non-authorized domain, but we both know how messy reality can be.

(PS: Yes, you are correct. Your real name sounds a lot more Dutch than yodax, though :wink: )

**Comment by Aravin** [comment]
@yodax, I tried in both Box and SMTP server.

All mails are delivered to spam.

## Sample Header

```
Delivered-To: araclassify@gmail.com
Received: by 10.176.1.173 with SMTP id 42csp262874ual;
        Tue, 30 Aug 2016 12:04:15 -0700 (PDT)
X-Received: by 10.129.38.212 with SMTP id m203mr4797010ywm.169.1472583855332;
        Tue, 30 Aug 2016 12:04:15 -0700 (PDT)
Return-Path: <admin@webepix.in>
Received: from box.webepix.in (box.webepix.in. [139.59.13.177])
        by mx.google.com with ESMTPS id e12si13312244ybf.262.2016.08.30.12.04.14
        for <araclassify@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 30 Aug 2016 12:04:15 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin@webepix.in designates 139.59.13.177 as permitted sender) client-ip=139.59.13.177;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@webepix.in;
       spf=pass (google.com: domain of admin@webepix.in designates 139.59.13.177 as permitted sender) smtp.mailfrom=admin@webepix.in;
       dmarc=pass (p=QUARANTINE dis=NONE) header.from=webepix.in
Received: from authenticated-user (box.webepix.in [139.59.13.177])
	(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by box.webepix.in (Postfix) with ESMTPSA id 68608140071
	for <araclassify@gmail.com>; Wed, 31 Aug 2016 00:34:13 +0530 (IST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=webepix.in; s=mail;
	t=1472583853; bh=pxPjx3A73DQO2i+t6AL1zxmPCj9bSW+J3WzhaWedDwU=;
	h=Date:From:To:Subject:From;
	b=VJMVi9IPaPc6ihfKdJf3wEIB7zF+pOYI8Ewfk0Epu2vSUmhuWI5OiOo5yLeSAfl8b
	 5oGM5jRqdjxj1V4uTYX81iBtJ+nsRKmsOb2+RLs0HVzrmoc1ql776yMb/yWl+HG+Ko
	 hnYzL8dXOx4eJ6EUdtAlFP/G+VBQA2Ze5RS4VcrfyweK6XwMwTP+/XMMcaH/KUSWGQ
	 nVBM09a+uT09NcpFuC4pXwW9/ziEjjRu/GKGn3GKDJZJZ6yT6gvdgtdcYiaQ4yvUS8
	 9YBaHECBRDbudCK/h1+rHoshHL8c47axru8rSMyqFxTyjLlFsw9Wr2UBSZvCTUTddW
	 9rg68lJZrmJIQ==
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII;
 format=flowed
Content-Transfer-Encoding: 7bit
Date: Wed, 31 Aug 2016 00:34:13 +0530
From: Webepix Admin <admin@webepix.in>
To: araclassify@gmail.com
Subject: Refer your friends and businesses you know
Organization: Webepix
Message-ID: <b2bd1285d9923b870988f230bd304bb9@webepix.in>
X-Sender: admin@webepix.in
```

---
@biermeester, How to change? SPF record to `v=spf1 mx ~all`?

**Comment by biermeester** [comment]
Does not really seem to be an SPF problem, since the header says `Received-SPF: pass`. Also, since you don't know how to change the SPF record, I'm guessing you are not using an external DNS server as I am, but the one included with MiaB. This means I cannot help you, because I've never user the included one.

Other than that, I can only tell you to keep unmarking the received messages as Spam and to add the sender to the address' contact list, hoping that Gmail/Zoho will soon learn that the messages coming from your server are not Spam.

**Comment by Aravin** [comment]
Haha. ok :)

Yes, you are correct I am not using any external DNS server.

When Gmail/Zoho will completely learn? about my domain

Does it depend on domain name? because I use `.in` domain name.

**Comment by biermeester** [comment]
I cannot tell when or if Gmail/Zoho will learn. All I can tell you is that after a few months, the complaints from people using my Miab server have stopped.

**Comment by Aravin** [comment]
I have 2 queries right now.

1. How to change defult dns records? to modify `v=spf1 mx ~all`

2. How many active users are there in Miab?

**Comment by johnsonc** [comment]
@Aravin : For 1) I think you would need to add a similar entry in the Custom DNS section, and that will override the particular automated external DNS setting.

**Comment by Aravin** [comment]
@johnsonc Are you sure?

**Comment by axelsegebrecht** [comment]
Hi all, I have the same issue and read up on the various posts here and elsewhere. I am using a VPS hosted with Scaleway and all checks are passing, so I don't understand what else I can do to stay out of Gmail, etc spam folders?

Version: v0.19b
Host OS: Ubuntu 14.04 LTS
System checks: All green

`Received: by mail-tester.com (Postfix, from userid 500)	id 89D059FC80;
	Thu, 15 Sep 2016 22:23:27 +0200 (CEST)
Authentication-Results: mail-tester.com;	dkim=pass (2048-bit key;
 unprotected) header.d=1ho.st header.i=@1ho.st header.b=UPPeBYnq;
	dkim-atps=neutral
X-Spam-Checker-Version: SpamAssassin 3.4.1 (2015-04-28) on mail-tester.com
X-Spam-Level: *
X-Spam-Status: No/1.9/5.0
X-Spam-Test-Scores: DKIM_SIGNED=0.1,DKIM_VALID=-0.1,DKIM_VALID_AU=-0.1,
	PYZOR_CHECK=1.985,SPF_HELO_PASS=-0.001,SPF_PASS=-0.001
X-Spam-Last-External-IP: 163.172.178.166
X-Spam-Last-External-HELO: eu-mx-1.bebraver.uk
X-Spam-Last-External-rDNS: eu-mx-1.bebraver.uk
X-Spam-Date-of-Scan: Thu, 15 Sep 2016 22:23:27 +0200
X-Spam-Report: * -0.0 SPF_PASS SPF: sender matches SPF record	* -0.0
 SPF_HELO_PASS SPF: HELO matches SPF record	*  2.0 PYZOR_CHECK Listed in
 Pyzor (http://pyzor.sf.net/)	*  0.1 DKIM_SIGNED Message has a DKIM or DK
 signature, not necessarily	*      valid	* -0.1 DKIM_VALID Message has at
 least one valid DKIM or DK signature	* -0.1 DKIM_VALID_AU Message has a
 valid DKIM or DK signature from author's	*       domain
Received-SPF: Pass (sender SPF authorized) identity=mailfrom;
 client-ip=163.172.178.166; helo=eu-mx-1.bebraver.uk;
 envelope-from=info@1ho.st; receiver=web-ucf9wz@mail-tester.com
DMARC-Filter: OpenDMARC Filter v1.3.1 mail-tester.com 763819FE0A
Authentication-Results: mail-tester.com; dmarc=pass header.from=1ho.st
Authentication-Results: mail-tester.com;	dkim=pass (2048-bit key;
 unprotected) header.d=1ho.st header.i=@1ho.st header.b=UPPeBYnq;
	dkim-atps=neutral
Received: from eu-mx-1.bebraver.uk (eu-mx-1.bebraver.uk [163.172.178.166])	(using TLSv1.2
	with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))	(No client certificate requested)
	by mail-tester.com (Postfix) with ESMTPS id 763819FE0A
	for <web-UCf9wz@mail-tester.com>; Thu, 15 Sep 2016 22:23:25 +0200 (CEST)
Received: from authenticated-user (eu-mx-1.bebraver.uk [163.172.178.166])	(using TLSv1
	with cipher ECDHE-RSA-AES256-SHA (256/256 bits))	(No client certificate requested)
	by eu-mx-1.bebraver.uk (Postfix) with ESMTPSA id 0ACAF1A109C
	for <web-UCf9wz@mail-tester.com>; Thu, 15 Sep 2016 22:23:19 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=1ho.st; s=mail;
	t=1473971005; bh=g3zLYH4xKxcPrHOD18z9YfpQcnk/GaJedfustWU5uGs=;
	h=Date:From:To:Subject:From;
	b=UPPeBYnqy1zJWFKf1tPVYsj5q2HR+A13d2RDQnUFY7UKK1IqRE7RdQxeR+TVF9szb
	 Le2rsOYy4YHyhgVZIx3kxTNIYashZSlv2R7XoOvo/cJNftpeOfOVtwJ1HNG0Nn/dL/
	 wh9xkRQ6223fh8I3UIHh6tZTuwq9OUHBLdrAtOlohc2Vv6L8B3VW0Lx+Nxl8D1sL79
	 TkZEvGEx/FxlIhd1bn76YbVAqujYLWcyGNP/5jhkS5HlQgeFlG6/aWNJvIjp3zivjt
	 Cm94wCaDjIcCT0op4AGL/TkIakkAMRRAL0G1QKeYtywphIVUpUhgIgbNXPWAB/VntY
	 hUFrMvCParQ8g==
MIME-Version: 1.0
Date: Thu, 15 Sep 2016 21:23:19 +0100
From: info@1ho.st
To: web-UCf9wz@mail-tester.com
Subject: test
Message-ID: <86dcb388f5d1cf00a9abe6ea96ba0e4a@1ho.st>
X-Sender: info@1ho.st
Return-Path: info@1ho.st
Content-Type: text/plain; charset=US-ASCII; format=flowed
Content-Transfer-Encoding: 7bit`

**Comment by ChiefGyk** [comment]
I think it has to do with the age of the server, and putting a few messages on their boards. Mine is on Digital Ocean and finally after about four months started showing in regular inbox for gmail accounts. I actually just tested it with a friend who has gmail and has never emailed me before. So it was mission success for me. I also subscribe to mxtoolbox.com so I am not sure that may have had something to do with it.
I think it has to do with the overall reputation of your email server

**Comment by Aravin** [comment]
@ChiefGyk , Are you sure?

**Comment by alexmigf** [comment]
Is blocked here http://www.mcafee.com/threat-intelligence/ip/default.aspx?ip=139.59.13.177

**Comment by acs-ferreira** [comment]
Same issue here, i've tested 3 sends from the box to Yahoo, GMail and Free, all marked as SPAM.

SPF and DKIM are all good. Not in any blacklist, tested on https://www.blk.mx/

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.

**Comment by ahillio** [comment]
I've been considering running my own mail server... which was a dreadful thought until I discovered Mail-In-a-Box just now.  Reputation is an immediate&obvious concern... and this thread sounds like it can be very problematic to begin with but that it might then get better if you wait a few months?

Is this a common issue?  Or just a fringe-case?

Three months of getting put into spam folders is definitely something I want to avoid...
