### ISSUE TITLE
Clean spam from non-spam folders every night using a cron job

### ISSUE THREAD

**Issue by ned14** [mail-in-a-box/mailinabox#925]
Spamassassin is very good, but sometimes doesn't spot spam sent very early in the RBL detection cycle. If a nightly cron job ran spamassassin on the email in the non-spam folders, it could eliminate almost all of the spam which got through because it became blacklisted a few hours later.

Luckily there is already a program which does this for you: https://github.com/isbg/isbg

I have it running like this:

```
python isbg.py --imapinbox INBOX --imaphost localhost --imapuser "xxx@xxx.com" --passwdfilename --noreport --spaminbox Spam --delete --expunge
```

So far, works very well. You can also ask isbg to only process the last 100 emails, or only new emails since the last run, or many other variations.

**Comment by yodax** [comment]
```
--passwdfilename
```

How would we run this for all users, it looks like it needs the password of the mailbox?

**Comment by ned14** [comment]
> How would we run this for all users, it looks like it needs the password of the mailbox?

isbg is an IMAP only tool, so it needs an IMAP login. I'd suggest its setup and installation as a cronjob would be on a per-user basis.

I've noticed by the way that if you run it under the mail user account that it seems to reuse the same spamassassin mailinabox uses and the same database of spam/ham etc. I don't know if that's shared between all users on mailinabox, but if it is, then it's already good to go.

**Comment by JoshData** [comment]
This is an interesting idea but I've got to say no to this one - having email disappear from user inboxes would be very confusing.

**Comment by zatricky** [comment]
Agreed. The lack of feedback will cause issues.

For me, I might know to look in the spam folder. But for other users, they will simply think the mail system/admin is broken/incompetent.

I also cannot imagine a good way to give the user that feedback. Some antispam systems send a periodic mail listing all the spam that was blocked - an adaptation of that idea *could* work - but I don't think it is a *good* way to do it.
