### ISSUE TITLE
Where are all the "data" directories?

### ISSUE THREAD

**Issue by chris13524** [mail-in-a-box/mailinabox#929]
I'm trying to make this work with Docker. Instead of separating each program into it's own container, I'm just installing the whole setup into one container (a little against Docker's goals, but whatever).

To do this, I need to figure out where are all the data (and config generated by the admin interface) directories are so I can mount them to the host machine. I want to be able to remove the container if needed and move to another server. Would anybody know of a list or at least few of these directories are?

**Comment by IMcPwn** [comment]
/home/user-data/

**Comment by v60fan** [comment]
The name server information and zone files can be found in /etc/nsd/
