### ISSUE TITLE
Increase server_names_hash_bucket_size to 64

### ISSUE THREAD

**Issue by konklone** [mail-in-a-box/mailinabox#93]
I was getting an error when I'd run `nginx -t`:

```
root@box:~/mailinabox# nginx -t
nginx: [emerg] could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Increasing it to 64 by uncommenting this line in `/etc/nginx/nginx.conf` fixed it:

```
server_names_hash_bucket_size 64;
```

Seems to be little downside to doing this except a longer nginx startup time. I couldn't find this versioned in this repo, so perhaps it's created during the install process? Not sure of the best way to file a PR for this.

**Comment by OmgImAlexis** [comment]
I'm getting the same issue with the latest version. 

````
xo@box:~$ sudo nginx 
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found
nginx: [emerg] could not build the server_names_hash, you should increase server_names_hash_bucket_size: 64
````

**Comment by JoshData** [comment]
Do you have a particularly long domain name?

**Comment by OmgImAlexis** [comment]
Yes I do, `keepsmilingbecauseyouneverknowwhosfallinginlovewithit.info` it was working fine when I did my first install back about 2 months ago though so I'm guessing it was one of the last updates that caused this.

**Comment by JoshData** [comment]
Okay I'm upping it to 128 in the next release. Thanks for posting!
