### ISSUE TITLE
DNS PROBLEM: ping: unknown host ns1.box

### ISSUE THREAD

**Issue by chebyte** [mail-in-a-box/mailinabox#930]
Hey there, I just finished configuration, all is working as except, but the server cant resolv ns* glue records

root@box:~# ping ns1.box.bettermail.space
ping: unknown host ns1.box.bettermail.space

so in the status check I get

````
Nameserver glue records are incorrect. The ns1.box.bettermail.space and ns2.box.bettermail.space nameservers must be configured at your domain name registrar as having the IP address 67.205.141.237. They currently report addresses of [Not Set]/[Not Set]. It may take several hours for public DNS to update after a change.
````

but when I make ping from my computer, is ok

````
ping ns1.box.bettermail.space
PING ns1.box.bettermail.space (67.205.141.237): 56 data bytes
64 bytes from 67.205.141.237: icmp_seq=0 ttl=54 time=334.473 ms
````

when I added dns google to resolv.conf ip is working, but the server overwrite this file always

any way to update dns cache?

thanks!

**Comment by anandatheerthan** [comment]
Hi, How did you resolve this.
