### ISSUE TITLE
Email storage.

### ISSUE THREAD

**Issue by futureinapps** [mail-in-a-box/mailinabox#933]
Hi, i extremly wanna know where are emails saving? How can i acess saved emails?

**Comment by IMcPwn** [comment]
/home/user-data/mail/mailboxes/[domain]/[account]

**Comment by futureinapps** [comment]
Ok, thx, i have another problem, i install wildcard certificate, and now have error in admin panel: 

Certificate has a problem: The certificate is missing an intermediate chain or the intermediate chain is incorrect or incomplete. (/home/user-data/ssl/ssl_certificate.pem: CN = *.mydomain.com error 20 at 0 depth lookup:unable to get local issuer certificate )

**Comment by IMcPwn** [comment]
No experience using wildcard certificates with mailinabox. Hopefully someone else can help you out.

**Comment by yodax** [comment]
When installing the certificate did you also install the intermediate chain for the certificate? Not all certificate authorities are directly trust by the different root programs. They require an intermediate certificate (that is trusted by the root) to work. You need to get that from your ssl provider and paste it in the intermediate box on the admin console.

I don't know for sure that mail-in-a-box works with wildcard certificates.

**Comment by JoshData** [comment]
> I don't know for sure that mail-in-a-box works with wildcard certificates.

A manually installed wildcard certificate _should_ work fine.
