### ISSUE TITLE
Mail Storage Encryption

### ISSUE THREAD

**Issue by mironoff111** [mail-in-a-box/mailinabox#934]
Hi!

Is there any possibility to encrypt all the stored mail (/home/user-data/mail/mailboxes/[domain]/[account]) like files in OwnCloud are encrypted  (encryption password is user's one). I think it can improve security and safety of the server's owner in the case that somebody else has access to the server (for example, the police)

**Comment by jkaberg** [comment]
Dovecot Pro has this, https://blog.open-xchange.com/2016/07/20/encryption-at-rest/

Unsure if it will ever be available in the open source edition

**Comment by IMcPwn** [comment]
Probably not. ``security.md``` states

> The primary goal of Mail-in-a-Box is to make deploying a good mail server easy, so we balance ― as everyone does ― privacy and security concerns with the practicality of actually deploying the system. That means we make certain assumptions about adversaries. We assume that adversaries...
> 
> * Have not been given Unix accounts on the box (i.e., we assume all users with shell access are trusted).

https://github.com/mail-in-a-box/mailinabox/blame/master/security.md#L16

**Comment by mironoff111** [comment]
@IMcPwn I can't be sure that nobody has the physical access to the server (it's dediacted and located in the basement).

**Comment by IMcPwn** [comment]
I wouldn't know how to implement this. If I could it wouldn't be my call. @joshdata is the maintainer of this project.

**Comment by JoshData** [comment]
See #27.

**Comment by jookk** [comment]
Encrypt home dir and use it as mail storage?
