### ISSUE TITLE
alias domain generates bounces

### ISSUE THREAD

**Issue by jalogisch** [mail-in-a-box/mailinabox#935]
First: thank you for the work you had already invested. 
# Description

If you define an alias domain, I notice that all mail for this alias domain is accepted first and after that tried to deliver to the destination domain. If the recipient does not exist you generate a bounce.
# Reproduce Steps
1. add alias domain to existing domain
2. send mail (from outside e.g. not from your box) to non-existing recipient

**Comment by JoshData** [comment]
This sounds like expected behavior.

**Comment by jalogisch** [comment]
Hej @JoshData 

to be honest - no because all MIAB alias domains do [backscatter](https://en.wikipedia.org/wiki/Backscatter_(email)) bounce and can be used to abuse or attack other. 

If the target for the alias is a local domain the final recipient should be resolved and the mail should be only accepted if that final recipient is present. 

Sorry I'm not able to write down the SQL that is needed to archive this but that should be considered to be changed.

**Comment by JoshData** [comment]
I'm open to changing anything, but someone is going to have to do the work to change it for it to happen.

**Comment by jalogisch** [comment]
I tried to find an answer to improve this proper project. As I had learned my Mail-Postmaster-Skills with exim based systems I have some issues finding the right way with postfix. 

Found this [serverfault](http://serverfault.com/a/793202) answer and think that should might solve the issue. 

Did you see - with your experience any issues with that?

**Comment by JoshData** [comment]
Which? There are two suggestions there.

**Comment by jalogisch** [comment]
Personal I would prefer **reject_unverified_recipient** but, I can see the Impact that this might have to systems with many aliases that has final external recipients. 

But I also know that if I just added this myself on the next update I should not forget to re-add it.

Taking ``virtual_alias_domains = $mydomain`` into account might not have such a big impact but I can't predict how this will impact the system.

**Comment by JoshData** [comment]
Well if you think you found an improvement, try it and report back! 

On March 29, 2017 10:05:23 AM EDT, Jan Doberstein <notifications@github.com> wrote:
>Personal I would prefer **reject_unverified_recipient** but, I can see
>the Impact that this might have to systems with many aliases that has
>final external recipients. 
>
>But I also know that if I just added this myself on the next update I
>should not forget to re-add it.
>
>Taking ``virtual_alias_domains = $mydomain`` into account might not
>have such a big impact but I can't predict how this will impact the
>system.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/935#issuecomment-290100358

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
