### ISSUE TITLE
Thunderbird Autoconfiguration

### ISSUE THREAD

**Issue by chris13524** [mail-in-a-box/mailinabox#941]
I'm trying to setup Thunderbird [autoconfiguration](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration). This requires an XML file hard coded at this path: `/mail/config-v1.1.xml`. When I try to make a new domain (`autoconfig.mail.domain.com`) and point it to my box (as well as adding the appropriate alias and creating the directory through the web interface). If I create a `mail` folder in `autoconfig.mail.domain.com` and try to access the index page (`autoconfig.mail.domain.com/mail`) I am taken to Roundcube. This would normally be appropriate if I just used `domain.com/mail`, but as I am using another subdomain, it shouldn't be using the Roundcube stuff.

Is there any way I can add this configuration file?

**Comment by chris13524** [comment]
I was able to symlink the file into the Roundcube directory, but I don't think the `/mail` path should be for all domains.

**Comment by JoshData** [comment]
This should already be working as we do it here:

https://github.com/mail-in-a-box/mailinabox/blob/65add24e2abcc0015d7a49645218e13e37e7d5b6/setup/web.sh#L71

**Comment by chris13524** [comment]
@JoshData How do I use this?

**Comment by JoshData** [comment]
I'm saying, we already have what you're proposing. (If it's not working, that's possible...)

**Comment by chris13524** [comment]
Yes, but how do I use it? There is no domain I can use afaik for the autoconfig.

**Comment by JoshData** [comment]
The autoconfig _is there_. Just go to Thunderbird and make a new account.

**Comment by chris13524** [comment]
Ok, I'll try after my domain finishes transferring.

**Comment by chris13524** [comment]
I deleted my symlink, and removed the DNS entries for the autoconfig domain. After doing this, Thunderbird will not autoconfig. The XML file is no longer available: https://autoconfig.neonorb.com/mail/config-v1.1.xml

**Comment by chris13524** [comment]
I can confirm however, that the XML is available here: https://mail.neonorb.com/.well-known/autoconfig/mail/config-v1.1.xml However, this is not where Thunderbird looks for the configuration.

**Comment by chris13524** [comment]
Ohh, I see what's happening. Thunderbird checks both these locations:

http://autoconfig.DOMAIN.com/mail/config-v1.1.xml
http://DOMAIN.com/.well-known/autoconfig/mail/config-v1.1.xml

The first one doesn't exist (which I added before to make it work).

I have neonorb.com pointing to another server (via custom DNS). This causes the second option to not work either.

I suppose many people would be using their main domain for other purposes, maybe the first option would be something to add? :)

**Comment by JoshData** [comment]
Now that we know why it's important, it would make sense to add it. But... Because it works on its own subdomain, it would be a lot of work to get right. It's probably easier if you can just add the XML file to your other server (if you can, you could proxy the HTTP request to the MiaB file).

**Comment by chris13524** [comment]
You should just be able to point autoconfig.DOMAIN.com to another directory (like the Static Web Hosting cpanel page) and symlink the config file. Currently this does not work (afaik), as `/mail` resolves to the Roundcube directory, regardless of the domain. This could be changed though.

The other option would be to symlink the configuration file into the Roundcube directory (as I did before) and add the domain.

**Comment by chris13524** [comment]
I had to do this again on another sever.

So for future reference, I added this DNS record: `autoconfig.DOMAIN IN CNAME box.DOMAIN`

And a symlink: `ln /var/lib/mailinabox/mozilla-autoconfig.xml /usr/local/lib/roundcubemail/config-v1.1.xml`

This makes this autoconfig file available for Thunderbird: http://autoconfig.DOMAIN/mail/config-v1.1.xml

**Comment by jvolkenant** [comment]
So in my case, I use m.example.com as my MIAB.  I use otherdomain.com for my email.  I point otherdomain.com to my house (not miab)  In order for me to use Thunderbird autoconfig I needed to do two things:

I had to add an alias for "@autoconfig.otherdomain.com" to me@otherdomain.com and then added the following to nginx config for autoconfig.otherdomain.com:

#autoconfig.otherdomain nginx section
location = /mail/config-v1.1.xml {
alias /var/lib/mailinabox/mozilla-autoconfig.xml;

After those two changes Thunderbird Autodiscover worked for me.

**Comment by jvolkenant** [comment]
Finally wrapping my head around this feature discussed here #608 

I created an alias email address for autoconfig.otherdomain.com (so I would get an SSL cert)
Added this file:
```
root@m:~# cat /home/user-data/www/custom.yaml 
autoconfig.otherdomain.com:
  redirects:
    ^/mail/config-v1.1.xml:  https://m.example.com/.well-known/autoconfig/mail/config-v1.1.xml
```
ran this:
```
~/mailinabox/tools/web_update
```

And now my email@otherdomain.com hosted on my miab (example.com) works with Thunderbird autoconfig.

Can anyone point me in the direction for adding autoconfig.example.com during install? (like box.example.com, example.com, www.example.com, and add autoconfig.example.com as well)

**Comment by jvolkenant** [comment]
@chris13524, can you test to see if this fixes your problem? 
https://github.com/jvolkenant/mailinabox/tree/client_autoconfig_fixes

Thunderbird and [ActiveSync Autodiscover](https://testconnectivity.microsoft.com) with [Nine](https://play.google.com/store/apps/details?id=com.ninefolders.hd3&hl=en_US) work with my additional hosted email domains.

**Comment by chris13524** [comment]
@jvolkenant I cannot confirm that this works. I installed both patches and then ran a few DNS updates (i.e. adding some txt subdomain records and running `dns_update` directly), but I can't get the new subdomain to show up. I also don't see any mention of "autoconfig" on the External DNS page.

Let me re-iterate my setup: MIAB is located at box.neonorb.com and I have neonorb.com have an A record pointing to another server. I'd expect this patch to create the endpoint: `autoconfig.neonorb.com/mail/config-v1.1.xml`, but I do not see this happening.

I see your change [only takes affect](https://github.com/jvolkenant/mailinabox/blob/603ffde020045b81ad0a82d74a04c40d694731c5/management/dns_update.py#L294) if the domain is not the "PRIMARY_DOMAIN". This would not work with my case, but perhaps I'm missing something? I'm not very familiar with the code here, so am just giving my first impression.

**Comment by jvolkenant** [comment]
Yea, we would need to add it for all domains then.  That might then cover all cases. I'll look into updating the PR for that next week.

**Comment by JoshData** [comment]
The primary domain (e.g. box.neonorb.com) cannot have an A record, so I don't think there is a reason to add the autoconfig subdomain CNAMEs. But, anyway, I think your patch should be working for @chris13524's setup since neonorb.com isn't the primary domain.

**Comment by jvolkenant** [comment]
@chris13524, it sounds like you need to restart the mailinabox service (service mailinabox restart).  I just tested your case on my test VM (although its running Bionic, it works just fine).

My test MIAB is m.fireislandak.com (not box.fireislandak.com, it's an old habit)
I firstly set fireislandak.com to 1.2.3.4.
Added nginx patch and dns_update.py patches
Restarted mailinabox management service
ran tools/dns_update and tools/web_update

root@m:~/mailinabox# grep CNAME /etc/nsd/zones/fireislandak.com.txt
autoconfig      IN      CNAME   m.fireislandak.com.
autodiscover    IN      CNAME   m.fireislandak.com.

Tested autoconfig with Thunderbird, worked.  Tested ActiveSync autodiscover with Nine, worked fine.

**Comment by chris13524** [comment]
@jvolkenant Ah, yes! That works! Can confirm this PR works.

@JoshData Sorry, I was thinking that the primary domain in my case would be neonorb.com not box.neonorb.com.

**Comment by jvolkenant** [comment]
@chris13524 Can you test again, I've updated the PR.

Thanks!

**Comment by chris13524** [comment]
@jvolkenant Sorry for the delay. The two new commits are now adding the ability to provision TLS certs for autoconfig.* and autodiscover.*. Though perhaps it is worth noting that I don't see either of these for box.neonorb.com

**Comment by jvolkenant** [comment]
@chris13524 Were you expecting to see autoconfig.box.neonorb.com and autodiscover.box.neonorb.com?  Do you use an email@box.neonorb.com?


I'd have to take a look to see how subdomains might do lookup with Thunderbird/Activesync, although autoconfig.neonorb.com & autodiscover.neonorb.com might be part of the lookup domains that are used.

**Comment by chris13524** [comment]
@jvolkenant I was expecting to see them there (box.neonorb.com) because it is possible to make email accounts there, no?

I don't use it, but if we are being consistent here...

**Comment by chris13524** [comment]
Alright, sounds like this issue is resolved!

**Comment by jvolkenant** [comment]
@ringe , have you tested #1467?  It would help to get your feedback.
