### ISSUE TITLE
Nameserver glue records (and other DNS things) randomly working and not working

### ISSUE THREAD

**Issue by chris13524** [mail-in-a-box/mailinabox#942]
I'm trying to setup my DNS server stuff. I've got my domain, `neonorb.com` (HostGator), and set the nameservers to Digital Ocean's nameservers (`ns1/2/3.digitalocean.com`). On the Digital Ocean control panel, I set `neonorb.com` and `mail.neonorb.com` to the box's nameservers (`ns1/2.mail.neonorb.com`), and did a few other things. I'm no expert with DNS so I probably am doing this wrong.

So the nameservers go something like this:
`HostGator -> Digital Ocean -> Box`

My problem is that on the status page, some times all the checks are AOK (the ones I need), and then literally 10 minutes later, without changing anything, some go bad. 10 minutes later, other are bad and some are good. 10 minutes later, they are all good again. I've been watching all day, tried rebooting, reinstalling the DNS all kinds of things. I didn't touch it for an entire Netflix movie, pausing it every 10 minutes and the error messages were different.

The main offenders are these (on and off like I said):
- Nameserver glue records (ns1.mail.neonorb.com and ns2.mail.neonorb.com) should be configured at your domain name registrar as having the IP address of this box (67.205.132.194). They currently report addresses of [Not Set]/67.205.132.194. If you have set up External DNS, this may be OK.
- This domain must resolve to your box's IP address (67.205.132.194) in public DNS but it currently resolves to [Not Set]. It may take several hours for public DNS to update after a change. This problem may result from other issues listed above.
- This domain's DNS MX record is not set. It should be '10 mail.neonorb.com'. Mail will not be delivered to this box. It may take several hours for public DNS to update after a change. This problem may result from other issues listed here.

I'm not sure if the issue is with Mail in a Box, but it's probably my DNS stuff.

`neonorb.com` zone file:

```
$ORIGIN neonorb.com.
$TTL 1800
neonorb.com. IN SOA ns1.digitalocean.com. hostmaster.neonorb.com. 1474323897 10800 3600 604800 1800
neonorb.com. 1800 IN NS ns1.mail.neonorb.com.
neonorb.com. 1800 IN NS ns2.mail.neonorb.com.
neonorb.com. 1800 IN A 192.241.130.20
autoconfig.neonorb.com. 1800 IN CNAME autoconfig.mail.neonorb.com.
```

`mail.neonorb.com` zone file:

```
$ORIGIN mail.neonorb.com.
$TTL 1800
mail.neonorb.com. IN SOA ns1.digitalocean.com. hostmaster.mail.neonorb.com. 1474325870 10800 3600 604800 1800
mail.neonorb.com. 1800 IN NS ns1.mail.neonorb.com.
mail.neonorb.com. 1800 IN NS ns2.mail.neonorb.com.
mail.neonorb.com. 1800 IN A 67.205.132.194
```

Here are the nameserver zone files:

```
$ORIGIN ns1.mail.neonorb.com.
$TTL 1800
ns1.mail.neonorb.com. IN SOA ns1.digitalocean.com. hostmaster.ns1.mail.neonorb.com. 1474336004 10800 3600 604800 1800
ns1.mail.neonorb.com. 1800 IN NS ns1.digitalocean.com.
ns1.mail.neonorb.com. 1800 IN NS ns2.digitalocean.com.
ns1.mail.neonorb.com. 1800 IN NS ns3.digitalocean.com.
ns1.mail.neonorb.com. 1800 IN A 67.205.132.194
```

**Comment by v60fan** [comment]
The standard setup would be to create glue records at host gator which point to your MIAB IP address. You create 2 glue records as I think you know. Then, after some propagation time, your MIAB will take over DNS for your domain.

You do not need to use Digital Ocean's DNS at all.

I'm not sure this is an issue.

Feel free to contact me (v60fan) on the Discourse forum if you'd like more help.
https://discourse.mailinabox.email
