### ISSUE TITLE
dnspython exception with IPv6 addresses

### ISSUE THREAD

**Issue by GeorgeTG** [mail-in-a-box/mailinabox#945]
After fresh install,  I cannot load the status page, or the SSL page.
I get the following errors:

`line 65, in run_checks#012    run_domain_checks(rounded_values, env, output, pool)#012  File "/home/georgetg/mailinabox/management/status_checks.py", line 312, in run_domain_checks#012    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)#012  File "/usr/lib/python3.4/multiprocessing/pool.py", line 268, in starmap#012    return self._map_async(func, iterable, starmapstar, chunksize).get()#012  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get#012    raise self._value#012TypeError: __str__ returned non-string (type bytes)
`

Edit: This is a dnspython problem.
https://github.com/rthalley/dnspython/blob/master/dns/rdtypes/IN/AAAA.py#L37
this function returns `bytes` instead of `str`, and this is the function that is called to implement `__str__`

**Comment by GeorgeTG** [comment]
#944 is the same as this

See also:
https://github.com/rthalley/dnspython/issues/204

**Comment by GeorgeTG** [comment]
Temporary hack:
https://github.com/GeorgeTG/mailinabox/tree/dnspythonhack

**Comment by JoshData** [comment]
I'm not able to reproduce the problem. Could you run

    pip3 freeze|grep dnspython

and let me know what output you get?

**Comment by JoshData** [comment]
Just flagging that https://discourse.mailinabox.email/t/status-check-fails-on-newly-created-box/1512 is the same issue.

**Comment by ma0ho** [comment]
Ok, pull request #947 should fix this issue.

**Comment by jeroenj** [comment]
@JoshData I'm running against the same issue when running the `setup/start.sh` script on an existing box.

Installed dnspython version:

```
jeroen@box:~$ pip3 freeze | grep dnspython
dnspython==1.14.0
dnspython3==1.14.0
```

**Comment by JoshData** [comment]
Interesting. Prior to running updates I had:

    # pip3 freeze | grep dnspython
    dnspython3==1.12.0

And no problems. After running `mailinabox` to update everything I had:

    dnspython==1.14.0
    dnspython3==1.12.0

and now I have the issue. First, it seems bad that two dnspython packages are installed.... but 1.14.0 has probably overwritten/overridden the files for 1.12.0. Second, I'm not sure what triggered the update of dnspython. We install `dnspython3` from apt. Something else we use must have brought in the newer `dnspython` (without the `3`) as a dependency.

**Comment by JoshData** [comment]
I've posted v0.20 to correct this issue.
