### ISSUE TITLE
Certificate provider recommendations (StartSSL and WoSign)

### ISSUE THREAD

**Issue by yodax** [mail-in-a-box/mailinabox#950]
Mozilla will probably drop support for certificates signed after a to be determined date in the future for StartSSL and WoSign.

Shall we remove them from the recommended providers? Or remove the recommended providers all together?

Click here for mozilla's investigation: https://docs.google.com/document/d/1C6BlmbeQfn4a9zydVi2UvjBGv6szuSB4sMYUcVrR8vQ/edit#heading=h.cb0l2fjfht30

Google contributed to the investigation and will probably follow mozilla in this I think.

**Comment by JoshData** [comment]
Yes, good call.

I don't think we need to offer recommendations anymore, since in most cases the box handles the cert now. If you/anyone has a particular recommendation in place of StartSSL/WoSign, I'm also OK with adding it.

**Comment by MariusBluem** [comment]
I'm on it 😉

**Comment by MariusBluem** [comment]
Fix is in 🙌

**Comment by yodax** [comment]
Apple is no longer trusting WoSign from 2016-09-19: https://support.apple.com/en-us/HT202858

```
To avoid disruption to existing WoSign certificate holders and to allow their transition to trusted roots, Apple products will trust individual existing certificates issued from this intermediate CA and published to public Certificate Transparency log servers by 2016-09-19
```
