### ISSUE TITLE
Password reset via webmail not working

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#966]
I can reset passwords via the admin panel, but when users reset it themselves in the web interface for non-admins it fails for some reason. This user happens to be an admin as well and I confirmed the bug for myself. using a random password with special characters

**Comment by josephbu** [comment]
@ChiefGyk Can you clarify which interface a non admin user is trying to use to reset password?

I can confirm a non admin user can change password ok via the RoundCube webmail interface.

**Comment by josephbu** [comment]
@ChiefGyk just following up, is this still an issue? Are you able to provide any more details?

**Comment by JoshData** [comment]
Closing because it's been a while. Feel free to re-open.
