### ISSUE TITLE
Update from v0.19b to v0.20

### ISSUE THREAD

**Issue by gitacticia** [mail-in-a-box/mailinabox#968]
We have rollen the update method and lost the cloud service.
We have reverted our snapshot and are digging ...

**Comment by gitacticia** [comment]
When rerolling the upgrade from 0.18c to 0.20 we got : 

Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.7.1
Update successful
Turned off maintenance mode
Reset log level to 'Warning'
ownCloud is already latest version

My sysadmin said "Turned off maintenance mode" didn't appeared in his upgrade ...

Still digging !

**Comment by gitacticia** [comment]
Ok, he lost that point : 

> No command 'ownCloud' found, did you mean:
>  Command 'owncloud' from package 'owncloud-client' (universe)
> ownCloud: command not found

**Comment by gitacticia** [comment]
So, the Maintenance mode was kicked out, but owncloud, didn't restarted ... Digging the code now ...

**Comment by gitacticia** [comment]
The cloud works well while the error occurs. Still working well ... Digging ...

**Comment by bronson** [comment]
Hi, what's the status now?  Don't leave us hanging.  :)

**Comment by gitacticia** [comment]
Still on a todo list but not yet planed. Only the prod server fails. So, we have to fork the VM and replay the update process. But - it's freaking bad - we have no time allowed by the boss ... I propose to close #968 because I'm guessing it is not really linked to miab. An admin of us has forked a previous version. He had left now with no documentation. It's hard to find what/where/when/why ...
