### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Snarkly** [mail-in-a-box/mailinabox#969]
Why does a person have to pay 12.00 a month for a server? I thought a person could run an email server on their own PC. I can't even afford 12.00 a month, I'm poor. Is there a way to get mail in a box without having to pay for a sever?

**Comment by biermeester** [comment]
You don't have to rent a server. You can set one up at at home, providing you have a static IP address and an ISP that doesn't block any of the needed ports. And your server needs to be up and running 24/7, of course.

**Comment by JoshData** [comment]
Computers on most residential networks are blocked from sending mail both on the sending end (e.g. your ISP blocking port 25) and on the receiving end (by blacklists) because residential computers are all too often hijacked to send spam. Your home IP address is also probably dynamic and lacks configurable “reverse DNS.” (see https://mailinabox.email/guide.html) If any of those four issues apply to you, then you won't be able to send mail reliably from your own computer.

**Comment by Snarkly** [comment]
Thanks guys but I have more questions now. 1 I use other ports now and I can send and receive through them, so I was wondering if you can set up mail in a box to use another port instead of 25?
2 Why does it have to run 24/7? Couldn't you just tell the people you host your own and you only accept mail between certain times. example between 9am - 5pm, that way it wouldn't have to run all the time.

**Comment by yodax** [comment]
You can get away with running it on a hosted machine slightly cheaper. I run mine for 2,99Euro a month on Scaleway. (There are some issues with ipv6, check the forum. It's probably better to disable it for a mail sever anyway, for now that is, until ipv6 is more common)

Looking at the questions being asked, I'm not sure you would have an enjoyable experience running your own server. That doesn't mean it can't be done. 

I have never considered running a mail server during office hours. I think people sending mail to you might not understand they can only send mail to you during that time. However if your mail server is down, their smtp server will hold on to it for a while and retry. Receiving email will not be the biggest problem, most likely nobody will accept your email. Like it was said before, most providers will think it is spam.

Some domains that are registered require a highly available redundant DNS server in their terms of service. For instance .nl domains require a separate secondary DNS server. 

There are also costs for registering a domain name. If you do it with a cheaper provider, you are most likely not going to have a good time. 

My advice would be; don't host this at home. If you want a custom domain you can do that with a lot of providers. With some you get email for free (limited) with a domain name. This will cost a lost less.

**Comment by Snarkly** [comment]
Thanks for you replies but I've decided this email isn't for me. Sorry but I can't promote it any more.
