### ISSUE TITLE
Externally hosted sub domain with Letsencrypt support

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#973]
I am trying to host a local HTTPS service using a custom DNS A record (trivial) but I am having no luck with the Letsencrypt side of things.

I had assumed that I could request locally a second Letsencrypt certificate but limited to the subdomain but that does not work with errors such as:

(Obfuscated)
```

Domain: domain.xxx
Type: unauthorized
Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
Requested
1234.1234.acme.invalid
from MIABip:443. Received certificate containing
'miab.xxx, domain.yyy, all-other-miab-hosted-domains'
```

Since that error messages contain responses from MIAB and not the local request it is obvious I am on the wrong track.

Can anyone suggest the best route to use a domain with both a dynamic DNS A record for hosting local services on DSL whilst maintaining MIAB mail and general hosting for the top level domain?

Appreciated.

**Comment by JoshData** [comment]
If the A record is pointing elsewhere, the box cannot help you. You have to use a Let's Enctypt tool on whatever machine the A record resolves to.

**Comment by anoma** [comment]
Thanks for the confirmation. That pushed me to recheck everything and discover I was simply making the wrong request to Letsencrypt .
