### ISSUE TITLE
"Upgrade Packages" button in the status check?

### ISSUE THREAD

**Issue by bronson** [mail-in-a-box/mailinabox#977]
Just checking, is there any design decision behind the lack of an "Upgrade Packages" button on the Status Checks page?  It would either report "success" or "failed, please ssh to your box and manually run `sudo apt-get upgrade`"

Doesn't seem too hard to add, and it would reduce the number of times I'm sshing to my box by 75%.

![screen shot 2016-10-17 at 1 40 48 pm](https://cloud.githubusercontent.com/assets/1776/19455441/df39afda-9471-11e6-8164-a8872a18225d.png)

I'd look into it unless there's a reason not to.

**Comment by JoshData** [comment]
There are always reasons not to do something! 

You have to make apt non interactive. And it would be hard to guarantee that its output doesn't get lost since it could break the management daemon during the upgrade. And if it does, will apt itself get killed? 

On October 17, 2016 5:04:24 PM EDT, Scott Bronson <notifications@github.com> wrote:
>Just checking, is there any design decision behind the lack of an
>"Upgrade Packages" button on the Status Checks page?  It would either
>report "success" or "failed, please ssh to your box and manually run
>`sudo apt-get upgrade`"
>
>Doesn't seem too hard to add, and it would reduce the number of times
>I'm sshing to my box by 75%.
>
>![screen shot 2016-10-17 at 1 40 48
>pm](https://cloud.githubusercontent.com/assets/1776/19455441/df39afda-9471-11e6-8164-a8872a18225d.png)
>
>I'd look into it unless there's a reason not to.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/issues/977

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bronson** [comment]
OK, that's true.

Making apt non-interactive is pretty easy, just run it with `--assume-yes`.  If anything non-trivial comes up, it will error out.

I don't think the management daemon could break.  I mean, no package would actually kill it during an upgrade (including python), and any overwritten files won't take effect until it's restarted.

Of course, there's probably some aspect of the upgrade that I'm missing...  Have you seen it break in the past?

I *think* it's possible to do safely...  but I don't know the big picture as well as you do.

**Comment by stan3** [comment]
Might be an idea to use aptd.

**Comment by bronson** [comment]
True, or the unattended-upgrades package.  I'll have to do some research.

**Comment by wsteitz** [comment]
What about using the unattended-upgrades package (https://help.ubuntu.com/community/AutomaticSecurityUpdates and https://wiki.debian.org/UnattendedUpgrades), at least for security related packages. This automatically updates the system. 
We could then use "apt-listchanges" to email the user about installed packages

**Comment by yodax** [comment]
I use unattended-upgrades, it checks and installs updates for me at 6:00AM. If there are updates it emails the list of updates that where installed with the corresponding log. If the updates require a reboot, I have configured it to reboot the machine. Works like a charm.

Building something for this might not be very easy though, I have seen wildly different apt configurations among cloud providers. We could point people in the right direction.

**Comment by bronson** [comment]
I guess the question for everyone is:

Ideally, what would you prefer: hit a button to upgrade, or have it be fully automatic?

**Comment by bronson** [comment]
Closing since it sounds like nobody's very interested.  :)

**Comment by mabkenar** [comment]
@bronson 
> I guess the question for everyone is:
> 
> Ideally, what would you prefer: hit a button to upgrade, or have it be fully automatic?

IMHO both options are good, definitely better than the current state (that is, to connect to the server via SSH to do an upgrade in the command line).

An unattended upgrade/reboot as @yodax wrote could *theoretically* break a running mail server, and the admin could miss it (especially if they **don't** use the web-client for checking their email). 

Therefore, I think having (i) update notifications sent via email plus (ii) an "Upgrade" button in the admin panel might be a good compromise. When the admin presses the button, they would wait for a few minutes and manually check if the server is still up and running. 

This will keep the server reasonably up-to-date while removing the possibility of bad surprises.

**Comment by jacebenson** [comment]
If nothing else. This should be listed in the docs/tips pages and how to set it up
