### ISSUE TITLE
Add Verification Services and Secondary DNS pages to the wiki?

### ISSUE THREAD

**Issue by bronson** [mail-in-a-box/mailinabox#981]
I don't think I have permission to edit the wiki.

I dashed the following two pages together because I thought it would be helpful.  Was hoping to put them somewhere where others could add to them.

Can I submit them somewhere?

**Comment by bronson** [comment]
# Verification Services

## Blacklist Checkers

Once your ISP gives you your IP address, make sure it isn't already on
spam blacklists.

(If so, tell them to give you another one.
It's a long and futile task to try to remove an address from the blacklists.)

* https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a94.76.202.152&run=toolpage#
* https://ers.trendmicro.com/reputations
* http://www.barracudacentral.org/lookups


## DNS Checkers

Once you've set everything up at your ISP and DNS provider (congratulations!),
you can use these tools to verify that things look OK.

* https://pingability.com/zoneinfo.jsp


## Deliverability Checkers

These services ask you to send them a message, then they tell you how spammy you look.
This verifies your DKIM and SPF records, and that your mail server can send.

* http://dkimvalidator.com/
* http://www.mail-tester.com/
* https://www.unlocktheinbox.com/mail-tester/

For dkimvalidator, make sure to send something unique in the body.
Otherwise they'll claim you're a little spammy.


### Other Checkers

Since you're running mail-in-a-box, you're probably using LetsEncrypt for SSL
and are guaranteed to get an A+ on the report card.  But, if you're
using your own cert, it's worth checking:

* https://www.ssllabs.com/ssltest/analyze.html

**Comment by bronson** [comment]
# Secondary DNS

If your email server goes down, no big deal, your mail will be held for a few hours or days before bouncing.
If your DNS server goes down, however, all your sites are down hard.  It makes sense to have redundant DNS.

Having secondary nameservers does make it a little harder to tweak your DNS configuration.
It's advisable to run your mail-in-a-box for a while to be sure that you're happy with
the way everything is set up.  Once you haven't thought about your box for a few months,
*then* it's probably time to set up your secondaries.


#### puck.nether.net

http://puck.nether.net/dns

This service appears to be a long-term pet project.  It's simple, fast, and straightforward.

* Open "Custom DNS" on your mail-in-a-box's admin page.
* Add `puck.nether.net` to Hostname in the Secondary Nameserver section.
  (because the transfer will originate from puck.nether.net, there's no need for a separate xfr section)
* Click "SIGN ME UP!" behind the above link and sign up.
* Click "Add a new domain".  Enter your domain and IP address (the IP address can be found
  on the Status Checks page: *Domain resolves to box's IP address. [int.u32.net ↦ 173.233.67.174]*)
* Your zone should be transferred within a few seconds.  Now ensure the secondary works (todo: describe how).
* Log into your registrar and change your domain server from ns2.box.example.com to
  puck.nether.net.
* Now your domains will stay up even if your box goes away for a few hours.


#### 1984's FreeDNS

https://www.1984.is/product/freedns/

(if that page doesn't make sense, select English in the upper right.  If it still doesn't
make sense, that's OK, you don't need to know much DNS to host mail-in-a-box.)

1984 is a reasonably large Iceland-based ISP.  They want to host your DNS
because they think that you'll like their service and use them for other products.

Follow the instructions above, except:

* sign up at 1984.is
* Add `ns2.1984.is xfr:93.95.224.6` to Hostname.
* Use any of their nameservers for your secondary (they provide a list).


#### Others

* If you're registered at Gandi, you're eligible to use their secondary:
  https://wiki.gandi.net/en/domains/dns#gandi_s_secondary_dns

**Comment by bronson** [comment]
(I'm not real happy with the Secondary DNS page but I figure it's better than nothing...  Can clean it up in the future)

**Comment by JoshData** [comment]
Could put it on the website: https://github.com/mail-in-a-box/mailinabox.email

**Comment by bronson** [comment]
That feels a little more "formal" than this merits...  but sure.  I'll send a PR there.

**Comment by bronson** [comment]
Just making sure: you're not using a static site generator?  You're editing the HTML by hand?

**Comment by JoshData** [comment]
Correct. (We can change that but... since it's just a few pages I don't think there's an advantage yet.)
