### ISSUE TITLE
Why dovecot lucene and not dovecot solr

### ISSUE THREAD

**Issue by pierreozoux** [mail-in-a-box/mailinabox#982]
I'm new to all this world of searching capabilities, so, sorry in advance if it is a stupid question.

Was just reading that http://wiki2.dovecot.org/Plugins/FTS
And it seems that the recommended search is with solr.

Is there any particular reason why choosing lucene and not solr?

Thanks for your time!

**Comment by JoshData** [comment]
Lucene is much much much easier to configure and maintain.

**Comment by pierreozoux** [comment]
I though the opposite: http://www.lucenetutorial.com/lucene-vs-solr.html

But I have no experience on that field, so I trust you.

Thanks for your answer!

**Comment by JoshData** [comment]
In this case it's the opposite because Dovecot is doing the driving and they've figured it out (to use the article's metaphor).
