### ISSUE TITLE
Incorrectly reading sshd_config for password-based login

### ISSUE THREAD

**Issue by majemedia** [mail-in-a-box/mailinabox#990]
I'm receiving this error in the admin:

> The SSH server on this machine permits password-based login. A more secure way to log in is using a public key. Add your SSH public key to $HOME/.ssh/authorized_keys, check that you can log in without a password, set the option 'PasswordAuthentication no' in /etc/ssh/sshd_config, and then restart the openssh via 'sudo service ssh restart'.

However the sshd_config is setup correctly:

<img width="359" alt="screenshot 2016-11-02 10 06 25" src="https://cloud.githubusercontent.com/assets/9761464/19934286/10952284-a0e4-11e6-9e75-d9460c0c360c.png">

the ssh service has also been restarted (not to mention that I recently did a reboot for security updates)

**Comment by josephbu** [comment]
Check permissions on _/etc/ssh/sshd_config_ as it's possible the check script can't read the file.

**Comment by majemedia** [comment]
That's not the problem. 644 on that one.

![screenshot 2016-11-03 08 17 20](https://cloud.githubusercontent.com/assets/9761464/19967391/0a091e60-a19e-11e6-91ae-f6b28cca4c36.png)

**Comment by yodax** [comment]
The deamon runs with root privs so it can read the file. Could you run:

```
grep "^PasswordAuthentication" /etc/ssh/sshd_config
```

**Comment by majemedia** [comment]
huh... I did... results showed up twice.

There was two entries in there.

The default one on line 52
A non-default one on line 94

This server was absolutely fresh 14.04.1 Digital Ocean droplet template... are there always two lines in there he wonders?

Yes... yes there are TWO PasswordAuthentication entries on default installs of Ubuntu 14.04.5 x64 on Digital Ocean at least.

**Comment by majemedia** [comment]
Opened support ticket with Digital Ocean

14.04.5 comes with OpenSSH_6.6.1p1 and according to that tag here:

https://github.com/openssh/openssh-portable/blob/V_6_6_P1/sshd_config

there are not two PasswordAuthentication lines... so DO is out of standard on that config.
