### ISSUE TITLE
Add Tasks To ownCloud?

### ISSUE THREAD

**Issue by IWriteThings** [mail-in-a-box/mailinabox#993]
The task management system for my phone works fine with my ownCloud. However, is there a way to add support for the GUI to ownCloud? It appears to just be a plugin. Can I add the support and open a pull request or does any one have comments on why having the tasks plugin might not be beneficial or appropriate for this project?

[The plugin is here.](https://apps.owncloud.com/content/show.php/Tasks?content=164356)

Please let me know if this seems like something we can or should integrate and I would happily work up the code to do it if you all think it would be allowed into the project.

**Comment by acs-ferreira** [comment]
I've recently submitted a PR for Notes, it will takes you about 5mn.
https://github.com/mail-in-a-box/mailinabox/pull/1000/files

IMO, this is useful too.

**Comment by IWriteThings** [comment]
Awesome. I will get to adding the tasks. Thanks for the example!

**Comment by JoshData** [comment]
Hi all. Thanks for your work here. The plan to is drop ownCloud from Mail-in-a-Box (see #514), however, and replace it with something simpler and more stable, so I won't be accepting PRs that increase ownCloud's functionality.

**Comment by acs-ferreira** [comment]
Ok @JoshData good to know.

**Comment by IWriteThings** [comment]
Thanks for the heads up! I will miss ownCloud. =(
