### ISSUE TITLE
v0.21 Release Candidate

### ISSUE THREAD

**Issue by JoshData** [mail-in-a-box/mailinabox#995]
`master` is now a release candidate for v0.21. Please try it and report back! :) Thanks.

**Comment by yodax** [comment]
I have installed it on two machines. One gave an error, I have created a PR for that here: https://github.com/mail-in-a-box/mailinabox/pull/996

I'll report back if there are any other things.

**Comment by acs-ferreira** [comment]
Testing here now too (upgrading from 0.20), no issues until now.

**Roundcube** could be upgraded to 1.2.2 (from 1.2.1):
https://github.com/roundcube/roundcubemail/releases/tag/1.2.2

**Comment by JoshData** [comment]
@acs-ferreira Will you create one or two new issues for updating Roundcube and ownCloud? We'll do it in the next update since I don't see any security issues.

**Comment by acs-ferreira** [comment]
@JoshData no problem, i create the issues.

**Comment by JoshData** [comment]
Thanks all for reviewing master. Since I'll be traveling through the end of the month, I am going to wait before making a release until I get back in case there are any problems.

**Comment by ma0ho** [comment]
I just updated as well and everything went very smooth. Thanks for your great work!

**Comment by ponychicken** [comment]
I did not review the code, but just upgraded and it worked fine.

**Comment by JoshData** [comment]
Thanks all.

https://discourse.mailinabox.email/t/version-0-21-is-posted/1678
