### ISSUE TITLE
Roundcube update

### ISSUE THREAD

**Issue by acs-ferreira** [mail-in-a-box/mailinabox#997]
Roundcube could be upgraded to 1.2.2 (from 1.2.1):
https://github.com/roundcube/roundcubemail/releases/tag/1.2.2

**Comment by joshuanasiatka** [comment]
Could this potentially be shifted over to Nextcloud 10.0.1 with their Mail plugin? Maybe have an option of Roundcube or Nextcloud Mail during setup?

**Comment by acs-ferreira** [comment]
See https://github.com/mail-in-a-box/mailinabox/issues/514

**Comment by amarsaudon** [comment]
Just an FYI, Roundcube <=1.2.2 has a remote execution vulnerability. 1.2.3 just released. https://blog.ripstech.com/2016/roundcube-command-execution-via-email/

**Comment by JoshData** [comment]
Thanks. It doesn't appear that we're vulnerable because this part doesn't apply to us:

> Roundcube must be configured to use PHP’s mail() function (by default, if no SMTP was specified 2 )

**Comment by amarsaudon** [comment]
Thanks for clarifying!

**Comment by JoshData** [comment]
fixed by cd59de6314824f646dddb6550cf9c55bfa223382
