### ISSUE TITLE
OwnCloud update

### ISSUE THREAD

**Issue by acs-ferreira** [mail-in-a-box/mailinabox#998]
OwnCloud upgrade to 9.1.2 instead of 9.1.1:
https://github.com/owncloud/core/releases/tag/v9.1.2

**Comment by joshuanasiatka** [comment]
Could this potentially be shifted over to Nextcloud 10.0.1?

**Comment by acs-ferreira** [comment]
See https://github.com/mail-in-a-box/mailinabox/issues/514
