### ISSUE TITLE
OwnCloud notes

### ISSUE THREAD

**Issue by acs-ferreira** [mail-in-a-box/mailinabox#999]
This PR provides users ability to write private notes using [OwnCloud Notes](https://github.com/owncloud/notes) app.

**Comment by JoshData** [comment]
Hi @acs-ferreira. Thanks for your work here. The plan to is drop ownCloud from Mail-in-a-Box (see #514), however, and replace it with something simpler and more stable, so I won't be accepting PRs that increase ownCloud's functionality.

**Comment by acs-ferreira** [comment]
No problem!
